objects/Account.object
<CustomObject>
    <fields>
        <fullName>WT_Type__c</fullName>
        <formula>CASE(RecordType.Name, &apos;Person Account (Prospect)&apos;, &apos;Prospect&apos;, &apos;Person Account (Customer)&apos;, &apos;Customer&apos; ,&apos; &apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Relationship_Group</fullName>
        <active>true</active>
        <label>Relationship Group</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>WT_Action__c</fullName>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>WT_Topic__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>401k</fullName>
                </value>
                <value>
                    <fullName>Access/Reset</fullName>
                </value>
                <value>
                    <fullName>Access Management</fullName>
                </value>
                <value>
                    <fullName>Accommodation</fullName>
                </value>
                <value>
                    <fullName>Accounts Payable</fullName>
                </value>
                <value>
                    <fullName>Badge Access</fullName>
                </value>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Business Cards</fullName>
                </value>
                <value>
                    <fullName>Cobra</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
                <value>
                    <fullName>Contingent Worker</fullName>
                </value>
                <value>
                    <fullName>Correction/Update</fullName>
                </value>
                <value>
                    <fullName>COVID</fullName>
                </value>
                <value>
                    <fullName>Deductions</fullName>
                </value>
                <value>
                    <fullName>Delegation</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Direct Deposit</fullName>
                </value>
                <value>
                    <fullName>Enrollment</fullName>
                </value>
                <value>
                    <fullName>Equifax</fullName>
                </value>
                <value>
                    <fullName>Equity</fullName>
                </value>
                <value>
                    <fullName>ESPP</fullName>
                </value>
                <value>
                    <fullName>Exception Form</fullName>
                </value>
                <value>
                    <fullName>Goals/Performance Management</fullName>
                </value>
                <value>
                    <fullName>Holiday</fullName>
                </value>
                <value>
                    <fullName>HR Partners</fullName>
                </value>
                <value>
                    <fullName>HSA/FSA</fullName>
                </value>
                <value>
                    <fullName>Insurance Cards</fullName>
                </value>
                <value>
                    <fullName>IT Support</fullName>
                </value>
                <value>
                    <fullName>Learning &amp; Development</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Case_Title__c</fullName>
        <description>Created as a part of DBSFCRM-417</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Customer_Name_CRM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Name (CRM)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cases (Customer Name (CRM))</relationshipLabel>
        <relationshipName>Cases1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Date_Received__c</fullName>
        <description>Created as a part of DBSFCRM-417</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Date  Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WT_Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Employee</label>
        <referenceTo>WT_Employee__c</referenceTo>
        <relationshipLabel>Cases (Employee)</relationshipLabel>
        <relationshipName>MYHR_Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Exception__c</fullName>
        <description>Created as a part of DDBSFCRM-417</description>
        <label>Exception</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complex Issue</fullName>
                </value>
                <value>
                    <fullName>Documentation</fullName>
                </value>
                <value>
                    <fullName>Received Late</fullName>
                </value>
                <value>
                    <fullName>With Legal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_HRCaseOwner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HR Case Owner</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only assign Case Owner as a HR User</errorMessage>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>contains</operation>
                <value>WT MyHR</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Cases2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Non_Customer_Complainant__c</fullName>
        <description>Created as a part of DBSFCRM-417</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Non-Customer Complainant</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Topic__c</fullName>
        <label>Topic</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Compensation</fullName>
                </value>
                <value>
                    <fullName>Employee Relations</fullName>
                </value>
                <value>
                    <fullName>Handbook</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
                <value>
                    <fullName>Payroll</fullName>
                </value>
                <value>
                    <fullName>Redirect</fullName>
                </value>
                <value>
                    <fullName>Time &amp; Absence</fullName>
                </value>
                <value>
                    <fullName>VOE</fullName>
                </value>
                <value>
                    <fullName>Workday</fullName>
                </value>
                <value>
                    <fullName>401k</fullName>
                    <isActive>false</isActive>
                    <label>401k</label>
                </value>
                <value>
                    <fullName>Accounts Payable</fullName>
                    <isActive>false</isActive>
                    <label>Accounts Payable</label>
                </value>
                <value>
                    <fullName>Benefit</fullName>
                    <isActive>false</isActive>
                    <label>Benefit</label>
                </value>
                <value>
                    <fullName>Doculivery</fullName>
                    <isActive>false</isActive>
                    <label>Doculivery</label>
                </value>
                <value>
                    <fullName>Fusion</fullName>
                    <isActive>false</isActive>
                    <label>Fusion</label>
                </value>
                <value>
                    <fullName>Kronos</fullName>
                    <isActive>false</isActive>
                    <label>Kronos</label>
                </value>
                <value>
                    <fullName>Learning &amp; Development</fullName>
                    <isActive>false</isActive>
                    <label>Learning &amp; Development</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>WT_MyHR</fullName>
        <active>true</active>
        <businessProcess>MyHR</businessProcess>
        <label>MyHR</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WT_Case_Note__c.object
<CustomObject>
    <description>Created as a part of DBSFCRM-593</description>
    <fields>
        <fullName>WT_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as a part of DBSFCRM-593</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Notes</relationshipLabel>
        <relationshipName>Case_Notes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Note_Category__c</fullName>
        <label>Note Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Called Customer</fullName>
                </value>
                <value>
                    <fullName>E-mailed Customer</fullName>
                </value>
                <value>
                    <fullName>Memo</fullName>
                </value>
                <value>
                    <fullName>Status Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Notes__c</fullName>
        <description>Created as a part of DBSFCRM-593</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Notes</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WT_Type__c</fullName>
        <description>Created as a part of DBSFCRM-593</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>WT_Note_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Resolving</fullName>
                </value>
                <value>
                    <fullName>Waiting for Customer</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Fulfillment</fullName>
                    <isActive>false</isActive>
                    <label>Fulfillment</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Note</label>
    <nameField>
        <displayFormat>Note-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WT_Employee__c.object
<CustomObject>
    <description>This object is used to store Wintrust Employee Details</description>
    <fields>
        <fullName>WT_Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Employee</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_CaseBeforeHandler_T.cls
/**
* -------------------------------------------------------------------------------------------------------------------------------------------------
* @Name         WT_CaseBeforeHandler_T
* @Author           Sivaranjani     <sivaranjani.d2@tcs.com.tcsdev> 
* @version      v1.0 
* @CreatedDate      11-26-2020
* @Author           Anitha Jaini     <ajaini@wintrust.com> 
* @version      v1.1 
* @ModifiedDate    12-18-2021
*
* @Author           Francis Xavier     <fxavierd@wintrust.com> 
* @version      v1.2 
* @ModifiedDate    04-20-2022
* ---------------------------------------------------------------------------------------------------------------------------------------------------
* @Description 
* Class is used as test class for WT_caseBeforeHandle,WT_CaseTrigger 
* ---------------------------------------------------------------------------------------------------------------------------------------------------
* FUNCTIONAL TEST LOGIC
* 1- runCaseStatusChangeValidation() 
*   > use to run test validation on status change  checkCaseValidation() function on WT_caseBeforeHandler, for fulfilled and Waiting for Customer status 
* changes on case. 
* 
* ----------------------------------------------------------------------------------------------------------------------------------------------------
**/
@isTest
public class WT_CaseBeforeHandler_T 
{
    @isTest
    static void setResolutionTargetTest()
    {
        RecordType complianceRecordType= [select id, developerName, Name from RecordType where Name='Compliance Complaint' and SobjectType='Case'];
        WT_DataFactory.createRequiredCustomSetting();
        
        User userRecord1 = WT_DataFactory.createUser('WT Funds');
        insert userRecord1; 
        
        // SGE-9 Create Account
        Account acc = new Account(
            Name = 'TestAcc',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName()
            .get('Relationship_Group')
            .getRecordTypeId()
        );
        insert acc;
        Contact con = new Contact(
            LastName = 'TestContact',
            AccountId = acc.Id
        );
        insert con;
        
        Case caseRecord = new Case();
        caseRecord.RecordTypeId=complianceRecordType.Id;
        caseRecord.WT_Exception__c='Complex Issue';
        caseRecord.WT_Date_Received__c=Date.Today();
        caseRecord.WT_Case_Title__c='Test Case';
        caseRecord.WT_Non_Customer_Complainant__c='Test';  
        caseRecord.OwnerId = userRecord1.Id;  
        caseRecord.AccountId = acc.Id;
        caseRecord.WT_Customer_Name_CRM__c = acc.Id; 
        insert caseRecord;
        
        WT_Employee__c wtEmp = new WT_Employee__c(
            WT_Email__c = 'test@wt.com'
        );
        insert wtEmp;
        
        // Femi: for my hr case 
        Case caseRecord2 = new Case();
        caseRecord2.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get('WT_MyHR').getRecordTypeId();
        caseRecord2.WT_Exception__c='Complex Issue';
        caseRecord.WT_Date_Received__c=Date.Today();
        caseRecord2.WT_Case_Title__c='Test Case';
        caseRecord2.WT_Non_Customer_Complainant__c='Test';  
        caseRecord2.OwnerId = userRecord1.Id;  
        caseRecord2.AccountId = acc.Id;
        caseRecord2.Origin = 'Email';
        caseRecord2.SuppliedEmail = 'test@wt.com';
        //caseRecord2.WT_HRCaseOwner__c = userinfo.getUserId();
        insert caseRecord2;
        
        caseRecord.WT_Exception__c='';
        //added SGE-9
        ContentVersion contentVersion_1 = WT_TestSetupHelper.getContentVersion(caseRecord.Id);
        insert contentVersion_1;
        User userRecord2 = WT_DataFactory.createUser('WT Retail');
        insert userRecord2; 
        system.assertnotEquals(userRecord1.username, userRecord2.username);      
        Test.startTest();
        caseRecord.OwnerId = userRecord2.Id;  
        update caseRecord;
        WT_Case_Note__c newCaseNote = new WT_Case_Note__c();
        newCaseNote.WT_Case__c = caseRecord.id;
        newCaseNote.WT_Note_Category__c = 'Status Update';
        newCaseNote.WT_Type__c ='Resolving';
        newCaseNote.WT_Notes__c='test';
        insert newCaseNote;
        
        Test.stopTest();
    } 
    @isTest
    static void testValidations()
    { 
        RecordType complianceRecordType= [select id, developerName, Name from RecordType where Name='Compliance Complaint' and SobjectType='Case'];
        WT_DataFactory.createRequiredCustomSetting();
        Case caseRecord = new Case();
        caseRecord.RecordTypeId=complianceRecordType.Id;
        caseRecord.WT_Exception__c='Complex Issue';
        caseRecord.WT_Date_Received__c=Date.Today();
        caseRecord.WT_Case_Title__c='Test Case';
        caseRecord.WT_Non_Customer_Complainant__c='Test'; 
        caseRecord.Status = 'Pending';
        insert caseRecord;
        CaseRecord.Status = 'Resolved';
        try
        {
            update caseRecord; 
        }
        catch(DmlException e)
        {
            System.debug(e.getMessage());
            System.assertEquals('Update failed. First exception on row 0 with id '+ caseRecord.id +'; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, '+System.Label.WT_Error_on_Case_Resolved+': []',e.getMessage());
        }
        WT_Case_Note__c newCaseNote = new WT_Case_Note__c();
        newCaseNote.WT_Case__c = caseRecord.id;
        newCaseNote.WT_Note_Category__c = 'Status Update';
        newCaseNote.WT_Type__c ='Resolving';
        newCaseNote.WT_Notes__c='test';
        insert newCaseNote;
        //update caseRecord;
    }
    @isTest
    static void testValidations2()
    { 
        RecordType complianceRecordType= [select id, developerName, Name from RecordType where Name='Compliance Complaint' and SobjectType='Case'];
        WT_DataFactory.createRequiredCustomSetting();
        Case caseRecord = new Case();
        caseRecord.RecordTypeId=complianceRecordType.Id;
        caseRecord.WT_Exception__c='Complex Issue';
        caseRecord.WT_Date_Received__c=Date.Today();
        caseRecord.WT_Case_Title__c='Test Case';
        caseRecord.WT_Non_Customer_Complainant__c='Test'; 
        caseRecord.Status = 'Pending';
        insert caseRecord;
        CaseRecord.Status = 'Cancelled';
        try
        {
            update caseRecord; 
        }
        catch(DmlException e)
        {
            System.debug(e.getMessage());
            System.assertEquals('Update failed. First exception on row 0 with id '+ caseRecord.id +'; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, '+System.Label.WT_Error_on_Cancellation+': []',e.getMessage());
        }
        WT_Case_Note__c newCaseNote = new WT_Case_Note__c();
        newCaseNote.WT_Case__c = caseRecord.id;
        newCaseNote.WT_Note_Category__c = 'Status Update';
        newCaseNote.WT_Type__c ='Cancellation';
        newCaseNote.WT_Notes__c='test';
        insert newCaseNote;
        update caseRecord;
    }
    
    @isTest
    static void testValidations3()
    {   
        User user = WT_DataFactory.createUser('WT MyHR');
        insert user;
        
        RecordType complianceRecordType= [select id, developerName, Name from RecordType where Name='myHR' and SobjectType='Case'];
        WT_DataFactory.createRequiredCustomSetting();
        Case caseRecord = new Case();
        caseRecord.RecordTypeId=complianceRecordType.Id;
        caseRecord.WT_Exception__c='Complex Issue';
        caseRecord.WT_Date_Received__c=Date.Today();
        caseRecord.WT_Case_Title__c='Test Case';
        caseRecord.WT_Non_Customer_Complainant__c='Test'; 
        caseRecord.Status = 'Pending';
        caseRecord.WT_Topic__c = 'Benefits';
        caseRecord.WT_Action__c = 'Medical';
        system.runAs(user){
            insert caseRecord;
        }
        caseRecord.WT_HRCaseOwner__c = user.Id;
        caseRecord.WT_Topic__c = 'Misc';
        caseRecord.WT_Action__c = 'Misc';
        caseRecord.OwnerId = user.Id;
        try
        {
            system.runAs(user){
                update caseRecord; 
            }
        }
        catch(DmlException e)
        {
            System.debug(e.getMessage());
            System.assertEquals('Update failed. First exception on row 0 with id '+ caseRecord.id +'; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, '+System.Label.WT_Error_on_Cancellation+': []',e.getMessage());
        }
    }  
}