objects/Account.object
<CustomObject>
    <fields>
        <fullName>WT_Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Group Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>FinServ__RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Leads</relationshipLabel>
        <relationshipName>RelatedLeads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Group Referrals</relationshipLabel>
        <relationshipName>RG_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Group Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WT_RelationshipGroup_Relation__c.object
<CustomObject>
    <description>A relationship between relationship account and person or business account.</description>
    <fields>
        <fullName>WT_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Group Relations (Account)</relationshipLabel>
        <relationshipName>Account_Account_Relations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WT_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WT_RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>RelatedTOAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship Group Relation</label>
    <nameField>
        <displayFormat>AAR-{000000000}</displayFormat>
        <label>Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Group Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/WT_RelationshipGroupRelationHandler.cls
/**
* ----------------------------------------------------------------------------------------------------------------
* @Name             WT_RelationshipGroupRelationHandler
* @Author           Swaminathan E   <SEzhumal@wintrust.com>
* @Version          v1.0
* @CreatedDate      29-07-2021
* @UsedBy           WT_RelationshipGroup_Relation__c Object
* -----------------------------------------------------------------------------------------------------------------
* @Description
* This is handler class for WT_RelationshipGroup_Relation__c trigger.
*
* This handles all the Rollup child records logic of the WT_RelationshipGroup_Relation__c trigger.
* ------------------------------------------------------------------------------------------------------------------
**/
public class WT_RelationshipGroupRelationHandler extends TriggerHandler 
{
    private List<WT_RelationshipGroup_Relation__c> listNewAccountAccount = new List<WT_RelationshipGroup_Relation__c>();
    private List<WT_RelationshipGroup_Relation__c> listOldAccountAccount = new List<WT_RelationshipGroup_Relation__c>();
    //constructor     
    public WT_RelationshipGroupRelationHandler()
    {
        if(trigger.isUpdate)
        {
            this.listNewAccountAccount = (List<WT_RelationshipGroup_Relation__c>) Trigger.new;
        }
        if(trigger.isInsert)
        {
            this.listNewAccountAccount = (List<WT_RelationshipGroup_Relation__c>) Trigger.new;            
        }
        if(trigger.isDelete)
        {
            this.listOldAccountAccount = (List<WT_RelationshipGroup_Relation__c>) Trigger.old;
        }
    }
    public override void afterInsert()
    { 
        calculateRollupRecords(listNewAccountAccount);
    }
    public override void afterUpdate()
    {    
        reCalculateRollupRecords(listNewAccountAccount);
    }
    public override void afterDelete()
    {  
        removeRollupRecords(listOldAccountAccount);
    } 
/**
*-------------------------------------------------------------------------------------------------------------- 
* @Description
* This method is used to calculate Rollup of child records
* --------------------------------------------------------------------------------------------------------------
* @Param  listOldAccountAccount    Map of old Account
* @Return void                         none
*--------------------------------------------------------------------------------------------------------------
**/
    public void removeRollupRecords(List<WT_RelationshipGroup_Relation__c> listOldAccountAccount)
    {
        List<SObject> listOfSObject = new List<SObject>();
        Set<Id> setAccountId = new Set<Id>();
        for(WT_RelationshipGroup_Relation__c acountAccountRecord: listOldAccountAccount)
        {
            setAccountId.add(acountAccountRecord.WT_RelatedAccount__c);
        }
        if(!setAccountId.isEmpty())
        {
            List<Opportunity> listOpportunity = [SELECT Id, WT_Relationship_Group__c, AccountId FROM Opportunity WHERE AccountId IN :setAccountId ];
            for(Opportunity opportunityRecord :listOpportunity)
            {
                opportunityRecord.WT_Relationship_Group__c = Null;
            }
            List<FinServ__FinancialAccount__c> listFinancialAccount = [SELECT Id, WT_Relationship_Group__c, FinServ__PrimaryOwner__c FROM FinServ__FinancialAccount__c WHERE FinServ__PrimaryOwner__c IN :setAccountId ];
            for(FinServ__FinancialAccount__c financialRecord: listFinancialAccount)
            {  
                financialRecord.WT_Relationship_Group__c = Null;
            }
            List<Lead> listReferral = [SELECT Id, FinServ__RelatedAccount__c FROM Lead WHERE FinServ__RelatedAccount__c IN :setAccountId ];
            for(Lead leadRecord: listReferral)
            {
                leadRecord.WT_Relationship_Group__c = Null;
            }
            List<Event> listEvent = [SELECT Id, WT_Relationship_Group__c, WhatId FROM Event WHERE WhatId IN :setAccountId ];
            for(Event eventRecord: listEvent)
            {
                eventRecord.WT_Relationship_Group__c = Null;
            }
            List<Task> listTask = [SELECT Id, WT_Relationship_Group__c, WhatId FROM Task WHERE WhatId IN :setAccountId ];
            for(Task taskRecord: listTask)
            {
                 taskRecord.WT_Relationship_Group__c = Null;
            }
            List<ActionPlan> listActionPlan = [SELECT Id, TargetId, WT_Relationship_Group__c FROM ActionPlan WHERE TargetId IN :setAccountId];
            for(ActionPlan actionPlanRecord: listActionPlan)
            {
                if(actionPlanRecord.TargetId.getsObjectType() == Account.sObjectType)
                {
                    actionPlanRecord.WT_Relationship_Group__c = Null;
                }
            }
            listOfSObject.addAll(listOpportunity);
            listOfSObject.addAll(listFinancialAccount);
            listOfSObject.addAll(listReferral);
            listOfSObject.addAll(listEvent);
            listOfSObject.addAll(listTask);
            listOfSObject.addAll(listActionPlan);
            List<Database.SaveResult> listUpdateResult = Database.update(listOfSObject, false);
            for (Database.SaveResult result : listUpdateResult) 
            {
                if (!result.isSuccess())
                {
                    for (Database.Error error : result.getErrors())
                    {
                        System.debug('Record Id: '+result.getId()+'Error: '+ error.getMessage());
                    }
                }    
            }
        }
    }
/**
* --------------------------------------------------------------------------------------------------------------
* @Description
* This method is used to calculate Rollup of child records
* --------------------------------------------------------------------------------------------------------------
* @Param  listNewAccountAccount    Map of new Account
* @Return void                         none
*--------------------------------------------------------------------------------------------------------------
**/
    public void calculateRollupRecords(List<WT_RelationshipGroup_Relation__c> listNewAccountAccount)
    {
        List<SObject> listOfSObject = new List<SObject>();
        Map<Id,Id> mapAccountId = new Map<Id,Id>();
        for(WT_RelationshipGroup_Relation__c acountAccountRecord: listNewAccountAccount)
        {
            if(acountAccountRecord.WT_Active__c)
            {
                mapAccountId.put(acountAccountRecord.WT_RelatedAccount__c,acountAccountRecord.WT_Account__c);
            }
        }
        if(!mapAccountId.isEmpty())
        {
            List<Opportunity> listOpportunity = [SELECT Id, WT_Relationship_Group__c, AccountId FROM Opportunity WHERE AccountId IN :mapAccountId.keySet() ];
            for(Opportunity opportunityRecord :listOpportunity)
            {
                opportunityRecord.WT_Relationship_Group__c = mapAccountId.get(opportunityRecord.AccountId);
            }
            List<FinServ__FinancialAccount__c> listFinancialAccount = [SELECT Id, WT_Relationship_Group__c, FinServ__PrimaryOwner__c FROM FinServ__FinancialAccount__c WHERE FinServ__PrimaryOwner__c IN :mapAccountId.keySet() ];
            for(FinServ__FinancialAccount__c financialRecord: listFinancialAccount)
            {  
                financialRecord.WT_Relationship_Group__c = mapAccountId.get(financialRecord.FinServ__PrimaryOwner__c);
            }
            List<Lead> listReferral = [SELECT Id , FinServ__RelatedAccount__c FROM Lead WHERE FinServ__RelatedAccount__c IN :mapAccountId.keySet() ];
            for(Lead leadRecord: listReferral)
            {
                leadRecord.WT_Relationship_Group__c = mapAccountId.get(leadRecord.FinServ__RelatedAccount__c);
            }
            List<Event> listEvent = [SELECT Id, WT_Relationship_Group__c, WhatId FROM Event WHERE WhatId IN :mapAccountId.keySet() ];
            for(Event eventRecord: listEvent)
            {
                  eventRecord.WT_Relationship_Group__c = mapAccountId.get(eventRecord.WhatId);
            }
            List<Task> listTask = [SELECT Id, WT_Relationship_Group__c, WhatId FROM Task WHERE WhatId IN :mapAccountId.keySet() ];
            for(Task taskRecord: listTask)
            {
                  taskRecord.WT_Relationship_Group__c = mapAccountId.get(taskRecord.WhatId);
            }
            List<ActionPlan> listActionPlan = [SELECT Id, TargetId, WT_Relationship_Group__c FROM ActionPlan WHERE TargetId IN :mapAccountId.keySet()];
            for(ActionPlan actionPlanRecord: listActionPlan)
            {
                if(actionPlanRecord.TargetId.getsObjectType() == Account.sObjectType)
                {
                    actionPlanRecord.WT_Relationship_Group__c = mapAccountId.get(actionPlanRecord.TargetId);
                }
            }
            listOfSObject.addAll(listOpportunity);
            listOfSObject.addAll(listFinancialAccount);
            listOfSObject.addAll(listReferral);
            listOfSObject.addAll(listEvent);
            listOfSObject.addAll(listTask);
            listOfSObject.addAll(listActionPlan);
            List<Database.SaveResult> listUpdateResult = Database.update(listOfSObject, false);
            for (Database.SaveResult result : listUpdateResult) 
            {
                if (!result.isSuccess())
                {
                    for (Database.Error error : result.getErrors())
                    {
                        System.debug('Record Id: '+result.getId()+'Error: '+ error.getMessage());
                    }
                }
            }
        }
    }
    /**
*-------------------------------------------------------------------------------------------------------------- 
* @Description
* This method is used to recalculate Rollup of child records
* --------------------------------------------------------------------------------------------------------------
* @Param  listNewAccountAccount    Map of new Account
* @Return void                         none
*--------------------------------------------------------------------------------------------------------------
**/
    public void reCalculateRollupRecords(List<WT_RelationshipGroup_Relation__c> listNewAccountAccount)
    {
        List<SObject> listOfSObject = new List<SObject>();
        Set<Id> setActiveRelatedId = new Set<Id>();
        Map<Id,Id> mapAccountId = new Map<Id,Id>();
        for(WT_RelationshipGroup_Relation__c acountAccountRecord: listNewAccountAccount)
        {
            if(acountAccountRecord.WT_Active__c)
            {
                setActiveRelatedId.add(acountAccountRecord.WT_RelatedAccount__c);
            }
            mapAccountId.put(acountAccountRecord.WT_RelatedAccount__c,acountAccountRecord.WT_Account__c);  
        }
        if(!mapAccountId.isEmpty())
        {
            List<Opportunity> listOpportunity = [SELECT Id, WT_Relationship_Group__c, AccountId FROM Opportunity WHERE AccountId IN :mapAccountId.keySet() ];
            for(Opportunity opportunityRecord :listOpportunity)
            {
                if(setActiveRelatedId.contains(opportunityRecord.AccountId))
                {
                    opportunityRecord.WT_Relationship_Group__c = mapAccountId.get(opportunityRecord.AccountId);
                }
                else
                {
                    opportunityRecord.WT_Relationship_Group__c = Null; 
                }
            }
            List<FinServ__FinancialAccount__c> listFinancialAccount = [SELECT Id, WT_Relationship_Group__c, FinServ__PrimaryOwner__c FROM FinServ__FinancialAccount__c WHERE FinServ__PrimaryOwner__c IN :mapAccountId.keySet() ];
            for(FinServ__FinancialAccount__c financialRecord: listFinancialAccount)
            {  
                if(setActiveRelatedId.contains(financialRecord.FinServ__PrimaryOwner__c))
                {
                    financialRecord.WT_Relationship_Group__c = mapAccountId.get(financialRecord.FinServ__PrimaryOwner__c);
                }
                else
                {
                    financialRecord.WT_Relationship_Group__c = Null; 
                }
            }
            List<Lead> listReferral = [SELECT Id, FinServ__RelatedAccount__c FROM Lead WHERE FinServ__RelatedAccount__c IN :mapAccountId.keySet()  ];
            for(Lead leadRecord: listReferral)
            {
                if(setActiveRelatedId.contains(leadRecord.FinServ__RelatedAccount__c))
                {
                    leadRecord.WT_Relationship_Group__c = mapAccountId.get(leadRecord.FinServ__RelatedAccount__c);
                }
                else
                {
                    leadRecord.WT_Relationship_Group__c = Null; 
                }
            }
            List<Event> listEvent = [SELECT Id, WT_Relationship_Group__c, WhatId FROM Event WHERE WhatId IN :mapAccountId.keySet()  ];
            for(Event eventRecord: listEvent)
            {
                if(setActiveRelatedId.contains(eventRecord.WhatId))
                {
                    eventRecord.WT_Relationship_Group__c = mapAccountId.get(eventRecord.WhatId);
                }
                else
                {
                    eventRecord.WT_Relationship_Group__c = Null;
                }   
            }
            List<Task> listTask = [SELECT Id, WT_Relationship_Group__c, WhatId FROM Task WHERE WhatId IN :mapAccountId.keySet()  ];
            for(Task taskRecord: listTask)
            {
                if(setActiveRelatedId.contains(taskRecord.WhatId))
                {
                    taskRecord.WT_Relationship_Group__c = mapAccountId.get(taskRecord.WhatId);
                }
                else
                {
                    taskRecord.WT_Relationship_Group__c = Null; 
                }     
            }
            List<ActionPlan> listActionPlan = [SELECT Id, TargetId, WT_Relationship_Group__c FROM ActionPlan WHERE TargetId IN :mapAccountId.keySet()];
            for(ActionPlan actionPlanRecord: listActionPlan)
            {
                if(actionPlanRecord.TargetId != null && actionPlanRecord.TargetId.getsObjectType() == Account.sObjectType)
                {
                    if(setActiveRelatedId.contains(actionPlanRecord.TargetId))
                    {
                        actionPlanRecord.WT_Relationship_Group__c = mapAccountId.get(actionPlanRecord.TargetId); 
                    }
                    else
                    {
                        actionPlanRecord.WT_Relationship_Group__c = Null;
                    }
                }
            }
            listOfSObject.addAll(listOpportunity);
            listOfSObject.addAll(listFinancialAccount);
            listOfSObject.addAll(listReferral);
            listOfSObject.addAll(listEvent);
            listOfSObject.addAll(listTask);
            listOfSObject.addAll(listActionPlan);
            List<Database.SaveResult> listUpdateResult = Database.update(listOfSObject, false);
            for (Database.SaveResult result : listUpdateResult) 
            {
                if (!result.isSuccess())
                {
                    for (Database.Error error : result.getErrors())
                    {
                        System.debug('Record Id: '+result.getId()+'Error: '+ error.getMessage());
                    }
                }
            }
        }
    }
}