objects/Account.object
<CustomObject>
    <fields>
        <fullName>WT_Primary_Contact_Name_Banker_Entered__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Contact Name (Banker Entered)</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WT_CI_Funding_History__c.object
<CustomObject>
    <fields>
        <fullName>WT_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CI Funding Histories (Account)</relationshipLabel>
        <relationshipName>CI_Funding_Histories1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WT_Date_of_Payment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date of Payment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WT_Split_Payment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Split Payment</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CI Funding History</label>
    <nameField>
        <displayFormat>CI-{0000000000}</displayFormat>
        <label>CI Funding History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CI Funding Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/WT_CIFundingController_T.cls
@isTest
public class WT_CIFundingController_T 
{
    static testMethod void testMethod1()
    {
        Account newAccount = new Account();
        newAccount.Name = 'Test';
        newAccount.WT_Primary_Contact_Name_Banker_Entered__c ='Test';
        insert newAccount;
        WT_CI_Funding_History__c FundingHistoryRecord = new WT_CI_Funding_History__c();
        FundingHistoryRecord.WT_Account__c = newAccount.Id;
        FundingHistoryRecord.WT_Split_Payment__c = 'test';
        FundingHistoryRecord.WT_Date_of_Payment__c =system.today();
        insert FundingHistoryRecord;
        WT_CIFundingController.getFundingList(newAccount.Id);
    } 
}