objects/Account.object
<CustomObject>
    <fields>
        <fullName>WT_Annual_Revenue_DNB__c</fullName>
        <label>Annual Revenue (DNB)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>WT_Annual_Revenue_InfoUSA__c</fullName>
        <label>Annual Revenue (InfoUSA)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>WT_DUNS_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>DUNS Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Employees_InfoUSA__c</fullName>
        <label>Employees - InfoUSA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WT_InfoUSA_Prospect_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>InfoUSA Prospect ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Primary_Contact_Name_DNB__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Contact Name (DNB)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Primary_Contact_Name_InfoUSA__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Contact Name (InfoUSA)</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Primary_Email_DNB__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Email (DNB)</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>WT_Primary_Email_InfoUSA__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Email  (InfoUSA)</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>BusinessAccount_Prospect</fullName>
        <active>true</active>
        <label>Business Account (Prospect)</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WT_Third_Party_Data__c.object
<CustomObject>
    <fields>
        <fullName>WT_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Third Party Data</relationshipLabel>
        <relationshipName>Third_Party_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Contact_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contact Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Country_Region__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Country/Region</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_D_U_N_S_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>D-U-N-S® Number</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>WT_Employees_Single_Site__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Employees (Single Site)</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_INFOUSAID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Info USA ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WT_PHONE__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Phone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Primary_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WT_Primary_City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary City</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Primary_Zip_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Zip Code</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Primary_state__c</fullName>
        <label>Primary state</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>WI</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Revenue_USD__c</fullName>
        <label>Revenue (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Third Party Data</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Third Party Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Third Party Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_ThirdPartyDataToAccountMatchUtility_T.cls
@isTest
public class WT_ThirdPartyDataToAccountMatchUtility_T 
{
    @TestSetup
    static void setup()
    {
        Id businessAccountProspectRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BusinessAccount_Prospect').getRecordTypeId();
        List<Account> listAccountToInsert = New List<Account>();
        
        Account newAccount = new Account();
        newAccount.Name = 'Test 1';
        newAccount.BillingStreet = '123 W Main St Suite 200';
        newAccount.BillingState = 'UT';
        newAccount.BillingCity = 'Salt Lake City';
        newAccount.BillingCountry = 'United States';
        newAccount.BillingPostalCode = '84096';
        newAccount.Phone = '1112223333';
        newAccount.RecordTypeId = businessAccountProspectRecordTypeId;
        listAccountToInsert.add(newAccount);
        
        Account newInfoUsaAccount = new Account();
        newInfoUsaAccount.Name = 'Test InfoUSAId';
        newInfoUsaAccount.BillingStreet = '123 InfoUsa';
        newInfoUsaAccount.BillingState = 'UT';
        newInfoUsaAccount.BillingCity = 'Salt Lake City';
        newInfoUsaAccount.BillingCountry = 'United States';
        newInfoUsaAccount.BillingPostalCode = '84096';
        newInfoUsaAccount.Phone = '1112223333';
        newInfoUsaAccount.RecordTypeId = businessAccountProspectRecordTypeId;
        newInfoUsaAccount.WT_InfoUSA_Prospect_ID__c = '96358';
        listAccountToInsert.add(newInfoUsaAccount);
        
        Account newDunsAccount = new Account();
        newDunsAccount.Name = 'Test Duns';
        newDunsAccount.BillingStreet = '123 InfoUsa';
        newDunsAccount.BillingState = 'UT';
        newDunsAccount.BillingCity = 'Salt Lake City';
        newDunsAccount.BillingCountry = 'United States';
        newDunsAccount.BillingPostalCode = '84096';
        newDunsAccount.Phone = '1112223333';
        newDunsAccount.RecordTypeId = businessAccountProspectRecordTypeId;
        newDunsAccount.WT_DUNS_Number__c = '562785';
        listAccountToInsert.add(newDunsAccount);
        
        Id[] arraySearchResults= new Id[3];
        arraySearchResults[0] = listAccountToInsert[0].Id;
        arraySearchResults[1] = listAccountToInsert[1].Id;
        arraySearchResults[2] = listAccountToInsert[2].Id;
        Test.setFixedSearchResults(arraySearchResults);
        
        insert listAccountToInsert;
    }
    
    @isTest
    static void testInfoUSAIdMatch()
    {
        Test.startTest();
        List<WT_Third_Party_Data__c> listThirdPartyDataToInsert = new List<WT_Third_Party_Data__c>();
        WT_Third_Party_Data__c newThirdPartyData = new WT_Third_Party_Data__c();
        newThirdPartyData.Name = 'Test';
        newThirdPartyData.WT_Primary_Address__c = '123 W Main St';
        newThirdPartyData.WT_Primary_City__c = 'Salt Lake City';
        newThirdPartyData.WT_Primary_state__c = 'UT';
        newThirdPartyData.WT_Primary_Zip_Code__c = '84096';
        newThirdPartyData.WT_Country_Region__c = 'United States';
        newThirdPartyData.WT_INFOUSAID__c = '96358';
        newThirdPartyData.WT_Employees_Single_Site__c = '888';
        newThirdPartyData.WT_Revenue_USD__c = 5000;
        listThirdPartyDataToInsert.add(newThirdPartyData);
        
        insert listThirdPartyDataToInsert;
        
        Account relatedAccount = [SELECT Id,
                                  WT_Annual_Revenue_InfoUSA__c,
                                  WT_Employees_InfoUSA__c,
                                  WT_Primary_Contact_Name_InfoUSA__c,
                                  WT_Primary_Email_InfoUSA__c,
                                  WT_InfoUSA_Prospect_ID__c
                                  FROM Account
                                  WHERE WT_InfoUSA_Prospect_ID__c = '96358'
                                  LIMIT 1];
        
        System.assertEquals(newThirdPartyData.WT_Revenue_USD__c, relatedAccount.WT_Annual_Revenue_InfoUSA__c);
        System.assertEquals(Integer.valueOf(newThirdPartyData.WT_Employees_Single_Site__c), relatedAccount.WT_Employees_InfoUSA__c);
        System.assertEquals(newThirdPartyData.WT_INFOUSAID__c, relatedAccount.WT_InfoUSA_Prospect_ID__c);
        System.assertEquals(newThirdPartyData.WT_Contact_Name__c, relatedAccount.WT_Primary_Contact_Name_InfoUSA__c);
        System.assertEquals(newThirdPartyData.WT_Email__c, relatedAccount.WT_Primary_Email_InfoUSA__c);
        
        WT_Third_Party_Data__c relatedThirdPartyData = [SELECT Id,
                                                        WT_Account__c
                                                        FROM WT_Third_Party_Data__c
                                                        LIMIT 1];
        
        System.assertEquals(relatedAccount.Id, relatedThirdPartyData.WT_Account__c);
        
        Test.stopTest();
    }
    
    @isTest
    static void testDunsIdMatch()
    {
        Test.startTest();
        List<WT_Third_Party_Data__c> listThirdPartyDataToInsert = new List<WT_Third_Party_Data__c>();
        WT_Third_Party_Data__c newThirdPartyData = new WT_Third_Party_Data__c();
        newThirdPartyData.Name = 'Test';
        newThirdPartyData.WT_Primary_Address__c = '123 W Main St';
        newThirdPartyData.WT_Primary_City__c = 'Salt Lake City';
        newThirdPartyData.WT_Primary_state__c = 'UT';
        newThirdPartyData.WT_Primary_Zip_Code__c = '84096';
        newThirdPartyData.WT_Country_Region__c = 'United States';
        newThirdPartyData.WT_D_U_N_S_Number__c = '562785';
        newThirdPartyData.WT_Employees_Single_Site__c = '888';
        newThirdPartyData.WT_Revenue_USD__c = 6000;
        listThirdPartyDataToInsert.add(newThirdPartyData);
        
        insert listThirdPartyDataToInsert;
        
        Account relatedAccount = [SELECT Id,
                                  WT_Annual_Revenue_DNB__c,
                                  WT_Primary_Contact_Name_DNB__c,
                                  WT_Primary_Email_DNB__c,
                                  WT_DUNS_Number__c
                                  FROM Account
                                  WHERE WT_DUNS_Number__c = '562785'
                                  LIMIT 1];
        
        System.assertEquals(newThirdPartyData.WT_Revenue_USD__c, relatedAccount.WT_Annual_Revenue_DNB__c);
        System.assertEquals(newThirdPartyData.WT_D_U_N_S_Number__c, relatedAccount.WT_DUNS_Number__c);
        System.assertEquals(newThirdPartyData.WT_Contact_Name__c, relatedAccount.WT_Primary_Contact_Name_DNB__c);
        System.assertEquals(newThirdPartyData.WT_Email__c, relatedAccount.WT_Primary_Email_DNB__c);
        
        WT_Third_Party_Data__c relatedThirdPartyData = [SELECT Id,
                                                        WT_Account__c
                                                        FROM WT_Third_Party_Data__c
                                                        LIMIT 1];
        
        System.assertEquals(relatedAccount.Id, relatedThirdPartyData.WT_Account__c);
        
        Test.stopTest();
    }
    
    @isTest
    static void testAddressWithName85PercentMatch()
    {
        Test.startTest();
        Account relatedAccount = [SELECT Id,
                                  WT_Annual_Revenue_InfoUSA__c,
                                  WT_Employees_InfoUSA__c,
                                  WT_Primary_Contact_Name_InfoUSA__c,
                                  WT_Primary_Email_InfoUSA__c,
                                  WT_InfoUSA_Prospect_ID__c
                                  FROM Account
                                  LIMIT 1];
        
        Id[] arraySearchResults= new Id[1];
        arraySearchResults[0] = relatedAccount.Id;
        Test.setFixedSearchResults(arraySearchResults);
        
        List<WT_Third_Party_Data__c> listThirdPartyDataToInsert = new List<WT_Third_Party_Data__c>();
        WT_Third_Party_Data__c newThirdPartyData = new WT_Third_Party_Data__c();
        newThirdPartyData.Name = 'Test';
        newThirdPartyData.WT_Primary_Address__c = '123 W Main St Suite 200';
        newThirdPartyData.WT_Primary_City__c = 'Salt Lake City';
        newThirdPartyData.WT_Primary_state__c = 'UT';
        newThirdPartyData.WT_Primary_Zip_Code__c = '84096';
        newThirdPartyData.WT_Country_Region__c = 'United States';
        newThirdPartyData.WT_INFOUSAID__c = '1234';
        newThirdPartyData.WT_Employees_Single_Site__c = '504';
        newThirdPartyData.WT_Revenue_USD__c = 500;
        listThirdPartyDataToInsert.add(newThirdPartyData);
        
        insert listThirdPartyDataToInsert;
        
        relatedAccount = [SELECT Id,
                          WT_Annual_Revenue_InfoUSA__c,
                          WT_Employees_InfoUSA__c,
                          WT_Primary_Contact_Name_InfoUSA__c,
                          WT_Primary_Email_InfoUSA__c,
                          WT_InfoUSA_Prospect_ID__c
                          FROM Account
                          LIMIT 1];
        
        System.assertEquals(newThirdPartyData.WT_Revenue_USD__c, relatedAccount.WT_Annual_Revenue_InfoUSA__c);
        System.assertEquals(Integer.valueOf(newThirdPartyData.WT_Employees_Single_Site__c), relatedAccount.WT_Employees_InfoUSA__c);
        System.assertEquals(newThirdPartyData.WT_INFOUSAID__c, relatedAccount.WT_InfoUSA_Prospect_ID__c);
        System.assertEquals(newThirdPartyData.WT_Contact_Name__c, relatedAccount.WT_Primary_Contact_Name_InfoUSA__c);
        System.assertEquals(newThirdPartyData.WT_Email__c, relatedAccount.WT_Primary_Email_InfoUSA__c);
        
        WT_Third_Party_Data__c relatedThirdPartyData = [SELECT Id,
                                                        WT_Account__c
                                                        FROM WT_Third_Party_Data__c
                                                        LIMIT 1];
        
        System.assertEquals(relatedAccount.Id, relatedThirdPartyData.WT_Account__c);
        
        Test.stopTest();
    }
    
    @isTest
    static void testAddressWithName85PercentAddress85PercentAndPhoneMatch()
    {
        Test.startTest();
        Account relatedAccount = [SELECT Id,
                                  WT_Annual_Revenue_InfoUSA__c,
                                  WT_Employees_InfoUSA__c,
                                  WT_Primary_Contact_Name_InfoUSA__c,
                                  WT_Primary_Email_InfoUSA__c,
                                  WT_InfoUSA_Prospect_ID__c
                                  FROM Account
                                  LIMIT 1];
        
        Id[] arraySearchResults= new Id[1];
        arraySearchResults[0] = relatedAccount.Id;
        Test.setFixedSearchResults(arraySearchResults);
        
        List<WT_Third_Party_Data__c> listThirdPartyDataToInsert = new List<WT_Third_Party_Data__c>();
        WT_Third_Party_Data__c newThirdPartyData = new WT_Third_Party_Data__c();
        newThirdPartyData.Name = 'Test 1';
        newThirdPartyData.WT_Primary_Address__c = '123 W Main St Suite 20';
        newThirdPartyData.WT_Primary_City__c = 'Salt Lake City';
        newThirdPartyData.WT_Primary_state__c = 'UT';
        newThirdPartyData.WT_Primary_Zip_Code__c = '84096';
        newThirdPartyData.WT_Country_Region__c = 'United States';
        newThirdPartyData.WT_PHONE__c = '1112223333';
        newThirdPartyData.WT_INFOUSAID__c = '1234';
        newThirdPartyData.WT_Employees_Single_Site__c = '504';
        listThirdPartyDataToInsert.add(newThirdPartyData);
        
        insert listThirdPartyDataToInsert;
        
        relatedAccount = [SELECT Id,
                          WT_Annual_Revenue_InfoUSA__c,
                          WT_Employees_InfoUSA__c,
                          WT_Primary_Contact_Name_InfoUSA__c,
                          WT_Primary_Email_InfoUSA__c,
                          WT_InfoUSA_Prospect_ID__c
                          FROM Account
                          LIMIT 1];
        
        System.assertEquals(newThirdPartyData.WT_Revenue_USD__c, relatedAccount.WT_Annual_Revenue_InfoUSA__c);
        System.assertEquals(Integer.valueOf(newThirdPartyData.WT_Employees_Single_Site__c), relatedAccount.WT_Employees_InfoUSA__c);
        System.assertEquals(newThirdPartyData.WT_INFOUSAID__c, relatedAccount.WT_InfoUSA_Prospect_ID__c);
        System.assertEquals(newThirdPartyData.WT_Contact_Name__c, relatedAccount.WT_Primary_Contact_Name_InfoUSA__c);
        System.assertEquals(newThirdPartyData.WT_Email__c, relatedAccount.WT_Primary_Email_InfoUSA__c);
        
        WT_Third_Party_Data__c relatedThirdPartyData = [SELECT Id,
                                                        WT_Account__c
                                                        FROM WT_Third_Party_Data__c
                                                        LIMIT 1];
        
        System.assertEquals(relatedAccount.Id, relatedThirdPartyData.WT_Account__c);
        Test.stopTest();
    }
    
    @isTest
    static void testNoMatchInfoUsa()
    {
        Test.startTest();
        List<WT_Third_Party_Data__c> listThirdPartyDataToInsert = new List<WT_Third_Party_Data__c>();
        WT_Third_Party_Data__c newThirdPartyData = new WT_Third_Party_Data__c();
        newThirdPartyData.Name = 'Test123';
        newThirdPartyData.WT_Primary_Address__c = '123 W Main St';
        newThirdPartyData.WT_Primary_City__c = 'Salt Lake City';
        newThirdPartyData.WT_Primary_state__c = 'UT';
        newThirdPartyData.WT_Primary_Zip_Code__c = '84096';
        newThirdPartyData.WT_Country_Region__c = 'United States';
        newThirdPartyData.WT_PHONE__c = '1112223333';
        newThirdPartyData.WT_INFOUSAID__c = '1234';
        newThirdPartyData.WT_Employees_Single_Site__c = '504';
        listThirdPartyDataToInsert.add(newThirdPartyData);
        
        insert listThirdPartyDataToInsert;
        
        Account relatedAccount = [SELECT Id,
                                  WT_Annual_Revenue_InfoUSA__c,
                                  WT_Employees_InfoUSA__c,
                                  WT_Primary_Contact_Name_InfoUSA__c,
                                  WT_Primary_Email_InfoUSA__c,
                                  WT_InfoUSA_Prospect_ID__c
                                  FROM Account
                                  WHERE WT_InfoUSA_Prospect_ID__c = :newThirdPartyData.WT_INFOUSAID__c
                                  LIMIT 1];
        
        System.assertEquals(newThirdPartyData.WT_Revenue_USD__c, relatedAccount.WT_Annual_Revenue_InfoUSA__c);
        System.assertEquals(Integer.valueOf(newThirdPartyData.WT_Employees_Single_Site__c), relatedAccount.WT_Employees_InfoUSA__c);
        System.assertEquals(newThirdPartyData.WT_INFOUSAID__c, relatedAccount.WT_InfoUSA_Prospect_ID__c);
        System.assertEquals(newThirdPartyData.WT_Contact_Name__c, relatedAccount.WT_Primary_Contact_Name_InfoUSA__c);
        System.assertEquals(newThirdPartyData.WT_Email__c, relatedAccount.WT_Primary_Email_InfoUSA__c);
        
        WT_Third_Party_Data__c relatedThirdPartyData = [SELECT Id,
                                                        WT_Account__c
                                                        FROM WT_Third_Party_Data__c
                                                        LIMIT 1];
        
        System.assertEquals(relatedAccount.Id, relatedThirdPartyData.WT_Account__c);
        Test.stopTest();
    }
    
    @isTest
    static void testNoMatchDuns()
    {
        Test.startTest();
        List<WT_Third_Party_Data__c> listThirdPartyDataToInsert = new List<WT_Third_Party_Data__c>();
        WT_Third_Party_Data__c newThirdPartyData = new WT_Third_Party_Data__c();
        newThirdPartyData.WT_Primary_Address__c = '123 W Main St';
        newThirdPartyData.WT_Primary_City__c = 'Salt Lake City';
        newThirdPartyData.WT_Primary_state__c = 'UT';
        newThirdPartyData.WT_Primary_Zip_Code__c = '84096';
        newThirdPartyData.WT_Country_Region__c = 'United States';
        newThirdPartyData.WT_PHONE__c = '1112223333';
        newThirdPartyData.WT_D_U_N_S_Number__c = '1234';
        newThirdPartyData.WT_Employees_Single_Site__c = '504';
        listThirdPartyDataToInsert.add(newThirdPartyData);
        
        insert listThirdPartyDataToInsert;
        
        Account relatedAccount = [SELECT Id,
                                  WT_Annual_Revenue_InfoUSA__c,
                                  WT_Employees_InfoUSA__c,
                                  WT_Primary_Contact_Name_InfoUSA__c,
                                  WT_Primary_Email_InfoUSA__c,
                                  WT_DUNS_Number__c
                                  FROM Account
                                  WHERE WT_DUNS_Number__c = :newThirdPartyData.WT_D_U_N_S_Number__c
                                  LIMIT 1];
        
        System.assertEquals(newThirdPartyData.WT_Revenue_USD__c, relatedAccount.WT_Annual_Revenue_InfoUSA__c);
        System.assertEquals(newThirdPartyData.WT_D_U_N_S_Number__c, relatedAccount.WT_DUNS_Number__c);
        System.assertEquals(newThirdPartyData.WT_Contact_Name__c, relatedAccount.WT_Primary_Contact_Name_InfoUSA__c);
        System.assertEquals(newThirdPartyData.WT_Email__c, relatedAccount.WT_Primary_Email_InfoUSA__c);
        
        WT_Third_Party_Data__c relatedThirdPartyData = [SELECT Id,
                                                        WT_Account__c
                                                        FROM WT_Third_Party_Data__c
                                                        LIMIT 1];
        
        System.assertEquals(relatedAccount.Id, relatedThirdPartyData.WT_Account__c);
        Test.stopTest();
    }
    
    @isTest
    static void testStringCompare()
    {
        Test.startTest();
        Boolean areMatch1 = WT_ThirdPartyDataToAccountMatchUtility.GetAreStrings85PercentFuzzyMatch('', '');
        System.assertEquals(true, areMatch1);
        
        Boolean areMatch2 = WT_ThirdPartyDataToAccountMatchUtility.GetAreStrings85PercentFuzzyMatch('Test', 'Test');
        System.assertEquals(true, areMatch2);
        
        Boolean areMatch3 = WT_ThirdPartyDataToAccountMatchUtility.GetAreStrings85PercentFuzzyMatch('Test', 'Tes');
        System.assertEquals(false, areMatch3);
        
        Boolean areMatch4 = WT_ThirdPartyDataToAccountMatchUtility.GetAreStrings85PercentFuzzyMatch('TestTest', 'TestTes');
        System.assertEquals(true, areMatch4);
        Test.stopTest();
    }
}