objects/Account.object
<CustomObject>
    <fields>
        <fullName>WT_Calls_Made_Last_Year__c</fullName>
        <label>Number of calls made last year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WT_Calls_Made_This_Year__c</fullName>
        <label>Number of calls made this year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WT_Classification__c</fullName>
        <description>Created as part of DBSFCRM-649. This captures classification of account.</description>
        <label>Classification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>C</fullName>
                    <label>C = Customer</label>
                </value>
                <value>
                    <fullName>C1</fullName>
                    <label>C1 = Top Priority Customer</label>
                </value>
                <value>
                    <fullName>C2</fullName>
                    <label>C2 = Medium Priority Customer</label>
                </value>
                <value>
                    <fullName>C3</fullName>
                    <label>C3 = Established Customer</label>
                </value>
                <value>
                    <fullName>C4</fullName>
                    <label>C4 = Customer - PPP Onboarding</label>
                </value>
                <value>
                    <fullName>COI</fullName>
                    <label>COI = Center of Influence</label>
                </value>
                <value>
                    <fullName>NQ</fullName>
                    <label>NQ = Middle Market (Revenue $10MM to $260MM)</label>
                </value>
                <value>
                    <fullName>NQ0</fullName>
                    <label>NQ0 = Companies with Unknown Revenue</label>
                </value>
                <value>
                    <fullName>NQBB</fullName>
                    <label>NQBB = Companies with Revenue $1.00MM to $9.99MM</label>
                </value>
                <value>
                    <fullName>NQSB</fullName>
                    <label>NQSB = Companies with Revenue under $1MM</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <label>P1 = Proposing within 6 months/Top Prospect</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <label>P2 = Proposing in 6-12 months</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <label>P3 = Proposing outside 12 months</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <label>P4 = Other</label>
                </value>
                <value>
                    <fullName>P5</fullName>
                    <label>P5 = PPP Lead</label>
                </value>
                <value>
                    <fullName>X1</fullName>
                    <label>X1 = EdFAC</label>
                </value>
                <value>
                    <fullName>X2</fullName>
                    <label>X2 = Bankrupt/Out of Business</label>
                </value>
                <value>
                    <fullName>X3</fullName>
                    <label>X3 = Industry Excluded</label>
                </value>
                <value>
                    <fullName>X4</fullName>
                    <label>X4 = Subsidiary</label>
                </value>
                <value>
                    <fullName>X5</fullName>
                    <label>X5 = Potential Duplicate</label>
                </value>
                <value>
                    <fullName>X6</fullName>
                    <label>X6 = Other</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>BusinessAccount_Customer</fullName>
        <active>true</active>
        <label>Business Account (Customer)</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>WT_Line_of_Business__c</fullName>
        <description>Created as a part of DBFSCRM-707</description>
        <label>Line of Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ABL</fullName>
                </value>
                <value>
                    <fullName>Agricultural Lending</fullName>
                </value>
                <value>
                    <fullName>Business Administrator</fullName>
                </value>
                <value>
                    <fullName>Business Banking</fullName>
                </value>
                <value>
                    <fullName>CCPA</fullName>
                </value>
                <value>
                    <fullName>Charter Leadership</fullName>
                </value>
                <value>
                    <fullName>Commercial Support</fullName>
                </value>
                <value>
                    <fullName>Community Advantage</fullName>
                </value>
                <value>
                    <fullName>Community Banking</fullName>
                </value>
                <value>
                    <fullName>Community Impact</fullName>
                </value>
                <value>
                    <fullName>Complaint Management</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Contact Center</fullName>
                </value>
                <value>
                    <fullName>CRE</fullName>
                </value>
                <value>
                    <fullName>Deposit Application</fullName>
                </value>
                <value>
                    <fullName>First Insurance</fullName>
                </value>
                <value>
                    <fullName>Franchise</fullName>
                </value>
                <value>
                    <fullName>Funds Group</fullName>
                </value>
                <value>
                    <fullName>Government Funds</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>IT Administrator</fullName>
                </value>
                <value>
                    <fullName>Leasing</fullName>
                </value>
                <value>
                    <fullName>MAD - Managed Assets Division</fullName>
                </value>
                <value>
                    <fullName>Middle Market</fullName>
                </value>
                <value>
                    <fullName>MyHR</fullName>
                </value>
                <value>
                    <fullName>Private Client Group</fullName>
                </value>
                <value>
                    <fullName>Professional Practice Group</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>SBA</fullName>
                </value>
                <value>
                    <fullName>Support Role</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WT_Client_Coverage__c.object
<CustomObject>
    <label>Client Coverage</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Client Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Client Coverages</pluralLabel>
    <recordTypes>
        <fullName>WT_Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_BatchUpdateCallsOnAccount_T.cls
/**
* --------------------------------------------------------------------------------------------------------------
* @Name             WT_BatchUpdateCallsOnAccount_T
* @Author           Vamsi Pulikallu <vpulikallu@wintrust.com>
* @ModifiedBy       Vamsi Pulikallu <vpulikallu@wintrust.com>
* @Version          v1.0
* @CreatedDate      31 Jan 2022
* --------------------------------------------------------------------------------------------------------------
* @Description
* This is test class for after handler class for WT_BatchUpdateCallsOnAccount.
* ---------------------------------------------------------------------------------------------------------------------------------------------------
* FUNCTIONAL TEST LOGIC
* 1- callsUpdate() 
*   > used to test the updation of calls made in a year fields on Account
* ----------------------------------------------------------------------------------------------------------------------------------------------------
**/
@isTest
public class WT_BatchUpdateCallsOnAccount_T 
{
    @isTest
    public static void coveredNA()
    {
        id businessCustomerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BusinessAccount_Customer').getRecordTypeId();
        id accountCoverageRecordTypeId = Schema.SObjectType.WT_Client_Coverage__c.getRecordTypeInfosByDeveloperName().get('WT_Account').getRecordTypeId();
        test.startTest();
        User userRecord = WT_DataFactory.createUser('System Administrator'); 
        userRecord.WT_Line_of_Business__c = 'Middle Market';
        insert userRecord;
        Account accountRecord = new Account(Name = 'Test12',WT_Calls_Made_This_Year__c =2,type = 'Customer',RecordTypeId = businessCustomerRecordTypeId,WT_Classification__c = 'C2', BillingStreet='11', BillingCity='11',BillingState='Some',BillingPostalCode='0011001',BillingCountry='India');
        insert accountRecord;
        Account accountRecord1 = new Account(Name = 'Test12',WT_Calls_Made_Last_Year__c =null,type = 'Customer',RecordTypeId = businessCustomerRecordTypeId,WT_Classification__c = 'C2', BillingStreet='11', BillingCity='11',BillingState='Some',BillingPostalCode='0011001',BillingCountry='India');
        insert accountRecord1;
        system.runAs(userRecord)
        {
            Database.executeBatch(new WT_BatchUpdateCallsOnAccount());
        }   
        System.assertEquals(2, [select count() from Account Where recordTypeId = :businessCustomerRecordTypeId AND isdeleted = false]);    
        test.stopTest();
    }
    
    @isTest
    public static void schedulerTest()
    {
        String cronexpression = '0 0 0 15 3 ? *';
        Test.startTest();
        String jobId = System.schedule('ScheduleBatchApexClass',  cronexpression, new WT_BatchUpdateCallsOnAccountSchedule());
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
        System.assertEquals(cronexpression, ct.CronExpression);
        System.assertEquals(0, ct.TimesTriggered);
        Test.stopTest();
    }
}