objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>BusinessAccount_Customer</fullName>
        <active>true</active>
        <label>Business Account (Customer)</label>
    </recordTypes>
    <recordTypes>
        <fullName>BusinessAccount_Prospect</fullName>
        <active>true</active>
        <label>Business Account (Prospect)</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Activity.object
<CustomObject>
    <fields>
        <fullName>WT_Activity_Type__c</fullName>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Appointment</fullName>
                </value>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Walk-in</fullName>
                </value>
                <value>
                    <fullName>Annual Review Appointment</fullName>
                </value>
                <value>
                    <fullName>Annual Review Phone Call</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Contact_Type__c</fullName>
        <description>Created as part of DBSFCRM-464</description>
        <label>Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting</fullName>
                </value>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
                <value>
                    <fullName>Networking Event</fullName>
                </value>
                <value>
                    <fullName>Sponsored Event</fullName>
                </value>
                <value>
                    <fullName>COI/Referral</fullName>
                </value>
                <value>
                    <fullName>CRA</fullName>
                </value>
                <value>
                    <fullName>Bank At Work</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Organizer_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Outcome_Notes__c</fullName>
        <description>Created as a part of DBSFCRM-464</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Outcome Notes**</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WT_Status__c</fullName>
        <description>Created as a part of DBSFCRM-464</description>
        <label>Event Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_TM_Activity_Lkp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TM Activity</label>
        <referenceTo>WT_Activity_Extension__c</referenceTo>
        <relationshipLabel>Activities</relationshipLabel>
        <relationshipName>Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event.object
<CustomObject>
    <recordTypes>
        <fullName>WT_Annual_Review</fullName>
        <active>true</active>
        <description>Created as part of DBSFCRM-155.</description>
        <label>Annual Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_CRA_Event</fullName>
        <active>true</active>
        <label>CRA Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_Wintrust_Event</fullName>
        <active>true</active>
        <label>Wintrust Event</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>WT_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed/Won</fullName>
                </value>
                <value>
                    <fullName>Closed/Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>WT_CRA_Call</fullName>
        <active>true</active>
        <label>CRA Call</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_Standard_Call</fullName>
        <active>true</active>
        <label>Standard Call</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_WFG_Call</fullName>
        <active>true</active>
        <label>WFG Call</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_Wintrust_Task</fullName>
        <active>true</active>
        <label>Wintrust Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WT_Activity_Extension__c.object
<CustomObject>
    <description>To store TM Call Records</description>
    <fields>
        <fullName>WT_Activity_Type__c</fullName>
        <description>Created as apart of DBSFCRM-852</description>
        <label>Activity Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Appointment</fullName>
                </value>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>Letter</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_EventId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>EventId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Outcome_Notes__c</fullName>
        <description>Created as apart of DBSFCRM-852</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Outcome Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WT_Status__c</fullName>
        <description>Created as apart of DBSFCRM-852</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_TaskId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>TaskId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Activity Extension</label>
    <nameField>
        <displayFormat>TM Call-{0000}</displayFormat>
        <label>Activity TM Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Extensions</pluralLabel>
    <recordTypes>
        <fullName>TM_Call</fullName>
        <active>true</active>
        <description>Created as part of 852</description>
        <label>TM Call</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_Annual_Review</fullName>
        <active>true</active>
        <description>Created as part of DBSFCRM-155.</description>
        <label>Annual Review</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_CRA_Call</fullName>
        <active>true</active>
        <label>CRA Call</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_CRA_Event</fullName>
        <active>true</active>
        <label>CRA Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_Event</fullName>
        <active>true</active>
        <label>Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_Standard_Call</fullName>
        <active>true</active>
        <label>Standard Call</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_Task</fullName>
        <active>true</active>
        <label>Task</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_WFG_Call</fullName>
        <active>true</active>
        <description>Created as part of DBFCRM 1332</description>
        <label>WFG Call</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_Wintrust_Event</fullName>
        <active>true</active>
        <label>Wintrust Event</label>
    </recordTypes>
    <recordTypes>
        <fullName>WT_Wintrust_Task</fullName>
        <active>true</active>
        <label>Wintrust Task</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WT_Display_Activity_RecordType__mdt.object
<CustomObject>
    <fields>
        <fullName>ObjectRecordType__c</fullName>
        <label>Object Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Person</fullName>
                    <default>true</default>
                    <label>Person</label>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Display Activity RecordType</label>
    <pluralLabel>Display Activity RecordTypes</pluralLabel>
</CustomObject>

classes/WT_ActivityTimeLineController.cls
/* --------------------------------------------------------------------------------------------------------------
* @Name             WT_ActivityTimeLineController
* @Author           Vamshi Papisetty
* @ModifiedBy       Vamshi Papisetty    <vpapiset@wintrust.com>
* @Version          v2.0
* @CreatedDate      05/24/2022          
* Code Coverage: WT_ActivitytimeLineController_T
* The is Apex Controller for Activity History LWC Component
* @Changes v2.0
*Adds list of recordtype for Person And Business Accounts--listRecord
* task of <recordtype> based on Account<recordtype>--includes Person And Business accounts 
* event  of <recordtype> based on Account<recordtype>--includes Person And Business accounts 
* Line -89  tasks/events<recordtypes> for  Opportunities (Conditions set to negative as create action is false
* Line-176 Mapping TaskId from Task to TaskId(field) of Activity Extension to get Outcome notes from ActivityExtension Object
* Line 184 Mapping eventId from Event to EventId(field) from  Activity Extension to get Outcome notes from ActivityExtension Object 
* Sort or display order of recordtypes based on Custom Meta data object Display Activity RecordTypes
* 05/24/2022-------------------------------------------------------------------------------------------------------
* Updated 8/25/2022--------------------------------------------------------------------------------------------**/
public with sharing class WT_ActivityTimeLineController
{
 @AuraEnabled(cacheable=true)
    Public static List<listRecordTypes> getRecordTypesInfo(Id recId)
    {
       //get recordtypes for Task and Event
        Schema.DescribeSObjectResult taskRecords = Task.SObjectType.getDescribe();
        Schema.DescribeSObjectResult eventRecords = Event.SObjectType.getDescribe();
        //list for storing the values
        List<listRecordTypes> listBusinessRecordTypes = new List<listRecordTypes>();
        List<listRecordTypes> listPersonRecordTypes  = new List<listRecordTypes>();
        List<listRecordTypes> listOpportunityRecordTypes = new List<listRecordTypes>();
        List<listRecordTypes> listSortedRecordTestType = new List<listRecordTypes>();

        //Business Logic Start
        Map<String,WT_Display_Activity_RecordType__mdt> mapBusinesstaskSortOrderMetaData = new Map<String,WT_Display_Activity_RecordType__mdt>();
        Map<Integer,WT_Display_Activity_RecordType__mdt> mapBusinessIntegerSortOrderMetaData = new Map<Integer,WT_Display_Activity_RecordType__mdt>();
        Map<String,listRecordTypes> mapBusinessTaskSortedRecordTestType = new Map<String,listRecordTypes>();
        
        List<WT_Display_Activity_RecordType__mdt> listBusinessSortRecordsMetadata =[Select Id, DeveloperName,ObjectRecordType__c,Sort_Order__c, Label from WT_Display_Activity_RecordType__mdt where ObjectRecordType__c ='Business'];
        for(WT_Display_Activity_RecordType__mdt sortMetadataRecords : listBusinessSortRecordsMetadata)
        {
            mapBusinesstaskSortOrderMetaData.put(sortMetadataRecords.Label,sortMetadataRecords);   
            mapBusinessIntegerSortOrderMetaData.put(Integer.valueOf(sortMetadataRecords.Sort_Order__c),sortMetadataRecords);
        }
        //Business Logic end

        //Person Logic Start
        Map<String,WT_Display_Activity_RecordType__mdt> mapPersonTaskSortOrderMetaData = new Map<String,WT_Display_Activity_RecordType__mdt>();
        Map<Integer,WT_Display_Activity_RecordType__mdt> mapPersonIntegerSortOrderMetaData = new Map<Integer,WT_Display_Activity_RecordType__mdt>();
        Map<String,listRecordTypes> mapPersonTaskSortRecordType = new Map<String,listRecordTypes>();
        
        List<WT_Display_Activity_RecordType__mdt> listPersonSortRecordsMetadata =[Select Id, DeveloperName,ObjectRecordType__c,Sort_Order__c, Label from WT_Display_Activity_RecordType__mdt where ObjectRecordType__c ='Person'];
        for(WT_Display_Activity_RecordType__mdt sortMetadataRecords : listPersonSortRecordsMetadata)
        {
            mapPersonTaskSortOrderMetaData.put(sortMetadataRecords.Label,sortMetadataRecords);   
            mapPersonIntegerSortOrderMetaData.put(Integer.valueOf(sortMetadataRecords.Sort_Order__c),sortMetadataRecords);
        }
        //Business Logic end

        Id recordId = recId;
        //Getting Object name
        String objName = String.valueOf(recordId.getSobjectType());
        if(objName == 'Account' || objName == 'account')
        {
         Account accountRecord  = [Select Id ,RecordType.DeveloperName FROM Account WHERE Id =:recordId];
           //recordtypes for Person account
            if(accountRecord.RecordType.DeveloperName =='PersonAccount_Customer'||accountRecord.RecordType.DeveloperName =='PersonAccount_Prospect')
            {
                for(Schema.RecordTypeInfo recordType: taskRecords.getRecordTypeInfos())
                {
                    //adding these record types for Person Account --basing standard activity/global actions
                    if(recordType.DeveloperName == 'WT_Standard_Call'||
                      recordType.DeveloperName == 'WT_Wintrust_Task'||
                      recordType.DeveloperName =='WT_CRA_Call')
                       {
                        listRecordTypes recType = new listRecordTypes();
                        recType.name = recordType.Name;
                        recType.id =  recordType.RecordTypeId;
                        recType.isTask = true;
                        listPersonRecordTypes.add(recType);
                        mapPersonTaskSortRecordType.put(recType.Name,recType);
                       }
                }
                for(Schema.RecordTypeInfo recordType: eventRecords.getRecordTypeInfos())
                {
                    if(recordType.DeveloperName == 'WT_Wintrust_Event')
                    {
                        listRecordTypes recType = new listRecordTypes();
                        recType.name = recordType.Name;
                        recType.id = recordType.RecordTypeId;
                        recType.isTask = false;
                        listPersonRecordTypes.add(recType);
                        mapPersonTaskSortRecordType.put(recType.Name,recType);
                    }
                }
                List<Integer> listSortOrder = new List<Integer>();
                for(listRecordTypes recType : listPersonRecordTypes)
                {                   
                    if(mapPersonTaskSortOrderMetaData.containsKey(recType.Name))
                    {                        
                        listSortOrder.add(Integer.valueOf(mapPersonTaskSortOrderMetaData.get(recType.Name).Sort_Order__c));                             
                    }
                }             
                listSortOrder.sort();
                for(Integer sortOrder : listSortOrder)
                {   
                    if(mapPersonIntegerSortOrderMetaData.containsKey(sortOrder))
                    {                        
                        listSortedRecordTestType.add(mapPersonTaskSortRecordType.get(mapPersonIntegerSortOrderMetaData.get(sortOrder).Label));                           
                    }
                }   
            }
            //adding these record types for Business Account --basing standard activity/global actions
            else if(accountRecord.RecordType.DeveloperName =='BusinessAccount_Customer'||accountRecord.RecordType.DeveloperName =='BusinessAccount_Prospect')
            {
                for(Schema.RecordTypeInfo recordType: taskRecords.getRecordTypeInfos())
                {
                    if(recordType.isAvailable())
                    {
                    if(recordType.DeveloperName == 'WT_Wintrust_Task'||recordType.DeveloperName == 'WT_CRA_Call'||
                           recordType.DeveloperName == 'WT_WFG_Call'||recordType.DeveloperName =='TM_Call'||
                           recordType.DeveloperName == 'WT_Standard_Call') 
                    {
                    listRecordTypes recType  = new listRecordTypes();
                     recType.name = recordType.Name;
                     recType.id = recordType.RecordTypeId;
                     recType.isTask = true;
                     listBusinessRecordTypes.add(recType);
                     mapBusinessTaskSortedRecordTestType.put(recType.Name,recType); //map to store rec name with recordtype details
                    }
                }
                }
                for(Schema.RecordTypeInfo recordType: eventRecords.getRecordTypeInfos())
                {
                    if(recordType.DeveloperName == 'WT_Wintrust_Event'||recordType.DeveloperName =='WT_Annual_Review'||
                         recordType.DeveloperName =='WT_CRA_Event') 
                   {
                    listRecordTypes recType = new listRecordTypes();
                    recType.name = recordType.Name;
                    recType.id = recordType.RecordTypeId;
                    recType.isTask =false;
                    listBusinessRecordTypes.add(recType);
                    mapBusinessTaskSortedRecordTestType.put(recType.Name,recType);
                   }   
                }
                List<Integer> listSortOrder = new List<Integer>();
                for(listRecordTypes recType : listBusinessRecordTypes)
                {                   
                    if(mapBusinesstaskSortOrderMetaData.containsKey(recType.Name))
                    {                        
                        listSortOrder.add(Integer.valueOf(mapBusinesstaskSortOrderMetaData.get(recType.Name).Sort_Order__c));                             
                    }
                }             
                listSortOrder.sort();
                for(Integer sortOrder : listSortOrder)
                {   
                    if(mapBusinessIntegerSortOrderMetaData.containsKey(sortOrder))
                    {                        
                        listSortedRecordTestType.add(mapBusinessTaskSortedRecordTestType.get(mapBusinessIntegerSortOrderMetaData.get(sortOrder).Label));                           
                    }
                }                
            }
        } 
        //getting recordtype for opportunity and also for tasks and events
        else if(objName == 'Opportunity'|| objName == 'opportunity')
       {
        Opportunity opportunityRecord = [select Id, RecordType.DeveloperName from Opportunity where Id =:recordId];
        if(opportunityRecord.RecordType.DeveloperName == 'Master')
         {
            for(Schema.RecordTypeInfo recordType : taskRecords.getRecordTypeInfos())
            {
            if(recordType.DeveloperName != 'Master'|| recordType.DeveloperName != 'ClientAssociateTask'||
                recordType.DeveloperName != 'WT_Task'|| recordType.DeveloperName != 'AdvisorTask'|| recordType.DeveloperName != 'WT_CRA_Call'||
                recordType.DeveloperName != 'TM_Call'||recordType.DeveloperName != 'WT_Standard_Call'||
                recordType.DeveloperName != 'WT_WFG_Call'|| recordType.DeveloperName != 'WT_Wintrust_Task')
            {
                listRecordTypes recType = new listRecordTypes();
                recType.name = recordType.Name;
                recType.isTask = true;  
                recType.id = recordType.RecordTypeId;
                listOpportunityRecordTypes.add(recType);
            }
            }
            for(Schema.RecordTypeInfo recordType : eventRecords.getRecordTypeInfos())
            {
                    if(recordType.DeveloperName != 'Master'||recordType.DeveloperName != 'WT_Event'||
                       recordType.DeveloperName != 'ClientAssociateEvent'|| recordType.DeveloperName != 'AdvisorEvent'|| 
                       recordType.DeveloperName != 'WT_Annual_Review'||
                       recordType.DeveloperName != 'WT_CRA_Event' || 
                recordType.DeveloperName != 'WT_Wintrust_Event' )
                {
                    listRecordTypes recType = new listRecordTypes();
                    recType.name = recordType.Name;
                    recType.isTask = false;
                    recType.id = recordType.RecordTypeId;
                    listOpportunityRecordTypes.add(recType);
                }
            } 
         }
        }
                   return listSortedRecordTestType; 
    }
    //Retreiving Test Task and event Record types(replicating page layouts for Global action layouts)
    @AuraEnabled(cacheable=true)
    Public static List<listRecordTypes> getTestRecordTestTypeInfo()
    {
        Schema.DescribeSObjectResult taskRecords = Task.SObjectType.getDescribe();
        Schema.DescribeSObjectResult eventRecords = Event.SObjectType.getDescribe();
        List<listRecordTypes> listRecordTestType = new List<listRecordTypes>();
        for(Schema.RecordTypeInfo recordType: taskRecords.getRecordTypeInfos())
        {
            //adding these record types test for navigating to page layout/global action
            if(recordType.DeveloperName.contains('_New'))
            {
                listRecordTypes recType = new listRecordTypes();
                recType.name = recordType.Name;
                recType.id =  recordType.RecordTypeId;
                listRecordTestType.add(recType);
            }
        }
        for(Schema.RecordTypeInfo recordType: eventRecords.getRecordTypeInfos())
        {
            //adding these record types test for navigating to page layout/global action
            if(recordType.DeveloperName.contains('_New') && recordType.isAvailable())
            {
                listRecordTypes recType = new listRecordTypes();
                recType.name = recordType.Name;
                recType.id =  recordType.RecordTypeId;
                listRecordTestType.add(recType);
            }
        }
        return listRecordTestType;
    }   
     @AuraEnabled(cacheable=true)
     Public static activity getActivites(Id recId)
      {
        String objName = String.valueOf(recId.getSobjectType());
        Set<Id> whatIds = new Set<Id>();
        //Set of account Id's for maps to have it associated with account
        whatIds.add(recId);
        if(objName  == 'Account')
        { 
            for(opportunity Opp : [Select Id FROM Opportunity WHERE accountId = :recId])
            {  
                whatIds.add(Opp.Id);
            }
        }        
            //Task values and Event maps
        Map<Id, Task> mapTaskIdAndTask = new Map<Id,Task>([Select Id,Subject,WT_TM_Activity_Lkp__c,WT_TM_Activity_Lkp__r.WT_Outcome_Notes__c,
                                                           ActivityDate,WT_Activity_Type__c,RecordType.Name,OwnerId,Owner.Name,
                                                           Status FROM Task WHERE whatId IN :whatIds]);
        Map<Id,Event> mapEventIdAndEvent = new Map<Id,Event>([Select Id,StartDateTime,Subject,WT_TM_Activity_Lkp__c,WT_Activity_Type__c,
                                                              WT_TM_Activity_Lkp__r.WT_Outcome_Notes__c, WhoId, Who.Name,WT_Organizer_User__r.Name,
                                                              WT_Organizer_User__c, WT_Contact_Type__c,IsChild,ActivityDate,
                                                              ActivityDateTime,EndDateTime,OwnerId,
                                                              RecordType.Name,Owner.Name,WT_Status__c FROM Event 
                                                              WHERE whatId IN : whatIds
                                                              AND IsChild=FALSE]);
        Map<String, WT_Activity_Extension__c> MapTaskIdActivityExtension = new Map<String, WT_Activity_Extension__c>();                
                //search for taskIds and eventIds in Actextn
        for(WT_Activity_Extension__c actExt : [Select Id, WT_TaskId__c,WT_EventId__c ,
                                               WT_Outcome_Notes__c FROM WT_Activity_Extension__c  
                                                WHERE WT_TaskId__c IN :mapTaskIdAndTask.keySet() OR WT_EventId__c IN :mapEventIdAndEvent.keySet()])
        {          
            if(actExt.WT_TaskId__c != null)
            {
                MapTaskIdActivityExtension.put(actExt.WT_TaskId__c,actExt);
            }
            if(actExt.WT_EventId__c != null)
            {
                MapTaskIdActivityExtension.put(actExt.WT_EventId__c,actExt);
            }
        }
        //temporary task and event lists to map it to activities
        List<Task> tempTskList = new List<Task>();
        List<Event> tempEvtList = new List<Event>();
       //checking for key=value pair
            for(Task tsk : mapTaskIdAndTask.values())
            {
                if(MapTaskIdActivityExtension.containsKey(tsk.Id))
                {
                    tsk.WT_Outcome_Notes__c = MapTaskIdActivityExtension.get(tsk.Id).WT_Outcome_Notes__c;
                }
                tempTskList.add(tsk);
            }
            for(Event evt : mapEventIdAndEvent.values())
            {
                if(MapTaskIdActivityExtension.containsKey(evt.Id))
                {
                evt.WT_Outcome_Notes__c = MapTaskIdActivityExtension.get(evt.Id).WT_Outcome_Notes__c;
            }
            tempEvtList.add(evt);
        }
        Activity activity = new Activity();
        activity.tasks = tempTskList;
        activity.events = tempEvtList;
        return activity;     
    }   
    public class listRecordTypes
    {
        @AuraEnabled
        public string name;
        @AuraEnabled
        public string id;
        @AuraEnabled
        public boolean isTask;      
    }
    Public class activity
    {
        @AuraEnabled
        public List<Task> tasks;
        @AuraEnabled
        public List<Event> events;    
    }
}