objects/Account.object
<CustomObject>
    <fields>
        <fullName>FinServ__LastInteraction__c</fullName>
        <description>Date of the last client meeting or call.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Interaction</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__NextInteraction__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Next Interaction</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Relationship_Group</fullName>
        <active>true</active>
        <label>Relationship Group</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__AccountAccountRelation__c.object
<CustomObject>
    <description>A relationship between two accounts, such as a household and a business account.</description>
    <fields>
        <fullName>FinServ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>RelatedFromAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>RelatedToAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Related Role</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>FinServ__ReciprocalRole__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Account Role</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FinServ__ReciprocalRole__c</referenceTo>
        <relationshipName>AccountReciprocalRole</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account-Account Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Account Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__FinancialAccountNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccountRole__c.object
<CustomObject>
    <description>Represents the role occupied by a person or organizational entity that is involved with a financial account, such as a beneficiary or trustee.</description>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <description>Financial account that this role is related to.</description>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Roles</relationshipLabel>
        <relationshipName>FinancialAccountRoles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FinServ__RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the organizational entity that is involved with the financial account.</description>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Roles</relationshipLabel>
        <relationshipName>FinancialAccountRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__Role__c</fullName>
        <description>Role that describes how the organizational entity or person is involved with the financial account.</description>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Beneficial Owner</fullName>
                </value>
                <value>
                    <fullName>Committee Member</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Additional Obligator</fullName>
                </value>
                <value>
                    <fullName>Authority Signor</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Co-Borrower</fullName>
                </value>
                <value>
                    <fullName>Guarantor</fullName>
                </value>
                <value>
                    <fullName>President</fullName>
                </value>
                <value>
                    <fullName>Borrower</fullName>
                </value>
                <value>
                    <fullName>Co-Maker</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Llc</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Aka</fullName>
                </value>
                <value>
                    <fullName>Association</fullName>
                </value>
                <value>
                    <fullName>Assistant Director</fullName>
                </value>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Auth. Agent For</fullName>
                </value>
                <value>
                    <fullName>Authority Signor - Non Owner</fullName>
                </value>
                <value>
                    <fullName>Bankrupt</fullName>
                </value>
                <value>
                    <fullName>Bene Ira</fullName>
                </value>
                <value>
                    <fullName>Beneficiary</fullName>
                </value>
                <value>
                    <fullName>Beneficiary Non</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>By</fullName>
                </value>
                <value>
                    <fullName>Education Saving Account</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Chairman</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Account Role</label>
    <nameField>
        <displayFormat>FAR-{000000000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FinServ__ReciprocalRole__c.object
<CustomObject>
    <description>Represents the other entity’s corresponding role in a one-to-one relationship between entities.</description>
    <fields>
        <fullName>FinServ__CreateInverseRole__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked, a new inverse role is created for the role.</description>
        <inlineHelpText>If checked, a corresponding inverse role is automatically created.</inlineHelpText>
        <label>Create Inverse Role</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FinServ__InverseRole__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Inverse Role</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Reciprocal Role</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reciprocal Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_AccountAccountRelationBeforeHandler_T.cls
/**
* ----------------------------------------------------------------------------------------------------------------
* @Name				WT_AccountAccountRelationBeforeHandler_T
* @Author			Anoop B	<abattini@wintrust.com>
* @Version			v1.0
* @CreatedDate		30-07-2021
* --------------------------------------------------------------------------------------------------------------
* @Description
* This is test class for after handler class for WT_AccountAccountRelationBeforeHandler.
* ---------------------------------------------------------------------------------------------------------------------------------------------------
* FUNCTIONAL TEST LOGIC

* ----------------------------------------------------------------------------------------------------------------------------------------------------
**/
@isTest
public class WT_AccountAccountRelationBeforeHandler_T 
{
	static testmethod void  testAccountAccountRelationHandler(){
        User userCreateRecord = WT_DataFactory.createUser('System Administrator');
        insert userCreateRecord;
        WT_DataFactory.createRequiredCustomSetting();
        system.runAs(userCreateRecord)
        {
            List <Account> listNewClassifiedAccount = WT_DataFactory.createNonPersonAccounts(1,'Relationship_Group',userCreateRecord.id);
            insert listNewClassifiedAccount[0];
            List <Account> listNewPersonAccount = WT_DataFactory.createAccounts(1,'PersonAccount_Prospect',userCreateRecord.id);
            insert listNewPersonAccount;
            listNewPersonAccount[0].FinServ__LastInteraction__c=Date.today();
            listNewPersonAccount[0].FinServ__NextInteraction__c=Date.today();
            update listNewPersonAccount[0];
            
            FinServ__FinancialAccount__c finAccount=new FinServ__FinancialAccount__c();
            finAccount.FinServ__FinancialAccountNumber__c='217981230';
            finAccount.FinServ__PrimaryOwner__c=listNewClassifiedAccount[0].Id;
            insert finAccount;
            
            FinServ__FinancialAccountRole__c FinAccountRole=new FinServ__FinancialAccountRole__c();
            FinAccountRole.FinServ__RelatedAccount__c=listNewPersonAccount[0].id;
            FinAccountRole.FinServ__FinancialAccount__c=finAccount.Id;
            FinAccountRole.FinServ__Role__c='Beneficiary';
            insert FinAccountRole;
            
            FinServ__ReciprocalRole__c finRole=new FinServ__ReciprocalRole__c();
            finRole.FinServ__CreateInverseRole__c=true;
            finRole.FinServ__InverseRole__c='Client';
            insert finRole;
            
            FinServ__AccountAccountRelation__c AAR = new FinServ__AccountAccountRelation__c(); 
            AAR.FinServ__Account__c = listNewClassifiedAccount[0].id;
            AAR.FinServ__RelatedAccount__c = listNewPersonAccount[0].Id;
            AAR.FinServ__Role__c=finRole.Id;
           
            Test.startTest();
            insert AAR;
            update AAR;
            delete AAR;
            Test.stopTest();
        }
    }
}