objects/Account.object
<CustomObject>
    <fields>
        <fullName>FinServ__ReferredByUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Referrer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>AccountEmployeeReferrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>BusinessAccount_Prospect</fullName>
        <active>true</active>
        <label>Business Account (Prospect)</label>
    </recordTypes>
    <recordTypes>
        <fullName>Relationship_Group</fullName>
        <active>true</active>
        <label>Relationship Group</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Group Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__ReciprocalRole__c.object
<CustomObject>
    <description>Represents the other entity’s corresponding role in a one-to-one relationship between entities.</description>
    <fields>
        <fullName>FinServ__CreateInverseRole__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked, a new inverse role is created for the role.</description>
        <inlineHelpText>If checked, a corresponding inverse role is automatically created.</inlineHelpText>
        <label>Create Inverse Role</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FinServ__InverseRole__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Inverse Role</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Reciprocal Role</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reciprocal Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>FinServ__ReferredByUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Referrer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>LeadUserReferrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Leads</relationshipLabel>
        <relationshipName>RelatedLeads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Group Referrals</relationshipLabel>
        <relationshipName>RG_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>WT_Wealth</fullName>
        <active>true</active>
        <businessProcess>Referral Process</businessProcess>
        <label>Wealth</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__ReferredByUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Referrer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>OpportunityEmployeeReferrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Group Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WT_RelationshipGroup_Relation__c.object
<CustomObject>
    <description>A relationship between relationship account and person or business account.</description>
    <fields>
        <fullName>WT_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Group Relations (Account)</relationshipLabel>
        <relationshipName>Account_Account_Relations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WT_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WT_Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Member</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WT_RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>RelatedTOAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Related Role</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>FinServ__ReciprocalRole__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Account Role</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FinServ__ReciprocalRole__c</referenceTo>
        <relationshipLabel>Relationship Group Relations</relationshipLabel>
        <relationshipName>Account_Account_Relations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship Group Relation</label>
    <nameField>
        <displayFormat>AAR-{000000000}</displayFormat>
        <label>Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Group Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WT_Switch_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting is created for bypassing the execution of Automations and Triggers as and when needed.</description>
    <fields>
        <fullName>WT_Is_Process_Builder_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Process Builder Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WT_Is_Trigger_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Trigger Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WT_Is_Validation_Rule_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Validation Rule Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WT_Is_Workflow_Rule_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Workflow Rule Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Switch Settings</label>
</CustomObject>

classes/WT_BatchRelationshipGroupMemberRollUp_T.cls
/**
* --------------------------------------------------------------------------------------------------------------
* @Name             WT_BatchRelationshipGroupMemberRollUp_T
* @Author           Swaminathan E   <SEzhumal@wintrust.com>
* @ModifiedBy       Swaminathan E   <SEzhumal@wintrust.com>
* @Version          v1.0
* @CreatedDate      09-08-2020
* --------------------------------------------------------------------------------------------------------------
* @Description
* This is test class used for Batch class for WT_BatchRelationshipGroupMemberRollUp.
* ---------------------------------------------------------------------------------------------------------------------------------------------------
* FUNCTIONAL TEST LOGIC
* 1- runExcuteLogic() 
*   > used to roll up all the child records.
* ----------------------------------------------------------------------------------------------------------------------------------------------------
**/
@isTest
public class WT_BatchRelationshipGroupMemberRollUp_T 
{
    @isTest
    public Static void runExcuteLogic()
    {
        WT_Switch_Settings__c switchRecord = new WT_Switch_Settings__c();
        switchRecord.WT_Is_Process_Builder_Active__c=false;
        switchRecord.WT_Is_Trigger_Active__c=false;
        switchRecord.WT_Is_Validation_Rule_Active__c=false;
        switchRecord.WT_Is_Workflow_Rule_Active__c=false;
        switchRecord.WT_Is_Required_AAR_Load__c=false;
        Database.insert(switchRecord,false);
        User userRecord = WT_DataFactory.createUser('System Administrator');       
        insert userRecord;
        List<Account> listRGAccount = WT_DataFactory.createNonPersonAccounts(2,'Relationship_Group',userRecord.Id);
        List<Account> listBusinessAccount = WT_DataFactory.createNonPersonAccounts(2,'BusinessAccount_Prospect',userRecord.Id);
        insert listBusinessAccount;
        insert listRGAccount;
        Id accountRecordId = Schema.SObjectType.FinServ__ReciprocalRole__c.getRecordTypeInfosByDeveloperName().get('AccountRole').getRecordTypeId();
        FinServ__ReciprocalRole__c role = new FinServ__ReciprocalRole__c();
        role.FinServ__CreateInverseRole__c  = false;
        role.FinServ__InverseRole__c = 'Client';
        role.Name = 'Client';
        role.RecordTypeId = accountRecordId;
        insert role;
        FinServ__FinancialAccount__c financialRecord = new FinServ__FinancialAccount__c();
        financialRecord.Name = 'Checking Account';
        financialRecord.FinServ__PrimaryOwner__c = listBusinessAccount[0].Id;
        financialRecord.RecordTypeId = Schema.SObjectType.FinServ__FinancialAccount__c.getRecordTypeInfosByDeveloperName().get('CheckingAccount').getRecordTypeId();
        insert financialRecord;
        FinServ__FinancialAccount__c financialRecord1 = new FinServ__FinancialAccount__c();
        financialRecord1.Name = 'Checking Account1';
        financialRecord1.FinServ__PrimaryOwner__c = listBusinessAccount[1].Id;
        financialRecord1.RecordTypeId = Schema.SObjectType.FinServ__FinancialAccount__c.getRecordTypeInfosByDeveloperName().get('CheckingAccount').getRecordTypeId();
        insert financialRecord1;
        Opportunity opportunityRecord = new Opportunity();
        opportunityRecord.Name = 'TM - Treasury Management Services';
        opportunityRecord.AccountId = listBusinessAccount[0].Id ;
        opportunityRecord.CloseDate = System.today();
        opportunityRecord.StageName = 'Stage 1 - Opportunity Identified';
        insert opportunityRecord;
        Opportunity opportunityRecord1 = new Opportunity();
        opportunityRecord1.Name = 'TM - Treasury Management Services1';
        opportunityRecord1.AccountId = listBusinessAccount[1].Id ;
        opportunityRecord1.CloseDate = System.today();
        opportunityRecord1.StageName = 'Stage 1 - Opportunity Identified';
        insert opportunityRecord1;
        Lead leadRecord = new Lead();
        leadRecord.FinServ__ReferredByUser__c = userRecord.Id;
        leadRecord.LastName = 'Referral Record3';
        leadRecord.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('WT_Wealth').getRecordTypeId();
        leadRecord.FinServ__RelatedAccount__c = listBusinessAccount[0].Id;
        insert leadRecord;
        Lead leadRecord1 = new Lead();
        leadRecord1.FinServ__ReferredByUser__c = userRecord.Id;
        leadRecord1.LastName = 'Referral Record4';
        leadRecord1.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('WT_Wealth').getRecordTypeId();
        leadRecord1.FinServ__RelatedAccount__c = listBusinessAccount[1].Id;
        insert leadRecord1;
        Event eventRecord =new Event(Subject='Send Letter',StartDateTime=System.now(),EndDateTime= System.now(),whatId=listBusinessAccount[0].Id);
        insert eventRecord;
        Event eventRecord1 =new Event(Subject='grade event',StartDateTime=System.now(),EndDateTime= System.now(),whatId=listBusinessAccount[1].Id);
        insert eventRecord1;
        Task taskRecord = new Task(subject='Send Letter' , Priority='Normal' , Status='Open' , WhatId=listBusinessAccount[0].Id );
        insert taskRecord;
        Task taskRecord1 = new Task(subject='grade task' , Priority='Normal' , Status='Open' , WhatId=listBusinessAccount[1].Id );
        insert taskRecord1;
        WT_RelationshipGroup_Relation__c relationRecord1 = new WT_RelationshipGroup_Relation__c();
        relationRecord1.WT_Account__c = listRGAccount[0].Id;
        relationRecord1.WT_RelatedAccount__c = listBusinessAccount[0].Id;
        relationRecord1.WT_Primary__c = true;
        relationRecord1.WT_Role__c = role.Id;
        relationRecord1.WT_Active__c = true;
        insert relationRecord1;
        WT_RelationshipGroup_Relation__c relationRecord2 = new WT_RelationshipGroup_Relation__c();
        relationRecord2.WT_Account__c = listRGAccount[0].Id;
        relationRecord2.WT_RelatedAccount__c = listBusinessAccount[1].Id;
        relationRecord2.WT_Role__c = role.Id;
        relationRecord2.WT_Active__c = false;
        insert relationRecord2;
        //System.assertEquals(0, [SELECT ID FROM LEAD WHERE WT_Relationship_Group__c = :listRGAccount[0].Id].size());
        test.startTest();
        WT_BatchRelationshipGroupMemberRollUp batchRollupReferral = new 
            WT_BatchRelationshipGroupMemberRollUp('aCCount,oPPortUniTy,RefeRRal,task,ActioN PlaN,Financial aCCount,evENT');
        Database.executeBatch(batchRollupReferral);
        test.stopTest();
        //System.assertEquals(1, [SELECT ID FROM LEAD WHERE WT_Relationship_Group__c = :listRGAccount[0].Id].size());
    }
}