objects/Account.object
<CustomObject>
    <fields>
        <fullName>WT_Parent_Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>DBSFCRM-1583</description>
        <label>Parent Relationship Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts (Parent Relationship Group)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Group Financial Accounts</relationshipLabel>
        <relationshipName>Financial_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>FinServ__RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Leads</relationshipLabel>
        <relationshipName>RelatedLeads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Group Referrals</relationshipLabel>
        <relationshipName>RG_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Group Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WT_RelationshipGroup_Relation__c.object
<CustomObject>
    <description>A relationship between relationship account and person or business account.</description>
    <fields>
        <fullName>WT_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Group Relations (Account)</relationshipLabel>
        <relationshipName>Account_Account_Relations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WT_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WT_RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>RelatedTOAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship Group Relation</label>
    <nameField>
        <displayFormat>AAR-{000000000}</displayFormat>
        <label>Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Group Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/WT_BatchRelationshipGroupMemberRollUp.cls
/**
* -------------------------------------------------------------------------------------------------------------------------------------------------
* @Name         WT_BatchRelationshipGroupMemberRollUp
* @Author           Swaminathan E     <sezhumal@wintrust.com> 
* @ModifiedBy       Swaminathan E     <sezhumal@wintrust.com>
* @version      v1.0 
* @CreatedDate      09-05-2021
* @UsedBy           Relationship Group Relation Object
* ---------------------------------------------------------------------------------------------------------------------------------------------------
* @Description 
* Class is used to roll up all the child records. 
* ---------------------------------------------------------------------------------------------------------------------------------------------------
* @Changes
* vx.x              <user id>
* MM-DD-YYYY        <Explanation> 
* ----------------------------------------------------------------------------------------------------------------------------------------------------
**/
// Test class: WT_BatchRelationshipGroupMemberRollUp_T
global class WT_BatchRelationshipGroupMemberRollUp implements Database.Batchable<sObject>
{
    public List<String> getRollUpObjectApiName;  
    global WT_BatchRelationshipGroupMemberRollUp (String getRollUpObjectApiName)
    {
        List<String> listRoll = getRollUpObjectApiName.split(',');
        List<String> listRollend = new List<String>();
        for(String rollupName : listRoll)
        {
            listRollend.add(rollupName.toLowerCase());
        }
        this.getRollUpObjectApiName = listRollend;
    }
    //Query all the existing Relationship Group Relation record
    public Database.QueryLocator start(Database.BatchableContext BC)
    {
        String query = 'SELECT Id, WT_RelatedAccount__c, WT_Account__c, WT_Active__c FROM WT_RelationshipGroup_Relation__c WHERE WT_RelatedAccount__c != Null';
        return Database.getQueryLocator(query);   
    }
    public void execute(Database.BatchableContext bc, List<WT_RelationshipGroup_Relation__c> listOfRGRelation)
    {
        List<SObject> listOfSObject = new List<SObject>();
        Set<Id> setActiveRelatedId = new Set<Id>();
        Map<Id,Id> mapAccountId = new Map<Id,Id>();
        for(WT_RelationshipGroup_Relation__c acountAccountRecord: listOfRGRelation)
        {
            if(acountAccountRecord.WT_Active__c)
            {
                setActiveRelatedId.add(acountAccountRecord.WT_RelatedAccount__c);
            }
            mapAccountId.put(acountAccountRecord.WT_RelatedAccount__c,acountAccountRecord.WT_Account__c);  
        }
        if(!mapAccountId.isEmpty())
        {
            if(getRollUpObjectApiName.contains('account')) 
            { 
                List<Account> listAccount = [SELECT Id, WT_Parent_Relationship_Group__c FROM Account WHERE Id IN :mapAccountId.keySet() ];
                for(Account accountRecord :listAccount)
                {
                    if(setActiveRelatedId.contains(accountRecord.Id))
                    {
                        accountRecord.WT_Parent_Relationship_Group__c = mapAccountId.get(accountRecord.Id);
                    }
                    else
                    {
                        accountRecord.WT_Parent_Relationship_Group__c = Null; 
                    }
                }
                listOfSObject.addAll(listAccount);
            }
            if(getRollUpObjectApiName.contains('opportunity')) 
            { 
                List<Opportunity> listOpportunity = [SELECT Id, WT_Relationship_Group__c, AccountId FROM Opportunity WHERE AccountId IN :mapAccountId.keySet() ];
                for(Opportunity opportunityRecord :listOpportunity)
                {
                    if(setActiveRelatedId.contains(opportunityRecord.AccountId))
                    {
                        opportunityRecord.WT_Relationship_Group__c = mapAccountId.get(opportunityRecord.AccountId);
                    }
                    else
                    {
                        opportunityRecord.WT_Relationship_Group__c = Null; 
                    }
                }
                listOfSObject.addAll(listOpportunity);
            }
            if(getRollUpObjectApiName.contains('financial account'))
            { 
                List<FinServ__FinancialAccount__c> listFinancialAccount = [SELECT Id, WT_Relationship_Group__c, FinServ__PrimaryOwner__c FROM FinServ__FinancialAccount__c WHERE FinServ__PrimaryOwner__c IN :mapAccountId.keySet() ];
                for(FinServ__FinancialAccount__c financialRecord: listFinancialAccount)
                {  
                    if(setActiveRelatedId.contains(financialRecord.FinServ__PrimaryOwner__c))
                    {
                        financialRecord.WT_Relationship_Group__c = mapAccountId.get(financialRecord.FinServ__PrimaryOwner__c);
                    }
                    else
                    {
                        financialRecord.WT_Relationship_Group__c = Null; 
                    }
                }
                listOfSObject.addAll(listFinancialAccount);
            }
            if(getRollUpObjectApiName.contains('referral'))
            {
                List<Lead> listReferral = [SELECT Id, FinServ__RelatedAccount__c FROM Lead WHERE FinServ__RelatedAccount__c IN :mapAccountId.keySet()  ];
                for(Lead leadRecord: listReferral)
                {
                    if(setActiveRelatedId.contains(leadRecord.FinServ__RelatedAccount__c))
                    {
                        leadRecord.WT_Relationship_Group__c = mapAccountId.get(leadRecord.FinServ__RelatedAccount__c);
                    }
                    else
                    {
                        leadRecord.WT_Relationship_Group__c = Null; 
                    }
                }
                listOfSObject.addAll(listReferral);
            }
            if(getRollUpObjectApiName.contains('event'))
            {
                List<Event> listEvent = [SELECT Id, WT_Relationship_Group__c, WhatId FROM Event WHERE WhatId IN :mapAccountId.keySet()  ];
                for(Event eventRecord: listEvent)
                {
                    if(setActiveRelatedId.contains(eventRecord.WhatId))
                    {
                        eventRecord.WT_Relationship_Group__c = mapAccountId.get(eventRecord.WhatId);
                    }
                    else
                    {
                        eventRecord.WT_Relationship_Group__c = Null;
                    }   
                }
                listOfSObject.addAll(listEvent);
            }
            if(getRollUpObjectApiName.contains('task'))
            { 
                List<Task> listTask = [SELECT Id, WT_Relationship_Group__c, WhatId FROM Task WHERE WhatId IN :mapAccountId.keySet()  ];
                for(Task taskRecord: listTask)
                {
                    if(setActiveRelatedId.contains(taskRecord.WhatId))
                    {
                        taskRecord.WT_Relationship_Group__c = mapAccountId.get(taskRecord.WhatId);
                    }
                    else
                    {
                        taskRecord.WT_Relationship_Group__c = Null; 
                    }     
                }
                listOfSObject.addAll(listTask);
            }
            if(getRollUpObjectApiName.contains('action plan'))
            { 
                List<ActionPlan> listActionPlan = [SELECT Id, TargetId, WT_Relationship_Group__c FROM ActionPlan WHERE TargetId IN :mapAccountId.keySet()];
                for(ActionPlan actionPlanRecord: listActionPlan)
                {
                    if(actionPlanRecord.TargetId.getsObjectType() == Account.sObjectType)
                    {
                        if(setActiveRelatedId.contains(actionPlanRecord.TargetId))
                        {
                            actionPlanRecord.WT_Relationship_Group__c = mapAccountId.get(actionPlanRecord.TargetId); 
                        }
                        else
                        {
                            actionPlanRecord.WT_Relationship_Group__c = Null;
                        }
                    }
                }
                listOfSObject.addAll(listActionPlan);
            }                                  
            List<Database.SaveResult> listUpdateResult = Database.update(listOfSObject, false);
            for (Database.SaveResult result : listUpdateResult) 
            {
                if (!result.isSuccess())
                {
                    for (Database.Error error : result.getErrors())
                    {
                        System.debug('Record Id: '+result.getId()+'Error: '+ error.getMessage());
                    }
                }
            }
        }
    }
    public void finish(Database.BatchableContext bc)
    {
        // execute any post-processing operations
    }
}