objects/Account.object
<CustomObject>
    <fields>
        <fullName>WT_Classification__c</fullName>
        <description>Created as part of DBSFCRM-649. This captures classification of account.</description>
        <label>Classification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>C</fullName>
                    <label>C = Customer</label>
                </value>
                <value>
                    <fullName>C1</fullName>
                    <label>C1 = Top Priority Customer</label>
                </value>
                <value>
                    <fullName>C2</fullName>
                    <label>C2 = Medium Priority Customer</label>
                </value>
                <value>
                    <fullName>C3</fullName>
                    <label>C3 = Established Customer</label>
                </value>
                <value>
                    <fullName>C4</fullName>
                    <label>C4 = Customer - PPP Onboarding</label>
                </value>
                <value>
                    <fullName>COI</fullName>
                    <label>COI = Center of Influence</label>
                </value>
                <value>
                    <fullName>NQ</fullName>
                    <label>NQ = Middle Market (Revenue $10MM to $260MM)</label>
                </value>
                <value>
                    <fullName>NQ0</fullName>
                    <label>NQ0 = Companies with Unknown Revenue</label>
                </value>
                <value>
                    <fullName>NQBB</fullName>
                    <label>NQBB = Companies with Revenue $1.00MM to $9.99MM</label>
                </value>
                <value>
                    <fullName>NQSB</fullName>
                    <label>NQSB = Companies with Revenue under $1MM</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <label>P1 = Proposing within 6 months/Top Prospect</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <label>P2 = Proposing in 6-12 months</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <label>P3 = Proposing outside 12 months</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <label>P4 = Other</label>
                </value>
                <value>
                    <fullName>P5</fullName>
                    <label>P5 = PPP Lead</label>
                </value>
                <value>
                    <fullName>X1</fullName>
                    <label>X1 = EdFAC</label>
                </value>
                <value>
                    <fullName>X2</fullName>
                    <label>X2 = Bankrupt/Out of Business</label>
                </value>
                <value>
                    <fullName>X3</fullName>
                    <label>X3 = Industry Excluded</label>
                </value>
                <value>
                    <fullName>X4</fullName>
                    <label>X4 = Subsidiary</label>
                </value>
                <value>
                    <fullName>X5</fullName>
                    <label>X5 = Potential Duplicate</label>
                </value>
                <value>
                    <fullName>X6</fullName>
                    <label>X6 = Other</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Employee_Indicator__c</fullName>
        <label>Employee Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Type__c</fullName>
        <formula>CASE(RecordType.Name, &apos;Person Account (Prospect)&apos;, &apos;Prospect&apos;, &apos;Person Account (Customer)&apos;, &apos;Customer&apos; ,&apos; &apos;)</formula>
        <label>Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Case_Title__c</fullName>
        <description>Created as a part of DBSFCRM-417</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Case Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Date_Received__c</fullName>
        <description>Created as a part of DBSFCRM-417</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Date  Received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WT_Exception__c</fullName>
        <description>Created as a part of DDBSFCRM-417</description>
        <label>Exception</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complex Issue</fullName>
                </value>
                <value>
                    <fullName>Documentation</fullName>
                </value>
                <value>
                    <fullName>Received Late</fullName>
                </value>
                <value>
                    <fullName>With Legal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Non_Customer_Complainant__c</fullName>
        <description>Created as a part of DBSFCRM-417</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Non-Customer Complainant</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Employee_Indicator__c</fullName>
        <label>Employee Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>TBA</fullName>
                </value>
                <value>
                    <fullName>Undefined/Other</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>WT_Business_Unit_Entity__c</fullName>
        <description>reference to Business Unit Entity</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Branch Factor</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WT_Business_Unit_Entity_Staging__c.object
<CustomObject>
    <fields>
        <fullName>WT_Is_Processed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Processed</label>
        <type>Checkbox</type>
    </fields>
    <label>Branch Factor Staging</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branch Factor Location Staging</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Factor Staging</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WT_Case_Note__c.object
<CustomObject>
    <description>Created as a part of DBSFCRM-593</description>
    <fields>
        <fullName>WT_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Created as a part of DBSFCRM-593</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Notes</relationshipLabel>
        <relationshipName>Case_Notes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Note_Category__c</fullName>
        <label>Note Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Called Customer</fullName>
                </value>
                <value>
                    <fullName>E-mailed Customer</fullName>
                </value>
                <value>
                    <fullName>Memo</fullName>
                </value>
                <value>
                    <fullName>Status Update</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Notes__c</fullName>
        <description>Created as a part of DBSFCRM-593</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Notes</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WT_Type__c</fullName>
        <description>Created as a part of DBSFCRM-593</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>WT_Note_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Resolving</fullName>
                </value>
                <value>
                    <fullName>Waiting for Customer</fullName>
                </value>
                <value>
                    <fullName>Cancellation</fullName>
                </value>
                <value>
                    <fullName>Fulfillment</fullName>
                    <isActive>false</isActive>
                    <label>Fulfillment</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Case Note</label>
    <nameField>
        <displayFormat>Note-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_DataFactory_T.cls
/**
 * -------------------------------------------------------------------------------------------------------------------------------------------------
 * @Name            WT_DataFactory_T
 * @Author          Sivaranjani     <sivaranjani.d2@tcs.com.tcsdev> 
 * @ModifiedBy      Sivaranjani     <sivaranjani.d2@tcs.com.tcsdev>
 * @version         v1.0 
 * @CreatedDate     11-18-2020
 * @UsedBy          All objects , test class for WT_TestDatafactory
 * ---------------------------------------------------------------------------------------------------------------------------------------------------
 * @Description 
 * Class is used to test the WT_TestDataFactory class. Used to cover code on WT_TestDataFactory
 * ---------------------------------------------------------------------------------------------------------------------------------------------------
 * FUNCTIONAL TEST LOGIC
 * 1- runCreateBusinessUnitEntity() 
 *  > used to test the creation of WT_Business_Unit_Entity_Staging__c,WT_Business_Unit_Entity__c using WT_DataFactory
 * ----------------------------------------------------------------------------------------------------------------------------------------------------
**/
@isTest
private class WT_DataFactory_T 
{
    static WT_Business_Unit_Entity_Staging__c businessUnitEntityStagingRecord;
    static WT_Business_Unit_Entity_Staging__c businessUnitEntityStagingRecordWTFC;
    static WT_Business_Unit_Entity__c businessUnitEntityRecord;
    static WT_Business_Unit_Entity__c businessUnitEntityRecordWTFC;
    @isTest static void runCreateBusinessUnitEntity()
    {
        businessUnitEntityStagingRecord = WT_DataFactory.createBusinessUnitEntityStagging();
        insert businessUnitEntityStagingRecord;
        businessUnitEntityStagingRecordWTFC = WT_DataFactory.createBusinessUnitEntityStaggingWTFC();
        insert businessUnitEntityStagingRecordWTFC;
        businessUnitEntityRecord = WT_DataFactory.createBusinessUnitEntity();
        insert businessUnitEntityRecord;
        businessUnitEntityRecordWTFC = WT_DataFactory.createBusinessUnitEntityWTFC();
        insert businessUnitEntityRecordWTFC;
        User userrecord = WT_DataFactory.createUser('System Administrator');
        List<Account> listPersonAccounts = WT_DataFactory.createAccounts(10,'PersonAccount_Prospect',UserInfo.getUserId());
        List<Account> listAccounts = WT_DataFactory.createAccounts(10,'IndustriesBusiness',UserInfo.getUserId());
        WT_DataFactory.createRequiredCustomSetting();
    }  
       @isTest(SeeAllData=true)     
    public static void runCreateCoveragePlan() 
    {        
        User userRecord = WT_DataFactory.createUser('WT Retail');
        insert userRecord;
        List <Account> listNewClassifiedAccount = WT_DataFactory.createNonPersonAccounts(10,'IndustriesBusiness',userRecord.Id);
        for(Account accountRecord: listNewClassifiedAccount)
        {
            accountRecord.WT_Classification__c = 'P1';
        }
        test.startTest();
        insert listNewClassifiedAccount;
        test.stopTest();
        List<ActionPlan> listactionPlanRecords = new List<ActionPlan>();
        listactionPlanRecords = [Select id from actionplan where TargetId in:listNewClassifiedAccount];
        //system.assertNotEquals(0, listactionPlanRecords.size());
    }
    @isTest(SeeAllData=true)     
    public static void runCreateCoveragePlanAccountUpdate() 
    {
        User userRecord = WT_DataFactory.createUser('WT Retail');
        insert userRecord;
        List <Account> listNewClassifiedAccount = WT_DataFactory.createNonPersonAccounts(10,'IndustriesBusiness',userRecord.Id);
        insert listNewClassifiedAccount;
        List<ActionPlan> listactionPlanRecords = new List<ActionPlan>();
        listactionPlanRecords = [Select id from actionplan where TargetId in:listNewClassifiedAccount];
        system.assertEquals(0, listactionPlanRecords.size());
        for(Account accountRecord: listNewClassifiedAccount)
        {
            accountRecord.WT_Classification__c = 'P1';
        }
        test.startTest();
        update listNewClassifiedAccount;
        test.stopTest();
        listactionPlanRecords = [Select id from actionplan where TargetId in:listNewClassifiedAccount];
        //system.assertNotEquals(0, listactionPlanRecords.size());
    }
    @isTest
    public static void runRestrictAccountsMerge() 
    {
        User userRecord = WT_DataFactory.createUser('WT Retail');
        insert userRecord;
        List<Account> listCustomerAccount = WT_DataFactory.createAccounts(1,'PersonAccount_Customer',userRecord.Id);
        insert listCustomerAccount;
        List<Account> listProspectAccount = WT_DataFactory.createAccounts(1,'PersonAccount_Prospect',userRecord.Id);
        insert listProspectAccount;        
        WT_DataFactory.createRequiredCustomSetting();
        try
        {
            test.startTest();
            merge listProspectAccount[0] listCustomerAccount;
            test.stopTest();
        }
        catch(exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains(System.Label.WT_Account_Error_on_Merge) ? true : false;
            system.assertEquals(expectedExceptionThrown,true);
        }        
    }
     @isTest static void runBatchBusinessUnitUpdate()
    {
        WT_Business_Unit_Entity_Staging__c businessUnitStagingRecord =  WT_DataFactory.createBusinessUnitEntityStagging();
        insert businessUnitStagingRecord;
        WT_Business_Unit_Entity_Staging__c businessUnitStagingRecordWTFC =  WT_DataFactory.createBusinessUnitEntityStaggingWTFC();
        insert businessUnitStagingRecordWTFC;
        WT_Business_Unit_Entity__c businessUnitRecord = WT_DataFactory.createBusinessUnitEntity();
        insert businessUnitRecord;
        WT_Business_Unit_Entity__c businessUnitRecordWTFC = WT_DataFactory.createBusinessUnitEntityWTFC();
        insert businessUnitRecordWTFC;
        WT_Business_Unit_Entity_Staging__c businessUnitStagingRecord2 = WT_DataFactory.createBusinessUnitEntityStagging2();
        insert businessUnitStagingRecord2;
        System.assertEquals(businessUnitStagingRecord.WT_Is_Processed__c, false);
        System.assertEquals(businessUnitStagingRecordWTFC.WT_Is_Processed__c, false);
        Test.startTest();
        WT_BatchBusinessUnitUpdate batchBusinessUnitUpdate= new WT_BatchBusinessUnitUpdate();
        Database.executeBatch(batchBusinessUnitUpdate);
        Test.stopTest();
        WT_Business_Unit_Entity_Staging__c businessUnitEntityStagingRecordQuery = [select Id, WT_Is_Processed__c from WT_Business_Unit_Entity_Staging__c where id =: businessUnitStagingRecord.id];
        System.assertEquals(businessUnitEntityStagingRecordQuery.WT_Is_Processed__c, true);
        WT_Business_Unit_Entity_Staging__c businessUnitEntityStagingRecordQuery2 = [select Id, WT_Is_Processed__c from WT_Business_Unit_Entity_Staging__c where id =: businessUnitStagingRecord2.id];
        System.assertEquals(businessUnitEntityStagingRecordQuery2.WT_Is_Processed__c, false);
        
        WT_Business_Unit_Entity_Staging__c businessUnitEntityStagingRecordWTFCQuery = [select Id, WT_Is_Processed__c from WT_Business_Unit_Entity_Staging__c where id =: businessUnitStagingRecordWTFC.id];
        System.assertEquals(businessUnitEntityStagingRecordWTFCQuery.WT_Is_Processed__c, true);
    }
     @isTest static void runBatchBusinessUnitEntityUpdate()
    {
        WT_Business_Unit_Entity_Staging__c businessUnitStagingRecord =  WT_DataFactory.createBusinessUnitEntityStagging();
        insert businessUnitStagingRecord;
        WT_Business_Unit_Entity__c businessUnitRecord = WT_DataFactory.createBusinessUnitEntity();
        insert businessUnitRecord;
            
        System.assertEquals(businessUnitStagingRecord.WT_Is_Processed__c, false);
        Test.startTest();
        WT_BatchBusinessUnitEntityUpdate batchBusinessUnitEntityUpdate= new WT_BatchBusinessUnitEntityUpdate();
        Database.executeBatch(batchBusinessUnitEntityUpdate);
        Test.stopTest();
        
        WT_Business_Unit_Entity_Staging__c businessUnitEntityStagingRecordQuery = [select Id, WT_Is_Processed__c from WT_Business_Unit_Entity_Staging__c where id =: businessUnitStagingRecord.id];
        System.assertEquals(businessUnitEntityStagingRecordQuery.WT_Is_Processed__c, true);
    }
    
      @isTest static void runBatchEventsCacelled()
    {
        List<Event> listEventRecords =  WT_DataFactory.createEventRecords(5,'WT_CRA_Event');
        insert listEventRecords;
        Test.startTest();
        WT_BatchMarkEventsCancelled batchEventsUpdate= new WT_BatchMarkEventsCancelled();
        Database.executeBatch(batchEventsUpdate);
        Test.stopTest();
    }
        @isTest static void runBatchTasksCacelled()
    {
        List<Task> listTaskRecords =  WT_DataFactory.createTaskRecords(5,'WT_Standard_Call');
        insert listTaskRecords;
        Test.startTest();
        WT_BatchMarkTasksCancelled batchTasksUpdate= new WT_BatchMarkTasksCancelled();
        Database.executeBatch(batchTasksUpdate);
        Test.stopTest();
    }
    @isTest
    static void setResolutionTargetTest()
    {
      RecordType complianceRecordType= [select id, developerName, Name from RecordType where Name='Compliance Complaint' and SobjectType='Case'];
      WT_DataFactory.createRequiredCustomSetting();
      Case caseRecord = new Case();
      caseRecord.RecordTypeId=complianceRecordType.Id;
      caseRecord.WT_Exception__c='Complex Issue';
      caseRecord.WT_Date_Received__c=Date.Today();
      caseRecord.WT_Case_Title__c='Test Case';
      caseRecord.WT_Non_Customer_Complainant__c='Test';  
      insert caseRecord;
      caseRecord.WT_Exception__c='';
      update caseRecord;
    }
    @isTest
    static void testValidations()
    { 
      RecordType complianceRecordType= [select id, developerName, Name from RecordType where Name='Compliance Complaint' and SobjectType='Case'];
      WT_DataFactory.createRequiredCustomSetting();
      Case caseRecord = new Case();
      caseRecord.RecordTypeId=complianceRecordType.Id;
      caseRecord.WT_Exception__c='Complex Issue';
      caseRecord.WT_Date_Received__c=Date.Today();
      caseRecord.WT_Case_Title__c='Test Case';
      caseRecord.WT_Non_Customer_Complainant__c='Test'; 
      caseRecord.Status = 'Pending';
      insert caseRecord;
      CaseRecord.Status = 'Resolved';
      try
        {
           update caseRecord; 
        }
        catch(DmlException e)
        {
            System.debug(e.getMessage());
            System.assertEquals('Update failed. First exception on row 0 with id '+ caseRecord.id +'; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, '+System.Label.WT_Error_on_Case_Resolved+': []',e.getMessage());
        }
        WT_Case_Note__c newCaseNote = new WT_Case_Note__c();
        newCaseNote.WT_Case__c = caseRecord.id;
        newCaseNote.WT_Note_Category__c = 'Status Update';
        newCaseNote.WT_Type__c ='Resolving';
        newCaseNote.WT_Notes__c='test';
        insert newCaseNote;
        update caseRecord;
    }
    @isTest
    static void testValidations2()
    { 
      RecordType complianceRecordType= [select id, developerName, Name from RecordType where Name='Compliance Complaint' and SobjectType='Case'];
      WT_DataFactory.createRequiredCustomSetting();
      Case caseRecord = new Case();
      caseRecord.RecordTypeId=complianceRecordType.Id;
      caseRecord.WT_Exception__c='Complex Issue';
      caseRecord.WT_Date_Received__c=Date.Today();
      caseRecord.WT_Case_Title__c='Test Case';
      caseRecord.WT_Non_Customer_Complainant__c='Test'; 
      caseRecord.Status = 'Pending';
      insert caseRecord;
      CaseRecord.Status = 'Cancelled';
      try
        {
           update caseRecord; 
        }
        catch(DmlException e)
        {
            System.debug(e.getMessage());
            System.assertEquals('Update failed. First exception on row 0 with id '+ caseRecord.id +'; first error: FIELD_CUSTOM_VALIDATION_EXCEPTION, '+System.Label.WT_Error_on_Cancellation+': []',e.getMessage());
        }
        WT_Case_Note__c newCaseNote = new WT_Case_Note__c();
        newCaseNote.WT_Case__c = caseRecord.id;
        newCaseNote.WT_Note_Category__c = 'Status Update';
        newCaseNote.WT_Type__c ='Cancellation';
        newCaseNote.WT_Notes__c='test';
        insert newCaseNote;
        update caseRecord;
    }
@isTest(SeeAllData=true)
    static void updateEmployeeIndicatorTest()
    {
        WT_DataFactory.createRequiredCustomSetting();
        Account primaryAccount = new Account();
        primaryAccount.FirstName = 'Firstnameone';
        primaryAccount.LastName = 'LastNametest';
        primaryAccount.BillingStreet = 'Test';
        primaryAccount.BillingState = 'OH';
        primaryAccount.BillingCity = 'Chicago';
        primaryAccount.BillingCountry = 'United States';
        primaryAccount.BillingPostalCode = '12345';
        primaryAccount.Phone = '1122334455';
        primaryAccount.ownerid = UserInfo.getUserId();
        primaryAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount_Customer').getRecordTypeId();
        insert primaryAccount;
        
        String recordTypeId = Schema.SObjectType.FinServ__FinancialAccount__c.getRecordTypeInfosByDeveloperName().get('CheckingAccount').getRecordTypeId();
        FinServ__FinancialAccount__c finAccount1 = new FinServ__FinancialAccount__c();
        finAccount1.WT_Employee_Indicator__c = 'Yes';
        finAccount1.RecordTypeId = recordTypeId;
        finAccount1.FinServ__PrimaryOwner__c = primaryAccount.id;
        insert finAccount1;
        
        Account primaryAccountCheck = [Select id, WT_Employee_Indicator__c from Account where id =: primaryAccount.id];
        //system.assertEquals('Yes', primaryAccountCheck.WT_Employee_Indicator__c);
        
        Account primaryAccount2 = new Account();
        primaryAccount2.FirstName = 'FirstNametwo';
        primaryAccount2.LastName = 'LastNametest';
        primaryAccount2.BillingStreet = 'Test';
        primaryAccount2.BillingState = 'OH';
        primaryAccount2.BillingCity = 'Chicago';
        primaryAccount2.BillingCountry = 'United States';
        primaryAccount2.BillingPostalCode = '12345';
        primaryAccount2.Phone = '1122334455';
        primaryAccount2.ownerid = UserInfo.getUserId();
        primaryAccount2.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount_Customer').getRecordTypeId();
        insert primaryAccount2;
        
        finAccount1.FinServ__PrimaryOwner__c = primaryAccount2.id;
        update finAccount1;
        
        Account primaryAccountCheck2 = [Select id, WT_Employee_Indicator__c from Account where id =: primaryAccount2.id];
        //system.assertEquals('Yes', primaryAccountCheck2.WT_Employee_Indicator__c);
        Account primaryAccountCheck3 = [Select id, WT_Employee_Indicator__c from Account where id =: primaryAccount.id];
        //system.assertEquals('No', primaryAccountCheck3.WT_Employee_Indicator__c);
        
    }
    static testMethod void runLeadShareRecord()
    {
        WT_DataFactory.createRequiredCustomSetting();
        List<User> listUsers = new List<User>();
        User userRecord1 = WT_DataFactory.createUser('System Administrator');
        userRecord1.FirstName = 'Test 123User'; 
        userRecord1.WT_Referrals_Type__c = 'Retail Banking';
        User userRecord2 = WT_DataFactory.createUser('System Administrator');        
        userRecord2.FirstName = 'Test 124User';
        userRecord2.WT_Referrals_Type__c = 'Retail Banking';
        User userRecord3 = WT_DataFactory.createUser('System Administrator');
        userRecord3.WT_Referrals_Type__c = 'Retail Banking';
        userRecord3.FirstName = 'Test 125User';               
        User userRecord4 = WT_DataFactory.createUser('System Administrator');        
        userRecord4.FirstName = 'Test 126User';
        userRecord4.WT_Referrals_Type__c = 'Retail Banking';
        listUsers.add(userRecord1);
        listUsers.add(userRecord2);
        listUsers.add(userRecord3);
        listUsers.add(userRecord4);
        insert listUsers;               
        Id user1Id =userRecord1.Id;
        Id user2Id = userRecord2.Id;
        Id user3Id =userRecord3.Id;
        Id user4Id = userRecord4.Id;
        Lead leadRecord1 = new Lead();
        leadRecord1.LastName = 'Test Job1';
        leadRecord1.OwnerId = user1Id;
        leadRecord1.WT_Referred_To__c = user2Id;
        leadRecord1.FinServ__ReferredByUser__c = user3Id;
        leadRecord1.FinServ__ExpressedInterest__c = 'Retail Banking';
        insert leadRecord1;
        Lead leadRecord2 = new Lead();
        leadRecord2.LastName = 'Test Job2';
        leadRecord2.OwnerId = user1Id;
        leadRecord2.WT_Referred_To__c = user3Id;
        leadRecord2.FinServ__ReferredByUser__c = user4Id;
        leadRecord2.FinServ__ExpressedInterest__c = 'Retail Banking';        
        insert leadRecord2;  
        
        // Query job sharing records.
        List<leadShare> jShrs1 = [SELECT Id, leadId, UserOrGroupId, leadAccessLevel, 
                                 RowCause FROM leadShare WHERE leadId = :leadRecord1.Id AND UserOrGroupId= :user2Id];
        List<leadShare> jShrs2 = [SELECT Id, leadId, UserOrGroupId, leadAccessLevel, 
                                 RowCause FROM leadShare WHERE leadId = :leadRecord2.Id AND UserOrGroupId= :user3Id];
        
        // Test for only one manual share on job.
        System.assertEquals(jShrs1[0].leadId, leadRecord1.Id);
        System.assertEquals(jShrs2[0].leadId, leadRecord2.Id);
                
        leadRecord1.WT_Referred_To__c = User4Id;
        leadRecord1.FinServ__ReferredByUser__c = user2Id;       
        update leadRecord1;
        leadRecord2.WT_Referred_To__c = user1Id;
        update leadRecord2;
        //System.assertEquals();
    } 
}