objects/Account.object
<CustomObject>
    <fields>
        <fullName>FinServ__LastInteraction__c</fullName>
        <description>Date of the last client meeting or call.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Interaction</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__NextInteraction__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Next Interaction</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FinServ__NextReview__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Next Review</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WT_Classification__c</fullName>
        <description>Created as part of DBSFCRM-649. This captures classification of account.</description>
        <label>Classification</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>C</fullName>
                    <label>C = Customer</label>
                </value>
                <value>
                    <fullName>C1</fullName>
                    <label>C1 = Top Priority Customer</label>
                </value>
                <value>
                    <fullName>C2</fullName>
                    <label>C2 = Medium Priority Customer</label>
                </value>
                <value>
                    <fullName>C3</fullName>
                    <label>C3 = Established Customer</label>
                </value>
                <value>
                    <fullName>C4</fullName>
                    <label>C4 = Customer - PPP Onboarding</label>
                </value>
                <value>
                    <fullName>COI</fullName>
                    <label>COI = Center of Influence</label>
                </value>
                <value>
                    <fullName>NQ</fullName>
                    <label>NQ = Middle Market (Revenue $10MM to $260MM)</label>
                </value>
                <value>
                    <fullName>NQ0</fullName>
                    <label>NQ0 = Companies with Unknown Revenue</label>
                </value>
                <value>
                    <fullName>NQBB</fullName>
                    <label>NQBB = Companies with Revenue $1.00MM to $9.99MM</label>
                </value>
                <value>
                    <fullName>NQSB</fullName>
                    <label>NQSB = Companies with Revenue under $1MM</label>
                </value>
                <value>
                    <fullName>P1</fullName>
                    <label>P1 = Proposing within 6 months/Top Prospect</label>
                </value>
                <value>
                    <fullName>P2</fullName>
                    <label>P2 = Proposing in 6-12 months</label>
                </value>
                <value>
                    <fullName>P3</fullName>
                    <label>P3 = Proposing outside 12 months</label>
                </value>
                <value>
                    <fullName>P4</fullName>
                    <label>P4 = Other</label>
                </value>
                <value>
                    <fullName>P5</fullName>
                    <label>P5 = PPP Lead</label>
                </value>
                <value>
                    <fullName>X1</fullName>
                    <label>X1 = EdFAC</label>
                </value>
                <value>
                    <fullName>X2</fullName>
                    <label>X2 = Bankrupt/Out of Business</label>
                </value>
                <value>
                    <fullName>X3</fullName>
                    <label>X3 = Industry Excluded</label>
                </value>
                <value>
                    <fullName>X4</fullName>
                    <label>X4 = Subsidiary</label>
                </value>
                <value>
                    <fullName>X5</fullName>
                    <label>X5 = Potential Duplicate</label>
                </value>
                <value>
                    <fullName>X6</fullName>
                    <label>X6 = Other</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_First_Date_Of_Contact__c</fullName>
        <description>Created as part of DBSFCRM-771 to populate Roll up First Date Of Contact</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First Date Of Contact</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WT_Last_Date_Of_Contact__c</fullName>
        <description>Created as part of DBSFCRM-771 to populate Last Date Of Contact</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Date Of Contact</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WT_Primary_Email_DNB__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Email (DNB)</label>
        <type>Email</type>
    </fields>
    <recordTypes>
        <fullName>BusinessAccount_Customer</fullName>
        <active>true</active>
        <label>Business Account (Customer)</label>
    </recordTypes>
    <recordTypes>
        <fullName>Relationship_Group</fullName>
        <active>true</active>
        <label>Relationship Group</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__AccountAccountRelation__c.object
<CustomObject>
    <description>A relationship between two accounts, such as a household and a business account.</description>
    <fields>
        <fullName>FinServ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>RelatedFromAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>RelatedToAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__Role__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Related Role</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>FinServ__ReciprocalRole__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Account Role</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>FinServ__ReciprocalRole__c</referenceTo>
        <relationshipName>AccountReciprocalRole</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account-Account Relationship</label>
    <nameField>
        <displayFormat>R-{000000000}</displayFormat>
        <label>Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Account Relations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__FinancialAccountNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Account Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/FinServ__FinancialAccountRole__c.object
<CustomObject>
    <description>Represents the role occupied by a person or organizational entity that is involved with a financial account, such as a beneficiary or trustee.</description>
    <fields>
        <fullName>FinServ__FinancialAccount__c</fullName>
        <description>Financial account that this role is related to.</description>
        <label>Financial Account</label>
        <referenceTo>FinServ__FinancialAccount__c</referenceTo>
        <relationshipLabel>Financial Account Roles</relationshipLabel>
        <relationshipName>FinancialAccountRoles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FinServ__RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Name of the organizational entity that is involved with the financial account.</description>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Roles</relationshipLabel>
        <relationshipName>FinancialAccountRoles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FinServ__Role__c</fullName>
        <description>Role that describes how the organizational entity or person is involved with the financial account.</description>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Beneficial Owner</fullName>
                </value>
                <value>
                    <fullName>Committee Member</fullName>
                </value>
                <value>
                    <fullName>Primary</fullName>
                </value>
                <value>
                    <fullName>Additional Obligator</fullName>
                </value>
                <value>
                    <fullName>Authority Signor</fullName>
                </value>
                <value>
                    <fullName>CEO</fullName>
                </value>
                <value>
                    <fullName>Co-Borrower</fullName>
                </value>
                <value>
                    <fullName>Guarantor</fullName>
                </value>
                <value>
                    <fullName>President</fullName>
                </value>
                <value>
                    <fullName>Borrower</fullName>
                </value>
                <value>
                    <fullName>Co-Maker</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Llc</fullName>
                </value>
                <value>
                    <fullName>Administrator</fullName>
                </value>
                <value>
                    <fullName>Agent</fullName>
                </value>
                <value>
                    <fullName>Aka</fullName>
                </value>
                <value>
                    <fullName>Association</fullName>
                </value>
                <value>
                    <fullName>Assistant Director</fullName>
                </value>
                <value>
                    <fullName>Attorney</fullName>
                </value>
                <value>
                    <fullName>Auth. Agent For</fullName>
                </value>
                <value>
                    <fullName>Authority Signor - Non Owner</fullName>
                </value>
                <value>
                    <fullName>Bankrupt</fullName>
                </value>
                <value>
                    <fullName>Bene Ira</fullName>
                </value>
                <value>
                    <fullName>Beneficiary</fullName>
                </value>
                <value>
                    <fullName>Beneficiary Non</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>By</fullName>
                </value>
                <value>
                    <fullName>Education Saving Account</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>Chairman</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Financial Account Role</label>
    <nameField>
        <displayFormat>FAR-{000000000}</displayFormat>
        <label>Role Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Account Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/FinServ__ReciprocalRole__c.object
<CustomObject>
    <description>Represents the other entity’s corresponding role in a one-to-one relationship between entities.</description>
    <fields>
        <fullName>FinServ__CreateInverseRole__c</fullName>
        <defaultValue>true</defaultValue>
        <description>When checked, a new inverse role is created for the role.</description>
        <inlineHelpText>If checked, a corresponding inverse role is automatically created.</inlineHelpText>
        <label>Create Inverse Role</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FinServ__InverseRole__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Inverse Role</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Reciprocal Role</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Role</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reciprocal Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>FinServ__RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Related Leads</relationshipLabel>
        <relationshipName>RelatedLeads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Account_Referred_Email__c</fullName>
        <description>This field is used to map the Account Email based on RecordType. This field is used in BeforeTrigger on Referral Object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Referred Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/WT_AccountAfterHandler_T.cls
/**
* --------------------------------------------------------------------------------------------------------------
* @Name				WT_AccountAfterHandler_T
* @Author			Karishma Keswani	<kkeswani@wintrust.com>
* @ModifiedBy		Karishma Keswani	<kkeswani@wintrust.com>
* @Version			v1.0
* @CreatedDate		07-12-2020
* --------------------------------------------------------------------------------------------------------------
* @Description
* This is test class for after handler class for WT_AccountAfterHandler.
* ---------------------------------------------------------------------------------------------------------------------------------------------------
* FUNCTIONAL TEST LOGIC
* 1- runCreateCoveragePlan() 
* 	> used to test the creation of Coverage Plan on the account classification.
* 2- runCreateCoveragePlanAccountUpdate()
*   > used to test the update of account record by populating classfication. This should create action plan.
* 3- runRestrictAccountsMerge()
*   > used to test the restriction of merging of Customer Account into Prospect
* ----------------------------------------------------------------------------------------------------------------------------------------------------
**/
@isTest
public class WT_AccountAfterHandler_T 
{
    @isTest(SeeAllData=true)     
    public static void runCreateCoveragePlan() 
    {        
        User userRecord = WT_DataFactory.createUser('WT Retail');
        insert userRecord;
        List <Account> listNewClassifiedAccount = WT_DataFactory.createNonPersonAccounts(10,'IndustriesBusiness',userRecord.Id);
        for(Account accountRecord: listNewClassifiedAccount)
        {
            accountRecord.WT_Classification__c = 'P1';
        }
        test.startTest();
        insert listNewClassifiedAccount;
        test.stopTest();
        List<ActionPlan> listactionPlanRecords = new List<ActionPlan>();
        listactionPlanRecords = [Select id from actionplan where TargetId in:listNewClassifiedAccount];
        //system.assertNotEquals(0, listactionPlanRecords.size());
    }
    @isTest(SeeAllData=true)     
    public static void runCreateCoveragePlanAccountUpdate() 
    {
        User userRecord = WT_DataFactory.createUser('WT Retail');
        insert userRecord;
        List <Account> listNewClassifiedAccount = WT_DataFactory.createNonPersonAccounts(10,'IndustriesBusiness',userRecord.Id);
        insert listNewClassifiedAccount;
        List<ActionPlan> listactionPlanRecords = new List<ActionPlan>();
        listactionPlanRecords = [Select id from actionplan where TargetId in:listNewClassifiedAccount];
        system.assertEquals(0, listactionPlanRecords.size());
        for(Account accountRecord: listNewClassifiedAccount)
        {
            accountRecord.WT_Classification__c = 'P1';
        }
        test.startTest();
        update listNewClassifiedAccount;
        test.stopTest();
        listactionPlanRecords = [Select id from actionplan where TargetId in:listNewClassifiedAccount];
        //system.assertNotEquals(0, listactionPlanRecords.size());
    }
    //Krupa added
     @isTest
    public static void updateMapAccountToReferral() 
    {
        User userRecord1 = WT_DataFactory.createUser('System Administrator');
        insert userRecord1;
        User userRecord2 = WT_DataFactory.createUser('System Administrator');
        insert userRecord2;
        User userRecord3 = WT_DataFactory.createUser('System Administrator');
        insert userRecord3;
        
        List<Account> listPersonAccount = WT_DataFactory.createAccounts(1,'PersonAccount_Customer',userRecord1.Id);
        listPersonAccount[0].PersonEmail = 'abc@gmail.com';
        insert listPersonAccount;
        
        List<Lead> listLead = WT_DataFactory.createLead(1,userRecord1.Id,userRecord2.Id,userRecord3.Id);
        listLead[0].FinServ__RelatedAccount__c = listPersonAccount[0].Id;
        insert listLead;
        
        listPersonAccount[0].PersonHomePhone = '7899876787';
        listPersonAccount[0].PersonEmail = 'abc123@gmail.com';
        update listPersonAccount;
        
        Lead insertedLead = [SELECT Id,
                             Phone,
                             WT_Account_Referred_Email__c
                             FROM Lead
                             WHERE Id = :listLead[0].Id];
        
        System.assertEquals('7899876787', insertedLead.Phone, 'Phone Matched');
        System.assertEquals('abc123@gmail.com', insertedLead.WT_Account_Referred_Email__c, 'Email Matched');
    }
    
    //Krupa added
    @isTest
    public static void updateMapBusinessAccountToReferral() 
    {
        User userRecord1 = WT_DataFactory.createUser('System Administrator'); 
        insert userRecord1;
        User userRecord2 = WT_DataFactory.createUser('System Administrator');
        insert userRecord2;
        User userRecord3 = WT_DataFactory.createUser('System Administrator');
        insert userRecord3;
        
        List<Account> listBusinessAccount = WT_DataFactory.createNonPersonAccounts(1,'BusinessAccount_Customer', userRecord1.Id);
        listBusinessAccount[0].WT_Primary_Email_DNB__c = 'abc2@gmail.com'; 
        insert listBusinessAccount;
        
        List<Lead> listLead = WT_DataFactory.createLead(1,userRecord1.Id,userRecord2.Id,userRecord3.Id);
        listLead[0].FinServ__RelatedAccount__c = listBusinessAccount[0].Id;
        insert listLead; 
        
        listBusinessAccount[0].Phone = '7890987898';
        listBusinessAccount[0].WT_Primary_Email_DNB__c = 'fjjf@gmail.com';
        update listBusinessAccount;
        
        Lead insertedLead = [SELECT Id,
                             Phone,
                             WT_Account_Referred_Email__c
                             FROM Lead
                             WHERE Id = :listLead[0].Id];
        
        System.assertEquals('7890987898', insertedLead.Phone, 'Phone Matched');
        System.assertEquals('fjjf@gmail.com', insertedLead.WT_Account_Referred_Email__c, 'Email Matched');
    }
    
    @isTest
    public static void runRestrictAccountsMerge() 
    {
        User userRecord = WT_DataFactory.createUser('System Administrator');
        insert userRecord;
        List<Account> listCustomerAccount = WT_DataFactory.createAccounts(1,'PersonAccount_Customer',userRecord.Id);
        insert listCustomerAccount;
        List<Account> listProspectAccount = WT_DataFactory.createAccounts(1,'PersonAccount_Prospect',userRecord.Id);
        insert listProspectAccount;        
        WT_DataFactory.createRequiredCustomSetting();
        try
        {
            test.startTest();
            merge listProspectAccount[0] listCustomerAccount;
            test.stopTest();
        }
        catch(exception e){
            Boolean expectedExceptionThrown =  e.getMessage().contains(System.Label.WT_Account_Error_on_Merge) ? true : false;
            system.assertEquals(expectedExceptionThrown,true);
        }        
    }
    
    @isTest
    public static void runupdateInteractionDatesonAccount() 
    {
        
        User userRecord = WT_DataFactory.createUser('WT Retail');
        insert userRecord;
        List <Account> listAccounts = WT_DataFactory.createAccounts(1,'PersonAccount_Customer',userRecord.Id);
        insert listAccounts;
        List<Account> listCustomerAccount = WT_DataFactory.createNonPersonAccounts(2,'IndustriesHousehold',userRecord.Id);
        listCustomerAccount[1].FinServ__NextReview__c=Date.today()-5;
        insert listCustomerAccount;
        
        FinServ__FinancialAccount__c finAccount=new FinServ__FinancialAccount__c();
        finAccount.FinServ__FinancialAccountNumber__c='217981230';
        finAccount.FinServ__PrimaryOwner__c=listAccounts[0].Id;
        insert finAccount;
        
        FinServ__FinancialAccountRole__c FinAccountRole=new FinServ__FinancialAccountRole__c();
        FinAccountRole.FinServ__RelatedAccount__c=listCustomerAccount[1].id;
        FinAccountRole.FinServ__FinancialAccount__c=finAccount.Id;
        FinAccountRole.FinServ__Role__c='Beneficiary';
        insert FinAccountRole;
        
        FinServ__ReciprocalRole__c finRole=new FinServ__ReciprocalRole__c();
        finRole.FinServ__CreateInverseRole__c=true;
        finRole.FinServ__InverseRole__c='Client';
        insert finRole;
        
        FinServ__AccountAccountRelation__c finAcc=new FinServ__AccountAccountRelation__c();
        finAcc.FinServ__Account__c=listCustomerAccount[0].Id;
        finAcc.FinServ__RelatedAccount__c=listCustomerAccount[1].Id;
        finAcc.FinServ__Role__c=finRole.Id;
        insert finAcc;
        
        WT_DataFactory.createRequiredCustomSetting();
        test.startTest();
        listCustomerAccount[0].FinServ__NextReview__c=Date.today();
        update listCustomerAccount[0];
        test.stopTest();
        Account testAccount=[Select Id,FinServ__NextReview__c from Account where Id=:listCustomerAccount[1].Id];
        system.assertEquals(testAccount.FinServ__NextReview__c,Date.today()-5);
        
    }
    
    @isTest
    public static void runupdateInteractionDatesonHouseHold() 
    {
        
        User userCreateRecord = WT_DataFactory.createUser('System Administrator');
        insert userCreateRecord;
        WT_DataFactory.createRequiredCustomSetting();
        system.runAs(userCreateRecord)
        {
            List <Account> listNewClassifiedAccount = WT_DataFactory.createNonPersonAccounts(1,'IndustriesHousehold',userCreateRecord.id);
            insert listNewClassifiedAccount[0];
            List <Account> listNewPersonAccount = WT_DataFactory.createAccounts(1,'PersonAccount_Customer',userCreateRecord.id);
            insert listNewPersonAccount;
            listNewPersonAccount[0].FinServ__LastInteraction__c=Date.today();
            listNewPersonAccount[0].FinServ__NextInteraction__c=Date.today();
            listNewPersonAccount[0].WT_Parent_Household__pc=listNewClassifiedAccount[0].Id;
            listNewPersonAccount[0].WT_First_Date_Of_Contact__c=Date.today();
            listNewPersonAccount[0].WT_Last_Date_Of_Contact__c=Date.today();
            update listNewPersonAccount[0];
            
            Contact con=[Select Id,AccountId from contact where AccountId=:listNewPersonAccount[0].Id];
            
            AccountContactRelation acr = new AccountContactRelation(); 
            acr.Accountid = listNewClassifiedAccount[0].id;
            acr.Contactid = con.Id;
            insert acr;
            Test.startTest();
            listNewPersonAccount[0].FinServ__LastInteraction__c=Date.today()+5;
            listNewPersonAccount[0].FinServ__NextInteraction__c=Date.today()-5;
            listNewPersonAccount[0].PersonHomePhone='9999999999';
            listNewPersonAccount[0].Phone='9999999999';
            update listNewPersonAccount[0];
            Test.stopTest();
        }
    }
    
    @isTest
    public static void runupdateInteractionDatesOnRelationGroup() 
    {
        User userCreateRecord = WT_DataFactory.createUser('System Administrator');
        insert userCreateRecord;
        WT_DataFactory.createRequiredCustomSetting();
        system.runAs(userCreateRecord)
        {
            List <Account> listNewClassifiedAccount = WT_DataFactory.createNonPersonAccounts(1,'Relationship_Group',userCreateRecord.id);
            insert listNewClassifiedAccount[0];
            List <Account> listNewBusinessAccount = WT_DataFactory.createNonPersonAccounts(1,'IndustriesBusiness',userCreateRecord.id);
            insert listNewBusinessAccount;
            
            listNewBusinessAccount[0].FinServ__LastInteraction__c=Date.today();
            listNewBusinessAccount[0].FinServ__NextInteraction__c=Date.today();
            update listNewBusinessAccount[0];
            
            FinServ__FinancialAccount__c finAccount=new FinServ__FinancialAccount__c();
            finAccount.FinServ__FinancialAccountNumber__c='217981230';
            finAccount.FinServ__PrimaryOwner__c=listNewClassifiedAccount[0].Id;
            insert finAccount;
            
            FinServ__FinancialAccountRole__c FinAccountRole=new FinServ__FinancialAccountRole__c();
            FinAccountRole.FinServ__RelatedAccount__c=listNewBusinessAccount[0].id;
            FinAccountRole.FinServ__FinancialAccount__c=finAccount.Id;
            FinAccountRole.FinServ__Role__c='Beneficiary';
            insert FinAccountRole;
            
            FinServ__ReciprocalRole__c finRole=new FinServ__ReciprocalRole__c();
            finRole.FinServ__CreateInverseRole__c=true;
            finRole.FinServ__InverseRole__c='Client';
            insert finRole;
            
            FinServ__AccountAccountRelation__c AAR = new FinServ__AccountAccountRelation__c(); 
            AAR.FinServ__Account__c = listNewClassifiedAccount[0].id;
            AAR.FinServ__RelatedAccount__c = listNewBusinessAccount[0].Id;
            AAR.FinServ__Role__c=finRole.Id;
            insert AAR;
            
            Test.startTest();
            listNewBusinessAccount[0].FinServ__LastInteraction__c=Date.today()+5;
            listNewBusinessAccount[0].FinServ__NextInteraction__c=Date.today()-5;
            update listNewBusinessAccount[0];
            Test.stopTest();
        }
    }
}