objects/Account.object
<CustomObject>
    <fields>
        <fullName>FinServ__ReferredByUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Referrer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>AccountEmployeeReferrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Branch__c</fullName>
        <description>Created as a part of DBSFCRM-122</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Branch #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>FinServ__ReferredByUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Referrer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserType</field>
                <operation>equals</operation>
                <value>Standard</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>LeadUserReferrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Referral_Business_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Branch Factor Location</label>
        <referenceTo>WT_Business_Unit_Entity__c</referenceTo>
        <relationshipLabel>Leads &amp; Referrals</relationshipLabel>
        <relationshipName>Leads_Referrals</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>WT_Wealth</fullName>
        <active>true</active>
        <businessProcess>Referral Process</businessProcess>
        <label>Wealth</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>WT_Branch__c</fullName>
        <description>Branch Number of the User</description>
        <label>Branch #</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>WT_Fusion_Feed_Branch</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Business_Unit_Entity__c</fullName>
        <description>reference to Business Unit Entity</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Branch Factor</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WT_Business_Unit_Entity__c.object
<CustomObject>
    <fields>
        <fullName>WT_Bank_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Branch__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Branch</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Branch Factor</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Business Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch Factors</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/WT_Fusion_Feed_Branch.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>118001</fullName>
    </customValue>
    <customValue>
        <fullName>118002</fullName>
    </customValue>
    <customValue>
        <fullName>118003</fullName>
    </customValue>
    <customValue>
        <fullName>118004</fullName>
    </customValue>
    <customValue>
        <fullName>118005</fullName>
    </customValue>
    <customValue>
        <fullName>118006</fullName>
    </customValue>
    <customValue>
        <fullName>118007</fullName>
    </customValue>
    <customValue>
        <fullName>118009</fullName>
    </customValue>
    <customValue>
        <fullName>118010</fullName>
    </customValue>
    <customValue>
        <fullName>118011</fullName>
    </customValue>
    <customValue>
        <fullName>118012</fullName>
    </customValue>
    <customValue>
        <fullName>118014</fullName>
    </customValue>
    <customValue>
        <fullName>118015</fullName>
    </customValue>
    <customValue>
        <fullName>118016</fullName>
    </customValue>
    <customValue>
        <fullName>118017</fullName>
    </customValue>
    <customValue>
        <fullName>118018</fullName>
    </customValue>
    <customValue>
        <fullName>118019</fullName>
    </customValue>
    <customValue>
        <fullName>118021</fullName>
    </customValue>
    <customValue>
        <fullName>118022</fullName>
    </customValue>
    <customValue>
        <fullName>118023</fullName>
    </customValue>
    <customValue>
        <fullName>118024</fullName>
    </customValue>
    <customValue>
        <fullName>118026</fullName>
    </customValue>
    <customValue>
        <fullName>118027</fullName>
    </customValue>
    <customValue>
        <fullName>118029</fullName>
    </customValue>
    <customValue>
        <fullName>118030</fullName>
    </customValue>
    <customValue>
        <fullName>158001</fullName>
    </customValue>
    <customValue>
        <fullName>158003</fullName>
    </customValue>
    <customValue>
        <fullName>158004</fullName>
    </customValue>
    <customValue>
        <fullName>158005</fullName>
    </customValue>
    <customValue>
        <fullName>158006</fullName>
    </customValue>
    <masterLabel>Fusion Feed Branch #</masterLabel>
</GlobalValueSet>

classes/WT_ReferralNewOverrideController_T.cls
/**
 * -------------------------------------------------------------------------------------------------------------------------------------------------
 * @Name			WT_ReferralNewOverrideController_T
 * @Author			Swaminathan E	<SEzhumal@wintrust.com>
 * @version 		v1.0 
 * @CreatedDate		08-12-2020
 * ---------------------------------------------------------------------------------------------------------------------------------------------------
 * @Description 
 * Class is used as test class for WT_ReferralNewOverrideController 
 * ---------------------------------------------------------------------------------------------------------------------------------------------------
 * FUNCTIONAL TEST LOGIC
 *  executeHandler()
 * 	> used to run the Apex class for the WT_DatePaidController , generally for code coverage.
 * ----------------------------------------------------------------------------------------------------------------------------------------------------
**/
@isTest
public class WT_ReferralNewOverrideController_T 
{
    static testMethod void executeHandler() 
    {
        List<Lead> recordList = new List<Lead>();        
        Profile p = [SELECT Id FROM Profile WHERE Name='WT Retail']; 
        User user = new User(Alias = 'stdtes', Email='standarduser123@testorg.com', 
                            EmailEncodingKey='UTF-8', LastName='Test12345', LanguageLocaleKey='en_US', 
                            LocaleSidKey='en_US', ProfileId = p.Id, 
                            TimeZoneSidKey='America/Los_Angeles', UserName='stdtest12345@test1.com' ,
                            WT_Business_Unit_Entity__c='118-1');
        insert user ;
        WT_Business_Unit_Entity__c businessUnitRecord = new WT_Business_Unit_Entity__c(Name = '118-1', WT_Bank_Number__c = '118',
                                                                                       WT_Branch__c = '1');
        insert businessUnitRecord;
        Account accountRecord = new Account();
        accountRecord.LastName = 'Test1';
        accountRecord.type = 'Prospect';
        accountRecord.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount_Prospect').getRecordTypeId();
        Lead leadRecord2 = new Lead();
        leadRecord2.FinServ__ReferredByUser__c = user.Id;
        leadRecord2.LastName = 'Referral Record2';
        leadRecord2.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('WT_Wealth').getRecordTypeId();
        Lead leadRecord3 = new Lead();
        leadRecord3.FinServ__ReferredByUser__c = user.Id;
        leadRecord3.LastName = 'Referral Record3';
        leadRecord3.RecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByDeveloperName().get('WT_Wealth').getRecordTypeId();
        leadRecord3.WT_Referral_Business_Unit__c = businessUnitRecord.id;
        recordList.add(leadRecord2);
        recordList.add(leadRecord3);
        insert accountRecord;       
        insert recordList;
        Test.startTest();
        WT_ReferralNewOverrideController.getPrePopulateValue();
        WT_ReferralNewOverrideController.populateName(accountRecord.id);
        WT_ReferralNewOverrideController.findRecords('t','User','');
        Test.stopTest();
    }
}