objects/Account.object
<CustomObject>
    <fields>
        <fullName>WT_Primary_Officer_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Officer Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>BusinessAccount_Customer</fullName>
        <active>true</active>
        <label>Business Account (Customer)</label>
    </recordTypes>
    <recordTypes>
        <fullName>Relationship_Group</fullName>
        <active>true</active>
        <label>Relationship Group</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WT_Bank_Officer_Lookup__c.object
<CustomObject>
    <description>This object holds the officer code lookup between source system code and Salesforce User Id</description>
    <fields>
        <fullName>WT_Unique_Officer_Code__c</fullName>
        <formula>IF(TEXT(WT_Source_System__c) = &apos;FIS&apos;, WT_Officer_Code__c + &apos;|&apos; + WT_Branch_Code__c ,
IF(TEXT(WT_Source_System__c) = &apos;Trust&apos;, WT_Branch_Code__c + WT_Officer_Code__c ,
IF(TEXT(WT_Source_System__c) = &apos;Wealth&apos;, WT_Branch_Code__c + WT_Officer_Code__c ,
IF(TEXT(WT_Source_System__c) = &apos;Encompass&apos;, WT_Officer_Code__c , WT_Officer_Code__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Officer Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bank_Officer_Lookups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Officer Lookup</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Bank Officer Lookup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Officer Lookups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_BatchBankOfficerAccountReconciliation.cls
//Code Coverage: WT_BatchBankOfficerAcctReconciliation_T
//Scheduler: WT_BatchBankOfficerAcctReconciliationSch
//This batch class is used to reconcile Account record Ownership with the Bank Officer Lookup object
//Bank Officer Lookup can be updated anytime but that doesn't necessarily trigger an update to the account
//This batch would ensure that both objects are always in sync
global class WT_BatchBankOfficerAccountReconciliation implements Database.Batchable<sObject>
{
    //Grab all account records that are of type Person Account (Customer), Business Account (Customer), Household, or Relationship Group
    //We would not grab prospects because MDM would not have owner information for those records
    global Database.QueryLocator start(Database.BatchableContext batchContext) 
    {
        Id personAcountCustomerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount_Customer').getRecordTypeId();
        Id businessAccountCustomerRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('BusinessAccount_Customer').getRecordTypeId();
        Id householdRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('IndustriesHousehold').getRecordTypeId();
        Id relationshipGroupRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Relationship_Group').getRecordTypeId();
        
        Set<Id> setRecordTypeId = new Set<Id>
        {
            personAcountCustomerRecordTypeId,
                businessAccountCustomerRecordTypeId,
                householdRecordTypeId,
                relationshipGroupRecordTypeId
        };
            //Return the query with all accounts
            return Database.getQueryLocator([SELECT Id,
                                             OwnerId,
                                             RecordTypeId,
                                             WT_Primary_Officer_Number__c
                                             FROM Account
                                             WHERE RecordTypeId IN :setRecordTypeId
                                             AND WT_Primary_Officer_Number__c != NULL
                                             AND WT_Primary_Officer_Number__c != '']);
    }
    
    global void execute(Database.BatchableContext batchContext, List<Account> scope)
    {
        List<Account> listAccountToUpdate = new List<Account>();
        Map<String, Id> mapBankOfficerCodeAndUserId = new Map<String, Id>();
        Set<String> setUniqueOfficerCode = new Set<String>();
        for(Account accountToReconcile : scope)
        {
            setUniqueOfficerCode.add(accountToReconcile.WT_Primary_Officer_Number__c);
        }
        
        if(!setUniqueOfficerCode.isEmpty())
        {
            for(WT_Bank_Officer_Lookup__c relatedBankOfficerLookup : [SELECT Id,
                                                                      WT_Unique_Officer_Code__c,
                                                                      WT_User__c
                                                                      FROM WT_Bank_Officer_Lookup__c
                                                                      WHERE WT_User__c != null])
            {
                mapBankOfficerCodeAndUserId.put(relatedBankOfficerLookup.WT_Unique_Officer_Code__c, relatedBankOfficerLookup.WT_User__c);
            }
        }
        
        if(!mapBankOfficerCodeAndUserId.isEmpty())
        {
            for(Account accountToReconcile : scope)
            {
                if(mapBankOfficerCodeAndUserId.containsKey(accountToReconcile.WT_Primary_Officer_Number__c) &&
                   mapBankOfficerCodeAndUserId.get(accountToReconcile.WT_Primary_Officer_Number__c) != accountToReconcile.OwnerId)
                {
                    accountToReconcile.OwnerId = mapBankOfficerCodeAndUserId.get(accountToReconcile.WT_Primary_Officer_Number__c);
                    listAccountToUpdate.add(accountToReconcile);
                }
            }
        }
        
        if(!listAccountToUpdate.isEmpty())
        {
            TriggerHandler.bypass('WT_AccountBeforeHandler');
            TriggerHandler.bypass('WT_AccountAfterHandler');
            TriggerHandler.bypass('WT_AccountAfterRequiredHandler');
            
            update listAccountToUpdate;
        }
    }
    
    global void finish(Database.BatchableContext batchContext)
    {
        
    } 
}