objects/ACHConfigurations__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to ACHConfigurations</description>
    <fields>
        <fullName>Brand__c</fullName>
        <description>Brand Description</description>
        <label>Brand</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>ACHConfigurations</label>
    <pluralLabel>ACHConfigurations</pluralLabel>
</CustomObject>

objects/ContentVersion.object
<CustomObject>
    <description>Configurations related to ACH files</description>
    <fields>
        <fullName>FileTransferStatus__c</fullName>
        <description>File transfer Status to external system</description>
        <label>File transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FileTransferStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Nacha_Config__mdt.object
<CustomObject>
    <description>Configurations needed for API call for Nacha File transfer</description>
    <fields>
        <fullName>Max_Retry_Count__c</fullName>
        <description>Retry Count for Nacha File transfer batch processing</description>
        <label>Max Retry Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Nacha Config</label>
    <pluralLabel>Nacha Config</pluralLabel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The final generated account number. This will be set only after the final account number is available as part of the response of an account open API call.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Brand__c</fullName>
        <description>Brand code of the Brand for the submission if applicable</description>
        <formula>tffa__Submission__r.tffa__Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product code identifier.</description>
        <label>Financial Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR (4 AND 5))</booleanFilter>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>$Source.tffa__ProductCategory__c</field>
                <operation>equals</operation>
                <valueField>tffa__Product__c.tffa__Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value>In Progress</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the application</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__FundingRequest__c.object
<CustomObject>
    <description>Supports the capture of details pertaining to funding a payment obligation using one of the various available sources of funding</description>
    <fields>
        <fullName>ACHReportGenerated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To indicate if this funding record is reported in ACH Report</description>
        <label>ACH Report Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsCoreEntryComplete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if Core Entry is Comeplete</description>
        <label>Core Entry Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsObsolete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if Funding is Obsolete</description>
        <label>Obsolete Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The account number which needs to be debited for this funding request</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LinkedApplication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to application.</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Funding Requests</relationshipLabel>
        <relationshipName>LinkedFundingRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Funding status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__FundingStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to parent submission.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Consolidated Funding Requests</relationshipLabel>
        <relationshipName>FundingRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of funding selected for the current application.</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__FundingType</valueSetName>
        </valueSet>
    </fields>
    <label>Funding Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__Brand__c</fullName>
        <description>Brand code of the Brand for the submission if applicable</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the submission</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UploadFileHistory__c.object
<CustomObject>
    <description>the file</description>
    <fields>
        <fullName>FileTransferRetryCount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>File Transfer Retry Count</description>
        <label>File Transfer Retry Count</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FileTransferStatus__c</fullName>
        <description>File Transfer Status</description>
        <label>File Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FileTransferStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>FileType__c</fullName>
        <description>Filetype C: Credit, D: Debit</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FileType</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Upload File History</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Upload File History</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upload File History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/FileTransferStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
    </customValue>
    <customValue>
        <fullName>Resend</fullName>
    </customValue>
    <customValue>
        <fullName>Created</fullName>
    </customValue>
    <customValue>
        <fullName>No Document</fullName>
    </customValue>
    <masterLabel>FileTransferStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__FundingStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>FUNDED</fullName>
        <label>Funded</label>
    </customValue>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
        <label>Failed</label>
    </customValue>
    <customValue>
        <fullName>APPROVAL</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>REVERSED</fullName>
        <label>Reversed</label>
    </customValue>
    <customValue>
        <fullName>REVERSAL_FAILED</fullName>
        <label>Reversal Failed</label>
    </customValue>
    <customValue>
        <fullName>ACH_FILE_GENERATED</fullName>
        <label>ACH File Generated</label>
    </customValue>
    <customValue>
        <fullName>ACH_FILE_FAILED</fullName>
        <label>ACH File Generation Failed</label>
    </customValue>
    <customValue>
        <fullName>HOLD_APPLIED</fullName>
        <label>Hold Applied on Funds</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>REVERSAL_NOT_REQ</fullName>
        <label>Reversal Not Required</label>
    </customValue>
    <customValue>
        <fullName>AUTHORIZED</fullName>
        <isActive>false</isActive>
        <label>AUTHORIZED</label>
    </customValue>
    <description>Status of funding</description>
    <masterLabel>FundingStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__FundingType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACH</fullName>
    </customValue>
    <customValue>
        <fullName>WIRE</fullName>
        <label>Wire Transfer</label>
    </customValue>
    <customValue>
        <fullName>CASH</fullName>
        <label>Branch or ATM Deposit</label>
    </customValue>
    <customValue>
        <fullName>DEBIT_CARD</fullName>
        <label>DEBIT CARD</label>
    </customValue>
    <customValue>
        <fullName>INTERNAL_TRANSFER</fullName>
        <label>INTERNAL TRANSFER</label>
    </customValue>
    <customValue>
        <fullName>APPLE_PAY</fullName>
        <isActive>false</isActive>
        <label>APPLE_PAY</label>
    </customValue>
    <customValue>
        <fullName>GOOGLE_PAY</fullName>
        <isActive>false</isActive>
        <label>GOOGLE_PAY</label>
    </customValue>
    <customValue>
        <fullName>CHECK</fullName>
        <isActive>false</isActive>
        <label>CHECK</label>
    </customValue>
    <customValue>
        <fullName>CREDIT_CARD</fullName>
        <isActive>false</isActive>
        <label>CREDIT_CARD</label>
    </customValue>
    <customValue>
        <fullName>PAYPAL</fullName>
        <isActive>false</isActive>
        <label>PAYPAL</label>
    </customValue>
    <description>Type of funding selected for the current deposit application.</description>
    <masterLabel>FundingType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>ABANDONED</fullName>
        <label>Abandoned</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>SAVED</fullName>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>SUBMITTED</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>Indicates current status of the submission.This will be computed and be useful for regulations.</description>
    <masterLabel>SubmissionStatus</masterLabel>
</GlobalValueSet>

classes/CZWTFCACHRepository.cls
/**
 * Copyright (c) 2020 Terafina Inc
 * @group  Repository
 * @description ACH repository
 **/
public with sharing class CZWTFCACHRepository extends tffa.AbstractRepository {
  private static final String STATUS_FUNDED = 'FUNDED';
  private static final String ACH_DEBIT = 'ACH_Debit%';

  /**
   * @description used for retrieving contentversion
   * @param String id
   * @return ContentVersion
   **/
  public static ContentVersion findContentVersion(String id) {
    List<String> queryParams = new List<String>();
    queryParams.add(id);
    String q = new tffa.QueryBuilder(ContentVersion.SObjectType).selectFields().build().whereClause('Id', '=:attr1').build().toQuery();
    List<ContentVersion> l = doQuery(q, queryParams);
    return l.isEmpty() ? null : l[0];
  }

  /**
   * @description used for retrieving content workspace
   * @param String name
   * @return List<ContentWorkspace>
   **/
  public static ContentWorkspace findContentWorkspace(String name) {
    List<String> queryParams = new List<String>();
    queryParams.add(name);
    String q = new tffa.QueryBuilder(ContentWorkspace.SObjectType)
      .selectFields()
      .build()
      .whereClause('Name', '=:attr1')
      .withLimit(1)
      .build()
      .toQuery();
    List<ContentWorkspace> l = doQuery(q, queryParams);
    return l.isEmpty() ? null : l[0];
  }

  /**
   * @description used for retrieving content folder
   * @param String name
   * @return List<ContentFolder>
   **/
  public static ContentFolder findContentFolder(String name) {
    List<String> queryParams = new List<String>();
    queryParams.add(name);
    String q = new tffa.QueryBuilder(ContentFolder.SObjectType)
      .selectFields()
      .build()
      .whereClause('Name', '=:attr1')
      .withLimit(1)
      .build()
      .toQuery();
    List<ContentFolder> l = doQuery(q, queryParams);
    return l.isEmpty() ? null : l[0];
  }

  /**
   * @description used for retrieving content folder Name
   * @param String docId
   * @return List<ContentFolderMember>
   **/
  public static ContentFolderMember findContentFolderMember(String docId) {
    List<String> queryParams = new List<String>();
    queryParams.add(docId);
    String q = new tffa.QueryBuilder(ContentFolderMember.SObjectType)
      .selectFields()
      .build()
      .whereClause('ChildRecordId', '=:attr1')
      .withLimit(1)
      .build()
      .toQuery();
    List<ContentFolderMember> l = doQuery(q, queryParams);
    return l.isEmpty() ? null : l[0];
  }

  /**
   * @description inserts contentversion
   * @param List<ContentVersion> contentVersion
   **/
  public static void insertItem(List<ContentVersion> contentVersion) {
    doInsert(contentVersion);
  }

  /**
   * @description inserts ach file
   * @param List<UploadFileHistory__c> achFiles
   **/
  public static void insertAchFIle(List<UploadFileHistory__c> achFiles) {
    doInsert(achFiles);
  }

  /**
   * @description inserts documentLink
   * @param List<ContentDocumentLink> contentDocLink
   **/
  public static void insertDocumentLink(List<ContentDocumentLink> contentDocLink) {
    doInsert(contentDocLink);
  }

  /**
   * @description updates folder member
   * @param List<ContentFolderMember> contentFolderName
   **/
  public static void updateFolderMember(List<ContentFolderMember> contentFolderName) {
    doUpsert(contentFolderName);
  }
  /**
   * @description updates ACHFIles
   * @param List<UploadFileHistory__c> achFiles
   **/
  public static void updateAchFiles(List<UploadFileHistory__c> achFiles) {
    doUpsert(achFiles);
  }

  public static List<ContentFolderMember> save(List<ContentFolderMember> entities) {
    return (List<ContentFolderMember>) doUpsert(entities);
  }

  public static List<ContentVersion> getContentVersion() {
    List<String> queryParam = new List<String>();
    String ACH_Debit = '%TRFACH_%';
    queryParam.add(ACH_Debit);
    String achConfig = new tffa.QueryBuilder(ContentVersion.SObjectType)
      .selectFields()
      .whereClause('Title', 'like :attr1')
      .opAnd()
      .whereClause('CreatedDate', '= TODAY')
      .build()
      .toQuery();
    List<ContentVersion> achConfigs = doQuery(achConfig, queryParam);
    return achConfigs;
  }

  public static List<ACHConfigurations__mdt> getMetaData(String brandCode) {
    List<String> queryParam = new List<String>();
    queryParam.add(brandCode);
    String achConfig = new tffa.QueryBuilder(ACHConfigurations__mdt.SObjectType)
      .selectFields()
      .whereClause('Brand__c', '= :attr1')
      .build()
      .toQuery();
    List<ACHConfigurations__mdt> achConfigs = doQuery(achConfig, queryParam);
    return achConfigs;
  }

  public static List<UploadFileHistory__c> fetchACHNachaFileTransferResults() {
    List<String> statuses = new List<String>{ 'Pending', 'Failure' };
    string ACH = 'ACH';
    Nacha_Config__mdt nachaConfig = CZWTFCCustomMetadataRepository.fetchWtfcNachaConfig();
    Double retryCount = (Double) nachaConfig.Max_Retry_Count__c;
    String q = new tffa.QueryBuilder(UploadFileHistory__c.SObjectType)
      .selectFields()
      .whereClause('FileTransferStatus__c', 'in:attr1')
      .opAnd()
      .whereClause('FileType__c', 'like :attr2')
      .opAnd()
      .whereClause('FileTransferRetryCount__c', '< :attr3')
      .build()
      .toQuery();
    return doQuery(q, new List<Object>{ statuses, ACH, retryCount });
  }

  public static List<SObject> getFundingRequestsForACHFileGeneration(String brandCode) {
    String query = new tffa.QueryBuilder(tffa__FundingRequest__c.SObjectType)
      .selectFields()
      .selectObject('tffa__LinkedApplication__r')
      .whereClause('tffa__AccountNumber__c', '!= null')
      .opAnd()
      .whereClause('tffa__Brand__c', '= :attr1')
      .opAnd()
      .selectFields()
      .selectObject('tffa__Product__r')
      .selectFields(new List<String>{ 'Name' })
      .build()
      .build()
      .whereClause('tffa__Status__c', '= :attr2')
      .opAnd()
      .whereClause('tffa__Type__c', '= :attr3')
      .opAnd()
      .whereClause('IsCoreEntryComplete__c', '= true')
      .opAnd()
      .whereClause('IsObsolete__c', '= false')
      .toQuery();

    return doQuery(query, new List<Object>{ brandCode, ACHConstants.FUNDING_IN_PROGRESS, CZWTFCConstants.FUNDING_TYPE_ACH });
  }

  public static List<SObject> getFundingRequestsForACHFileGenerationBatch() {
    String query = new tffa.QueryBuilder(tffa__FundingRequest__c.SObjectType)
      .selectFields()
      .selectObject('tffa__Submission__r')
      .selectFields()
      .build()
      .whereClause('tffa__Type__c', '= :attr1')
      .opAnd()
      .whereClause('ACHReportGenerated__c', '= :attr2')
      .opAnd()
      .whereClause('tffa__Status__c', '!= :attr3')
      .toQuery();

    return doQuery(query, new List<Object>{CZWTFCConstants.FUNDING_TYPE_ACH,false,ACHConstants.FUNDING_IN_PROGRESS});
  }
}