objects/Case.object
<CustomObject>
    <fields>
        <fullName>WT_Date_of_Request_Received__c</fullName>
        <description>Created as part of DBSFCRM-197</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Date of Request Received</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WT_Switch_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting is created for bypassing the execution of Automations and Triggers as and when needed.</description>
    <fields>
        <fullName>WT_Is_Process_Builder_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Process Builder Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WT_Is_Trigger_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Trigger Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WT_Is_Validation_Rule_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Validation Rule Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WT_Is_Workflow_Rule_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Workflow Rule Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Switch Settings</label>
</CustomObject>

classes/WT_AttachmentAfterHandler_T.cls
/**
* --------------------------------------------------------------------------------------------------------------
* @Name             WT_AttachmentAfterHandler_T 
* @Author           Femi Onakoya    <fonakoya@wintrust.com>
* @ModifiedBy       
* @Version          v1.0
* @CreatedDate      07-18-2022
* @UsedBy           t
* --------------------------------------------------------------------------------------------------------------
* @Description
* This  class to is used to test WT_AttachmentAfterHandler 
* --------------------------------------------------------------------------------------------------------------
* @Changes
* vX.X
* MM-DD-YYYY
* --------------------------------------------------------------------------------------------------------------
**/

@isTest
public class WT_AttachmentAfterHandler_T
{
    
    static testMethod void attachmentConvertTOFileTest()
    {
        WT_Switch_Settings__c switchRecord = new WT_Switch_Settings__c(WT_Is_Process_Builder_Active__c=true,WT_Is_Trigger_Active__c=true,WT_Is_Validation_Rule_Active__c=false,WT_Is_Workflow_Rule_Active__c=true);
        insert switchRecord;
        
        List<Case> listOfCase = new List<case>();
        List<Attachment> listOfAttachment = new List<Attachment>();
        
        case caseRec = new case();
        caseRec.Origin = 'Email';
        caseRec.WT_Date_of_Request_Received__c = system.today();
        listOfCase.add(caseRec);
        INSERT listOfCase;
        
        EmailMessage email = new EmailMessage();
        email.FromAddress = 'test@abc.org';
        email.Incoming = True;
        email.ToAddress= 'test@xyz.org';
        email.Subject = 'Test email';
        email.HtmlBody = 'Test email body';
        email.ParentId = caseRec.Id; 
        email.CreatedDate = system.today();
        INSERT email;
        
        system.assertEquals(email.ParentId, caseRec.Id);
        
        Attachment attachmentRecord=new Attachment();       
        attachmentRecord.Name='Unit Test Attachment';
        Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
        attachmentRecord.body=bodyBlob;
        attachmentRecord.parentId=email.Id;
        attachmentRecord.ContentType = '.Wav';
        listOfAttachment.add(attachmentRecord);
        INSERT listOfAttachment;
        
        System.assertNotEquals(null, listOfAttachment[0].Id);
        
        Test.startTest(); 
        WT_AttachmentAfterHandler handler = new WT_AttachmentAfterHandler();
        handler.listOfNewAttachments = listOfAttachment;
        handler.ConvertAttachmentToFile();
        Test.stopTest();
    }
    
}