objects/ContentVersion.object
<CustomObject>
    <description>Configurations related to ACH files</description>
    <fields>
        <fullName>FileTransferStatus__c</fullName>
        <description>File transfer Status to external system</description>
        <label>File transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FileTransferStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__FundingRequest__c.object
<CustomObject>
    <description>Supports the capture of details pertaining to funding a payment obligation using one of the various available sources of funding</description>
    <fields>
        <fullName>ACHReportGenerated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To indicate if this funding record is reported in ACH Report</description>
        <label>ACH Report Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Funding status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__FundingStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to parent submission.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Consolidated Funding Requests</relationshipLabel>
        <relationshipName>FundingRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of funding selected for the current application.</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__FundingType</valueSetName>
        </valueSet>
    </fields>
    <label>Funding Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__Brand__c</fullName>
        <description>Brand code of the Brand for the submission if applicable</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the submission</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UploadFileHistory__c.object
<CustomObject>
    <description>the file</description>
    <fields>
        <fullName>DocumentId__c</fullName>
        <description>Contains the document id for the file</description>
        <encryptionScheme>None</encryptionScheme>
        <label>DocumentId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FileName__c</fullName>
        <description>File Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FileName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FileTransferStatus__c</fullName>
        <description>File Transfer Status</description>
        <label>File Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FileTransferStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Upload File History</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Upload File History</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upload File History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/FileTransferStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
    </customValue>
    <customValue>
        <fullName>Resend</fullName>
    </customValue>
    <customValue>
        <fullName>Created</fullName>
    </customValue>
    <customValue>
        <fullName>No Document</fullName>
    </customValue>
    <masterLabel>FileTransferStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__FundingStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>FUNDED</fullName>
        <label>Funded</label>
    </customValue>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
        <label>Failed</label>
    </customValue>
    <customValue>
        <fullName>APPROVAL</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>REVERSED</fullName>
        <label>Reversed</label>
    </customValue>
    <customValue>
        <fullName>REVERSAL_FAILED</fullName>
        <label>Reversal Failed</label>
    </customValue>
    <customValue>
        <fullName>ACH_FILE_GENERATED</fullName>
        <label>ACH File Generated</label>
    </customValue>
    <customValue>
        <fullName>ACH_FILE_FAILED</fullName>
        <label>ACH File Generation Failed</label>
    </customValue>
    <customValue>
        <fullName>HOLD_APPLIED</fullName>
        <label>Hold Applied on Funds</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>REVERSAL_NOT_REQ</fullName>
        <label>Reversal Not Required</label>
    </customValue>
    <customValue>
        <fullName>AUTHORIZED</fullName>
        <isActive>false</isActive>
        <label>AUTHORIZED</label>
    </customValue>
    <description>Status of funding</description>
    <masterLabel>FundingStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__FundingType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACH</fullName>
    </customValue>
    <customValue>
        <fullName>WIRE</fullName>
        <label>Wire Transfer</label>
    </customValue>
    <customValue>
        <fullName>CASH</fullName>
        <label>Branch or ATM Deposit</label>
    </customValue>
    <customValue>
        <fullName>DEBIT_CARD</fullName>
        <label>DEBIT CARD</label>
    </customValue>
    <customValue>
        <fullName>INTERNAL_TRANSFER</fullName>
        <label>INTERNAL TRANSFER</label>
    </customValue>
    <customValue>
        <fullName>APPLE_PAY</fullName>
        <isActive>false</isActive>
        <label>APPLE_PAY</label>
    </customValue>
    <customValue>
        <fullName>GOOGLE_PAY</fullName>
        <isActive>false</isActive>
        <label>GOOGLE_PAY</label>
    </customValue>
    <customValue>
        <fullName>CHECK</fullName>
        <isActive>false</isActive>
        <label>CHECK</label>
    </customValue>
    <customValue>
        <fullName>CREDIT_CARD</fullName>
        <isActive>false</isActive>
        <label>CREDIT_CARD</label>
    </customValue>
    <customValue>
        <fullName>PAYPAL</fullName>
        <isActive>false</isActive>
        <label>PAYPAL</label>
    </customValue>
    <description>Type of funding selected for the current deposit application.</description>
    <masterLabel>FundingType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>ABANDONED</fullName>
        <label>Abandoned</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>SAVED</fullName>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>SUBMITTED</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>Indicates current status of the submission.This will be computed and be useful for regulations.</description>
    <masterLabel>SubmissionStatus</masterLabel>
</GlobalValueSet>

classes/CZNachaFileTransferBatchTest.cls
@isTest
private class CZNachaFileTransferBatchTest {
  @isTest
  public static void testCreate() {
    Test.startTest();

    try {
      Test.setMock(HttpCalloutMock.class, new CZWTFCNachaFTMockClass(200));
      CZNachaFileTransferBatch obj = new CZNachaFileTransferBatch();
      Database.BatchableContext batchableContext;
      tffa__Submission__c sub = new tffa__Submission__c(tffa__Brand__c = '100');
      insert sub;
      tffa__fundingrequest__c fund = new tffa__fundingrequest__c(tffa__Type__c='ACH',ACHReportGenerated__c= false,tffa__Status__c = 'ACH_FILE_GENERATED',tffa__Submission__c=sub.id);
      insert fund;
      UploadFileHistory__c file1 = new UploadFileHistory__c();
      file1.FileName__c = 'Mytestfile';
      file1.DocumentId__c = '0691h000001ONNPAA4';
      List<ContentVersion> cvList = new List<ContentVersion>();
      ContentVersion oo = new ContentVersion();
      ContentVersion o1 = new ContentVersion();
      oo.FileTransferStatus__c = 'Failure';
      o1.FileTransferStatus__c = 'Success';
      cvList.add(oo);
      cvList.add(o1);
      List<UploadFileHistory__c> files = new List<UploadFileHistory__c>();
      files.add(file1);
      List<UploadFileHistory__c> lst = obj.start(batchableContext);
      obj.execute(batchableContext, files);
      obj.sendEmail(cvList);
      obj.finish(batchableContext);
    } catch (Exception e) {
      tffa.Logger.error('Exception Nacha FT batch Test class:' + e.getStackTraceString());
    }
    Test.stopTest();
  }
}