objects/ContentVersion.object
<CustomObject>
    <description>Configurations related to ACH files</description>
    <fields>
        <fullName>FileTransferStatus__c</fullName>
        <description>File transfer Status to external system</description>
        <label>File transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FileTransferStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/tffa__AccountPreference__c.object
<CustomObject>
    <description>List of account preferences/additional services applied along with the application. Example values are ATM_CARD, INTERNET_BANKING, CHECKBOOK</description>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>Account number. e.g. Account number captured for Balance Transfer.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Address associated with the preference. e.g Payment address captured for Balance Transfer.</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Account Preferences</relationshipLabel>
        <relationshipName>AccountPreferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application</description>
        <inlineHelpText>Master Detail Lookup</inlineHelpText>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Account Preferences</relationshipLabel>
        <relationshipName>AccountPreferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>Unique identifier for the preference or service opted for.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <description>Current state (of processing) of the account preference.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account Preference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Address__c.object
<CustomObject>
    <description>An address is a collection of information, presented in a mostly fixed format, used to give the location of a building, apartment, or other structure or a plot of land, generally using political boundaries and street names as references,  along with other identifiers such as house or apartment numbers

 For more reference lookup https://en.wikipedia.org/wiki/Address_(geography)#United_States</description>
    <fields>
        <fullName>tffa__City__c</fullName>
        <description>The city of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Line1__c</fullName>
        <description>line 1 of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Line1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Line2__c</fullName>
        <description>line 2 of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <description>A state is a geographical region of a country used for administrative or political purposes,</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ZipCode__c</fullName>
        <description>Also known as post code , a series of numbers that forms part of an address, used to help organize post so that it can be delivered more quickly</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>CZTitle1__c</fullName>
        <description>Title 1</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Title 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CZTitle2__c</fullName>
        <description>Title 2</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Title 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CZTitle3__c</fullName>
        <description>Title 3</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Title 3</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>Fis branch code for Location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Branch Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The final generated account number. This will be set only after the final account number is available as part of the response of an account open API call.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account address for purposes of statement etc. If Address Prefill Source Id is set, the address details are not persisted directly, only address id is persisted.</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product code identifier.</description>
        <label>Financial Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR (4 AND 5))</booleanFilter>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>$Source.tffa__ProductCategory__c</field>
                <operation>equals</operation>
                <valueField>tffa__Product__c.tffa__Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value>In Progress</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <defaultValue>&quot;Init&quot;</defaultValue>
        <description>The stage of the application in context of the product applied. This will be different for each product and is more granular than the status field.This field will be updated on the state transition the application in the origination workflow.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>Unique code for the brand</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <fields>
        <fullName>CZStarterCheckCount__c</fullName>
        <description>Starter Check Count</description>
        <label>Starter Check Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CZStarterCheckStartNumber__c</fullName>
        <description>Starter Check Starting Number</description>
        <label>Starter Check Start Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique identifier for the product</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>FIS Branch Code.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This is the branch code received in URL Parameter from marketing site.</inlineHelpText>
        <label>FIS Branch Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__BrandEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The current brand of the submission</description>
        <label>Brand</label>
        <referenceTo>tffa__Brand__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <defaultValue>&quot;Init&quot;</defaultValue>
        <description>The current state/step of the Submission</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UploadFileHistory__c.object
<CustomObject>
    <description>the file</description>
    <fields>
        <fullName>FileName__c</fullName>
        <description>File Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FileName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FileTransferStatus__c</fullName>
        <description>File Transfer Status</description>
        <label>File Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FileTransferStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SerialNumber__c</fullName>
        <description>The serial number of the generated file.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SerialNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Upload File History</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Upload File History</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upload File History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/FileTransferStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
    </customValue>
    <customValue>
        <fullName>Resend</fullName>
    </customValue>
    <customValue>
        <fullName>Created</fullName>
    </customValue>
    <customValue>
        <fullName>No Document</fullName>
    </customValue>
    <masterLabel>FileTransferStatus</masterLabel>
</GlobalValueSet>

classes/CZStarterCheckExecutor.cls
public inherited sharing class CZStarterCheckExecutor {
  public static List<UploadFileHistory__c> uploadFileHistoryList = new List<UploadFileHistory__c>();

  public static void processRequest(tffa__Application__c app) {
    FISCCIntegrationLogService.applicationCode = FISCCIntegrationConstants.STARTER_CHECK;
    tffa__AccountPreference__c accPref;
    try {
      for (tffa__AccountPreference__c accPrefObj : app.tffa__AccountPreferences__r) {
        if (('CHECK-ORDER').equals(accPrefObj.tffa__Code__c) && accPrefObj.CZIsStarterCheckRequired__c) {
          accPref = accPrefObj;
          break;
        }
      }
      if (accPref == null) {
        return;
      }
      FISCCIntegrationLogService.setCurrentLog(FISCCIntegrationConstants.STARTER_CHECK + '-' + app.Name + '-' + app.tffa__AccountNumber__c);
      WintrustEnvConfig__mdt wintrustEnvConfig = CZWTFCHelperRepository.fetchWintrustEnvConfig();

      List<UploadFileHistory__c> uploadHistoryList = CZWTFCHelperRepository.fetchUploadFileHistory(app.Id, CZWTFCConstants.STARTER_CHECK);
      Integer fileNumber = 1;
      Integer chqStartNum = Integer.valueOf(app.tffa__Product__r.CZStarterCheckStartNumber__c);
      if (chqStartNum == 0 || chqStartNum == null) {
        chqStartNum = CZWTFCConstants.STARTER_CHECK_START_NUMBER;
      }
      Integer starterCheckCount = Integer.valueOf(app.tffa__Product__r.CZStarterCheckCount__c);
      if (starterCheckCount == 0 || starterCheckCount == null) {
        starterCheckCount = CZWTFCConstants.STARTER_CHECK_COUNT;
      }

      Decimal temp = starterCheckCount / 3.0;
      Integer totalFileCount = (Integer) temp.round(roundingMode.UP);

      tffa.Logger.debug('CZStarterCheckExecutor totalFileCount ' + totalFileCount);

      while (fileNumber <= totalFileCount) {
        UploadFileHistory__c uploadFileHistory;
        if (uploadHistoryList != null) {
          for (UploadFileHistory__c uploadFileHistoryObj : uploadHistoryList) {
            if (Integer.valueOf(uploadFileHistoryObj.SerialNumber__c) == fileNumber) {
              uploadFileHistory = uploadFileHistoryObj;
              break;
            }
          }
        }

        if (uploadFileHistory != null && uploadFileHistory.FileTransferStatus__c == CZWTFCConstants.PROCESS_STATUS_SUCCESS) {
          tffa.Logger.debug('CZStarterCheckExecutor fileNumber :' + uploadFileHistory.FileName__c + ' already exist.');
          fileNumber++;
          continue;
        }

        FISCCIntegrationLogService.setCurrentLogItem(FISCCIntegrationConstants.STARTER_CHECK, app.id, true);
        try {
          tffa.Logger.debug('CZStarterCheckExecutor chqStartNum :' + chqStartNum);
          tffa.Logger.debug('CZStarterCheckExecutor fileNumber :' + fileNumber);

          CZWTFCPrintRequestDTO request = new CZWTFCPrintRequestDTO();
          request.PrintRequest.CheckData.JobID = accPref.StarterCheckJobID__c;
          request.PrintRequest.CheckData.CustomerData01 = app.CZTitle1__c;
          request.PrintRequest.CheckData.CustomerData02 = app.CZTitle2__c;
          request.PrintRequest.CheckData.CustomerData03 = app.CZTitle3__c;

          if (app.tffa__Address__r != null) {
            tffa__Address__c addressObj = app.tffa__Address__r;
            request.PrintRequest.CheckData.CustomerData04 =
              addressObj.tffa__Line1__c + (addressObj.tffa__Line2__c != null ? ', ' + addressObj.tffa__Line2__c : '');

            request.PrintRequest.CheckData.CustomerData05 =
              addressObj.tffa__City__c +
              (addressObj.tffa__State__c != null ? ', ' + addressObj.tffa__State__c : '') +
              ', ' +
              addressObj.tffa__ZipCode__c;
          }

          request.PrintRequest.CheckData.CheckNumber01 = ((fileNumber - 1) * 3) + chqStartNum;
          request.PrintRequest.CheckData.CheckNumber02 = ((fileNumber - 1) * 3) + chqStartNum + 1;
          request.PrintRequest.CheckData.CheckNumber03 = ((fileNumber - 1) * 3) + chqStartNum + 2;
          request.PrintRequest.CheckData.BranchID = app.FISBranchCode__c;
          request.PrintRequest.CheckData.RoutingNumber = FISCCIntegrationLogService.submissionObj.tffa__BrandEntity__r.tffa__RoutingNumber__c;
          request.PrintRequest.CheckData.AccountNumber = app.tffa__AccountNumber__c;
          request.PrintRequest.CheckData.UserID = wintrustEnvConfig.StarterCheckUserID__c;

          String bulkContent = '<?xml version="1.0"?>' + new CZWTFCXMLSerializer().serialize(request);
          tffa.Logger.debug('CZStarterCheckExecutor bulkContent : ' + bulkContent);

          String fileName = 'Starter_Check_' + accPref.StarterCheckJobID__c + '-' + fileNumber + '.txt';
          if (uploadFileHistory == null)
            uploadFileHistory = setUploadHistory(app, fileName, fileNumber);

          Nacha_Config__mdt wtfcnachaConfig = CZWTFCCustomMetadataRepository.fetchWtfcNachaConfig();
          /*ContentVersion created only to pass file name and file contents. ContentVersion is not to be saved*/
          ContentVersion cv = new ContentVersion();
          cv.PathOnClient = fileName;
          cv.VersionData = Blob.valueOf(bulkContent);
          FISCCIntegrationLogService.setLogItemRequestAndResponse(
            'File Name : ' +
            fileName +
            '\n' +
            '    File Contents : ' +
            bulkContent,
            null
          );
          CZMulesoftFileTransferService.transferSingleFile(uploadFileHistory, cv, wtfcnachaConfig);

          uploadFileHistoryList.add(uploadFileHistory);

          tffa.Logger.debug('CZStarterCheckExecutor New File Generated* ');
        } catch (Exception ex) {
          FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.LOG_ITEM_STATUS_FAILURE);
          tffa.Logger.error('Exception in CZStarterCheckExecutor :' + ex.getMessage() + ' :: ' + ex.getStackTraceString());
        } finally {
          fileNumber++;
        }
        FISCCIntegrationLogService.setLogItemOk(FISCCIntegrationConstants.LOG_ITEM_STATUS_SUCCESS);
        if (Test.isRunningTest()) {
          break;
        }
      }

      FISCCIntegrationLogService.setUploadFileHistory(uploadFileHistoryList);
      FISCCIntegrationLogService.setLogOk(FISCCIntegrationConstants.LOG_ITEM_STATUS_SUCCESS);
    } catch (Exception ex) {
      FISCCIntegrationLogService.setLogFailed(FISCCIntegrationConstants.LOG_ITEM_STATUS_FAILURE);
      tffa.Logger.error('Exception in CZStarterCheckExecutor :' + ex.getMessage() + ' :: ' + ex.getStackTraceString());
    }
  }

  public static UploadFileHistory__c setUploadHistory(tffa__Application__c app, String fileName, Integer fileNumber) {
    UploadFileHistory__c uploadFileHistory = new UploadFileHistory__c();
    uploadFileHistory.ApplicationID__c = app.id;
    uploadFileHistory.SubmissionID__c = String.valueOf(app.tffa__Submission__c);
    uploadFileHistory.BrandCode__c = app.tffa__Brand__c;
    uploadFileHistory.FileName__c = fileName;
    uploadFileHistory.FileExt__c = 'txt';
    uploadFileHistory.FileType__c = CZWTFCConstants.STARTER_CHECK;
    uploadFileHistory.FileTransferStatus__c = CZWTFCConstants.PROCESS_STATUS_FAILURE;
    uploadFileHistory.SubmissionName__c = FISCCIntegrationLogService.submissionObj.Name;
    uploadFileHistory.SerialNumber__c = String.valueOf(fileNumber);
    return uploadFileHistory;
  }
}