objects/Contact.object
<CustomObject>
    <fields>
        <fullName>FinServ__LastFourDigitSSN__c</fullName>
        <description>Last 4-Digits of SSN or Tax ID</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SSN/Tax ID (Last Four Digits)</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinServ__MailingAddress__c</fullName>
        <description>Compound field for Mailing Address.</description>
        <formula>if(ISBLANK(MailingStreet),  &quot;&quot; , MailingStreet &amp; br()) &amp;
if(ISBLANK(MailingCity),  &quot;&quot; , MailingCity&amp; &quot;, &quot; ) &amp;
if(ISBLANK(MailingState),  &quot;&quot; , MailingState&amp; &quot; &quot; ) &amp;
if(ISBLANK(MailingPostalCode),  &quot;&quot; , MailingPostalCode &amp; br()) &amp;
if(ISBLANK(MailingCountry),  &quot;&quot; , MailingCountry)</formula>
        <label>Mailing Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FinServ__MotherMaidenName__c</fullName>
        <description>Mother&apos;s Maiden Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Mother&apos;s Maiden Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/WT_CTIContactSearchController.cls
/**
 * ----------------------------------------------------------------------------------------------------------------------
 * @Name           WT_CTIContactSearchController
 * @Author         Anh Phan
 * @ModifiedBy     Anh Phan
 * @Version        v1.0
 * @CreatedDate    11-03-2021
 * @UsedBy         wT_CTIContactSearch(LWC) 
 * @TestClass      WT_CTIContactSearchController_T
 * ----------------------------------------------------------------------------------------------------------------------
 * @Description
 * Server side controller for wT_CTIContactSearch(LWC)
 * ----------------------------------------------------------------------------------------------------------------------
 * @Changes
 * ----------------------------------------------------------------------------------------------------------------------
**/
public without sharing class WT_CTIContactSearchController
{
 private static final String CONTACTQUERY = 'SELECT FinServ__MotherMaidenName__c,Email,Birthdate,FinServ__MailingAddress__c,FinServ__LastFourDigitSSN__c,Id,Name,HomePhone,AssistantPhone,Phone,MobilePhone,OtherPhone FROM Contact WHERE HomePhone = :phoneNumber OR AssistantPhone = :phoneNumber OR Phone = :phoneNumber OR MobilePhone = :phoneNumber OR OtherPhone = :phoneNumber';
 
  /**
   * ----------------------------------------------------------------------------------------------------------------------
   * @Description
   * Method to retrieve contact details based on user input 
   * ----------------------------------------------------------------------------------------------------------------------
   * @param     phoneNumber     String input for phone number to search
   * @return    List<Contact>   A list of contacts that matches the entered phone number
   * ----------------------------------------------------------------------------------------------------------------------
  **/
  @AuraEnabled
  public static List<Contact> getContactsForPhone(String phoneNumber)
  {
      List<Contact> listContact;
      try
      {
        listContact = Database.query(CONTACTQUERY);
      }
      catch (Exception e) 
      {throw new AuraHandledException(e.getMessage());
      }
      return listContact;
  }

}