objects/ContentVersion.object
<CustomObject>
    <description>Configurations related to ACH files</description>
    <fields>
        <fullName>FileTransferStatusMessage__c</fullName>
        <description>File Transfer Status Message for moveit file upload</description>
        <encryptionScheme>None</encryptionScheme>
        <label>File Transfer Status Message</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FileTransferStatus__c</fullName>
        <description>File transfer Status to external system</description>
        <label>File transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FileTransferStatus</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

objects/Nacha_Config__mdt.object
<CustomObject>
    <description>Configurations needed for API call for Nacha File transfer</description>
    <fields>
        <fullName>File_Upload_Failed_Mail_Id__c</fullName>
        <description>emails for receiving the failure message of Batch processed</description>
        <label>File Upload Failed Mail Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Nacha Config</label>
    <pluralLabel>Nacha Config</pluralLabel>
</CustomObject>

objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__FundingRequest__c.object
<CustomObject>
    <description>Supports the capture of details pertaining to funding a payment obligation using one of the various available sources of funding</description>
    <fields>
        <fullName>ACHReportGenerated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>To indicate if this funding record is reported in ACH Report</description>
        <label>ACH Report Generated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Funding status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__FundingStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to parent submission.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Consolidated Funding Requests</relationshipLabel>
        <relationshipName>FundingRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__Brand__c</fullName>
        <description>Brand code of the Brand for the submission if applicable</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the submission</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UploadFileHistory__c.object
<CustomObject>
    <description>the file</description>
    <fields>
        <fullName>DocumentId__c</fullName>
        <description>Contains the document id for the file</description>
        <encryptionScheme>None</encryptionScheme>
        <label>DocumentId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FileTransferStatusMessage__c</fullName>
        <description>File Transfer Status Message</description>
        <encryptionScheme>None</encryptionScheme>
        <label>File Transfer Status Message</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FileTransferStatus__c</fullName>
        <description>File Transfer Status</description>
        <label>File Transfer Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FileTransferStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Upload File History</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Upload File History</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upload File History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/FileTransferStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Success</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
        <default>true</default>
        <label>Pending</label>
    </customValue>
    <customValue>
        <fullName>Failure</fullName>
    </customValue>
    <customValue>
        <fullName>Resend</fullName>
    </customValue>
    <customValue>
        <fullName>Created</fullName>
    </customValue>
    <customValue>
        <fullName>No Document</fullName>
    </customValue>
    <masterLabel>FileTransferStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__FundingStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>FUNDED</fullName>
        <label>Funded</label>
    </customValue>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
        <label>Failed</label>
    </customValue>
    <customValue>
        <fullName>APPROVAL</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>REVERSED</fullName>
        <label>Reversed</label>
    </customValue>
    <customValue>
        <fullName>REVERSAL_FAILED</fullName>
        <label>Reversal Failed</label>
    </customValue>
    <customValue>
        <fullName>ACH_FILE_GENERATED</fullName>
        <label>ACH File Generated</label>
    </customValue>
    <customValue>
        <fullName>ACH_FILE_FAILED</fullName>
        <label>ACH File Generation Failed</label>
    </customValue>
    <customValue>
        <fullName>HOLD_APPLIED</fullName>
        <label>Hold Applied on Funds</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>REVERSAL_NOT_REQ</fullName>
        <label>Reversal Not Required</label>
    </customValue>
    <customValue>
        <fullName>AUTHORIZED</fullName>
        <isActive>false</isActive>
        <label>AUTHORIZED</label>
    </customValue>
    <description>Status of funding</description>
    <masterLabel>FundingStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>ABANDONED</fullName>
        <label>Abandoned</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>SAVED</fullName>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>SUBMITTED</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>Indicates current status of the submission.This will be computed and be useful for regulations.</description>
    <masterLabel>SubmissionStatus</masterLabel>
</GlobalValueSet>

classes/CZNachaFileTransferBatch.cls
/**
 * Copyright (c) 2019 Terafina Inc
 *
 * @description Upload File Transfer Batch job
 * @group Job
 */
global inherited sharing class CZNachaFileTransferBatch extends tffa.AbstractBatchJob implements Database.Batchable<sObject>, Database.AllowsCallouts {
  @TestVisible
  private static boolean testException = false;
  private final String templateName = 'ACHFileTransferReport';
  global List<UploadFileHistory__c> start(Database.BatchableContext bc) {
    List<UploadFileHistory__c> fileList = new List<UploadFileHistory__c>();
    fileList.addAll(CZWTFCACHRepository.fetchACHNachaFileTransferResults());
    tffa.Logger.flush();
    return fileList;
  }
  global void execute(Database.BatchableContext batchableContext, List<UploadFileHistory__c> files) {
    UploadFileHistory__c file;
    list<Id> docIds = new List<Id>();
    CZWTFCFileTransferResultDTO fileTransferResultDTO = new CZWTFCFileTransferResultDTO();
    tffa.Interaction.begin(CZNachaFileTransferBatch.class, 'execute');
    try {
      for (UploadFileHistory__c f : files) {
        if (f.DocumentId__c != null) {
          docIds.add(f.DocumentId__c);
        }
      }
      Map<String, UploadFileHistory__c> fileMap = new Map<String, UploadFileHistory__c>();

      for (UploadFileHistory__c uploadFile : files) {
        fileMap.put(uploadFile.DocumentId__c, uploadFile);
      }

      List<ContentVersion> cvList = ACHFileTransRepository.findCVByDocId(docIds);
      fileTransferResultDTO = CZMulesoftFileTransferService.transferFiles(cvList, fileMap);

      ACHFileTransRepository.save(fileTransferResultDTO.files);
    } catch (exception e) {
      tffa.Logger.error('Exception : ==-> ' + e.getMessage() + ' ' + e.getStackTraceString());
    } finally {
      try {
        sendEmail(fileTransferResultDTO.cvList);
      } finally{
        tffa.Interaction.close();
      }
    }
  }
  global void finish(Database.BatchableContext batchableContext) {
    tffa.Logger.debug('CZNachaFileTransferBatch finish()');
    tffa.Logger.flush();
  }

  public void sendEmail(List<ContentVersion> cvList) {
    try {
      List<tffa.NotificationDTO> notifications = new List<tffa.NotificationDTO>();
      Nacha_Config__mdt wtfcnachaConfig = CZWTFCCustomMetadataRepository.fetchWtfcNachaConfig();
      String emailid = wtfcnachaConfig.File_Upload_Failed_Mail_Id__c == null ? '' : wtfcnachaConfig.File_Upload_Failed_Mail_Id__c;
      List<String> emailIdList = emailid.split(',');
      tffa.NotificationDTO.NotificationRecipientDTO[] recipients = new List<tffa.NotificationDTO.NotificationRecipientDTO>{};

      if (emailIdList != null && !emailIdList.isEmpty()) {
        for (String mail : emailIdList) {
          recipients.add(
            new tffa.NotificationDTO.NotificationRecipientDTO(tffa.NotificationDTO.NotificationRecipientType.USER, null, null, mail, null)
          );
        }
      }
      String htmlBody = '';

      List<SObject> fundingRequestList = CZWTFCACHRepository.getFundingRequestsForACHFileGenerationBatch();
      Map<string, Map<String, Integer>> achFundingRequestDetailsMap = new Map<String, Map<String, Integer>>();
      tffa__FundingRequest__c fundingReq;
      List<tffa__FundingRequest__c> fundingRequeststoUpdate = new List<tffa__FundingRequest__c>();
      for (SObject fundingRequest : fundingRequestList) {
        fundingReq = (tffa__FundingRequest__c) fundingRequest;
        fundingReq.ACHReportGenerated__c = true;
        fundingRequeststoUpdate.add(fundingReq);
        Map<String, Integer> fundingRequestStatusMap = new Map<String, Integer>();
        if (achFundingRequestDetailsMap.ContainsKey(fundingReq.tffa__Submission__r.tffa__Brand__c)) {
          fundingRequestStatusMap = achFundingRequestDetailsMap.get(fundingReq.tffa__Submission__r.tffa__Brand__c);
          if (fundingRequestStatusMap.containsKey(fundingReq.tffa__Status__c)) {
            fundingRequestStatusMap.put(fundingReq.tffa__Status__c, fundingRequestStatusMap.get(fundingReq.tffa__Status__c) + 1);
          } else {
            fundingRequestStatusMap.put(fundingReq.tffa__Status__c, 1);
          }
        } else {
          fundingRequestStatusMap.put(fundingReq.tffa__Status__c, 1);
          achFundingRequestDetailsMap.put(fundingReq.tffa__Submission__r.tffa__Brand__c, fundingRequestStatusMap);
        }
      }
      if (!achFundingRequestDetailsMap.IsEmpty() || cvList != null) {
        htmlBody = 'Hi,<br/>ACH Batch Job has completed.<br/>Below are the details.<br/><br/>';
      } else {
        htmlBody = 'Hi,<br/>ACH Batch Job has completed.<br/>There were no records to process.<br/><br/>';
      }

      if (!achFundingRequestDetailsMap.IsEmpty()) {
        htmlBody += '<table border="1" style="border-collapse: collapse"><caption>ACH Request File Generation Status</caption><tr><th>Brand</th><th>ACH Request Status</th><th>Record Count</th></tr>';
        Integer count;
        for (String brandCode : achFundingRequestDetailsMap.keyset()) {
          Map<String, Integer> statusMap = achFundingRequestDetailsMap.get(brandCode);
          string status;
          for (String statusfromMap : statusMap.keyset()) {
            status = statusfromMap;
            count = statusMap.get(status);
            htmlBody += '<tr><td>' + brandCode + '</td>';
            htmlBody += '<td>' + status + '</td>';
            htmlBody += '<td>' + count + '</td></tr>';
          }
        }
        htmlBody += '</table><br/><br/>';
      }
      if (cvList != null) {
        htmlBody += '<table border="1" style="border-collapse: collapse"><caption>File Transfer Status</caption>';
        for (ContentVersion cv : cvList) {
          if (cv.FileTransferStatus__c == CZWTFCConstants.FILE_TRANSFER_SUCCESS) {
            htmlBody += '<tr><td>' + String.valueOf(cv.PathOnClient + '   ' + cv.FileTransferStatusMessage__c) + +'</td></tr>';
          }
          if (cv.FileTransferStatus__c == 'Failure') {
            htmlBody += '<tr><td>' + String.valueOf(cv.PathOnClient + '   ' + cv.FileTransferStatusMessage__c) + '</td></tr>';
          }
        }
        htmlBody += '</table>';
      }

      if (htmlBody != '' && !emailIdList.isEmpty()) {
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.ToAddresses = emailIdList;
        mail.HTMLBody = htmlBody;
        mail.Subject = 'ACH File Transfer Report';
        Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>{ mail };
        Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        if (results[0].success) {
          WTFCObjectManagerRepository.doUpsertObjects(fundingRequeststoUpdate);
        } else {
          tffa.Logger.error('FileTransferBatch email failed :' + results[0].errors[0].message);
        }
      }
    } catch (Exception ex) {
      tffa.Logger.error('FileTransferBatch email failed :' + ex.getMessage() + ' ' + ex.getStackTraceString());
    }
  }
}