objects/CZConvergeConfiguration__mdt.object
<CustomObject>
    <description>It contains all the config for Converge(Elavon) Funding</description>
    <fields>
        <fullName>EndPoint__c</fullName>
        <description>URL endpoint</description>
        <label>EndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LogRequest__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked http request body will be logged in &apos;Debug Logs&apos;.</description>
        <inlineHelpText>If checked http request body will be logged in &apos;Debug Logs&apos;.</inlineHelpText>
        <label>Log Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LogResponse__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked response from http will be logged in &apos;Debug Logs&apos;.</description>
        <inlineHelpText>If checked response from http will be logged in &apos;Debug Logs&apos;.</inlineHelpText>
        <label>Log Response</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <description>Method</description>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RequestTimeout__c</fullName>
        <description>Request timeout defaulted to 120 seconds</description>
        <label>RequestTimeout</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Converge Configuration</label>
    <pluralLabel>Converge Configurations</pluralLabel>
</CustomObject>

classes/CZWTFCConvergeAdapter.cls
public with sharing class CZWTFCConvergeAdapter {
  @TestVisible
  private static boolean testException = false;
  public static HttpResponse execute(CZConvergeConfiguration__mdt convergeConfig, Map<String, Object> params, String requestBody) {
    HttpRequest req = new HttpRequest();
    HttpResponse response;
    try {
      if (Test.isRunningTest() && testException) {
        throw new tffa.ApplicationException('Called through test class');
      }
      req.setMethod(convergeConfig.Method__c);
      req.setEndpoint(convergeConfig.EndPoint__c);
      req.setTimeout(Integer.valueOf(convergeConfig.RequestTimeout__c));

      if (String.isNotBlank(requestBody)) {
        req.setBody(requestBody);
      }

      if (convergeConfig.LogRequest__c) {
        CZWTFCIntegrationLogService.setLogItemRequestAndResponse('Endpoint: ' + req.getEndpoint() + ' Request: ' + requestBody, null);
      }

      Http http = new Http();
      tffa.Logger.debug('Endpoint ' + convergeConfig.EndPoint__c);
      response = http.send(req);
      if (convergeConfig.LogResponse__c) {
        CZWTFCIntegrationLogService.setLogItemRequestAndResponse(null, response.getBody());
      }
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in execute :::' + ex.getMessage() + 'LineNumber :::' + ex.getLineNumber());
    }
    tffa.Logger.debug('Response ' + response);
    return response;
  }
}