objects/CZFCMAccountTypesList__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings maintains  FCM account type values</description>
    <fields>
        <fullName>AccountTypeId__c</fullName>
        <description>Account Type Id</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Type Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>FCM Account Types</label>
</CustomObject>

objects/CZFCMDocumenTypes__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>FCM Document Types</description>
    <label>FCM Document Types</label>
</CustomObject>

objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The final generated account number. This will be set only after the final account number is available as part of the response of an account open API call.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Brand__c</fullName>
        <description>Brand code of the Brand for the submission if applicable</description>
        <formula>tffa__Submission__r.tffa__Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__DepositBoxAccountNumber__c</fullName>
        <description>Box Number of the safe deposit box. Include 3 pieces of information, the branch number, region code and box number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Deposit box account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ProductCategory__c</fullName>
        <description>Different product category supported by system. This classifies the flow of account opening , the underlying data model and the servicing components about an account.</description>
        <label>Product Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ProductCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product code identifier.</description>
        <label>Financial Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR (4 AND 5))</booleanFilter>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>$Source.tffa__ProductCategory__c</field>
                <operation>equals</operation>
                <valueField>tffa__Product__c.tffa__Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value>In Progress</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__NationalIdentifierValue__c</fullName>
        <description>The value of the taxpayer identifier as assigned by the IRS to the individual or legal entity.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>National identifier value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <fields>
        <fullName>tffa__Category__c</fullName>
        <description>Broad classification of the product</description>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ProductCategory</valueSetName>
        </valueSet>
    </fields>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FCMGenerateDocumentIdExtension.cls
public inherited sharing class FCMGenerateDocumentIdExtension {
  public static String docId = '';

  public static String getFCMDocumentId(tffa__Application__c app, CZFCMContentVersionDTO contentVersionDTO, tffa__Party__c party, FISCC_Adapter_Configs__mdt adapterConfig, FISCC_Charter_Config__mdt charterConfig) {
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    Object result = null;
    try {
      docId = '';

      fisccRequestBaseDTO = createGetFCMDocumentIdRequest(app, contentVersionDTO, party, adapterConfig, charterConfig);

      result = FISCCHostAdapter.processHostRequest(fisccRequestBaseDTO, adapterConfig, charterConfig);
      
      isFCMAPICallSuccess(result);

      return docId;
    } catch (Exception ex) {
      tffa.Logger.error('Exception in getAccessToken : ' + ex.getMessage() + ex.getLineNumber() + ex.getStackTraceString());
      return '';
    }
  }

  public static FISCCRequestBaseDTO createGetFCMDocumentIdRequest(
    tffa__Application__c app, 
    CZFCMContentVersionDTO contentVersionDTO, 
    tffa__Party__c party,
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    FCMGenerateDocumentIdRequest request = new FCMGenerateDocumentIdRequest();
    FCMGenerateDocumentIdRequest.Accounts accountObj = new FCMGenerateDocumentIdRequest.Accounts();
    try {
      request.ftype = fetchFileType(contentVersionDTO.FileExtension);
      request.FCMUploadDate = fetchDate();

      if(party != null){
        contentVersionDTO.Title = contentVersionDTO.Title + ';' + party.Name;
      }

      String description = contentVersionDTO.Title;
      if(description != null && description.length() > 100){
        description = description.substring(0,100);
      }

      if(FISCCIntegrationConstants.DIGITAL.equalsIgnoreCase(FISCCIntegrationLogService.submissionObj.tffa__Channel__c)){
        request.dtype = 'Account Opening Documents – Digital';
        request.docdescription = 'Digital:' + description;
      } else {
        request.dtype = 'Account Opening Documents';
        request.docdescription = description;
      }
      
      if(app != null){
        accountObj.account = FISCCIntegrationConstants.SAFE_DEPOSIT_PROD_CATEGORY.contains(app.tffa__ProductCategory__c) ? app.tffa__DepositBoxAccountNumber__c : app.tffa__AccountNumber__c;
        String fcmAccountType = getFCMAccountType(app.tffa__Product__r, app.tffa__Brand__c);

        if(fcmAccountType != ''){
          accountObj.application = fcmAccountType;
        }
      }

      if(String.isNotBlank(contentVersionDTO.DocumentCode)){
        CZFCMDocumenTypes__c docType = CZFCMDocumenTypes__c.getValues(contentVersionDTO.DocumentCode);

        if(docType != null){
          request.dtype = docType.DocumentType__c;
        }

        if(docType != null && docType.IsCustomerlevelDoc__c && party != null){
          accountObj.account = party.tffa__NationalIdentifierValue__c != null ? party.tffa__NationalIdentifierValue__c : party.Customer_Number__c;
          accountObj.application = 'ZZ';
        }
      }

      request.accountlist.add(accountObj);

      fisccRequestBaseDTO = request;

      tffa.Logger.debug('fisccRequestBaseDTO::'+ fisccRequestBaseDTO);

      return fisccRequestBaseDTO;
    } catch (Exception ex) {
      tffa.Logger.error(
        'Exception in FCMGenerateDocumentIdExtension createGetFCMDocumentIdRequest : ' +
        ex.getMessage() +
        ex.getLineNumber() +
        ex.getStackTraceString()
      );
    }
    return fisccRequestBaseDTO;
  }

  public static void isFCMAPICallSuccess(Object response) {
    FCMGenerateDocIdResponse objFCMGenerateDocumentIdResponse = null;
    try {    
      objFCMGenerateDocumentIdResponse = (FCMGenerateDocIdResponse) response;
      docId = objFCMGenerateDocumentIdResponse.docid;

    } catch (Exception ex) {
      tffa.Logger.error(
        'Exception in FCMGenerateDocumentIdExtension isFCMAPICallSuccess : ' +
        ex.getMessage() +
        ex.getLineNumber() +
        ex.getStackTraceString()
      );
    }
  }

  public static String fetchFileType(String type) {
    if (type.equalsIgnoreCase('jpeg') || type.equalsIgnoreCase('jpg') || type.equalsIgnoreCase('png')|| type.equalsIgnoreCase('bmp')|| type.equalsIgnoreCase('gif')) {
      return 'jpg';
    } else if (type.equalsIgnoreCase('tif') || type.equalsIgnoreCase('tiff')) {
      return 'tif';
    } else if (type.equalsIgnoreCase('xls') || type.equalsIgnoreCase('xlsx') || type.equalsIgnoreCase('doc') || type.equalsIgnoreCase('docx') || type.equalsIgnoreCase('msg')) {
      return type.toLowerCase();
    }

    return 'pdf';
  }

  public static String fetchDate() {
    DateTime d = Date.Today();
    return d.format('MM/dd/yyyy');
  }

  //TODO-PAHSE2 : SDB  
  public static String getFCMAccountType(tffa__Product__c product, String brancdCode) {
    String productTypecode = '';
    String fcmAccountType = '';
    if (product.tffa__Category__c == CZWTFCConstants.IRA) {
      return 'TI';
    } else if (product.tffa__Category__c.contains(CZWTFCConstants.CERTIFICATE)) {
      productTypecode =  brancdCode + ' CD';
    } else if (product.tffa__Category__c.contains(CZWTFCConstants.CHECKING)) {
      productTypecode =  brancdCode + ' DDA';
    } else if (product.tffa__Category__c.contains(CZWTFCConstants.MONEY_MARKET)) {
      productTypecode =  brancdCode + ' DDA';
    } else if (product.tffa__Category__c.contains(CZWTFCConstants.SAVINGS) || product.tffa__Category__c.contains(CZWTFCConstants.HSA)) {
      productTypecode =  brancdCode + ' Savings';
    } 

    if(!Test.isRunningTest()){
      fcmAccountType = productTypeCode != '' ? CZFCMAccountTypesList__c.getValues(productTypeCode).AccountTypeId__c : '';
    }

    return fcmAccountType;
  }
}