objects/CZTerafinaFisMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings maintains  Terafina Fis Mapping values</description>
    <fields>
        <fullName>FisValue__c</fullName>
        <description>Fis Value</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Terafina Fis Mapping</label>
</CustomObject>

objects/tffa__Address__c.object
<CustomObject>
    <description>An address is a collection of information, presented in a mostly fixed format, used to give the location of a building, apartment, or other structure or a plot of land, generally using political boundaries and street names as references,  along with other identifiers such as house or apartment numbers

 For more reference lookup https://en.wikipedia.org/wiki/Address_(geography)#United_States</description>
    <fields>
        <fullName>tffa__City__c</fullName>
        <description>The city of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Line1__c</fullName>
        <description>line 1 of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Line1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <description>A state is a geographical region of a country used for administrative or political purposes,</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ZipCode__c</fullName>
        <description>Also known as post code , a series of numbers that forms part of an address, used to help organize post so that it can be delivered more quickly</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>CZAccountOpeningDate__c</fullName>
        <description>Account Opening Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Opening Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The final generated account number. This will be set only after the final account number is available as part of the response of an account open API call.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account address for purposes of statement etc. If Address Prefill Source Id is set, the address details are not persisted directly, only address id is persisted.</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <defaultValue>&quot;Init&quot;</defaultValue>
        <description>The stage of the application in context of the product applied. This will be different for each product and is more granular than the status field.This field will be updated on the state transition the application in the origination workflow.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Beneficiary__c.object
<CustomObject>
    <description>A beneficiary typically refers to someone who is eligible to receive distributions from deposits upon death of primary owner of account. Beneficiary capture typically happens for Certificate Deposits.
Designating a beneficiary not only ensures the CD will not have to go through probate when the applicant dies.</description>
    <fields>
        <fullName>CZParty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Party</relationshipLabel>
        <relationshipName>Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Beneficiary address</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Beneficiaries</relationshipLabel>
        <relationshipName>Beneficiaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Beneficiaries</relationshipLabel>
        <relationshipName>Beneficiaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__BirthDate__c</fullName>
        <description>Date of birth</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Birth date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>tffa__FirstName__c</fullName>
        <description>First name of beneficiary</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>Last name of beneficiary</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LegalName__c</fullName>
        <description>The legal name of a business is the official name of the person or entity that owns a business.For limited partnerships, LLCs, and corporations, the legal name of the business is the name registered with the state filing office</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Legal name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__MiddleName__c</fullName>
        <description>The middle name of the beneficiary.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__NationalIdentifierType__c</fullName>
        <description>Classifies identification numbers used by the Internal Revenue Service (IRS) in the administration of tax laws.</description>
        <label>National identifier type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__NationalIdentifierType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__OrganizationType__c</fullName>
        <description>Type of Organization. This governs the structure of the business.</description>
        <label>Organization type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__OrganizationType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__PartyType__c</fullName>
        <defaultValue>&quot;INDIVIDUAL&quot;</defaultValue>
        <description>Party type of associated beneficiary</description>
        <label>Party type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__RelationCodeName__c</fullName>
        <description>Name of the relation code.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Relation code name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__SharePercentage__c</fullName>
        <description>Percentage of share</description>
        <label>Share percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tffa__Suffix__c</fullName>
        <description>The name suffix of the beneficiary. (E.g., JR = Junior, SR = Senior, etc.)</description>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Suffix</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - PRIMARY, CONTINGENT</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__BeneficiaryType</valueSetName>
        </valueSet>
    </fields>
    <label>Beneficiary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Beneficiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__BirthDate__c</fullName>
        <description>The date of birth of the individual</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Birth date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>tffa__FirstName__c</fullName>
        <description>The first name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>The last name of the individual represented by the parent object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LegalName__c</fullName>
        <description>The legal name of a business is the official name of the person or entity that owns a business.For limited partnerships, LLCs, and corporations, the legal name of the business is the name registered with the state filing office</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Legal name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__MiddleName__c</fullName>
        <description>The middle name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__NationalIdentifierType__c</fullName>
        <description>Classifies identification numbers used by the Internal Revenue Service (IRS) in the administration of tax laws.</description>
        <label>National identifier type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__NationalIdentifierType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__OrganizationType__c</fullName>
        <description>Type of Organization. This governs the structure of the business.</description>
        <label>Organization type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__OrganizationType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Suffix__c</fullName>
        <description>The name suffix of the individual represented by the parent object. (E.g., JR = Junior, SR = Senior, etc.)</description>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Suffix</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__BeneficiaryType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PRIMARY</fullName>
        <default>true</default>
        <label>Primary</label>
    </customValue>
    <customValue>
        <fullName>CONTINGENT</fullName>
        <label>Contingent</label>
    </customValue>
    <description>Type of the Beneficiary</description>
    <masterLabel>BeneficiaryType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__NationalIdentifierType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>SSN</fullName>
    </customValue>
    <customValue>
        <fullName>TIN</fullName>
    </customValue>
    <description>Classifies identification numbers used by the Internal Revenue Service IRS.</description>
    <masterLabel>NationalIdentifierType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__Suffix.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Jr</fullName>
    </customValue>
    <customValue>
        <fullName>Sr</fullName>
        <label>Sr.</label>
    </customValue>
    <customValue>
        <fullName>II</fullName>
    </customValue>
    <customValue>
        <fullName>III</fullName>
    </customValue>
    <customValue>
        <fullName>IV</fullName>
    </customValue>
    <customValue>
        <fullName>246</fullName>
        <isActive>false</isActive>
        <label>246</label>
    </customValue>
    <customValue>
        <fullName>Esq</fullName>
        <isActive>false</isActive>
        <label>Esq</label>
    </customValue>
    <customValue>
        <fullName>VI</fullName>
        <isActive>false</isActive>
        <label>VI</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <isActive>false</isActive>
        <label>V</label>
    </customValue>
    <customValue>
        <fullName>2nd</fullName>
        <isActive>false</isActive>
        <label>2nd</label>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
        <isActive>false</isActive>
        <label>Test</label>
    </customValue>
    <description>The name suffix of the individual represented by the parent object. (E.g., JR = Junior, SR = Senior, etc.)</description>
    <masterLabel>Suffix</masterLabel>
</GlobalValueSet>

classes/CZHSAAddBeneficiaryExtension.cls
public with sharing class CZHSAAddBeneficiaryExtension {
  public static Boolean invokeApiCall(
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig,
    List<tffa__Beneficiary__c> beneficiaryList,
    tffa__Application__c applicationObj
  ) {
    Boolean finalResult = false;

    try {
      FISCCRequestBaseDTO fisccRequestBaseDTO = createBeneficiaryRequest(beneficiaryList, applicationObj);
      Object result = FISCCHostAdapter.processHostRequest(fisccRequestBaseDTO, adapterConfig, charterConfig);

      finalResult = isFISCCAPICallSuccess(result);
      if (finalResult) {
        FISCCIntegrationLogService.setLogItemOk(FISCCIntegrationConstants.HSA_NEW_BENEFICIARY);
        return true;
      } else {
        FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.HSA_NEW_BENEFICIARY);
        return false;
      }
    } catch (Exception ex) {
      tffa.Logger.debug(
        'Exception in CZHSAAddBeneficiaryExtension.invokeApiCall ' +
        ex.getMessage() +
        ' Exception :::' +
        ex.getStackTraceString()
      );
      FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.HSA_NEW_BENEFICIARY);
      return false;
    }
  }

  public static FISCCRequestBaseDTO createBeneficiaryRequest(
    List<tffa__Beneficiary__c> beneficiaryList,
    tffa__Application__c applicationObj
  ) {
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    CZHSAAddBeneficiaryReqDTO request = new CZHSAAddBeneficiaryReqDTO();

    try {
      request.acctInfo.ApplCde = 'DP';
      request.acctInfo.AcctNum = applicationObj.tffa__AccountNumber__c;

      for (tffa__Beneficiary__c benef : beneficiaryList) {
        CZHSAAddBeneficiaryReqDTO.AddList addList = new CZHSAAddBeneficiaryReqDTO.AddList();
        addList.E1E2 = benef.tffa__RelationCodeName__c == 'SPOUSE' ? 4 : 5;
        addList.E2E1 = benef.tffa__Type__c == 'PRIMARY' ? 1 : 2;
        addList.EffDte = CZWTFCCommonHelper.formatDate(applicationObj.CZAccountOpeningDate__c, FISCCIntegrationConstants.MDM_DATE_FORMAT);
        addList.RelaPercent = benef.tffa__SharePercentage__c;

        if (benef.CZParty__c != null) {
          addList.ExistingCust.CustNum = Decimal.valueOf(benef.CZParty__r.Customer_Number__c);
        } else if (String.isNotBlank(benef.Customer_Number__c)) {
          addList.ExistingCust.CustNum = Decimal.valueOf(benef.Customer_Number__c);
        } else {
          if (benef.tffa__PartyType__c == FISCCIntegrationConstants.ORGANIZATION) {
            addList.NewCust.CustNme = CZWTFCCommonHelper.trimString(benef.tffa__LegalName__c, FISCCIntegrationConstants.FULL_NAME_LENGTH);
            addList.NewCust.CustTyp = 'O';

            if(!Test.isRunningTest()){
              CZTerafinaFisMapping__c tfFisOrganizationTypeeMap = CZTerafinaFisMapping__c.getValues(
                'OrganizationType' +
                '_' +
                benef.tffa__OrganizationType__c
              );
              addList.NewCust.BusTyp = tfFisOrganizationTypeeMap.FisValue__c;
            }
            
          } else {
            addList.NewCust.CustNme = CZWTFCCommonHelper.getFormattedFullName(
              benef.tffa__FirstName__c,
              benef.tffa__MiddleName__c,
              benef.tffa__LastName__c,
              benef.tffa__Suffix__c,
              FISCCIntegrationConstants.FULL_NAME_LENGTH
            );
            addList.NewCust.CustTyp = 'I';
            addList.NewCust.BusTyp = '';
          }


          if (benef.tffa__Address__r != null) {
            addList.NewCust.Addr = benef.tffa__Address__r.tffa__Line1__c;
            addList.NewCust.CtyStZip =
              benef.tffa__Address__r.tffa__City__c +
              ' ' +
              benef.tffa__Address__r.tffa__State__c +
              ' ' +
              benef.tffa__Address__r.tffa__ZipCode__c;
            addList.NewCust.Country = 'USA';
          }

          if (benef.tffa__BirthDate__c != null) {
            Datetime birthDate = Datetime.newInstance(benef.tffa__BirthDate__c, Time.newInstance(0, 0, 0, 0));
            addList.NewCust.BrthDte = birthDate.format('yyyy-MM-dd');
          }

          if (String.isNotBlank(benef.tffa__NationalIdentifierType__c))
            addList.NewCust.TaxId = CZWTFCCommonHelper.getTaxIdType(benef.tffa__NationalIdentifierType__c);
          if (String.isNotBlank(benef.tffa__NationalIdentifierValue__c))
            addList.NewCust.TaxNum = Decimal.valueOf(benef.tffa__NationalIdentifierValue__c);
          if (String.isNotBlank(benef.tffa__PrimaryPhone__c)) {
            String phoneNumber = benef.tffa__PrimaryPhone__c.right(10);
            addList.NewCust.Phone = Decimal.valueOf(phoneNumber);
          }

          addList.NewCust.OvrdStandardized = 'No';
          addList.NewCust.OvrdDupTaxNum = 'No';
          addList.NewCust.OvrdAddrStandardized = 'No';
        }

        request.beneficiaryInfo.AddLst.add(addList);
      }

      fisccRequestBaseDTO = request;

      tffa.Logger.debug('fisccRequestBaseDTO::' + fisccRequestBaseDTO);

      return fisccRequestBaseDTO;
    } catch (Exception ex) {
      tffa.Logger.error(
        'Exception in CZHSAAddBeneficiaryExtension createBeneficiaryRequest : ' +
        ex.getMessage() +
        ex.getLineNumber() +
        ex.getStackTraceString()
      );
    }
    return fisccRequestBaseDTO;
  }

  public static Boolean isFISCCAPICallSuccess(Object response) {
    CZHSAAddBeneficiaryResponseDTO objCZHSAAddBeneficiaryResponseDTO;
    if (response instanceof CZHSAAddBeneficiaryResponseDTO) {
      objCZHSAAddBeneficiaryResponseDTO = (CZHSAAddBeneficiaryResponseDTO) response;
    }

    tffa.Logger.debug('CZHSAAddBeneficiaryExtension - isFISCCAPICallSuccess::' + objCZHSAAddBeneficiaryResponseDTO);

    if (
      objCZHSAAddBeneficiaryResponseDTO != null &&
      objCZHSAAddBeneficiaryResponseDTO.Metadata.MsgLst != null &&
      !objCZHSAAddBeneficiaryResponseDTO.Metadata.MsgLst.isEmpty()
    ) {
      if (
        ('0').equalsIgnoreCase(objCZHSAAddBeneficiaryResponseDTO.Metadata.MsgLst[0].Code) &&
        ('Success').equalsIgnoreCase(objCZHSAAddBeneficiaryResponseDTO.Metadata.MsgLst[0].Text)
      ) {
        return true;
      }
    }

    return false;
  }
}