objects/CZTerafinaFisMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings maintains  Terafina Fis Mapping values</description>
    <fields>
        <fullName>FisValue__c</fullName>
        <description>Fis Value</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Terafina Fis Mapping</label>
</CustomObject>

objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <fields>
        <fullName>IsEncrypted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether HTTP request and response are encrypted.</description>
        <inlineHelpText>Indicates whether HTTP request and response are encrypted.</inlineHelpText>
        <label>IsEncrypted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ServiceURL__c</fullName>
        <description>This contains base url for API</description>
        <label>ServiceURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <fields>
        <fullName>ServiceURL__c</fullName>
        <description>It contains named credential having base url only</description>
        <label>ServiceURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/tffa__Employment__c.object
<CustomObject>
    <description>Captures employment information of the applicant. Employment is a relationship between two parties, usually based on a contract where work is paid for, where one party, which may be a corporation, for profit, not-for-profit organization, co-operative or other entity is the employer and the other is the employee.</description>
    <fields>
        <fullName>OccupationType__c</fullName>
        <description>Occupation of the candidate</description>
        <label>OccupationType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Occupation</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party object</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Title__c</fullName>
        <description>The designation of the employee. Could be Senior Manager, Director, VP etc.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the employment</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__EmploymentType</valueSetName>
        </valueSet>
    </fields>
    <label>Employment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Employment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsFisDueDiligenceCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Fis Due Diligence Created</description>
        <label>IsFisDueDiligenceCreated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Citizenship__c</fullName>
        <description>The citizenship of the individual.</description>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Citizenship</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__Citizenship.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Citizen</fullName>
        <label>US Citizen</label>
    </customValue>
    <customValue>
        <fullName>Resident</fullName>
        <label>Permanent Resident Alien</label>
    </customValue>
    <customValue>
        <fullName>NonResident</fullName>
        <label>Non-Permanent Resident Alien</label>
    </customValue>
    <customValue>
        <fullName>International_I20</fullName>
        <label>I20 (International Student)</label>
    </customValue>
    <description>The citizenship of the individual. Valid values are Citizen,Resident,NonResident</description>
    <masterLabel>Citizenship</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__EmploymentType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>SALARIED</fullName>
        <label>Salaried</label>
    </customValue>
    <customValue>
        <fullName>CONTRACTOR</fullName>
        <label>Contractor</label>
    </customValue>
    <customValue>
        <fullName>SELF_EMPLOYED</fullName>
        <label>Self employed</label>
    </customValue>
    <customValue>
        <fullName>FULLTIME</fullName>
        <label>Full Time</label>
    </customValue>
    <customValue>
        <fullName>PARTTIME</fullName>
        <label>Part Time</label>
    </customValue>
    <customValue>
        <fullName>RETIRED</fullName>
        <label>Retired</label>
    </customValue>
    <customValue>
        <fullName>STUDENT</fullName>
        <label>Student</label>
    </customValue>
    <customValue>
        <fullName>HOMEMAKER</fullName>
        <label>Homemaker</label>
    </customValue>
    <customValue>
        <fullName>UNEMPLOYED</fullName>
        <label>Unemployed</label>
    </customValue>
    <customValue>
        <fullName>MILITARY</fullName>
        <label>Military</label>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
        <isActive>false</isActive>
        <label>Test</label>
    </customValue>
    <description>Type of the employment, Valid values are SALARIED,CONTRACTOR,SELF_EMPLOYED,RETIRED,STUDENT,UNEMPLOYED,MILITARY</description>
    <masterLabel>EmploymentType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

classes/FISCCCreateDueDiligenceExtension.cls
public with sharing class FISCCCreateDueDiligenceExtension {
  @TestVisible
  private static boolean testException = false;

  public static boolean invokeApiCall(
    tffa__Party__c partyObj,
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    Object result = null;
    Boolean isSuccess = true;
    String logitemCCD = FISCCIntegrationLogService.setCurrentLogItem(
      FISCCIntegrationConstants.CREATE_CUSTOMER_DUE_DILIGENCE,
      partyObj.Name,
      false
    );
    if (FISCCIntegrationLogService.isLogItemNewOrFailed(logitemCCD)) {
      fisccRequestBaseDTO = FISCCCreateDueDiligenceExtension.generateRequest(partyObj);
      tffa.Logger.debug('--------- fisccRequestBaseDTO' + fisccRequestBaseDTO);
      String custNumber = '';

      FISCC_Adapter_Configs__mdt adapterconfiguration = adapterConfig.clone();

      if (!Test.isRunningTest()) {
        custNumber = adapterConfig.IsEncrypted__c ? FISCCCommonHelper.encrypt(partyObj.Customer_Number__c) : partyObj.Customer_Number__c;
      }
      adapterconfiguration.ServiceURL__c = adapterConfig.ServiceURL__c.replace('{custNumber}', custNumber);

      result = FISCCHostAdapter.processHostRequest(fisccRequestBaseDTO, adapterconfiguration, charterConfig);
      tffa.Logger.debug('--------- result' + result);
      isSuccess = FISCCCreateDueDiligenceExtension.parseCreateDDResponse(result);
      if (isSuccess) {
        partyObj.IsFisDueDiligenceCreated__c = true;
        if (!Test.isRunningTest()) {
          FISCCIntegrationLogService.setLogItemOk(FISCCIntegrationConstants.CREATE_CUSTOMER_DUE_DILIGENCE);
          FISCCIntegrationLogService.setLogItemMessage(FISCCIntegrationConstants.CREATE_CUSTOMER_DUE_DILIGENCE_SUCCESS);
        }
      } else {
        if (!Test.isRunningTest()) {
          isSuccess = false;
          FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.CREATE_CUSTOMER_DUE_DILIGENCE);
          FISCCIntegrationLogService.setLogItemMessage(FISCCIntegrationConstants.ErrorMessage);
          throw new tffa.ApplicationException('create Due diligence failed');
        }
      }
    }
    return isSuccess;
  }

  public static FISCCRequestBaseDTO generateRequest(tffa__Party__c partyObj) {
    tffa.Logger.debug('In generateDDReq');
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    FISCCCreateDDRequestDTO createDDReq = new FISCCCreateDDRequestDTO();
    try {
      if (Test.isRunningTest() && testException) {
        throw new tffa.ApplicationException('Called through test class');
      }

      if (partyObj != null && partyObj.tffa__Employments__r != null && !partyObj.tffa__Employments__r.isEmpty()) {
        if (
          (partyObj.tffa__Employments__r[0].tffa__Type__c) == 'STUDENT' ||
          (partyObj.tffa__Employments__r[0].tffa__Type__c) == 'HOMEMAKER'
        ) {
          createDDReq.dueDiligenceDemographics.FullTime = 'U';
          createDDReq.dueDiligenceDemographics.OccpnDesc = partyObj.tffa__Employments__r[0].tffa__Type__c;
        } else if (partyObj.tffa__Employments__r[0].tffa__Type__c != null) {
          CZTerafinaFisMapping__c tfFisMap = CZTerafinaFisMapping__c.getValues(
            FISCCIntegrationConstants.EMPLOYMENT_TYPE +
            '_' +
            partyObj.tffa__Employments__r[0].tffa__Type__c
          );
          if (tfFisMap != null) {
            createDDReq.dueDiligenceDemographics.FullTime = tfFisMap.FisValue__c;
          }
          createDDReq.dueDiligenceDemographics.OccpnDesc = getOccupationLabel(partyObj.tffa__Employments__r[0].OccupationType__c);
        }

        if (!String.isBlank(partyObj.tffa__Employments__r[0].tffa__Title__c)) {
          createDDReq.dueDiligenceDemographics.Title = partyObj.tffa__Employments__r[0].tffa__Title__c;
        }
        if (partyObj.tffa__Citizenship__c == CZWTFCConstants.RESIDENT) {
          createDDReq.dueDiligenceDemographics.RsdntPrsn = 'Y';
        }
        fisccRequestBaseDTO = createDDReq;
      }
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in generateCreateDDRequest ' + ex.getMessage() + ' Exception :::' + ex.getStackTraceString());
    }
    return fisccRequestBaseDTO;
  }

  public static Boolean parseCreateDDResponse(Object response) {
    try {
      if (Test.isRunningTest() && testException) {
        throw new tffa.ApplicationException('Called through test class');
      }

      if (response instanceof FISCCCreateDDResponseDTO) {
        FISCCCreateDDResponseDTO createDDResp = (FISCCCreateDDResponseDTO) response;
        return true;
      } else {
        return false;
      }
    } catch (Exception ex) {
      tffa.Logger.error('Exception in parseCreateDDResponse ' + ex.getMessage() + ' Exception :::' + ex.getStackTraceString());
      return false;
    }
  }

  public static String getOccupationLabel(String value) {
    List<Schema.PicklistEntry> picklistEntries = Schema.SObjectType.tffa__Employment__c.fields.OccupationType__c.getPicklistValues();

    if (picklistEntries != null) {
      for (Schema.PicklistEntry ple : picklistEntries) {
        if ((ple.getValue()).equalsIgnoreCase(value)) {
          return ple.getLabel();
        }
      }
    }
    return '';
  }

  public static String getEmploymentTypeLabel(String value) {
    List<Schema.PicklistEntry> picklistEntries = Schema.SObjectType.tffa__Employment__c.fields.tffa__Type__c.getPicklistValues();

    if (picklistEntries != null) {
      for (Schema.PicklistEntry ple : picklistEntries) {
        if ((ple.getValue()).equalsIgnoreCase(value)) {
          return ple.getLabel();
        }
      }
    }
    return '';
  }
}