objects/CZTerafinaFisMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings maintains  Terafina Fis Mapping values</description>
    <fields>
        <fullName>FisValue__c</fullName>
        <description>Fis Value</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Terafina Fis Mapping</label>
</CustomObject>

objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/tffa__Address__c.object
<CustomObject>
    <description>An address is a collection of information, presented in a mostly fixed format, used to give the location of a building, apartment, or other structure or a plot of land, generally using political boundaries and street names as references,  along with other identifiers such as house or apartment numbers

 For more reference lookup https://en.wikipedia.org/wiki/Address_(geography)#United_States</description>
    <fields>
        <fullName>tffa__City__c</fullName>
        <description>The city of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Country__c</fullName>
        <description>Country of the address</description>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__AddressCountry</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Line1__c</fullName>
        <description>line 1 of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Line1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Line2__c</fullName>
        <description>line 2 of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <description>A state is a geographical region of a country used for administrative or political purposes,</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ZipCode__c</fullName>
        <description>Also known as post code , a series of numbers that forms part of an address, used to help organize post so that it can be delivered more quickly</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__DueDiligence__c.object
<CustomObject>
    <description>Due diligence is the process of gathering data in order to verify the identity of the applicant and to make sure they are not involved in money laundering , fraud  and high risk activities.
Tracks due diligence status for the given provider.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to related party.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Due Diligences</relationshipLabel>
        <relationshipName>DueDiligences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>The status captured for the due diligence record.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceType</valueSetName>
        </valueSet>
    </fields>
    <label>Due Diligence</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Due Diligences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__DueDiligenceItem__c.object
<CustomObject>
    <description>List of answers  which are captured for the applicant against the CDD questions. CDD questions can be fetched from KBA third party systems.</description>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>A logical name that uniquely identifies the item among a list. Can be a question code.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__DueDiligence__c</fullName>
        <description>Reference to parent due diligence.</description>
        <label>Due Diligence</label>
        <referenceTo>tffa__DueDiligence__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <defaultValue>&quot;QUESTION&quot;</defaultValue>
        <description>The nature of the item. A DueDiligence item can hold OOW questions, or results related to a DueDiligence activity, e.g. name mismatch, phone mismatch, etc</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceItemType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Value__c</fullName>
        <description>The value of the answer captured.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Due Diligence Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Due Diligence Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Employment__c.object
<CustomObject>
    <description>Captures employment information of the applicant. Employment is a relationship between two parties, usually based on a contract where work is paid for, where one party, which may be a corporation, for profit, not-for-profit organization, co-operative or other entity is the employer and the other is the employee.</description>
    <fields>
        <fullName>OccupationType__c</fullName>
        <description>Occupation of the candidate</description>
        <label>OccupationType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Occupation</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employment address</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party object</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Title__c</fullName>
        <description>The designation of the employee. Could be Senior Manager, Director, VP etc.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the employment</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__EmploymentType</valueSetName>
        </valueSet>
    </fields>
    <label>Employment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Employment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>tffa__BusinessDescription__c</fullName>
        <description>Description of business</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Business description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Citizenship__c</fullName>
        <description>The citizenship of the individual.</description>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Citizenship</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__CountryOfCitizenship__c</fullName>
        <description>The name of the country of citizenship of the individual.</description>
        <label>Country of citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__CountryOfCitizenship</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyAddressXref__c.object
<CustomObject>
    <description>Association table between Party and Address . This supports capture of multiple types and also periodAtAddress.
This creates an address book of the party</description>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <description>The address lookup @managed</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyAddresses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>The party which owns the address.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>AddressXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Indicates address type. Classification of the address with respect to owning entity type. 

For individual, values are - HOME,MAILING,PERMANENT
For company, values are - REGISTERED,MAILING</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__AddressType</valueSetName>
        </valueSet>
    </fields>
    <label>Party Address Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartyAddresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/tffa__AddressCountry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>TW</fullName>
    </customValue>
    <customValue>
        <fullName>MF</fullName>
    </customValue>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>US</fullName>
        <default>true</default>
        <label>United States of America</label>
    </customValue>
    <customValue>
        <fullName>CN</fullName>
        <label>China</label>
    </customValue>
    <customValue>
        <fullName>AF</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AX</fullName>
    </customValue>
    <customValue>
        <fullName>DZ</fullName>
    </customValue>
    <customValue>
        <fullName>AS</fullName>
    </customValue>
    <customValue>
        <fullName>AD</fullName>
    </customValue>
    <customValue>
        <fullName>AO</fullName>
    </customValue>
    <customValue>
        <fullName>AI</fullName>
    </customValue>
    <customValue>
        <fullName>AG</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AM</fullName>
    </customValue>
    <customValue>
        <fullName>AW</fullName>
    </customValue>
    <customValue>
        <fullName>AU</fullName>
    </customValue>
    <customValue>
        <fullName>AT</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>BS</fullName>
    </customValue>
    <customValue>
        <fullName>BH</fullName>
    </customValue>
    <customValue>
        <fullName>BD</fullName>
    </customValue>
    <customValue>
        <fullName>BB</fullName>
    </customValue>
    <customValue>
        <fullName>BY</fullName>
    </customValue>
    <customValue>
        <fullName>BE</fullName>
    </customValue>
    <customValue>
        <fullName>BZ</fullName>
    </customValue>
    <customValue>
        <fullName>BJ</fullName>
    </customValue>
    <customValue>
        <fullName>BM</fullName>
    </customValue>
    <customValue>
        <fullName>BT</fullName>
    </customValue>
    <description>All the countries of the world</description>
    <masterLabel>AddressCountry</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__AddressType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HOME</fullName>
        <default>true</default>
        <label>Home</label>
    </customValue>
    <customValue>
        <fullName>PREVIOUS_HOME</fullName>
        <label>Previous Home</label>
    </customValue>
    <customValue>
        <fullName>MAILING</fullName>
        <label>Mailing</label>
    </customValue>
    <customValue>
        <fullName>PERMANENT</fullName>
        <label>Permanent</label>
    </customValue>
    <customValue>
        <fullName>REGISTERED</fullName>
        <label>Registered</label>
    </customValue>
    <customValue>
        <fullName>WORK</fullName>
        <label>Work</label>
    </customValue>
    <customValue>
        <fullName>PREVIOUS_REGISTERED</fullName>
        <label>Previous Registered</label>
    </customValue>
    <description>Classification of the address</description>
    <masterLabel>AddressType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__Citizenship.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Citizen</fullName>
        <label>US Citizen</label>
    </customValue>
    <customValue>
        <fullName>Resident</fullName>
        <label>Permanent Resident Alien</label>
    </customValue>
    <customValue>
        <fullName>NonResident</fullName>
        <label>Non-Permanent Resident Alien</label>
    </customValue>
    <customValue>
        <fullName>International_I20</fullName>
        <label>I20 (International Student)</label>
    </customValue>
    <description>The citizenship of the individual. Valid values are Citizen,Resident,NonResident</description>
    <masterLabel>Citizenship</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__DueDiligenceItemType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>QUESTION</fullName>
        <label>Question</label>
    </customValue>
    <customValue>
        <fullName>RESPONSE</fullName>
        <label>Response</label>
    </customValue>
    <description>Types of DueDiligenceItem(s). A DueDiligenceItem can be used to store OOW Questions, or results related to a DueDiligence activity.</description>
    <masterLabel>DueDiligenceItemType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__DueDiligenceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IDV</fullName>
    </customValue>
    <customValue>
        <fullName>CDD</fullName>
    </customValue>
    <customValue>
        <fullName>FRAUD</fullName>
        <label>Fraud</label>
    </customValue>
    <customValue>
        <fullName>OFAC</fullName>
    </customValue>
    <customValue>
        <fullName>QUALIFILE</fullName>
        <label>QualiFile</label>
    </customValue>
    <customValue>
        <fullName>IDA</fullName>
    </customValue>
    <customValue>
        <fullName>CREDIT_BUREAU</fullName>
        <label>Credit Bureau</label>
    </customValue>
    <customValue>
        <fullName>DEBIT_BUREAU</fullName>
        <label>Debit Bureau</label>
    </customValue>
    <description>Types of due diligences</description>
    <masterLabel>DueDiligenceType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__EmploymentType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>SALARIED</fullName>
        <label>Salaried</label>
    </customValue>
    <customValue>
        <fullName>CONTRACTOR</fullName>
        <label>Contractor</label>
    </customValue>
    <customValue>
        <fullName>SELF_EMPLOYED</fullName>
        <label>Self employed</label>
    </customValue>
    <customValue>
        <fullName>FULLTIME</fullName>
        <label>Full Time</label>
    </customValue>
    <customValue>
        <fullName>PARTTIME</fullName>
        <label>Part Time</label>
    </customValue>
    <customValue>
        <fullName>RETIRED</fullName>
        <label>Retired</label>
    </customValue>
    <customValue>
        <fullName>STUDENT</fullName>
        <label>Student</label>
    </customValue>
    <customValue>
        <fullName>HOMEMAKER</fullName>
        <label>Homemaker</label>
    </customValue>
    <customValue>
        <fullName>UNEMPLOYED</fullName>
        <label>Unemployed</label>
    </customValue>
    <customValue>
        <fullName>MILITARY</fullName>
        <label>Military</label>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
        <isActive>false</isActive>
        <label>Test</label>
    </customValue>
    <description>Type of the employment, Valid values are SALARIED,CONTRACTOR,SELF_EMPLOYED,RETIRED,STUDENT,UNEMPLOYED,MILITARY</description>
    <masterLabel>EmploymentType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

classes/FISCCCustomerDDExtension.cls
public with sharing class FISCCCustomerDDExtension {
  public static FISCCDepositOriginationRequestBaseDTO generateCustomerDDRequest(
    tffa__Party__c partyObj,
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    FISCCDepositOriginationRequestBaseDTO fisccDepositOriginationRequestBaseDTO = null;
    try {
      tffa.Logger.debug('Inside generateCustomerDDRequest method');
      FISCCDOCustomerDDRequest baseddReq = new FISCCDOCustomerDDRequest();
      baseddReq.dueDiligenceReq.dueDiligenceDemographics.CustNbr = FISCCIntegrationConstants.MBPASS_DUMMY_CUSTOMER_NUMBER;
      if (
        partyObj.tffa__Type__c == FISCCIntegrationConstants.INDIVIDUAL &&
        partyObj.tffa__Employments__r != null &&
        !partyObj.tffa__Employments__r.isEmpty()
      ) {
        baseddReq.dueDiligenceReq.dueDiligenceDemographics.OccpnDesc = CZWTFCCommonHelper.getOccupationLabel(
          partyObj.tffa__Employments__r[0].OccupationType__c
        );
        if (String.isNotBlank(partyObj.tffa__Employments__r[0].tffa__Title__c)) {
          baseddReq.dueDiligenceReq.dueDiligenceDemographics.Title = partyObj.tffa__Employments__r[0].tffa__Title__c;
        }
        if (partyObj.tffa__Employments__r[0].tffa__Type__c == 'RETIRED') {
          baseddReq.dueDiligenceReq.dueDiligenceDemographics.FullTime = 'R';
        } else if (partyObj.tffa__Employments__r[0].tffa__Type__c == 'UNEMPLOYED') {
          baseddReq.dueDiligenceReq.dueDiligenceDemographics.FullTime = 'U';
        }
      }

      if (partyObj.tffa__Type__c == FISCCIntegrationConstants.INDIVIDUAL && partyObj.tffa__Citizenship__c == CZWTFCConstants.RESIDENT) {
        baseddReq.dueDiligenceReq.dueDiligenceDemographics.RsdntPrsn = 'Y';
        if (partyObj.tffa__CountryOfCitizenship__c != null) {
          CZTerafinaFisMapping__c tfFisCountryOfCitizenMap = CZTerafinaFisMapping__c.getValues(
            'AddressCountry' +
            '_' +
            partyObj.tffa__CountryOfCitizenship__c
          );
          if (tfFisCountryOfCitizenMap != null) {
            baseddReq.dueDiligenceReq.dueDiligenceDemographics.CntryCtznshp = tfFisCountryOfCitizenMap.FisValue__c;
          }
        }
      }
      /* tffa__Address__c addressObj;
      if (partyObj.tffa__AddressXrefs__r != null && partyObj.tffa__AddressXrefs__r.size() > 1) {
        addressObj = CZWTFCCommonHelper.getPartyAddressByType(partyObj.tffa__AddressXrefs__r, 'HOME');
      }
      if (addressObj != null) {
        baseddReq.dueDiligenceReq.dueDiligenceDemographics.Cmmt = getAddressString(addressObj);
      }
      */
      if (partyObj.tffa__Type__c == FISCCIntegrationConstants.ORGANIZATION) {
        if (String.isNotBlank(partyObj.tffa__BusinessDescription__c)) {
          baseddReq.dueDiligenceReq.dueDiligenceDemographics.DescBus = partyObj.tffa__BusinessDescription__c;
        }
        if (FISCCIntegrationLogService.cddObjMap.containsKey(partyObj.Id)) {
          baseddReq = setCDDQuestions(partyObj, baseddReq);
        }
        baseddReq.dueDiligenceReq.dueDiligenceDemographics.UsrDefFld22 = partyObj.CZIsCIPExempt__c ? 'Y' : 'N';
      }

      fisccDepositOriginationRequestBaseDTO = baseddReq;
      tffa.Logger.debug('generateCustomerDDRequest req ==> ' + fisccDepositOriginationRequestBaseDTO);
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in generateCustomerDDRequest ' + ex.getLineNumber() + ' ' + ex.getMessage());
    }
    return fisccDepositOriginationRequestBaseDTO;
  }

  public static String getAddressString(tffa__Address__c addressObj) {
    String addressStr = '';
    if (String.isNotBlank(addressObj.tffa__Line1__c)) {
      addressStr += addressObj.tffa__Line1__c;
    }
    if (String.isNotBlank(addressObj.tffa__Line2__c)) {
      addressStr += ' ' + addressObj.tffa__Line2__c;
    }
    if (String.isNotBlank(addressObj.tffa__City__c)) {
      addressStr += ' ' + addressObj.tffa__City__c;
    }
    if (String.isNotBlank(addressObj.tffa__State__c)) {
      addressStr += ' ' + addressObj.tffa__State__c;
    }
    if (String.isNotBlank(addressObj.tffa__ZipCode__c)) {
      addressStr += ' ' + addressObj.tffa__ZipCode__c;
    }
    if (String.isNotBlank(addressObj.tffa__Country__c)) {
      addressStr += ' ' + addressObj.tffa__Country__c;
    }
    return addressStr;
  }

  public static FISCCDOCustomerDDRequest setCDDQuestions(tffa__Party__c partyObj, FISCCDOCustomerDDRequest baseddReq) {
    try {
      if (FISCCIntegrationLogService.cddObjMap != null) {
        List<tffa__DueDiligence__c> ddLst = FISCCIntegrationLogService.cddObjMap.containsKey(partyObj.Id)
          ? FISCCIntegrationLogService.cddObjMap.get(partyObj.Id)
          : null;

        if (ddLst != null && !ddLst.isEmpty()) {
          for (tffa__DueDiligence__c ddObj : ddLst) {
            if (ddObj.tffa__Items__r != null && !ddObj.tffa__Items__r.isEmpty()) {
              for (tffa__DueDiligenceItem__c ddItemObj : ddObj.tffa__Items__r) {
                if (ddItemObj.tffa__Code__c == 'ForeignOriginatingCountry') {
                  List<String> countryLst = ddItemObj.tffa__Value__c.split(';');
                  for (String country : countryLst) {
                    FISCCDOCustomerDDRequest.IncomingCountry incomingCtr = new FISCCDOCustomerDDRequest.IncomingCountry();
                    CZTerafinaFisMapping__c tfFisIdentityMap = CZTerafinaFisMapping__c.getValues('AddressCountry' + '_' + country);
                    if (tfFisIdentityMap != null) {
                      incomingCtr.InCtryCde = tfFisIdentityMap.FisValue__c;
                      baseddReq.dueDiligenceReq.incomingCountries.add(incomingCtr);
                    }
                  }
                } else if (ddItemObj.tffa__Code__c == 'ForeignDestinationCountry') {
                  List<String> countryLst = ddItemObj.tffa__Value__c.split(';');
                  for (String country : countryLst) {
                    FISCCDOCustomerDDRequest.OutgoingCountry outgoingCtr = new FISCCDOCustomerDDRequest.OutgoingCountry();
                    CZTerafinaFisMapping__c tfFisIdentityMap = CZTerafinaFisMapping__c.getValues('AddressCountry' + '_' + country);
                    if (tfFisIdentityMap != null) {
                      outgoingCtr.OutCtryCde = tfFisIdentityMap.FisValue__c;
                      baseddReq.dueDiligenceReq.outgoingCountries.add(outgoingCtr);
                    }
                  }
                } else {
                  baseddReq.dueDiligenceReq.dueDiligenceDemographics.setValue(
                    ddItemObj.tffa__Code__c,
                    getCddValue(ddItemObj.tffa__Value__c)
                  );
                }
              }
            }
          }
        }
      }
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in setCDDQuestions ' + ex.getMessage());
    }
    return baseddReq;
  }

  public static String getCddValue(String value) {
    if (value == 'Yes') {
      return 'Y';
    } else if (value == 'No') {
      return 'N';
    } else {
      return value;
    }
  }
}