objects/CZTerafinaFisMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom settings maintains  Terafina Fis Mapping values</description>
    <fields>
        <fullName>FisValue__c</fullName>
        <description>Fis Value</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Terafina Fis Mapping</label>
</CustomObject>

objects/tffa__Address__c.object
<CustomObject>
    <description>An address is a collection of information, presented in a mostly fixed format, used to give the location of a building, apartment, or other structure or a plot of land, generally using political boundaries and street names as references,  along with other identifiers such as house or apartment numbers

 For more reference lookup https://en.wikipedia.org/wiki/Address_(geography)#United_States</description>
    <fields>
        <fullName>tffa__City__c</fullName>
        <description>The city of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Line1__c</fullName>
        <description>line 1 of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Line1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Line2__c</fullName>
        <description>line 2 of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <description>A state is a geographical region of a country used for administrative or political purposes,</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ZipCode__c</fullName>
        <description>Also known as post code , a series of numbers that forms part of an address, used to help organize post so that it can be delivered more quickly</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Employment__c.object
<CustomObject>
    <description>Captures employment information of the applicant. Employment is a relationship between two parties, usually based on a contract where work is paid for, where one party, which may be a corporation, for profit, not-for-profit organization, co-operative or other entity is the employer and the other is the employee.</description>
    <fields>
        <fullName>OccupationType__c</fullName>
        <description>Occupation of the candidate</description>
        <label>OccupationType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Occupation</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employment address</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party object</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Title__c</fullName>
        <description>The designation of the employee. Could be Senior Manager, Director, VP etc.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the employment</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__EmploymentType</valueSetName>
        </valueSet>
    </fields>
    <label>Employment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Employment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>CellPhoneNumber__c</fullName>
        <description>Cell phone of the party.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Cell phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CostCenter__c</fullName>
        <description>Cost center for location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Cost center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>Fis branch code for Location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Branch Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsCrossCharterCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is CrossCharter Customer</description>
        <inlineHelpText>If the customer is not having an existing realtionship with this charter but has a relationship in another charter.</inlineHelpText>
        <label>CrossCharter Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__BirthDate__c</fullName>
        <description>The date of birth of the individual</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Birth date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>tffa__BusinessDescription__c</fullName>
        <description>Description of business</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Business description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Citizenship__c</fullName>
        <description>The citizenship of the individual.</description>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Citizenship</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__FirstName__c</fullName>
        <description>The first name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__IndustryClassificationValue__c</fullName>
        <description>the value captured against the industrylassificationType</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Industry classification value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__IsEmployee__c</fullName>
        <defaultValue>false</defaultValue>
        <description>true, if the individual is an employee of the bank</description>
        <label>Is employee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__IsExistingCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current applicant is existing customer of the bank.</description>
        <label>IsExistingCustomer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>The last name of the individual represented by the parent object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LegalName__c</fullName>
        <description>The legal name of a business is the official name of the person or entity that owns a business.For limited partnerships, LLCs, and corporations, the legal name of the business is the name registered with the state filing office</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Legal name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__MiddleName__c</fullName>
        <description>The middle name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__NationalIdentifierType__c</fullName>
        <description>Classifies identification numbers used by the Internal Revenue Service (IRS) in the administration of tax laws.</description>
        <label>National identifier type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__NationalIdentifierType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__NationalIdentifierValue__c</fullName>
        <description>The value of the taxpayer identifier as assigned by the IRS to the individual or legal entity.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>National identifier value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__OrganizationType__c</fullName>
        <description>Type of Organization. This governs the structure of the business.</description>
        <label>Organization type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__OrganizationType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__PrimaryEmail__c</fullName>
        <description>Primary email of the party.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryPhone__c</fullName>
        <description>Primary phone number of the party</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Primary phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__SecondaryPhone__c</fullName>
        <description>Secondary phone of the party.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Secondary phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Suffix__c</fullName>
        <description>The name suffix of the individual represented by the parent object. (E.g., JR = Junior, SR = Senior, etc.)</description>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Suffix</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyAddressXref__c.object
<CustomObject>
    <description>Association table between Party and Address . This supports capture of multiple types and also periodAtAddress.
This creates an address book of the party</description>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <description>The address lookup @managed</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyAddresses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>The party which owns the address.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>AddressXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Indicates address type. Classification of the address with respect to owning entity type. 

For individual, values are - HOME,MAILING,PERMANENT
For company, values are - REGISTERED,MAILING</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__AddressType</valueSetName>
        </valueSet>
    </fields>
    <label>Party Address Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartyAddresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/tffa__AddressType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HOME</fullName>
        <default>true</default>
        <label>Home</label>
    </customValue>
    <customValue>
        <fullName>PREVIOUS_HOME</fullName>
        <label>Previous Home</label>
    </customValue>
    <customValue>
        <fullName>MAILING</fullName>
        <label>Mailing</label>
    </customValue>
    <customValue>
        <fullName>PERMANENT</fullName>
        <label>Permanent</label>
    </customValue>
    <customValue>
        <fullName>REGISTERED</fullName>
        <label>Registered</label>
    </customValue>
    <customValue>
        <fullName>WORK</fullName>
        <label>Work</label>
    </customValue>
    <customValue>
        <fullName>PREVIOUS_REGISTERED</fullName>
        <label>Previous Registered</label>
    </customValue>
    <description>Classification of the address</description>
    <masterLabel>AddressType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__Citizenship.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Citizen</fullName>
        <label>US Citizen</label>
    </customValue>
    <customValue>
        <fullName>Resident</fullName>
        <label>Permanent Resident Alien</label>
    </customValue>
    <customValue>
        <fullName>NonResident</fullName>
        <label>Non-Permanent Resident Alien</label>
    </customValue>
    <customValue>
        <fullName>International_I20</fullName>
        <label>I20 (International Student)</label>
    </customValue>
    <description>The citizenship of the individual. Valid values are Citizen,Resident,NonResident</description>
    <masterLabel>Citizenship</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__EmploymentType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>SALARIED</fullName>
        <label>Salaried</label>
    </customValue>
    <customValue>
        <fullName>CONTRACTOR</fullName>
        <label>Contractor</label>
    </customValue>
    <customValue>
        <fullName>SELF_EMPLOYED</fullName>
        <label>Self employed</label>
    </customValue>
    <customValue>
        <fullName>FULLTIME</fullName>
        <label>Full Time</label>
    </customValue>
    <customValue>
        <fullName>PARTTIME</fullName>
        <label>Part Time</label>
    </customValue>
    <customValue>
        <fullName>RETIRED</fullName>
        <label>Retired</label>
    </customValue>
    <customValue>
        <fullName>STUDENT</fullName>
        <label>Student</label>
    </customValue>
    <customValue>
        <fullName>HOMEMAKER</fullName>
        <label>Homemaker</label>
    </customValue>
    <customValue>
        <fullName>UNEMPLOYED</fullName>
        <label>Unemployed</label>
    </customValue>
    <customValue>
        <fullName>MILITARY</fullName>
        <label>Military</label>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
        <isActive>false</isActive>
        <label>Test</label>
    </customValue>
    <description>Type of the employment, Valid values are SALARIED,CONTRACTOR,SELF_EMPLOYED,RETIRED,STUDENT,UNEMPLOYED,MILITARY</description>
    <masterLabel>EmploymentType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__NationalIdentifierType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>SSN</fullName>
    </customValue>
    <customValue>
        <fullName>TIN</fullName>
    </customValue>
    <description>Classifies identification numbers used by the Internal Revenue Service IRS.</description>
    <masterLabel>NationalIdentifierType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__Suffix.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Jr</fullName>
    </customValue>
    <customValue>
        <fullName>Sr</fullName>
        <label>Sr.</label>
    </customValue>
    <customValue>
        <fullName>II</fullName>
    </customValue>
    <customValue>
        <fullName>III</fullName>
    </customValue>
    <customValue>
        <fullName>IV</fullName>
    </customValue>
    <customValue>
        <fullName>246</fullName>
        <isActive>false</isActive>
        <label>246</label>
    </customValue>
    <customValue>
        <fullName>Esq</fullName>
        <isActive>false</isActive>
        <label>Esq</label>
    </customValue>
    <customValue>
        <fullName>VI</fullName>
        <isActive>false</isActive>
        <label>VI</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <isActive>false</isActive>
        <label>V</label>
    </customValue>
    <customValue>
        <fullName>2nd</fullName>
        <isActive>false</isActive>
        <label>2nd</label>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
        <isActive>false</isActive>
        <label>Test</label>
    </customValue>
    <description>The name suffix of the individual represented by the parent object. (E.g., JR = Junior, SR = Senior, etc.)</description>
    <masterLabel>Suffix</masterLabel>
</GlobalValueSet>

classes/FISCCUpdateCustomerInfoExtension.cls
public with sharing class FISCCUpdateCustomerInfoExtension {
  public static List<FISCCDepositOriginationRequestBaseDTO> generatePhnEmailDelReq(tffa__Party__c partyObj) {
    List<FISCCDepositOriginationRequestBaseDTO> reqList = new List<FISCCDepositOriginationRequestBaseDTO>();

    if (partyObj.CZFisEmail__c != null && partyObj.CZFisEmail__c != partyObj.tffa__PrimaryEmail__c) {
      FISCCCreateEmailAddressesDTO objFISCCCreateEmailAddressesDTO = new FISCCCreateEmailAddressesDTO();
      List<FISCCCreateEmailAddressesDTO> lstFISCCCreateEmailAddressesDTO = new List<FISCCCreateEmailAddressesDTO>();
      FISCCDOCustomerEmailRequest objFISCCDOCustomerEmailRequest = new FISCCDOCustomerEmailRequest();
      objFISCCCreateEmailAddressesDTO.AddDelInd = 'D';
      objFISCCCreateEmailAddressesDTO.ResnCde = 'PRI';
      objFISCCCreateEmailAddressesDTO.EffDte = partyObj.CZFisEmailEffDt__c;
      lstFISCCCreateEmailAddressesDTO.add(objFISCCCreateEmailAddressesDTO);
      objFISCCDOCustomerEmailRequest.customerEmail.emailAddressLst = lstFISCCCreateEmailAddressesDTO;
      objFISCCDOCustomerEmailRequest.customerEmail.CustNbr = partyObj.Customer_Number__c;
      objFISCCDOCustomerEmailRequest.SvcID = FISCCIntegrationConstants.SVCID_CustomerEmail;
      reqList.add(objFISCCDOCustomerEmailRequest);
    }

    if (checkFISContactNumberIsPresentForDelete(partyObj, 'All')) {
      FISCCCreatePhoneNumberDTO objprimaryPhneDTO = new FISCCCreatePhoneNumberDTO();
      FISCCCreatePhoneNumberDTO objWrkPhneDTO = new FISCCCreatePhoneNumberDTO();
      FISCCCreatePhoneNumberDTO objCellPhneDTO = new FISCCCreatePhoneNumberDTO();
      List<FISCCCreatePhoneNumberDTO> lstFISCCCreatePhoneNumberDTO = new List<FISCCCreatePhoneNumberDTO>();
      FISCCDOPhoneNumberRequest objFISCCDOPhoneNumberRequest = new FISCCDOPhoneNumberRequest();

      if (checkFISContactNumberIsPresentForDelete(partyObj, 'Home')) {
        objprimaryPhneDTO.AddDelInd = 'D';
        if (partyObj.tffa__Type__c == FISCCIntegrationConstants.INDIVIDUAL) {
          objprimaryPhneDTO.ResnCde = 'HME';
        } else {
          objprimaryPhneDTO.ResnCde = 'PRI';
        }

        objprimaryPhneDTO.EffDte = partyObj.CZFisHomeNbrEffDt__c;
        lstFISCCCreatePhoneNumberDTO.add(objprimaryPhneDTO);
      }

      if (checkFISContactNumberIsPresentForDelete(partyObj, 'Work')) {
        objWrkPhneDTO.AddDelInd = 'D';
        if (partyObj.tffa__Type__c == FISCCIntegrationConstants.INDIVIDUAL) {
          objWrkPhneDTO.ResnCde = 'WRK';
        } else {
          objWrkPhneDTO.ResnCde = 'SEC';
        }
        objWrkPhneDTO.EffDte = partyObj.CZFisWorkNbrEffDt__c;
        lstFISCCCreatePhoneNumberDTO.add(objWrkPhneDTO);
      }

      if (checkFISContactNumberIsPresentForDelete(partyObj, 'Cell')) {
        objCellPhneDTO.AddDelInd = 'D';
        objCellPhneDTO.ResnCde = 'MBL';
        objCellPhneDTO.EffDte = partyObj.CZFisCellNbrEffDt__c;
        lstFISCCCreatePhoneNumberDTO.add(objCellPhneDTO);
      }

      objFISCCDOPhoneNumberRequest.custPhoneNumber.CustNbr = partyObj.Customer_Number__c;
      objFISCCDOPhoneNumberRequest.SvcID = 'CI051';
      objFISCCDOPhoneNumberRequest.custPhoneNumber.phoneNumLst = lstFISCCCreatePhoneNumberDTO;
      reqList.add(objFISCCDOPhoneNumberRequest);
    }
    return reqList;
  }

  public static FISCCDepositOriginationRequestBaseDTO genUpdateCustomerDueDiligenceReq(tffa__Party__c partyObj) {
    FISCCDepositOriginationRequestBaseDTO fisccDepositOriginationRequestBaseDTO = null;
    FISCCDOCustomerDDRequest baseddReq = new FISCCDOCustomerDDRequest();
    if (partyObj.tffa__Employments__r != null && !partyObj.tffa__Employments__r.isEmpty()) {
      baseddReq.dueDiligenceReq.dueDiligenceDemographics.OccpnDesc = CZWTFCCommonHelper.getOccupationLabel(
        partyObj.tffa__Employments__r[0].OccupationType__c
      );
      if (String.isNotBlank(partyObj.tffa__Employments__r[0].tffa__Title__c)) {
        baseddReq.dueDiligenceReq.dueDiligenceDemographics.Title = partyObj.tffa__Employments__r[0].tffa__Title__c;
      } else {
        baseddReq.dueDiligenceReq.dueDiligenceDemographics.Title = '';
      }
      if (partyObj.tffa__Employments__r[0].tffa__Type__c == 'RETIRED') {
        baseddReq.dueDiligenceReq.dueDiligenceDemographics.FullTime = 'R';
      } else if (partyObj.tffa__Employments__r[0].tffa__Type__c == 'UNEMPLOYED') {
        baseddReq.dueDiligenceReq.dueDiligenceDemographics.FullTime = 'U';
      }
    }

    if (partyObj.tffa__Type__c == FISCCIntegrationConstants.INDIVIDUAL && partyObj.tffa__Citizenship__c == CZWTFCConstants.RESIDENT) {
      baseddReq.dueDiligenceReq.dueDiligenceDemographics.RsdntPrsn = 'Y';
    }

    if (partyObj.tffa__Type__c == FISCCIntegrationConstants.ORGANIZATION) {
      if (String.isNotBlank(partyObj.tffa__BusinessDescription__c)) {
        baseddReq.dueDiligenceReq.dueDiligenceDemographics.DescBus = partyObj.tffa__BusinessDescription__c;
      }
      if (FISCCIntegrationLogService.cddObjMap.containsKey(partyObj.Id)) {
        baseddReq = FISCCCustomerDDExtension.setCDDQuestions(partyObj, baseddReq);
      }
      //baseddReq.dueDiligenceReq.dueDiligenceDemographics.UsrDefFld22 = partyObj.CZIsCIPExempt__c ? 'Y' : 'N';
    }

    baseddReq.dueDiligenceReq.dueDiligenceDemographics.CustNbr = partyObj.Customer_Number__c;
    fisccDepositOriginationRequestBaseDTO = baseddReq;
    fisccDepositOriginationRequestBaseDTO.SvcID = FISCCIntegrationConstants.SVCID_DueDiligence;
    return fisccDepositOriginationRequestBaseDTO;
  }

  public static FISCCDepositOriginationRequestBaseDTO genUpdateCustomerDemographicsReq(tffa__Party__c partyObj) {
    tffa.Logger.debug('In genUpdateCustomerDueDiligenceReq');
    FISCCDepositOriginationRequestBaseDTO fisccDepositOriginationRequestBaseDTO = null;
    FISCCDOIndividualDemoRequest individualDemo = new FISCCDOIndividualDemoRequest();
    FISCCDOOrganizationDemoRequest organizationDemo = new FISCCDOOrganizationDemoRequest();

    List<String> codeList = new List<String>();
    if (partyObj.CZFisCustCodes__c != null) {
      codeList = partyObj.CZFisCustCodes__c.split(',');
    }
    tffa.Logger.debug('codeList ' + codeList + '  ' + codeList.contains('2'));
    if (partyObj.tffa__IsEmployee__c && !codeList.contains('2')) {
      codeList.add('002');
    }
    if (!partyObj.tffa__IsEmployee__c && codeList.contains('2')) {
      codeList = removeEmployeeCode(codeList);
    }
    if (FISCCCommonHelper.isPlatinumMemberShipCustomer(partyObj) && !codeList.contains('30')) {
      codeList.add('030');
    }
    if (FISCCCommonHelper.isJuniorSaverMember(partyObj) && !codeList.contains('18')) {
      codeList.add('018');
    }

    if (partyObj.tffa__Type__c == FISCCIntegrationConstants.INDIVIDUAL) {
      individualDemo.individualDemographics.CIApplNbr = partyObj.Customer_Number__c;

      individualDemo.individualDemographics.CICustDteOfBrth = String.valueOf(partyObj.tffa__BirthDate__c);
      individualDemo = FISCCCommonHelper.setIdentityInfo(partyObj, individualDemo);

      individualDemo.individualDemographics.CIBrnchNbr = partyObj.FISBranchCode__c;
      individualDemo.individualDemographics.CIPrmyOffcrNbr = partyObj.CZPrimaryOfficer__c;
      individualDemo.individualDemographics.CIScndyOffcrNbr = partyObj.CZSecondaryOfficer__c;
      individualDemo.individualDemographics.CICstCntrNbr = partyObj.CostCenter__c;

      if (String.isNotBlank(partyObj.tffa__NationalIdentifierValue__c)) {
        individualDemo.individualDemographics.DupTaxNbrOverride = 'Y';
        individualDemo.individualDemographics.CICustTaxNbr = partyObj.tffa__NationalIdentifierValue__c;
        CZTerafinaFisMapping__c tfFisTaxMap = CZTerafinaFisMapping__c.getValues('TaxType' + '_' + partyObj.tffa__NationalIdentifierType__c);
        if (tfFisTaxMap != null) {
          individualDemo.individualDemographics.CICustTaxCde = tfFisTaxMap.FisValue__c;
        }
      }

      individualDemo = fillCustomerCodes(codeList, individualDemo);

      fisccDepositOriginationRequestBaseDTO = individualDemo;
      fisccDepositOriginationRequestBaseDTO.SvcID = FISCCIntegrationConstants.INDIVIDUAL_DEMOGRAPHICS;
    } else if (partyObj.tffa__Type__c == FISCCIntegrationConstants.ORGANIZATION) {
      organizationDemo.organizationDemographics.CIApplNbr = partyObj.Customer_Number__c;

      organizationDemo.organizationDemographics.CIBrnchNbr = partyObj.FISBranchCode__c;
      organizationDemo.organizationDemographics.CIPrmyOffcrNbr = partyObj.CZPrimaryOfficer__c;
      organizationDemo.organizationDemographics.CIScndyOffcrNbr = partyObj.CZSecondaryOfficer__c;
      organizationDemo.organizationDemographics.CICstCntrNbr = partyObj.CostCenter__c;

      if (String.isNotBlank(partyObj.tffa__NationalIdentifierValue__c)) {
        organizationDemo.organizationDemographics.DupTaxNbrOverride = 'Y';
        organizationDemo.organizationDemographics.CICustTaxNbr = partyObj.tffa__NationalIdentifierValue__c;
        CZTerafinaFisMapping__c tfFisTaxMap = CZTerafinaFisMapping__c.getValues('TaxType' + '_' + partyObj.tffa__NationalIdentifierType__c);
        if (tfFisTaxMap != null) {
          organizationDemo.organizationDemographics.CICustTaxCde = tfFisTaxMap.FisValue__c;
        }
      }

      organizationDemo = fillOrgCustomerCodes(codeList, organizationDemo);

      if (String.isNotBlank(partyObj.tffa__IndustryClassificationValue__c)) {
        organizationDemo.organizationDemographics.CINaicsCde = partyObj.tffa__IndustryClassificationValue__c;
      }
      String orgType = partyObj.tffa__OrganizationType__c;
      if (orgType == 'LIMITED_LIABILITY_COMPANY') {
        orgType = 'LLC';
      }
      CZTerafinaFisMapping__c tfFisOrgTypeMap = CZTerafinaFisMapping__c.getValues('OrganizationType' + '_' + orgType);
      if (tfFisOrgTypeMap != null) {
        organizationDemo.organizationDemographics.CITypOfBusCde = tfFisOrgTypeMap.FisValue__c;
      }

      fisccDepositOriginationRequestBaseDTO = organizationDemo;
      fisccDepositOriginationRequestBaseDTO.SvcID = FISCCIntegrationConstants.ORGANIZATION_DEMOGRAPHICS;
    }
    return fisccDepositOriginationRequestBaseDTO;
  }

  public static FISCCCustNameAddressRequest generateNameAddressUpdateRequest(tffa__Party__c partyObj) {
    FISCCCustNameAddressRequest customerAddressReq = new FISCCCustNameAddressRequest();
    tffa__Address__c addressObj;
    if (!partyObj.tffa__AddressXrefs__r.isEmpty()) {
      addressObj = partyObj.tffa__AddressXrefs__r[0].tffa__Address__r;
    }
    if (partyObj.tffa__Type__c == FISCCIntegrationConstants.INDIVIDUAL) {
      customerAddressReq.customerAddress.CINmeAddrLne01 = CZWTFCCommonHelper.getFormattedFullName(
        partyObj.tffa__FirstName__c,
        partyObj.tffa__MiddleName__c,
        partyObj.tffa__LastName__c,
        partyObj.tffa__Suffix__c,
        FISCCIntegrationConstants.FULL_NAME_LENGTH
      );
    } else if (partyObj.tffa__Type__c == FISCCIntegrationConstants.ORGANIZATION) {
      if (partyObj.tffa__LegalName__c.length() > 40) {
        customerAddressReq.customerAddress.CINmeAddrLne01 = partyObj.tffa__LegalName__c.substring(0, 39);
      } else {
        customerAddressReq.customerAddress.CINmeAddrLne01 = partyObj.tffa__LegalName__c;
      }
    }
    customerAddressReq.customerAddress.CINmeAddrLneCde01 = 'N';
    if (addressObj != null) {
      customerAddressReq.customerAddress.CINmeAddrLne02 = addressObj.tffa__Line1__c;
      if (String.isNotBlank(addressObj.tffa__Line2__c)) {
        customerAddressReq.customerAddress.CINmeAddrLne03 = addressObj.tffa__Line2__c;
        customerAddressReq.customerAddress.CINmeAddrLne04 =
          addressObj.tffa__City__c +
          ' ' +
          addressObj.tffa__State__c +
          ' ' +
          addressObj.tffa__ZipCode__c;
        customerAddressReq.customerAddress.CINmeAddrLneCde02 = 'A';
        customerAddressReq.customerAddress.CINmeAddrLneCde03 = 'S';
        customerAddressReq.customerAddress.CINmeAddrLneCde04 = 'C';
      } else {
        customerAddressReq.customerAddress.CINmeAddrLne03 =
          addressObj.tffa__City__c +
          ' ' +
          addressObj.tffa__State__c +
          ' ' +
          addressObj.tffa__ZipCode__c;
        customerAddressReq.customerAddress.CINmeAddrLneCde02 = 'S';
        customerAddressReq.customerAddress.CINmeAddrLneCde03 = 'C';
        customerAddressReq.customerAddress.CINmeAddrLne04 = '';
        customerAddressReq.customerAddress.CINmeAddrLneCde04 = '';
      }
    }
    customerAddressReq.customerAddress.AddrOvrideInd = 'Y';
    customerAddressReq.customerAddress.OvrideAddrStddization = 'Y';
    customerAddressReq.customerAddress.CINmeAddrOvrideStdInd = 'Y';
    tffa.Logger.debug('Name Address update Request ' + customerAddressReq);
    return customerAddressReq;
  }

  public static List<FISCCDepositOriginationRequestBaseDTO> generatePhoneEmailUpdateReq(tffa__Party__c partyObj) {
    List<FISCCDepositOriginationRequestBaseDTO> reqList = new List<FISCCDepositOriginationRequestBaseDTO>();
    if (partyObj.tffa__PrimaryEmail__c != null && partyObj.CZFisEmail__c != partyObj.tffa__PrimaryEmail__c) {
      FISCCCreateEmailAddressesDTO objFISCCCreateEmailAddressesDTO = new FISCCCreateEmailAddressesDTO();
      List<FISCCCreateEmailAddressesDTO> lstFISCCCreateEmailAddressesDTO = new List<FISCCCreateEmailAddressesDTO>();
      FISCCDOCustomerEmailRequest objFISCCDOCustomerEmailRequest = new FISCCDOCustomerEmailRequest();
      objFISCCCreateEmailAddressesDTO.ResnCde = FISCCApplicationConstants.RESEND_CODE;
      objFISCCCreateEmailAddressesDTO.EmailAddr = partyObj.tffa__PrimaryEmail__c;
      objFISCCCreateEmailAddressesDTO.AddDelInd = FISCCIntegrationConstants.AddDelInd;
      lstFISCCCreateEmailAddressesDTO.add(objFISCCCreateEmailAddressesDTO);
      objFISCCDOCustomerEmailRequest.customerEmail.emailAddressLst = lstFISCCCreateEmailAddressesDTO;
      objFISCCDOCustomerEmailRequest.customerEmail.CustNbr = partyObj.Customer_Number__c;
      objFISCCDOCustomerEmailRequest.SvcID = FISCCIntegrationConstants.SVCID_CustomerEmail;
      reqList.add(objFISCCDOCustomerEmailRequest);
    }

    if (checkFISContactNumberIsPresentForUpdate(partyObj, 'All')) {
      FISCCCreatePhoneNumberDTO objprimaryPhneDTO = new FISCCCreatePhoneNumberDTO();
      FISCCCreatePhoneNumberDTO objWrkPhneDTO = new FISCCCreatePhoneNumberDTO();
      FISCCCreatePhoneNumberDTO objCellPhneDTO = new FISCCCreatePhoneNumberDTO();
      List<FISCCCreatePhoneNumberDTO> lstFISCCCreatePhoneNumberDTO = new List<FISCCCreatePhoneNumberDTO>();
      FISCCDOPhoneNumberRequest objFISCCDOPhoneNumberRequest = new FISCCDOPhoneNumberRequest();

      if (checkFISContactNumberIsPresentForUpdate(partyObj, 'Home')) {
        String homePhne = (partyObj.tffa__PrimaryPhone__c).Substring(partyObj.tffa__PrimaryPhone__c.length() - 10);

        String areaCde = homePhne.substring(0, 3);
        String localNbr = homePhne.substring(3, 10);

        if (partyObj.tffa__Type__c == FISCCIntegrationConstants.INDIVIDUAL) {
          objprimaryPhneDTO.ResnCde = 'HME';
        } else {
          objprimaryPhneDTO.ResnCde = 'PRI';
        }
        objprimaryPhneDTO.AddDelInd = 'A';
        objprimaryPhneDTO.AreaCde = areaCde;
        objprimaryPhneDTO.LocalNbr = localNbr;
        lstFISCCCreatePhoneNumberDTO.add(objprimaryPhneDTO);
      }

      if (checkFISContactNumberIsPresentForUpdate(partyObj, 'Work')) {
        String wrkPhne = (partyObj.tffa__SecondaryPhone__c).Substring(partyObj.tffa__SecondaryPhone__c.length() - 10);

        String areaCde = wrkPhne.substring(0, 3);
        String localNbr = wrkPhne.substring(3, 10);

        if (partyObj.tffa__Type__c == FISCCIntegrationConstants.INDIVIDUAL) {
          objWrkPhneDTO.ResnCde = 'WRK';
        } else {
          objWrkPhneDTO.ResnCde = 'SEC';
        }
        objWrkPhneDTO.AddDelInd = 'A';
        objWrkPhneDTO.AreaCde = areaCde;
        objWrkPhneDTO.LocalNbr = localNbr;
        lstFISCCCreatePhoneNumberDTO.add(objWrkPhneDTO);
      }

      if (checkFISContactNumberIsPresentForUpdate(partyObj, 'Cell')) {
        String cellPhne = (partyObj.CellPhoneNumber__c).Substring(partyObj.CellPhoneNumber__c.length() - 10);

        String areaCde = cellPhne.substring(0, 3);
        String localNbr = cellPhne.substring(3, 10);

        objCellPhneDTO.ResnCde = 'MBL';
        objCellPhneDTO.AddDelInd = 'A';
        objCellPhneDTO.AreaCde = areaCde;
        objCellPhneDTO.LocalNbr = localNbr;
        lstFISCCCreatePhoneNumberDTO.add(objCellPhneDTO);
      }

      objFISCCDOPhoneNumberRequest.custPhoneNumber.CustNbr = partyObj.Customer_Number__c;
      objFISCCDOPhoneNumberRequest.SvcID = 'CI051';
      objFISCCDOPhoneNumberRequest.custPhoneNumber.phoneNumLst = lstFISCCCreatePhoneNumberDTO;
      reqList.add(objFISCCDOPhoneNumberRequest);
    }
    return reqList;
  }

  public static boolean checkFISContactNumberIsPresentForDelete(tffa__Party__c partyObj, String type) {
    String homePhoneNbr = '';
    if (partyObj.tffa__PrimaryPhone__c != null) {
      homePhoneNbr = (partyObj.tffa__PrimaryPhone__c).Substring(partyObj.tffa__PrimaryPhone__c.length() - 10);
    }

    if ((type == 'Home' || type == 'All') && partyObj.CZFisHomeNbr__c != null && homePhoneNbr != partyObj.CZFisHomeNbr__c) {
      return true;
    }

    String wrkPhoneNbr = '';
    if (partyObj.tffa__SecondaryPhone__c != null) {
      wrkPhoneNbr = (partyObj.tffa__SecondaryPhone__c).Substring(partyObj.tffa__SecondaryPhone__c.length() - 10);
    }

    if ((type == 'Work' || type == 'All') && partyObj.CZFisWorkNbr__c != null && wrkPhoneNbr != partyObj.CZFisWorkNbr__c) {
      return true;
    }

    String cellPhoneNbr = '';
    if (partyObj.CellPhoneNumber__c != null) {
      cellPhoneNbr = (partyObj.CellPhoneNumber__c).Substring(partyObj.CellPhoneNumber__c.length() - 10);
    }
    if ((type == 'Cell' || type == 'All') && partyObj.CZFisCellNbr__c != null && cellPhoneNbr != partyObj.CZFisCellNbr__c) {
      return true;
    }

    return false;
  }

  public static boolean checkFISContactNumberIsPresentForUpdate(tffa__Party__c partyObj, String type) {
    String homePhoneNbr;
    if (partyObj.tffa__PrimaryPhone__c != null) {
      homePhoneNbr = (partyObj.tffa__PrimaryPhone__c).Substring(partyObj.tffa__PrimaryPhone__c.length() - 10);
    }
    if ((type == 'Home' || type == 'All') && homePhoneNbr != null && homePhoneNbr != partyObj.CZFisHomeNbr__c) {
      return true;
    }

    String wrkPhoneNbr;
    if (partyObj.tffa__SecondaryPhone__c != null) {
      wrkPhoneNbr = (partyObj.tffa__SecondaryPhone__c).Substring(partyObj.tffa__SecondaryPhone__c.length() - 10);
    }
    if ((type == 'Work' || type == 'All') && wrkPhoneNbr != null && wrkPhoneNbr != partyObj.CZFisWorkNbr__c) {
      return true;
    }

    String cellPhoneNbr;
    if (partyObj.CellPhoneNumber__c != null) {
      cellPhoneNbr = (partyObj.CellPhoneNumber__c).Substring(partyObj.CellPhoneNumber__c.length() - 10);
    }
    if ((type == 'Cell' || type == 'All') && cellPhoneNbr != null && cellPhoneNbr != partyObj.CZFisCellNbr__c) {
      return true;
    }
    return false;
  }

  public static List<String> removeEmployeeCode(List<String> strList) {
    Integer indx;
    for (Integer i = 0; i < strList.size(); i++) {
      if (strList[i] == '2') {
        indx = i;
        break;
      }
    }
    strList.remove(indx);
    return strList;
  }

  public static FISCCDOIndividualDemoRequest fillCustomerCodes(List<String> codeLst, FISCCDOIndividualDemoRequest individualDemo) {
    tffa.Logger.debug('In fillCustomerCodes ' + codeLst);

    individualDemo.individualDemographics.CICustCde1 = '0';
    individualDemo.individualDemographics.CICustCde2 = '0';
    individualDemo.individualDemographics.CICustCde3 = '0';
    individualDemo.individualDemographics.CICustCde4 = '0';
    individualDemo.individualDemographics.CICustCde5 = '0';
    individualDemo.individualDemographics.CICustCde6 = '0';
    individualDemo.individualDemographics.CICustCde7 = '0';
    individualDemo.individualDemographics.CICustCde8 = '0';
    individualDemo.individualDemographics.CICustCde9 = '0';
    individualDemo.individualDemographics.CICustCde10 = '0';
    individualDemo.individualDemographics.CICustCde11 = '0';
    individualDemo.individualDemographics.CICustCde12 = '0';
    individualDemo.individualDemographics.CICustCde13 = '0';
    individualDemo.individualDemographics.CICustCde14 = '0';
    individualDemo.individualDemographics.CICustCde15 = '0';

    for (String code : codeLst) {
      if (individualDemo.individualDemographics.CICustCde1 == '0') {
        individualDemo.individualDemographics.CICustCde1 = code;
      } else if (individualDemo.individualDemographics.CICustCde2 == '0') {
        individualDemo.individualDemographics.CICustCde2 = code;
      } else if (individualDemo.individualDemographics.CICustCde3 == '0') {
        individualDemo.individualDemographics.CICustCde3 = code;
      } else if (individualDemo.individualDemographics.CICustCde4 == '0') {
        individualDemo.individualDemographics.CICustCde4 = code;
      } else if (individualDemo.individualDemographics.CICustCde5 == '0') {
        individualDemo.individualDemographics.CICustCde5 = code;
      } else if (individualDemo.individualDemographics.CICustCde6 == '0') {
        individualDemo.individualDemographics.CICustCde6 = code;
      } else if (individualDemo.individualDemographics.CICustCde7 == '0') {
        individualDemo.individualDemographics.CICustCde7 = code;
      } else if (individualDemo.individualDemographics.CICustCde8 == '0') {
        individualDemo.individualDemographics.CICustCde8 = code;
      } else if (individualDemo.individualDemographics.CICustCde9 == '0') {
        individualDemo.individualDemographics.CICustCde9 = code;
      } else if (individualDemo.individualDemographics.CICustCde10 == '0') {
        individualDemo.individualDemographics.CICustCde10 = code;
      } else if (individualDemo.individualDemographics.CICustCde11 == '0') {
        individualDemo.individualDemographics.CICustCde11 = code;
      } else if (individualDemo.individualDemographics.CICustCde12 == '0') {
        individualDemo.individualDemographics.CICustCde12 = code;
      } else if (individualDemo.individualDemographics.CICustCde13 == '0') {
        individualDemo.individualDemographics.CICustCde13 = code;
      } else if (individualDemo.individualDemographics.CICustCde14 == '0') {
        individualDemo.individualDemographics.CICustCde14 = code;
      } else if (individualDemo.individualDemographics.CICustCde15 == '0') {
        individualDemo.individualDemographics.CICustCde15 = code;
      }
    }
    return individualDemo;
  }

  public static boolean updatePartyInfo(tffa__Party__c party) {
    tffa.Logger.debug('In updatePartyInfo');
    boolean isAliasDeleted = true;
    boolean partyUpdateSuccess = true;

    if (!party.CZAllAliasCreated__c) {
      if (party.tffa__IsExistingCustomer__c || party.IsCrossCharterCustomer__c) {
        List<String> aliasSeqNoList = FISCCCustomerAliasExtension.fetchCustomerAliasSeqNo(party);
        if (!aliasSeqNoList.isEmpty()) {
          isAliasDeleted = FISCCCustomerAliasExtension.deleteCustomerAlias(party, aliasSeqNoList);
        }
      }
      tffa.Logger.debug('In updatePartyInfo-->isAliasDeleted ' + isAliasDeleted);
      if (isAliasDeleted) {
        partyUpdateSuccess = FISCCCustomerAliasExtension.invokeAddAliasAPI(party);
      }
    }
    return partyUpdateSuccess;
  }

  public static FISCCDOOrganizationDemoRequest fillOrgCustomerCodes(List<String> codeLst, FISCCDOOrganizationDemoRequest organizationDemo) {
    tffa.Logger.debug('In fillCustomerCodes ' + codeLst);

    organizationDemo.organizationDemographics.CICustCde1 = '0';
    organizationDemo.organizationDemographics.CICustCde2 = '0';
    organizationDemo.organizationDemographics.CICustCde3 = '0';
    organizationDemo.organizationDemographics.CICustCde4 = '0';
    organizationDemo.organizationDemographics.CICustCde5 = '0';
    organizationDemo.organizationDemographics.CICustCde6 = '0';
    organizationDemo.organizationDemographics.CICustCde7 = '0';
    organizationDemo.organizationDemographics.CICustCde8 = '0';
    organizationDemo.organizationDemographics.CICustCde9 = '0';
    organizationDemo.organizationDemographics.CICustCde10 = '0';
    organizationDemo.organizationDemographics.CICustCde11 = '0';
    organizationDemo.organizationDemographics.CICustCde12 = '0';
    organizationDemo.organizationDemographics.CICustCde13 = '0';
    organizationDemo.organizationDemographics.CICustCde14 = '0';
    organizationDemo.organizationDemographics.CICustCde15 = '0';

    for (String code : codeLst) {
      if (organizationDemo.organizationDemographics.CICustCde1 == '0') {
        organizationDemo.organizationDemographics.CICustCde1 = code;
      } else if (organizationDemo.organizationDemographics.CICustCde2 == '0') {
        organizationDemo.organizationDemographics.CICustCde2 = code;
      } else if (organizationDemo.organizationDemographics.CICustCde3 == '0') {
        organizationDemo.organizationDemographics.CICustCde3 = code;
      } else if (organizationDemo.organizationDemographics.CICustCde4 == '0') {
        organizationDemo.organizationDemographics.CICustCde4 = code;
      } else if (organizationDemo.organizationDemographics.CICustCde5 == '0') {
        organizationDemo.organizationDemographics.CICustCde5 = code;
      } else if (organizationDemo.organizationDemographics.CICustCde6 == '0') {
        organizationDemo.organizationDemographics.CICustCde6 = code;
      } else if (organizationDemo.organizationDemographics.CICustCde7 == '0') {
        organizationDemo.organizationDemographics.CICustCde7 = code;
      } else if (organizationDemo.organizationDemographics.CICustCde8 == '0') {
        organizationDemo.organizationDemographics.CICustCde8 = code;
      } else if (organizationDemo.organizationDemographics.CICustCde9 == '0') {
        organizationDemo.organizationDemographics.CICustCde9 = code;
      } else if (organizationDemo.organizationDemographics.CICustCde10 == '0') {
        organizationDemo.organizationDemographics.CICustCde10 = code;
      } else if (organizationDemo.organizationDemographics.CICustCde11 == '0') {
        organizationDemo.organizationDemographics.CICustCde11 = code;
      } else if (organizationDemo.organizationDemographics.CICustCde12 == '0') {
        organizationDemo.organizationDemographics.CICustCde12 = code;
      } else if (organizationDemo.organizationDemographics.CICustCde13 == '0') {
        organizationDemo.organizationDemographics.CICustCde13 = code;
      } else if (organizationDemo.organizationDemographics.CICustCde14 == '0') {
        organizationDemo.organizationDemographics.CICustCde14 = code;
      } else if (organizationDemo.organizationDemographics.CICustCde15 == '0') {
        organizationDemo.organizationDemographics.CICustCde15 = code;
      }
    }
    return organizationDemo;
  }
}