objects/Deluxe_Creds__mdt.object
<CustomObject>
    <description>It contains Wintrust Configurations</description>
    <fields>
        <fullName>Endpoint_URL__c</fullName>
        <description>Endpoint Url</description>
        <label>Endpoint URL</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FI_ID__c</fullName>
        <description>FI ID</description>
        <label>FI ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FI_TOKEN__c</fullName>
        <description>FI Token</description>
        <label>FI TOKEN</label>
        <type>TextArea</type>
    </fields>
    <label>Deluxe_Creds</label>
    <pluralLabel>Deluxe_Creds</pluralLabel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>CZLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location</description>
        <label>Location</label>
        <referenceTo>tffa__Location__c</referenceTo>
        <relationshipLabel>Location</relationshipLabel>
        <relationshipName>Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>Fis branch code for Location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Branch Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The final generated account number. This will be set only after the final account number is available as part of the response of an account open API call.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this application should be considered as primary in the submission. Such applications cannot be removed from the submission. Used in bundle applications, where one application is marked as primary.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__ProductCategory__c</fullName>
        <description>Different product category supported by system. This classifies the flow of account opening , the underlying data model and the servicing components about an account.</description>
        <label>Product Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ProductCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product code identifier.</description>
        <label>Financial Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR (4 AND 5))</booleanFilter>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>$Source.tffa__ProductCategory__c</field>
                <operation>equals</operation>
                <valueField>tffa__Product__c.tffa__Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value>In Progress</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__RoutingNumber__c</fullName>
        <description>Routing number of the created account.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Routing number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ApplicationPartyXref__c.object
<CustomObject>
    <description>Each Applicant of the submission can play different roles in the application and the eventual account.</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current applicant is primary applicant of the application.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__RoleCode__c</fullName>
        <description>Denormalized code field of applicant role.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Role code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <fields>
        <fullName>tffa__RoutingNumber__c</fullName>
        <description>Routing number of the branch. An identification number assigned to the banking institution.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Routing number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Location__c.object
<CustomObject>
    <description>Named geographical place (such as a branch or terminal) that provides permanent facilities for movement of goods (such as customs, storage, and other support services) or is designated for a stated purpose. Read more: http://www.businessdictionary.com/definition/location.html</description>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>Fis branch code for Location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Branch Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__RoutingNumber__c</fullName>
        <description>Routing number of the branch. An identification number assigned to the banking institution.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Routing number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Location (branch)</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (branch)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>Fis branch code for Location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Branch Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__IsEmployee__c</fullName>
        <defaultValue>false</defaultValue>
        <description>true, if the individual is an employee of the bank</description>
        <label>Is employee</label>
        <type>Checkbox</type>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyPartyXref__c.object
<CustomObject>
    <description>A relationship between 2 applicants of a submission. 
Personal relationship could be SPOUSE, PARENT, FRIENDS.
Business relationship between a company and an individual could be DIRECTOR, OWNER, EXECUTIVE, PARTNER etc. In additional the ownership percentage can be captured for OWNER type of relationship. 
Relationship between 2 company type applicants can also be captured such as PARENT and SUBSIDIARY.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Party managing the relationship</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Related To</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Party Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Party Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <fields>
        <fullName>CZDeluxeProgram__c</fullName>
        <description>DeluxeProgramValues will be stored here</description>
        <encryptionScheme>None</encryptionScheme>
        <label>CZDeluxeProgram</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__IsEmployee__c</fullName>
        <defaultValue>false</defaultValue>
        <description>true, if the product is applicable only to an employee of the bank</description>
        <label>Is employee Product?</label>
        <type>Checkbox</type>
    </fields>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>FIS Branch Code.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This is the branch code received in URL Parameter from marketing site.</inlineHelpText>
        <label>FIS Branch Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__BrandEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The current brand of the submission</description>
        <label>Brand</label>
        <referenceTo>tffa__Brand__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__SubmissionPartyXref__c.object
<CustomObject>
    <description>An individual or a legal entity which is applying for certain services/products in the bank. An applicant exists only in the context of a submission.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to Party object @managed</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current applicant is primary applicant of the application.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission object.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submission Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CZDeluxeService.cls
global with sharing class CZDeluxeService {
  public static String getRedirectUrl(String applicationID) {
    tffa__Application__c application = CZWTFCApplicationRepository.findApplicationById(applicationID);

    String requestXML = createRequestXML(application);
    tffa.Logger.debug(requestXML);

    CZWTFCIntegrationLogService.setIntegrationLog(application.tffa__Submission__c, 'Deluxe Check Order');
    CZWTFCIntegrationLogService.setCurrentLog('Deluxe Check Order');
    CZWTFCIntegrationLogService.setCurrentLogItem('Deluxe Check Order - ' + application.Name, application.Id, true);
    String redirectURL;
    try {
      redirectURL = invokeAPIRequest(requestXML);
      CZWTFCIntegrationLogService.setLogItemOk(application.Name);
    } catch (Exception ex) {
      CZWTFCIntegrationLogService.setLogItemFailed(application.Name, ex.getMessage());
      throw ex;
    } finally {
      CZWTFCIntegrationLogService.setLogItemRequestAndResponse(requestXML, redirectURL);
      CZWTFCIntegrationLogService.persistIntegationLogs();
    }
    return redirectURL;
  }

  public static String invokeAPIRequest(String requestXML) {
    Deluxe_Creds__mdt fiConfig = CZWTFCHelperRepository.fetchDeluxeConfig('Deluxe_Data');
    string postData =
      'FIId=' +
      fiConfig.FI_ID__c +
      '&FIToken=' +
      EncodingUtil.urlEncode(fiConfig.FI_TOKEN__c, 'UTF-8') +
      '&xml_data=' +
      EncodingUtil.urlEncode(requestXML, 'UTF-8').replaceAll('\\s+', '');

    tffa.Logger.debug('postData :' + postData);

    HttpRequest req = new HttpRequest();
    req.setEndpoint(fiConfig.Endpoint_URL__c);
    req.setMethod('POST');
    req.setHeader('Content-Type', 'application/x-www-form-urlencoded');
    req.setHeader('Content-Length', string.valueOf(postData.length()));

    req.setBody(postData);
    Http http = new Http();
    HTTPResponse res = http.send(req);
    tffa.Logger.debug(res);
    String returnURL;
    if (res.getStatusCode() == 302) {
      for (String headerKey : res.getHeaderKeys()) {
        tffa.Logger.debug(headerKey + ' : ' + res.getHeader(headerKey));
      }
      returnURL = res.getHeader('Location');
    } else {
      throw new tffa.ApplicationException(res.getStatusCode() + ' ' + res.getBody());
    }
    return returnURL;
  }

  public static String createRequestXML(tffa__Application__c application) {
    User currentUser = tffa.UserService.getCurrentUser();

    Boolean isBusinessApplication = application.tffa__ProductCategory__c.contains('BUSINESS');

    Set<Id> partyIds = new Set<Id>();
    ID primaryPartyID;
    for (tffa__ApplicationPartyXref__c xref : application.tffa__PartyXrefs__r) {
      // collect all parties from appicaltion party
      if (
        CZWTFCDisclosureHelper.ROLE_MAP.get('BUSINESS_SIGNER').contains(xref.tffa__RoleCode__c) ||
        CZWTFCDisclosureHelper.ROLE_MAP.get('CONSUMER_SIGNER').contains(xref.tffa__RoleCode__c)
      )
        partyIds.add(xref.tffa__Party__c);
      if (xref.tffa__Primary__c == true) {
        primaryPartyID = xref.tffa__Party__c;
      }
    }
    if (partyIds.size() == 0) {
      tffa.Logger.error('No signers on the account. Cannot redirect to Deluxe.');
      throw new tffa.ApplicationException('No signers on the account. Cannot redirect to Deluxe.');
    }
    // get the parties with party ids
    List<tffa__Party__c> partiesWithAddress = CZWTFCPartyRepository.findAddressByParties(partyIds);

    String programName = 'NONE';
    for (tffa__Party__c prty : partiesWithAddress) {
      if (primaryPartyID == prty.ID) {
        if (prty.CZIsFounder__c) {
          programName = 'FOUNDER';
          break;
        } else if (prty.tffa__IsEmployee__c) {
          programName = 'EMPLOYEE';
          break;
        } else if (application.tffa__Product__r.CZDeluxeProgram__c != null) {
          programName = 'product level';
          break;
        }
      }
    }

    String xmlRequest = '<?xml version="1.0" encoding="UTF-8"?><Deluxe Version=\"10.0\">';
    xmlRequest = xmlRequest + '<DeluxePort>';
    xmlRequest = xmlRequest + '<ChkOrdAddRq>';
    xmlRequest = xmlRequest + '<RqUID>' + application.Id + '</RqUID>';
    xmlRequest = xmlRequest + '<ChkOrdInfo>';
    xmlRequest = xmlRequest + '<DepAcctId>';
    xmlRequest = xmlRequest + '<AcctId>' + application.tffa__AccountNumber__c + '</AcctId>';
    xmlRequest = xmlRequest + '<AcctType>DDA</AcctType>';
    xmlRequest = xmlRequest + '<BankInfo>';
    xmlRequest = xmlRequest + '<BankIdType>ABA</BankIdType>';
    xmlRequest = xmlRequest + '<BankId>' + application.tffa__Submission__r.tffa__BrandEntity__r.tffa__RoutingNumber__c + '</BankId>';
    xmlRequest = xmlRequest + '<BranchId>' + application.CZLocation__r.FISBranchCode__c + '</BranchId>';
    xmlRequest = xmlRequest + '</BankInfo>';
    xmlRequest = xmlRequest + '<Program><ProgramName>' + programName + '</ProgramName></Program>';
    if (application.CZAccountOpeningDate__c != null) {
      xmlRequest = xmlRequest + '<OpenDt>' + CZWTFCCommonHelper.formatDate(application.CZAccountOpeningDate__c, 'MM-dd') + '</OpenDt>';
    }
    if (isBusinessApplication) {
      xmlRequest = xmlRequest + '<CustomerType>Business</CustomerType>';
    } else {
      xmlRequest = xmlRequest + '<CustomerType>Personal</CustomerType>';
    }
    xmlRequest = xmlRequest + '</DepAcctId>';

    for (tffa__Party__c prt : partiesWithAddress) {
      if (prt.tffa__Type__c == 'INDIVIDUAL') {
        xmlRequest = xmlRequest + '<PersonInfo>';
        xmlRequest = xmlRequest + '<NameAddrType>Primary</NameAddrType>';
        xmlRequest = xmlRequest + '<PersonName>';
        xmlRequest = xmlRequest + '<LastName>' + prt.tffa__LastName__c + '</LastName>';
        xmlRequest = xmlRequest + '<FirstName>' + prt.tffa__FirstName__c + '</FirstName>';
        if (!String.isBlank(prt.tffa__MiddleName__c))
          xmlRequest = xmlRequest + '<MiddleName>' + prt.tffa__MiddleName__c + '</MiddleName>';
        if (!String.isBlank(prt.tffa__Suffix__c))
          xmlRequest = xmlRequest + '<NameSuffix>' + prt.tffa__Suffix__c + '</NameSuffix>';
        xmlRequest = xmlRequest + '</PersonName>';
        xmlRequest = xmlRequest + '<ContactInfo>';
        if (prt.tffa__PrimaryPhone__c != null) {
          xmlRequest = xmlRequest + '<PhoneNum>';
          xmlRequest = xmlRequest + '<PhoneType>EvePhone</PhoneType>';
          xmlRequest = xmlRequest + '<Phone>' + prt.tffa__PrimaryPhone__c + '</Phone>';
          xmlRequest = xmlRequest + '</PhoneNum>';
        } else if (prt.CellPhoneNumber__c != null) {
          xmlRequest = xmlRequest + '<PhoneNum>';
          xmlRequest = xmlRequest + '<PhoneType>EvePhone</PhoneType>';
          xmlRequest = xmlRequest + '<Phone>' + prt.CellPhoneNumber__c + '</Phone>';
          xmlRequest = xmlRequest + '</PhoneNum>';
        }
        if (prt.tffa__SecondaryPhone__c != null) {
          xmlRequest = xmlRequest + '<PhoneNum>';
          xmlRequest = xmlRequest + '<PhoneType>DayPhone</PhoneType>';
          xmlRequest = xmlRequest + '<Phone>' + prt.tffa__SecondaryPhone__c + '</Phone>';
          xmlRequest = xmlRequest + '</PhoneNum>';
        }
      } else {
        xmlRequest = xmlRequest + '<OrgInfo><Name>' + prt.Name + '</Name>';
      }

      if (application.tffa__Address__r != null) {
        tffa__Address__c addressObj = application.tffa__Address__r;
        xmlRequest = xmlRequest + '<PostAddr>';
        xmlRequest = xmlRequest + '<Addr1>' + addressObj.tffa__Line1__c + '</Addr1>';
        if (!String.isBlank(addressObj.tffa__Line2__c))
          xmlRequest = xmlRequest + '<Addr2>' + addressObj.tffa__Line2__c + '</Addr2>';
        xmlRequest = xmlRequest + '<City>' + addressObj.tffa__City__c + '</City>';
        xmlRequest = xmlRequest + '<StateProv>' + addressObj.tffa__State__c + '</StateProv>';
        xmlRequest = xmlRequest + '<PostalCode>' + addressObj.tffa__ZipCode__c + '</PostalCode>';
        xmlRequest = xmlRequest + '<Country>' + addressObj.tffa__Country__c + '</Country>';
        xmlRequest = xmlRequest + '</PostAddr>';
      }
      if (!String.isBlank(prt.tffa__PrimaryEmail__c))
        xmlRequest = xmlRequest + '<EmailAddr>' + prt.tffa__PrimaryEmail__c + '</EmailAddr>';
      xmlRequest = xmlRequest + '</ContactInfo>';
      if (prt.tffa__Type__c == 'INDIVIDUAL') {
        xmlRequest = xmlRequest + '</PersonInfo>';
      } else {
        xmlRequest = xmlRequest + '</OrgInfo>';
      }
      //}
    }
    xmlRequest = xmlRequest + '</ChkOrdInfo>';
    xmlRequest = xmlRequest + '<AgentInfo>';
    xmlRequest = xmlRequest + '<UserId>' + currentUser.userName + '</UserId>';
    xmlRequest = xmlRequest + '<FullName>' + currentUser.Name + '</FullName>';
    xmlRequest = xmlRequest + '</AgentInfo>';
    xmlRequest = xmlRequest + '</ChkOrdAddRq>';
    xmlRequest = xmlRequest + '</DeluxePort>';
    xmlRequest = xmlRequest + '</Deluxe>';
    return xmlRequest;
  }
}