objects/FinServ__FinancialAccount__c.object
<CustomObject>
    <description>A client&apos;s financial account, such as an investment account, bank account, or insurance policy.</description>
    <fields>
        <fullName>FinServ__PrimaryOwner__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Primary Owner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordType.DeveloperName</field>
                <operation>notEqual</operation>
                <value>IndustriesHousehold</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Account Primary Owner</relationshipLabel>
        <relationshipName>ClientFinancialAccounts</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Officer_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Officer Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Financial Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Financial Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>WT_Officer_Number__c</fullName>
        <description>Created as a part of DBSFCRM-707</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Officer Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WT_Bank_Officer_Lookup__c.object
<CustomObject>
    <description>This object holds the officer code lookup between source system code and Salesforce User Id</description>
    <fields>
        <fullName>WT_Branch_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Branch Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Officer_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Officer Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Source_System__c</fullName>
        <label>Source System</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Encompass</fullName>
                </value>
                <value>
                    <fullName>FIS</fullName>
                </value>
                <value>
                    <fullName>Trust</fullName>
                </value>
                <value>
                    <fullName>Wealth</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Bank_Officer_Lookups</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Officer Lookup</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Bank Officer Lookup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Officer Lookups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WT_Switch_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting is created for bypassing the execution of Automations and Triggers as and when needed.</description>
    <label>Switch Settings</label>
</CustomObject>

classes/WT_BatchBankOfficerFinAcctReconcile_T.cls
@isTest
public class WT_BatchBankOfficerFinAcctReconcile_T 
{
    @testSetup
    static void Setup()
    {
        User newUser = WT_TestSetupHelper.GetUser('testfirstname', 'testlastname', 'test-user@libertyvillebank.com', 'test-user@fakeemail.com.wintrustbank', 'Standard User');
        WT_Switch_Settings__c newSwitchSetting = WT_TestSetupHelper.GetCustomSetting();
        
        insert newSwitchSetting;
        insert newUser;
    }
    
    @isTest
    static void TestFinancialAccountUpdate()
    {
        List<User> listNewUser = [SELECT Id, Name FROM User];
        User userRecord = WT_DataFactory.createUser('WT Retail');
        insert userRecord;
        
        String householdRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        List <Account> listNewPersonAccount = WT_DataFactory.createAccounts(1, 'PersonAccount_Customer', userRecord.id);
        insert listNewPersonAccount;
        
        WT_Bank_Officer_Lookup__c newLookup = new WT_Bank_Officer_Lookup__c();
        newLookup.WT_User__c = listNewUser[0].Id;
        newLookup.WT_Branch_Code__c = '123';
        newLookup.WT_Officer_Code__c = '123';
        newLookup.WT_Source_System__c = 'FIS';        
        insert newLookup;
        
        FinServ__FinancialAccount__c newFinancialAccount = new FinServ__FinancialAccount__c();
        newFinancialAccount.FinServ__PrimaryOwner__c = listNewPersonAccount[0].Id;
        newFinancialAccount.WT_Officer_Number__c = '123|123';
        insert newFinancialAccount;
        
        Database.executeBatch(new WT_BatchBankOfficerFinAcctReconciliation());
    }
}