objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <fields>
        <fullName>ApplicationId__c</fullName>
        <description>Application Id (Field specific to FIS CodeConnect APIs)</description>
        <inlineHelpText>Application Id (Field specific to FIS CodeConnect APIs)</inlineHelpText>
        <label>ApplicationId</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentType__c</fullName>
        <defaultValue>&quot;application/json&quot;</defaultValue>
        <description>Content type for HTTP request e.g. application/json, application/xml etc.</description>
        <inlineHelpText>Content type for HTTP request  e.g. application/json, application/xml etc.</inlineHelpText>
        <label>Content Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HTTPMethod__c</fullName>
        <defaultValue>&quot;POST&quot;</defaultValue>
        <description>Valid http method e.g. GET, POST etc.</description>
        <inlineHelpText>Valid http method e.g. GET, POST etc.</inlineHelpText>
        <label>HTTP Method</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsEncrypted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether HTTP request and response are encrypted.</description>
        <inlineHelpText>Indicates whether HTTP request and response are encrypted.</inlineHelpText>
        <label>IsEncrypted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsIBSAuthRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether IBS Authorization header is required (Flag specific to FIS CodeConnect APIs).</description>
        <inlineHelpText>Indicates whether IBS Authorization header is required (Flag specific to FIS CodeConnect APIs).</inlineHelpText>
        <label>IsIBSAuthRequired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LogRequest__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked http request body will be logged in &apos;Debug Logs&apos;.</description>
        <inlineHelpText>If checked http request body will be logged in &apos;Debug Logs&apos;.</inlineHelpText>
        <label>Log Request</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ServiceURL__c</fullName>
        <description>This contains base url for API</description>
        <label>ServiceURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Timeout__c</fullName>
        <defaultValue>120000</defaultValue>
        <description>Timeout for http request in milliseconds. Default is set to maximum timeout &apos;120000&apos;.</description>
        <inlineHelpText>Timeout for http request in milliseconds. Default is set to maximum timeout &apos;120000&apos;.</inlineHelpText>
        <label>Timeout</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <fields>
        <fullName>ConsumerKey__c</fullName>
        <description>Consumer Key</description>
        <label>Consumer Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConsumerSecret__c</fullName>
        <description>Consumer Secret</description>
        <label>Consumer Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndpointUrlCBAuth__c</fullName>
        <description>This field contains base url for API explicitly to handle CB services</description>
        <label>EndpointUrlCBAuth</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndpointUrlCB__c</fullName>
        <description>This field contains base url for API explicitly to handle CB auth</description>
        <label>EndpointUrlCB</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndpointUrlCEB__c</fullName>
        <description>This contains base url for API explicitly to handle CEB</description>
        <label>EndpointUrlCEB</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndpointUrlFCM__c</fullName>
        <description>FCM URL</description>
        <label>Endpoint FCM URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndpointUrl__c</fullName>
        <description>Endpoint Url</description>
        <label>EndpointUrl</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCMConsumerKey__c</fullName>
        <description>FCM Consumer Key</description>
        <label>FCM Consumer Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCMConsumerSecret__c</fullName>
        <description>FCM Consumer Secret</description>
        <label>FCM Consumer Secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FCMEntityToken__c</fullName>
        <description>FCM Entity Token (Username and Password)</description>
        <label>FCM Entity Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FISIcEncSk1__c</fullName>
        <description>FISIcEncSk1</description>
        <label>FISIcEncSk1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FISIcEncSk2__c</fullName>
        <description>FISIcEncSk2</description>
        <label>FISIcEncSk2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FISIcEncX5ts256__c</fullName>
        <description>FISIcEncX5ts256</description>
        <label>FISIcEncX5ts256</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IBSAuthorization__c</fullName>
        <description>IBS-Authorization is not required for the sandbox environment. When provided, base64 encode the string in the format &quot;userid:password&quot;.</description>
        <inlineHelpText>IBSAuthorization.</inlineHelpText>
        <label>IBSAuthorization</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrganizationId__c</fullName>
        <description>FIS processing organization ID</description>
        <label>OrganizationId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceURL__c</fullName>
        <description>It contains named credential having base url only</description>
        <label>ServiceURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SourceId__c</fullName>
        <description>Source Id (also known as the Connectware vendor ID)</description>
        <label>SourceId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

classes/FISCCCoreAPICall.cls
public inherited sharing class FISCCCoreAPICall {
  public static HttpResponse execute(String requestBody, FISCC_Adapter_Configs__mdt adptrConfig, FISCC_Charter_Config__mdt charterConfig) {
    HttpRequest httpRequest = null;
    HttpResponse httpResponse = null;
    Http http = new Http();
    tffa.Interaction.begin(FISCCCoreAPICall.class, adptrConfig.DeveloperName);
    try {
      httpRequest = new HttpRequest();
      string postData = '';
      string auth = '';
      if (adptrConfig.DeveloperName.equalsIgnoreCase('AccessToken')) {
        if (adptrConfig.LogRequest__c) {
          FISCCIntegrationLogService.setLogItemRequestAndResponse(requestBody, null);
        }
        if (('CB').equals(FISCCIntegrationLogService.applicationCode)) {
          httpRequest.setEndpoint(charterConfig.EndpointUrlCBAuth__c + adptrConfig.ServiceURL__c);
        } else if (('FCM').equals(FISCCIntegrationLogService.applicationCode)) {
          httpRequest.setEndpoint(charterConfig.EndpointUrlFCM__c + adptrConfig.ServiceURL__c);
        } else {
          httpRequest.setEndpoint(charterConfig.EndpointUrl__c + adptrConfig.ServiceURL__c);
        }

        Blob headerValue = Blob.valueOf(charterConfig.ConsumerKey__c + ':' + charterConfig.ConsumerSecret__c);
        if (('FCM').equals(FISCCIntegrationLogService.applicationCode)) {
          headerValue = Blob.valueOf(charterConfig.FCMConsumerKey__c + ':' + charterConfig.FCMConsumerSecret__c);
        }
        String authorizationHeader = 'BASIC ' + EncodingUtil.base64Encode(headerValue);
        httpRequest.setHeader('Authorization', authorizationHeader);

        // commented and added by Rishi to handle CEB/CB integration dummy host
        httpRequest.setMethod(adptrConfig.HTTPMethod__c);
        httpRequest.setHeader('content-Type', adptrConfig.ContentType__c);
        postData = requestBody.substringAfter('"postData":"').substringBefore('"');
        tffa.logger.debug('postData ==>' + postData);
        httpRequest.setBody(postData);
      } else {
        if (('FCM').equals(FISCCIntegrationLogService.applicationCode)) {
          if (adptrConfig.DeveloperName.equalsIgnoreCase('AuthorizationToken')) {
            httpRequest.setHeader('entityToken', 'Basic ' + charterConfig.FCMEntityToken__c);
          } else {
            httpRequest.setHeader('entityToken', 'Bearer ' + FISCCIntegrationLogService.entityAuthToken);
          }
        }
        httpRequest.setHeader('content-Type', adptrConfig.ContentType__c);
        httpRequest.setMethod(adptrConfig.HTTPMethod__c);
        httpRequest.setTimeout(Integer.valueOf(adptrConfig.Timeout__c)); // 20 sec waiting Time
        // commented and added by Rishi to handle CEB integration dummy host
        //httpRequest.setEndpoint(charterConfig.ServiceURL__c + adptrConfig.ServiceURL__c);
        if (('CEB').equals(FISCCIntegrationLogService.applicationCode)) {
          httpRequest.setEndpoint(charterConfig.EndpointUrlCEB__c + adptrConfig.ServiceURL__c);
        } else if (('CB').equals(FISCCIntegrationLogService.applicationCode)) {
          httpRequest.setEndpoint(charterConfig.EndpointUrlCB__c + adptrConfig.ServiceURL__c);
        } else if (('FCM').equals(FISCCIntegrationLogService.applicationCode)) {
          httpRequest.setEndpoint(charterConfig.EndpointUrlFCM__c + adptrConfig.ServiceURL__c);
        } else {
          httpRequest.setEndpoint(charterConfig.EndpointUrl__c + adptrConfig.ServiceURL__c);
        }

        httpRequest.setHeader('uuid', CZWTFCCommonHelper.generateUUID());
        tffa.logger.debug('uuid ==>' + httpRequest.getHeader('uuid'));

        if (adptrConfig.LogRequest__c) {
          FISCCIntegrationLogService.setLogItemRequestAndResponse(
            'Endpoint: ' +
            httpRequest.getEndpoint() +
            'UUID ' +
            httpRequest.getHeader('uuid') +
            ' Request: ' +
            requestBody,
            null
          );
        }

        httpRequest.setHeader('application-id', adptrConfig.ApplicationId__c);
        httpRequest.setHeader('security-token-type', 'Oauth2');
        httpRequest.setHeader('organization-id', charterConfig.OrganizationId__c);
        httpRequest.setHeader('Accept', '*/*');

        httpRequest.setHeader('source-id', charterConfig.SourceId__c);

        httpRequest.setHeader('security-token-type', 'Oauth2');

        if (adptrConfig.IsIBSAuthRequired__c) {
          if (adptrConfig.IsEncrypted__c)
            httpRequest.setHeader('IBS-Authorization', FISCCCommonHelper.encrypt(charterConfig.IBSAuthorization__c));
          else
            httpRequest.setHeader('IBS-Authorization', charterConfig.IBSAuthorization__c);
        }
        if (adptrConfig.IsEncrypted__c) {
          httpRequest.setHeader('fis-ic-enc-x5ts256', charterConfig.FISIcEncX5ts256__c);
          httpRequest.setHeader('fis-ic-enc-sk', charterConfig.FISIcEncSk1__c + charterConfig.FISIcEncSk2__c);
        }
        httpRequest.setHeader('Authorization', FISCCIntegrationLogService.auth);
        tffa.logger.debug('Header Values ==>' + httpRequest.getHeader('Authorization'));

        if (adptrConfig.DeveloperName.equalsIgnoreCase('UploadFCMDocument')) {
          if (FISCCIntegrationLogService.contentVersionData != null) {
            tffa.logger.debug('FISCCCoreAPICall - Setting ContentVersionData in request body');
            httpRequest.setBodyAsBlob(FISCCIntegrationLogService.contentVersionData);
          }
        } else if (String.isNotBlank(requestBody) && !adptrConfig.HTTPMethod__c.equalsIgnoreCase('GET')) {
          httpRequest.setBody(requestBody);
        }
      }

      tffa.logger.debug('httpRequest3 ==> ' + httpRequest);
      httpResponse = http.send(httpRequest);
      tffa.logger.debug('httpResponse in coreApiCall =>' + httpResponse);
      if (httpResponse != null) {
        tffa.logger.debug('httpResponse body in coreApiCall =>' + httpResponse.getBody());
      }
    } catch (Exception ex) {
      tffa.logger.error('Exception :::' + ex.getMessage() + ' LineNumber :::' + ex.getStackTraceString());
    } finally {
      tffa.Interaction.close();
    }
    return httpResponse;
  }
}