objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The final generated account number. This will be set only after the final account number is available as part of the response of an account open API call.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Beneficiary__c.object
<CustomObject>
    <description>A beneficiary typically refers to someone who is eligible to receive distributions from deposits upon death of primary owner of account. Beneficiary capture typically happens for Certificate Deposits.
Designating a beneficiary not only ensures the CD will not have to go through probate when the applicant dies.</description>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Beneficiaries</relationshipLabel>
        <relationshipName>Beneficiaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Beneficiary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Beneficiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/FISCCBenefRelnExtension.cls
public with sharing class FISCCBenefRelnExtension {
  public static Boolean invokeApiCall(
    tffa__Application__c appObj,
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    tffa.Logger.debug('--------- called');
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    Object result = null;
    Boolean isSuccess;
    try {
      fisccRequestBaseDTO = FISCCBenefRelnExtension.generateBenefRelnReq(appObj);
      tffa.Logger.debug('--------- fisccRequestBaseDTO' + fisccRequestBaseDTO);
      result = FISCCHostAdapter.processHostRequest(fisccRequestBaseDTO, adapterConfig, charterConfig);
      tffa.Logger.debug('--------- result' + result);
      isSuccess = FISCCBenefRelnExtension.parseBenefRelnResponse(result);
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in FISCCBenefRelnExtension ' + ex.getMessage() + ' Exception :::' + ex.getStackTraceString());
    }
    return isSuccess;
  }

  public static FISCCRequestBaseDTO generateBenefRelnReq(tffa__Application__c appObj) {
    tffa.Logger.debug('In generateBenefRelnReq');
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    FISCCBenefRelnRequestDTO benefRelnReq = new FISCCBenefRelnRequestDTO();

    try {
      if (appObj != null && appObj.tffa__Beneficiaries__r != null && !appObj.tffa__Beneficiaries__r.isEmpty()) {
        benefRelnReq.caMaintainAcc.ApCd1 = FISCCIntegrationConstants.GenDPApplID;
        benefRelnReq.caMaintainAcc.ApNbr1 = appObj.tffa__AccountNumber__c;
        tffa.Logger.debug('In benefRelnReq');
        for (tffa__Beneficiary__c benefObj : appObj.tffa__Beneficiaries__r) {
          FISCCBenefRelnRequestDTO.CustomerAccountRelnList customerDetail = new FISCCBenefRelnRequestDTO.CustomerAccountRelnList();
          customerDetail.AcNbr2 = benefObj.Customer_Number__c;
          customerDetail.E1ToE2RlCd = 411;
          customerDetail.E2ToE1RlCd = 902;
          benefRelnReq.caAccRelnList.add(customerDetail);
        }
        fisccRequestBaseDTO = benefRelnReq;
      }
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in generateBenefRelnReq ' + ex.getMessage() + ' Exception :::' + ex.getStackTraceString());
    }
    return fisccRequestBaseDTO;
  }

  public static Boolean parseBenefRelnResponse(Object response) {
    tffa.Logger.debug('parseBenefRelnResponse----> ' + response);
    try {
      if (response instanceof FISCCBenefRelnResponseDTO) {
        FISCCBenefRelnResponseDTO benefResp = (FISCCBenefRelnResponseDTO) response;
        tffa.Logger.debug('parseBenefRelnResponse--> ' + benefResp);
        return true;
      } else {
        return false;
      }
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in parseBenefRelnResponse ' + ex.getMessage() + ' Exception :::' + ex.getStackTraceString());
      return false;
    }
  }
}