objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/tffa__AccountPreference__c.object
<CustomObject>
    <description>List of account preferences/additional services applied along with the application. Example values are ATM_CARD, INTERNET_BANKING, CHECKBOOK</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application</description>
        <inlineHelpText>Master Detail Lookup</inlineHelpText>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Account Preferences</relationshipLabel>
        <relationshipName>AccountPreferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to related party.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Account Preferences</relationshipLabel>
        <relationshipName>AccountPreferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Preference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FISCCCardBaseIntegrationExtension.cls
public inherited sharing class FISCCCardBaseIntegrationExtension {
  public FISCCCardBaseIntegrationExtension() {
  }

  public static Object invokeGenerateCardNo(
    tffa__party__c partyObj,
    tffa__AccountPreference__c accPref,
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    Object result = null;

    fisccRequestBaseDTO = FISCCCardBaseIntegrationHelper.getGenerateCardNoRequest(partyObj, accPref, charterConfig);
    tffa.Logger.debug('getGenerateCardNoRequest :: ' + fisccRequestBaseDTO);
    result = FISCCHostAdapter.processHostRequest(fisccRequestBaseDTO, adapterConfig, charterConfig);
    tffa.Logger.debug('result in invokeGenerateCardNo ==>' + result);
    return result;
  }

  public static Object invokeGenerateDepositOrigination(
    tffa__party__c partyObj,
    tffa__AccountPreference__c accPref,
    tffa__Application__c appObj,
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    Object result = null;

    fisccRequestBaseDTO = FISCCCardBaseIntegrationHelper.getDepositOriginationRequest(partyObj, accPref, appObj, charterConfig);
    tffa.Logger.debug('getDepositOriginationRequest :: ' + fisccRequestBaseDTO);
    result = FISCCHostAdapter.processHostRequest(fisccRequestBaseDTO, adapterConfig, charterConfig);
    tffa.Logger.debug('result in invokeGenerateDepositOrigination ==>' + result);
    return result;
  }

  public static Object invokeupdateCustomerDemographics(
    tffa__party__c partyObj,
    tffa__AccountPreference__c accPref,
    tffa__Application__c appObj,
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    Object result = null;

    fisccRequestBaseDTO = FISCCCardBaseIntegrationHelper.getUpdateCustDemographicsRequest(partyObj, accPref, appObj);
    tffa.Logger.debug('getUpdateCustDemographicsRequest :: ' + fisccRequestBaseDTO);
    result = FISCCHostAdapter.processHostRequest(fisccRequestBaseDTO, adapterConfig, charterConfig);
    tffa.Logger.debug('result in invokeupdateCustomerDemographics ==>' + result);
    return result;
  }

  public static Object invokeExpediteCardShipping(
    tffa__party__c partyObj,
    tffa__AccountPreference__c accPref,
    tffa__Application__c appObj,
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    Object result = null;

    fisccRequestBaseDTO = FISCCCardBaseIntegrationHelper.getExpediteDeliveryRequest(partyObj, accPref, appObj, charterConfig);
    tffa.Logger.debug('getExpediteDeliveryRequest :: ' + fisccRequestBaseDTO);
    result = FISCCHostAdapter.processHostRequest(fisccRequestBaseDTO, adapterConfig, charterConfig);
    tffa.Logger.debug('result in invokeExpediteCardShipping ==>' + result);
    return result;
  }
}