objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <fields>
        <fullName>IBSAuthorization__c</fullName>
        <description>IBS-Authorization is not required for the sandbox environment. When provided, base64 encode the string in the format &quot;userid:password&quot;.</description>
        <inlineHelpText>IBSAuthorization.</inlineHelpText>
        <label>IBSAuthorization</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/FISIBSAuthConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>FIS IBS Authentication Configuration</description>
    <fields>
        <fullName>BrandCode__c</fullName>
        <description>The Code of the charter the data is associated with</description>
        <encryptionScheme>None</encryptionScheme>
        <label>BrandCode</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IBSAuthorization__c</fullName>
        <description>Base64 encode the string in the format &amp;quot;userid:password&amp;quot;</description>
        <encryptionScheme>None</encryptionScheme>
        <label>IBSAuthorization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FISIBSAuthConfig</label>
</CustomObject>

classes/FISCCPasswordChangeProvider.cls
public with sharing class FISCCPasswordChangeProvider {
  @TestVisible
  private static boolean testException = false;

  public static Boolean processPasswordChange(FISIBSAuthConfig__c fisAuth, String password) {
    tffa.Logger.debug('in FISCCPasswordChangeProvider processPasswordChange fisAuth: ' + fisAuth + ' Password: ' + password);

    Boolean isSuccess = false;
    try {
      if (Test.isRunningTest() && testException) {
        throw new tffa.ApplicationException('Called through test class');
      }

      String strDeveloperName = 'PasswordChange';
      FISCC_Adapter_Configs__mdt adapterConfig = FISCCIntegrationLogRepository.findAdapterConfig(strDeveloperName);

      FISCC_Charter_Config__mdt charterConfig = FISCCIntegrationLogRepository.findCharterConfigByBrandCode(fisAuth.BrandCode__c);

      FISCCIntegrationLogService.auth = FISCCGetAccessTokenProvider.processGetAccessToken(charterConfig);

      charterConfig.IBSAuthorization__c = fisAuth.IBSAuthorization__c;
      isSuccess = FISCCPasswordChangeExtension.invokeApiCall(fisAuth, password, adapterConfig, charterConfig);
    } catch (Exception ex) {
      tffa.Logger.debug(
        'Exception in FISCCPasswordChangeProvider processPasswordChange ' +
        ex.getMessage() +
        ' Exception :::' +
        ex.getStackTraceString()
      );
    }
    return isSuccess;
  }
}