objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

classes/FISCCDemographicsProvider.cls
public with sharing class FISCCDemographicsProvider {
  static List<Id> partyObjInternationalPhnLst = new List<Id>();
  public static boolean processIntPhoneNbr(List<tffa__Party__c> partyObjLst) {
    tffa.Logger.debug('In FISCCDemographicsProvider.processIntPhoneNbr');
    boolean isSuccess = false;
    try {
      FISCCRequestBaseDTO fisccRequestBaseDTO;
      FISCC_Adapter_Configs__mdt adapterConfig = FISCCIntegrationLogRepository.findAdapterConfig(
        FISCCIntegrationConstants.DeveloperName_Deposit_Originate
      );
      //FISCCIntegrationLogService.setCurrentLog(FISCCIntegrationConstants.CUSTOMER_INFORMATION);
      List<FISCCDepositOriginationRequestBaseDTO> lstFISCCDepositOriginationRequestBaseDTO = generateDemoGraphicsReq(partyObjLst);

      FISCCDepositOriginationRequest objFISCCDepositOriginationRequest = new FISCCDepositOriginationRequest();
      objFISCCDepositOriginationRequest.DepositOriginationLst = lstFISCCDepositOriginationRequestBaseDTO;
      tffa.logger.debug(
        'objFISCCDepositOriginationRequest.DepositOriginationLst in processIntPhoneNbr DO build Request ==>' +
        objFISCCDepositOriginationRequest.DepositOriginationLst
      );
      fisccRequestBaseDTO = objFISCCDepositOriginationRequest;
      Object result = null;
      FISCCIntegrationLogService.setCurrentLogItem(FISCCIntegrationConstants.CUST, FISCCIntegrationConstants.INT_PHN_NBR, true);

      result = FISCCHostAdapter.processHostRequest(fisccRequestBaseDTO, adapterConfig, FISCCIntegrationLogService.charterConfig);

      if (parseDemogrphicsResp(result)) {
        FISCCIntegrationLogService.setLogItemOk(FISCCIntegrationConstants.DEPOSIT_ORIGINATOR_INDIVIDUAL_DEMOGRAPHICS);
        isSuccess = true;
      } else {
        FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.DEPOSIT_ORIGINATOR_INDIVIDUAL_DEMOGRAPHICS);
        isSuccess = false;
      }
    } catch (Exception ex) {
      tffa.Logger.error('Exception in FISCCDemographicsProvider.processIntPhoneNbr ' + ex.getLineNumber() + ' ' + ex.getMessage());
      FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.DEPOSIT_ORIGINATOR_INDIVIDUAL_DEMOGRAPHICS);
      isSuccess = false;
    }
    FISCCDemographicsProvider.partyObjInternationalPhnLst = new List<Id>();
    return isSuccess;
  }

  public static List<FISCCDepositOriginationRequestBaseDTO> generateDemoGraphicsReq(List<tffa__Party__c> partyObjLst) {
    tffa.Logger.debug('In FISCCDemographicsProvider.generateDemoGraphicsReq');
    List<FISCCDepositOriginationRequestBaseDTO> lstFISCCDepositOriginationRequestBaseDTO = new List<FISCCDepositOriginationRequestBaseDTO>();
    FISCCDepositOriginationRequestBaseDTO objFISCCDepositOriginationRequestBaseDTO;
    FISCCDepositOriginationRequest objFISCCDepositOriginationRequest = new FISCCDepositOriginationRequest();

    for (tffa__Party__c partyObj : partyObjLst) {
      if (
        !partyObj.CZIntPhnNbrCreated__c &&
        String.isNotBlank(partyObj.CZInternationalPhoneNumber__c) &&
        partyObj.tffa__Type__c == FISCCIntegrationConstants.INDIVIDUAL &&
        String.isNotBlank(partyObj.Customer_Number__c)
      ) {
        objFISCCDepositOriginationRequestBaseDTO = FISCCCustomerIndDemoExtension.generateCustomerIndDemoRequest(partyObj);
        FISCCDemographicsProvider.partyObjInternationalPhnLst.add(partyObj.Id);
        lstFISCCDepositOriginationRequestBaseDTO.add(objFISCCDepositOriginationRequestBaseDTO);
      }
    }
    return lstFISCCDepositOriginationRequestBaseDTO;
  }

  public static boolean parseDemogrphicsResp(Object response) {
    if (response == null || !(response instanceof FISCCDepositOriginationEntityResponse)) {
      return false;
    }
    for (tffa__Party__c partyObj : FISCCIntegrationLogService.partyObjMap.values()) {
      if (FISCCDemographicsProvider.partyObjInternationalPhnLst.contains(partyObj.Id)) {
        partyObj.CZIntPhnNbrCreated__c = true;
      }
    }
    return true;
  }
}