objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Beneficiary__c.object
<CustomObject>
    <description>A beneficiary typically refers to someone who is eligible to receive distributions from deposits upon death of primary owner of account. Beneficiary capture typically happens for Certificate Deposits.
Designating a beneficiary not only ensures the CD will not have to go through probate when the applicant dies.</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Beneficiaries</relationshipLabel>
        <relationshipName>Beneficiaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Beneficiary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Beneficiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CZWTFCHSAProvider.cls
public inherited sharing class CZWTFCHSAProvider {
  
  public static void addHSABeneficiary( List<tffa__Beneficiary__c> beneficiaryList, tffa__Application__c applicationObj) {
    try {
      FISCCIntegrationLogService.setCurrentLog(FISCCIntegrationConstants.HSA_ENQUIRY);
      FISCCIntegrationLogService.setCurrentLogItem(FISCCIntegrationConstants.HSA_NEW_BENEFICIARY, applicationObj.Id, true);
      FISCC_Adapter_Configs__mdt adapterConfig = FISCCIntegrationLogRepository.findAdapterConfig('NewHSABeneficiary');
      CZHSAAddBeneficiaryExtension.invokeApiCall(adapterConfig, FISCCIntegrationLogService.charterConfig, beneficiaryList, applicationObj);
    } catch (Exception ex) {
      tffa.logger.error('Exception in  CZWTFCHSAProvider ' + ex.getMessage() + ' ' + ex.getStackTraceString());
    }
  }
}