objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__KYCDecisionOutcome__c</fullName>
        <description>Outcome of a KYC decisioning process.</description>
        <label>KYC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationDecisionOutcome</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__ProductCode__c</fullName>
        <description>Unique product code maintained in the system</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Financial Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product code identifier.</description>
        <label>Financial Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR (4 AND 5))</booleanFilter>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>$Source.tffa__ProductCategory__c</field>
                <operation>equals</operation>
                <valueField>tffa__Product__c.tffa__Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value>In Progress</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <defaultValue>&quot;Init&quot;</defaultValue>
        <description>The stage of the application in context of the product applied. This will be different for each product and is more granular than the status field.This field will be updated on the state transition the application in the origination workflow.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the application</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__KYCDecisionOutcome__c</fullName>
        <description>A rollup of DecisionOutcome(s) of associated Application(s). Typically set to the worst among the Application(s).</description>
        <label>KYC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationDecisionOutcome</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <defaultValue>&quot;Init&quot;</defaultValue>
        <description>The current state/step of the Submission</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the submission</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__ApplicationDecisionOutcome.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>APPROVED</fullName>
        <label>✅Approved</label>
    </customValue>
    <customValue>
        <fullName>DECLINED</fullName>
        <label>❌Declined</label>
    </customValue>
    <customValue>
        <fullName>REVIEW</fullName>
        <label>⚠️Review</label>
    </customValue>
    <customValue>
        <fullName>COUNTER_OFFER</fullName>
        <label>🔶Counter offer</label>
    </customValue>
    <description>Possible outcomes of an Application decisioning process. Each outcome has a different effect on the Application process. e.g. DECLINED may result in termination of further processing, REVIEW may result in manual intervention for further processing</description>
    <masterLabel>ApplicationDecisionOutcome</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>ABANDONED</fullName>
        <label>Abandoned</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>SAVED</fullName>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>SUBMITTED</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>Indicates current status of the submission.This will be computed and be useful for regulations.</description>
    <masterLabel>SubmissionStatus</masterLabel>
</GlobalValueSet>

classes/CZAccNbrGenerationTest.cls
@isTest
public with sharing class CZAccNbrGenerationTest {
  @isTest
  public static void GenerateAccNbr() {
    tffa__Submission__c sub = new tffa__Submission__c(tffa__Status__c = 'SUBMITTED', tffa__State__c = 'ReviewSubmit');
    insert sub;

    List<tffa__Application__c> applicationobjs = new List<tffa__Application__c>();
    tffa__Product__c product1 = CZWTFCTestDataRepository.createCheckingProduct();
    tffa__Application__c application = CZWTFCTestDataRepository.createCheckingApplication();
    application.tffa__Product__c = product1.id;
    application.tffa__Submission__c = sub.id;
    application.tffa__ProductCode__c = '20234';

    insert application;

    applicationobjs.add(application);

    FISCCIntegrationLogService.auth = '1234';
    Map<String, String> mp = new Map<String, String>();
    mp.put('submission', sub.Id);
    mp.put('applicationName', 'TAC');
    mp.put('branch', '5');
    mp.put('productCode', '803');
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new CZAccNbrGenerationMockClass());
    CZAccNbrGenerationProvider.generateAccountNbr(applicationobjs);

    try {
      CZAccNbrGenerationMockClass accMockCls = new CZAccNbrGenerationMockClass();
      accMockCls.respond(new HttpRequest());
    } catch (Exception ex) {
      tffa.Logger.debug('Test Execption thrown');
    }

    //test excpetion block in provider
    try {
      CZAccNbrGenerationProvider.testException = true;
      Object resp = CZAccNbrGenerationProvider.generateAccountNbr(applicationobjs);
      System.assertNotEquals(resp, null);
    } catch (Exception ex) {
      tffa.Logger.debug('Test Execption thrown');
    }
    //test excpetion block in extension invoke api
    try {
      CZAccNbrGenerationExtension.testException = true;
      Object resp = CZAccNbrGenerationExtension.invokeApiCall(
        new FISCC_Adapter_Configs__mdt(),
        new FISCC_Charter_Config__mdt(),
        applicationobjs
      );
      System.assertNotEquals(resp, null);
    } catch (Exception ex) {
      tffa.Logger.debug('Test Execption thrown');
    }
    //test excpetion block in extension generate request
    try {
      CZAccNbrGenerationExtension.testException = true;
      Object resp = CZAccNbrGenerationExtension.generateRequest(applicationobjs);
      System.assertNotEquals(resp, null);
    } catch (Exception ex) {
      tffa.Logger.debug('Test Execption thrown');
    }

    Test.stopTest();
  }

  @isTest
  public static void accNbrgeneRespBuilderTestCase() {
    tffa__Submission__c sub = new tffa__Submission__c(tffa__Status__c = 'SUBMITTED', tffa__State__c = 'ReviewSubmit');
    insert sub;

    List<tffa__Application__c> applicationobjs = new List<tffa__Application__c>();
    tffa__Product__c product1 = CZWTFCTestDataRepository.createCheckingProduct();
    tffa__Application__c application = CZWTFCTestDataRepository.createCheckingApplication();
    application.tffa__Product__c = product1.id;
    application.tffa__Submission__c = sub.id;
    application.tffa__KYCDecisionOutcome__c = 'APPROVED';
    application.tffa__ProductCode__c = '20234';

    insert application;

    applicationobjs.add(application);
    Test.startTest();
    //success flow
    try {
      String resp = '{"Entity":{"account_number":{"DPAcctTyp":803,"GenDPAcctNbr":72024674,"GenDPApplID":"DP","DPAcctBrnch":5}},"Metadata":{"MsgLst":[{"Type":"Informational Message","Text":"Success","Severity":"Info","Code":"0"}]}}';
      CZAccNbrGenerationResponseDTO dto = (CZAccNbrGenerationResponseDTO) System.JSON.deserialize(
        resp,
        CZAccNbrGenerationResponseDTO.class
      );
      CZAccNbrGenResponseBuilder respBuilder = new CZAccNbrGenResponseBuilder();
      respBuilder.build(resp, new FISCC_Adapter_Configs__mdt(), new FISCC_Charter_Config__mdt());
      respBuilder.parseResponse(dto, new FISCC_Adapter_Configs__mdt(), new FISCC_Charter_Config__mdt());
      Object resp1 = CZAccNbrGenerationExtension.parseResponse(dto, applicationobjs);
      System.assertNotEquals(resp1, null);
    } catch (Exception ex) {
      tffa.Logger.debug('Test Execption thrown');
    }

    //Exception block in CZAccNbrGenerationRequestDTO.build
    try {
      String resp = '{"Entity":{"account_number":{"DPAcctTyp":803,"GenDPAcctNbr":72024674,"GenDPApplID":"DP","DPAcctBrnch":5}},"Metadata":{"MsgLst":[{"Type":"Informational Message","Text":"Success","Severity":"Info","Code":"0"}]}}';
      CZAccNbrGenerationResponseDTO dto = (CZAccNbrGenerationResponseDTO) System.JSON.deserialize(
        resp,
        CZAccNbrGenerationResponseDTO.class
      );
      CZAccNbrGenResponseBuilder respBuilder = new CZAccNbrGenResponseBuilder();
      CZAccNbrGenResponseBuilder.testException = true;
      respBuilder.build(resp, new FISCC_Adapter_Configs__mdt(), new FISCC_Charter_Config__mdt());
    } catch (Exception ex) {
      System.assertNotEquals(ex.getMessage(), null);
    }

    //Exception block in CZAccNbrGenResponseBuilder.parseResponse
    try {
      String resp = '{"Entity":{"account_number":{"DPAcctTyp":803,"GenDPAcctNbr":72024674,"GenDPApplID":"DP","DPAcctBrnch":5}},"Metadata":{"MsgLst":[{"Type":"Informational Message","Text":"Success","Severity":"Info","Code":"0"}]}}';
      CZAccNbrGenerationResponseDTO dto = (CZAccNbrGenerationResponseDTO) System.JSON.deserialize(
        resp,
        CZAccNbrGenerationResponseDTO.class
      );
      CZAccNbrGenResponseBuilder respBuilder = new CZAccNbrGenResponseBuilder();
      CZAccNbrGenResponseBuilder.testException = true;
      respBuilder.parseResponse(new CZAccNbrGenerationResponseDTO(), new FISCC_Adapter_Configs__mdt(), new FISCC_Charter_Config__mdt());
    } catch (Exception ex) {
      System.assertNotEquals(ex.getMessage(), null);
    }
    // System.assertEquals('1', '1', 'Success');
    Test.stopTest();
  }
}