objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/tffa__ApplicantRole__c.object
<CustomObject>
    <description>Defines possible roles played by a Party (or Applicant) on an Application. e.g. SOLE_OWNER, JOINT_OWNER, AUTHORIZED_SIGNATORY etc. These roles finally translate to roles on opened accounts. Each role has specific characteristics, that can influence the relationship. e.g.parties with SOLE_OWNER, JOINT_OWNER roles become owners of the account, whereas ones with AGENT, GUARANTOR roles do not. Roles may be categorized based on this nature of relationship. Roles may also have applicable authority list. These control what actions are permitted on the account.</description>
    <fields>
        <fullName>tffa__Category__c</fullName>
        <description>Defines the nature of the role.</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicantRoleCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>A unique identifier for the role. Usually corresponds to role maintained in core system.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Applicant Role</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicant Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The final generated account number. This will be set only after the final account number is available as part of the response of an account open API call.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__DepositBoxAccountNumber__c</fullName>
        <description>Box Number of the safe deposit box. Include 3 pieces of information, the branch number, region code and box number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Deposit box account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this application should be considered as primary in the submission. Such applications cannot be removed from the submission. Used in bundle applications, where one application is marked as primary.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__ProductCategory__c</fullName>
        <description>Different product category supported by system. This classifies the flow of account opening , the underlying data model and the servicing components about an account.</description>
        <label>Product Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ProductCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product code identifier.</description>
        <label>Financial Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR (4 AND 5))</booleanFilter>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>$Source.tffa__ProductCategory__c</field>
                <operation>equals</operation>
                <valueField>tffa__Product__c.tffa__Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value>In Progress</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ApplicationPartyXref__c.object
<CustomObject>
    <description>Each Applicant of the submission can play different roles in the application and the eventual account.</description>
    <fields>
        <fullName>CZFISRelationshipCode__c</fullName>
        <description>FIS Relationship Code</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Relationship Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ApplicantRole__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The role played by the party in the application. Finally translates to role on opened account.</description>
        <label>Role</label>
        <referenceTo>tffa__ApplicantRole__c</referenceTo>
        <relationshipLabel>Application Parties</relationshipLabel>
        <relationshipName>ApplicationPartyXrefs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current applicant is primary applicant of the application.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Beneficiary__c.object
<CustomObject>
    <description>A beneficiary typically refers to someone who is eligible to receive distributions from deposits upon death of primary owner of account. Beneficiary capture typically happens for Certificate Deposits.
Designating a beneficiary not only ensures the CD will not have to go through probate when the applicant dies.</description>
    <fields>
        <fullName>CZFisRelnshipCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to check if FIS Relnship is created</description>
        <label>FIS Relnship Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Beneficiaries</relationshipLabel>
        <relationshipName>Beneficiaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Beneficiary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Beneficiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyPartyXref__c.object
<CustomObject>
    <description>A relationship between 2 applicants of a submission. 
Personal relationship could be SPOUSE, PARENT, FRIENDS.
Business relationship between a company and an individual could be DIRECTOR, OWNER, EXECUTIVE, PARTNER etc. In additional the ownership percentage can be captured for OWNER type of relationship. 
Relationship between 2 company type applicants can also be captured such as PARENT and SUBSIDIARY.</description>
    <fields>
        <fullName>CZFisRelnshipCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to check if FIS Relnship is created</description>
        <label>FIS Relnship Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Party managing the relationship</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Related To</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Party Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Party Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <fields>
        <fullName>IsCustodianProduct__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Custodian Product?</description>
        <label>Custodian Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Category__c</fullName>
        <description>Broad classification of the product</description>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ProductCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique identifier for the product</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__SubmissionPartyXref__c.object
<CustomObject>
    <description>An individual or a legal entity which is applying for certain services/products in the bank. An applicant exists only in the context of a submission.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to Party object @managed</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current applicant is primary applicant of the application.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission object.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submission Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/tffa__ApplicantRoleCategory.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>OWNER</fullName>
        <label>Owner</label>
    </customValue>
    <customValue>
        <fullName>SIGNER</fullName>
        <label>Signer</label>
    </customValue>
    <customValue>
        <fullName>OTHER</fullName>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>AGENT</fullName>
        <label>Agent</label>
    </customValue>
    <description>Broad  classification of applicant roles. Roles belonging to same category have similar nature. e.g. OWNER may mean ownership type of roles like Sole Owner, Joint Owner.</description>
    <masterLabel>ApplicantRoleCategory</masterLabel>
</GlobalValueSet>

classes/FISCCCustAccRelnExtension.cls
public with sharing class FISCCCustAccRelnExtension {
  public static boolean invokeCustAccRelnAPI(List<tffa__Party__c> partyObjs, tffa__Application__c tfApp, tffa__Submission__c subObj) {
    tffa.logger.debug('In invokeCustAccRelnAPI');
    boolean isRelnCreationSuccess = false;
    Object result;
    try {
      do {
        FISCCDepositOriginationExtension.relnAdded.clear();
        FISCCIntegrationLogService.setCurrentLogItem(FISCCIntegrationConstants.CUSTOMER_ACCOUNT_RELATIONSHIP, tfApp.Name, true);
        FISCCRequestBaseDTO fisccRequestBaseDTO;
        FISCC_Adapter_Configs__mdt adapterConfig = FISCCIntegrationLogRepository.findAdapterConfig(
          FISCCIntegrationConstants.CUST_RELN_ADAPTERCONFIG
        );
        fisccRequestBaseDTO = generateCustAccRelnReq(tfApp);
        tffa.Logger.debug('invokeCustAccRelnAPI fisccRequestBaseDTO' + fisccRequestBaseDTO);
        result = FISCCHostAdapter.processHostRequest(fisccRequestBaseDTO, adapterConfig, FISCCIntegrationLogService.charterConfig);
        tffa.Logger.debug('invokeCustAccRelnAPI result' + result);
        if (parseCustAcctRelnResponse(result, tfApp)) {
          FISCCIntegrationLogService.setLogItemOk(FISCCIntegrationConstants.CUSTOMER_ACCOUNT_RELATIONSHIP);
          isRelnCreationSuccess = true;
        } else {
          FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.CUSTOMER_ACCOUNT_RELATIONSHIP);
          isRelnCreationSuccess = false;
          break;
        }
      } while (!CZWTFCCommonHelper.checkCustomerAccRelnCompleted(tfApp));
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in invokeCustAccRelnAPI ' + ex.getMessage() + ' Exception :::' + ex.getStackTraceString());
      isRelnCreationSuccess = false;
    }
    return isRelnCreationSuccess;
  }

  /**
   *
   */
  public static FISCCRequestBaseDTO generateCustAccRelnReq(tffa__Application__c appObj) {
    tffa.Logger.debug('In generateCustAccRelnReq');
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    FISCCCustAccRelnRequestDTO relnReq = new FISCCCustAccRelnRequestDTO();
    tffa__Product__c prod = appObj.tffa__Product__r;
    Integer applicantRelnCounter = 0;
    try {
      relnReq.caMaintainAcc.ApCd1 = FISCCIntegrationConstants.GenDPApplID;
      relnReq.caMaintainAcc.ApNbr1 = appObj.tffa__AccountNumber__c;
      for (tffa__ApplicationPartyXref__c appParty : appObj.tffa__PartyXrefs__r) {
        if (applicantRelnCounter < FISCCIntegrationConstants.CUSTOMER_RELN_LIMIT && !appParty.CZFisRelnshipCreated__c && !FISCCIntegrationConstants.DEPUTY.equalsIgnoreCase(appParty.tffa__ApplicantRole__r.tffa__Code__c)) {
          FISCCDepositOriginationExtension.relnAdded.add(appParty.Id);
          tffa__Party__c partyObject = FISCCIntegrationLogService.partyObjMap.get(appParty.tffa__party__c);
          FISCCCustAccRelnRequestDTO.CustomerAccountRelnList customerDetail = new FISCCCustAccRelnRequestDTO.CustomerAccountRelnList();
          customerDetail.AcNbr2 = partyObject.Customer_Number__c;
          customerDetail.E2ToE1RlCd = appParty.tffa__Primary__c
            ? FISCCIntegrationConstants.CUST_ACC_PRIMARY_RELN
            : FISCCIntegrationConstants.CUST_ACC_SECONDARY_RELN;
          if (appParty.tffa__ApplicantRole__r != null && appParty.tffa__ApplicantRole__r.CZFISRelationshipCode__c != null) {
            customerDetail.E1ToE2RlCd = appParty.tffa__ApplicantRole__r.CZFISRelationshipCode__c;
          } else {
            if (prod.IsCustodianProduct__c) {
              customerDetail.E1ToE2RlCd = FISCCIntegrationConstants.CustodianProduct_JointRelation;
            } else {
              customerDetail.E1ToE2RlCd = FISCCIntegrationConstants.JOINT_RELATION;
            }
          }
          relnReq.caAccRelnList.add(customerDetail);
          applicantRelnCounter++;
        }
      }

      if(appObj.tffa__ProductCategory__c != null && FISCCIntegrationConstants.SAFE_DEPOSIT_PROD_CATEGORY.contains(appObj.tffa__ProductCategory__c) && appObj.tffa__DepositBoxAccountNumber__c != null){
        relnReq.caMaintainAcc.ApCd1 = FISCCIntegrationConstants.GenSDBApplID;
        relnReq.caMaintainAcc.ApNbr1 = appObj.tffa__DepositBoxAccountNumber__c;
      }

      if (
        applicantRelnCounter < FISCCIntegrationConstants.CUSTOMER_RELN_LIMIT &&
        appObj.tffa__Beneficiaries__r != null &&
        !appObj.tffa__Beneficiaries__r.isEmpty() &&
        !FISCCIntegrationConstants.IRA_PRODUCT_CATEGORY.equalsIgnoreCase(prod.tffa__Category__c) &&
        !FISCCIntegrationConstants.HSA_PRODUCT_CATEGORY.equalsIgnoreCase(prod.tffa__Category__c)
      ) {
        for (tffa__Beneficiary__c benefObj : appObj.tffa__Beneficiaries__r) {
          if (applicantRelnCounter < FISCCIntegrationConstants.CUSTOMER_RELN_LIMIT && !benefObj.CZFisRelnshipCreated__c) {
            FISCCDepositOriginationExtension.relnAdded.add(benefObj.Id);
            FISCCCustAccRelnRequestDTO.CustomerAccountRelnList customerDetail = new FISCCCustAccRelnRequestDTO.CustomerAccountRelnList();
            customerDetail.AcNbr2 = benefObj.Customer_Number__c;
            customerDetail.E1ToE2RlCd = FISCCIntegrationConstants.BENEF_RELN_CODE;
            customerDetail.E2ToE1RlCd = FISCCIntegrationConstants.CUST_ACC_SECONDARY_RELN;
            relnReq.caAccRelnList.add(customerDetail);
            applicantRelnCounter++;
          }
        }
      }
      fisccRequestBaseDTO = relnReq;
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in generateCustAccRelnReq ' + ex.getMessage() + ' Exception :::' + ex.getStackTraceString());
    }
    return fisccRequestBaseDTO;
  }

  /**
   * Parse Response
   */
  public static boolean parseCustAcctRelnResponse(Object response, tffa__Application__c appObj) {
    try {
      if (response instanceof FISCCCustAccRelnResponseDTO) {
        FISCCCustAccRelnResponseDTO custAcctResp = (FISCCCustAccRelnResponseDTO) response;
        tffa.Logger.debug('parseCustAcctRelnResponse--> ' + custAcctResp);
        for (tffa__ApplicationPartyXref__c appPartyObj : appObj.tffa__PartyXrefs__r) {
          if (FISCCDepositOriginationExtension.relnAdded.contains(appPartyObj.Id)) {
            appPartyObj.CZFisRelnshipCreated__c = true;
          }
        }

        for (tffa__Beneficiary__c benefObj : appObj.tffa__Beneficiaries__r) {
          if (FISCCDepositOriginationExtension.relnAdded.contains(benefObj.Id)) {
            benefObj.CZFisRelnshipCreated__c = true;
          }
        }
        return true;
      } else {
        return false;
      }
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in parseCustAcctRelnResponse ' + ex.getMessage() + ' Exception :::' + ex.getStackTraceString());
      return false;
    }
  }
}