objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <fields>
        <fullName>tffa__RoutingNumber__c</fullName>
        <description>Routing number of the branch. An identification number assigned to the banking institution.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Routing number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__BrandCode__c</fullName>
        <description>Brand code of the submission this party is associated with</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>The last name of the individual represented by the parent object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__NationalIdentifierValue__c</fullName>
        <description>The value of the taxpayer identifier as assigned by the IRS to the individual or legal entity.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>National identifier value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryEmail__c</fullName>
        <description>Primary email of the party.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

classes/FISCCCEBEnrollmentExtension.cls
public inherited sharing class FISCCCEBEnrollmentExtension {
  // request DTO object
  public static FISCCCEBEnrollmentRequestDTO objFISCCCEBEnrollmentRequestDTO = new FISCCCEBEnrollmentRequestDTO();
  @TestVisible
  private static boolean testException = false;
  public static Object invokeCEBEnroll(
    Map<String, Object> params,
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    Object result = null;
    boolean isCEBEnrollSuccess = null;

    try {
      if (Test.isRunningTest() && testException) {
        throw new tffa.ApplicationException('Called through test class');
      }
      if (params != null && !params.isEmpty()) {
        fisccRequestBaseDTO = generateCEBEnrollRequest(params, adapterConfig, charterConfig);
        tffa.Logger.debug('generateCEBEnrollRequest is called');
      } else {
        tffa.Logger.debug('generateCEBEnrollRequest is called with null params****');
      }

      //TODO result handling
      //tffa.logger.debug('generateCEBEnrollRequest req :: ' + fisccRequestBaseDTO);
      result = FISCCHostAdapter.processHostRequest(fisccRequestBaseDTO, adapterConfig, charterConfig);
      tffa.Logger.debug('result in invokeCEBEnroll ==>' + result);
      tffa.Logger.debug('HostAdapter is called');

      return result;
    } catch (Exception ex) {
      tffa.Logger.error('Exception in invokeCEBEnroll : ' + ex.getMessage() + ' Exception:::' + ex.getStackTraceString());
      return null;
    }
  }

  // creates request object for CEB Enroll call
  public static FISCCRequestBaseDTO generateCEBEnrollRequest(
    Map<String, Object> params,
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    tffa.Logger.debug('Inside generateCEBEnrollRequest method');
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    tffa__Party__c partyObj = (tffa__Party__c) params.get('partyObj');
    tffa.logger.debug('partyObj in generateCEBEnrollRequest ==>' + partyObj);

    try {
      if (Test.isRunningTest() && testException) {
        throw new tffa.ApplicationException('Called through test class');
      }
      if (partyObj != null) {
        tffa.Logger.debug('inside party not null ');
        // setting userInfo
        objFISCCCEBEnrollmentRequestDTO.enrollment.userInfo.userType = 'Individual'; //partyObj.tffa__Type__c;
        objFISCCCEBEnrollmentRequestDTO.enrollment.userInfo.lastName = partyObj.tffa__LastName__c;
        objFISCCCEBEnrollmentRequestDTO.enrollment.userInfo.emailType = 'Primary';
        objFISCCCEBEnrollmentRequestDTO.enrollment.userInfo.emailAddress = partyObj.tffa__PrimaryEmail__c;
        objFISCCCEBEnrollmentRequestDTO.enrollment.userInfo.taxId = partyObj.tffa__NationalIdentifierValue__c;
        objFISCCCEBEnrollmentRequestDTO.enrollment.userInfo.ipId = partyObj.Customer_Number__c;
        objFISCCCEBEnrollmentRequestDTO.enrollment.userInfo.userId = (String) params.get('userName');
        objFISCCCEBEnrollmentRequestDTO.enrollment.userInfo.password = (String) params.get('password');

        objFISCCCEBEnrollmentRequestDTO.enrollment.bankInfo.feId = partyObj.tffa__BrandCode__c;
        // fetching brand to get aba number
        tffa__Brand__c brandObj = CZWTFCBrandRepository.fetchBrandByCode(partyObj.tffa__BrandCode__c);
        objFISCCCEBEnrollmentRequestDTO.enrollment.bankInfo.abaNumber = brandObj.tffa__RoutingNumber__c;
      }
    } catch (Exception ex) {
      tffa.Logger.error(' Exception into generateCEBEnrollRequest :::' + ex.getMessage() + ' Exception:::' + ex.getStackTraceString());
      return null;
    }
    //tffa.Logger.debug('generated objFISCCCEBEnrollmentRequestDTO : ==>' + objFISCCCEBEnrollmentRequestDTO);
    fisccRequestBaseDTO = objFISCCCEBEnrollmentRequestDTO;
    return fisccRequestBaseDTO;
  }
}