objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__InvestmentPlanNumber__c</fullName>
        <description>The plan number which is generated as per Instituition strategy</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Investment Plan Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Beneficiary__c.object
<CustomObject>
    <description>A beneficiary typically refers to someone who is eligible to receive distributions from deposits upon death of primary owner of account. Beneficiary capture typically happens for Certificate Deposits.
Designating a beneficiary not only ensures the CD will not have to go through probate when the applicant dies.</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Beneficiaries</relationshipLabel>
        <relationshipName>Beneficiaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__BirthDate__c</fullName>
        <description>Date of birth</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Birth date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>tffa__FirstName__c</fullName>
        <description>First name of beneficiary</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>Last name of beneficiary</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LegalName__c</fullName>
        <description>The legal name of a business is the official name of the person or entity that owns a business.For limited partnerships, LLCs, and corporations, the legal name of the business is the name registered with the state filing office</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Legal name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__MiddleName__c</fullName>
        <description>The middle name of the beneficiary.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__NationalIdentifierType__c</fullName>
        <description>Classifies identification numbers used by the Internal Revenue Service (IRS) in the administration of tax laws.</description>
        <label>National identifier type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__NationalIdentifierType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__NationalIdentifierValue__c</fullName>
        <description>The value of the taxpayer identifier as assigned by the IRS to the individual or legal entity.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>National identifier value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PartyType__c</fullName>
        <defaultValue>&quot;INDIVIDUAL&quot;</defaultValue>
        <description>Party type of associated beneficiary</description>
        <label>Party type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__PrimaryPhone__c</fullName>
        <description>Primary phone number of the beneficiary</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>tffa__RelationCodeName__c</fullName>
        <description>Name of the relation code.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Relation code name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__SharePercentage__c</fullName>
        <description>Percentage of share</description>
        <label>Share percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tffa__Suffix__c</fullName>
        <description>The name suffix of the beneficiary. (E.g., JR = Junior, SR = Senior, etc.)</description>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Suffix</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - PRIMARY, CONTINGENT</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__BeneficiaryType</valueSetName>
        </valueSet>
    </fields>
    <label>Beneficiary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Beneficiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/tffa__BeneficiaryType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PRIMARY</fullName>
        <default>true</default>
        <label>Primary</label>
    </customValue>
    <customValue>
        <fullName>CONTINGENT</fullName>
        <label>Contingent</label>
    </customValue>
    <description>Type of the Beneficiary</description>
    <masterLabel>BeneficiaryType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__NationalIdentifierType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>SSN</fullName>
    </customValue>
    <customValue>
        <fullName>TIN</fullName>
    </customValue>
    <description>Classifies identification numbers used by the Internal Revenue Service IRS.</description>
    <masterLabel>NationalIdentifierType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__Suffix.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Jr</fullName>
    </customValue>
    <customValue>
        <fullName>Sr</fullName>
        <label>Sr.</label>
    </customValue>
    <customValue>
        <fullName>II</fullName>
    </customValue>
    <customValue>
        <fullName>III</fullName>
    </customValue>
    <customValue>
        <fullName>IV</fullName>
    </customValue>
    <customValue>
        <fullName>246</fullName>
        <isActive>false</isActive>
        <label>246</label>
    </customValue>
    <customValue>
        <fullName>Esq</fullName>
        <isActive>false</isActive>
        <label>Esq</label>
    </customValue>
    <customValue>
        <fullName>VI</fullName>
        <isActive>false</isActive>
        <label>VI</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <isActive>false</isActive>
        <label>V</label>
    </customValue>
    <customValue>
        <fullName>2nd</fullName>
        <isActive>false</isActive>
        <label>2nd</label>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
        <isActive>false</isActive>
        <label>Test</label>
    </customValue>
    <description>The name suffix of the individual represented by the parent object. (E.g., JR = Junior, SR = Senior, etc.)</description>
    <masterLabel>Suffix</masterLabel>
</GlobalValueSet>

classes/CZIRAAddBeneficiaryExtension.cls
public with sharing class CZIRAAddBeneficiaryExtension {

  public static Boolean invokeApiCall(
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig,
    List<tffa__Beneficiary__c> beneficiaryList,
    tffa__Application__c applicationObj
  ) {
    CZIRAAddBeneficiaryResponseDTO response;

    try {
      FISCCRequestBaseDTO fisccRequestBaseDTO = createBeneficiaryRequest(beneficiaryList, applicationObj);
      Object result = FISCCHostAdapter.processHostRequest(fisccRequestBaseDTO, adapterConfig, charterConfig);

      response = isFISCCAPICallSuccess(result); 

      if(response != null){
        FISCCIntegrationLogService.setLogItemOk(FISCCIntegrationConstants.IRA_NEW_BENEFICIARY);
        return true;
      } else {
        FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.IRA_NEW_BENEFICIARY);
        return false;
      }
      
    } catch (Exception ex) {
      tffa.Logger.debug(
        'Exception in CZIRAAddBeneficiaryExtension.invokeApiCall ' +
        ex.getMessage() +
        ' Exception :::' +
        ex.getStackTraceString()
      );
      FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.IRA_NEW_BENEFICIARY);
      return false;
    }
  }

  public static FISCCRequestBaseDTO createBeneficiaryRequest(
    List<tffa__Beneficiary__c> beneficiaryList,
    tffa__Application__c applicationObj
  ) {
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    CZIRAAddBeneficiaryReqDTO request = new CZIRAAddBeneficiaryReqDTO();
    
    try {

      request.planBeneficiary.PlnNbr = applicationObj.tffa__InvestmentPlanNumber__c;

      for(tffa__Beneficiary__c benef: beneficiaryList){
        CZIRAAddBeneficiaryReqDTO.PlanBeneficiariesDataLst addList = new CZIRAAddBeneficiaryReqDTO.PlanBeneficiariesDataLst();

        if(benef.tffa__PartyType__c == FISCCIntegrationConstants.ORGANIZATION){
          addList.Nme = CZWTFCCommonHelper.trimString(benef.tffa__LegalName__c, FISCCIntegrationConstants.FULL_NAME_LENGTH);
        } else {
          addList.Nme = CZWTFCCommonHelper.getFormattedFullName(
          benef.tffa__FirstName__c,
          benef.tffa__MiddleName__c,
          benef.tffa__LastName__c,
          benef.tffa__Suffix__c,
          FISCCIntegrationConstants.FULL_NAME_LENGTH
        );
        }

        if(String.isNotBlank(benef.tffa__NationalIdentifierType__c))
          addList.TaxId = CZWTFCCommonHelper.getTaxIdType(benef.tffa__NationalIdentifierType__c);
        if(String.isNotBlank(benef.tffa__NationalIdentifierValue__c) && String.isNotBlank(addList.TaxId) && addList.TaxId != 'T')
          addList.TxpyrNbr= String.valueOf(benef.tffa__NationalIdentifierValue__c);
        if(String.isNotBlank(benef.tffa__PrimaryPhone__c)){
          addList.Phn = benef.tffa__PrimaryPhone__c.right(10);
        }

        // If NationalIdentifierType is ITIN send N to FIS
        if(String.isNotBlank(addList.TaxId) && addList.TaxId == 'T'){
          addList.TaxId = 'N';
        }   

        addList.SpseNonSpseInd = benef.tffa__RelationCodeName__c == 'SPOUSE' ? 'S' : 'N';
        addList.PrmyCntgInd = benef.tffa__Type__c == 'PRIMARY' ? 'P' : 'C';
        addList.Perc = String.valueOf(benef.tffa__SharePercentage__c);

        if(benef.tffa__BirthDate__c != null){
          Datetime birthDate = Datetime.newInstance(benef.tffa__BirthDate__c, Time.newInstance(0,0,0,0));
          addList.Birthdate = birthDate.format('yyyy-MM-dd');
        }

        request.planBeneficiariesDataLst.add(addList);
      }

      fisccRequestBaseDTO = request;

      tffa.Logger.debug('fisccRequestBaseDTO::'+ fisccRequestBaseDTO);

      return fisccRequestBaseDTO;
    } catch (Exception ex) {
      tffa.Logger.error(
        'Exception in CZIRAAddBeneficiaryExtension createBeneficiaryRequest : ' +
        ex.getMessage() +
        ex.getLineNumber() +
        ex.getStackTraceString()
      );
    }
    return fisccRequestBaseDTO;
  }

  public static CZIRAAddBeneficiaryResponseDTO isFISCCAPICallSuccess(Object response) {
    CZIRAAddBeneficiaryResponseDTO objCZIRAAddBeneficiaryResponseDTO;
    if (response instanceof CZIRAAddBeneficiaryResponseDTO) {
      objCZIRAAddBeneficiaryResponseDTO = (CZIRAAddBeneficiaryResponseDTO) response;
    }
    
    return objCZIRAAddBeneficiaryResponseDTO;
  }
}