objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>CostCenter__c</fullName>
        <description>Cost center for location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Cost center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>Fis branch code for Location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Branch Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Brand__c</fullName>
        <description>Brand code of the Brand for the submission if applicable</description>
        <formula>tffa__Submission__r.tffa__Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product code identifier.</description>
        <label>Financial Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR (4 AND 5))</booleanFilter>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>$Source.tffa__ProductCategory__c</field>
                <operation>equals</operation>
                <valueField>tffa__Product__c.tffa__Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value>In Progress</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__PromotionCode__c</fullName>
        <description>A promotion code which was part of a marketing campaign.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Promotion code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <fields>
        <fullName>CIPrmyOffcrNbr__c</fullName>
        <description>CI Prmy Offcr Nbr</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Officer Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>Unique code for the brand</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>CostCenter__c</fullName>
        <description>Cost center for location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Cost center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>Fis branch code for Location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Branch Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsExceptionPlanRequired__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is Exception Plan Required</description>
        <inlineHelpText>Exception plan is not required to be set for new accounts for existing customers who have transactional accounts older than 30 days.</inlineHelpText>
        <label>ExceptionPlan Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__BirthDate__c</fullName>
        <description>The date of birth of the individual</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Birth date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>tffa__FirstName__c</fullName>
        <description>The first name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>The last name of the individual represented by the parent object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__MiddleName__c</fullName>
        <description>The middle name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__NationalIdentifierValue__c</fullName>
        <description>The value of the taxpayer identifier as assigned by the IRS to the individual or legal entity.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>National identifier value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <fields>
        <fullName>IsMoneyMarketProduct__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is it a Money Market Product?</description>
        <label>IsMoneyMarketProduct</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Category__c</fullName>
        <description>Broad classification of the product</description>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ProductCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique identifier for the product</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FISCCDOCreateNewDepositAccExtension.cls
public with sharing class FISCCDOCreateNewDepositAccExtension {
  public static FISCCCreateNewDepositAccDTO createNewDepositAccountRequest(
    List<tffa__Party__c> partyObjs,
    List<tffa__Application__c> appObjs,
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    FISCCDepositOriginationRequestBaseDTO fisccDepositOriginationRequestBaseDTO = null;
    FISCCDOCreateNewDepositAccRequest objFISCCDOCreateNewDepositAccountRequest = new FISCCDOCreateNewDepositAccRequest();

    FISCCCreateNewDepositAccDTO fisccCreateNewDepositAccountDTO = new FISCCCreateNewDepositAccDTO();

    try {
      tffa.Logger.debug('Inside newDepositAccountRequest method');
      tffa__Party__c partyObj = CZWTFCCommonHelper.getPrimaryParty(FISCCIntegrationLogService.submissionObj, partyObjs);
      tffa__Brand__c brandObj = FISCCIntegrationLogService.brandObj;
      //FISCCIntegrationLogService.setPartyObjs();
      fisccCreateNewDepositAccountDTO.DPAcctNbrNewAcct = FISCCIntegrationConstants.DUMMY_ACCT_NUMBER;
      fisccCreateNewDepositAccountDTO.DPBrnch = Integer.valueOf(appObjs[0].FISBranchCode__c);
      fisccCreateNewDepositAccountDTO.DPCstCntr = Integer.valueOf(appObjs[0].CostCenter__c);

      // DateTime startDate = Date.Today();
      // fisccCreateNewDepositAccountDTO.RmrkExpDte = startDate.addMonths(FISCCIntegrationConstants.REMARK_MONTHS_TO_ADD).format('yyyy-dd-MM');
      // fisccCreateNewDepositAccountDTO.RmrkLne01 = FISCCIntegrationConstants.ACCOUNT_OPENED_ONLINE;
      // fisccCreateNewDepositAccountDTO.CIRmrkMaintSrcInd = FISCCIntegrationConstants.REMARK_IDENTITY;

      if (appObjs[0].tffa__PromotionCode__c != null && (!String.isBlank(appObjs[0].tffa__PromotionCode__c))) {
        if (appObjs[0].tffa__PromotionCode__c.length() > 12) {
          fisccCreateNewDepositAccountDTO.DPTrckCde = appObjs[0].tffa__PromotionCode__c.subString(0, 12);
        } else {
          fisccCreateNewDepositAccountDTO.DPTrckCde = appObjs[0].tffa__PromotionCode__c;
        }
      }

      fisccCreateNewDepositAccountDTO.DPAcctTyp = Integer.valueOf(appObjs[0].tffa__Product__r.tffa__Code__c);
      if (String.isNotBlank(partyObj.tffa__NationalIdentifierValue__c)) {
        fisccCreateNewDepositAccountDTO.DPFedTaxId = FISCCIntegrationConstants.DPFedTaxId;
        fisccCreateNewDepositAccountDTO.DPFedTaxNbr = partyObj.tffa__NationalIdentifierValue__c;
      } else {
        fisccCreateNewDepositAccountDTO.DPFedTaxId = 'N';
      }

      fisccCreateNewDepositAccountDTO.DPFedWithholdingInd = FISCCIntegrationConstants.DPFedWithholdingInd;

      if (brandObj != null && !String.isBlank(brandObj.CIPrmyOffcrNbr__c)) {
        fisccCreateNewDepositAccountDTO.DPPrmyOffcr = Integer.valueOf(brandObj.CIPrmyOffcrNbr__c);
      }

      fisccCreateNewDepositAccountDTO.DPAcctNme = CZWTFCCommonHelper.getFormattedFullName(
        partyObj.tffa__FirstName__c,
        partyObj.tffa__MiddleName__c,
        partyObj.tffa__LastName__c,
        '',
        24
      );
      fisccCreateNewDepositAccountDTO.DPBirthdate = partyObj.tffa__BirthDate__c;
      if ('CHECKING'.equals(appObjs[0].tffa__Product__r.tffa__Category__c) || appObjs[0].tffa__Product__r.IsMoneyMarketProduct__c) {
        fisccCreateNewDepositAccountDTO.DPStatCodes = FISCCIntegrationConstants.CHECKING_STAT_CODES;
      } else {
        fisccCreateNewDepositAccountDTO.DPStatCodes = FISCCIntegrationConstants.SAVINGS_STAT_CODES;
      }

      if (FISCCIntegrationLogService.partyObjs != null) {
        for (tffa__Party__c party : FISCCIntegrationLogService.partyObjs) {
          if (party.IsExceptionPlanRequired__c) {
            fisccCreateNewDepositAccountDTO.DPFundsAEP = FISCCIntegrationConstants.NEW_ACCOUNT_EXCEPTION_PLAN_CODE;
          }
        }
      }

      if (FISCCCommonHelper.validateStandardODAddOn(appObjs[0])) {
        fisccCreateNewDepositAccountDTO.DPExcpPlnNbr = FISCCIntegrationConstants.OD_FOR_STANDARD_ADDON_EXCPPLNNBR;
      }

      tffa.logger.debug(
        'FISCCDOCreateNewDepositAccountRequestExtension : fisccDepositOriginationRequestBaseDTO ==> ' +
        fisccDepositOriginationRequestBaseDTO
      );
    } catch (Exception ex) {
      tffa.Logger.error('Exception in invokeCEBEnroll : ' + +ex.getMessage() + ' Exception:::' + ex.getStackTraceString());
      return null;
    }
    tffa.logger.debug(
      'FISCCDOCreateNewDepositAccountRequestExtension : fisccDepositOriginationRequestBaseDTO1 ==>' + fisccCreateNewDepositAccountDTO
    );
    return fisccCreateNewDepositAccountDTO;
  }
}