objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <fields>
        <fullName>ServiceURL__c</fullName>
        <description>This contains base url for API</description>
        <label>ServiceURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <fields>
        <fullName>FCMEntityId__c</fullName>
        <description>FCM Entity Id</description>
        <label>FCM Entity Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ServiceURL__c</fullName>
        <description>It contains named credential having base url only</description>
        <label>ServiceURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

classes/FCMGetEntityAuthorizationTokenProvider.cls
public inherited sharing class FCMGetEntityAuthorizationTokenProvider {
  public static String processGetAuthorizationTokenToken(FISCC_Charter_Config__mdt charterConfig) {
    String authorization = '';
    try {
      String strAPiName = 'AuthorizationToken';

      FISCC_Adapter_Configs__mdt adapterConfig = FISCCIntegrationLogRepository.findAdapterConfig(strAPiName);
      adapterConfig.ServiceURL__c = adapterConfig.ServiceURL__c.replace('{EntityID}', charterConfig.FCMEntityId__c );

      authorization = FCMGetEntityAuthorizationTokenExtension.getAuthorizationToken(adapterConfig, charterConfig);

    } catch (Exception ex) {
      tffa.logger.error('Exception in FISCCGetAccessTokenProvider ' + ex.getMessage() + ' ' + ex.getStackTraceString());
    }
    return authorization;
  }
}