objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/tffa__Address__c.object
<CustomObject>
    <description>An address is a collection of information, presented in a mostly fixed format, used to give the location of a building, apartment, or other structure or a plot of land, generally using political boundaries and street names as references,  along with other identifiers such as house or apartment numbers

 For more reference lookup https://en.wikipedia.org/wiki/Address_(geography)#United_States</description>
    <label>Address</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>CZCity__c</fullName>
        <description>The city of the address</description>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CZLine1__c</fullName>
        <description>line 1 of the address</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Line1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CZLine2__c</fullName>
        <description>line 2 of the address</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CZState__c</fullName>
        <description>A state is a geographical region of a country used for administrative or political purposes,</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CZTitle1__c</fullName>
        <description>Title 1</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Title 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CZTitle2__c</fullName>
        <description>Title 2</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Title 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CZTitle3__c</fullName>
        <description>Title 3</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Title 3</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CZZipCode__c</fullName>
        <description>Also known as post code , a series of numbers that forms part of an address, used to help organize post so that it can be delivered more quickly</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The final generated account number. This will be set only after the final account number is available as part of the response of an account open API call.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account address for purposes of statement etc. If Address Prefill Source Id is set, the address details are not persisted directly, only address id is persisted.</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product code identifier.</description>
        <label>Financial Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR (4 AND 5))</booleanFilter>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>$Source.tffa__ProductCategory__c</field>
                <operation>equals</operation>
                <valueField>tffa__Product__c.tffa__Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value>In Progress</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>CellPhoneNumber__c</fullName>
        <description>Cell phone of the party.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Cell phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreferredContactNumber__c</fullName>
        <description>Prefered contact number used as primary contact number for user communication</description>
        <label>Preferred Contact Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PhoneType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__FirstName__c</fullName>
        <description>The first name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>The last name of the individual represented by the parent object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__MiddleName__c</fullName>
        <description>The middle name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryPhone__c</fullName>
        <description>Primary phone number of the party</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Primary phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__SecondaryPhone__c</fullName>
        <description>Secondary phone of the party.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Secondary phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Suffix__c</fullName>
        <description>The name suffix of the individual represented by the parent object. (E.g., JR = Junior, SR = Senior, etc.)</description>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Suffix</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyAddressXref__c.object
<CustomObject>
    <description>Association table between Party and Address . This supports capture of multiple types and also periodAtAddress.
This creates an address book of the party</description>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <description>The address lookup @managed</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyAddresses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>The party which owns the address.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>AddressXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Address Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartyAddresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__PhoneType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HOME</fullName>
        <label>Home</label>
    </customValue>
    <customValue>
        <fullName>WORK</fullName>
        <label>Work</label>
    </customValue>
    <customValue>
        <fullName>CELL</fullName>
        <label>Cell</label>
    </customValue>
    <customValue>
        <fullName>MOBILE</fullName>
        <label>Mobile</label>
    </customValue>
    <customValue>
        <fullName>BUSINESS</fullName>
        <label>Business</label>
    </customValue>
    <description>The type of the primary phone , valid values can be HOME,WORK,BUSINESS</description>
    <masterLabel>PhoneType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__Suffix.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Jr</fullName>
    </customValue>
    <customValue>
        <fullName>Sr</fullName>
        <label>Sr.</label>
    </customValue>
    <customValue>
        <fullName>II</fullName>
    </customValue>
    <customValue>
        <fullName>III</fullName>
    </customValue>
    <customValue>
        <fullName>IV</fullName>
    </customValue>
    <customValue>
        <fullName>246</fullName>
        <isActive>false</isActive>
        <label>246</label>
    </customValue>
    <customValue>
        <fullName>Esq</fullName>
        <isActive>false</isActive>
        <label>Esq</label>
    </customValue>
    <customValue>
        <fullName>VI</fullName>
        <isActive>false</isActive>
        <label>VI</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <isActive>false</isActive>
        <label>V</label>
    </customValue>
    <customValue>
        <fullName>2nd</fullName>
        <isActive>false</isActive>
        <label>2nd</label>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
        <isActive>false</isActive>
        <label>Test</label>
    </customValue>
    <description>The name suffix of the individual represented by the parent object. (E.g., JR = Junior, SR = Senior, etc.)</description>
    <masterLabel>Suffix</masterLabel>
</GlobalValueSet>

classes/FISCCDepositNameAddressHelper.cls
public with sharing class FISCCDepositNameAddressHelper {
  public static FISCCDepositNameAddressDTO depositAccountAddressRequest(
    List<tffa__Party__c> partyObjs,
    List<tffa__Application__c> appObjs,
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    FISCCDepositNameAddressDTO fisccDepositNameAddressDTO = new FISCCDepositNameAddressDTO();

    try {
      tffa.Logger.debug('Inside depositAccountAddressRequest method');
      tffa__Party__c partyObj = CZWTFCCommonHelper.getAppPrimaryParty(appObjs[0], partyObjs);
      tffa__Product__c prod = appObjs[0].tffa__Product__r;
      fisccDepositNameAddressDTO.DPAcctNbrNmeAddrMaint = appObjs[0].tffa__AccountNumber__c;
      fisccDepositNameAddressDTO.DPNmeAndAddrTyp = FISCCIntegrationConstants.DPNmeAndAddrTyp;

      fisccDepositNameAddressDTO.DPCIRqstInd = FISCCIntegrationConstants.DPCIRqstInd;

      if (partyObj.PreferredContactNumber__c.equalsIgnoreCase('CELL')) {
        fisccDepositNameAddressDTO.DPNmeAndAddrHmPh = Long.valueOf(CZWTFCCommonHelper.formatPhoneNumber(partyObj.CellPhoneNumber__c));
        if (!String.isBlank(partyObj.tffa__SecondaryPhone__c)) {
          fisccDepositNameAddressDTO.DPNmeAndAddrBusPh = Long.valueOf(
            CZWTFCCommonHelper.formatPhoneNumber(partyObj.tffa__SecondaryPhone__c)
          );
        } else if (!String.isBlank(partyObj.tffa__PrimaryPhone__c)) {
          fisccDepositNameAddressDTO.DPNmeAndAddrBusPh = Long.valueOf(CZWTFCCommonHelper.formatPhoneNumber(partyObj.tffa__PrimaryPhone__c));
        }
      } else if (partyObj.PreferredContactNumber__c.equalsIgnoreCase('HOME')) {
        fisccDepositNameAddressDTO.DPNmeAndAddrHmPh = Long.valueOf(CZWTFCCommonHelper.formatPhoneNumber(partyObj.tffa__PrimaryPhone__c));
        if (!String.isBlank(partyObj.tffa__SecondaryPhone__c)) {
          fisccDepositNameAddressDTO.DPNmeAndAddrBusPh = Long.valueOf(
            CZWTFCCommonHelper.formatPhoneNumber(partyObj.tffa__SecondaryPhone__c)
          );
        } else if (!String.isBlank(partyObj.CellPhoneNumber__c)) {
          fisccDepositNameAddressDTO.DPNmeAndAddrBusPh = Long.valueOf(CZWTFCCommonHelper.formatPhoneNumber(partyObj.CellPhoneNumber__c));
        }
      } else if (partyObj.PreferredContactNumber__c.equalsIgnoreCase('WORK')) {
        fisccDepositNameAddressDTO.DPNmeAndAddrHmPh = Long.valueOf(CZWTFCCommonHelper.formatPhoneNumber(partyObj.tffa__SecondaryPhone__c));
        if (!String.isBlank(partyObj.CellPhoneNumber__c)) {
          fisccDepositNameAddressDTO.DPNmeAndAddrBusPh = Long.valueOf(CZWTFCCommonHelper.formatPhoneNumber(partyObj.CellPhoneNumber__c));
        } else if (!String.isBlank(partyObj.tffa__PrimaryPhone__c)) {
          fisccDepositNameAddressDTO.DPNmeAndAddrBusPh = Long.valueOf(CZWTFCCommonHelper.formatPhoneNumber(partyObj.tffa__PrimaryPhone__c));
        }
      }
      /*tffa__Address__c addressObj;
      if (partyObj.tffa__AddressXrefs__r.size() > 1) {
        addressObj = CZWTFCCommonHelper.getPartyAddressByType(partyObj.tffa__AddressXrefs__r, 'MAILING');
      } else {
        addressObj = partyObj.tffa__AddressXrefs__r[0].tffa__Address__r;
      }*/
      // --call address

      fillAccountTitle(appObjs[0], fisccDepositNameAddressDTO);
      tffa.logger.debug('fillAddressDetails called');

      tffa.logger.debug('appObjs in depositAccountAddressRequest==>' + appObjs);
    } catch (Exception ex) {
      tffa.Logger.error('Exception in depositAccountAddressRequest : ' + +ex.getMessage() + ' Exception:::' + ex.getStackTraceString());
      return null;
    }
    tffa.Logger.debug('fisccDepositNameAddressDTO ==>' + fisccDepositNameAddressDTO);
    return fisccDepositNameAddressDTO;
  }

  // Not Used TODO: Remove this code
  public static fisccDepositNameAddressDTO fillPartyAndAddressDetails(
    List<tffa__Party__c> partyObjs,
    tffa__Party__c primaryParty,
    tffa__Application__c appObj,
    FISCCDepositNameAddressDTO fisccDepositNameAddressDTO,
    Boolean isCustodian
  ) {
    Integer jointApplicantCounter = 1;
    tffa.logger.debug('inside fisccDepositNameAddressDTO fillPartyAndAddressDetails');
    try {
      if (partyObjs != null && !partyObjs.isEmpty()) {
        tffa.logger.debug('inside objParty not null ');
        for (tffa__Party__c partyObj : partyObjs) {
          Boolean isPrimary = primaryParty.Id.equals(partyObj.Id);
          String sfx = partyObj.tffa__Suffix__c != null ? partyObj.tffa__Suffix__c + ' ' : '';
          if (isPrimary) {
            fisccDepositNameAddressDTO.DPNmeAndAddrLne1 = CZWTFCCommonHelper.getFormattedFullName(
              partyObj.tffa__FirstName__c,
              partyObj.tffa__MiddleName__c,
              partyObj.tffa__LastName__c,
              (isCustodian) ? sfx + FISCCIntegrationConstants.MINOR_UTMA : partyObj.tffa__Suffix__c,
              FISCCIntegrationConstants.FULL_NAME_LENGTH
            );
          } else {
            if (jointApplicantCounter == 1) {
              fisccDepositNameAddressDTO.DPNmeAndAddrLne2 = CZWTFCCommonHelper.getFormattedFullName(
                partyObj.tffa__FirstName__c,
                partyObj.tffa__MiddleName__c,
                partyObj.tffa__LastName__c,
                (isCustodian) ? sfx + FISCCIntegrationConstants.CUSTODIAN : partyObj.tffa__Suffix__c,
                FISCCIntegrationConstants.FULL_NAME_LENGTH
              );
            }
            jointApplicantCounter++;
          }
        }
      }
      fillAddress(partyObjs, appObj, fisccDepositNameAddressDTO);
    } catch (Exception ex) {
      tffa.logger.debug(
        ' Exception into FISCCCreateNewDepositAccountHelper : assignNameValue :::' +
        ex.getMessage() +
        ' Exception:::' +
        ex.getStackTraceString()
      );
      return null;
    }

    tffa.logger.debug('FISCCCreateNewDepositAccountHelper in AssignNameValue : ==>' + fisccDepositNameAddressDTO);
    return fisccDepositNameAddressDTO;
  }

  public static FisccDepositNameAddressDTO fillAccountTitle(
    tffa__Application__c appObj,
    FisccDepositNameAddressDTO fisccDepositNameAddressDTO
  ) {
    List<String> accTitleLst = new List<String>();
    if (String.isNotBlank(appObj.CZTitle1__c)) {
      accTitleLst.add(appObj.CZTitle1__c);
    }
    if (String.isNotBlank(appObj.CZTitle2__c)) {
      accTitleLst.add(appObj.CZTitle2__c);
    }
    if (String.isNotBlank(appObj.CZTitle3__c)) {
      accTitleLst.add(appObj.CZTitle3__c);
    }

    if (appObj.tffa__Address__r != null) {
      FISCCCommonHelper.setAccountAddress(accTitleLst, appObj.tffa__Address__r);
    }
    for (String title : accTitleLst) {
      if (String.isBlank(fisccDepositNameAddressDTO.DPNmeAndAddrLne1)) {
        fisccDepositNameAddressDTO.DPNmeAndAddrLne1 = title;
      } else if (String.isBlank(fisccDepositNameAddressDTO.DPNmeAndAddrLne2)) {
        fisccDepositNameAddressDTO.DPNmeAndAddrLne2 = title;
      } else if (String.isBlank(fisccDepositNameAddressDTO.DPNmeAndAddrLne3)) {
        fisccDepositNameAddressDTO.DPNmeAndAddrLne3 = title;
      } else if (String.isBlank(fisccDepositNameAddressDTO.DPNmeAndAddrLne4)) {
        fisccDepositNameAddressDTO.DPNmeAndAddrLne4 = title;
      } else if (String.isBlank(fisccDepositNameAddressDTO.DPNmeAndAddrLne5)) {
        fisccDepositNameAddressDTO.DPNmeAndAddrLne5 = title;
      }
    }
    return fisccDepositNameAddressDTO;
  }

  // Not Used TODO: Remove this code
  /**
   *  fill address in DTO
   */
  public static FisccDepositNameAddressDTO fillAddress(
    List<tffa__Party__c> partyObjs,
    tffa__Application__c appObj,
    FisccDepositNameAddressDTO fisccDepositNameAddressDTO
  ) {
    if (partyObjs.size() == 1) {
      fisccDepositNameAddressDTO.DPNmeAndAddrLne2 = appObj.CZLine1__c;

      if (String.isNotBlank(appObj.CZLine2__c)) {
        fisccDepositNameAddressDTO.DPNmeAndAddrLne3 = appObj.CZLine2__c;
        if (String.isNotBlank(appObj.CZCity__c) && String.isNotBlank(appObj.CZState__c) && String.isNotBlank(appObj.CZZipCode__c)) {
          fisccDepositNameAddressDTO.DPNmeAndAddrLne4 = appObj.CZCity__c + ' ' + appObj.CZState__c + ' ' + appObj.CZZipCode__c;
        }
      } else if (String.isNotBlank(appObj.CZCity__c) && String.isNotBlank(appObj.CZState__c) && String.isNotBlank(appObj.CZZipCode__c)) {
        fisccDepositNameAddressDTO.DPNmeAndAddrLne3 = appObj.CZCity__c + ' ' + appObj.CZState__c + ' ' + appObj.CZZipCode__c;
      }
    } else if (partyObjs.size() >= 2) {
      fisccDepositNameAddressDTO.DPNmeAndAddrLne3 = appObj.CZLine1__c;

      if (String.isNotBlank(appObj.CZLine2__c)) {
        fisccDepositNameAddressDTO.DPNmeAndAddrLne4 = appObj.CZLine2__c;
        if (String.isNotBlank(appObj.CZCity__c) && String.isNotBlank(appObj.CZState__c) && String.isNotBlank(appObj.CZZipCode__c)) {
          fisccDepositNameAddressDTO.DPNmeAndAddrLne5 = appObj.CZCity__c + ' ' + appObj.CZState__c + ' ' + appObj.CZZipCode__c;
        }
      } else if (String.isNotBlank(appObj.CZCity__c) && String.isNotBlank(appObj.CZState__c) && String.isNotBlank(appObj.CZZipCode__c)) {
        fisccDepositNameAddressDTO.DPNmeAndAddrLne4 = appObj.CZCity__c + ' ' + appObj.CZState__c + ' ' + appObj.CZZipCode__c;
      }
    }
    return fisccDepositNameAddressDTO;
  }
}