objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <fields>
        <fullName>OrganizationId__c</fullName>
        <description>FIS processing organization ID</description>
        <label>OrganizationId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/tffa__AccountPreference__c.object
<CustomObject>
    <description>List of account preferences/additional services applied along with the application. Example values are ATM_CARD, INTERNET_BANKING, CHECKBOOK</description>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>Account number. e.g. Account number captured for Balance Transfer.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Address associated with the preference. e.g Payment address captured for Balance Transfer.</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Account Preferences</relationshipLabel>
        <relationshipName>AccountPreferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application</description>
        <inlineHelpText>Master Detail Lookup</inlineHelpText>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Account Preferences</relationshipLabel>
        <relationshipName>AccountPreferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__CardBINCode__c</fullName>
        <description>Bank Identification Number (“BIN”) or Issuer identification number (“IIN”) is the first six digits of a bank card number or payment
        cards number and it is part of ISO/IEC 7812.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <inlineHelpText>Bank Identification Number (“BIN”) or Issuer identification number (“IIN”) is beneficial to identify a card brand, issuing institution or bank, country of issuance, card type and category of cards.</inlineHelpText>
        <label>Card BIN Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__CardNumber__c</fullName>
        <description>Card number (of applied debit card)</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Card number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>Unique identifier for the preference or service opted for.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__EmbossedName__c</fullName>
        <description>Name as it would appear on a card. e.g. Add-on Card.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Embossed name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to related party.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Account Preferences</relationshipLabel>
        <relationshipName>AccountPreferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <description>Current state (of processing) of the account preference.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account Preference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Address__c.object
<CustomObject>
    <description>An address is a collection of information, presented in a mostly fixed format, used to give the location of a building, apartment, or other structure or a plot of land, generally using political boundaries and street names as references,  along with other identifiers such as house or apartment numbers

 For more reference lookup https://en.wikipedia.org/wiki/Address_(geography)#United_States</description>
    <fields>
        <fullName>tffa__City__c</fullName>
        <description>The city of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Line1__c</fullName>
        <description>line 1 of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Line1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Line2__c</fullName>
        <description>line 2 of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <description>A state is a geographical region of a country used for administrative or political purposes,</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ZipCode__c</fullName>
        <description>Also known as post code , a series of numbers that forms part of an address, used to help organize post so that it can be delivered more quickly</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>Fis branch code for Location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Branch Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The final generated account number. This will be set only after the final account number is available as part of the response of an account open API call.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account address for purposes of statement etc. If Address Prefill Source Id is set, the address details are not persisted directly, only address id is persisted.</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product code identifier.</description>
        <label>Financial Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR (4 AND 5))</booleanFilter>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>$Source.tffa__ProductCategory__c</field>
                <operation>equals</operation>
                <valueField>tffa__Product__c.tffa__Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value>In Progress</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <defaultValue>&quot;Init&quot;</defaultValue>
        <description>The stage of the application in context of the product applied. This will be different for each product and is more granular than the status field.This field will be updated on the state transition the application in the origination workflow.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>Fis branch code for Location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Branch Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__FirstName__c</fullName>
        <description>The first name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>The last name of the individual represented by the parent object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__MiddleName__c</fullName>
        <description>The middle name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__NationalIdentifierValue__c</fullName>
        <description>The value of the taxpayer identifier as assigned by the IRS to the individual or legal entity.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>National identifier value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyAddressXref__c.object
<CustomObject>
    <description>Association table between Party and Address . This supports capture of multiple types and also periodAtAddress.
This creates an address book of the party</description>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <description>The address lookup @managed</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyAddresses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>The party which owns the address.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>AddressXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Address Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartyAddresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <fields>
        <fullName>tffa__Category__c</fullName>
        <description>Broad classification of the product</description>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ProductCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique identifier for the product</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FISCCCardBaseIntegrationHelper.cls
public with sharing class FISCCCardBaseIntegrationHelper {
  public static String cardNumber = '';

  public static FISCCRequestBaseDTO getGenerateCardNoRequest(
    tffa__party__c partyObj,
    tffa__AccountPreference__c accPref,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    FISCCRequestBaseDTO requestDTO;
    FISCCDebitCardNoGenRequestDTO request = new FISCCDebitCardNoGenRequestDTO();
    //request.CardNumber.CBInstnNbr = (partyObj.BrandCode__c == null) ? '' : partyObj.BrandCode__c.leftPad(5, '0');
    //request.CardNumber.CBCrdPrfxNbr = accPref.tffa__CardBINCode__c == null ? '' :accPref.tffa__CardBINCode__c;
    request.CardNumber.CBInstnNbr = (charterConfig.OrganizationId__c).right(3).leftPad(5, '0');
    request.CardNumber.CBCrdPrfxNbr = CZWTFCHelperRepository.findAddOnServiceByCodeandType(
        accPref.tffa__code__c,
        FISCCIntegrationConstants.DBT_TYPE
      )
      .tffa__CardBINCode__c;
    requestDTO = request;

    return requestDTO;
  }

  public static FISCCRequestBaseDTO getCardCreationRequest(
    tffa__party__c partyObj,
    tffa__AccountPreference__c accPref,
    tffa__Application__c appObj,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    FISCCRequestBaseDTO requestDTO;
    FISCCDebitCardCreationRequestDTO request = new FISCCDebitCardCreationRequestDTO();
    tffa__Address__c addressObj = new tffa__Address__c();
    addressObj = partyObj.tffa__AddressXrefs__r[0].tffa__Address__r;

    request.CardNew.CBCrdNbr = accPref.tffa__CardNumber__c;
    request.CardNew.CustNbr = partyObj.Customer_Number__c;
    request.CardNew.CBStAbbr = addressObj.tffa__State__c;
    request.CardNew.CBInstnNbr = (charterConfig.OrganizationId__c).right(3).leftPad(5, '0');
    request.CardNew.CBCrdPrfxNbr = CZWTFCHelperRepository.findAddOnServiceByCodeandType(
        accPref.tffa__code__c,
        FISCCIntegrationConstants.DBT_TYPE
      )
      .tffa__CardBINCode__c;
    request.CardNew.CBBrnchNbr = appObj.FISBranchCode__c;
    request.CardNew.CBStrAddrLne1 = CZWTFCCommonHelper.trimString(addressObj.tffa__Line1__c, 30);
    request.CardNew.CBStrAddrLne2 = CZWTFCCommonHelper.trimString(addressObj.tffa__Line2__c, 30);
    request.CardNew.CBCtyNme = CZWTFCCommonHelper.trimString(addressObj.tffa__City__c, 20);
    request.CardNew.CBZIP = CZWTFCCommonHelper.trimString(addressObj.tffa__ZipCode__c, 5);
    //if ('SAVINGS'.equals(appObj.tffa__Product__r.tffa__Category__c)) {
    //request.CardNew.CBPrmyDdaAcctNbr = appObj.tffa__AccountNumber__c;
    //} else if ('CHECKING'.equals(appObj.tffa__Product__r.tffa__Category__c)) {
    //request.CardNew.CBPrmySavAcctNbr = appObj.tffa__AccountNumber__c;
    //}
    request.CardNew.CBPrmyDdaAcctNbr = appObj.tffa__AccountNumber__c;
    request.CardNew.CBPrmySsn = partyObj.tffa__NationalIdentifierValue__c;
    request.CardNew.NmeEmbossOnCard = accPref.tffa__EmbossedName__c;
    request.CardNew.CBShrtNmeFrst = CZWTFCCommonHelper.trimString(partyObj.tffa__FirstName__c, 10);
    request.CardNew.CBShrtNmeLst = CZWTFCCommonHelper.trimString(partyObj.tffa__LastName__c, 15);
    String middleNameInitial = CZWTFCCommonHelper.trimString(partyObj.tffa__MiddleName__c, 1);
    request.CardNew.CBCrdNmeLne1 = accPref.tffa__EmbossedName__c;

    requestDTO = request;

    return requestDTO;
  }

  public static FISCCRequestBaseDTO getCardToCustRelationRequest(
    tffa__party__c partyObj,
    tffa__AccountPreference__c accPref,
    tffa__Application__c appObj
  ) {
    FISCCRequestBaseDTO requestDTO;
    FISCCDebitCardAccRelRequestDTO request = new FISCCDebitCardAccRelRequestDTO();
    tffa__Address__c addressObj = new tffa__Address__c();
    addressObj = partyObj.tffa__AddressXrefs__r[0].tffa__Address__r;
    request.acc.CIRltApplNbr01 = partyObj.Customer_Number__c;
    request.acc.CIEnt1ToEnt2RltCde = FISCCIntegrationConstants.SOLE_OWNER;
    request.acc.PriSecRltCde01 = 'P';
    request.acc.NAStandardizationOvride = 'Y';
    request.acc.CINmeAddrLneCde01 = 'N';
    String suffix = partyObj.tffa__Suffix__c != null ? partyObj.tffa__Suffix__c : '';
    request.acc.NmeAddrLne01 = CZWTFCCommonHelper.getFormattedFullName(
      partyObj.tffa__FirstName__c,
      partyObj.tffa__MiddleName__c,
      partyObj.tffa__LastName__c,
      suffix,
      FISCCIntegrationConstants.CUST_NAME_LENGTH
    );

    if (addressObj.tffa__Line2__c != null) {
      request.acc.CINmeAddrLneCde02 = 'A';
      request.acc.CINmeAddrLneCde03 = 'S';
      request.acc.CINmeAddrLneCde04 = 'C';
      request.acc.NmeAddrLne02 = CZWTFCCommonHelper.trimString(addressObj.tffa__Line1__c, 30);
      request.acc.NmeAddrLne03 = CZWTFCCommonHelper.trimString(addressObj.tffa__Line2__c, 30);
      request.acc.NmeAddrLne04 = (addressObj.tffa__City__c + ' ' + addressObj.tffa__State__c + ' ' + addressObj.tffa__ZipCode__c);
    } else {
      request.acc.CINmeAddrLneCde02 = 'S';
      request.acc.CINmeAddrLneCde03 = 'C';
      request.acc.NmeAddrLne02 = CZWTFCCommonHelper.trimString(addressObj.tffa__Line1__c, 30);
      request.acc.NmeAddrLne03 = (addressObj.tffa__City__c + ' ' + addressObj.tffa__State__c + ' ' + addressObj.tffa__ZipCode__c);
    }
    request.acc.ApplCde = 'CBM';
    request.acc.AcctNbr = accPref.tffa__CardNumber__c;
    requestDTO = request;

    return requestDTO;
  }

  public static FISCCRequestBaseDTO getUpdateCustDemographicsRequest(
    tffa__party__c partyObj,
    tffa__AccountPreference__c accPref,
    tffa__Application__c appObj
  ) {
    FISCCRequestBaseDTO requestDTO;
    FISCCDebitCardCustDetailsRequestDTO request = new FISCCDebitCardCustDetailsRequestDTO();

    request.CardsCardholderAddress.Email = partyObj.tffa__PrimaryEmail__c;
    request.CardsCardholderAddress.PrmyHmPh = (partyObj.CellPhoneNumber__c) == null
      ? partyObj.tffa__PrimaryPhone__c
      : partyObj.CellPhoneNumber__c;
    requestDTO = request;

    return requestDTO;
  }

  public static Boolean isAPICallSuccess(List<FISCCMsgListDTO> msgList) {
    Boolean isScuccess = false;
    if (msgList != null && !msgList.isEmpty()) {
      if (('0').equalsIgnoreCase(msgList[0].Code) && ('Success').equalsIgnoreCase(msgList[0].Text)) {
        isScuccess = true;
      }
    }
    return isScuccess;
  }
}