objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <fields>
        <fullName>IBSAuthorization__c</fullName>
        <description>IBS-Authorization is not required for the sandbox environment. When provided, base64 encode the string in the format &quot;userid:password&quot;.</description>
        <inlineHelpText>IBSAuthorization.</inlineHelpText>
        <label>IBSAuthorization</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/FISIBSAuthConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>FIS IBS Authentication Configuration</description>
    <fields>
        <fullName>IBSAuthorization__c</fullName>
        <description>Base64 encode the string in the format &amp;quot;userid:password&amp;quot;</description>
        <encryptionScheme>None</encryptionScheme>
        <label>IBSAuthorization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FISIBSAuthConfig</label>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>tffa__BrandCode__c</fullName>
        <description>Brand code of the submission this party is associated with</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FISCCCEBEnrollmentProvider.cls
public inherited sharing class FISCCCEBEnrollmentProvider {
  public static Object CEBEnroll(tffa__Party__c partyObj, String userName, String password) {
    Boolean isSuccess = false;
    Boolean isAPICall = false;
    Boolean isAPICallFailed = false;

    Object result = null;

    String strDeveloperName = 'CEBEnroll';

    try {
      FISCC_Adapter_Configs__mdt adapterConfig = FISCCIntegrationLogRepository.findAdapterConfig(strDeveloperName);
      FISCC_Charter_Config__mdt charterConfig = FISCCIntegrationLogRepository.findCharterConfigByBrandCode(partyObj.tffa__BrandCode__c);
      if (!Test.isRunningTest()) {
        FISIBSAuthConfig__c fisAuthConfig = FISCCIntegrationLogRepository.findAuthByBrandandActiveState(partyObj.tffa__BrandCode__c, true);
        charterConfig.IBSAuthorization__c = fisAuthConfig.IBSAuthorization__c;
      }
      FISCCIntegrationLogService.applicationCode = 'CEB';
      FISCCIntegrationLogService.charterConfig = charterConfig;
      FISCCIntegrationLogService.auth = FISCCGetAccessTokenProvider.processGetAccessToken(charterConfig);

      tffa.logger.debug('partyObj' + partyObj);
      if (partyObj != null) {
        tffa.logger.debug('param partyObj is not empty ..');
        Map<String, Object> paramMap = new Map<String, Object>();
        paramMap.put('partyObj', partyObj);
        paramMap.put('userName', userName);
        paramMap.put('password', password);
        //tffa.logger.debug('paramMap for invokeCEBEnroll :: ' + paramMap);
        result = FISCCCEBEnrollmentExtension.invokeCEBEnroll(paramMap, adapterConfig, charterConfig);
        tffa.logger.debug('result from CEBEnroll provider :: ' + result);
      }
    } catch (Exception ex) {
      tffa.Logger.error('Exception in FISCCCEBEnrollmentProvider : ' + ex.getMessage() + ' Exception :::' + ex.getStackTraceString());
    }
    tffa.logger.debug('result from CEBEnroll provider :: ' + result);
    return result;
  }
}