objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <fields>
        <fullName>IBSAuthorization__c</fullName>
        <description>IBS-Authorization is not required for the sandbox environment. When provided, base64 encode the string in the format &quot;userid:password&quot;.</description>
        <inlineHelpText>IBSAuthorization.</inlineHelpText>
        <label>IBSAuthorization</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/FISIBSAuthConfig__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>FIS IBS Authentication Configuration</description>
    <fields>
        <fullName>IBSAuthorization__c</fullName>
        <description>Base64 encode the string in the format &amp;quot;userid:password&amp;quot;</description>
        <encryptionScheme>None</encryptionScheme>
        <label>IBSAuthorization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FISIBSAuthConfig</label>
</CustomObject>

objects/tffa__AccountPreference__c.object
<CustomObject>
    <description>List of account preferences/additional services applied along with the application. Example values are ATM_CARD, INTERNET_BANKING, CHECKBOOK</description>
    <fields>
        <fullName>tffa__AddOnServiceType__c</fullName>
        <description>Captures the type of applied add-on service.</description>
        <label>Add-on service type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__AddOnServiceType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application</description>
        <inlineHelpText>Master Detail Lookup</inlineHelpText>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Account Preferences</relationshipLabel>
        <relationshipName>AccountPreferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to related party.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Account Preferences</relationshipLabel>
        <relationshipName>AccountPreferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Current status (of processing) of the account preference.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__AccountPreferenceStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Account Preference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__AdditionalPreference__c.object
<CustomObject>
    <description>Additional preference usually captured for a party e.g. Online Banking, E-Statements. These are not specific to an application. For ones that are, use Account Preferences.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the party whose preference is being captured.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Additional Preferences</relationshipLabel>
        <relationshipName>AdditionalPreferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Current status (of processing) of the additional preference</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__AdditionalPreferenceStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Additional Preferences</relationshipLabel>
        <relationshipName>AdditionalPreferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Additional Preference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>IsRoutingRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to check if routing and mail event needs to be triggered from batch for an application</description>
        <label>Is Routing Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Brand__c</fullName>
        <description>Brand code of the Brand for the submission if applicable</description>
        <formula>tffa__Submission__r.tffa__Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the application</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ApplicationPartyXref__c.object
<CustomObject>
    <description>Each Applicant of the submission can play different roles in the application and the eventual account.</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Beneficiary__c.object
<CustomObject>
    <description>A beneficiary typically refers to someone who is eligible to receive distributions from deposits upon death of primary owner of account. Beneficiary capture typically happens for Certificate Deposits.
Designating a beneficiary not only ensures the CD will not have to go through probate when the applicant dies.</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Beneficiaries</relationshipLabel>
        <relationshipName>Beneficiaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Beneficiary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Beneficiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__FundingRequest__c.object
<CustomObject>
    <description>Supports the capture of details pertaining to funding a payment obligation using one of the various available sources of funding</description>
    <fields>
        <fullName>tffa__LinkedApplication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to application.</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Funding Requests</relationshipLabel>
        <relationshipName>LinkedFundingRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Funding status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__FundingStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to parent submission.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Consolidated Funding Requests</relationshipLabel>
        <relationshipName>FundingRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyPartyXref__c.object
<CustomObject>
    <description>A relationship between 2 applicants of a submission. 
Personal relationship could be SPOUSE, PARENT, FRIENDS.
Business relationship between a company and an individual could be DIRECTOR, OWNER, EXECUTIVE, PARTNER etc. In additional the ownership percentage can be captured for OWNER type of relationship. 
Relationship between 2 company type applicants can also be captured such as PARENT and SUBSIDIARY.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Party managing the relationship</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Related To</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Party Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Party Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__Brand__c</fullName>
        <description>Brand code of the Brand for the submission if applicable</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the submission</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__SubmissionPartyXref__c.object
<CustomObject>
    <description>An individual or a legal entity which is applying for certain services/products in the bank. An applicant exists only in the context of a submission.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to Party object @managed</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>The data entry status of the party in this submission. This is applicable in case of joint applications where the party fills data individually</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionPartyStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission object.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submission Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/tffa__AccountPreferenceStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
        <label>Failed</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>List of status(s) (of processing) of account preference.</description>
    <masterLabel>AccountPreferenceStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__AdditionalPreferenceStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
        <label>Failed</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>List of status(s) (of processing) of additional preference.</description>
    <masterLabel>AdditionalPreferenceStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__FundingStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>FUNDED</fullName>
        <label>Funded</label>
    </customValue>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
        <label>Failed</label>
    </customValue>
    <customValue>
        <fullName>APPROVAL</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>REVERSED</fullName>
        <label>Reversed</label>
    </customValue>
    <customValue>
        <fullName>REVERSAL_FAILED</fullName>
        <label>Reversal Failed</label>
    </customValue>
    <customValue>
        <fullName>ACH_FILE_GENERATED</fullName>
        <label>ACH File Generated</label>
    </customValue>
    <customValue>
        <fullName>ACH_FILE_FAILED</fullName>
        <label>ACH File Generation Failed</label>
    </customValue>
    <customValue>
        <fullName>HOLD_APPLIED</fullName>
        <label>Hold Applied on Funds</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>REVERSAL_NOT_REQ</fullName>
        <label>Reversal Not Required</label>
    </customValue>
    <customValue>
        <fullName>AUTHORIZED</fullName>
        <isActive>false</isActive>
        <label>AUTHORIZED</label>
    </customValue>
    <description>Status of funding</description>
    <masterLabel>FundingStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionPartyStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>COMPLETE</fullName>
        <label>Complete</label>
    </customValue>
    <customValue>
        <fullName>INCOMPLETE</fullName>
        <label>Incomplete</label>
    </customValue>
    <description>The status of the party in the submission. More akin to data entry status</description>
    <masterLabel>SubmissionPartyStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>ABANDONED</fullName>
        <label>Abandoned</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>SAVED</fullName>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>SUBMITTED</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>Indicates current status of the submission.This will be computed and be useful for regulations.</description>
    <masterLabel>SubmissionStatus</masterLabel>
</GlobalValueSet>

classes/FISCCIntegrationLogService.cls
public with sharing class FISCCIntegrationLogService extends CZWTFCIntegrationLogService {
  //submission attribute
  public static tffa__Submission__c submissionObj { get; set; }
  //party attribute
  public static list<tffa__Party__c> partyObjs { get; set; }
  //Application attribute
  public static list<tffa__Application__c> applicationObjs { get; set; }

  public static list<tffa__Application__c> reviewApps { get; set; }

  public static FISCC_Charter_Config__mdt charterConfig { get; set; }
  public static tffa__Brand__c brandObj { get; set; }

  public static String auth;
  public static String tempAuth;
  public static String applicationCode = '';
  public static Boolean isBatchSource = false;
  public static String entityAuthToken;

  public static Blob contentVersionData;
  public static String fcmDocumentId;

  public static void setCharterConfig(String brandCode) {
    charterConfig = FISCCIntegrationLogRepository.findCharterConfigByBrandCode(brandCode);
    if (!Test.isRunningTest()) {
      FISIBSAuthConfig__c fisAuthConfig = FISCCIntegrationLogRepository.findAuthByBrandandActiveState(brandCode, true);
      if (fisAuthConfig != null) {
        charterConfig.IBSAuthorization__c = fisAuthConfig.IBSAuthorization__c;
      }
    }
  }

  public static void setBrandObj(String brandCode) {
    brandObj = CZWTFCBrandRepository.fetchBrandByCode(brandCode);
  }

  public static void setSubmissionObj(String submissionId) {
    submissionObj = FISCCIntegrationLogRepository.findSubmissionById(submissionId);
    if (submissionObj != null)
      setCharterConfig(submissionObj.tffa__Brand__c);
    setBrandObj(submissionObj.tffa__Brand__c);
  }

  public static void setApplicationObjs() {
    applicationObjs = FISCCIntegrationLogRepository.findApplicationWithChildObjects(submissionObj.tffa__Applications__r);
  }

  public static void setPartyObjs() {
    List<Id> partyIds = new List<id>();
    for (tffa__SubmissionPartyXref__c partyXrefObj : submissionObj.tffa__PartyXrefs__r) {
      partyIds.add(partyXrefObj.tffa__Party__c);
    }
    partyObjs = FISCCIntegrationLogRepository.findPartydWithChildObjects(partyIds);
  }

  public static tffa__Submission__c fetchSubmissionById(String submissionId) {
    return FISCCIntegrationLogRepository.findSubmissionById(submissionId);
  }

  public static void persistData() {
    tffa.Logger.debug('Before Persist : Submission obj ::: ' + json.serialize(FISCCIntegrationLogService.submissionObj));
    tffa.Logger.debug('Before Persist : applicationObjs::: ' + json.serialize(FISCCIntegrationLogService.applicationObjs));
    tffa.Logger.debug('Before Persist : setPartyObjs ::: ' + json.serialize(FISCCIntegrationLogService.partyObjs));
    List<tffa__Beneficiary__c> benefList = new List<tffa__Beneficiary__c>();
    List<tffa__ApplicationPartyXref__c> appPartyLst = new List<tffa__ApplicationPartyXref__c>();
    List<tffa__AccountPreference__c> accPrefObjLst = new List<tffa__AccountPreference__c>();
    List<tffa__FundingRequest__c> fundingReqList = new List<tffa__FundingRequest__c>();
    List<tffa__AdditionalPreference__c> additionalPreferenceList = new List<tffa__AdditionalPreference__c>();
    //upsert party in salesforce
    if (FISCCIntegrationLogService.partyObjs != null && FISCCIntegrationLogService.partyObjs.size() != 0) {
      FISCCObjectManagerRepository.doUpsertPartys(FISCCIntegrationLogService.partyObjs);

      for(tffa__Party__c partyObj : FISCCIntegrationLogService.partyObjs){
        for(tffa__AdditionalPreference__c additionalPreference : partyObj.tffa__AdditionalPreferences__r){
          additionalPreferenceList.add(additionalPreference);
        }
      }

      FISCCObjectManagerRepository.doUpsertAdditionalPrefObj(additionalPreferenceList);
    }

    tffa.Logger.debug('party updated');
    if (isBatchSource) {
      for (tffa__Application__c applicationObject : FISCCIntegrationLogService.applicationObjs) {
        applicationObject.IsRoutingRequired__c = true;
      }
    }

    //upsert account
    if (FISCCIntegrationLogService.applicationObjs != null && !FISCCIntegrationLogService.applicationObjs.isEmpty()) {
      FISCCObjectManagerRepository.doUpsertApplications(FISCCIntegrationLogService.applicationObjs);
    }
    tffa.Logger.debug('Applications updated');
    if (FISCCIntegrationLogService.applicationObjs != null && !FISCCIntegrationLogService.applicationObjs.isEmpty()) {
      for (tffa__Application__c applicationObject : FISCCIntegrationLogService.applicationObjs) {
        if (applicationObject.tffa__Beneficiaries__r != null && !applicationObject.tffa__Beneficiaries__r.isEmpty()) {
          benefList.addAll(applicationObject.tffa__Beneficiaries__r);
        }

        if (applicationObject.tffa__PartyXrefs__r != null && !applicationObject.tffa__PartyXrefs__r.isEmpty()) {
          appPartyLst.addAll(applicationObject.tffa__PartyXrefs__r);
        }

        if (applicationObject.tffa__LinkedFundingRequests__r != null && !applicationObject.tffa__LinkedFundingRequests__r.isEmpty()) {
          fundingReqList.addAll(applicationObject.tffa__LinkedFundingRequests__r);
        }

        if (
          (applicationObject.tffa__Status__c == CZWTFCConstants.ACCOUNT_OPENED ||
          applicationObject.tffa__Status__c == CZWTFCConstants.FUNDED) &&
          applicationObject.tffa__AccountPreferences__r != null &&
          !applicationObject.tffa__AccountPreferences__r.isEmpty()
        ) {
          for (tffa__AccountPreference__c accPrefObj : applicationObject.tffa__AccountPreferences__r) {
            if (FISCCIntegrationConstants.OD_FOR_STANDARD_ADDON_TYPE == accPrefObj.tffa__AddOnServiceType__c) {
              accPrefObj.tffa__Status__c = CZWTFCConstants.ADDON_STATUS_COMPLETED;
              accPrefObjLst.add(accPrefObj);
            }
          }
        }

        /* send account opening email*/
        if (!isBatchSource) {
          try {
            System.enqueueJob(new CZWTFCAppRoutingService(applicationObject));
          } catch (Exception ex) {
            tffa.Logger.error('Exception in Routing Enqueue Job ' + ex.getMessage() + ' ' + ex.getStackTraceString());
            applicationObject.IsRoutingRequired__c = true;
          }
        }
      }
    }

    if (benefList != null && !benefList.isEmpty()) {
      FISCCObjectManagerRepository.doUpsertBeneficiarys(benefList);
      tffa.Logger.debug('Beneficiary updated updated');
    }

    if (appPartyLst != null && !appPartyLst.isEmpty()) {
      FISCCObjectManagerRepository.doApplicationPartyReq(appPartyLst);
      tffa.Logger.debug('ApplicationPartyXref updated');
    }

    if (fundingReqList != null && !fundingReqList.isEmpty()) {
      FISCCObjectManagerRepository.doUpsertFundingReq(fundingReqList);
      tffa.Logger.debug('fundingReqList updated updated');
    }

    if (accPrefObjLst != null && !accPrefObjLst.isEmpty()) {
      FISCCObjectManagerRepository.doUpsertAccountPrefObj(accPrefObjLst);
      tffa.Logger.debug('AccountPreference updated');
    }

    persistIntegationLogs();
    //--- Update Submission

    FISCCObjectManagerRepository.doUpsertSubmission(FISCCIntegrationLogService.submissionObj);
    tffa.Logger.debug('Submission updated');
  }

  /**
   * Triggers one mail (only primary applicant) per submission having a funding request verification status as Manual pending
   */
  public static void triggerMailForManualFundingPending(String subId) {
    tffa__FundingRequest__c fundingRequest = null;
    String fundingVerificationStatus = null;
    tffa__Submission__c subObj;
    List<tffa__Application__c> appList;
    try {
      tffa.Logger.debug('start of funding verification status event');
      subObj = FISCCIntegrationLogRepository.findSubmissionById(subId);
      appList = FISCCIntegrationLogRepository.findApplicationWithChildObjects(subObj.tffa__Applications__r);
      if (!appList.isEmpty()) {
        for (tffa__application__c application : appList) {
          if (application != null && !application.tffa__LinkedFundingRequests__r.isEmpty()) {
            for (Integer i = 0; i < application.tffa__LinkedFundingRequests__r.size(); i++) {
              fundingRequest = application.tffa__LinkedFundingRequests__r[i];
              if (fundingRequest != null && !String.isBlank(fundingRequest.tffa__VerificationStatus__c)) {
                fundingVerificationStatus = String.valueOf(fundingRequest.tffa__VerificationStatus__c);
                if (FISCCIntegrationConstants.PENDING_MANUAL_VERIFICATION.endsWithIgnoreCase(fundingVerificationStatus)) {
                  try {
                    tffa.Logger.debug('TRIGGERING EVENT FOR FUNDING VERIFICATION STATUS');
                    (new CZWTFCApplicationEventExtension('Funding_Manual_Verification')).post(application);
                    return;
                  } catch (Exception ex) {
                    tffa.Logger.debug(
                      'Exception in Mail Events Triggering :::' +
                      ex.getMessage() +
                      ' LineNumber :::' +
                      ex.getStackTraceString()
                    );
                  }
                }
              }
            }
          }
        }
      }
    } catch (Exception e) {
      tffa.Logger.debug(' Exception in generateMails : ' + e.getMessage() + ' Exception :::' + e.getStackTraceString());
    }
  }
}