objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>IsAuthenticatedCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Authenticated Customer</description>
        <label>Authenticated Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsEmailIdMissing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Email Id field missing from MDM Response</description>
        <label>EmailId Missing in IBS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsPhoneNumberMissing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Phone Number field missing from MDM Response</description>
        <label>Phone Number Missing in IBS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__IsExistingCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current applicant is existing customer of the bank.</description>
        <label>IsExistingCustomer</label>
        <type>Checkbox</type>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FISCCUpdateCustInfoProvider.cls
public with sharing class FISCCUpdateCustInfoProvider {
  public static boolean updateCustInfo(List<tffa__Party__c> partyObjList) {
    Object result = null;
    Boolean isSuccess = true;
    String strDeveloperName = 'CreateDueDiligence';
    Boolean isIntegrationLogSet = false;

    // try{
    List<tffa__Party__c> partyUpdatedList = new List<tffa__Party__c>();
    FISCC_Adapter_Configs__mdt adapterConfig = FISCCIntegrationLogRepository.findAdapterConfig(strDeveloperName);
    FISCC_Charter_Config__mdt charterConfig = FISCCIntegrationLogService.charterConfig;
    //null check auth
    if (String.isBlank(FISCCIntegrationLogService.auth)) {
      FISCCIntegrationLogService.auth = FISCCGetAccessTokenProvider.processGetAccessToken(charterConfig);
    }
    for (tffa__Party__c partyObj : partyObjList) {
      boolean partySuccess = true;
      if (!partyObj.tffa__IsExistingCustomer__c) {
        if (!isIntegrationLogSet) {
          FISCCIntegrationLogService.setCurrentLog(FISCCIntegrationConstants.UPDATED_CUSTOMER_INFORMATION_FLOW);
          isIntegrationLogSet = true;
        }
        partySuccess = FISCCCreateDueDiligenceExtension.invokeApiCall(partyObj, adapterConfig, charterConfig);
      }
      if (
        partyObj.IsAuthenticatedCustomer__c &&
        partyObj.tffa__IsExistingCustomer__c &&
        (partyObj.IsEmailIdMissing__c || partyObj.IsPhoneNumberMissing__c)
      ) {
        boolean dueDiligencefailed = false;
        if (!partySuccess) {
          dueDiligencefailed = true;
        }
        if (!isIntegrationLogSet) {
          FISCCIntegrationLogService.setCurrentLog(FISCCIntegrationConstants.UPDATED_CUSTOMER_INFORMATION_FLOW);
          isIntegrationLogSet = true;
        }
        partySuccess = FISCCDepositOriginationProvider.updateCustomerInformation(partyObj);
        if (dueDiligencefailed) {
          partySuccess = false;
        }
      }

      if (!partySuccess) {
        isSuccess = false;
      }
    }
    if (isIntegrationLogSet) {
      if (isSuccess) {
        FISCCIntegrationLogService.setLogOk(FISCCIntegrationConstants.UPDATED_CUSTOMER_INFORMATION_COMPLETED);
      } else {
        FISCCIntegrationLogService.setLogFailed(FISCCIntegrationConstants.UPDATED_CUSTOMER_INFORMATION_FAILURE);
      }
    }
    return isSuccess;
  }
}