objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

objects/FundingAccountDetails__mdt.object
<CustomObject>
    <description>It contains account details for different funding types</description>
    <fields>
        <fullName>BrandCode__c</fullName>
        <description>Brand Code</description>
        <label>BrandCode</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BrandName__c</fullName>
        <description>Brand Name</description>
        <label>Brand Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLAccountNumber__c</fullName>
        <description>GL Account Number</description>
        <label>GLAccountNumber</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GLCostCenter__c</fullName>
        <description>GL Cost Center</description>
        <label>GLCostCenter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TransactionCode__c</fullName>
        <description>Transaction Code</description>
        <label>Transaction Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TransactionType__c</fullName>
        <description>Transaction Type</description>
        <label>Transaction Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Funding Account Details</label>
    <pluralLabel>FundingAccountDetails</pluralLabel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The final generated account number. This will be set only after the final account number is available as part of the response of an account open API call.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Amount__c</fullName>
        <description>Total certificate amount captured for the certificate application</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>tffa__Brand__c</fullName>
        <description>Brand code of the Brand for the submission if applicable</description>
        <formula>tffa__Submission__r.tffa__Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand Code</label>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__FundingRequest__c.object
<CustomObject>
    <description>Supports the capture of details pertaining to funding a payment obligation using one of the various available sources of funding</description>
    <fields>
        <fullName>CZSourceAccountBrand__c</fullName>
        <description>Source Account Brand for Internal Transfer</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Source Account Brand for Internal Transfer.</inlineHelpText>
        <label>Source Account Brand</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The account number which needs to be debited for this funding request</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Amount__c</fullName>
        <description>The amount of funds which this funding request denotes.</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>tffa__LinkedApplication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to application.</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Funding Requests</relationshipLabel>
        <relationshipName>LinkedFundingRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__TraceNumber__c</fullName>
        <description>A unique number assigned to every ACH entry by an Originating Depository Financial Institution which identifies that entry within a specific ACH file. The first 8 digits of the trace number are the transit/routing number of the ODFI and the last 7 digits are sequence numbers assigned by the originator.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Trace Number</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <label>Funding Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WintrustEnvConfig__mdt.object
<CustomObject>
    <description>It contains Wintrust Configurations</description>
    <fields>
        <fullName>FISDLRTransErrorCode__c</fullName>
        <description>FIS Dollar Transaction Error Codes</description>
        <label>FIS Dollar Transaction Error Codes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Wintrust Env Config</label>
    <pluralLabel>Wintrust Env Config</pluralLabel>
</CustomObject>

classes/FISCCDollarTransactionExtension.cls
public with sharing class FISCCDollarTransactionExtension {
  @TestVisible
  private static boolean testConfigFlow = false;
  private static WintrustEnvConfig__mdt wintrustEnvConfig = CZWTFCHelperRepository.fetchWintrustEnvConfig();
  public static Boolean invokeApiCall(
    tffa__Application__c appObj,
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig,
    String reqType
  ) {
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    Object result = null;
    Boolean isSuccess;
    FISCCDollarTransResponseDTO respDTO;
    Boolean isFisProcessIssue = false;
    Boolean containsFisErrorCode = false;
    Integer counter = 0;
    String DPOverrideCode = null;
    Integer txnInd = 0;
    Boolean processDlrTrans = true;
    try {
      String fisErrorCode = wintrustEnvConfig.FISDLRTransErrorCode__c;
      List<String> fisErrorCodeList = fisErrorCode != null ? fisErrorCode.split(',') : new List<String>();

      while (processDlrTrans) {
        fisccRequestBaseDTO = FISCCDollarTransactionExtension.generateRequest(appObj, reqType, DPOverrideCode, txnInd);
        result = FISCCHostAdapter.processHostRequest(fisccRequestBaseDTO, adapterConfig, charterConfig);
        respDTO = FISCCDollarTransactionExtension.parseDollarTransResponse(result);
        if (respDTO != null) {
          if ((respDTO.Metadata.MsgLst[0].Severity).equalsIgnoreCase('Error')) {
            isSuccess = false;
            isFisProcessIssue = true;
            for (FISCCMsgListDTO msg : respDTO.Metadata.MsgLst) {
              if (fisErrorCodeList.contains(msg.Code)) {
                containsFisErrorCode = true;
              }
            }
          } else {
            isSuccess = true;
          }
        } else {
          isSuccess = false;
        }

        if (
          !isSuccess &&
          !containsFisErrorCode &&
          isFisProcessIssue &&
          respDTO != null &&
          respDTO.entity.depositOnlineDollarTransResp.DPOvrideInfo != null &&
          counter < FISCCIntegrationConstants.DLR_TRANSACTION_RETRY
        ) {
          DPOverrideCode = respDTO.entity.depositOnlineDollarTransResp.DPOvrideInfo;
          if (respDTO.entity.depositOnlineDollarTransResp.TxnSecurityInd != null) {
            txnInd = respDTO.entity.depositOnlineDollarTransResp.TxnSecurityInd;
          }
          counter++;
          processDlrTrans = true;
        } else {
          processDlrTrans = false;
        }
      }
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in FISCCFundingHoldExtension ' + ex.getMessage() + ' Exception :::' + ex.getStackTraceString());
    }
    return isSuccess;
  }

  public static FISCCDODepositOnlineDlrTransDTO generateRequest(
    tffa__Application__c appObject,
    String reqType,
    String dpOverrideCode,
    Integer txnInd
  ) {
    FISCCDODepositOnlineDlrTransDTO requestDto = new FISCCDODepositOnlineDlrTransDTO();
    tffa.Logger.debug('Generate Dollar Transaction Request');
    FundingAccountDetails__mdt fundingAccDetail;
    if (appObject != null) {
      if (Test.isRunningTest() && testConfigFlow) {
        //TODO Jitendra
        fundingAccDetail = FISCCIntegrationLogRepository.findFundingAccDetails(reqType, '118');
      }
      if (!Test.isRunningTest()) {
        if (reqType.equalsIgnoreCase(CZWTFCConstants.INTERNAL_TRANSFER_SOURCE)) {
          fundingAccDetail = FISCCIntegrationLogRepository.findFundingAccDetails(
            reqType,
            appObject.tffa__LinkedFundingRequests__r[0].CZSourceAccountBrand__c
          );
        } else {
          fundingAccDetail = FISCCIntegrationLogRepository.findFundingAccDetails(reqType, appObject.tffa__Brand__c);
        }
      }
      requestDto.depositOnlineDollarTrans.DPAcctNbr = appObject.tffa__AccountNumber__c;
      requestDto.depositOnlineDollarTrans.DPGLAcctNbr = Integer.valueOf(fundingAccDetail.GLAccountNumber__c);
      requestDto.depositOnlineDollarTrans.DPGLCstCntr = Integer.valueOf(fundingAccDetail.GLCostCenter__c);
      requestDto.depositOnlineDollarTrans.DPTxnCde = Integer.valueOf(fundingAccDetail.TransactionCode__c);

      if (reqType.equalsIgnoreCase(CZWTFCConstants.DEBIT_CARD)) {
        requestDto.depositOnlineDollarTrans.DPTxnTrlrDesc1 = CZWTFCConstants.DEBIT_CARD_DESC_ONE;
        requestDto.depositOnlineDollarTrans.DPTxnTrlrDesc2 = appObject.tffa__LinkedFundingRequests__r[0].tffa__TraceNumber__c;
      } else if (
        reqType.equalsIgnoreCase(CZWTFCConstants.INTERNAL_TRANSFER_SOURCE) || reqType.equalsIgnoreCase(CZWTFCConstants.INTERNAL_TRANSFER_CD)
      ) {
        FundingAccountDetails__mdt fundingAccDest = FISCCIntegrationLogRepository.findFundingAccDetails(
          CZWTFCConstants.INTERNAL_TRANSFER_DESTINATION,
          appObject.tffa__Brand__c
        );
        requestDto.depositOnlineDollarTrans.DPAcctNbr = appObject.tffa__LinkedFundingRequests__r[0].tffa__AccountNumber__c;
        String desc1 = 'To ' + fundingAccDest.BrandName__c;
        requestDto.depositOnlineDollarTrans.DPTxnTrlrDesc1 = desc1.length() > 18 ? desc1.substring(0, 17) : desc1;
        requestDto.depositOnlineDollarTrans.DPTxnTrlrDesc2 = maskString(appObject.tffa__AccountNumber__c);
        requestDto.depositOnlineDollarTrans.DPTxnTrlrDesc3 = fundingAccDest.BrandCode__c;
        if (reqType.equalsIgnoreCase(CZWTFCConstants.INTERNAL_TRANSFER_CD)) {
          requestDto.depositOnlineDollarTrans.DPTxnTrlrDesc1 = CZWTFCConstants.CD_SAME_CHARTER_DESC;
          requestDto.depositOnlineDollarTrans.DPTxnTrlrDesc3 = '';
        }
      } else if (reqType.equalsIgnoreCase(CZWTFCConstants.INTERNAL_TRANSFER_DESTINATION)) {
        FundingAccountDetails__mdt fundingAccSource = FISCCIntegrationLogRepository.findFundingAccDetails(
          CZWTFCConstants.INTERNAL_TRANSFER_SOURCE,
          appObject.tffa__LinkedFundingRequests__r[0].CZSourceAccountBrand__c
        );
        String desc1 = 'From ' + fundingAccSource.BrandName__c;
        requestDto.depositOnlineDollarTrans.DPTxnTrlrDesc1 = desc1.length() > 18 ? desc1.substring(0, 17) : desc1;
        requestDto.depositOnlineDollarTrans.DPTxnTrlrDesc2 = maskString(appObject.tffa__LinkedFundingRequests__r[0].tffa__AccountNumber__c);
        requestDto.depositOnlineDollarTrans.DPTxnTrlrDesc3 = fundingAccSource.BrandCode__c;
      } else if (reqType == CZWTFCConstants.FUNDING_TYPE_ACH) {
        requestDto.depositOnlineDollarTrans.DPTxnTrlrDesc1 = CZWTFCConstants.ACH_FUND_DESC_ONE;
        requestDto.depositOnlineDollarTrans.DPTxnTrlrDesc2 = maskString(appObject.tffa__LinkedFundingRequests__r[0].tffa__AccountNumber__c);
      }

      requestDto.depositOnlineDollarTrans.DPLogTyp = FISCCIntegrationConstants.DPLogTyp;
      requestDto.depositOnlineDollarTrans.DPDolrTxnAmt = appObject.tffa__LinkedFundingRequests__r[0].tffa__Amount__c;

      if (fundingAccDetail.TransactionType__c == 'CREDIT') {
        requestDto.depositOnlineDollarTrans.AutoOvrideInd = '3';
      } else if (fundingAccDetail.TransactionType__c == 'DEBIT' && dpOverrideCode != null) {
        requestDto.depositOnlineDollarTrans.DPOvrideInfo = dpOverrideCode;
        if (txnInd != 0) {
          requestDto.depositOnlineDollarTrans.TxnSecurityInd = String.valueOf(txnInd);
        } else {
          requestDto.depositOnlineDollarTrans.TxnSecurityInd = '2';
        }
      }
    }
    return requestDto;
  }

  public static FISCCDollarTransResponseDTO parseDollarTransResponse(Object response) {
    tffa.Logger.debug('parseDollarTransResponse----> ' + response);
    try {
      if (response instanceof FISCCDollarTransResponseDTO) {
        FISCCDollarTransResponseDTO fundResp = (FISCCDollarTransResponseDTO) response;
        return fundResp;
      } else {
        return null;
      }
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in parseDollarTransResponse ' + ex.getMessage() + ' Exception :::' + ex.getStackTraceString());
      return null;
    }
  }

  public static String maskString(String value) {
    try {
      if (value.length() > 4) {
        String valueToMask = value.substring(0, value.length() - 4);
        String mask = 'X'.repeat(valueToMask.length());
        String masked = value.replaceFirst(valueToMask, mask);
        return masked;
      }
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in maskString ' + ex.getMessage() + ' Exception :::' + ex.getStackTraceString());
    }
    return value;
  }
}