objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <fields>
        <fullName>ServiceURL__c</fullName>
        <description>This contains base url for API</description>
        <label>ServiceURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/FISCC_Charter_Config__mdt.object
<CustomObject>
    <description>Metadata for all the configs related to FISCC_Charter_Config</description>
    <fields>
        <fullName>ServiceURL__c</fullName>
        <description>It contains named credential having base url only</description>
        <label>ServiceURL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>FISCC_Charter_Config</label>
    <pluralLabel>FISCC_Charter_Config</pluralLabel>
</CustomObject>

classes/CZWTFCOfficerDetailsExtension.cls
public with sharing class CZWTFCOfficerDetailsExtension {
  public static CZWTFCOfficerDetailsResponse invokeOfficeDetails(
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    CZWTFCOfficerDetailsResponse response;
    CZWTFCOfficerDetailsResponse finalResponse = new CZWTFCOfficerDetailsResponse();

    Object result = null;
    String moreInd = 'Y';
    String reqStartKey = null;
    try {
      while (moreInd.equals('Y')) {
        FISCC_Adapter_Configs__mdt adapterConfigInput = adapterConfig.clone(false, true);

        adapterConfigInput.ServiceURL__c = adapterConfig.ServiceURL__c + '?ReqCde=R&MaxNbrRtes=9999&MaxNbrTiers=9999';

        if (reqStartKey != null) {
          adapterConfigInput.ServiceURL__c += '&StrtOfcrNbr=' + reqStartKey;
        }

        result = FISCCHostAdapter.processHostRequest(null, adapterConfigInput, charterConfig);
        tffa.logger.debug('CZWTFCOfficerDetailsExtension : invokeOfficeDetail result ==>' + result);
        response = isFISCCAPICallSuccess(result);
        tffa.logger.debug('CZWTFCOfficerDetailsExtension : response ==>' + response);
        if (response != null) {
          moreInd = response.controlData.MoreInd;
          reqStartKey = response.controlData.StrtOfcrNbr;
          finalResponse.controlData = response.controlData;
          finalResponse.officerDetailsLts.addAll(response.officerDetailsLts);
        } else {
          moreInd = 'N';
          finalResponse = null;
        }
      }
    } catch (Exception ex) {
      tffa.Logger.error('Exception in CZWTFCOfficerDetailsExtension.invokeOfficeDetails : ' + ex.getMessage() + ex.getStackTraceString());
    }
    return finalResponse;
  }

  public static CZWTFCOfficerDetailsResponse isFISCCAPICallSuccess(Object response) {
    CZWTFCOfficerDetailsResponse objCZWTFCOfficerDetailsResponse;
    try {
      if (response instanceof CZWTFCOfficerDetailsResponse) {
        objCZWTFCOfficerDetailsResponse = (CZWTFCOfficerDetailsResponse) response;
      }
    } catch (Exception ex) {
      tffa.Logger.debug(
        'Exception in CZWTFCOfficerDetailsExtension.isFISCCAPICallSuccess : ' +
        +ex.getMessage() +
        ' Exception:::' +
        ex.getStackTraceString()
      );
    }
    return objCZWTFCOfficerDetailsResponse;
  }
}