objects/FISCC_Adapter_Configs__mdt.object
<CustomObject>
    <description>It contains header details of respective APIs</description>
    <label>FISCC Adapter Configs</label>
    <pluralLabel>FISCC Adapter Configs</pluralLabel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__IsExistingCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current applicant is existing customer of the bank.</description>
        <label>IsExistingCustomer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyPartyXref__c.object
<CustomObject>
    <description>A relationship between 2 applicants of a submission. 
Personal relationship could be SPOUSE, PARENT, FRIENDS.
Business relationship between a company and an individual could be DIRECTOR, OWNER, EXECUTIVE, PARTNER etc. In additional the ownership percentage can be captured for OWNER type of relationship. 
Relationship between 2 company type applicants can also be captured such as PARENT and SUBSIDIARY.</description>
    <fields>
        <fullName>CZFisRelnshipCreated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to check if FIS Relnship is created</description>
        <label>FIS Relnship Created</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__OwnershipPercentage__c</fullName>
        <description>Percentage ownership of related party in the party (an Organization) in a business ownership type relationship.</description>
        <label>Ownership percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Party managing the relationship</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Related To</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__RelatedParty__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Related party in the relationship</description>
        <label>Related Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Related As</relationshipLabel>
        <relationshipName>RelatedPartyXrefs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__RelationCode__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Captures how Related Party related to Party.</description>
        <inlineHelpText>Captures how Related Party related to Party.</inlineHelpText>
        <label>Relation Code</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Relation code not active.</errorMessage>
            <filterItems>
                <field>tffa__PartyRelationCode__c.tffa__Disabled__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__PartyRelationCode__c</referenceTo>
        <relationshipLabel>Party Party Relationships</relationshipLabel>
        <relationshipName>PartyPartyXrefs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Title__c</fullName>
        <description>The designation of the related party w.r.t to the party (organization). Could be Senior Manager, Director, VP, CIO, CEO etc. Usually captured in addition to the main relationship - Owner, Signer</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Party Party Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Party Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__PartyRelationCode__c.object
<CustomObject>
    <description>Defines possible relationships that can be captured between parties in the system. The relationship that can be captured is dependent on the participating parties (partyType and relatedPartyType) as well as the nature of the relationship (category e.g. PERSONAL, BUSINESS). Note: The code represents how party of type RelatedPartyType is related to party of type PartyType.</description>
    <fields>
        <fullName>tffa__Value__c</fullName>
        <description>The value of the code, that gets stamped on the party to party relationship. This is unique for a code.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Party Relation Code</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Party Relation Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__SubmissionPartyXref__c.object
<CustomObject>
    <description>An individual or a legal entity which is applying for certain services/products in the bank. An applicant exists only in the context of a submission.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to Party object @managed</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission object.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Submission Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

classes/FISCCOrgCustomerRelnExtension.cls
public with sharing class FISCCOrgCustomerRelnExtension {
  public static List<Id> customerToCustomerRelnCreated = new List<Id>();
  public static Id orgOwnerCreated;
  public static boolean invokeBusinessOwnerRelnCall(List<tffa__Party__c> partyObjs, tffa__Submission__c subObj) {
    tffa.Logger.debug('In invokeBusinessOwnerRelnCall');
    boolean isRelnCreationSuccess = false;
    Object result;
    try {
      do {
        customerToCustomerRelnCreated = new List<Id>();

        for (tffa__Party__c partyObj : partyObjs) {
          if (
            partyObj.tffa__Type__c == FISCCIntegrationConstants.ORGANIZATION &&
            !partyObj.CZOwnerRelnCompleted__c &&
            !partyObj.tffa__IsExistingCustomer__c
          ) {
            FISCCIntegrationLogService.setCurrentLogItem(
              FISCCIntegrationConstants.CUST_TO_CUST_CREATION_RELN,
              'Business and Owners Reln',
              true
            );
            FISCC_Adapter_Configs__mdt adapterConfig = FISCCIntegrationLogRepository.findAdapterConfig(
              FISCCIntegrationConstants.CUST_TO_CUST_RELN_ADAPTERCONFIG
            );
            FISCCRequestBaseDTO fisccRequestBaseDTO = null;
            fisccRequestBaseDTO = generateReq(partyObj, subObj);

            result = FISCCHostAdapter.processHostRequest(fisccRequestBaseDTO, adapterConfig, FISCCIntegrationLogService.charterConfig);

            if (parseRelnResponse(result, partyObjs)) {
              FISCCIntegrationLogService.setLogItemOk(FISCCIntegrationConstants.CUST_TO_CUST_CREATION_RELN_SUCCESS);
              isRelnCreationSuccess = true;
            } else {
              FISCCCommonHelper.setErrormessageInSub();
              FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.CUST_TO_CUST_CREATION_RELN_FAILURE);
              isRelnCreationSuccess = false;
              throw new tffa.ApplicationException('Customer to Customer Relationship API Failed.');
            }
            FISCCOrgCustomerRelnExtension.customerToCustomerRelnCreated = new List<Id>();
          }
        }
      } while (!CZWTFCCommonHelper.checkCustToCustRelnCreated(FISCCIntegrationLogService.partyObjMap));
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in invokeCustAccRelnAPI ' + ex.getMessage() + ' Exception :::' + ex.getStackTraceString());
      isRelnCreationSuccess = false;
    }
    return isRelnCreationSuccess;
  }

  public static FISCCRequestBaseDTO generateReq(tffa__Party__c partyObj, tffa__Submission__c subObj) {
    Integer relnAdded = 0;
    tffa.Logger.debug('In FISCCOrgCustomerRelnExtension.generateReq');
    FISCCRequestBaseDTO fisccRequestBaseDTO = null;
    FISCCCustToCustRelnRequestDTO reqDto = new FISCCCustToCustRelnRequestDTO();

    // for (tffa__Party__c partyObj : partyObjs) {
    if (relnAdded < 10) {
      if (partyObj.tffa__PartyXrefs__r != null && !partyObj.tffa__PartyXrefs__r.isEmpty()) {
        reqDto.ccMaintainedCust.CustNbr = partyObj.Customer_Number__c;
        orgOwnerCreated = partyObj.Id;
        for (tffa__PartyPartyXref__c partyPartyObj : partyObj.tffa__PartyXrefs__r) {
          if (!partyPartyObj.CZFisRelnshipCreated__c && relnAdded < 10 && partyPartyObj.tffa__RelationCode__r != null) {
            FISCCCustToCustRelnRequestDTO.CustomerRelnship relnDto = new FISCCCustToCustRelnRequestDTO.CustomerRelnship();

            relnDto.E1toE2Cde = partyPartyObj.tffa__RelationCode__r.tffa__Value__c;
            relnDto.E2toE1Cde = partyPartyObj.tffa__RelationCode__r.CZToRelnCode__c;
            relnDto.RltBeneTitle = partyPartyObj.tffa__Title__c;
            relnDto.RltPercentOwner = partyPartyObj.tffa__OwnershipPercentage__c != null
              ? String.valueOf(partyPartyObj.tffa__OwnershipPercentage__c)
              : null;
            relnDto.RltCustNbr = FISCCIntegrationLogService.partyObjMap.get(partyPartyObj.tffa__RelatedParty__c).Customer_Number__c;
            customerToCustomerRelnCreated.add(partyPartyObj.Id);
            reqDto.customerRelnship.add(relnDto);
            relnAdded++;
          }
        }
      }
    }

    fisccRequestBaseDTO = reqDto;
    return fisccRequestBaseDTO;
  }

  public static boolean parseRelnResponse(Object response, List<tffa__Party__c> partyObjs) {
    tffa.Logger.debug('In parseRelnResponse');
    try {
      if (response instanceof FISCCCustToCustRelnDTO) {
        FISCCCustToCustRelnDTO custToCustResp = (FISCCCustToCustRelnDTO) response;
        tffa.Logger.debug('parseRelnResponse--> ' + custToCustResp);
        for (
          tffa__PartyPartyXref__c partyPartyObj : FISCCIntegrationLogService.partyObjMap.get(FISCCOrgCustomerRelnExtension.orgOwnerCreated)
            .tffa__PartyXrefs__r
        ) {
          if (FISCCOrgCustomerRelnExtension.customerToCustomerRelnCreated.contains(partyPartyObj.Id)) {
            partyPartyObj.CZFisRelnshipCreated__c = true;
          }
        }
        FISCCIntegrationLogService.partyObjMap.get(FISCCOrgCustomerRelnExtension.orgOwnerCreated).CZOwnerRelnCompleted__c = true;
        for (
          tffa__PartyPartyXref__c partyPartyObj : FISCCIntegrationLogService.partyObjMap.get(FISCCOrgCustomerRelnExtension.orgOwnerCreated)
            .tffa__PartyXrefs__r
        ) {
          if (!partyPartyObj.CZFisRelnshipCreated__c) {
            FISCCIntegrationLogService.partyObjMap.get(FISCCOrgCustomerRelnExtension.orgOwnerCreated).CZOwnerRelnCompleted__c = false;
            break;
          }
        }
        return true;
      } else {
        return false;
      }
    } catch (Exception ex) {
      tffa.Logger.error('Exception in parseRelnResponse ' + ex.getMessage() + ' Exception :::' + ex.getStackTraceString());
      return false;
    }
  }
}