objects/IntegrationLog__c.object
<CustomObject>
    <description>IntegrationLog holds the configurable API Flow and status.</description>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IntegrationLogItem__c.object
<CustomObject>
    <description>Integration log items maintained</description>
    <fields>
        <fullName>IntegrationLog__c</fullName>
        <description>Hold the reference of IntegrationLog object</description>
        <label>Integration Log</label>
        <referenceTo>IntegrationLog__c</referenceTo>
        <relationshipLabel>IntegrationLogs</relationshipLabel>
        <relationshipName>IntegrationLogs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Integration Log Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Target Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Log Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__AccountPreference__c.object
<CustomObject>
    <description>List of account preferences/additional services applied along with the application. Example values are ATM_CARD, INTERNET_BANKING, CHECKBOOK</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application</description>
        <inlineHelpText>Master Detail Lookup</inlineHelpText>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Account Preferences</relationshipLabel>
        <relationshipName>AccountPreferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to related party.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Account Preferences</relationshipLabel>
        <relationshipName>AccountPreferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Preference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__AdditionalPreference__c.object
<CustomObject>
    <description>Additional preference usually captured for a party e.g. Online Banking, E-Statements. These are not specific to an application. For ones that are, use Account Preferences.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the party whose preference is being captured.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Additional Preferences</relationshipLabel>
        <relationshipName>AdditionalPreferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Additional Preferences</relationshipLabel>
        <relationshipName>AdditionalPreferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Additional Preference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ApplicationPartyXref__c.object
<CustomObject>
    <description>Each Applicant of the submission can play different roles in the application and the eventual account.</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Beneficiary__c.object
<CustomObject>
    <description>A beneficiary typically refers to someone who is eligible to receive distributions from deposits upon death of primary owner of account. Beneficiary capture typically happens for Certificate Deposits.
Designating a beneficiary not only ensures the CD will not have to go through probate when the applicant dies.</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Beneficiaries</relationshipLabel>
        <relationshipName>Beneficiaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Beneficiary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Beneficiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__FundingRequest__c.object
<CustomObject>
    <description>Supports the capture of details pertaining to funding a payment obligation using one of the various available sources of funding</description>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to parent submission.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Consolidated Funding Requests</relationshipLabel>
        <relationshipName>FundingRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UploadFileHistory__c.object
<CustomObject>
    <description>the file</description>
    <label>Upload File History</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Upload File History</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upload File History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FISCCObjectManagerRepository.cls
public with sharing class FISCCObjectManagerRepository extends tffa.AbstractRepository {
  public static List<tffa__Submission__c> doUpsertSubmission(tffa__Submission__c entity) {
    return doUpsert(new List<tffa__Submission__c>{ entity });
  }
  public static List<tffa__party__c> doUpsertParties(List<tffa__party__c> entities) {
    return doUpsert(entities);
  }
  public static List<IntegrationLog__c> doUpsertIntegrationLogs(List<IntegrationLog__c> entities) {
    return doUpsert(entities);
  }
  public static List<IntegrationLogItem__c> doUpsertIntegrationLogItems(List<IntegrationLogItem__c> entities) {
    return doUpsert(entities);
  }
  public static List<tffa__application__c> doUpsertApplications(List<tffa__application__c> entities) {
    return doUpsert(entities);
  }
  public static List<tffa__Beneficiary__c> doUpsertBeneficiarys(List<tffa__Beneficiary__c> entities) {
    return doUpsert(entities);
  }
  public static List<tffa__FundingRequest__c> doUpsertFundingReq(List<tffa__FundingRequest__c> entities) {
    return doUpsert(entities);
  }
  public static List<tffa__ApplicationPartyXref__c> doApplicationPartyReq(List<tffa__ApplicationPartyXref__c> entities) {
    return doUpsert(entities);
  }
  public static List<tffa__AccountPreference__c> doUpsertAccountPrefObj(List<tffa__AccountPreference__c> entities) {
    return doUpsert(entities);
  }

  public static List<sObject> updateRecords(List<sObject> entities) {
    return doUpsert(entities);
  }
  public static List<tffa__AdditionalPreference__c> doUpsertAdditionalPrefObj(List<tffa__AdditionalPreference__c> entities) {
    return doUpsert(entities);
  }
  public static List<UploadFileHistory__c> doUpsertuploadFileHistoryObj(List<UploadFileHistory__c> entities) {
    return doUpsert(entities);
  }
}