objects/InterestPlanDetails__c.object
<CustomObject>
    <description>Interest Plan Details</description>
    <fields>
        <fullName>APY__c</fullName>
        <description>Annual Percentage Yield</description>
        <label>Annual Percentage Yield</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>InterestRate__c</fullName>
        <description>Interest Rate</description>
        <label>Interest Rate</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>InterestPlanDetails</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>InterestPlanDetails</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>InterestPlanDetails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_BatchAPYProcessor.cls
public class WT_BatchAPYProcessor implements Database.Batchable<sObject>
{
    public Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator([SELECT Id, APY__c, InterestRate__c
                                         FROM InterestPlanDetails__c]);   
    }
    
    public void execute(Database.BatchableContext bc, List<InterestPlanDetails__c> scope)
    {
        for(InterestPlanDetails__c interestPlan : scope)
        {
            if(interestPlan.InterestRate__c != null)
            {
                WT_TerafinaAPYHelper.APYResponseModel apyModel = WT_TerafinaAPYHelper.GetApy((Double)(interestPlan.InterestRate__c/100), (Double)0.0, 'monthly', null, null);
                interestPlan.APY__c = apyModel.APY;
            }
        }
        
        update scope;
    }
    
    public void finish(Database.BatchableContext bc)
    {
    }
}