objects/IntegrationLog__c.object
<CustomObject>
    <description>IntegrationLog holds the configurable API Flow and status.</description>
    <fields>
        <fullName>Submission__c</fullName>
        <description>stores submission id for one flow</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Integration Logs</relationshipLabel>
        <relationshipName>IntegrationLogs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>Log-{000000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/IntegrationLogItem__c.object
<CustomObject>
    <description>Integration log items maintained</description>
    <fields>
        <fullName>IntegrationLog__c</fullName>
        <description>Hold the reference of IntegrationLog object</description>
        <label>Integration Log</label>
        <referenceTo>IntegrationLog__c</referenceTo>
        <relationshipLabel>IntegrationLogs</relationshipLabel>
        <relationshipName>IntegrationLogs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Integration Log Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Target Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Log Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__AdditionalPreference__c.object
<CustomObject>
    <description>Additional preference usually captured for a party e.g. Online Banking, E-Statements. These are not specific to an application. For ones that are, use Account Preferences.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the party whose preference is being captured.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Additional Preferences</relationshipLabel>
        <relationshipName>AdditionalPreferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Additional Preferences</relationshipLabel>
        <relationshipName>AdditionalPreferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Additional Preference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Address__c.object
<CustomObject>
    <description>An address is a collection of information, presented in a mostly fixed format, used to give the location of a building, apartment, or other structure or a plot of land, generally using political boundaries and street names as references,  along with other identifiers such as house or apartment numbers

 For more reference lookup https://en.wikipedia.org/wiki/Address_(geography)#United_States</description>
    <label>Address</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account address for purposes of statement etc. If Address Prefill Source Id is set, the address details are not persisted directly, only address id is persisted.</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ApplicationPartyXref__c.object
<CustomObject>
    <description>Each Applicant of the submission can play different roles in the application and the eventual account.</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Employment__c.object
<CustomObject>
    <description>Captures employment information of the applicant. Employment is a relationship between two parties, usually based on a contract where work is paid for, where one party, which may be a corporation, for profit, not-for-profit organization, co-operative or other entity is the employer and the other is the employee.</description>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employment address</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party object</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Employment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Identification__c.object
<CustomObject>
    <description>Identification details of the party such as  driver license numbers, passport numbers .  Supports capture of identity document id as well which is stored as an attachment in the system.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to the parent party object</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Identifications</relationshipLabel>
        <relationshipName>Identifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Identification</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Identifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyAddressXref__c.object
<CustomObject>
    <description>Association table between Party and Address . This supports capture of multiple types and also periodAtAddress.
This creates an address book of the party</description>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <description>The address lookup @managed</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyAddresses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>The party which owns the address.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>AddressXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Address Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartyAddresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__PartyPartyXref__c.object
<CustomObject>
    <description>A relationship between 2 applicants of a submission. 
Personal relationship could be SPOUSE, PARENT, FRIENDS.
Business relationship between a company and an individual could be DIRECTOR, OWNER, EXECUTIVE, PARTNER etc. In additional the ownership percentage can be captured for OWNER type of relationship. 
Relationship between 2 company type applicants can also be captured such as PARENT and SUBSIDIARY.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Party managing the relationship</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Related To</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Party Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Party Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Stipulation__c.object
<CustomObject>
    <description>During the application process, the lender makes stipulations of the borrower to ensure that they meet the criteria or profile of the loan agreement. For example, things like “Borrower needs to provide 3 months of income history” or “At the time of closing borrow must present 2 forms of identification” are common stipulations lenders put forth. These stipulations could also be added from credit decisioning system. This is fundamentally a lending concept , but we have designed for it to support any kind of products.

The stipulations can be related to the applicants in context of the product applied or could for the applicant irrespective of the product.</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to application object for which current stipulation is raised</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Stipulations</relationshipLabel>
        <relationshipName>Stipulations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to party object for which current stipulation is raised</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Stipulations</relationshipLabel>
        <relationshipName>Stipulations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to submission object for which current stipulation is raised</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Stipulations</relationshipLabel>
        <relationshipName>Stipulations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stipulation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Stipulation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stipulations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__SubmissionPartyXref__c.object
<CustomObject>
    <description>An individual or a legal entity which is applying for certain services/products in the bank. An applicant exists only in the context of a submission.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to Party object @managed</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission object.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submission Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WintrustEnvConfig__mdt.object
<CustomObject>
    <description>It contains Wintrust Configurations</description>
    <fields>
        <fullName>PurgeSubmission__c</fullName>
        <description>Days after which submissions will be deleted</description>
        <label>PurgeSubmission</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Wintrust Env Config</label>
    <pluralLabel>Wintrust Env Config</pluralLabel>
</CustomObject>

classes/CZWTFCPurgeSubmissionHelper.cls
public with sharing class CZWTFCPurgeSubmissionHelper {
  @TestVisible
  private static boolean calledFromTestCls = false;

  public static List<tffa__Submission__c> getPurgeSub() {
    WintrustEnvConfig__mdt wintrustEnvConfig = CZWTFCHelperRepository.fetchWintrustEnvConfig();

    Date currentDate = system.today();
    Integer dateToAdd = Integer.valueOf(wintrustEnvConfig.PurgeSubmission__c) * -1;
    Date updatedDate = currentDate.addDays(dateToAdd); // sub

    List<String> subsToDelete = new List<String>();
    List<String> subIdList = CZWTFCSubmissionRepository.getPurgeSubIds();
    if (Test.isRunningTest() && calledFromTestCls) {
      List<tffa__Submission__c> subTest = CZWTFCSubmissionRepository.findtestSubmission();
      subIdList.add(subTest[0].Id);
    }

    List<tffa__Submission__c> subAppList = new List<tffa__Submission__c>();

    if (subIdList != null && !subIdList.isEmpty()) {
      subAppList = CZWTFCSubmissionRepository.findSubmissionAndAppByIds(subIdList);
      if (subAppList != null && !subAppList.isEmpty()) {
        for (tffa__Submission__c sub : subAppList) {
          boolean canBeDeleted = true;
          if (sub.tffa__Applications__r != null && !sub.tffa__Applications__r.isEmpty()) {
            for (tffa__Application__c app : sub.tffa__Applications__r) {
              if (app.Lastmodifieddate > updatedDate) {
                canBeDeleted = false;
              }
            }
          }
          if (canBeDeleted) {
            subsToDelete.add(sub.Id);
          }
        }
      }
    }

    return CZWTFCSubmissionRepository.findSubmissionForPurge(subsToDelete);
  }

  public static void deletePartyAndItsChildObj(tffa__Submission__c sub) {
    List<IntegrationLog__c> integrationLogList = new List<IntegrationLog__c>();
    List<IntegrationLogItem__c> integrationLogItemList = new List<IntegrationLogItem__c>();
    List<tffa__Party__c> partyList = new List<tffa__Party__c>();
    List<tffa__PartyAddressXref__c> partyAddressList = new List<tffa__PartyAddressXref__c>();
    List<tffa__Address__C> addressList = new List<tffa__Address__C>();
    List<tffa__Identification__c> identificationList = new List<tffa__Identification__c>();
    List<tffa__Employment__c> employemntList = new List<tffa__Employment__c>();
    List<tffa__Stipulation__c> stipulationList = new List<tffa__Stipulation__c>();
    List<tffa__AdditionalPreference__c> additionalPrefList = new List<tffa__AdditionalPreference__c>();

    List<String> partyIdList = new List<String>();

    List<String> idList = new List<String>();
    idList.add(sub.Id);

    if (sub.tffa__PartyXrefs__r != null && !sub.tffa__PartyXrefs__r.isEmpty()) {
      for (tffa__SubmissionPartyXref__c subParty : sub.tffa__PartyXrefs__r) {
        partyIdList.add(subParty.tffa__Party__c);
      }
    }

    integrationLogList = FISCCIntegrationLogRepository.findLogsBySubmissionId(sub.Id);
    if (integrationLogList != null) {
      for (IntegrationLog__c intLog : integrationLogList) {
        if (intLog.IntegrationLogs__r != null) {
          integrationLogItemList.addAll(intLog.IntegrationLogs__r);
        }
      }
    }

    List<tffa__Party__c> partyObjList = FISCCIntegrationLogRepository.findPartydWithChildObjects(partyIdList);

    if (partyObjList != null && !partyObjList.isEmpty()) {
      for (tffa__Party__c partyObj : partyObjList) {
        //partyObj
        partyList.add(partyObj);
        idList.add(partyObj.Id);

        //party address
        if (partyObj.tffa__AddressXrefs__r != null && !partyObj.tffa__AddressXrefs__r.isEmpty()) {
          for (tffa__PartyAddressXref__c partyAdd : partyObj.tffa__AddressXrefs__r) {
            partyAddressList.add(partyAdd);
            if (partyAdd.tffa__Address__r != null) {
              addressList.add(partyAdd.tffa__Address__r);
            }
          }
        }

        //identification
        if (partyObj.tffa__Identifications__r != null && !partyObj.tffa__Identifications__r.isEmpty()) {
          identificationList.addAll(partyObj.tffa__Identifications__r);
        }

        // Employment
        if (partyObj.tffa__Employments__r != null && !partyObj.tffa__Employments__r.isEmpty()) {
          for (tffa__Employment__c emp : partyObj.tffa__Employments__r) {
            employemntList.add(emp);
            if (emp.tffa__Address__r != null) {
              addressList.add(emp.tffa__Address__r);
            }
          }
        }

        List<tffa__Stipulation__c> tempStipulationList = new List<tffa__Stipulation__c>();
        List<tffa__AdditionalPreference__c> tempAdditionalPrefList = new List<tffa__AdditionalPreference__c>();

        //stipulation  find
        tempStipulationList = CZWTFCHelperRepository.findStipByParty(partyObj.Id);
        stipulationList.addAll(tempStipulationList);

        //additional Pref
        tempAdditionalPrefList = CZWTFCHelperRepository.findAdditionalPrefByParty(partyObj.Id);
        additionalPrefList.addAll(tempAdditionalPrefList);
      }
    }

    if (integrationLogItemList != null && !integrationLogItemList.isEmpty()) {
      CZWTFCHelperRepository.removeIntegrationItemLogs(integrationLogItemList);
    }
    if (integrationLogList != null && !integrationLogList.isEmpty()) {
      CZWTFCHelperRepository.removeIntegrationLogs(integrationLogList);
    }
    if (partyAddressList != null && !partyAddressList.isEmpty()) {
      CZWTFCHelperRepository.removePartyAddress(partyAddressList);
    }
    if (employemntList != null && !employemntList.isEmpty()) {
      CZWTFCHelperRepository.removeEmployment(employemntList);
    }
    if (stipulationList != null && !stipulationList.isEmpty()) {
      CZWTFCHelperRepository.removeStip(stipulationList);
    }
    if (additionalPrefList != null && !additionalPrefList.isEmpty()) {
      CZWTFCHelperRepository.removeAddPref(additionalPrefList);
    }
    if (identificationList != null && !identificationList.isEmpty()) {
      CZWTFCHelperRepository.removeIdentification(identificationList);
    }
    if (addressList != null && !addressList.isEmpty()) {
      CZWTFCHelperRepository.removeAddress(addressList);
    }
    if (partyList != null && !partyList.isEmpty()) {
      CZWTFCHelperRepository.removeParty(partyList);
    }
    CZWTFCSubmissionRepository.remove(new List<tffa__Submission__c>{ sub });

    List<String> cdIdList = CZWTFCHelperRepository.fetchContentDocumentId(idList);

    if (cdIdList != null && !cdIdList.isEmpty()) {
      CZWTFCHelperRepository.deleteContentDocumentById(cdIdList);
    }
  }
}