objects/InterestPlanDetails__c.object
<CustomObject>
    <description>Interest Plan Details</description>
    <fields>
        <fullName>BrandCode__c</fullName>
        <description>Brand Code</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntBasisDays__c</fullName>
        <description>Interest Basis Days</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Interest Basis Days</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntCalcMeths__c</fullName>
        <description>Interest Calculation Methods</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Interest Calculation Methods</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntPlnCde__c</fullName>
        <description>Interest Plan Code</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Interest Plan Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntPmtMthd__c</fullName>
        <description>Interest Payment Method</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Interest Payment Method</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>InterestRate__c</fullName>
        <description>Interest Rate</description>
        <label>Interest Rate</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Interest Plan Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Interest Plan Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RteSchedInd__c</fullName>
        <description>Rate Schedule Indicator</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Rate Schedule Indicator</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TDFreqId__c</fullName>
        <description>Time Deposit Frequency ID</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Time Deposit Frequency ID</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TDMatTerm__c</fullName>
        <description>Time Deposit Maturity Term</description>
        <label>Time Deposit Maturity Term</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TDTermId__c</fullName>
        <description>Time Deposit Maturity Term ID</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Time Deposit Maturity Term ID</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TierMaxBal__c</fullName>
        <description>Tier Maximum Balance</description>
        <label>Tier Maximum Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TierMinBal__c</fullName>
        <description>Tier Minimum Balance</description>
        <label>Tier Minimum Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>InterestPlanDetails</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>InterestPlanDetails</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>InterestPlanDetails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>Unique code for the brand</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/GetInterestRatesBatch.cls
global inherited sharing class GetInterestRatesBatch extends tffa.AbstractBatchJob implements Database.Batchable<sObject>, Database.AllowsCallouts {
  private List<String> param = new List<String>{};

  public Database.QueryLocator start(Database.BatchableContext bc) {
    tffa.Logger.debug('GetInterestRatesBatch.start: Start Datetime : ' + String.valueOf(Datetime.now()));
    tffa.Logger.flush();
    return Database.getQueryLocator(getQuery());
  }

  public void execute(Database.BatchableContext bc, List<SObject> brandsLst) {
    tffa.Interaction.begin(GetInterestRatesBatch.class, 'execute');
    try{
      Set<String> intPlanCodeSet = CZWTFCHelperRepository.fetchUniqueInterestPlanCodes();
      for (tffa__Brand__c brand : (List<tffa__Brand__c>) brandsLst) {
        tffa.logger.debug('GetInterestRatesBatch: Executing for brand code: ' + brand.tffa__Code__c);
        FISCCGetInterestRatesResponse response = FISCCGetInterestRatesProvider.getInterestRates(brand.tffa__Code__c);
        List<sObject> intPlanDtlsLst = new List<InterestPlanDetails__c>();
        List<String> usedIntPlanDtlsLst = new List<String>();
        if (response != null) {
          for (String intPlanCode : intPlanCodeSet) {
            FISCCInvestmentRateSchedulesDTO investmentRateSchedule = response.investmentRateSchedulesMap.get(intPlanCode);
            if (investmentRateSchedule != null) {
              if ('N'.equals(investmentRateSchedule.RteSchedInd)) {
                //Non-tiered
                InterestPlanDetails__c intPlanDtls = getNonTieredInterestPlanDetails(brand.tffa__Code__c, investmentRateSchedule);
                usedIntPlanDtlsLst.add(intPlanDtls.IntPlnCde__c + ':' + CZWTFCConstants.NON_TIERED + ':' + CZWTFCConstants.NON_TIERED);
                intPlanDtlsLst.add(intPlanDtls);
              } else {
                //Tiered
                for (FISCCInvestmentRateTiersDTO invRateTier : response.investmentRateTiersMap.get(intPlanCode)) {
                  InterestPlanDetails__c intPlanDtls = getTieredInterestPlanDetails(brand.tffa__Code__c, investmentRateSchedule, invRateTier);
                  usedIntPlanDtlsLst.add(
                    intPlanDtls.IntPlnCde__c +
                    ':' +
                    String.valueOf(intPlanDtls.TierMinBal__c.setScale(2)) +
                    ':' +
                    String.valueOf(intPlanDtls.TierMaxBal__c.setScale(2))
                  );
                  intPlanDtlsLst.add(intPlanDtls);
                }
              }
            }
          }
          WTFCObjectManagerRepository.doUpsertObjects(intPlanDtlsLst);
          CZWTFCHelperRepository.deleteUnusedInterestPlanDetails(brand.tffa__Code__c, usedIntPlanDtlsLst);
        }
      }
    } catch (Exception ex) {
      tffa.Logger.error('Exception in execute passBatch' + ex.getStackTraceString());
    } finally {
      tffa.Interaction.close();
    }
  }

  public void finish(Database.BatchableContext bc) {
    tffa.Logger.flush();
  }

  private static String getQuery() {
    String query = new tffa.QueryBuilder(tffa__Brand__c.SObjectType).selectFields(new List<String>{ 'tffa__Code__c' }).build().toQuery();

    tffa.Logger.debug(query);
    return query;
  }

  public static InterestPlanDetails__c getNonTieredInterestPlanDetails(
    String brandCode,
    FISCCInvestmentRateSchedulesDTO investmentRateSchedule
  ) {
    InterestPlanDetails__c intPlanDtls = CZWTFCHelperRepository.getIntPlanDtlsNonTiered(
      brandCode,
      investmentRateSchedule.IntPlnCde,
      investmentRateSchedule.RteSchedInd
    );
    if (intPlanDtls == null) {
      intPlanDtls = new InterestPlanDetails__c();
    }
    intPlanDtls.BrandCode__c = brandCode;
    intPlanDtls.IntPlnCde__c = investmentRateSchedule.IntPlnCde;
    intPlanDtls.IntPmtMthd__c = investmentRateSchedule.IntPmtMthd;
    intPlanDtls.Name__c = investmentRateSchedule.Nme;
    intPlanDtls.IntBasisDays__c = investmentRateSchedule.IntBasisDays;
    intPlanDtls.TDFreqId__c = investmentRateSchedule.TDFreqId;
    intPlanDtls.TDMatTerm__c = investmentRateSchedule.TDMatTerm;
    intPlanDtls.TDTermId__c = investmentRateSchedule.TDTermId;
    intPlanDtls.IntCalcMeths__c = investmentRateSchedule.IntCalcMeths;
    intPlanDtls.RteSchedInd__c = investmentRateSchedule.RteSchedInd;
    intPlanDtls.InterestRate__c = investmentRateSchedule.IntStateRte;
    return intPlanDtls;
  }

  public static InterestPlanDetails__c getTieredInterestPlanDetails(
    String brandCode,
    FISCCInvestmentRateSchedulesDTO investmentRateSchedule,
    FISCCInvestmentRateTiersDTO invRateTier
  ) {
    InterestPlanDetails__c intPlanDtls = CZWTFCHelperRepository.getIntPlanDtlsTiered(
      brandCode,
      investmentRateSchedule.IntPlnCde,
      investmentRateSchedule.RteSchedInd,
      invRateTier.TierMinBal,
      invRateTier.TierMaxBal
    );
    if (intPlanDtls == null) {
      intPlanDtls = new InterestPlanDetails__c();
    }
    intPlanDtls.BrandCode__c = brandCode;
    intPlanDtls.IntPlnCde__c = investmentRateSchedule.IntPlnCde;
    intPlanDtls.IntPmtMthd__c = investmentRateSchedule.IntPmtMthd;
    intPlanDtls.Name__c = investmentRateSchedule.Nme;
    intPlanDtls.IntBasisDays__c = investmentRateSchedule.IntBasisDays;
    intPlanDtls.TDFreqId__c = investmentRateSchedule.TDFreqId;
    intPlanDtls.TDMatTerm__c = investmentRateSchedule.TDMatTerm;
    intPlanDtls.TDTermId__c = investmentRateSchedule.TDTermId;
    intPlanDtls.IntCalcMeths__c = investmentRateSchedule.IntCalcMeths;
    intPlanDtls.RteSchedInd__c = investmentRateSchedule.RteSchedInd;
    intPlanDtls.TierMinBal__c = invRateTier.TierMinBal;
    intPlanDtls.TierMaxBal__c = invRateTier.TierMaxBal;
    intPlanDtls.InterestRate__c = invRateTier.TierRte;
    return intPlanDtls;
  }
}