objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>WT_Date_Unpublished__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Unpublished</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WT_Knowledge_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Knowledge Category</label>
        <referenceTo>WT_Knowledge_Category__c</referenceTo>
        <relationshipLabel>Knowledge</relationshipLabel>
        <relationshipName>Knowledge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Question__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Question</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

objects/WT_Knowledge_Category__c.object
<CustomObject>
    <fields>
        <fullName>WT_Category_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Category Title</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>WT_Date_Published__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Published</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WT_Date_Unpublished__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Unpublished</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WT_Sub_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sub-Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Knowledge Category</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Knowledge Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knowledge Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_FAQArticleCategoryController.cls
public class WT_FAQArticleCategoryController 
{
    @AuraEnabled 
    public static ArticleCategoryResponseModel GetListArticleInArticleCategory(String articleCategoryId, List<Id> listExistingArticleId, Boolean isFirstRequest)
    {
        ArticleCategoryResponseModel responseModel = new ArticleCategoryResponseModel();
        List<ArticleModel> listArticle = new List<ArticleModel>();
        DateTime now = System.now();
        Boolean isSandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
        responseModel.IsSandbox = isSandbox;
        responseModel.HasMoreResults = false;
        Map<Id, ArticleModel> mapKnowledgeArticleIdAndArticleModel = new Map<Id, ArticleModel>();
        Map<Id, Id> mapKnowledgeArticleIdAndKnowledgeArticleVersionId = new Map<Id, Id>();
        if(listExistingArticleId == null)
        {
            listExistingArticleId = new List<Id>();
        }
        
        //Get the list of Knowledge Article Versions that are Published and match the Category
        //From them query KnowledgeArticleViewStat object using the master Knowledge Article Id to get the view stat for each article so it can be ordered correctly
        for(Knowledge__kav article : [SELECT Id,
                                      Title,
                                      WT_Question__c,
                                      UrlName,
                                      WT_Knowledge_Category__r.WT_Category_Title__c,
                                      //WT_Knowledge_Category__r.WT_Sub_Title__c,
                                      KnowledgeArticleId,
                                      WT_Knowledge_Category__r.Name
                                      FROM Knowledge__kav
                                      WHERE WT_Knowledge_Category__c = :articleCategoryId
                                      AND PublishStatus = 'Online'
                                      AND (WT_Knowledge_Category__r.WT_Date_Published__c <= :now AND
                                           (WT_Knowledge_Category__r.WT_Date_Unpublished__c = NULL OR WT_Knowledge_Category__r.WT_Date_Unpublished__c > :now))
                                      AND Id NOT IN :listExistingArticleId
                                      LIMIT 10000])
        {
            mapKnowledgeArticleIdAndKnowledgeArticleVersionId.put(article.KnowledgeArticleId, article.Id);
            mapKnowledgeArticleIdAndArticleModel.put(article.KnowledgeArticleId, new ArticleModel(article.WT_Question__c, article.Title, article.UrlName, article.WT_Knowledge_Category__r.Name, isSandbox));
            responseModel.Title = article.WT_Knowledge_Category__r.WT_Category_Title__c;
            //responseModel.SubTitle = article.WT_Knowledge_Category__r.WT_Sub_Title__c;
        }
        
        if(!mapKnowledgeArticleIdAndArticleModel.isEmpty())
        {
            Integer maxResultCount = 10;
            if(isFirstRequest)
            {
                maxResultCount = 6;
            }
            Integer iterationCount = 0;
            for(KnowledgeArticleViewStat articleViewStat : [SELECT Id,
                                                            ViewCount,
                                                            Channel,
                                                            ParentId,
                                                            NormalizedScore
                                                            FROM KnowledgeArticleViewStat
                                                            WHERE Channel = 'Pkb'
                                                            AND ParentId IN :mapKnowledgeArticleIdAndArticleModel.keySet()
                                                            ORDER BY NormalizedScore DESC])
            {
                if(iterationCount < maxResultCount)
                {
                    listArticle.add(mapKnowledgeArticleIdAndArticleModel.get(articleViewStat.ParentId));
                    listExistingArticleId.add(mapKnowledgeArticleIdAndKnowledgeArticleVersionId.get(articleViewStat.ParentId));
                }
                else
                {
                    responseModel.HasMoreResults = true;
                    break;
                }
                iterationCount++;
            }
        }
        
        responseModel.ListArticle = listArticle;
        responseModel.IsSuccess = true;
        responseModel.ListExistingArticleId = listExistingArticleId;
        
        return responseModel;
    }
    
    public class ArticleCategoryResponseModel
    {
        @AuraEnabled public String Title;
        @AuraEnabled public String SubTitle;
        @AuraEnabled public Boolean IsSuccess;
        @AuraEnabled public Boolean IsSandbox;
        @AuraEnabled public Boolean HasMoreResults;
        @AuraEnabled public List<ArticleModel> ListArticle;
        @AuraEnabled public List<Id> ListExistingArticleId;
    }
    
    public class ArticleModel
    {
        @AuraEnabled public String ArticleQuestion;
        @AuraEnabled public String ArticleTitle;
        @AuraEnabled public String ArticleUrl;
        @AuraEnabled public String ArticleRedirectUrl;
        
        public ArticleModel(String question, String title, String url, String articleCategoryName, Boolean isSandbox)
        {
            this.ArticleQuestion = (String.isNotBlank(question)) ? question.unescapeHtml4() : '';
            this.ArticleTitle = title;
            this.ArticleUrl = url;
            if(isSandbox)
            {
                this.ArticleRedirectUrl = '/s/article/' + url + '?categoryName=' + articleCategoryName.replace('&', '~');
            }
            else
            {
             	this.ArticleRedirectUrl = '/s/article/' + url + '?categoryName=' + articleCategoryName.replace('&', '~');  
            }
        }
    }
}