objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>WT_Answer__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>WT_Date_Unpublished__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Unpublished</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WT_Disclaimer__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Disclaimer</label>
        <length>130000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>WT_Knowledge_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Knowledge Category</label>
        <referenceTo>WT_Knowledge_Category__c</referenceTo>
        <relationshipLabel>Knowledge</relationshipLabel>
        <relationshipName>Knowledge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Question__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Question</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

objects/WT_Knowledge_Category__c.object
<CustomObject>
    <fields>
        <fullName>WT_Category_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Category Title</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>WT_Date_Published__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Published</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WT_Date_Unpublished__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Unpublished</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WT_Sub_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sub-Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Knowledge Category</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Knowledge Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knowledge Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WT_Knowledge_Search_Log__c.object
<CustomObject>
    <fields>
        <fullName>WT_Knowledge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Knowledge</label>
        <referenceTo>Knowledge__kav</referenceTo>
        <relationshipLabel>Knowledge Search Logs</relationshipLabel>
        <relationshipName>Knowledge_Search_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Search_Term__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Search Term</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Knowledge Search Log</label>
    <nameField>
        <displayFormat>KSL-{00000000}</displayFormat>
        <label>Knowledge Search Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Knowledge Search Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WT_Knowledge_Vote__c.object
<CustomObject>
    <fields>
        <fullName>WT_Knowledge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Knowledge</label>
        <referenceTo>Knowledge__kav</referenceTo>
        <relationshipLabel>Knowledge Votes</relationshipLabel>
        <relationshipName>Knowledge_Votes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Down</fullName>
                </value>
                <value>
                    <fullName>Up</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Knowledge Vote</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Knowledge Vote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knowledge Votes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_FAQArticleController.cls
public class WT_FAQArticleController 
{
    @AuraEnabled 
    public static ArticleResponseModel GetArticle(String articleName, String searchTerm)
    {
        ArticleResponseModel responseModel = new ArticleResponseModel();
        DateTime now = System.now();
        
        Boolean isSandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
        responseModel.IsSandbox = isSandbox;
        
        for(Knowledge__kav article : [SELECT Id,
                                      Title,
                                      WT_Question__c,
                                      UrlName,
                                      WT_Answer__c,
                                      WT_Knowledge_Category__r.WT_Category_Title__c,
                                      //WT_Knowledge_Category__r.WT_Sub_Title__c,
                                      WT_Disclaimer__c
                                      FROM Knowledge__kav
                                      WHERE UrlName = :articleName
                                      AND PublishStatus = 'Online'
                                      AND (WT_Knowledge_Category__r.WT_Date_Published__c <= :now AND
                                           (WT_Knowledge_Category__r.WT_Date_Unpublished__c = NULL OR WT_Knowledge_Category__r.WT_Date_Unpublished__c > :now))
                                      UPDATE VIEWSTAT])
        {
            responseModel.ArticleQuestion = article.WT_Question__c;
            responseModel.ArticleAnswer = article.WT_Answer__c;
            if(String.isNotBlank(article.WT_Disclaimer__c))
            {
                responseModel.HasDisclaimer = true;
                responseModel.ArticleDisclaimer = article.WT_Disclaimer__c;
            }
            else
            {
                responseModel.HasDisclaimer = false;    
            }
            
            if(String.isNotBlank(searchTerm))
            {
                LogSearchArticleFuture(article.Id, searchTerm);
            }
        }
        responseModel.IsSuccess = true;
        
        return responseModel;
    }
    
    @AuraEnabled 
    public static ArticleRatingResponseModel RateArticle(String articleName, Boolean isLike)
    {
        ArticleRatingResponseModel responseModel = new ArticleRatingResponseModel();
        responseModel.IsSuccess = false;
        DateTime now = System.now();
        WT_Knowledge_Vote__c voteRecord = null;
        
        for(Knowledge__kav article : [SELECT Id,
                                      KnowledgeArticleId
                                      FROM Knowledge__kav
                                      WHERE UrlName = :articleName
                                      AND PublishStatus = 'Online'
                                      AND (WT_Knowledge_Category__r.WT_Date_Published__c <= :now AND
                                           (WT_Knowledge_Category__r.WT_Date_Unpublished__c = NULL OR WT_Knowledge_Category__r.WT_Date_Unpublished__c > :now))
                                      LIMIT 1])
        {
            voteRecord = new WT_Knowledge_Vote__c();
            voteRecord.WT_Knowledge__c = article.Id;
            voteRecord.WT_Type__c = (isLike) ? 'Up' : 'Down';
        }
        
        if(voteRecord != null)
        {
            try
            {
                insert voteRecord;
                responseModel.IsSuccess = true;
            }
            catch(Exception ex)
            {
                responseModel.Message = ex.getMessage();
            }
        }
        
        return responseModel;
    }
    
    @Future
    public static void LogSearchArticleFuture(Id articleId, String searchTerm)
    {
        if(articleId != null)
        {
            WT_Knowledge_Search_Log__c newSearchLog = new WT_Knowledge_Search_Log__c();
            newSearchLog.WT_Search_Term__c = searchTerm;
            newSearchLog.WT_Knowledge__c = articleId;
            
            try
            {
                insert newSearchLog;
            }
            catch(Exception ex)
            {
                System.debug('ex: ' + ex.getMessage());
            }
        }
    }
    
    public class ArticleRatingResponseModel
    {
        @AuraEnabled public Boolean IsSuccess;
        @AuraEnabled public String Message;
    }
    
    public class ArticleResponseModel
    {
        @AuraEnabled public String ArticleQuestion;
        @AuraEnabled public String ArticleAnswer;
        @AuraEnabled public String ArticleDisclaimer;
        @AuraEnabled public Boolean HasDisclaimer;
        @AuraEnabled public Boolean IsSuccess;
        @AuraEnabled public Boolean IsSandbox;
    }
}