objects/Knowledge__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>WT_Answer__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Answer</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>WT_Knowledge_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Knowledge Category</label>
        <referenceTo>WT_Knowledge_Category__c</referenceTo>
        <relationshipLabel>Knowledge</relationshipLabel>
        <relationshipName>Knowledge</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Question__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Question</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

objects/WT_Knowledge_Category__c.object
<CustomObject>
    <fields>
        <fullName>WT_Date_Published__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Published</label>
        <type>DateTime</type>
    </fields>
    <label>Knowledge Category</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Knowledge Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knowledge Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_FAQHomeController_T.cls
@isTest
public class WT_FAQHomeController_T 
{
    @testSetup
    static void Setup()
    {
        WT_Knowledge_Category__c knowledgeCategory = new WT_Knowledge_Category__c();
        knowledgeCategory.Name = 'Test';
        knowledgeCategory.WT_Date_Published__c = System.now().addDays(-1);
        
        insert knowledgeCategory;
        
        Knowledge__kav newArticle = new Knowledge__kav();
        newArticle.WT_Question__c = 'Test Question';
        newArticle.WT_Answer__c = 'Test Answer';
        newArticle.IsVisibleInPkb = true;
        newArticle.Title = 'Test Title';
        newArticle.UrlName = 'test-article';
        newArticle.WT_Knowledge_Category__c = knowledgeCategory.Id;
        insert newArticle;
    }
	
    @isTest
    static void TestGetFaqCategories()
    {
        Test.startTest();        
        Knowledge__kav newArticle = [SELECT Id,
                                     UrlName,
                                     WT_Knowledge_Category__c,
                                     KnowledgeArticleId
                                     FROM Knowledge__kav
                                     LIMIT 1];
        
        KbManagement.PublishingService.publishArticle(newArticle.KnowledgeArticleId, true);   
        WT_FAQHomeController.GetFaqCategories(newArticle.WT_Knowledge_Category__c, newArticle.UrlName);
        Test.stopTest();
    }
}