objects/MuleSoft_Adapter_Config__mdt.object
<CustomObject>
    <description>Mulesoft Adapter Config</description>
    <fields>
        <fullName>EndPoint__c</fullName>
        <description>End Point from where we receieve the tokan</description>
        <label>End Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mulesoft Adapter Config</label>
    <pluralLabel>Mulesoft Adapter Configs</pluralLabel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>CZMDMPartyID__c</fullName>
        <description>MDM Global Id</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MDM Global ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CellPhoneNumber__c</fullName>
        <description>Cell phone of the party.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Cell phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__BrandCode__c</fullName>
        <description>Brand code of the submission this party is associated with</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryEmail__c</fullName>
        <description>Primary email of the party.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryPhone__c</fullName>
        <description>Primary phone number of the party</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Primary phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__SecondaryPhone__c</fullName>
        <description>Secondary phone of the party.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Secondary phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__Channel__c</fullName>
        <defaultValue>&quot;BRANCH&quot;</defaultValue>
        <description>Keeps track of current channel.</description>
        <label>Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionChannelType</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionChannelType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BRANCH</fullName>
        <label>Branch</label>
    </customValue>
    <customValue>
        <fullName>DIGITAL</fullName>
        <label>Digital</label>
    </customValue>
    <customValue>
        <fullName>CALL_CENTER</fullName>
        <label>Call Center</label>
    </customValue>
    <customValue>
        <fullName>AGENT</fullName>
        <label>Agent</label>
    </customValue>
    <description>Type of the channel from which the submission has been originated</description>
    <masterLabel>SubmissionChannelType</masterLabel>
</GlobalValueSet>

classes/MDMCustomerUpdateExtension.cls
public with sharing class MDMCustomerUpdateExtension {
  public static String updateCustomer(tffa__Submission__c submission, tffa__Party__c party) {
    try {
      MuleSoft_Adapter_Config__mdt adapterConfig = party.tffa__Type__c == FISCCIntegrationConstants.INDIVIDUAL
        ? CZWTFCHelperRepository.fetchMulesoftAdapterConfig('UpdateCustomer')
        : CZWTFCHelperRepository.fetchMulesoftAdapterConfig('UpdateBusinessCustomer');

      Integer custNumber = Integer.valueOf(party.Customer_Number__c);

      adapterConfig.EndPoint__c =
        adapterConfig.EndPoint__c +
        '?orgId=' +
        MDMCommonHelper.getBrandCode(party.tffa__BrandCode__c) +
        '&mdmPartyId=' +
        party.CZMDMPartyID__c +
        '&cisNmb=' +
        String.valueOf(custNumber);

      if (submission.tffa__Channel__c == CZWTFCConstants.BRANCH) {
        adapterConfig.EndPoint__c = adapterConfig.EndPoint__c + '&interactionMethod=BRANCH';
      } else {
        adapterConfig.EndPoint__c = adapterConfig.EndPoint__c + '?interactionMethod=ONLINE';
      }

      MDMCustomerUpdateRequest request = generateCustomerUpdateRequest(submission, party);

      String requestStr = System.JSON.serialize(request, true);

      CZMulesoftAdapter.auth = FISCCIntegrationLogService.auth;

      Object resp = CZMulesoftAdapter.invokeAPI(requestStr, adapterConfig);

      FISCCIntegrationLogService.setLogItemOk(FISCCIntegrationConstants.UPDATE_CUSTOMER_MDM);
      return 'SUCCESS';
    } catch (Exception ex) {
      tffa.logger.error('Exception in MDMCustomerUpdateExtension ' + ex.getMessage() + ' ' + ex.getStackTraceString());

      FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.UPDATE_CUSTOMER_MDM);
      return 'FAILURE';
    }
  }

  public static MDMCustomerUpdateRequest generateCustomerUpdateRequest(tffa__Submission__c submission, tffa__Party__c party) {
    MDMCustomerUpdateRequest request = new MDMCustomerUpdateRequest();
    request.phoneNumbersLst = getCommunication(party);
    request.emailAddressesLst.add(getEmail(party));
    return request;
  }

  public static List<MDMCustomerUpdateRequest.PhoneNumber> getCommunication(tffa__Party__c party) {
    List<MDMCustomerUpdateRequest.PhoneNumber> communicationList = new List<MDMCustomerUpdateRequest.PhoneNumber>();
    MDMCustomerUpdateRequest.PhoneNumber item = new MDMCustomerUpdateRequest.PhoneNumber();

    //Consumer - MBL
    //business - MBL
    if (party.CellPhoneNumber__c != null) {
      String phoneNumber = String.valueOf(party.CellPhoneNumber__c).right(10);
      item.resnCde = 'MBL';
      item.areaCde = phoneNumber.left(3);
      item.localNbr = phoneNumber.right(7);
      communicationList.add(item);
    }

    //Consumer - HME
    //business - PRI
    if (party.tffa__PrimaryPhone__c != null) {
      item = new MDMCustomerUpdateRequest.PhoneNumber();
      String phoneNumber = String.valueOf(party.tffa__PrimaryPhone__c).right(10);
      item.resnCde = party.tffa__Type__c == FISCCIntegrationConstants.INDIVIDUAL ? 'HME' : 'PRI';
      item.areaCde = phoneNumber.left(3);
      item.localNbr = phoneNumber.right(7);
      communicationList.add(item);
    }

    //Consumer - WRK
    //business - SEC
    if (party.tffa__SecondaryPhone__c != null) {
      item = new MDMCustomerUpdateRequest.PhoneNumber();
      String phoneNumber = String.valueOf(party.tffa__SecondaryPhone__c).right(10);
      item.resnCde = party.tffa__Type__c == FISCCIntegrationConstants.INDIVIDUAL ? 'WRK' : 'SEC';
      item.areaCde = phoneNumber.left(3);
      item.localNbr = phoneNumber.right(7);
      communicationList.add(item);
    }

    if (party.CZInternationalPhoneNumber__c != null) {
      item = new MDMCustomerUpdateRequest.PhoneNumber();
      String phoneNumber = String.valueOf(party.CZInternationalPhoneNumber__c);
      String[] internationNumber = phoneNumber.split(' ');
      item.resnCde = 'ITL';
      item.ctryCde = internationNumber[0].replaceAll('\\+', '');
      item.areaCde = internationNumber[1];
      item.localNbr = internationNumber[2];
      communicationList.add(item);
    }
    return communicationList;
  }

  public static MDMCustomerUpdateRequest.EmailAddress getEmail(tffa__Party__c party) {
    MDMCustomerUpdateRequest.EmailAddress item = new MDMCustomerUpdateRequest.EmailAddress();
    item.resnCde = 'PRI';
    item.emailAddr = party.tffa__PrimaryEmail__c;
    return item;
  }
}