objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>WT_Opportunity_Record_Type__c</fullName>
        <formula>RecordType.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Record_Type_Name__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Deposit</fullName>
                </value>
                <value>
                    <fullName>Investment</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>TM</fullName>
                </value>
                <value>
                    <fullName>Loan</fullName>
                </value>
                <value>
                    <fullName>Leasing</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Letter of Credit (Standby)</fullName>
                </value>
                <value>
                    <fullName>Terafina</fullName>
                </value>
                <value>
                    <fullName>Easy Access Loan</fullName>
                </value>
                <value>
                    <fullName>Deposit,Loan,International,Investment,TM,Other,Letter of Credit (Standby),Leasing</fullName>
                    <isActive>false</isActive>
                    <label>Deposit,Loan,International,Investment,TM,Other,Letter of Credit (Standby),Leasing</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Relationship_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Relationship Group</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Group Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WT_RelationshipGroup_Relation__c.object
<CustomObject>
    <description>A relationship between relationship account and person or business account.</description>
    <fields>
        <fullName>WT_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Group Relations (Account)</relationshipLabel>
        <relationshipName>Account_Account_Relations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WT_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WT_RelatedAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>RelatedTOAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship Group Relation</label>
    <nameField>
        <displayFormat>AAR-{000000000}</displayFormat>
        <label>Account Relation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Group Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/WT_OpportunityBeforeHandler.cls
/**
* -------------------------------------------------------------------------------------------------------------------------------------------------
* @Name             WT_OpportunityBeforeHandler
* @Author           sivaranjani         <smoorthi@wintrust.com>
* @ModifiedBy       Swaminathan E       <SEzhumal@wintrust.com>
* @version          v1.0 
* @CreatedDate      22 Feb 2021
* @UsedBy           Opportunity Object
* ---------------------------------------------------------------------------------------------------------------------------------------------------
* @Description 
* this is used by trigger WT_OpportunityTrigger 
* ---------------------------------------------------------------------------------------------------------------------------------------------------
* @Changes
* v2.0
* 08-31-2021
* ----------------------------------------------------------------------------------------------------------------------------------------------------
**/
// Test class: WT_OpportunityAfterHandler_T
public class WT_OpportunityBeforeHandler extends TriggerHandler
{
    private List<Opportunity> listNewOpportunity = new List<Opportunity>();
    private Map<Id, Opportunity> mapNewOpportunityIdandOpportunity = new Map<Id, Opportunity>();
    private Map<Id, Opportunity> mapOldOpportunityIdandOpportunity = new Map<Id, Opportunity>();
    public WT_OpportunityBeforeHandler()
    {      
        PopulateGlobalLists(); 
    }
    public override void beforeInsert()
    {
        populateRecordTypeName(listNewOpportunity);
        populateRelationshiproupId(listNewOpportunity);
    }    
    public override void beforeUpdate()
    {
        populateRecordTypeName(listNewOpportunity);
        populateRelationshiproupId(listNewOpportunity);
    } 
    private void PopulateGlobalLists()
    {        
        listNewOpportunity = (List<Opportunity>) Trigger.new;
        mapNewOpportunityIdandOpportunity = (Map<Id, Opportunity>) Trigger.newMap;
        mapOldOpportunityIdandOpportunity = (Map<Id, Opportunity>) Trigger.oldMap;
    }
/**
* --------------------------------------------------------------------------------------------------------------
* @Description
* This method is used to populate the Relationship Group ID for the Task linked to Business accounts
*
* --------------------------------------------------------------------------------------------------------------
* @Param  listNewOpportunity          List of Opportunity
* @Return void                 Returns none
* --------------------------------------------------------------------------------------------------------------
**/
    public void populateRelationshiproupId(List<Opportunity> listNewOpportunity)
    {
        Set<Id> setAccountId = new Set<Id>();
        Map<Id,Id> mapAccountId = new Map<Id,Id>();
        for(Opportunity opportunityRecord: listNewOpportunity)
        {
            setAccountId.add(opportunityRecord.AccountId);
        }
        List<WT_RelationshipGroup_Relation__c> listRelationRecord = [SELECT Id, WT_Account__c, WT_RelatedAccount__c FROM WT_RelationshipGroup_Relation__c WHERE WT_Active__c = true AND WT_RelatedAccount__c IN : setAccountId ];
        if (listRelationRecord.size() > 0)
        {
            for(WT_RelationshipGroup_Relation__c relation :listRelationRecord )
            {
                mapAccountId.put(relation.WT_RelatedAccount__c,relation.WT_Account__c);
            }
        }
        for(Opportunity opportunityRecord: listNewOpportunity)
        {
            if(mapAccountId.containsKey(opportunityRecord.AccountId))
            {
                opportunityRecord.WT_Relationship_Group__c = mapAccountId.get(opportunityRecord.AccountId);
            }
            else
            {
                opportunityRecord.WT_Relationship_Group__c = Null; 
            }
        }
    }  
/**
* --------------------------------------------------------------------------------------------------------------
* @Description
* This method is used to populate the Record Type Name for the Task linked to Business accounts
*
* --------------------------------------------------------------------------------------------------------------
* @Param  listOpportunity          List of Opportunity
* @Return void                 Returns none
* --------------------------------------------------------------------------------------------------------------
**/
    public static void populateRecordTypeName(list<Opportunity> listOpportunity)
    {
        for(Opportunity opporunityToUpdate: listOpportunity){
            opporunityToUpdate.WT_Record_Type_Name__c = opporunityToUpdate.WT_Opportunity_Record_Type__c;
        }
    }
    
}