objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>WT_Actual_Close_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Actual Close Date</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WT_Goal__c.object
<CustomObject>
    <description>Object to hold all the goals assigned to any given user in the system</description>
    <fields>
        <fullName>WT_Actual__c</fullName>
        <label>Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WT_Date_From__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WT_Date_To__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WT_Goal_Metric__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Metric</label>
        <referenceTo>WT_Goal_Metric__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Goal_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_In_Progress__c</fullName>
        <label>In-Progress</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WT_Parent_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Goal</label>
        <referenceTo>WT_Goal__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Percentage_Achieved__c</fullName>
        <label>Percentage To Goal</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>WT_Run_Rate_To_Goal__c</fullName>
        <label>Run Rate To Goal</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>WT_Should_Roll_Up_From_Child__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Roll Up From Child</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>WT_Target__c</fullName>
        <label>Target</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WT_Goal_Metric__c.object
<CustomObject>
    <description>Re-usable metric that can be assigned to multiple Goals</description>
    <fields>
        <fullName>WT_Actual_Result_Criteria_Logic__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Actual Result Criteria Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Actual_Result_Criteria__c</fullName>
        <description>This field is store the JSON structure of the goal criteria from UI</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Actual Result Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WT_Actual_Result_Date_Field_API_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Actual Result Date Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_CRM_Field_API_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SF Field To Sum</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_CRM_Object_API_Name__c</fullName>
        <label>SF Object</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
                <value>
                    <fullName>Referral</fullName>
                </value>
                <value>
                    <fullName>Task</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_InProgress_Result_Criteria__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>In Progress Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WT_InProgress_Result_Date_Field_API_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>In Progress Result Date Field</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_In_Progress_Criteria_Logic__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>In Progress Criteria Logic</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Metric_Type__c</fullName>
        <description>Type of roll-up operation applied to the Metric</description>
        <label>Metric Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>COUNT</fullName>
                </value>
                <value>
                    <fullName>SUM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Goal Metric</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_GoalPopulationLogic_T.cls
/**
* -----------------------------------------------------------------------------------------------------------------------------------------
* @Name           WT_GoalPopulationLogic_T
* @Author         Krupa Chinthakindi
* @ModifiedBy     Krupa Chinthakindi
* @Version        v1.0
* @CreatedDate    12/29/2021
  @Description    This test class is for WT_GoalPopulationLogic
* -----------------------------------------------------------------------------------------------------------------------------------------
* -----------------------------------------------------------------------------------------------------------------------------------------
* 
**/
@isTest
public with sharing class WT_GoalPopulationLogic_T {
      //This method is insert goal metrics with actual criteria and Inprogress Criteria
   @isTest
    static void TestupdateGoal() {
       
        User user = WT_DataFactory.createUser('WT Business Administrator');
        insert user; 
        
        List<Account> listCustomerAccount = WT_DataFactory.createAccounts(1,'PersonAccount_Customer',user.Id);
        insert listCustomerAccount;
        
        List<Opportunity> ListOppty = WT_DataFactory.createOppty(1);
        ListOppty[0].AccountID = listCustomerAccount[0].Id;
        ListOppty[0].OwnerId = user.Id;
        ListOppty[0].StageName = 'Stage 1 - Opportunity Identified';
        insert ListOppty;
      
        WT_Goal_Metric__c gm = new WT_Goal_Metric__c();
        gm.Name = 'test1123';
        gm.WT_Metric_Type__c = 'SUM';
        gm.WT_CRM_Object_API_Name__c = 'Opportunity';
        gm.WT_CRM_Field_API_Name__c = 'Amount';
        gm.WT_Actual_Result_Criteria__c = '[{"field":"Amount","operator":"greater than","value":"2000"},{},{},{},{},{},{}]';
        gm.WT_Actual_Result_Criteria_Logic__c = '1';
        gm.WT_Actual_Result_Date_Field_API_Name__c = 'CloseDate';
        gm.WT_InProgress_Result_Criteria__c  =  '[{"field":"Amount","operator":"greater than","value":"2000"},{},{},{},{},{},{}]';
        gm.WT_In_Progress_Criteria_Logic__c = '1';
        gm.WT_InProgress_Result_Date_Field_API_Name__c = 'WT_Actual_Close_Date__c';
        List<WT_Goal_Metric__c> gmLst = new List<WT_Goal_Metric__c>();
        gmLst.add(gm);
        system.runAs(user){
            insert gmLst;
          
        }

        WT_Goal__c tg = new WT_Goal__c();
        tg.Name = 'Test123';
        tg.WT_Should_Roll_Up_From_Child__c = false;
        tg.WT_Goal_Metric__c = gmLst[0].Id;
        tg.WT_Date_From__c = Date.newInstance(2022, 1, 12);
        tg.WT_Date_To__c = Date.newInstance(2022, 6, 12);
        tg.WT_Percentage_Achieved__c = 1;
        tg.WT_Actual__c = 10000;
        tg.WT_In_Progress__c = 7000;
        tg.WT_Target__c = 5000;
        tg.WT_Run_Rate_To_Goal__c = 1;
        tg.WT_Goal_Owner__c = user.Id;
        system.runAs(user){
            insert tg;
           
        }
        List<Id> tgIds = new List<Id>();
        tgIds.add(tg.Id);
        Test.startTest();
        WT_GoalPopulationLogic.updateGoal(tgIds);
        Test.stopTest(); 
    }
    //This method is to insert goal metrics and goal records to cover the ParentGoals
       @isTest
       static void testParentUpdateGoal() {
       
        User user = WT_DataFactory.createUser('WT Business Administrator');
        insert user; 
           
        List<Account> listCustomerAccount = WT_DataFactory.createAccounts(1,'PersonAccount_Customer',user.Id);
        insert listCustomerAccount;
        
        List<Opportunity> ListOppty = WT_DataFactory.createOppty(1);
        ListOppty[0].AccountID = listCustomerAccount[0].Id;
        ListOppty[0].OwnerId = user.Id;
        ListOppty[0].StageName = 'Stage 1 - Opportunity Identified';
        insert ListOppty;
        
        WT_Goal_Metric__c gm = new WT_Goal_Metric__c();
        gm.Name = 'test1123';
        gm.WT_Metric_Type__c = 'SUM';
        gm.WT_CRM_Object_API_Name__c = 'Opportunity';
        gm.WT_CRM_Field_API_Name__c = 'Amount';
        gm.WT_Actual_Result_Criteria__c = '[{"field":"Amount","operator":"greater than","value":"2000"},{},{},{},{},{},{}]';
        gm.WT_Actual_Result_Criteria_Logic__c = '1';
        gm.WT_Actual_Result_Date_Field_API_Name__c = 'CloseDate';
        gm.WT_InProgress_Result_Criteria__c  = '';
        gm.WT_In_Progress_Criteria_Logic__c = '';
        gm.WT_InProgress_Result_Date_Field_API_Name__c = '';
        List<WT_Goal_Metric__c> gmLst = new List<WT_Goal_Metric__c>();
        gmLst.add(gm);
        system.runAs(user){
            insert gmLst;
          
        }

        WT_Goal__c tg = new WT_Goal__c();
        tg.Name = 'Test123';
        tg.WT_Should_Roll_Up_From_Child__c = false;
        tg.WT_Goal_Metric__c = gmLst[0].Id;
        tg.WT_Date_From__c = Date.newInstance(2022, 1, 12);
        tg.WT_Date_To__c = Date.newInstance(2022, 6, 12);
        tg.WT_Should_Roll_Up_From_Child__c = true;
        tg.WT_Percentage_Achieved__c = 1;
        tg.WT_Actual__c = 10000;
        tg.WT_In_Progress__c = 8000;
        tg.WT_Target__c = 5000;
        tg.WT_Run_Rate_To_Goal__c = 1;
        tg.WT_Goal_Owner__c = user.Id;
        system.runAs(user){
            insert tg;
           
        }
           
        WT_Goal__c tg1 = new WT_Goal__c();
        tg1.Name = 'Test123';
        tg1.WT_Goal_Metric__c = gmLst[0].Id;
        tg.WT_Date_From__c = Date.newInstance(2022, 1, 12);
        tg.WT_Date_To__c = Date.newInstance(2022, 6, 12);
        tg1.WT_Parent_Goal__c = tg.Id;   
        tg1.WT_Should_Roll_Up_From_Child__c = true;
        tg1.WT_Percentage_Achieved__c = 1;
        tg1.WT_Actual__c = 1;
        tg1.WT_In_Progress__c = 1;
        tg1.WT_Target__c = 5000;
        tg1.WT_Run_Rate_To_Goal__c = 1;
        system.runAs(user){
            insert tg1;
           
        }
           
        List<Id> tgIds = new List<Id>();
        tgIds.add(tg1.Id);
        tgIds.add(tg.Id);
        Test.startTest();
        WT_GoalPopulationLogic.updateGoal(tgIds);
        Test.stopTest(); 
    }
    //This method is to cover the metrictype as Count for Inprogress Criteria
    @isTest
    static void testInProgressToGoal() {
       
        User user = WT_DataFactory.createUser('WT Business Administrator');
        insert user; 
       
        List<Account> listCustomerAccount = WT_DataFactory.createAccounts(1,'PersonAccount_Customer',user.Id);
        insert listCustomerAccount;
        
        List<Opportunity> ListOppty = WT_DataFactory.createOppty(1);
        ListOppty[0].AccountID = listCustomerAccount[0].Id;
        ListOppty[0].OwnerId = user.Id;
        ListOppty[0].StageName = 'Stage 1 - Opportunity Identified';
        insert ListOppty;
        
        WT_Goal_Metric__c gm1 = new WT_Goal_Metric__c();
        gm1.Name = 'test1123';
        gm1.WT_Metric_Type__c = 'COUNT';
        gm1.WT_CRM_Object_API_Name__c = 'Opportunity';
        gm1.WT_CRM_Field_API_Name__c = '';
        gm1.WT_InProgress_Result_Criteria__c  = '[{"field":"Amount","operator":"greater than","value":"2000"},{},{},{},{},{},{}]';
        gm1.WT_In_Progress_Criteria_Logic__c = '1';
        gm1.WT_InProgress_Result_Date_Field_API_Name__c = 'CloseDate';
        List<WT_Goal_Metric__c> gmLst = new List<WT_Goal_Metric__c>();
        gmLst.add(gm1);
        system.runAs(user){
            insert gmLst;
        }
        WT_Goal__c tg2 = new WT_Goal__c();
        tg2.Name = 'Test123';
        tg2.WT_Goal_Metric__c = gm1.Id;
        tg2.WT_Date_From__c = Date.Today() - 30;
        tg2.WT_Date_To__c = Date.Today(); 
        tg2.WT_Should_Roll_Up_From_Child__c = true;
        tg2.WT_Percentage_Achieved__c = 1;
       // tg2.WT_Actual__c = 1;
        tg2.WT_In_Progress__c = 1;
        tg2.WT_Target__c = 5000;
        tg2.WT_Run_Rate_To_Goal__c = 1;
        system.runAs(user){
            insert tg2;
        }
        Date dateToday=System.Today(); 
        WT_Goal__c tg1 = new WT_Goal__c();
        tg1.Name = 'Test123';
        tg1.WT_Should_Roll_Up_From_Child__c = false;
        tg1.WT_Parent_Goal__c = tg2.Id;  
        tg1.WT_Goal_Metric__c = gmLst[0].Id;
        tg1.WT_Date_From__c = Date.Today() - 30;
        tg1.WT_Date_To__c = Date.Today(); 
        tg1.WT_Percentage_Achieved__c = 1;
        //tg1.WT_Actual__c = 1;
        tg1.WT_In_Progress__c = 1;
        tg1.WT_Target__c = 5000;
        tg1.WT_Run_Rate_To_Goal__c = 1;
        tg1.WT_Goal_Owner__c = user.Id;
        system.runAs(user){
            insert tg1; 
        }
        List<Id> tgIds = new List<Id>();
        tgIds.add(tg1.Id);
        tgIds.add(tg2.Id);

        Test.startTest();
          WT_GoalPopulationLogic.updateGoal(tgIds);
        Test.stopTest(); 
    }   
}