objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>WT_Probability__c</fullName>
        <description>created as part of 1170</description>
        <label>Probability (%)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>50</fullName>
                </value>
                <value>
                    <fullName>75</fullName>
                </value>
                <value>
                    <fullName>90</fullName>
                </value>
                <value>
                    <fullName>0</fullName>
                    <isActive>false</isActive>
                    <label>0</label>
                </value>
                <value>
                    <fullName>100</fullName>
                    <isActive>false</isActive>
                    <label>100</label>
                </value>
                <value>
                    <fullName>35</fullName>
                    <isActive>false</isActive>
                    <label>35</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/WT_Opportunity_Stage_History__c.object
<CustomObject>
    <fields>
        <fullName>WT_CloseDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CloseDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WT_OpportunityId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OpportunityId</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>OpportunityStageHistories</relationshipLabel>
        <relationshipName>OpportunityStageHistories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Probability__c</fullName>
        <label>Probability</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>WT_StageName__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>StageName</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Opportunity Stage History</label>
    <nameField>
        <displayFormat>Stage History-{0000}</displayFormat>
        <label>Opportunity Stage History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpportunityStageHistories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_OpportunityStageHistoryController_T.cls
/**
* ----------------------------------------------------------------------------------------------------------------------
* @Name				WT_WT_OpportunityStageHistoryController_T
* @Author			Anoop		<abattini@wintrust.com>
* @Version			v1.0
* @CreatedDate		12-OCT-2021
* ---------------------------------------------------------------------------------------------------------------------
* @Description
* This is test class for before handler class for WT_OpportunityStageHistoryController.
* ---------------------------------------------------------------------------------------------------------------------------------------------------
* FUNCTIONAL TEST LOGIC
* testMethod1()
* 	> 
----------------------------------------------------------------
**/
@isTest
public class WT_OpportunityStageHistoryController_T 
{
    @isTest
    public static void testMethod1()
    {
        Opportunity varOpportunity = new Opportunity();
        varOpportunity.name = 'Test Name One';
        varOpportunity.StageName = 'Stage 1 - Opportunity Identified';
        varOpportunity.CloseDate = Date.newInstance(2021, 12, 31);
        insert varOpportunity;
        
        test.startTest();
        varOpportunity.StageName = 'Test StageName two';
        update varOpportunity;
        WT_Opportunity_Stage_History__c stg = new WT_Opportunity_Stage_History__c();
        stg.WT_StageName__c ='Closed/Won';
        stg.WT_CloseDate__c =date.today();
        stg.WT_Probability__c =10;
        stg.WT_OpportunityId__c = varOpportunity.Id;
        insert stg;
        WT_OpportunityStageHistoryController.getOpportunityHistoryLoadList(varOpportunity.Id);
        WT_OpportunityStageHistoryController.getOpportunityHistoryList(varOpportunity.Id);
        test.stopTest();
    }
}