objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>WT_Actual_Close_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Actual Close Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WT_Status_Reason__c</fullName>
        <label>Status Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>WT_Status__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Won</fullName>
                </value>
                <value>
                    <fullName>Declined - Credit</fullName>
                </value>
                <value>
                    <fullName>Declined - Pricing</fullName>
                </value>
                <value>
                    <fullName>Declined - Other</fullName>
                </value>
                <value>
                    <fullName>Rejected - Credit Structure</fullName>
                </value>
                <value>
                    <fullName>Rejected - Pricing</fullName>
                </value>
                <value>
                    <fullName>Rejected - Incumbent Response</fullName>
                </value>
                <value>
                    <fullName>Cancelled - Fell Through</fullName>
                </value>
                <value>
                    <fullName>Cancelled - Lost to purchase</fullName>
                </value>
                <value>
                    <fullName>Cancelled - Other</fullName>
                </value>
                <value>
                    <fullName>Automatic Deactivation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Declied - Credit</fullName>
                    <isActive>false</isActive>
                    <label>Declied - Credit</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>StageName</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed/Won</fullName>
                </value>
                <value>
                    <fullName>Closed/Lost</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/WT_BatchOpportunityClosedLostWeekly.cls
/**
* --------------------------------------------------------------------------------------------------------------
* @Name				WT_BatchOpportunityClosedLostWeekly
* @Author			Vamsi Pulikallu	<VPulikal@wintrust.com>
* @ModifiedBy		Vamsi Pulikallu	<VPulikal@wintrust.com>
* @Version			v1.0
* @CreatedDate		09 Feb 2021
* @ModifiedDate		09 Feb 2021
* @UsedBy			
* --------------------------------------------------------------------------------------------------------------
* @Description
* This is used to update Opportunities to Closed/Lost if they are open for more than 365 days
* --------------------------------------------------------------------------------------------------------------
* @Changes
* v1.0
*--------------------------------------------------------------------------------------------------------------
**/
// Code Coverage: WT_BatchOpportunity_T
public class WT_BatchOpportunityClosedLostWeekly implements Database.Batchable<sObject>, Database.Stateful
{
    public Database.QueryLocator start(Database.BatchableContext bc) 
    {
        String query = 'SELECT Id, CloseDate, WT_Actual_Close_Date__c , WT_Status__c, StageName,WT_Status_Reason__c FROM Opportunity WHERE WT_Status__c = \'Open\' AND CloseDate <= LAST_N_DAYS:364';
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext bc, List<Opportunity> scope)
    {
        system.debug(scope.size());
        List<Opportunity> listUpdateOpportunities = New List<Opportunity>();
        for(Opportunity opportunityRecord : scope) 
        {
            //if the estimated close date is more than 365 days
            if(opportunityRecord.CloseDate <= system.now().addDays(-365))
            {
                opportunityRecord.StageName = 'Stage 7 - Deal Lost or Declined';
                opportunityRecord.WT_Status_Reason__c = 'Automatic Deactivation';
                opportunityRecord.WT_Status__c ='Closed/Lost';
                opportunityRecord.WT_Actual_Close_Date__c = system.now();
                listUpdateOpportunities.add(opportunityRecord);
            }
        }
        if(listUpdateOpportunities.size()>0)
        {
            Database.update(listUpdateOpportunities, false);
            //update listUpdateOpportunities;
        }
    }
    public void finish(Database.BatchableContext bc)
    {
    } 
}