objects/SubBrand__c.object
<CustomObject>
    <description>Sub Brands</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>tffa__Brand__c</referenceTo>
        <relationshipLabel>SubBrands</relationshipLabel>
        <relationshipName>SubBrand</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SubBrand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SubBrand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubBrands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <fields>
        <fullName>FooterLogo__c</fullName>
        <description>Footer Logo for Brand</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Footer Logo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HeaderLogo__c</fullName>
        <description>Header Logo for Brand</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Header Logo</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>Unique code for the brand</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__Brand__c</fullName>
        <description>Brand code of the Brand for the submission if applicable</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CZWTFCMXFetchAccountsProviderTest.cls
@isTest
public with sharing class CZWTFCMXFetchAccountsProviderTest {
  @isTest
  static void testFetchAccounts() {
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new CZWTFCMXFetchAccountsProviderMockClass('testSuccess'));
    try {
      Map<String, String> params = new Map<String, String>();
      params.put(
        'sessionToken',
        'VVNSLWY4OWQyMzlhLTI5Y2UtNGM1MC1iYzgxLTlkMDZlMjE0NmQ0N3w3ZTk0ZmViMTEwMThlNTllMGExODJhM2I0YmRmNWZhMWQ2Y2UzZmQ3ZmYwMWVjODk3MjhmOWQ4NDcwY2E5NjZlOWU4Y2EzODA1NjMxOWE4OWM5OTU5ZDIzYzEzN2IzYjNiZWE5NzNmMmM1NTAwNmMyY2UyYTQ3ZTc3YjRkOGZkZmFlZGZlYzU3NmUxMDg0NDdiNDAwMzVhMzc5NjAyNjU4fDlGUkpxbGhwTlRSZ1JOT1dnSHZITjNFZUE1Vk1hWFJ5WEk2YjV0WXpIY3M='
      );
      CZWTFCMXFetchMemberAccountsProvider.fetchMemberAccountList(params);
    } catch (Exception e) {
      tffa.Logger.debug('Inside exception');
    }

    //Test error block
    try {
      CZWTFCMXFetchAccountsServiceProvider.invokeAPI(new Map<String, String>());
      CZWTFCMXFetchAccountsServiceProvider.testException = true;
      CZWTFCMXFetchAccountsServiceProvider.invokeAPI(new Map<String, String>());
    } catch (Exception ex) {
    }

    try {
      CZWTFCMXFetchMemberAccountResponseDTO.parse('');
    } catch (Exception exc) {
    }

    try {
      CZWTFCMXFetchMemberAccountsAdapter.testException = true;
      CZWTFCMXFetchMemberAccountsAdapter.execute(new Map<String, String>());
    } catch (Exception excp) {
    }

    try {
      CZWTFCMXFetchMemberAccountsProvider.testException = true;
      CZWTFCMXFetchMemberAccountsProvider.fetchMemberAccountList(new Map<String, String>());
    } catch (Exception excec) {
    }

    try {
      CZWTFCMXFetchMemberAccountsService.testException = true;
      CZWTFCMXFetchMemberAccountsService.execute(new Map<String, String>());
    } catch (Exception error) {
    }

    System.assertEquals('1', '1', 'Success');
    Test.stopTest();
  }

  @isTest
  public static void testMXFetchAcc() {
    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new CZWTFCMXFetchMicroDepoMockClass());
    try {
      Map<String, String> params = new Map<String, String>();
      params.put(
        'sessionToken',
        'VVNSLWY4OWQyMzlhLTI5Y2UtNGM1MC1iYzgxLTlkMDZlMjE0NmQ0N3w3ZTk0ZmViMTEwMThlNTllMGExODJhM2I0YmRmNWZhMWQ2Y2UzZmQ3ZmYwMWVjODk3MjhmOWQ4NDcwY2E5NjZlOWU4Y2EzODA1NjMxOWE4OWM5OTU5ZDIzYzEzN2IzYjNiZWE5NzNmMmM1NTAwNmMyY2UyYTQ3ZTc3YjRkOGZkZmFlZGZlYzU3NmUxMDg0NDdiNDAwMzVhMzc5NjAyNjU4fDlGUkpxbGhwTlRSZ1JOT1dnSHZITjNFZUE1Vk1hWFJ5WEk2YjV0WXpIY3M='
      );
      params.put('microDepositGUID', '123456789');
      CZWTFCMXFetchMicroDepoAccProvider.fetchMemberAccountList(params);
    } catch (Exception e) {
      tffa.Logger.debug('Inside exception');
    }

    tffa.Context ctx = tffa.Context.get();
    tffa__Brand__c brandObj = new tffa__Brand__c();
    brandObj.Name = '118';
    brandObj.tffa__Code__c = '118';
    brandObj.FooterLogo__c = 'test';
    brandObj.HeaderLogo__c = 'test';
    insert brandObj;

    SubBrand__c subB = new SubBrand__c();
    subB.Brand__c = brandObj.Id;
    subB.Name = 'Test';
    insert subB;

    tffa__Submission__c sub = new tffa__Submission__c(tffa__Brand__c = '118');
    insert sub;
    Map<String, String> mp = new Map<String, String>();
    mp.put('subId', sub.Id);
    mp.put('isMXUserCreated', 'false');
    try {
      CZWTFCMXController.setSubForTest = true;
      CZWTFCMXController.fetchMicroDepositAccount(ctx, mp);
    } catch (Exception ex) {
    }

    try {
      CZWTFCMXController.testException = true;
      CZWTFCMXController.setSubForTest = true;
      CZWTFCMXController.fetchMicroDepositAccount(ctx, mp);
    } catch (Exception ex) {
    }

    try {
      Map<String, String> params = new Map<String, String>();
      CZWTFCMXFetchMicroDepoAccProvider.testException = true;
      CZWTFCMXFetchMicroDepoAccProvider.fetchMemberAccountList(params);
    } catch (Exception ex) {
    }
    System.assertEquals('1', '1', 'Success');
    Test.stopTest();
  }
}