objects/SubBrand__c.object
<CustomObject>
    <description>Sub Brands</description>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>tffa__Brand__c</referenceTo>
        <relationshipLabel>SubBrands</relationshipLabel>
        <relationshipName>SubBrand</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SubBrand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SubBrand</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubBrands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Beneficiary__c.object
<CustomObject>
    <description>A beneficiary typically refers to someone who is eligible to receive distributions from deposits upon death of primary owner of account. Beneficiary capture typically happens for Certificate Deposits.
Designating a beneficiary not only ensures the CD will not have to go through probate when the applicant dies.</description>
    <fields>
        <fullName>CZParty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Party</relationshipLabel>
        <relationshipName>Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__FirstName__c</fullName>
        <description>First name of beneficiary</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>Last name of beneficiary</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryEmail__c</fullName>
        <description>Primary email of the beneficiary.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryPhone__c</fullName>
        <description>Primary phone number of the beneficiary</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>tffa__Suffix__c</fullName>
        <description>The name suffix of the beneficiary. (E.g., JR = Junior, SR = Senior, etc.)</description>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Suffix</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - PRIMARY, CONTINGENT</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__BeneficiaryType</valueSetName>
        </valueSet>
    </fields>
    <label>Beneficiary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Beneficiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address for Brand</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City for Brand</description>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailHeaderLogoUrl__c</fullName>
        <description>URL For the logo which will be reflected in the email.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>EmailHeaderLogoUrl</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailPhone__c</fullName>
        <description>Phone number which will get reflected in the email.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>EmailPhone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SenderEmailId__c</fullName>
        <description>Sender Email Id for Brand</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Sender Email Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State for Brand</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip__c</fullName>
        <description>Zip for Brand</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ContactEmail__c</fullName>
        <description>Contact Email for Brand</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Contact Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__InfoUrl__c</fullName>
        <description>Location of additional resource about the brand as a url.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Info URL</label>
        <type>Url</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>tffa__FirstName__c</fullName>
        <description>The first name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>The last name of the individual represented by the parent object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryEmail__c</fullName>
        <description>Primary email of the party.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryPhone__c</fullName>
        <description>Primary phone number of the party</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Primary phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Suffix__c</fullName>
        <description>The name suffix of the individual represented by the parent object. (E.g., JR = Junior, SR = Senior, etc.)</description>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Suffix</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Url__c</fullName>
        <description>URL in encrypted form which is associated with party to identify a unique application access URL and generated as part of OTP authentication flow</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Url</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyPartyXref__c.object
<CustomObject>
    <description>A relationship between 2 applicants of a submission. 
Personal relationship could be SPOUSE, PARENT, FRIENDS.
Business relationship between a company and an individual could be DIRECTOR, OWNER, EXECUTIVE, PARTNER etc. In additional the ownership percentage can be captured for OWNER type of relationship. 
Relationship between 2 company type applicants can also be captured such as PARENT and SUBSIDIARY.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Party managing the relationship</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Related To</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Party Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Party Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__SiteUrl__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store the current site url of public site</description>
    <fields>
        <fullName>tffa__Url__c</fullName>
        <description>Holds URL of the customer facing application for the current environment</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Url</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Site Url</label>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__Brand__c</fullName>
        <description>Brand code of the Brand for the submission if applicable</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Url__c</fullName>
        <description>URL to access current submission</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__SubmissionPartyXref__c.object
<CustomObject>
    <description>An individual or a legal entity which is applying for certain services/products in the bank. An applicant exists only in the context of a submission.</description>
    <fields>
        <fullName>tffa__IsPresent__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates whether the joint applicant was physically present during application data capture.</description>
        <label>Is present</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to Party object @managed</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryContact__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies primary point of contact in a business application. This is different from primary field which identifies the primary applicant. e.g. The primary applicant in a business application is a business.</description>
        <label>Primary contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current applicant is primary applicant of the application.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission object.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Url__c</fullName>
        <description>URL to access current submission</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Submission Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/tffa__BeneficiaryType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PRIMARY</fullName>
        <default>true</default>
        <label>Primary</label>
    </customValue>
    <customValue>
        <fullName>CONTINGENT</fullName>
        <label>Contingent</label>
    </customValue>
    <description>Type of the Beneficiary</description>
    <masterLabel>BeneficiaryType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__Suffix.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Jr</fullName>
    </customValue>
    <customValue>
        <fullName>Sr</fullName>
        <label>Sr.</label>
    </customValue>
    <customValue>
        <fullName>II</fullName>
    </customValue>
    <customValue>
        <fullName>III</fullName>
    </customValue>
    <customValue>
        <fullName>IV</fullName>
    </customValue>
    <customValue>
        <fullName>246</fullName>
        <isActive>false</isActive>
        <label>246</label>
    </customValue>
    <customValue>
        <fullName>Esq</fullName>
        <isActive>false</isActive>
        <label>Esq</label>
    </customValue>
    <customValue>
        <fullName>VI</fullName>
        <isActive>false</isActive>
        <label>VI</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <isActive>false</isActive>
        <label>V</label>
    </customValue>
    <customValue>
        <fullName>2nd</fullName>
        <isActive>false</isActive>
        <label>2nd</label>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
        <isActive>false</isActive>
        <label>Test</label>
    </customValue>
    <description>The name suffix of the individual represented by the parent object. (E.g., JR = Junior, SR = Senior, etc.)</description>
    <masterLabel>Suffix</masterLabel>
</GlobalValueSet>

classes/CZWTFCSubmissionJointEventExtension.cls
// Copyright (c) 2019 Terafina Inc
/**
 * Used for publishing notifications about a Submission's lifecycle event to relevant stakeholders.
 * Lifecycle events include - <br>
 * 1. Submission_Primary_Submitted <br>
 * 2. Submission_Joint_Completed <br>
 * 3. Submission_Joint_Submitted <br>
 *
 * Typically invoked from SubmissionService. Mapping to a lifecycle event is done via EventConfiguration
 * (Custom Metadata).
 */
global inherited sharing class CZWTFCSubmissionJointEventExtension extends tffa.EventExtension {
  global CZWTFCSubmissionJointEventExtension(string eventName) {
    this.eventName = eventName;
  }

  global CZWTFCSubmissionJointEventExtension() {
  }

  public override Object post(Object obj) {
    if (!(obj instanceof tffa__Submission__c || obj instanceof tffa__SubmissionPartyXref__c)) {
      tffa.Logger.error('Input is not of type tffa__Submission__c or tffa__SubmissionPartyXref__c');
      return obj;
    }
    tffa__Submission__c sub;
    tffa__SubmissionPartyXref__c xref;

    if (obj instanceof tffa__Submission__c) {
      sub = (tffa__Submission__c) obj;
    } else if (obj instanceof tffa__SubmissionPartyXref__c) {
      xref = (tffa__SubmissionPartyXref__c) obj;
    }
    tffa.Logger.debug('in CZWTFCSubmissionJointEventExtension.post for eventname ::' + eventName);

    //move this to switch case
    if (eventName == 'Submission_Primary_Submitted') {
      processPrimaryApplicantNotifications(sub);
      processJointInitiatedNotifications(sub);
    } else if (eventName == 'Submission_Joint_Abandoned' || eventName == 'Submission_Joint_Saved') {
      processJointApplicantNotifications(xref);
    }

    return obj;
  }

  private void processPrimaryApplicantNotifications(tffa__Submission__c sub) {
    // sub = tffa.SubmissionRepository.findByIdWithPartiesAndApplications(sub.Id);
    sub = CZWTFCSubmissionRepository.findSubmissionAndChildObjById(sub.Id);
    List<tffa.NotificationDTO> notifications = new List<tffa.NotificationDTO>();
    if (!sub.tffa__PartyXrefs__r.isEmpty()) {
      for (tffa__SubmissionPartyXref__c spx : sub.tffa__PartyXrefs__r) {
        tffa.NotificationDTO.NotificationRecipientDTO[] recipients = new List<tffa.NotificationDTO.NotificationRecipientDTO>{};
        if (spx.tffa__Primary__c) {
          tffa__Party__c p = spx.tffa__Party__r;
          recipients.add(
            new tffa.NotificationDTO.NotificationRecipientDTO(
              tffa.NotificationDTO.NotificationRecipientType.PARTY,
              p.Id,
              p.Name,
              p.tffa__PrimaryEmail__c,
              p.tffa__PrimaryPhone__c
            )
          );
          if (!recipients.isEmpty()) {
            tffa.NotificationDTO notif = new tffa.NotificationDTO();
            notif.primaryEntityId = p.Id;
            notif.eventName = eventName;
            notif.recipients = recipients;
            notif = buildNotificationFacts(notif, sub, spx);
            notifications.add(notif);
          }
        }
      }
      if (!notifications.isEmpty()) {
        Map<String, Object> facts = new Map<String, Object>();
        facts.put('EventName', eventName);
        tffa.NotificationDispatcher dispatcher = tffa.NotificationDispatcherFactory.getInstance().getProvider(facts);
        dispatcher.dispatch(notifications, facts);
      }
    }
  }

  private void processJointInitiatedNotifications(tffa__Submission__c sub) {
    //sub = tffa.SubmissionRepository.findByIdWithPartiesAndApplications(sub.Id);
    sub = CZWTFCSubmissionRepository.findSubmissionAndChildObjById(sub.Id);
    List<tffa.NotificationDTO> notifications = new List<tffa.NotificationDTO>();
    if (!sub.tffa__PartyXrefs__r.isEmpty()) {
      for (tffa__SubmissionPartyXref__c spx : sub.tffa__PartyXrefs__r) {
        tffa.NotificationDTO.NotificationRecipientDTO[] recipients = new List<tffa.NotificationDTO.NotificationRecipientDTO>{};
        if (!spx.tffa__Primary__c && !spx.tffa__IsPresent__c) {
          tffa__Party__c p = spx.tffa__Party__r;
          recipients.add(
            new tffa.NotificationDTO.NotificationRecipientDTO(
              tffa.NotificationDTO.NotificationRecipientType.PARTY,
              p.Id,
              p.Name,
              p.tffa__PrimaryEmail__c,
              p.tffa__PrimaryPhone__c
            )
          );
          if (!recipients.isEmpty()) {
            //build url mail - Submission_Joint_Initiated
            tffa.NotificationDTO notif = new tffa.NotificationDTO();
            notif.eventName = 'Submission_Joint_Initiated';
            notif.primaryEntityId = p.Id;
            notif.recipients = recipients;
            notif = buildNotificationFacts(notif, sub, spx);
            notifications.add(notif);

            //build for otp mail - Submission_OTP_Generated
            notif = new tffa.NotificationDTO();
            notif.eventName = 'Submission_OTP_Generated';
            notif.primaryEntityId = p.Id;
            notif.confidential = true;
            notif.recipients = recipients;
            notif = buildNotificationFacts(notif, sub, spx);
            notifications.add(notif);
          }
        }
      }
      if (!notifications.isEmpty()) {
        Map<String, Object> facts = new Map<String, Object>();
        facts.put('EventName', eventName);
        tffa.NotificationDispatcher dispatcher = tffa.NotificationDispatcherFactory.getInstance().getProvider(facts);
        dispatcher.dispatch(notifications, facts);
      }
    }
  }

  @TestVisible
  private void processJointApplicantNotifications(tffa__SubmissionPartyXref__c spx) {
    // tffa__Submission__c sub = tffa.SubmissionRepository.findByIdWithPrimaryPartyAndApplications(spx.tffa__Submission__c);
    tffa__Submission__c sub = new tffa__Submission__c();
    sub = CZWTFCSubmissionRepository.findSubmissionAndChildObjById(spx.tffa__Submission__c);
    List<tffa.NotificationDTO> notifications = new List<tffa.NotificationDTO>();
    tffa.NotificationDTO.NotificationRecipientDTO[] recipients = new List<tffa.NotificationDTO.NotificationRecipientDTO>{};
    tffa.NotificationDTO.NotificationRecipientDTO[] ccRecipients = new List<tffa.NotificationDTO.NotificationRecipientDTO>{};
    tffa__Party__c p = spx.tffa__Party__r;
    recipients.add(
      new tffa.NotificationDTO.NotificationRecipientDTO(
        tffa.NotificationDTO.NotificationRecipientType.PARTY,
        p.Id,
        p.Name,
        p.tffa__PrimaryEmail__c,
        p.tffa__PrimaryPhone__c
      )
    );
    if (!recipients.isEmpty()) {
      //build for url mail
      tffa.NotificationDTO notif = new tffa.NotificationDTO();
      notifications.add(notif);
      notif.eventName = eventName;
      notif.recipients = recipients;
      notif = buildNotificationFacts(notif, sub, spx);
      if (eventName == 'Submission_Joint_Abandoned') {
        tffa__Party__c primaryParty = sub.tffa__PartyXrefs__r[0].tffa__Party__r;
        ccRecipients.add(
          new tffa.NotificationDTO.NotificationRecipientDTO(
            tffa.NotificationDTO.NotificationRecipientType.PARTY,
            primaryParty.Id,
            primaryParty.Name,
            primaryParty.tffa__PrimaryEmail__c,
            primaryParty.tffa__PrimaryPhone__c
          )
        );
        if (!ccRecipients.isEmpty()) {
          notif.ccRecipients = ccRecipients;
        }
      }
    }

    if (!notifications.isEmpty()) {
      Map<String, Object> facts = new Map<String, Object>();
      facts.put('EventName', eventName);
      tffa.NotificationDispatcher dispatcher = tffa.NotificationDispatcherFactory.getInstance().getProvider(facts);
      dispatcher.dispatch(notifications, facts);
    }
  }

  private tffa.NotificationDTO buildNotificationFacts(
    tffa.NotificationDTO notif,
    tffa__Submission__c sub,
    tffa__SubmissionPartyXref__c xref
  ) {
    Map<String, Object> factsMap = new Map<String, Object>(); //Notification DTO level fact map
    tffa__Party__c party = xref.tffa__Party__r;
    String suffix = '';
    switch on eventName {
      when 'Submission_Joint_Abandoned', 'Submission_Joint_Saved' {
        //notif.addFact('PartyName', party.Name);
        suffix = party.tffa__Suffix__c != null ? ' ' + party.tffa__Suffix__c : '';
        factsMap.put('PartyName', party.tffa__FirstName__c + ' ' + party.tffa__LastName__c + suffix);
        PageReference pageRef = new PageReference(tffa__SiteUrl__c.getOrgDefaults().tffa__Url__c + '/sales');
        pageRef.getParameters().put('q', buildQueryParam(sub, party, false));
        pageRef.getParameters().put('medium', 'email');
        pageRef.getParameters().put('source', 'notification');
        pageRef.getParameters().put('campaign', notif.eventName.toLowerCase());
        //notif.addFact('SubmissionQueryParam', pageRef.getUrl());
        factsMap.put('SubmissionQueryParam', pageRef.getUrl());
      }
      when 'Submission_Joint_Initiated', 'Submission_Primary_Submitted' {
        //notif.addFact('PartyName', party.Name);
        suffix = party.tffa__Suffix__c != null ? ' ' + party.tffa__Suffix__c : '';
        factsMap.put('PartyName', party.tffa__FirstName__c + ' ' + party.tffa__LastName__c + suffix);
        PageReference pageRef = new PageReference(tffa__SiteUrl__c.getOrgDefaults().tffa__Url__c + '/sales');
        pageRef.getParameters().put('q', buildQueryParam(sub, party, true));
        pageRef.getParameters().put('medium', 'email');
        pageRef.getParameters().put('source', 'notification');
        pageRef.getParameters().put('campaign', notif.eventName.toLowerCase());
        pageRef.getParameters().put('brandCode', sub.tffa__Brand__c);
        //notif.addFact('SubmissionQueryParam', pageRef.getUrl());
        factsMap.put('SubmissionQueryParam', pageRef.getUrl());

        //build for addition of facts  Submission_Joint_Initiated / Submission_Primary_Submitted
        tffa.Logger.debug('sub.tffa__Brand__c ::::' + sub.tffa__Brand__c);
        tffa__Brand__c brandObj = CZWTFCBrandRepository.fetchBrandByCode(sub.tffa__Brand__c);
        tffa.Logger.debug('brandObj subjointevnt ::::' + brandObj);
        factsMap.put('brandName', brandObj.Name);
        factsMap.put('phoneNo', brandObj.EmailPhone__c);
        factsMap.put('logoUrl', brandObj.EmailHeaderLogoUrl__c);
        factsMap.put('address', brandObj.Address__c);
        factsMap.put('city', brandObj.City__c);
        factsMap.put('state', brandObj.State__c);
        factsMap.put('zip', brandObj.Zip__c);
        factsMap.put('bankUrl', brandObj.tffa__InfoUrl__c);
        factsMap.put('email', brandObj.tffa__ContactEmail__c);
        tffa__Party__c primaryPartyObj = new tffa__Party__c();
        if (!sub.tffa__PartyXrefs__r.isEmpty()) {
          for (tffa__SubmissionPartyXref__c spXref : sub.tffa__PartyXrefs__r) {
            if (spXref.tffa__Type__c == 'INDIVIDUAL' && (spXref.tffa__Primary__c || spXref.tffa__PrimaryContact__c)) {
              primaryPartyObj = spXref.tffa__Party__r;
            }
          }
        }
        suffix = primaryPartyObj.tffa__Suffix__c != null ? ' ' + primaryPartyObj.tffa__Suffix__c : '';
        factsMap.put('primaryPartyName', primaryPartyObj.tffa__FirstName__c + ' ' + primaryPartyObj.tffa__LastName__c + suffix);
        if (brandObj.subBrand__r != null && !brandObj.subBrand__r.isEmpty()) {
          String subBrandName = '';
          String commaSeperateSubBrandName = '';
          for (SubBrand__c subBrandObj : brandObj.subBrand__r) {
            if (subBrandName == '') {
              subBrandName += subBrandObj.Name;
              commaSeperateSubBrandName += subBrandObj.Name;
            } else {
              subBrandName += ' | ' + subBrandObj.Name;
              commaSeperateSubBrandName += ', ' + subBrandObj.Name;
            }
          }

          factsMap.put('subBranchHeading', 'Our family of banks');
          factsMap.put('subBrandName', subBrandName);
          factsMap.put('footerBrand', commaSeperateSubBrandName + ' are branches of ' + brandObj.Name);
        } else {
          factsMap.put('subBranchHeading', ' ');
          factsMap.put('subBrandName', ' ');
          factsMap.put('footerBrand', ' ');
        }

        tffa.Logger.debug('factsMap subjointevnt ::::' + factsMap);
        notif.orgWideEmailAddress = brandObj.SenderEmailId__c;
        notif.facts = factsMap;
      }
      when 'Submission_OTP_Generated' {
        suffix = party.tffa__Suffix__c != null ? ' ' + party.tffa__Suffix__c : '';
        factsMap.put('PartyName', party.tffa__FirstName__c + ' ' + party.tffa__LastName__c + suffix);
        tffa.Logger.debug('sub.tffa__Brand__c ::::' + sub.tffa__Brand__c);
        tffa__Brand__c brandObj = CZWTFCBrandRepository.fetchBrandByCode(sub.tffa__Brand__c);
        tffa.Logger.debug('brandObj subjointevnt ::::' + brandObj);
        factsMap.put('brandName', brandObj.Name);
        factsMap.put('phoneNo', brandObj.EmailPhone__c);
        factsMap.put('logoUrl', brandObj.EmailHeaderLogoUrl__c);
        factsMap.put('address', brandObj.Address__c);
        factsMap.put('city', brandObj.City__c);
        factsMap.put('state', brandObj.State__c);
        factsMap.put('zip', brandObj.Zip__c);
        factsMap.put('bankUrl', brandObj.tffa__InfoUrl__c);
        factsMap.put('email', brandObj.tffa__ContactEmail__c);
        if (brandObj.subBrand__r != null && !brandObj.subBrand__r.isEmpty()) {
          String subBrandName = '';
          String commaSeperateSubBrandName = '';
          for (SubBrand__c subBrandObj : brandObj.subBrand__r) {
            if (subBrandName == '') {
              subBrandName += subBrandObj.Name;
              commaSeperateSubBrandName += subBrandObj.Name;
            } else {
              subBrandName += ' | ' + subBrandObj.Name;
              commaSeperateSubBrandName += ', ' + subBrandObj.Name;
            }
          }

          factsMap.put('subBranchHeading', 'Our family of banks');
          factsMap.put('subBrandName', subBrandName);
          factsMap.put('footerBrand', commaSeperateSubBrandName + ' are branches of ' + brandObj.Name);
        } else {
          factsMap.put('subBranchHeading', ' ');
          factsMap.put('subBrandName', ' ');
          factsMap.put('footerBrand', ' ');
        }

        tffa.Logger.debug('factsMap subjointevnt ::::' + factsMap);
        notif.orgWideEmailAddress = brandObj.SenderEmailId__c;
        notif.facts = factsMap;
      }
      when else {
        notif.primaryEntityId = party.Id;
      }
    }
    tffa.Logger.debug('Notification dto ::::' + notif);
    return notif;
  }

  private String buildQueryParam(tffa__Submission__c sub, tffa__Party__c party, Boolean otpStatus) {
    //build url params
    Map<String, String> urlParams = new Map<String, String>();
    urlParams.put('Submission__c', sub.Id);
    urlParams.put('Party__c', party.Id);
    if (otpStatus) {
      urlParams.put('OTPStatus__c', 'CHALLENGED');
    }

    //encrypt
    // String q = tffa.ApexPageUtils.encryptQueryParameters(urlParams);
    String q = '';
    if (!Test.isRunningTest()) {
      q = tffa.Cipher.encrypt(JSON.serialize(urlParams));
    }
    return q;
  }
}