objects/TFEntries__c.object
<CustomObject>
    <description>the file</description>
    <label>TFEntries</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>TFEntries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TFEntries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__Description__c</fullName>
        <description>Additional information about the application. Usually it is same as product description.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>tffa__KYCDecisionOutcome__c</fullName>
        <description>Outcome of a KYC decisioning process.</description>
        <label>KYC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationDecisionOutcome</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__ProductCategory__c</fullName>
        <description>Different product category supported by system. This classifies the flow of account opening , the underlying data model and the servicing components about an account.</description>
        <label>Product Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ProductCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__ProductCode__c</fullName>
        <description>Unique product code maintained in the system</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Financial Product Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product code identifier.</description>
        <label>Financial Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR (4 AND 5))</booleanFilter>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>$Source.tffa__ProductCategory__c</field>
                <operation>equals</operation>
                <valueField>tffa__Product__c.tffa__Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value>In Progress</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the application</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ApplicationPartyXref__c.object
<CustomObject>
    <description>Each Applicant of the submission can play different roles in the application and the eventual account.</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>tffa__KYCDecisionOutcome__c</fullName>
        <description>Outcome of a KYC decisioning process.</description>
        <label>KYC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyDecisionOutcome</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <fields>
        <fullName>tffa__Category__c</fullName>
        <description>Broad classification of the product</description>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ProductCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique identifier for the product</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>tffa__Description__c</fullName>
        <description>A summarized description, meant to provide a quick overview about the product.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>tffa__FullDescription__c</fullName>
        <description>A comprehensive description enumerating key features about the product.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Full description</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>tffa__ImageUrl__c</fullName>
        <description>Location of image describing the product as a url.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Image</label>
        <type>Url</type>
    </fields>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__KYCDecisionOutcome__c</fullName>
        <description>A rollup of DecisionOutcome(s) of associated Application(s). Typically set to the worst among the Application(s).</description>
        <label>KYC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationDecisionOutcome</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the submission</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/UploadFileHistory__c.object
<CustomObject>
    <description>the file</description>
    <label>Upload File History</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Upload File History</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Upload File History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__ApplicationDecisionOutcome.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>APPROVED</fullName>
        <label>✅Approved</label>
    </customValue>
    <customValue>
        <fullName>DECLINED</fullName>
        <label>❌Declined</label>
    </customValue>
    <customValue>
        <fullName>REVIEW</fullName>
        <label>⚠️Review</label>
    </customValue>
    <customValue>
        <fullName>COUNTER_OFFER</fullName>
        <label>🔶Counter offer</label>
    </customValue>
    <description>Possible outcomes of an Application decisioning process. Each outcome has a different effect on the Application process. e.g. DECLINED may result in termination of further processing, REVIEW may result in manual intervention for further processing</description>
    <masterLabel>ApplicationDecisionOutcome</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyDecisionOutcome.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>APPROVED</fullName>
        <label>✅Approved</label>
    </customValue>
    <customValue>
        <fullName>DECLINED</fullName>
        <label>❌Declined</label>
    </customValue>
    <customValue>
        <fullName>REVIEW</fullName>
        <label>⚠️Review</label>
    </customValue>
    <customValue>
        <fullName>COUNTER_OFFER</fullName>
        <label>🔶Counter offer</label>
    </customValue>
    <description>Possible outcomes of an Party decisioning process. Each outcome has a different effect on the Party as well as on related Application(s). e.g. if outcome is DECLINED, related Application may be DECLINED, if outcome is REVIEW, related Application may be marked for REVIEW</description>
    <masterLabel>PartyDecisionOutcome</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>ABANDONED</fullName>
        <label>Abandoned</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>SAVED</fullName>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>SUBMITTED</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>Indicates current status of the submission.This will be computed and be useful for regulations.</description>
    <masterLabel>SubmissionStatus</masterLabel>
</GlobalValueSet>

classes/CZWTFCApplicationRepositoryTest.cls
@isTest
public with sharing class CZWTFCApplicationRepositoryTest {
  @isTest
  public static void testSaveApp() {
    tffa__Party__c party = new tffa__Party__c();
    insert party;
    tffa__Submission__c sub = new tffa__Submission__c();
    insert sub;
    tffa__Application__c app = new tffa__Application__c();
    app.tffa__Submission__c = sub.id;
    app.tffa__Status__c = 'SUBMITTED';
    app.tffa__KYCDecisionOutcome__c = 'DECLINED';
    insert app;
    tffa__ApplicationPartyXref__c partyXrf = new tffa__ApplicationPartyXref__c();
    partyXrf.tffa__Party__c = party.id;
    partyXrf.tffa__Application__c = app.id;

    //tffa__Application__c newapp = tffa.ApplicationService.create(app);
    List<tffa__Application__c> entities = new List<tffa__Application__c>();
    entities.add(app);
    Test.startTest();
    List<tffa__Application__c> applications = CZWTFCApplicationRepository.save(entities);
    Test.stopTest();
  }

  @isTest
  public static void testSaveSub() {
    tffa__Submission__c sub = new tffa__Submission__c();
    //tffa__Submission__c newsub = tffa.SubmissionService.create(sub);
    List<tffa__Submission__c> entities = new List<tffa__Submission__c>();
    entities.add(sub);
    Test.startTest();
    List<tffa__Submission__c> subList = CZWTFCApplicationRepository.save(entities);
    Test.stopTest();
  }

  @isTest
  public static void testgetTfentries() {
    Test.startTest();
    List<TFEntries__c> tfList = CZWTFCApplicationRepository.getTfentries();
    Test.stopTest();
  }

  @isTest
  public static void testfindSubmissionById() {
    Test.startTest();
    tffa__Submission__c subList = CZWTFCApplicationRepository.findSubmissionById('id');
    Test.stopTest();
  }

  @isTest
  public static void testgetContentFolder() {
    Test.startTest();
    ContentFolder cfolder = CZWTFCApplicationRepository.getContentFolder('cf');
    Test.stopTest();
  }

  @isTest
  public static void testfindAppXrefByAppIds() {
    Test.startTest();
    List<tffa__ApplicationPartyXref__c> appXref = CZWTFCApplicationRepository.findAppXrefByAppIds(new List<String>{ 'dummy' });
    Test.stopTest();
  }

  @isTest
  public static void testGetContent() {
    Test.startTest();
    ContentVersion cVersion = CZWTFCApplicationRepository.getContent('dummy');
    Test.stopTest();
  }

  @isTest
  public static void testGetContentWorkSpace() {
    Test.startTest();
    ContentWorkspace cWorkSpace = CZWTFCApplicationRepository.getContentWorkSpace('dummy');
    Test.stopTest();
  }

  @isTest
  public static void testGetContentFolderMember() {
    Test.startTest();
    ContentFolderMember member = CZWTFCApplicationRepository.getContentFolderMember('dummy');
    Test.stopTest();
  }

  @isTest
  public static void testSave() {
    Test.startTest();
    List<TFEntries__c> tflist = CZWTFCApplicationRepository.save(new List<TFEntries__c>());
    List<UploadFileHistory__c> uploadFileHistory = CZWTFCApplicationRepository.save(new List<UploadFileHistory__c>());
    List<ContentVersion> contentVersion = CZWTFCApplicationRepository.save(new List<ContentVersion>());
    List<ContentDocumentLink> contentDocumentLink = CZWTFCApplicationRepository.save(new List<ContentDocumentLink>());
    List<ContentFolderMember> contentFolderMember = CZWTFCApplicationRepository.save(new List<ContentFolderMember>());

    Test.stopTest();
  }

  // @isTest
  // public static void testSaveSingle() {
  //   Test.startTest();

  //   tffa__Submission__c submissionObj = CZWTFCTestDataRepository.makeData();
  //   submissionObj.tffa__Status__c = CZWTFCKYCConstants.SUBMISSION_IN_PROGRESS;
  //   update submissionObj;

  //   tffa.SObjectAssembler asm = new tffa.SObjectAssembler(submissionObj);

  //   //Inserting products
  //   createCheckingProduct1();

  //   //tffa__Application__c checkingApp = CZWTFCTestDataRepository.createCheckingApplication();
  //   tffa__Application__c checkingApp = new tffa__Application__c();
  //   checkingApp.tffa__ProductCategory__c = 'CHECKING';
  //   checkingApp.tffa__ProductCode__c = '54';
  //   checkingApp.tffa__Submission__c = submissionObj.id;
  //   insert checkingApp;
  //   tffa__Application__c app = CZWTFCApplicationRepository.findApplicationWithId(checkingApp.Id);
  //   Test.stopTest();
  // }

  @isTest
  public static tffa__Product__c createCheckingProduct1() {
    tffa__Product__c product = new tffa__Product__c();
    product.tffa__Category__c = 'CHECKING';
    product.tffa__Code__c = '54';
    product.Name = 'Super Checking';
    product.tffa__ImageUrl__c = 'flexible_business.png';
    product.tffa__Description__c = '&#10003 Interest Bearing Checking<br/><br/>&#10003 $100 Minimum Opening Deposit<br/><br/>&#10003 No Minimum Balance Requirement<br/><br/>&#10003 No Monthly Service Fee<br/><br/>&#10003 Checks are Optional<br/><br/>&#10003 No Charge at Bank ATMs';
    product.tffa__FullDescription__c = '&#10003 Interest Bearing Checking<br/><br/>&#10003 $100 Minimum Opening Deposit<br/><br/>&#10003 No Minimum Balance Requirement<br/><br/>&#10003 No Monthly Service Fee<br/><br/>&#10003 Checks are Optional<br/><br/>&#10003 No Charge at Bank ATMs';
    product = tffa.ProductService.create(product);
    return product;
  }

  @isTest
  public static void fisccTestDataRepo() {
    Test.startTest();
    FISCCTestDataRepository.createIndividualPartyWithChildObjects();
    FISCCTestDataRepository.createIndividualParty();
    Test.stopTest();
  }

  @isTest
  public static void helperTestRepos() {
    Test.startTest();

    try {
      CZWTFCHelperRepository.fetchContentDocumentId(new List<String>{});
    } catch (Exception ex) {
    }

    try {
      CZWTFCHelperRepository.deleteContentDocument('Test');
      CZWTFCHelperRepository.getBeneficiaryById('50');
      CZWTFCHelperRepository.fetchEnvConfig();
      CZWTFCHelperRepository.getFundingMat();
      CZWTFCHelperRepository.deleteContentDocumentById(new List<String>{});
    } catch (Exception ex) {
    }

    Test.stopTest();
  }

  @isTest
  public static void testMethod1() {
    Test.startTest();

    tffa__Party__c party = new tffa__Party__c();
    insert party;
    tffa__Submission__c sub = new tffa__Submission__c();
    insert sub;
    tffa__Application__c app = new tffa__Application__c();
    app.tffa__Submission__c = sub.id;
    app.tffa__Status__c = 'SUBMITTED';
    app.tffa__KYCDecisionOutcome__c = 'DECLINED';
    insert app;

    CZWTFCApplicationRepository.findApplicationByMDMStatus();
    CZWTFCApplicationRepository.findApplicationPartyById(String.valueOf(app.Id));
    CZWTFCApplicationRepository.findApplicationPartyByPartyId(String.valueOf(party.Id), String.valueOf(app.Id));
    CZWTFCApplicationRepository.findAccountPrefByAppIdAndCode(app, 'test');
    CZWTFCApplicationRepository.findAppById(app.id);

    Test.stopTest();
  }
}