objects/TFEntries__c.object
<CustomObject>
    <description>the file</description>
    <fields>
        <fullName>LastACHFileRecNo__c</fullName>
        <description>Last ACH number of records in the file</description>
        <label>LastACHFileRecNo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>TFEntries</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>TFEntries Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TFEntries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>SubmissionName__c</fullName>
        <description>This field has the name of the submission</description>
        <formula>tffa__Submission__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SubmissionName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The final generated account number. This will be set only after the final account number is available as part of the response of an account open API call.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Amount__c</fullName>
        <description>Total certificate amount captured for the certificate application</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>tffa__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this application should be considered as primary in the submission. Such applications cannot be removed from the submission. Used in bundle applications, where one application is marked as primary.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product code identifier.</description>
        <label>Financial Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR (4 AND 5))</booleanFilter>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>$Source.tffa__ProductCategory__c</field>
                <operation>equals</operation>
                <valueField>tffa__Product__c.tffa__Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value>In Progress</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__RoutingNumber__c</fullName>
        <description>Routing number of the created account.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Routing number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the application</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ApplicationPartyXref__c.object
<CustomObject>
    <description>Each Applicant of the submission can play different roles in the application and the eventual account.</description>
    <fields>
        <fullName>PartyLegalName__c</fullName>
        <description>This field has the legal name which can be used in case of Organisation Name</description>
        <formula>tffa__Party__r.tffa__LegalName__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PartyLegalName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PartyPersonName__c</fullName>
        <description>This field has the first name and last name of party</description>
        <formula>UPPER(LEFT( tffa__Party__r.tffa__FirstName__c,1 ))&amp;LOWER(Mid( tffa__Party__r.tffa__FirstName__c, 2, Len( tffa__Party__r.tffa__FirstName__c )-1))&amp; &quot;, &quot; &amp; UPPER(LEFT( tffa__Party__r.tffa__LastName__c,1 ))&amp;LOWER(Mid( tffa__Party__r.tffa__LastName__c, 2, Len( tffa__Party__r.tffa__LastName__c)-1))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PartyPersonName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current applicant is primary applicant of the application.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__FundingRequest__c.object
<CustomObject>
    <description>Supports the capture of details pertaining to funding a payment obligation using one of the various available sources of funding</description>
    <fields>
        <fullName>MembershipAmount__c</fullName>
        <description>Membership Amount</description>
        <label>Membership Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TraceNo__c</fullName>
        <description>This column is used to trace the file sent to HarlandClarke or ACH</description>
        <encryptionScheme>None</encryptionScheme>
        <label>TraceNo</label>
        <length>254</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The account number which needs to be debited for this funding request</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__AccountType__c</fullName>
        <description>Type of account captured for funding</description>
        <label>AccountType</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__FundingAccountType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Amount__c</fullName>
        <description>The amount of funds which this funding request denotes.</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>tffa__LinkedApplication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to application.</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Funding Requests</relationshipLabel>
        <relationshipName>LinkedFundingRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__RoutingNumber__c</fullName>
        <description>Routing number of the account</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Routing number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Funding status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__FundingStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Funding Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__FundingAccountType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CHECKING</fullName>
        <label>Checking</label>
    </customValue>
    <customValue>
        <fullName>SAVINGS</fullName>
        <label>Savings</label>
    </customValue>
    <description>Type of account captured for funding</description>
    <masterLabel>FundingAccountType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__FundingStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>FUNDED</fullName>
        <label>Funded</label>
    </customValue>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
        <label>Failed</label>
    </customValue>
    <customValue>
        <fullName>APPROVAL</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>REVERSED</fullName>
        <label>Reversed</label>
    </customValue>
    <customValue>
        <fullName>REVERSAL_FAILED</fullName>
        <label>Reversal Failed</label>
    </customValue>
    <customValue>
        <fullName>ACH_FILE_GENERATED</fullName>
        <label>ACH File Generated</label>
    </customValue>
    <customValue>
        <fullName>ACH_FILE_FAILED</fullName>
        <label>ACH File Generation Failed</label>
    </customValue>
    <customValue>
        <fullName>HOLD_APPLIED</fullName>
        <label>Hold Applied on Funds</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>REVERSAL_NOT_REQ</fullName>
        <label>Reversal Not Required</label>
    </customValue>
    <customValue>
        <fullName>AUTHORIZED</fullName>
        <isActive>false</isActive>
        <label>AUTHORIZED</label>
    </customValue>
    <description>Status of funding</description>
    <masterLabel>FundingStatus</masterLabel>
</GlobalValueSet>

classes/ACHEntryRecordBuilder.cls
public with sharing virtual class ACHEntryRecordBuilder {
  @TestVisible
  private static Boolean testException = false;
  @TestVisible
  protected Integer unqCounter = getLastNumber(null);
  protected ACHFileDTO achdata;
  private Map<String, tffa__ApplicationPartyXref__c> ApplicationData = new Map<String, tffa__ApplicationPartyXref__c>();
  public void setACHData(ACHFileDTO achdata) {
    this.achdata = achdata;
    fillAllApplicationsforFunding();
  }
  public void fillAllApplicationsforFunding() {
    String[] selectedApplicationIds = new List<String>();
    for (tffa__FundingRequest__c abtAcct : achdata.abtAccts) {
      selectedApplicationIds.add(abtAcct.tffa__LinkedApplication__c);
    }

    // String query = new tffa.QueryBuilder(tffa__ApplicationPartyXref__c.SObjectType)
    // .selectFields()
    // .whereClause('tffa__Primary__c', '= true')
    // .opAnd()
    // .whereClause('tffa__Application__c', '= :selectedApplicationIds')
    // .build()
    // .toQuery();
    // List<tffa__ApplicationPartyXref__c> listApplication = Database.query(query);
    List<tffa__ApplicationPartyXref__c> listApplication = CZWTFCApplicationRepository.findAppXrefByAppIds(selectedApplicationIds);

    for (tffa__ApplicationPartyXref__c application : listApplication) {
      ApplicationData.put(application.tffa__Application__c, application);
    }
  }

  public virtual List<ACHEntryDetailRecord> buildRecords() {
    List<ACHEntryDetailRecord> recs = new List<ACHEntryDetailRecord>();
    for (tffa__FundingRequest__c abtAcct : achdata.abtAccts) {
      try {
        //---------------------------------------------------------------------------------
        ACHEntryDetailRecord rec = new ACHEntryDetailRecord();
        rec.setTransactionCode(ACHConstants.TXN_CODEMAP.get(abtAcct.tffa__AccountType__c + '_' + ACHConstants.TXN_TYPE_DEBIT));
        rec.setRdfiIdentification(abtAcct.tffa__RoutingNumber__c.substring(0, 8));
        rec.setCheckDigit(abtAcct.tffa__RoutingNumber__c.substring(8, 9));
        if (abtAcct.tffa__AccountNumber__c.length() > 17) {
          rec.setDfiAcctNo((abtAcct.tffa__AccountNumber__c).right(17));
        } else {
          rec.setDfiAcctNo(abtAcct.tffa__AccountNumber__c);
        }
        Decimal amount = 0;

        if (abtAcct.tffa__Amount__c != null) {
          amount = amount + abtAcct.tffa__Amount__c;
        }
        if (abtAcct.MembershipAmount__c != null) {
          amount = amount + abtAcct.MembershipAmount__c;
        }

        rec.setAmount(amount);
        rec.setIndvidualIdentificationNo(abtAcct.tffa__LinkedApplication__r.SubmissionName__c);
        if (test.isRunningTest()) {
          rec.setIndividualName('hey');
        } else {
          rec.setIndividualName(
            getPartyName(
                ApplicationData.get(abtAcct.tffa__LinkedApplication__r.id).PartyPersonName__c,
                ApplicationData.get(abtAcct.tffa__LinkedApplication__r.id).PartyLegalName__c
              )
              .left(22)
          );
        }

        rec.setPaymentTypeCode(ACHConstants.FIELD_PAYMENTTYPECODE);
        rec.setAddendaRecFlag(ACHConstants.FIELD_ADDEDNDA_RECORD_INDICATOR);
        //String refNo = getRefNo();
        //refNo = (refNo.length() > 15) ? refNo.substring(refNo.length() - 15, refNo.length()) : refNo;
        //rec.setTraceNo(refNo);
        //private ACHAddendaRecord addendaRec;
        rec.setProductName(abtAcct.tffa__LinkedApplication__r.tffa__Product__r.Name);
        String refNo = getRefNo(achdata.odfiId);
        rec.setTraceNo(refNo);
        rec.setPcbAcctNo(abtAcct.tffa__LinkedApplication__r.tffa__AccountNumber__c);
        rec.setAchFileName(achdata.achFileName);
        recs.add(rec);
        abtAcct.put('TraceNo__c', rec.getTraceNo());
        abtAcct.put('tffa__Status__c', 'ACH_FILE_GENERATED');
        tffa.Logger.debug('***records' + rec);
        unqCounter++;
      } catch (Exception ex) {
        abtAcct.put('tffa__Status__c', 'ACH_FILE_FAILED');
        tffa.Logger.debug('Exception   :::' + ex.getMessage() + 'LineNumber  :::' + ex.getStackTraceString());
      }
    }
    getLastNumber(achdata.abtAccts.size());
    return recs;
  }
  /*  returns unique reference number of length 15. 
        first 13 digits from getTime().
        last 2 digits from getUniqueCount().
        unqCounter is appended in order to assure uniqueness even if speed of execution is high, even less than millisecs
        after adding this method unqCounter logic may appear redundand since good amount of time consumed to access the methods and 
        access the logic and hence timestamp would be unique.
    */
  @TestVisible
  protected String getRefNo() {
    return String.valueOf(Datetime.now().getTime()) + getUniqueCount();
  }
  protected String getRefNo(String odfid) {
    String uniqueNumber = String.valueOf(unqCounter);
    String refNo = odfid + uniqueNumber.leftPad(7, '0');
    return refNo;
  }
  @TestVisible
  private String getPartyName(String personalName, String legalName) {
    if (legalName != null && legalName != '') {
      return legalName;
    } else {
      return personalName.remove(',');
    }
  }
  //returns String(length=2) for number 0 to 99
  @TestVisible
  protected String getUniqueCount() {
    String cnt = '';
    cnt = String.valueOf(Math.mod(unqCounter++, 100));
    cnt = cnt.leftPad(2, '0');
    return cnt;
  }
  @TestVisible
  private Integer getLastNumber(Integer countRecords) {
    try {
      List<TFEntries__c> tfentries = CZWTFCApplicationRepository.getTfentries();

      if (countRecords != null || countRecords > 0) {
        if (tfentries == null || tfentries.size() <= 0) {
          countRecords = 5001 + countRecords;
          TFEntries__c instfentries = new TFEntries__c();
          instfentries.LastACHFileRecNo__c = countRecords;
          CZWTFCApplicationRepository.saveSingle(instfentries);
        } else {
          TFEntries__c updtfentries = tfentries.get(0);
          updtfentries.LastACHFileRecNo__c = tfentries.get(0).LastACHFileRecNo__c + countRecords;
          CZWTFCApplicationRepository.saveSingle(updtfentries);
        }
      }
      if (tfentries == null || tfentries.size() < 1) {
        return 5001;
      } else {
        return Integer.valueOf(tfentries[0].LastACHFileRecNo__c);
      }
    } catch (Exception ex) {
      tffa.Logger.debug(ex.getMessage() + ' ' + ex.getStackTraceString());
    }
    return 5001;
  }
}