objects/tffa__AdditionalPreference__c.object
<CustomObject>
    <description>Additional preference usually captured for a party e.g. Online Banking, E-Statements. These are not specific to an application. For ones that are, use Account Preferences.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to the party whose preference is being captured.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Additional Preferences</relationshipLabel>
        <relationshipName>AdditionalPreferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Additional Preferences</relationshipLabel>
        <relationshipName>AdditionalPreferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <defaultValue>&quot;ADD_ON_SERVICE&quot;</defaultValue>
        <description>Nature of the preference.</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__AdditionalPreferenceType</valueSetName>
        </valueSet>
    </fields>
    <label>Additional Preference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Additional Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account address for purposes of statement etc. If Address Prefill Source Id is set, the address details are not persisted directly, only address id is persisted.</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ApplicationPartyXref__c.object
<CustomObject>
    <description>Each Applicant of the submission can play different roles in the application and the eventual account.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Application Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__DueDiligence__c.object
<CustomObject>
    <description>Due diligence is the process of gathering data in order to verify the identity of the applicant and to make sure they are not involved in money laundering , fraud  and high risk activities.
Tracks due diligence status for the given provider.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to related party.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Due Diligences</relationshipLabel>
        <relationshipName>DueDiligences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>The status captured for the due diligence record.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceType</valueSetName>
        </valueSet>
    </fields>
    <label>Due Diligence</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Due Diligences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Employment__c.object
<CustomObject>
    <description>Captures employment information of the applicant. Employment is a relationship between two parties, usually based on a contract where work is paid for, where one party, which may be a corporation, for profit, not-for-profit organization, co-operative or other entity is the employer and the other is the employee.</description>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Employment address</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party object</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the employment</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__EmploymentType</valueSetName>
        </valueSet>
    </fields>
    <label>Employment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Employment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Identification__c.object
<CustomObject>
    <description>Identification details of the party such as  driver license numbers, passport numbers .  Supports capture of identity document id as well which is stored as an attachment in the system.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to the parent party object</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Identifications</relationshipLabel>
        <relationshipName>Identifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>The kind of document that was examined to verify identity of the applicant. A driver&apos;s license is an example of an identity document.. The name will be defaulted to the name field</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__IdentificationType</valueSetName>
        </valueSet>
    </fields>
    <label>Identification</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Identifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyAddressXref__c.object
<CustomObject>
    <description>Association table between Party and Address . This supports capture of multiple types and also periodAtAddress.
This creates an address book of the party</description>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <description>The address lookup @managed</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyAddresses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>The party which owns the address.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>AddressXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Indicates address type. Classification of the address with respect to owning entity type. 

For individual, values are - HOME,MAILING,PERMANENT
For company, values are - REGISTERED,MAILING</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__AddressType</valueSetName>
        </valueSet>
    </fields>
    <label>Party Address Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartyAddresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__PartyPartyXref__c.object
<CustomObject>
    <description>A relationship between 2 applicants of a submission. 
Personal relationship could be SPOUSE, PARENT, FRIENDS.
Business relationship between a company and an individual could be DIRECTOR, OWNER, EXECUTIVE, PARTNER etc. In additional the ownership percentage can be captured for OWNER type of relationship. 
Relationship between 2 company type applicants can also be captured such as PARENT and SUBSIDIARY.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Party managing the relationship</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Related To</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Party Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Party Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__SubmissionPartyXref__c.object
<CustomObject>
    <description>An individual or a legal entity which is applying for certain services/products in the bank. An applicant exists only in the context of a submission.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to Party object @managed</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission object.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Submission Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/tffa__AdditionalPreferenceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ADD_ON_SERVICE</fullName>
        <label>Add-on service</label>
    </customValue>
    <customValue>
        <fullName>OTHER</fullName>
        <label>Other</label>
    </customValue>
    <description>Possible types of additional preferences. Loosely based on the source of the preference.</description>
    <masterLabel>AdditionalPreferenceType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__AddressType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HOME</fullName>
        <default>true</default>
        <label>Home</label>
    </customValue>
    <customValue>
        <fullName>PREVIOUS_HOME</fullName>
        <label>Previous Home</label>
    </customValue>
    <customValue>
        <fullName>MAILING</fullName>
        <label>Mailing</label>
    </customValue>
    <customValue>
        <fullName>PERMANENT</fullName>
        <label>Permanent</label>
    </customValue>
    <customValue>
        <fullName>REGISTERED</fullName>
        <label>Registered</label>
    </customValue>
    <customValue>
        <fullName>WORK</fullName>
        <label>Work</label>
    </customValue>
    <customValue>
        <fullName>PREVIOUS_REGISTERED</fullName>
        <label>Previous Registered</label>
    </customValue>
    <description>Classification of the address</description>
    <masterLabel>AddressType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__DueDiligenceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IDV</fullName>
    </customValue>
    <customValue>
        <fullName>CDD</fullName>
    </customValue>
    <customValue>
        <fullName>FRAUD</fullName>
        <label>Fraud</label>
    </customValue>
    <customValue>
        <fullName>OFAC</fullName>
    </customValue>
    <customValue>
        <fullName>QUALIFILE</fullName>
        <label>QualiFile</label>
    </customValue>
    <customValue>
        <fullName>IDA</fullName>
    </customValue>
    <customValue>
        <fullName>CREDIT_BUREAU</fullName>
        <label>Credit Bureau</label>
    </customValue>
    <customValue>
        <fullName>DEBIT_BUREAU</fullName>
        <label>Debit Bureau</label>
    </customValue>
    <description>Types of due diligences</description>
    <masterLabel>DueDiligenceType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__EmploymentType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>SALARIED</fullName>
        <label>Salaried</label>
    </customValue>
    <customValue>
        <fullName>CONTRACTOR</fullName>
        <label>Contractor</label>
    </customValue>
    <customValue>
        <fullName>SELF_EMPLOYED</fullName>
        <label>Self employed</label>
    </customValue>
    <customValue>
        <fullName>FULLTIME</fullName>
        <label>Full Time</label>
    </customValue>
    <customValue>
        <fullName>PARTTIME</fullName>
        <label>Part Time</label>
    </customValue>
    <customValue>
        <fullName>RETIRED</fullName>
        <label>Retired</label>
    </customValue>
    <customValue>
        <fullName>STUDENT</fullName>
        <label>Student</label>
    </customValue>
    <customValue>
        <fullName>HOMEMAKER</fullName>
        <label>Homemaker</label>
    </customValue>
    <customValue>
        <fullName>UNEMPLOYED</fullName>
        <label>Unemployed</label>
    </customValue>
    <customValue>
        <fullName>MILITARY</fullName>
        <label>Military</label>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
        <isActive>false</isActive>
        <label>Test</label>
    </customValue>
    <description>Type of the employment, Valid values are SALARIED,CONTRACTOR,SELF_EMPLOYED,RETIRED,STUDENT,UNEMPLOYED,MILITARY</description>
    <masterLabel>EmploymentType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__IdentificationType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DL</fullName>
        <label>Drivers License</label>
    </customValue>
    <customValue>
        <fullName>StateID</fullName>
        <label>State ID</label>
    </customValue>
    <customValue>
        <fullName>Passport</fullName>
    </customValue>
    <customValue>
        <fullName>StudentID</fullName>
        <label>Student ID with Photo - under 18 only</label>
    </customValue>
    <customValue>
        <fullName>Minor</fullName>
    </customValue>
    <customValue>
        <fullName>MilitaryID</fullName>
        <label>Military ID</label>
    </customValue>
    <customValue>
        <fullName>ASSUMED_NAME_CERT</fullName>
        <label>Assumed Name Certificate</label>
    </customValue>
    <customValue>
        <fullName>NONE</fullName>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>CERT_OF_FORMATION</fullName>
        <label>Certificate of Formation</label>
    </customValue>
    <customValue>
        <fullName>ARTICLES_OF_INCORPORATION</fullName>
        <label>Articles of Incorporation</label>
    </customValue>
    <customValue>
        <fullName>CERT_OF_LIMITED_PARTNERSHIP</fullName>
        <label>Certificate of Limited Partnership</label>
    </customValue>
    <customValue>
        <fullName>BUSINESS_LICENSE</fullName>
        <label>Business License</label>
    </customValue>
    <customValue>
        <fullName>GreenCard</fullName>
        <label>Green Card</label>
    </customValue>
    <customValue>
        <fullName>ForeignPassport</fullName>
        <label>FOREIGN PASSPORT</label>
    </customValue>
    <customValue>
        <fullName>ResidentAlienCard</fullName>
        <label>RESIDENT ALIEN CARD</label>
    </customValue>
    <customValue>
        <fullName>Matricula</fullName>
        <label>MATRICULA</label>
    </customValue>
    <customValue>
        <fullName>USImmigrationVisa</fullName>
        <label>US IMMIGRATION VISA</label>
    </customValue>
    <description>The list of supported identification type for a party</description>
    <masterLabel>IdentificationType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

classes/CZWTFCPartyRepository.cls
global with sharing class CZWTFCPartyRepository extends tffa.AbstractRepository {
  /*
   * @descrption used to get tffa__Party__c in list according to Party id
   * @params partyID
   * @return List<tffa__Party__c>
   */
  public static tffa__Party__c fetchPartyById(String id) {
    String q = new tffa.QueryBuilder(tffa__Party__c.SObjectType).selectFields().whereClause('Id', '=:attr1').build().toQuery();

    List<tffa__Party__c> partyList = doQuery(q, new List<Object>{ id });

    return partyList.isEmpty() ? null : partyList[0];
  }

  /**
   * Fetches a party entity by id along with all child relationships
   */
  public static tffa__Party__c findByIdWithChildObjects(String id) {
    String q = new tffa.QueryBuilder(tffa__Party__c.SObjectType)
      .selectFields() /** */
      .selectChildObject('tffa__AddressXrefs__r') /** */
      .selectFields() /** */ /** */
      .selectObject('tffa__Address__r') /** */ /** */
      .selectFields() /** */ /** */
      .build() /** */
      .build() /** */ /** */ /** */
      .selectChildObject('Identifications__r') /** */ /** */ /** */
      .selectFields() /** */ /** */ /** */
      .build() /** */ /** */ /** */ /** */
      .selectChildObject('tffa__DueDiligences__r') /** */ /** */ /** */ /** */
      .selectFields() /** */ /** */ /** */ /** */
      .build()
      .selectChildObject('tffa__Employments__r') /** */ /** */ /** */ /** */
      .selectFields() /** */ /** */ /** */ /** */
      .build()
      .selectChildObject('tffa__AdditionalPreferences__r') /** */ /** */ /** */ /** */
      .selectFields() /** */ /** */ /** */ /** */
      .build()
      .selectChildObject('tffa__Applications__r') /** */ /** */ /** */ /** */
      .selectFields() /** */ /** */ /** */ /** */
      .build()
      .whereClause('Id', '=:attr1')
      .withLimit(1)
      .build()
      .toQuery();

    List<tffa__Party__c> party = (List<tffa__Party__c>) doQuery(q, new List<Object>{ id });
    return party.isEmpty() ? null : party[0];
  }

  /**
   * Fetches a party entity by id along with all child relationships without dd
   */
  public static tffa__Party__c findByIdWithChildObjs(String id) {
    String q = new tffa.QueryBuilder(tffa__Party__c.SObjectType)
      .selectFields() /** */
      .selectChildObject('tffa__AddressXrefs__r') /** */
      .selectFields() /** */ /** */
      .selectObject('tffa__Address__r') /** */ /** */
      .selectFields() /** */ /** */
      .build() /** */
      .build() /** */ /** */ /** */
      .selectChildObject('Identifications__r') /** */ /** */ /** */
      .selectFields() /** */ /** */ /** */
      .build() /** */ /** */ /** */ /** */
      .selectChildObject('tffa__Employments__r') /** */ /** */ /** */ /** */
      .selectFields() /** */ /** */ /** */ /** */
      .build()
      .selectChildObject('tffa__AdditionalPreferences__r') /** */ /** */ /** */ /** */
      .selectFields() /** */ /** */ /** */ /** */
      .build()
      .whereClause('Id', '=:attr1')
      .withLimit(1)
      .build()
      .toQuery();

    List<tffa__Party__c> party = (List<tffa__Party__c>) doQuery(q, new List<Object>{ id });
    return party.isEmpty() ? null : party[0];
  }

  public static List<tffa__Party__c> save(List<tffa__Party__c> entities) {
    return (List<tffa__Party__c>) doUpsert(entities);
  }

  public static List<tffa__AdditionalPreference__c> saveAddPreferences(List<tffa__AdditionalPreference__c> entities) {
    return (List<tffa__AdditionalPreference__c>) doUpsert(entities);
  }

  /**
   * Fetches MXConfiguration__mdt corresponding to the API
   */
  public static MXConfiguration__mdt fetchMxParams(String mxServiceMapper) {
    String q = new tffa.QueryBuilder(MXConfiguration__mdt.SObjectType)
      .selectFields()
      .whereClause('DeveloperName', '= :attr1')
      .build()
      .toQuery();
    //List<MXConfiguration__mdt> result = Database.query(q);
    List<MXConfiguration__mdt> result = (List<MXConfiguration__mdt>) doQuery(q, new List<Object>{ mxServiceMapper });
    return result.isEmpty() ? new MXConfiguration__mdt() : result[0];
  }

  public static List<tffa__Party__c> findAllPartiesByIds(List<String> ids) {
    String q = new tffa.QueryBuilder(tffa__Party__c.SObjectType)
      .selectFields()
      .selectChildObject('tffa__AddressXrefs__r') /** */
      .selectFields() /** */ /** */
      .selectObject('tffa__Address__r') /** */ /** */
      .selectFields() /** */ /** */
      .build() /** */
      .whereClause('tffa__Type__c', '= :attr1')
      .build()
      .whereClause('Id', 'In :attr2')
      .build()
      .toQuery();
    return doQuery(q, new List<Object>{ 'HOME', ids });
  }

  public static Map<String, tffa__Party__c> findAllPartiesWithChildByIds(tffa__Submission__c sub) {
    List<String> ids = new List<String>();
    Map<String, tffa__Party__c> partyMap = new Map<String, tffa__Party__c>();
    for (tffa__SubmissionPartyXref__c subP : sub.tffa__PartyXrefs__r) {
      ids.add(subP.tffa__Party__c);
    }

    if (!ids.isEmpty()) {
      String q = new tffa.QueryBuilder(tffa__Party__c.SObjectType)
        .selectFields()
        .selectChildObject('tffa__AddressXrefs__r') /** */
        .selectFields() /** */ /** */
        .selectObject('tffa__Address__r') /** */ /** */
        .selectFields() /** */ /** */
        .build() /** */
        .build() /** */ /** */ /** */
        .selectChildObject('Identifications__r') /** */ /** */ /** */
        .selectFields() /** */ /** */ /** */
        .build() /** */ /** */ /** */ /** */
        .selectChildObject('tffa__DueDiligences__r') /** */ /** */ /** */ /** */
        .selectFields() /** */ /** */ /** */ /** */
        .build()
        .selectChildObject('tffa__AdditionalPreferences__r') /** */ /** */ /** */ /** */
        .selectFields() /** */ /** */ /** */ /** */
        .build()
        .whereClause('Id', 'In :attr1')
        .build()
        .toQuery();

      List<tffa__Party__c> partyList = doQuery(q, new List<Object>{ ids });
      if (partyList != null && !partyList.isEmpty()) {
        for (tffa__Party__c partyObj : partyList) {
          partyMap.put(partyObj.Id, partyObj);
        }
      }
    }
    return partyMap;
  }

  /**
   *
   */
  public static List<tffa__Party__c> findPartyObj(String emailAddress, String lastName, String last3SSN) {
    String q = new tffa.QueryBuilder(tffa__Party__c.SObjectType)
      .selectFields()
      .whereClause('tffa__PrimaryEmail__c', '=:attr1')
      .opAnd()
      .whereClause('tffa__LastName__c', '=:attr2')
      .opAnd()
      .whereClause('tffa__LastnNationalIdentifierValue__c', '=:attr3')
      .build()
      .toQuery();
    //return Database.query(q);
    return (List<tffa__Party__c>) doQuery(q, new List<Object>{ emailAddress, lastName, last3SSN });
  }

  /**
   *
   */
  public static List<tffa__Party__c> findPartyObject(String emailAddress, String lastName, String last3SSN, String brand) {
    String q = new tffa.QueryBuilder(tffa__Party__c.SObjectType)
      .selectFields()
      .whereClause('tffa__PrimaryEmail__c', '=:attr1')
      .opAnd()
      .whereClause('tffa__LastName__c', '=:attr2')
      .opAnd()
      .whereClause('tffa__LastnNationalIdentifierValue__c', '=:attr3')
      .opAnd()
      .whereClause('tffa__BrandCode__c', '=:attr4')
      .build()
      .toQuery();
    //return Database.query(q);
    return (List<tffa__Party__c>) doQuery(q, new List<Object>{ emailAddress, lastName, last3SSN, brand });
  }

  public static tffa__Employment__c findEmploymentByPartyID(String id) {
    String q = new tffa.QueryBuilder(tffa__Employment__c.SObjectType)
      .selectFields()
      .whereClause('tffa__Party__c', '=:attr1')
      .build()
      .toQuery();
    List<tffa__Employment__c> empList = (List<tffa__Employment__c>) doQuery(q, new List<Object>{ id });
    return empList.isEmpty() ? null : empList[0];
  }

  public static List<tffa__SubmissionPartyXref__c> saveSubPartyXref(List<tffa__SubmissionPartyXref__c> entities) {
    return (List<tffa__SubmissionPartyXref__c>) doUpsert(entities);
  }

  public static tffa__Party__c findByIdWithOLBAddPref(String id) {
    String q = new tffa.QueryBuilder(tffa__Party__c.SObjectType)
      .selectFields()
      .selectChildObject('tffa__AdditionalPreferences__r')
      .selectFields()
      .whereClause('tffa__AddOnServiceType__c', '=:attr1')
      .build()
      .whereClause('Id', '=:attr2')
      .withLimit(1)
      .build()
      .toQuery();
    List<tffa__Party__c> party = (List<tffa__Party__c>) doQuery(q, new List<Object>{ FISCCIntegrationConstants.ADDON_OLB_TYPE, id });
    return party.isEmpty() ? null : party[0];
  }

  public static tffa__SubmissionPartyXref__c findSubPartyById(String id) {
    List<String> queryParams = new List<String>();
    queryParams.add(id);
    String q = new tffa.QueryBuilder(tffa__SubmissionPartyXref__c.SObjectType)
      .selectFields()
      .whereClause('tffa__Party__c', '=:attr1')
      .build()
      .toQuery();

    List<tffa__SubmissionPartyXref__c> submissionJointPartyXref = doQuery(q, queryParams);

    return submissionJointPartyXref.isEmpty() ? null : submissionJointPartyXref[0];
  }

  public static tffa__AdditionalPreference__c findAdditionalPreferenceByPartyIdAndCode(String id, String code) {
    String q = new tffa.QueryBuilder(tffa__AdditionalPreference__c.SObjectType)
      .selectFields()
      .whereClause('tffa__Code__c', '=:attr1')
      .opAnd()
      .whereClause('tffa__Party__c', '=:attr2')
      .build()
      .toQuery();
    List<tffa__AdditionalPreference__c> additionalPreference = (List<tffa__AdditionalPreference__c>) doQuery(
      q,
      new List<Object>{ code, id }
    );
    return additionalPreference.isEmpty() ? null : additionalPreference[0];
  }

  public static List<tffa__Party__c> fetchPartyByMDMUploadStatus(String status) {
    String q = new tffa.QueryBuilder(tffa__Party__c.SObjectType)
      .selectFields()
      .selectChildObject('tffa__Submissions__r')
      .selectFields()
      .build()
      .whereClause('MDMUploadStatus__c', '=:attr1')
      .opAnd()
      .whereClause('MDMUploadRetryCount__c', ' < :attr2')
      .build()
      .toQuery();

    WintrustEnvConfig__mdt wintrustEnvConfig = CZWTFCHelperRepository.fetchWintrustEnvConfig();

    List<tffa__Party__c> partyList = doQuery(q, new List<Object>{ status, wintrustEnvConfig.BatchRetryCount__c });

    return partyList.isEmpty() ? new List<tffa__Party__c>() : partyList;
  }

  public static List<tffa__Party__c> fetchPartyByIds(Set<String> ids) {
    String q = new tffa.QueryBuilder(tffa__Party__c.SObjectType).selectFields().whereClause('Id', ' IN :attr1').build().toQuery();

    List<tffa__Party__c> partyList = doQuery(q, new List<Object>{ ids });

    return partyList.isEmpty() ? new List<tffa__Party__c>() : partyList;
  }

  /**
   * Fetches parties by ids.
   */
  public static List<tffa__Party__c> findByIdWithAddressType(Set<String> ids, Set<String> addressTypes) {
    String q = new tffa.QueryBuilder(tffa__Party__c.SObjectType)
      .selectFields()
      .selectChildObject('AddressXrefs__r')
      .selectFields()
      .selectObject('Address__r')
      .selectFields()
      .build()
      .whereClause('Type__c', 'in :attr2')
      .build()
      .whereClause('Id', 'in :attr1')
      .withLimit(ids.size())
      .build()
      .toQuery();
    return doQuery(q, new List<Object>{ ids, addressTypes });
  }
}