objects/tffa__DueDiligence__c.object
<CustomObject>
    <description>Due diligence is the process of gathering data in order to verify the identity of the applicant and to make sure they are not involved in money laundering , fraud  and high risk activities.
Tracks due diligence status for the given provider.</description>
    <fields>
        <fullName>DueDiligenceResponse__c</fullName>
        <description>Due diligence Response</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Due dilgience Response</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>tffa__ConversationId__c</fullName>
        <description>Conversation id when exchanging information with a remote interface.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Conversation id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ExternalQuestionnaireId__c</fullName>
        <description>Stores the reference to an external questionnaire or quiz. Populated when OOW questions are returned in a due-diligence activity.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>External Questionnaire Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to related party.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Due Diligences</relationshipLabel>
        <relationshipName>DueDiligences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__ProviderStatus__c</fullName>
        <description>Stores the status, returned by the provider. This is specific to the provider implementation. The status field helps standardize the provider status across all provider implementations.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Provider__c</fullName>
        <description>The provider for the diligence verification. This could be the name of the interface provider.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ReportName__c</fullName>
        <description>Name of the associated report.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Report name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Response__c</fullName>
        <description>Certain providers respond with JSON /HTML as response which can be stored in this field and parsed for display purposes.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Response</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>tffa__Score__c</fullName>
        <description>A computed score as per the provider and type of due diligence. In some cases like QUALIFILE, the interface may provide a score.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Score</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>The status captured for the due diligence record.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>The status captured for the due diligence record.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceType</valueSetName>
        </valueSet>
    </fields>
    <label>Due Diligence</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Due Diligences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__DueDiligenceItem__c.object
<CustomObject>
    <description>List of answers  which are captured for the applicant against the CDD questions. CDD questions can be fetched from KBA third party systems.</description>
    <fields>
        <fullName>tffa__Choices__c</fullName>
        <description>A JSON string representing a choice array ({ name: String, value: String }[]). Each choice has a name which is the label or display name or text of the choice and a value which is the value or id of the choice. Applicable when the answer is of type SELECT.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Choices</label>
        <length>1024</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>A logical name that uniquely identifies the item among a list. Can be a question code.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__DueDiligence__c</fullName>
        <description>Reference to parent due diligence.</description>
        <label>Due Diligence</label>
        <referenceTo>tffa__DueDiligence__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Label__c</fullName>
        <description>The question text, or a display name.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether value is required. Applicable to type QUESTION.</description>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__SortOrder__c</fullName>
        <description>The order of the item w.r.t other items.</description>
        <label>Sort order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <defaultValue>&quot;QUESTION&quot;</defaultValue>
        <description>The nature of the item. A DueDiligence item can hold OOW questions, or results related to a DueDiligence activity, e.g. name mismatch, phone mismatch, etc</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceItemType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__ValueType__c</fullName>
        <defaultValue>&quot;TEXT&quot;</defaultValue>
        <description>The type for the answer captured.</description>
        <label>Value type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__AnswerType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Value__c</fullName>
        <description>The value of the answer captured.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Due Diligence Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Due Diligence Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>IsDobMatch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if DOB match in fisdss</description>
        <label>IsDobMatch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSsnMatch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if SSN match in fisdss</description>
        <label>IsSsnMatch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>KYCFraudText__c</fullName>
        <description>KYC Fraud Text</description>
        <encryptionScheme>None</encryptionScheme>
        <label>KYC Fraud Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NumberOfInquires__c</fullName>
        <description>Number Of Inquires</description>
        <label>NumberOfInquires</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalAmountApplicantOwes__c</fullName>
        <description>Total Amount Applicant Owes</description>
        <label>TotalAmountApplicantOwes</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tffa__DebitBureauScore__c</fullName>
        <description>Score given by a debit bureau (e.g. ChexSystems) to the party. e.g. QualiFile score. It is a reflection of the party&apos;s banking behavour.</description>
        <label>Debit Bureau score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tffa__DebitBureauStatus__c</fullName>
        <description>A rollup of status across DueDiligence(s) of type DEBIT_BUREAU.</description>
        <label>Debit Bureau status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__IDAStatus__c</fullName>
        <description>A rollup of status across DueDiligence(s) of type IDA.</description>
        <label>IDA status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__IDVStatus__c</fullName>
        <description>A rollup of status across DueDiligence(s) of type IDV.</description>
        <label>IDV Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__OFACStatus__c</fullName>
        <description>A rollup of status across DueDiligence(s) of type OFAC.</description>
        <label>OFAC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the submission</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__SubmissionPartyXref__c.object
<CustomObject>
    <description>An individual or a legal entity which is applying for certain services/products in the bank. An applicant exists only in the context of a submission.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to Party object @managed</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__SortOrder__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Controls the relative order of the item in a list.</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>The data entry status of the party in this submission. This is applicable in case of joint applications where the party fills data individually</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionPartyStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission object.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Submission Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/tffa__AnswerType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CHECKBOX</fullName>
        <label>Checkbox</label>
    </customValue>
    <customValue>
        <fullName>TEXT</fullName>
        <label>Text</label>
    </customValue>
    <customValue>
        <fullName>LABEL</fullName>
        <label>Label</label>
    </customValue>
    <customValue>
        <fullName>NUMBER</fullName>
        <label>Number</label>
    </customValue>
    <customValue>
        <fullName>SELECT</fullName>
        <label>Select</label>
    </customValue>
    <customValue>
        <fullName>RADIO_GROUP</fullName>
        <label>Radio Group</label>
    </customValue>
    <customValue>
        <fullName>CHECKBOX_GROUP</fullName>
        <label>Checkbox Group</label>
    </customValue>
    <customValue>
        <fullName>MULTISELECT</fullName>
        <label>Multiselect</label>
    </customValue>
    <customValue>
        <fullName>DATE</fullName>
        <label>Date</label>
    </customValue>
    <customValue>
        <fullName>CURRENCY</fullName>
        <label>Currency</label>
    </customValue>
    <customValue>
        <fullName>SSN</fullName>
    </customValue>
    <customValue>
        <fullName>EMAIL</fullName>
        <label>Email</label>
    </customValue>
    <customValue>
        <fullName>PERCENT</fullName>
        <label>Percent</label>
    </customValue>
    <customValue>
        <fullName>TIN</fullName>
    </customValue>
    <customValue>
        <fullName>DATETIME</fullName>
        <label>Date/Time</label>
    </customValue>
    <customValue>
        <fullName>TEXTAREA</fullName>
        <label>Text Area</label>
    </customValue>
    <customValue>
        <fullName>SLIDER</fullName>
        <label>Slider</label>
    </customValue>
    <customValue>
        <fullName>PHONE</fullName>
        <label>Phone</label>
    </customValue>
    <customValue>
        <fullName>ADDRESS</fullName>
        <label>Address</label>
    </customValue>
    <customValue>
        <fullName>LOV</fullName>
        <isActive>false</isActive>
        <label>LOV</label>
    </customValue>
    <description>Type of answer. These correspond to the simple components supported by UI.</description>
    <masterLabel>AnswerType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__DueDiligenceItemType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>QUESTION</fullName>
        <label>Question</label>
    </customValue>
    <customValue>
        <fullName>RESPONSE</fullName>
        <label>Response</label>
    </customValue>
    <description>Types of DueDiligenceItem(s). A DueDiligenceItem can be used to store OOW Questions, or results related to a DueDiligence activity.</description>
    <masterLabel>DueDiligenceItemType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__DueDiligenceStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PASSED</fullName>
        <label>✅Passed</label>
    </customValue>
    <customValue>
        <fullName>DECLINED</fullName>
        <label>❌Declined</label>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
        <label>❌Failed</label>
    </customValue>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <label>🔶In progress</label>
    </customValue>
    <customValue>
        <fullName>CHALLENGED</fullName>
        <label>⚠️Challenged</label>
    </customValue>
    <customValue>
        <fullName>REVIEW</fullName>
        <label>⚠️Review</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>❌Expired</label>
    </customValue>
    <description>States of a due diligence activity.</description>
    <masterLabel>DueDiligenceStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__DueDiligenceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IDV</fullName>
    </customValue>
    <customValue>
        <fullName>CDD</fullName>
    </customValue>
    <customValue>
        <fullName>FRAUD</fullName>
        <label>Fraud</label>
    </customValue>
    <customValue>
        <fullName>OFAC</fullName>
    </customValue>
    <customValue>
        <fullName>QUALIFILE</fullName>
        <label>QualiFile</label>
    </customValue>
    <customValue>
        <fullName>IDA</fullName>
    </customValue>
    <customValue>
        <fullName>CREDIT_BUREAU</fullName>
        <label>Credit Bureau</label>
    </customValue>
    <customValue>
        <fullName>DEBIT_BUREAU</fullName>
        <label>Debit Bureau</label>
    </customValue>
    <description>Types of due diligences</description>
    <masterLabel>DueDiligenceType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionPartyStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>COMPLETE</fullName>
        <label>Complete</label>
    </customValue>
    <customValue>
        <fullName>INCOMPLETE</fullName>
        <label>Incomplete</label>
    </customValue>
    <description>The status of the party in the submission. More akin to data entry status</description>
    <masterLabel>SubmissionPartyStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>ABANDONED</fullName>
        <label>Abandoned</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>SAVED</fullName>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>SUBMITTED</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>Indicates current status of the submission.This will be computed and be useful for regulations.</description>
    <masterLabel>SubmissionStatus</masterLabel>
</GlobalValueSet>

classes/FISDSSService.cls
public with sharing class FISDSSService {
  /**
   * @description stores the IDA related fields
   * @param IDAResponseDTO idaResp
   * @return tffa__DueDiligence__c
   */
  @TestVisible
  private static tffa__DueDiligence__c buildIDADueDiligence(FISIDAResponseDTO idaResp) {
    tffa__DueDiligence__c dueDiligence = new tffa__DueDiligence__c();
    List<tffa__DueDiligenceItem__c> ddItems = new List<tffa__DueDiligenceItem__c>();
    Integer counter = 0;
    try {
      if (idaResp != null) {
        dueDiligence.Name = 'FIS OOW';
        dueDiligence.tffa__Type__c = 'IDA';
        dueDiligence.tffa__Status__c = 'CHALLENGED';
        dueDiligence.tffa__Provider__c = 'FIS IDA';
        dueDiligence.tffa__ExternalQuestionnaireId__c = String.valueOf(idaResp.quizId);
        dueDiligence.tffa__ConversationId__c = String.valueOf(idaResp.transId);

        tffa.SObjectAssembler asm = new tffa.SObjectAssembler(dueDiligence);
        if (idaResp.idaQuestion1 != null)
          ddItems.add(FISDSSService.createDueDiligencItem(idaResp.idaQuestion1, counter++));
        if (idaResp.idaQuestion2 != null)
          ddItems.add(FISDSSService.createDueDiligencItem(idaResp.idaQuestion2, counter++));
        if (idaResp.idaQuestion3 != null)
          ddItems.add(FISDSSService.createDueDiligencItem(idaResp.idaQuestion3, counter++));
        if (idaResp.idaQuestion4 != null)
          ddItems.add(FISDSSService.createDueDiligencItem(idaResp.idaQuestion4, counter++));
        if (idaResp.idaQuestion5 != null)
          ddItems.add(FISDSSService.createDueDiligencItem(idaResp.idaQuestion5, counter++));
        if (idaResp.idaQuestion6 != null)
          ddItems.add(FISDSSService.createDueDiligencItem(idaResp.idaQuestion6, counter++));
        if (idaResp.idaQuestion7 != null)
          ddItems.add(FISDSSService.createDueDiligencItem(idaResp.idaQuestion7, counter++));
        if (idaResp.idaQuestion8 != null)
          ddItems.add(FISDSSService.createDueDiligencItem(idaResp.idaQuestion8, counter++));
        if (idaResp.idaQuestion9 != null)
          ddItems.add(FISDSSService.createDueDiligencItem(idaResp.idaQuestion9, counter++));
        asm.addChildObjects('Items__r', ddItems);
        dueDiligence = (tffa__DueDiligence__c) asm.assemble();
      }
    } catch (Exception e) {
      tffa.Logger.error('Exception in processKBAQuestions ' + e.getStackTraceString() + e.getLineNumber() + e.getMessage());
    }
    return dueDiligence;
  }

  /**
   * @description remove old due diligence from salesforce
   * @param tffa__Party__c partyObj
   * @return tffa__Party__c
   **/
  public static void removeExistingDueDiligence(tffa__Party__c partyObj, List<String> typeList) {
    CZWTFCHelperRepository.removeDDByPartyId(partyObj.id, typeList);
  }

  /**
   * @description stores the DueDiligenceItem related to DueDiligence
   * @param IdaQuestion idaQuestion, Integer counter
   * @return tffa__DueDiligenceItem__c
   */
  @TestVisible
  private static tffa__DueDiligenceItem__c createDueDiligencItem(FISIDAResponseDTO.IdaQuestion idaQuestion, Integer counter) {
    counter++;
    tffa__DueDiligenceItem__c item = new tffa__DueDiligenceItem__c(
      Name = idaQuestion.questionText.left(80),
      tffa__Label__c = idaQuestion.questionText,
      tffa__Code__c = String.valueOf(idaQuestion.id),
      tffa__ValueType__c = 'RADIO_GROUP',
      tffa__Required__c = true,
      tffa__SortOrder__c = counter
    );
    List<Object> choices = new List<Object>();
    if (!String.isBlank(idaQuestion.answer1Text) && !String.isBlank(idaQuestion.answer1Id)) {
      choices.add(new Map<String, String>{ 'name' => idaQuestion.answer1Text, 'value' => String.valueOf(idaQuestion.answer1Id) });
    }
    if (!String.isBlank(idaQuestion.answer2Text) && !String.isBlank(idaQuestion.answer2Id)) {
      choices.add(new Map<String, String>{ 'name' => idaQuestion.answer2Text, 'value' => String.valueOf(idaQuestion.answer2Id) });
    }
    if (!String.isBlank(idaQuestion.answer3Text) && !String.isBlank(idaQuestion.answer3Id)) {
      choices.add(new Map<String, String>{ 'name' => idaQuestion.answer3Text, 'value' => String.valueOf(idaQuestion.answer3Id) });
    }
    if (!String.isBlank(idaQuestion.answer4Text) && !String.isBlank(idaQuestion.answer4Id)) {
      choices.add(new Map<String, String>{ 'name' => idaQuestion.answer4Text, 'value' => String.valueOf(idaQuestion.answer4Id) });
    }
    if (!String.isBlank(idaQuestion.answer5Text) && !String.isBlank(idaQuestion.answer5Id)) {
      choices.add(new Map<String, String>{ 'name' => idaQuestion.answer5Text, 'value' => String.valueOf(idaQuestion.answer5Id) });
    }
    if (!String.isBlank(idaQuestion.answer6Text) && !String.isBlank(idaQuestion.answer6Id)) {
      choices.add(new Map<String, String>{ 'name' => idaQuestion.answer6Text, 'value' => String.valueOf(idaQuestion.answer6Id) });
    }
    item.tffa__Choices__c = JSON.serialize(choices);
    return item;
  }

  public static tffa__Party__c upsertDueDiligence(tffa__Party__c partyObj, FISIDAResponseDTO idaResp) {
    List<tffa__DueDiligence__c> ddList = new List<tffa__DueDiligence__c>();
    tffa.SObjectAssembler asm;

    if (idaResp != null && idaResp.errorCd == null && idaResp.idaQuestion1 != null) {
      partyObj.tffa__IDAStatus__c = 'CHALLENGED';
      tffa__DueDiligence__c idaDD = FISDSSService.buildIDADueDiligence(idaResp);
      ddList.add(idaDD);
    } else if (idaResp != null && idaResp.errorCd != null) {
      tffa__DueDiligence__c dueDiligence = new tffa__DueDiligence__c();
      dueDiligence.Name = 'FIS OOW';
      dueDiligence.tffa__Type__c = 'IDA';
      dueDiligence.tffa__Score__c = '0';
      dueDiligence.tffa__Status__c = 'FAILED';
      dueDiligence.tffa__Provider__c = 'FIS IDA';
      String response = 'ErrorCode: ' + idaResp.errorCd + ' Text: ' + idaResp.errorTxt;
      dueDiligence.tffa__Response__c = response.replace('null', '');
      partyObj.tffa__IDAStatus__c = 'FAILED';
      ddList.add(dueDiligence);
    }

    // Update Party And Insert IDA DD

    if (!ddList.isEmpty()) {
      if (!Test.isRunningTest()) {
        tffa.DueDiligenceService.createOrUpdate(partyObj.Id, ddList);
      }
      List<tffa__Party__c> partyList = CZWTFCPartyRepository.save(new List<tffa__Party__c>{ partyObj });
      asm = new tffa.SObjectAssembler(partyList[0]);
      asm.addChildObjects('DueDiligences__r', ddList);
    } else {
      List<tffa__Party__c> partyList = CZWTFCPartyRepository.save(new List<tffa__Party__c>{ partyObj });
      asm = new tffa.SObjectAssembler(partyList[0]);
    }
    tffa.Logger.debug('parseIDAResponse Flow Completed');
    return (tffa__Party__c) asm.assemble();
  }

  public static tffa__Party__c doAnswersCheckAndBuildDD(
    tffa__Party__c partyObj,
    FISIDAResponseDTO idaDecision,
    tffa__DueDiligence__c idaDD
  ) {
    tffa.Logger.debug('inside doAnswersCheckAndBuildDD response : ' + idaDecision);
    List<tffa__DueDiligence__c> ddList = new List<tffa__DueDiligence__c>();
    tffa.SObjectAssembler asm;

    if (idaDecision != null) {
      idaDD.tffa__Score__c = (idaDecision.score != null) ? String.valueOf(idaDecision.score) : '';
      idaDD.tffa__ProviderStatus__c = (idaDecision.decision != null) ? String.valueOf(idaDecision.decision) : '';
      if (idaDecision.decision != null && idaDecision.decision.containsIgnoreCase('Pass')) {
        partyObj.tffa__IDAStatus__c = 'PASSED';
        idaDD.tffa__Status__c = 'PASSED';
      } else if (idaDecision.decision != null && idaDecision.decision.containsIgnoreCase('Fail')) {
        partyObj.tffa__IDAStatus__c = 'DECLINED';
        partyObj.tffa__OFACStatus__c = 'FAILED';
        partyObj.tffa__DebitBureauStatus__c = 'FAILED';
        partyObj.tffa__IDVStatus__c = 'FAILED';
        idaDD.tffa__Status__c = 'DECLINED';
      } else {
        partyObj.tffa__IDAStatus__c = 'FAILED';
        partyObj.tffa__OFACStatus__c = 'FAILED';
        partyObj.tffa__DebitBureauStatus__c = 'FAILED';
        partyObj.tffa__IDVStatus__c = 'FAILED';
        String response = 'Error code: ' + idaDecision.errorCd + ' Text: ' + idaDecision.errorTxt;
        idaDD.tffa__Response__c = response.replace('null', '');
        idaDD.tffa__Status__c = 'FAILED';
      }
      asm = new tffa.SObjectAssembler(idaDD);
      if (idaDecision.idaOid != null) {
        String wrongAnswer = String.valueOf(idaDecision.base - idaDecision.score);
        Map<String, String> ddItemMap = new Map<String, String>{
          'Result' => String.valueOf(idaDecision.decision),
          'Ida Oid ' => String.valueOf(idaDecision.idaOid),
          'Number of Wrong Answers' => wrongAnswer,
          'Provider' => 'FIS OOW'
        };
        for (String code : ddItemMap.keySet()) {
          tffa__DueDiligenceItem__c ddItem = new tffa__DueDiligenceItem__c();
          ddItem.Name = code;
          ddItem.tffa__Code__c = code;
          ddItem.tffa__Value__c = ddItemMap.get(code);
          asm.addChildObject('tffa__Items__r', ddItem);
        }
      }
      idaDD = (tffa__DueDiligence__c) asm.assemble();
      ddList.add(idaDD);
    } else {
      idaDD.tffa__Score__c = '';
      idaDD.tffa__ProviderStatus__c = '';
      idaDD.tffa__Status__c = 'FAILED';
      partyObj.tffa__IDAStatus__c = 'FAILED';
      partyObj.tffa__OFACStatus__c = 'FAILED';
      partyObj.tffa__DebitBureauStatus__c = 'FAILED';
      partyObj.tffa__IDVStatus__c = 'FAILED';
      String response = 'ErrorCode: ' + idaDecision.errorCd + ' Text: ' + idaDecision.errorTxt;
      idaDD.tffa__Response__c = response.replace('null', '');
      asm = new tffa.SObjectAssembler(idaDD);
      idaDD = (tffa__DueDiligence__c) asm.assemble();
      ddList.add(idaDD);
    }

    if (!ddList.isEmpty()) {
      if (!Test.isRunningTest()) {
        tffa.DueDiligenceService.createOrUpdate(partyObj.Id, ddList);
      }
      List<tffa__Party__c> partyList = CZWTFCPartyRepository.save(new List<tffa__Party__c>{ partyObj });
      asm = new tffa.SObjectAssembler(partyList[0]);
      asm.addChildObjects('DueDiligences__r', ddList);
    } else {
      List<tffa__Party__c> partyList = CZWTFCPartyRepository.save(new List<tffa__Party__c>{ partyObj });
      asm = new tffa.SObjectAssembler(partyList[0]);
    }
    tffa.Logger.debug('doAnswersCheckAndBuildDD Flow Completed');
    return (tffa__Party__c) asm.assemble();
  }

  @TestVisible
  public static tffa__Party__c processIDVResult(tffa__Party__c partyObj, FISIDVResponseDTO idvResp) {
    try {
      List<tffa__DueDiligence__c> ddList = new List<tffa__DueDiligence__c>();
      tffa.SObjectAssembler asm;

      tffa__DueDiligence__c idvDD = new tffa__DueDiligence__c();
      tffa__SubmissionPartyXref__c subPartyObj = CZWTFCPartyRepository.findSubPartyById(partyObj.Id);
      String reportName = 'idv_report.html';
      if (idvResp != null && String.isBlank(idvResp.consumer.errorCd)) {
        try {
          if (idvResp.consumer != null && idvResp.consumer.chexsystemsResponse != null) {
            if (idvResp.consumer.chexsystemsResponse.consumerPreviousInquiry != null) {
              if (String.isNotBlank(idvResp.consumer.chexsystemsResponse.consumerPreviousInquiry.previousInquiryTotalQty)) {
                String noOfInq = idvResp.consumer.chexsystemsResponse.consumerPreviousInquiry.previousInquiryTotalQty;
                partyObj.NumberOfInquires__c = Integer.valueof(noOfInq);
              } else {
                partyObj.NumberOfInquires__c = 0;
              }
            }

            partyObj.KYCFraudText__c = idvResp.consumer.chexsystemsResponse.fraudFinderResponseTxt;

            if (
              idvResp.consumer.chexsystemsResponse.closureInformation != null &&
              idvResp.consumer.chexsystemsResponse.closureInformation.reportedClosure != null &&
              !idvResp.consumer.chexsystemsResponse.closureInformation.reportedClosure.isEmpty()
            ) {
              Decimal totalChrgAmnt = 0;
              for (Integer idx = 0; idx < idvResp.consumer.chexsystemsResponse.closureInformation.reportedClosure.size(); idx++) {
                if (
                  String.isNotBlank(idvResp.consumer.chexsystemsResponse.closureInformation.reportedClosure[idx].originalChargeOffAmt) &&
                  String.isNotBlank(idvResp.consumer.chexsystemsResponse.closureInformation.reportedClosure[idx].settlementPaidCd) &&
                  idvResp.consumer.chexsystemsResponse.closureInformation.reportedClosure[idx].settlementPaidCd.equalsIgnoreCase('N')
                ) {
                  String chrgAmnt = idvResp.consumer.chexsystemsResponse.closureInformation.reportedClosure[idx].originalChargeOffAmt;
                  totalChrgAmnt += Decimal.valueof(chrgAmnt.replaceAll(',', ''));
                } else {
                  totalChrgAmnt += 0;
                }
              }
              partyObj.TotalAmountApplicantOwes__c = totalChrgAmnt;
            }
          }
        } catch (Exception ex) {
          tffa.Logger.error(
            'Exception in processing charge amnt and NumberOfInquires from Response DTO ' +
            ex.getStackTraceString() +
            ex.getLineNumber() +
            ' ' +
            ex.getMessage()
          );
        }

        if (
          idvResp.consumer.identityManagerResponse != null &&
          idvResp.consumer.identityManagerResponse.validationsResult != null &&
          String.isBlank(idvResp.consumer.identityManagerResponse.errorCd) &&
          String.isBlank(idvResp.consumer.identityManagerResponse.errorInformation)
        ) {
          partyObj.IsDobMatch__c = idvResp.consumer.identityManagerResponse.validationsResult.dobCheckOk;
          partyObj.IsSsnMatch__c = idvResp.consumer.identityManagerResponse.validationsResult.ssnCheckOk;
          partyObj.tffa__IDVStatus__c = idvResp.consumer.identityManagerResponse.validationsResult.idCheckOk ? 'PASSED' : 'DECLINED';

          idvDD.Name = 'FIS IDV';
          idvDD.tffa__Type__c = 'IDV';
          idvDD.tffa__Status__c = idvResp.consumer.identityManagerResponse.validationsResult.idCheckOk ? 'PASSED' : 'DECLINED';
          idvDD.DueDiligenceResponse__c = String.valueof(idvResp.consumer.identityManagerResponse);
          tffa.Logger.debug('idvDD ' + idvDD);
          ddList.add(idvDD);
        } else {
          partyObj.IsDobMatch__c = false;
          partyObj.IsSsnMatch__c = false;
          partyObj.tffa__IDVStatus__c = 'FAILED';

          idvDD.Name = 'FIS IDV';
          idvDD.tffa__Type__c = 'IDV';
          idvDD.tffa__Status__c = 'FAILED';
          idvDD.DueDiligenceResponse__c = String.valueof(idvResp.consumer.identityManagerResponse);
          tffa.Logger.debug('idvDD -' + idvDD);
          ddList.add(idvDD);
        }

        tffa__DueDiligence__c ofacDD = new tffa__DueDiligence__c();
        if (idvResp.consumer.ofacResponse != null && idvResp.consumer.ofacResponse.ofacValidationsResult != null) {
          partyObj.tffa__OFACStatus__c = idvResp.consumer.ofacResponse.ofacValidationsResult.ofacHit ? 'DECLINED' : 'PASSED';

          ofacDD.Name = 'FIS OFAC';
          ofacDD.tffa__Type__c = 'OFAC';
          ofacDD.tffa__Status__c = idvResp.consumer.ofacResponse.ofacValidationsResult.ofacHit ? 'DECLINED' : 'PASSED';
          ofacDD.DueDiligenceResponse__c = String.valueof(idvResp.consumer.ofacResponse);
          tffa.Logger.debug('ofacDD ' + ofacDD);
          ddList.add(ofacDD);
        } else {
          partyObj.tffa__OFACStatus__c = 'FAILED';

          ofacDD.Name = 'FIS OFAC';
          ofacDD.tffa__Type__c = 'OFAC';
          ofacDD.tffa__Status__c = 'FAILED';
          ofacDD.DueDiligenceResponse__c = String.valueof(idvResp.consumer.ofacResponse);
          tffa.Logger.debug('ofacDD- ' + ofacDD);
          ddList.add(ofacDD);
        }

        tffa__DueDiligence__c qualifileDD = new tffa__DueDiligence__c();
        if (
          idvResp.consumer.qualifileResponse != null &&
          idvResp.consumer.qualifileResponse.accountActionInfo != null &&
          String.isBlank(idvResp.consumer.qualifileResponse.errorCd) &&
          String.isBlank(idvResp.consumer.qualifileResponse.errorInformation) &&
          String.isBlank(idvResp.consumer.qualifileResponse.errorTxt)
        ) {
          String score = idvResp.consumer.qualifileResponse.qualifileInformation.scoreNbr;

          if (idvResp.consumer.qualifileResponse.accountActionInfo.accountAcceptanceTxt.equalsIgnoreCase('ACCEPT')) {
            partyObj.tffa__DebitBureauStatus__c = 'PASSED';
            qualifileDD.tffa__Status__c = 'PASSED';
            qualifileDD.tffa__Score__c = score;
          } else if (idvResp.consumer.qualifileResponse.accountActionInfo.accountAcceptanceTxt.equalsIgnoreCase('REVIEW')) {
            partyObj.tffa__DebitBureauStatus__c = 'REVIEW';
            qualifileDD.tffa__Status__c = 'REVIEW';
            qualifileDD.tffa__Score__c = score;
          } else if (idvResp.consumer.qualifileResponse.accountActionInfo.accountAcceptanceTxt.equalsIgnoreCase('DECLINE')) {
            partyObj.tffa__DebitBureauStatus__c = 'DECLINED';
            qualifileDD.tffa__Status__c = 'DECLINED';
            qualifileDD.tffa__Score__c = score;
          } else if (
            idvResp.consumer.complianceInfo != null &&
            idvResp.consumer.complianceInfo.debitBureauComplianceInfo != null &&
            !String.isBlank(idvResp.consumer.complianceInfo.debitBureauComplianceInfo.debitFreezeMessage)
          ) {
            partyObj.tffa__DebitBureauStatus__c = 'DECLINED';
            qualifileDD.tffa__Status__c = 'DECLINED';
            qualifileDD.tffa__Score__c = score;
          } else {
            partyObj.tffa__DebitBureauStatus__c = 'FAILED';
            qualifileDD.tffa__Status__c = 'FAILED';
            qualifileDD.tffa__Score__c = '0';
          }
          partyObj.tffa__DebitBureauScore__c = Decimal.valueOf(score);

          qualifileDD.Name = 'FIS DEBIT BUREAU';
          qualifileDD.tffa__Type__c = 'DEBIT_BUREAU';
          qualifileDD.DueDiligenceResponse__c = String.valueof(idvResp.consumer.qualifileResponse);
          qualifileDD.tffa__ReportName__c = 'DebitBureau_Report';
        } else {
          partyObj.tffa__DebitBureauStatus__c = 'FAILED';
          partyObj.tffa__DebitBureauScore__c = Decimal.valueOf(0);

          qualifileDD.Name = 'FIS Qualifile';
          qualifileDD.tffa__Type__c = 'DEBIT_BUREAU';
          qualifileDD.tffa__Status__c = 'FAILED';
          qualifileDD.DueDiligenceResponse__c = String.valueof(idvResp.consumer.qualifileResponse);
          tffa.Logger.debug('qualifileDD- ' + qualifileDD);
          //ddList.add(qualifileDD);
        }

        List<tffa__DueDiligenceItem__c> ddItems = FISDSSService.createQualifileDDItems(idvResp);
        if (ddItems != null && !ddItems.isEmpty()) {
          tffa.SObjectAssembler asmQDD = new tffa.SObjectAssembler(qualifileDD);
          asmQDD.addChildObjects('Items__r', ddItems);
          ddList.add((tffa__DueDiligence__c) asmQDD.assemble());
        } else {
          ddList.add(qualifileDD);
        }
      } else {
        partyObj.tffa__DebitBureauStatus__c = 'FAILED';
        partyObj.IsDobMatch__c = false;
        partyObj.IsSsnMatch__c = false;
        partyObj.tffa__IDVStatus__c = 'FAILED';
        partyObj.tffa__OFACStatus__c = 'FAILED';
      }

      // Update Party And Insert DD
      if (!ddList.isEmpty()) {
        if (!Test.isRunningTest()) {
          tffa.DueDiligenceService.createOrUpdate(partyObj.Id, ddList);
        }
        List<tffa__Party__c> partyList = CZWTFCPartyRepository.save(new List<tffa__Party__c>{ partyObj });
        asm = new tffa.SObjectAssembler(partyList[0]);
        asm.addChildObjects('DueDiligences__r', ddList);
      } else {
        List<tffa__Party__c> partyList = CZWTFCPartyRepository.save(new List<tffa__Party__c>{ partyObj });
        asm = new tffa.SObjectAssembler(partyList[0]);
      }

      try {
        String reportId = partyObj.Id + ':' + reportName;
        tffa__DueDiligence__c qualfileDDObj = CZWTFCHelperRepository.getDueDiligenceObj('DEBIT_BUREAU', partyObj.id);
        if (idvResp != null && String.isBlank(idvResp.consumer.errorCd) && String.isNotBlank(idvResp.txtReport)) {
          tffa.DocumentMetadataDTO report = new tffa.DocumentMetadataDTO(
            qualifyReportName(reportName, partyObj),
            Blob.valueOf(idvResp.txtReport),
            partyObj.id,
            'OTHER'
          );
          report.participants.add(new tffa.DocumentParticipantDTO(null, (String) subPartyObj.tffa__Submission__c));

          if (qualfileDDObj != null) {
            report.participants.add(new tffa.DocumentParticipantDTO(null, (String) qualfileDDObj.Id));
          }
          tffa.ContentService.createContentWithParticipant(report);
        }
      } catch (Exception excep) {
        tffa.Logger.error(
          'Exception in generating Document Report ' +
          excep.getStackTraceString() +
          excep.getLineNumber() +
          ' ' +
          excep.getMessage()
        );
      }

      tffa.Logger.debug('parseIDAResponse Flow Completed');
      return (tffa__Party__c) asm.assemble();
    } catch (Exception ex) {
      tffa.Logger.error('Exception in processIDVResult ' + ex.getStackTraceString() + ex.getLineNumber() + ex.getMessage());
      return partyObj;
    }
  }

  public static List<tffa__DueDiligenceItem__c> createQualifileDDItems(FISIDVResponseDTO idvResp) {
    Integer counter = 0;
    List<tffa__DueDiligenceItem__c> ddItems = new List<tffa__DueDiligenceItem__c>();
    FISIDVResponseDTO.QualiFileInformation qualifileResp = new FISIDVResponseDTO.QualiFileInformation();

    if (idvResp.consumer.qualifileResponse != null && idvResp.consumer.qualifileResponse.qualifileInformation != null) {
      qualifileResp = idvResp.consumer.qualifileResponse.qualifileInformation;
    } else if (
      idvResp.consumer.chexsystemsResponse != null &&
      !String.isBlank(idvResp.consumer.chexsystemsResponse.errorCd) &&
      !String.isBlank(idvResp.consumer.chexsystemsResponse.errorTxt)
    ) {
      counter += 1;
      ddItems.add(
        FISDSSService.createQualifileDDItem(
          idvResp.consumer.chexsystemsResponse.errorCd,
          idvResp.consumer.chexsystemsResponse.errorTxt,
          'TechnicalFailure',
          counter
        )
      );
    }

    if (
      qualifileResp != null &&
      qualifileResp.qualifileReason1 != null &&
      qualifileResp.qualifileReason1.reasonCd != null &&
      qualifileResp.qualifileReason1.reasonTxt != null
    ) {
      counter += 1;
      ddItems.add(
        FISDSSService.createQualifileDDItem(
          qualifileResp.qualifileReason1.reasonCd,
          qualifileResp.qualifileReason1.reasonTxt,
          'QualifileReasonOne',
          counter
        )
      );
    }

    if (
      qualifileResp != null &&
      qualifileResp.qualifileReason2 != null &&
      qualifileResp.qualifileReason2.reasonCd != null &&
      qualifileResp.qualifileReason2.reasonTxt != null
    ) {
      counter += 1;
      ddItems.add(
        FISDSSService.createQualifileDDItem(
          qualifileResp.qualifileReason2.reasonCd,
          qualifileResp.qualifileReason2.reasonTxt,
          'QualifileReasonTwo',
          counter
        )
      );
    }

    if (
      qualifileResp != null &&
      qualifileResp.qualifileReason3 != null &&
      qualifileResp.qualifileReason3.reasonCd != null &&
      qualifileResp.qualifileReason3.reasonTxt != null
    ) {
      counter += 1;
      ddItems.add(
        FISDSSService.createQualifileDDItem(
          qualifileResp.qualifileReason3.reasonCd,
          qualifileResp.qualifileReason3.reasonTxt,
          'QualifileReasonThree',
          counter
        )
      );
    }

    if (
      qualifileResp != null &&
      qualifileResp.qualifileReason4 != null &&
      qualifileResp.qualifileReason4.reasonCd != null &&
      qualifileResp.qualifileReason4.reasonTxt != null
    ) {
      counter += 1;
      ddItems.add(
        FISDSSService.createQualifileDDItem(
          qualifileResp.qualifileReason4.reasonCd,
          qualifileResp.qualifileReason4.reasonTxt,
          'QualifileReasonFour',
          counter
        )
      );
    }

    if (
      qualifileResp != null &&
      qualifileResp.qualifileReason5 != null &&
      qualifileResp.qualifileReason5.reasonCd != null &&
      qualifileResp.qualifileReason5.reasonTxt != null
    ) {
      counter += 1;
      ddItems.add(
        FISDSSService.createQualifileDDItem(
          qualifileResp.qualifileReason5.reasonCd,
          qualifileResp.qualifileReason5.reasonTxt,
          'QualifileReasonFive',
          counter
        )
      );
    }
    if (counter == 0) {
      if (
        idvResp.consumer.complianceInfo != null &&
        idvResp.consumer.complianceInfo.debitBureauComplianceInfo != null &&
        !String.isBlank(idvResp.consumer.complianceInfo.debitBureauComplianceInfo.debitFreezeMessage)
      ) {
        counter += 1;
        ddItems.add(
          FISDSSService.createQualifileDDItem(
            'SecurityFreeze',
            idvResp.consumer.complianceInfo.debitBureauComplianceInfo.debitFreezeMessage,
            'CheckxSystemsSecurityFreeze',
            counter
          )
        );
      }
    }

    return ddItems;
  }

  @TestVisible
  private static tffa__DueDiligenceItem__c createQualifileDDItem(
    String reasonCd,
    String reasonTxt,
    String qualifileReason,
    Integer counter
  ) {
    tffa__DueDiligenceItem__c item = new tffa__DueDiligenceItem__c(
      Name = qualifileReason,
      tffa__Label__c = qualifileReason,
      tffa__Code__c = reasonCd,
      tffa__Required__c = false,
      tffa__SortOrder__c = counter,
      tffa__Type__c = 'RESPONSE',
      tffa__Value__c = reasonTxt
    );
    return item;
  }

  /**
   * Builds report name from party name
   */
  @TestVisible
  public static String qualifyReportName(String reportName, tffa__Party__c party) {
    // build report name reflecting the concerned party
    String prefix = party.Name.toLowerCase().replaceAll('\\s+', '_');
    if (prefix.length() > 18) {
      prefix = prefix.substring(0, 18);
    }
    return prefix + '_' + reportName;
  }
}