objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether this application should be considered as required in the submission. Such applications cannot be removed from the submission. Used in bundle applications, where one or more applications are marked as required.</description>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__SortOrder__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Controls the relative order of the item in a list.</description>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the application</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Value__c</fullName>
        <description>The lifetime value (perceived) of the account. An important metric that indicates the total revenue the bank can reasonably expect from the account. Derived from product and other facts.</description>
        <label>Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__DueDiligence__c.object
<CustomObject>
    <description>Due diligence is the process of gathering data in order to verify the identity of the applicant and to make sure they are not involved in money laundering , fraud  and high risk activities.
Tracks due diligence status for the given provider.</description>
    <fields>
        <fullName>tffa__ConversationId__c</fullName>
        <description>Conversation id when exchanging information with a remote interface.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Conversation id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ExternalQuestionnaireId__c</fullName>
        <description>Stores the reference to an external questionnaire or quiz. Populated when OOW questions are returned in a due-diligence activity.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>External Questionnaire Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to related party.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Due Diligences</relationshipLabel>
        <relationshipName>DueDiligences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Provider__c</fullName>
        <description>The provider for the diligence verification. This could be the name of the interface provider.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Provider</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>The status captured for the due diligence record.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>The status captured for the due diligence record.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceType</valueSetName>
        </valueSet>
    </fields>
    <label>Due Diligence</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Due Diligences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__DueDiligenceItem__c.object
<CustomObject>
    <description>List of answers  which are captured for the applicant against the CDD questions. CDD questions can be fetched from KBA third party systems.</description>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>A logical name that uniquely identifies the item among a list. Can be a question code.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__DueDiligence__c</fullName>
        <description>Reference to parent due diligence.</description>
        <label>Due Diligence</label>
        <referenceTo>tffa__DueDiligence__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Label__c</fullName>
        <description>The question text, or a display name.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether value is required. Applicable to type QUESTION.</description>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__SortOrder__c</fullName>
        <description>The order of the item w.r.t other items.</description>
        <label>Sort order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <defaultValue>&quot;QUESTION&quot;</defaultValue>
        <description>The nature of the item. A DueDiligence item can hold OOW questions, or results related to a DueDiligence activity, e.g. name mismatch, phone mismatch, etc</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceItemType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Value__c</fullName>
        <description>The value of the answer captured.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Due Diligence Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Due Diligence Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>tffa__PrimaryEmail__c</fullName>
        <description>Primary email of the party.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the submission</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__DueDiligenceItemType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>QUESTION</fullName>
        <label>Question</label>
    </customValue>
    <customValue>
        <fullName>RESPONSE</fullName>
        <label>Response</label>
    </customValue>
    <description>Types of DueDiligenceItem(s). A DueDiligenceItem can be used to store OOW Questions, or results related to a DueDiligence activity.</description>
    <masterLabel>DueDiligenceItemType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__DueDiligenceStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PASSED</fullName>
        <label>✅Passed</label>
    </customValue>
    <customValue>
        <fullName>DECLINED</fullName>
        <label>❌Declined</label>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
        <label>❌Failed</label>
    </customValue>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <label>🔶In progress</label>
    </customValue>
    <customValue>
        <fullName>CHALLENGED</fullName>
        <label>⚠️Challenged</label>
    </customValue>
    <customValue>
        <fullName>REVIEW</fullName>
        <label>⚠️Review</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>❌Expired</label>
    </customValue>
    <description>States of a due diligence activity.</description>
    <masterLabel>DueDiligenceStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__DueDiligenceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IDV</fullName>
    </customValue>
    <customValue>
        <fullName>CDD</fullName>
    </customValue>
    <customValue>
        <fullName>FRAUD</fullName>
        <label>Fraud</label>
    </customValue>
    <customValue>
        <fullName>OFAC</fullName>
    </customValue>
    <customValue>
        <fullName>QUALIFILE</fullName>
        <label>QualiFile</label>
    </customValue>
    <customValue>
        <fullName>IDA</fullName>
    </customValue>
    <customValue>
        <fullName>CREDIT_BUREAU</fullName>
        <label>Credit Bureau</label>
    </customValue>
    <customValue>
        <fullName>DEBIT_BUREAU</fullName>
        <label>Debit Bureau</label>
    </customValue>
    <description>Types of due diligences</description>
    <masterLabel>DueDiligenceType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>ABANDONED</fullName>
        <label>Abandoned</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>SAVED</fullName>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>SUBMITTED</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>Indicates current status of the submission.This will be computed and be useful for regulations.</description>
    <masterLabel>SubmissionStatus</masterLabel>
</GlobalValueSet>

classes/CZWTFCAdverseActionExtTest.cls
@isTest
public with sharing class CZWTFCAdverseActionExtTest {
  @isTest
  public static void adverseActionExt() {
    tffa__Submission__c sub = new tffa__Submission__c();
    insert sub;

    tffa__Application__c appObj = new tffa__Application__c();
    appObj.tffa__Submission__c = sub.Id;
    insert appObj;

    tffa__Party__c partyObj = new tffa__Party__c();
    partyObj.tffa__Type__c = 'Individual';
    partyObj.Name = 'John';
    partyObj.tffa__PrimaryEmail__c = 'Test@test.com';
    insert partyObj;

    tffa__DueDiligence__c dueDiligence = new tffa__DueDiligence__c();
    List<tffa__DueDiligenceItem__c> ddItems = new List<tffa__DueDiligenceItem__c>();
    dueDiligence.Name = 'FIS QUALIFILE';
    dueDiligence.tffa__Type__c = 'DEBIT_BUREAU';
    dueDiligence.tffa__Status__c = 'CHALLENGED';
    dueDiligence.tffa__Provider__c = 'FIS QUALIFILE';
    dueDiligence.tffa__ExternalQuestionnaireId__c = '12323';
    dueDiligence.tffa__ConversationId__c = '1233';
    dueDiligence.tffa__Party__c = partyObj.Id;

    tffa.SObjectAssembler asm12 = new tffa.SObjectAssembler(dueDiligence);

    tffa__DueDiligenceItem__c item = new tffa__DueDiligenceItem__c(
      Name = 'Test',
      tffa__Label__c = 'test',
      tffa__Code__c = '12345',
      tffa__Required__c = true,
      tffa__SortOrder__c = 1,
      tffa__Value__c = '12345'
    );
    ddItems.add(item);

    asm12.addChildObjects('Items__r', ddItems);
    dueDiligence = (tffa__DueDiligence__c) asm12.assemble();
    insert dueDiligence;

    tffa.SObjectAssembler asmPar = new tffa.SObjectAssembler(partyObj);
    asmPar.addChildObjects('DueDiligences__r', new List<tffa__DueDiligence__c>{ dueDiligence });
    partyObj = (tffa__Party__c) asmPar.assemble();
    update partyObj;

    Test.startTest();
    ApexPages.StandardController stdController;
    ApexPages.currentPage().getParameters().put('id', partyObj.Id);
    AdverseActionLetterExtension a = new AdverseActionLetterExtension(stdController);
    System.assertEquals('1', '1', 'Success');
    Test.stopTest();
  }
}