objects/tffa__ApplicantRole__c.object
<CustomObject>
    <description>Defines possible roles played by a Party (or Applicant) on an Application. e.g. SOLE_OWNER, JOINT_OWNER, AUTHORIZED_SIGNATORY etc. These roles finally translate to roles on opened accounts. Each role has specific characteristics, that can influence the relationship. e.g.parties with SOLE_OWNER, JOINT_OWNER roles become owners of the account, whereas ones with AGENT, GUARANTOR roles do not. Roles may be categorized based on this nature of relationship. Roles may also have applicable authority list. These control what actions are permitted on the account.</description>
    <label>Applicant Role</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicant Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product code identifier.</description>
        <label>Financial Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR (4 AND 5))</booleanFilter>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>$Source.tffa__ProductCategory__c</field>
                <operation>equals</operation>
                <valueField>tffa__Product__c.tffa__Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value>In Progress</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the application</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ApplicationPartyXref__c.object
<CustomObject>
    <description>Each Applicant of the submission can play different roles in the application and the eventual account.</description>
    <fields>
        <fullName>tffa__ApplicantRole__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The role played by the party in the application. Finally translates to role on opened account.</description>
        <label>Role</label>
        <referenceTo>tffa__ApplicantRole__c</referenceTo>
        <relationshipLabel>Application Parties</relationshipLabel>
        <relationshipName>ApplicationPartyXrefs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__FundingRequest__c.object
<CustomObject>
    <description>Supports the capture of details pertaining to funding a payment obligation using one of the various available sources of funding</description>
    <fields>
        <fullName>tffa__LinkedApplication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to application.</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Funding Requests</relationshipLabel>
        <relationshipName>LinkedFundingRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Funding status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__FundingStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to parent submission.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Consolidated Funding Requests</relationshipLabel>
        <relationshipName>FundingRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the submission</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__FundingStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>FUNDED</fullName>
        <label>Funded</label>
    </customValue>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
        <label>Failed</label>
    </customValue>
    <customValue>
        <fullName>APPROVAL</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>REVERSED</fullName>
        <label>Reversed</label>
    </customValue>
    <customValue>
        <fullName>REVERSAL_FAILED</fullName>
        <label>Reversal Failed</label>
    </customValue>
    <customValue>
        <fullName>ACH_FILE_GENERATED</fullName>
        <label>ACH File Generated</label>
    </customValue>
    <customValue>
        <fullName>ACH_FILE_FAILED</fullName>
        <label>ACH File Generation Failed</label>
    </customValue>
    <customValue>
        <fullName>HOLD_APPLIED</fullName>
        <label>Hold Applied on Funds</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>REVERSAL_NOT_REQ</fullName>
        <label>Reversal Not Required</label>
    </customValue>
    <customValue>
        <fullName>AUTHORIZED</fullName>
        <isActive>false</isActive>
        <label>AUTHORIZED</label>
    </customValue>
    <description>Status of funding</description>
    <masterLabel>FundingStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>ABANDONED</fullName>
        <label>Abandoned</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>SAVED</fullName>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>SUBMITTED</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>Indicates current status of the submission.This will be computed and be useful for regulations.</description>
    <masterLabel>SubmissionStatus</masterLabel>
</GlobalValueSet>

classes/ACHFileGenSchedulerTest.cls
/**
@author     : Sagar Padhye
@description: This test class covers testcoverage for most of the ACH related classes.
			  Individual Test classes have been written for some ACH related classes to increase codecoverage.
@version 	: 1.0  03 Jan, 2019
@author   : Girish Suvarna
@version  : 2.0  11 Feb, 2020
*/

@isTest
private class ACHFileGenSchedulerTest {
  @testSetup
  static void setupData() {
    setupConfigData();
  }

  static void setupConfigData() {
    String FundingStatus = 'IN_PROGRESS';
    String FundingType = 'ACH';
    Test.loadData(tffa__Product__c.sObjectType, 'TFTD_PRODUCT');
    Test.loadData(tffa__Party__c.sObjectType, 'TFParty');
    Test.loadData(tffa__ApplicantRole__c.sObjectType, 'TFApplicantRole');
    Test.loadData(tffa__Submission__c.sObjectType, 'TFSubmission');
    Test.loadData(tffa__Application__c.sObjectType, 'TFApplications');
    Test.loadData(tffa__ApplicationPartyXref__c.sObjectType, 'TFApplicationPartyXref');
    Test.loadData(tffa__FundingRequest__c.sObjectType, 'TFFundingRequest');
  }

  @isTest
  static void test1() {
    Test.StartTest();
    Id batchJobId = Database.executeBatch(new ACHFileGenBatch(), 50);
    AsyncApexJob aaj = [SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors FROM AsyncApexJob WHERE ID =: batchJobId ];
    
    System.assertNotEquals(aaj, null);    
    Test.stopTest();
  }
  @isTest
  static void test4() {
    Test.startTest();
    ACHBatch ab = new ACHBatch();
    ab.getBatchControl();
    ACHBatchHeaderRecord headerrecord = new ACHBatchHeaderRecord('Dummy');
    List<ACHEntryDetailRecord> batchEntries = new List<ACHEntryDetailRecord>();
    ACHBatchControlRecord batchControlRecord = new ACHBatchControlRecord();
    ab.setBatchHeader(headerrecord);
    ab.setBatchEntries(batchEntries);
    ab.setBatchControl(batchControlRecord);
    ab.getBatchHeader();
    ab.getBatchString();

    ACHBatchControlRecord abcr = new ACHBatchControlRecord();
    abcr.setTotalBatchCreditAmount(10.00);
    abcr.setMsgAuthCode('authmsg');
    abcr.setReservedField('');

    ACHDocumentDTO ad = new ACHDocumentDTO();
    ad.getFileHeader();
    ad.getFillerRecs();
    ad.getFileControl();

    ACHEntryDetailRecord adr = new ACHEntryDetailRecord();
    adr.setAddendaRec(new ACHAddendaRecord());
    adr.getRecordString();
    adr.setAchFileName('dummy');
    adr.getAchFileName();
    adr.setPcbAcctNo('dummypcb');
    adr.getPcbAcctNo();
    adr.setProductName('dummyProdName');
    adr.getProductName();
    adr.setAddendaRec(null);
    adr.getAddendaRec();
    adr.setTraceNo('dummytraceno');
    adr.getRecStrForCreditFile('dummyRescType');

    ACHFileControlRecord acr = new ACHFileControlRecord();
    acr.setReservedField('');
    acr.getRecordTypecode();
    acr.getBatchCount();
    acr.getBlockCount();
    acr.getEntryHash();
    acr.getTotalFileDebitAmount();
    acr.getTotalFileCreditAmount();
    acr.getReservedField();
    acr.getTotalFileDebitRecords();
    acr.getTotalFileCreditRecords();
    acr.getRecordString();

    ACHFileHeaderRecord ahr = new ACHFileHeaderRecord();
    ahr.setPriorityCode('pc');
    ahr.setRecordSize('10');
    ahr.setBlockingFactor('10');
    ahr.setFormatCode('10');

    ACHFillerRecords afr = new ACHFillerRecords(1);
    afr.getRecordString();
    String fundingStatus = 'IN_PROGRESS';
    String query = new tffa.QueryBuilder(tffa__FundingRequest__c.SObjectType)
      .selectFields()
      .selectObject('tffa__LinkedApplication__r')
      .selectFields()
      .build()
      .whereClause('tffa__Status__c', '= :fundingStatus')
      .toQuery();
    List<tffa__FundingRequest__c> apps = Database.query(query);
    ACHFileDTO achdata = new ACHFileDTO(ACHFileType.ACH, apps, '118');
    ACHFileBuilder afb = new ACHFileBuilder(achdata);
    afb.buildACHFile();
    System.assertNotEquals(afb, null);
    Test.stopTest();
  }
  @isTest
  static void test3() {
    Test.StartTest();
    ACHAddendaRecord ad = new ACHAddendaRecord();
    ad.setAddendaCodeType('test');
    ad.setPaymentInfo('test1');
    ad.setAddendaSeqNo(1);
    ad.setEntryDetailSeqNo(2);

    ACHEntryRecordBuilder arb = new ACHEntryRecordBuilder();
    arb.getRefNo();
    arb.getPartyName('person', 'legalname');
    arb.getUniqueCount();
    arb.getLastNumber(0);
    System.assertNotEquals(arb, null);
    Test.stopTest();
  }
  /* @isTest
  static void test2() {
    GlobalScapeDTO ac = new GlobalScapeDTO();
    GlobalScapeDTO.Token t1 = new GlobalScapeDTO.Token();
    String json = '{ "user" : { "name" : "Simon Fell", "twitter" : "@superfell" } }';
    t1.parse(json);

    GlobalScapeDTO.User t2 = new GlobalScapeDTO.User();
    t2.parse(json);

    GlobalScapeDTO.PostFileResponse t3 = new GlobalScapeDTO.PostFileResponse();
    t3.parse(json);

    GlobalScapeDTO.ErrorModel t4 = new GlobalScapeDTO.ErrorModel();
    t4.parse(json);
  }*/

  @isTest
  static public void test6() {
    ACHFileDTO achdata;
    ACHFileBuilder acfb = new ACHFileBuilder(achdata);
    Test.StartTest();
    acfb.logACHFileInfo('ach');
    System.assertNotEquals(acfb, null);
    Test.stopTest();
  }

  @isTest
  static public void test7() {
    ACHBatchControlRecord abcr = new ACHBatchControlRecord();
    abcr.setTotalBatchCreditAmount(10.00);
    abcr.setMsgAuthCode('authmsg');
    abcr.setReservedField('');

    ACHEntryDetailRecord adr = new ACHEntryDetailRecord();
    adr.setAddendaRec(new ACHAddendaRecord());
    adr.getRecordString();
    adr.setAchFileName('dummy');
    adr.getAchFileName();
    adr.setPcbAcctNo('dummypcb');
    adr.getPcbAcctNo();
    adr.setProductName('dummyProdName');
    adr.getProductName();
    adr.setAddendaRec(null);
    adr.getAddendaRec();
    adr.setTraceNo('dummytraceno');
    adr.getRecStrForCreditFile('dummyRescType');

    ACHFileControlRecord acr = new ACHFileControlRecord();
    acr.setReservedField('');
    acr.setBatchCount(1);
    acr.setBlockCount(8);
    acr.setEntryCount(1);
    acr.setEntryHash(3);
    acr.setTotalFileDebitAmount(100.00);
    acr.setTotalFileCreditAmount(100.00);
    acr.setTotalFileDebitRecords(10);
    acr.setTotalFileCreditRecords(11);

    ACHFileHeaderRecord ahr = new ACHFileHeaderRecord();
    ahr.setPriorityCode('pc');
    ahr.setRecordSize('10');
    ahr.setBlockingFactor('10');
    ahr.setFormatCode('10');
    ahr.setImmediateDestination('abc');
    ahr.setImmdiateOrigin('xyz');
    ahr.setFileCreationDate('01-01-2000');
    ahr.setFileCreationTime('12232512');
    ahr.setFileIdModifier('qwe');
    ahr.setImmediateDestinationName('a');
    ahr.setImmediateOriginName('b');
    ahr.setRefCode('test');

    ACHBatch ab = new ACHBatch();
    ACHBatchHeaderRecord headerrecord = new ACHBatchHeaderRecord('Dummy');
    List<ACHEntryDetailRecord> batchEntries = new List<ACHEntryDetailRecord>();
    batchEntries.add(adr);
    ab.setBatchHeader(headerrecord);
    ab.setBatchEntries(batchEntries);
    ab.setBatchControl(abcr);
    ab.getBatchHeader();
    ab.getBatchString();
    ab.getBatchControl();
    ACHFillerRecords afr = new ACHFillerRecords(1);
    afr.getRecordString();
    String fundingStatus = 'IN_PROGRESS';
    String query = new tffa.QueryBuilder(tffa__FundingRequest__c.SObjectType)
      .selectFields()
      .selectObject('tffa__LinkedApplication__r')
      .selectFields()
      .build()
      .whereClause('tffa__Status__c', '= :fundingStatus')
      .toQuery();
    List<tffa__FundingRequest__c> apps = Database.query(query);
    ACHFileDTO achdata = new ACHFileDTO(ACHFileType.ACH, apps, '118');
    ACHFileBuilder afb = new ACHFileBuilder(achdata);
    ACHDocumentDTO doc = new ACHDocumentDTO();
    ACHDocumentBuilder adb = new ACHDocumentBuilder(achdata);

    List<ACHBatch> batches = new List<ACHBatch>();
    batches.add(ab);
    doc.setFileHeader(ahr);
    doc.setFileControl(acr);
    doc.setFillerRecs(afr);
    doc.setBatches(batches);
    doc.getFileHeader();
    doc.getFillerRecs();
    ACHCreditFileBuilder acb = new ACHCreditFileBuilder(doc);
    String creditFileStr = acb.buildCreditFile();
    string genMsg = 'File Generated Successfully';
    string achFileStr = doc.getACHDocumentString();

    Test.StartTest();

    afb.createFilesAndNotify(doc, 'achFileStr', 'creditFileStr', 'genMsg');

    System.assertNotEquals(afb, null);
    Test.stopTest();
  }

  @isTest
  static public void test8() {
    ACHFileDTO achdata;
    ACHFileBuilder acfb = new ACHFileBuilder(achdata);
    Test.StartTest();
    acfb.buildACHFile();
    System.assertNotEquals(acfb, null);
    Test.stopTest();
  }
}