objects/tffa__DueDiligence__c.object
<CustomObject>
    <description>Due diligence is the process of gathering data in order to verify the identity of the applicant and to make sure they are not involved in money laundering , fraud  and high risk activities.
Tracks due diligence status for the given provider.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to related party.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Due Diligences</relationshipLabel>
        <relationshipName>DueDiligences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Due Diligence</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Due Diligences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>tffa__FraudStatus__c</fullName>
        <description>A rollup of status across DueDiligence(s) of type FRAUD.</description>
        <label>Fraud Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__OFACStatus__c</fullName>
        <description>A rollup of status across DueDiligence(s) of type OFAC.</description>
        <label>OFAC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__DueDiligenceStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PASSED</fullName>
        <label>✅Passed</label>
    </customValue>
    <customValue>
        <fullName>DECLINED</fullName>
        <label>❌Declined</label>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
        <label>❌Failed</label>
    </customValue>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <label>🔶In progress</label>
    </customValue>
    <customValue>
        <fullName>CHALLENGED</fullName>
        <label>⚠️Challenged</label>
    </customValue>
    <customValue>
        <fullName>REVIEW</fullName>
        <label>⚠️Review</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>❌Expired</label>
    </customValue>
    <description>States of a due diligence activity.</description>
    <masterLabel>DueDiligenceStatus</masterLabel>
</GlobalValueSet>

classes/CZWTFCDueDiligenceServiceExt.cls
global inherited sharing class CZWTFCDueDiligenceServiceExt extends tffa.DueDiligenceServiceExt {
  global override List<tffa__Party__c> postVerify(List<tffa__Party__c> parties, Map<String, Object> facts) {
    tffa.Interaction.begin(CZWTFCDueDiligenceServiceExt.class, 'postVerify');
    try {
      tffa.Logger.debug('Parties ' + parties.size());
      return parties;
    } finally {
      tffa.Interaction.close();
    }
  }

  global override List<tffa__DueDiligence__c> postUpdateStatus(List<tffa__DueDiligence__c> entities, Map<String, Object> facts) {
    tffa.Interaction.begin(CZWTFCDueDiligenceServiceExt.class, 'postUpdateStatus');

    try {
      Set<Id> partyIds = new Set<Id>();

      for (tffa__DueDiligence__c dd : entities) {
        partyIds.add(dd.tffa__Party__c);
      }

      List<Id> partyIdLst = new List<Id>(partyIds);
      List<tffa__Party__c> partyLst = FISCCIntegrationLogRepository.findPartydWithChildObjects(partyIdLst);
      tffa.PartyService.doDecision(
        partyLst,
        new Map<String, Object>{
          'Type__c' => 'KYC',
          'CZFraudStatus__c' => partyLst[0].tffa__FraudStatus__c,
          'CZOFACStatus__c' => partyLst[0].tffa__OFACStatus__c
        }
      );

      return entities;
    } finally {
      tffa.Interaction.close();
    }
  }
}