objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <fields>
        <fullName>ContactNumber__c</fullName>
        <description>Contact Number for Brand</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Contact Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Disclosure__c.object
<CustomObject>
    <description>Supports the capture of a list of disclosures which the applicant has to accept or execute before opening the account. List of disclosures is fetched from disclosure checklist maintained for a product and type of applicant.</description>
    <fields>
        <fullName>tffa__EventName__c</fullName>
        <description>Event or purpose of capture of Disclosure</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Event name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Label__c</fullName>
        <description>The disclosure text.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to parent submission.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Disclosures</relationshipLabel>
        <relationshipName>Disclosures</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Disclosure</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__Brand__c</fullName>
        <description>Brand code of the Brand for the submission if applicable</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CZWTFCGenDisclosurePdfProvider.cls
public with sharing class CZWTFCGenDisclosurePdfProvider {
  public boolean generateDisclosurePdf(tffa__Submission__c sub) {
    CZWTFCGenDisclosurePdfProvider pdfProvider = new CZWTFCGenDisclosurePdfProvider();
    Map<String, String> mp = new Map<String, String>();
    try {
      tffa__Brand__c brandObj = CZWTFCBrandRepository.fetchBrandByCode(sub.tffa__Brand__c);
      Set<String> eventNameSet = new Set<String>();

      for (tffa__Disclosure__c dis : sub.tffa__Disclosures__r) {
        eventNameSet.add(dis.tffa__EventName__c);
      }

      //for group disclosures
      List<String> eventLst = new List<String>(eventNameSet);
      if (!eventLst.isEmpty()) {
        for (Integer idx = 0; idx < eventLst.size(); idx++) {
          String disclosure = '';
          if (eventLst[idx].equalsIgnoreCase('AccountDetails_OD')) {
            disclosure += '\nPlease take a moment to review your selection. Is everything correct?';
          }
          for (tffa__Disclosure__c dis : sub.tffa__Disclosures__r) {
            if (dis.tffa__EventName__c != null && dis.tffa__EventName__c.equalsIgnoreCase(eventLst[idx])) {
              if (CZWTFCConstants.disclosureLabelMap.containsKey(dis.tffa__Label__c)) {
                disclosure += ' \n\n' + CZWTFCConstants.disclosureLabelMap.get(dis.tffa__Label__c);
              } else {
                disclosure += ' \n\n' + dis.tffa__Label__c;
              }
            }
          }
          if (eventLst[idx].equalsIgnoreCase('AccountDetails_OD')) {
            disclosure +=
              '\n\nYou have a right to change these selections at any time by calling ' +
              brandObj.ContactNumber__c +
              ' or visiting your local branch.';
            Date startDate = system.today();
            Datetime dt = DateTime.newInstance(startDate, Time.newInstance(0, 0, 0, 0));
            String dayOfWeek = dt.format('EEEE');
            String month = dt.format('MMMM');
            disclosure +=
              '\n\n' +
              dayofWeek +
              ', ' +
              month +
              ' ' +
              String.valueOf(Date.Today().Day()) +
              ' ,' +
              String.valueOf(Date.Today().Year());
          }
          if (eventLst[idx].equalsIgnoreCase('AccountDetails_OD')) {
            disclosure = disclosure.replace('<div>', '');
            disclosure = disclosure.replace('</div>', ' \n');
            disclosure = disclosure.replace('<b>', '');
            disclosure = disclosure.replace('</b>', '');
          }
          mp.put(eventLst[idx], disclosure);
        }
      }

      for (String key : mp.keySet()) {
        pdfProvider.createPDF(key, mp.get(key), sub);
      }
      return true;
    } catch (Exception ex) {
      tffa.Logger.error('Exception msg in CZWTFCGenDisclosurePdfProvider : ' + ex.getMessage() + ' ' + ex.getStackTraceString());
      return false;
    }
  }

  public void createPDF(String pdfName, String disclosureContent, tffa__Submission__c sub) {
    String updatedPdfName = (CZWTFCConstants.disclosureNameMap.containsKey(pdfName))
      ? CZWTFCConstants.disclosureNameMap.get(pdfName)
      : pdfName;
    PageReference pageRef = Page.DisclosurePdfConverter;
    pageRef.getParameters().put('disclosureTitle', updatedPdfName);
    pageRef.getParameters().put('disclosureText', disclosureContent);
    tffa.DocumentMetadataDTO disclosurePdf = new tffa.DocumentMetadataDTO(updatedPdfName + '.pdf', pageRef.getContent(), sub.id, 'OTHER');
    tffa.ContentService.createContentWithParticipant(disclosurePdf);
  }
}