objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsAuthenticatedCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Authenticated Customer</description>
        <label>Authenticated Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsDobMissing__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Dob field missing from MDM Response</description>
        <label>DOB Missing in IBS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__BirthDate__c</fullName>
        <description>The date of birth of the individual</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Birth date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>tffa__IsExistingCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current applicant is existing customer of the bank.</description>
        <label>IsExistingCustomer</label>
        <type>Checkbox</type>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FISCCPartyDobUpdateExtension.cls
public with sharing class FISCCPartyDobUpdateExtension {
  public static List<FISCCDepositOriginationRequestBaseDTO> generateRequest(List<tffa__Party__c> parties) {
    tffa.Logger.debug('In FISCCPartyDobUpdateExtension.generateRequest ');
    List<FISCCDepositOriginationRequestBaseDTO> requestLst = new List<FISCCDepositOriginationRequestBaseDTO>();
    try {
      for (tffa__Party__c party : parties) {
        if (party.IsAuthenticatedCustomer__c && party.tffa__IsExistingCustomer__c && party.IsDobMissing__c) {
          FISCCDOIndividualDemoRequest individualDemo = new FISCCDOIndividualDemoRequest();
          individualDemo.SvcID = FISCCIntegrationConstants.INDIVIDUAL_DEMOGRAPHICS;
          individualDemo.individualDemographics.CIApplNbr = party.Customer_Number__c;
          individualDemo.individualDemographics.CICustDteOfBrth = String.valueOf(party.tffa__BirthDate__c);
          FISCCDepositOriginationRequestBaseDTO req = (FISCCDepositOriginationRequestBaseDTO) individualDemo;
          requestLst.add(req);
        }
      }
    } catch (Exception ex) {
      tffa.Logger.error('Exception in generating request for individual Demographics ' + ex.getMessage() + ' ' + ex.getStackTraceString());
    }
    return requestLst;
  }
}