objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CZStarterCheckReqBatch.cls
public inherited sharing class CZStarterCheckReqBatch extends tffa.AbstractBatchJob implements Database.Batchable<sObject>, Database.AllowsCallouts {
  public List<tffa__Application__c> start(Database.BatchableContext batchableContext) {
    tffa.Logger.debug('CZStarterCheckReqBatch start() method');
    List<tffa__Application__c> listApplication = CZWTFCApplicationRepository.getApplicationByCheck();
    return listApplication;
  }

  public void execute(Database.BatchableContext batchableContext, List<tffa__Application__c> listApplication) {
    tffa.Logger.debug('CZStarterCheckReqBatch execute() method');
    try {
      tffa__Application__c app = listApplication.isEmpty() ? new tffa__Application__c() : listApplication[0];
      FISCCIntegrationLogService.setSubmissionObj(String.valueOf(app.tffa__Submission__c));
      FISCCIntegrationLogService.setIntegrationLog(String.valueOf(app.tffa__Submission__c));
      tffa.Logger.debug('CZStarterCheckReqBatch execute() method : app => ' + app);
      CZStarterCheckExecutor.processRequest(app);
    } catch (Exception ex) {
      tffa.Logger.error('CZStarterCheckReqBatch Exception msg : ' + ex.getMessage() + ' ' + ex.getStackTraceString());
    } finally {
      FISCCIntegrationLogService.persistData();
    }
  }

  public void finish(Database.BatchableContext batchableContext) {
    tffa.Logger.debug('CZStarterCheckReqBatch finish() method');
  }
}