objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FISCCDepositOriginationProvider.cls
public with sharing class FISCCDepositOriginationProvider {
  public static boolean createDepositOrigination(List<tffa__Party__c> partyObjs, tffa__Application__c appObj, tffa__Submission__c subObj) {
    Boolean isSuccess = false;
    Boolean isAPICall = false;
    Boolean isAPICallFailed = false;
    String custAddKey = null;
    List<tffa__Party__c> listParty = new List<tffa__Party__c>();
    tffa.logger.debug('partyObjs.size()==>' + partyObjs.size());

    FISCCIntegrationLogService.auth = FISCCGetAccessTokenProvider.processGetAccessToken(FISCCIntegrationLogService.charterConfig);
    custAddKey = FISCCIntegrationLogService.setCurrentLogItem(FISCCIntegrationConstants.DEPOSIT_ORIGINATOR, appObj.Name, true);
    tffa.logger.debug('FISCCIntegrationLogService.auth in DO==>' + FISCCIntegrationLogService.auth);
    if (!partyObjs.isEmpty()) {
      if (FISCCIntegrationLogService.isLogItemNewOrFailed(custAddKey)) {
        isAPICall = FISCCDepositOriginationExtension.invokeDepositOriginationApiCall(partyObjs, appObj, subObj);
        tffa.logger.debug('isAPICall in DO==>' + isAPICall);
        if (isAPICall != null && isAPICall) {
          FISCCIntegrationLogService.setLogOk(FISCCIntegrationConstants.DEPOSIT_ORIGINATOR_COMPLETED);
        } else {
          FISCCIntegrationLogService.setLogFailed(FISCCIntegrationConstants.DEPOSIT_ORIGINATOR_FAILED);
          isAPICallFailed = true;
          tffa.Logger.debug('Create DO  Call Failed for parties ::: ' + partyObjs);
        }
      }

      if (isAPICallFailed != null && isAPICallFailed) {
        throw new tffa.ApplicationException('DO Party details validation failed ....!!!');
      }

      if (isAPICall) {
        isSuccess = true;
      }
    }

    tffa.logger.debug('isSuccess in createCustomerProvider ==>' + isSuccess);
    return isSuccess;
  }

  public static boolean updateCustomerInformation(tffa__Party__c partyObj) {
    Boolean isApiSuccess = true;
    try {
      String logitemMissingInfo = FISCCIntegrationLogService.setCurrentLogItem(
        FISCCIntegrationConstants.UPDATED_CUSTOMER_INFORMATION,
        partyObj.Name,
        false
      );
      if (FISCCIntegrationLogService.isLogItemNewOrFailed(logitemMissingInfo)) {
        isApiSuccess = FISCCDepositOriginationExtension.sendCustInfo(partyObj);
        if (isApiSuccess) {
          FISCCIntegrationLogService.setLogItemOk(FISCCIntegrationConstants.UPDATED_CUSTOMER_INFORMATION);
        } else {
          FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.UPDATED_CUSTOMER_INFORMATION);
        }
      }
    } catch (Exception ex) {
      tffa.Logger.error('Exception in updateCustomerInformation ' + ex.getMessage() + ' ' + ex.getStackTraceString());
      FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.UPDATED_CUSTOMER_INFORMATION);
    }
    return isApiSuccess;
  }
}