objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <fields>
        <fullName>Address__c</fullName>
        <description>Address for Brand</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Street Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactNumber__c</fullName>
        <description>Contact Number for Brand</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Contact Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__DueDiligence__c.object
<CustomObject>
    <description>Due diligence is the process of gathering data in order to verify the identity of the applicant and to make sure they are not involved in money laundering , fraud  and high risk activities.
Tracks due diligence status for the given provider.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to related party.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Due Diligences</relationshipLabel>
        <relationshipName>DueDiligences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>The status captured for the due diligence record.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceType</valueSetName>
        </valueSet>
    </fields>
    <label>Due Diligence</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Due Diligences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__DueDiligenceItem__c.object
<CustomObject>
    <description>List of answers  which are captured for the applicant against the CDD questions. CDD questions can be fetched from KBA third party systems.</description>
    <fields>
        <fullName>tffa__DueDiligence__c</fullName>
        <description>Reference to parent due diligence.</description>
        <label>Due Diligence</label>
        <referenceTo>tffa__DueDiligence__c</referenceTo>
        <relationshipLabel>Items</relationshipLabel>
        <relationshipName>Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <defaultValue>&quot;QUESTION&quot;</defaultValue>
        <description>The nature of the item. A DueDiligence item can hold OOW questions, or results related to a DueDiligence activity, e.g. name mismatch, phone mismatch, etc</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceItemType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Value__c</fullName>
        <description>The value of the answer captured.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Due Diligence Item</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Due Diligence Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>tffa__BrandCode__c</fullName>
        <description>Brand code of the submission this party is associated with</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__DebitBureauScore__c</fullName>
        <description>Score given by a debit bureau (e.g. ChexSystems) to the party. e.g. QualiFile score. It is a reflection of the party&apos;s banking behavour.</description>
        <label>Debit Bureau score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__DueDiligenceItemType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>QUESTION</fullName>
        <label>Question</label>
    </customValue>
    <customValue>
        <fullName>RESPONSE</fullName>
        <label>Response</label>
    </customValue>
    <description>Types of DueDiligenceItem(s). A DueDiligenceItem can be used to store OOW Questions, or results related to a DueDiligence activity.</description>
    <masterLabel>DueDiligenceItemType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__DueDiligenceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IDV</fullName>
    </customValue>
    <customValue>
        <fullName>CDD</fullName>
    </customValue>
    <customValue>
        <fullName>FRAUD</fullName>
        <label>Fraud</label>
    </customValue>
    <customValue>
        <fullName>OFAC</fullName>
    </customValue>
    <customValue>
        <fullName>QUALIFILE</fullName>
        <label>QualiFile</label>
    </customValue>
    <customValue>
        <fullName>IDA</fullName>
    </customValue>
    <customValue>
        <fullName>CREDIT_BUREAU</fullName>
        <label>Credit Bureau</label>
    </customValue>
    <customValue>
        <fullName>DEBIT_BUREAU</fullName>
        <label>Debit Bureau</label>
    </customValue>
    <description>Types of due diligences</description>
    <masterLabel>DueDiligenceType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

classes/AdverseActionLetterV2Extension.cls
public with sharing class AdverseActionLetterV2Extension {
  //Score Date
  public String scoreDate { get; set; }
  public String partyId { get; set; }
  public String debitBureauScore{ get; set; }
  public String brandName { get; set; }
  public String brandAddress{ get; set; }
  public String brandPhoneNumber{ get; set; }

  public tffa__Party__c partyDtls { get; set; }
  public tffa__Brand__c brandDtls { get; set; }

  public List<String> reasons { get; set; }

  public AdverseActionLetterV2Extension(ApexPages.StandardController stdController) {
    try {
      List<tffa__DueDiligence__c> ddList = new List<tffa__DueDiligence__c>();
      partyId = ApexPages.currentPage().getParameters().get('id');
      tffa.Logger.debug('partyId:' + partyId);

      //partyId = 'a108A000002pSjXQAU'; //temp for testing
      reasons = new List<String>();
      partyDtls = CZWTFCPartyRepository.fetchPartyById(partyId);
      ddList = CZWTFCHelperRepository.getDueDiligenceList(partyId);
      if (ddList != null && !ddList.isEmpty()) {
        for (tffa__DueDiligence__c dd : ddList) {
          if (dd.tffa__Type__c.equalsIgnoreCase('DEBIT_BUREAU')) {
            //Set qualifile date
            scoreDate = dd.CreatedDate.format('MM/dd/yyyy');

            //Set qualifile reason
            if (dd.tffa__Items__r != null && !dd.tffa__Items__r.isEmpty()) {
              for (tffa__DueDiligenceItem__c ddItem : dd.tffa__Items__r) {
                reasons.add(ddItem.tffa__Value__c);
              }
            }
            break;
          }
        }
      }
      brandDtls = CZWTFCBrandRepository.fetchBrandByCode(partyDtls.tffa__BrandCode__c);
      debitBureauScore = partyDtls.tffa__DebitBureauScore__c != null?String.valueOf(partyDtls.tffa__DebitBureauScore__c):'';
      brandName = brandDtls.Name;
	  brandAddress = brandDtls.Address__c;
      brandPhoneNumber = brandDtls.ContactNumber__c;
      tffa.Logger.debug('brandName:' + brandName);
      tffa.Logger.debug('brandAddress:' + brandAddress);
      tffa.Logger.debug('debitBureauScore:' + debitBureauScore);
    } catch (Exception ex) {
      tffa.Logger.debug(' Exception msg : ' + ex.getMessage() + ' ' + ex.getStackTraceString());
    }
  }
}