objects/tffa__Address__c.object
<CustomObject>
    <description>An address is a collection of information, presented in a mostly fixed format, used to give the location of a building, apartment, or other structure or a plot of land, generally using political boundaries and street names as references,  along with other identifiers such as house or apartment numbers

 For more reference lookup https://en.wikipedia.org/wiki/Address_(geography)#United_States</description>
    <fields>
        <fullName>tffa__City__c</fullName>
        <description>The city of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Line1__c</fullName>
        <description>line 1 of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Line1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Line2__c</fullName>
        <description>line 2 of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <description>A state is a geographical region of a country used for administrative or political purposes,</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ZipCode__c</fullName>
        <description>Also known as post code , a series of numbers that forms part of an address, used to help organize post so that it can be delivered more quickly</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ApplicantRole__c.object
<CustomObject>
    <description>Defines possible roles played by a Party (or Applicant) on an Application. e.g. SOLE_OWNER, JOINT_OWNER, AUTHORIZED_SIGNATORY etc. These roles finally translate to roles on opened accounts. Each role has specific characteristics, that can influence the relationship. e.g.parties with SOLE_OWNER, JOINT_OWNER roles become owners of the account, whereas ones with AGENT, GUARANTOR roles do not. Roles may be categorized based on this nature of relationship. Roles may also have applicable authority list. These control what actions are permitted on the account.</description>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>A unique identifier for the role. Usually corresponds to role maintained in core system.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Applicant Role</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicant Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>Fis branch code for Location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Branch Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account address for purposes of statement etc. If Address Prefill Source Id is set, the address details are not persisted directly, only address id is persisted.</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__DepositBoxAccountNumber__c</fullName>
        <description>Box Number of the safe deposit box. Include 3 pieces of information, the branch number, region code and box number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Deposit box account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__DepositBoxCode__c</fullName>
        <description>Code of the safe deposit box as identified by the core banking system</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Deposit box code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <defaultValue>&quot;Init&quot;</defaultValue>
        <description>The stage of the application in context of the product applied. This will be different for each product and is more granular than the status field.This field will be updated on the state transition the application in the origination workflow.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ApplicationPartyXref__c.object
<CustomObject>
    <description>Each Applicant of the submission can play different roles in the application and the eventual account.</description>
    <fields>
        <fullName>tffa__ApplicantRole__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The role played by the party in the application. Finally translates to role on opened account.</description>
        <label>Role</label>
        <referenceTo>tffa__ApplicantRole__c</referenceTo>
        <relationshipLabel>Application Parties</relationshipLabel>
        <relationshipName>ApplicationPartyXrefs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Beneficiary__c.object
<CustomObject>
    <description>A beneficiary typically refers to someone who is eligible to receive distributions from deposits upon death of primary owner of account. Beneficiary capture typically happens for Certificate Deposits.
Designating a beneficiary not only ensures the CD will not have to go through probate when the applicant dies.</description>
    <fields>
        <fullName>CZParty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Party</relationshipLabel>
        <relationshipName>Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Beneficiary address</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Beneficiaries</relationshipLabel>
        <relationshipName>Beneficiaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Beneficiaries</relationshipLabel>
        <relationshipName>Beneficiaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__FirstName__c</fullName>
        <description>First name of beneficiary</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>Last name of beneficiary</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__MiddleName__c</fullName>
        <description>The middle name of the beneficiary.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryPhone__c</fullName>
        <description>Primary phone number of the beneficiary</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>tffa__Suffix__c</fullName>
        <description>The name suffix of the beneficiary. (E.g., JR = Junior, SR = Senior, etc.)</description>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Suffix</valueSetName>
        </valueSet>
    </fields>
    <label>Beneficiary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Beneficiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>Fis branch code for Location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Branch Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__FirstName__c</fullName>
        <description>The first name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>The last name of the individual represented by the parent object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__MiddleName__c</fullName>
        <description>The middle name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryPhone__c</fullName>
        <description>Primary phone number of the party</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Primary phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Suffix__c</fullName>
        <description>The name suffix of the individual represented by the parent object. (E.g., JR = Junior, SR = Senior, etc.)</description>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Suffix</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyAddressXref__c.object
<CustomObject>
    <description>Association table between Party and Address . This supports capture of multiple types and also periodAtAddress.
This creates an address book of the party</description>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <description>The address lookup @managed</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyAddresses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>The party which owns the address.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>AddressXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Address Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartyAddresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__PartyPartyXref__c.object
<CustomObject>
    <description>A relationship between 2 applicants of a submission. 
Personal relationship could be SPOUSE, PARENT, FRIENDS.
Business relationship between a company and an individual could be DIRECTOR, OWNER, EXECUTIVE, PARTNER etc. In additional the ownership percentage can be captured for OWNER type of relationship. 
Relationship between 2 company type applicants can also be captured such as PARENT and SUBSIDIARY.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Party managing the relationship</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Related To</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Party Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Party Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/tffa__Suffix.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Jr</fullName>
    </customValue>
    <customValue>
        <fullName>Sr</fullName>
        <label>Sr.</label>
    </customValue>
    <customValue>
        <fullName>II</fullName>
    </customValue>
    <customValue>
        <fullName>III</fullName>
    </customValue>
    <customValue>
        <fullName>IV</fullName>
    </customValue>
    <customValue>
        <fullName>246</fullName>
        <isActive>false</isActive>
        <label>246</label>
    </customValue>
    <customValue>
        <fullName>Esq</fullName>
        <isActive>false</isActive>
        <label>Esq</label>
    </customValue>
    <customValue>
        <fullName>VI</fullName>
        <isActive>false</isActive>
        <label>VI</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <isActive>false</isActive>
        <label>V</label>
    </customValue>
    <customValue>
        <fullName>2nd</fullName>
        <isActive>false</isActive>
        <label>2nd</label>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
        <isActive>false</isActive>
        <label>Test</label>
    </customValue>
    <description>The name suffix of the individual represented by the parent object. (E.g., JR = Junior, SR = Senior, etc.)</description>
    <masterLabel>Suffix</masterLabel>
</GlobalValueSet>

classes/FISCCDOAddSDBDeputyExtension.cls
public with sharing class FISCCDOAddSDBDeputyExtension {

  public static List<FISCCDepositOriginationRequestBaseDTO> invokeDepositeBoxDeputy(
    tffa__Application__c appObj,
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    List<FISCCDepositOriginationRequestBaseDTO> lstFisccDepositOriginationRequestBaseDTO = new List<FISCCDepositOriginationRequestBaseDTO>();
    FISCCDepositOriginationRequestBaseDTO fisccDepositOriginationRequestBaseDTO = null;
    try {

      List<tffa__Party__c> deputyList = new List<tffa__Party__c>();
      for (tffa__ApplicationPartyXref__c appParty : appObj.tffa__PartyXrefs__r) {
        if(FISCCIntegrationConstants.DEPUTY.equalsIgnoreCase(appParty.tffa__ApplicantRole__r.tffa__Code__c) && !appParty.CZDeputyCreated__c){

          deputyList.add(appParty.tffa__party__r);
          FISCCDepositOriginationExtension.deputyId.add(appParty.Id);

          if(deputyList.size() == 2) {
            fisccDepositOriginationRequestBaseDTO = depositBoxDeputyRequest(deputyList, appObj);
            lstFisccDepositOriginationRequestBaseDTO.add(fisccDepositOriginationRequestBaseDTO);
            deputyList.clear();
          }
        }
      }

      if(deputyList.size() == 1){
        fisccDepositOriginationRequestBaseDTO = depositBoxDeputyRequest(deputyList, appObj);
        lstFisccDepositOriginationRequestBaseDTO.add(fisccDepositOriginationRequestBaseDTO);
        deputyList.clear();
      }

      return lstFisccDepositOriginationRequestBaseDTO;
    } catch (Exception ex) {
      tffa.Logger.error('Exception in invokeDepositeBoxOwner : ' + ex.getMessage() + ex.getLineNumber() + ex.getStackTraceString());
      return lstFisccDepositOriginationRequestBaseDTO;
    }
  }

  public static FISCCDepositOriginationRequestBaseDTO depositBoxDeputyRequest(
    List<tffa__Party__c> deputyList,
    tffa__Application__c appObj
  ) {
    FISCCDepositOriginationRequestBaseDTO fisccDepositOriginationRequestBaseDTO = null;
    CZSDBAddDeputyRequest request = new CZSDBAddDeputyRequest();
    request.SvcID = FISCCIntegrationConstants.SVCID_SDBAddDeputy;

    request.boxDeputies.BoxNbr = appObj.tffa__DepositBoxAccountNumber__c;
    request.boxDeputies.BoxPrfx = appObj.tffa__DepositBoxCode__c;
    request.boxDeputies.Brnch = appObj.FISBranchCode__c;

    if(deputyList.size() > 0){
      generateDeputy1request(request, deputyList[0]);
    } 
    
    if(deputyList.size() > 1){
      generateDeputy2request(request, deputyList[1]);
    }

    fisccDepositOriginationRequestBaseDTO = request;
      
    return fisccDepositOriginationRequestBaseDTO;
  }

  public static CZSDBAddDeputyRequest generateDeputy1request(CZSDBAddDeputyRequest request, tffa__Party__c partyObj){

    request.boxDeputies.Deputy1ShrtNme = CZWTFCCommonHelper.getFormattedFullName(
      partyObj.tffa__FirstName__c,
      partyObj.tffa__MiddleName__c,
      partyObj.tffa__LastName__c,
      partyObj.tffa__Suffix__c,
      FISCCIntegrationConstants.CUST_NAME_LENGTH_1
    );

    request.boxDeputies.Deputy1NmeAddr1 = CZWTFCCommonHelper.getFormattedFullName(
      partyObj.tffa__FirstName__c,
      partyObj.tffa__MiddleName__c,
      partyObj.tffa__LastName__c,
      partyObj.tffa__Suffix__c,
      FISCCIntegrationConstants.FULL_NAME_LENGTH
    );

    tffa__Address__c addressObj = partyObj.tffa__AddressXrefs__r[0].tffa__Address__r;

    // Set Address
    if(addressObj != null){
      request.boxDeputies.Deputy1NmeAddr2 = addressObj.tffa__Line1__c;

      if(addressObj.tffa__Line2__c != null){
        request.boxDeputies.Deputy1NmeAddr3 = addressObj.tffa__Line2__c;
        request.boxDeputies.Deputy1NmeAddr4 = addressObj.tffa__City__c + ' ' + addressObj.tffa__State__c + ' ' +
        addressObj.tffa__ZipCode__c;
      } else {
        request.boxDeputies.Deputy1NmeAddr3 = addressObj.tffa__City__c + ' ' + addressObj.tffa__State__c + ' ' +
        addressObj.tffa__ZipCode__c;
      }
    }

    // Set Phone number
    if(partyObj.tffa__PrimaryPhone__c != null){
      String phoneNumber = getPhoneNumber(partyObj.tffa__PrimaryPhone__c);
      request.boxDeputies.Deputy1HmPhPrt1 = phoneNumber.substring(0, 3);
      request.boxDeputies.Deputy1HmPhPrt2 = phoneNumber.substring(3, 6);
      request.boxDeputies.Deputy1HmPhPrt3 = phoneNumber.substring(6);
    }

    // Set Tax Id and type
    request.boxDeputies.Deputy1TaxNbr = partyObj.tffa__NationalIdentifierValue__c;
    request.boxDeputies.Deputy1TaxId = CZWTFCCommonHelper.getTaxIdType(partyObj.tffa__NationalIdentifierType__c);

    return request;
  }

  public static CZSDBAddDeputyRequest generateDeputy2request(CZSDBAddDeputyRequest request, tffa__Party__c partyObj){
    
    request.boxDeputies.Deputy2ShrtNme = CZWTFCCommonHelper.getFormattedFullName(
      partyObj.tffa__FirstName__c,
      partyObj.tffa__MiddleName__c,
      partyObj.tffa__LastName__c,
      partyObj.tffa__Suffix__c,
      FISCCIntegrationConstants.CUST_NAME_LENGTH_1
    );

    request.boxDeputies.Deputy2NmeAddr1 = CZWTFCCommonHelper.getFormattedFullName(
      partyObj.tffa__FirstName__c,
      partyObj.tffa__MiddleName__c,
      partyObj.tffa__LastName__c,
      partyObj.tffa__Suffix__c,
      FISCCIntegrationConstants.FULL_NAME_LENGTH
    );

    tffa__Address__c addressObj = partyObj.tffa__AddressXrefs__r[0].tffa__Address__r;

    // Set Address
    if(addressObj != null){
      request.boxDeputies.Deputy2NmeAddr2 = addressObj.tffa__Line1__c;

      if(addressObj.tffa__Line2__c != null){
        request.boxDeputies.Deputy2NmeAddr3 = addressObj.tffa__Line2__c;
        request.boxDeputies.Deputy2NmeAddr4 = addressObj.tffa__City__c + ' ' + addressObj.tffa__State__c + ' ' +
        addressObj.tffa__ZipCode__c;
      } else {
        request.boxDeputies.Deputy2NmeAddr3 = addressObj.tffa__City__c + ' ' + addressObj.tffa__State__c + ' ' +
        addressObj.tffa__ZipCode__c;
      }
    }

    // Set Phone number
    if(partyObj.tffa__PrimaryPhone__c != null){
      String phoneNumber = getPhoneNumber(partyObj.tffa__PrimaryPhone__c);
      request.boxDeputies.Deputy2HmPhPrt1 = phoneNumber.substring(0, 3);
      request.boxDeputies.Deputy2HmPhPrt2 = phoneNumber.substring(3, 6);
      request.boxDeputies.Deputy2HmPhPrt3 = phoneNumber.substring(6);
    }

    // Set Tax Id and type
    request.boxDeputies.Deputy2TaxNbr = partyObj.tffa__NationalIdentifierValue__c;
    request.boxDeputies.Deputy2TaxId = CZWTFCCommonHelper.getTaxIdType(partyObj.tffa__NationalIdentifierType__c);

    return request;
  }

  public static String getPhoneNumber(String phonenumber){
    phonenumber = phonenumber.reverse();
    phonenumber = phonenumber.substring(0,10);
    phonenumber = phonenumber.reverse();

    return phonenumber;
  }
}