objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>Unique code for the brand</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>tffa__ExternalId__c</fullName>
        <description>External id of the brand as referred by external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__BrandLocation__c.object
<CustomObject>
    <description>A list of locations associated with brand</description>
    <fields>
        <fullName>tffa__Brand__c</fullName>
        <description>Reference to the parent brand object.</description>
        <label>Brand</label>
        <referenceTo>tffa__Brand__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__ExternalId__c</fullName>
        <description>External id of the brand as referred by external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>tffa__Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Location which is linked to the brand</description>
        <label>Location</label>
        <referenceTo>tffa__Location__c</referenceTo>
        <relationshipLabel>Brand Locations</relationshipLabel>
        <relationshipName>BrandLocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Brand Location</label>
    <nameField>
        <displayFormat>BL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Location__c.object
<CustomObject>
    <description>Named geographical place (such as a branch or terminal) that provides permanent facilities for movement of goods (such as customs, storage, and other support services) or is designated for a stated purpose. Read more: http://www.businessdictionary.com/definition/location.html</description>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>A logical identifier that is more human friendly.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>tffa__ExternalId__c</fullName>
        <description>External id of the brand as referred by external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Location (branch)</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (branch)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Unique identifier for the product</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>tffa__ExternalId__c</fullName>
        <description>External id as referred by external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ProductFeature__c.object
<CustomObject>
    <description>Product can have many business features, which can be configured for the consumption of the use cases.</description>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>A logical identifier for the product feature.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ExternalId__c</fullName>
        <description>External id as referred by external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <description>Reference to parent product</description>
        <label>Product</label>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipName>Features</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Product Feature</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial  Product Features</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__ProductMatrix__c.object
<CustomObject>
    <description>Represents business rules for filtering products available for applying. Criteria for filtering may be based on the originating channel, branch and even user (by skills).</description>
    <fields>
        <fullName>tffa__ExternalId__c</fullName>
        <description>External id as referred by external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The outcome of the rule, an allowed product.</description>
        <label>Product (outcome)</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Matrices</relationshipLabel>
        <relationshipName>Matrices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Product Matrix</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ProductTerm__c.object
<CustomObject>
    <description>Configuration to maintain rate and purpose for allowed amount ranges and term ranges where applicable. This can also be used to validate the amount and term.</description>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <defaultValue>&quot;PT-0001&quot;</defaultValue>
        <description>A logical identifier for the term. Could be a combination of term and amount information.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ExternalId__c</fullName>
        <description>External id as referred by external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <description>Reference to parent product</description>
        <label>Financial Product</label>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipName>Terms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Product Term</label>
    <nameField>
        <displayFormat>PT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Product Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CZWTFCProductRepository.cls
public with sharing class CZWTFCProductRepository extends tffa.AbstractRepository {
  /**
   *
   */
  public static List<tffa__ProductMatrix__c> getAllProductsMatrix() {
    String q = new tffa.QueryBuilder(tffa__ProductMatrix__c.SObjectType).selectFields().build().toQuery();

    List<tffa__ProductMatrix__c> result = (List<tffa__ProductMatrix__c>) doQuery(q, new List<Object>{});
    return result.isEmpty() ? null : result;
  }

  public static tffa__Product__c fetchProductById(String id) {
    String q = new tffa.QueryBuilder(tffa__Product__c.SObjectType).selectFields().whereClause('Id', '=:attr1').build().toQuery();

    List<tffa__Product__c> result = (List<tffa__Product__c>) doQuery(q, new List<Object>{ id });
    return result.isEmpty() ? null : result.get(0);
  }

  /**
   *
   */
  public static tffa__ProductFeature__c fetchProductFeatByExternalId(String externalID, String name) {
    String q = new tffa.QueryBuilder(tffa__ProductFeature__c.SObjectType)
      .selectFields()
      .whereClause('tffa__ExternalId__c', '=:attr1')
      .OpAnd()
      .whereClause('Name', '!=:attr2')
      .build()
      .toQuery();

    List<tffa__ProductFeature__c> result = (List<tffa__ProductFeature__c>) doQuery(q, new List<Object>{ externalID, name });
    return result.isEmpty() ? null : result[0];
  }

  /**
   *
   */
  public static List<tffa__ProductMatrix__c> getProdMatrixByProdCode(String prodCode) {
    List<tffa__ProductMatrix__c> result = new List<tffa__ProductMatrix__c>();

    String query = new tffa.QueryBuilder(tffa__Product__c.SObjectType)
      .selectFields()
      .whereClause('tffa__Code__c', '=:attr1')
      .build()
      .toQuery();

    List<tffa__Product__c> prod = (List<tffa__Product__c>) doQuery(query, new List<Object>{ prodCode });

    if (prod != null && !prod.isEmpty()) {
      String q = new tffa.QueryBuilder(tffa__ProductMatrix__c.SObjectType)
        .selectFields()
        .whereClause('tffa__Product__c', '=:attr1')
        .build()
        .toQuery();

      result = (List<tffa__ProductMatrix__c>) doQuery(q, new List<Object>{ prod[0].Id });
    }
    return result.isEmpty() ? null : result;
  }

  public static Map<String, tffa__Location__c> fetchLocationByIds(List<String> locIds) {
    Map<String, tffa__Location__c> resultMap = new Map<String, tffa__Location__c>();
    String q = new tffa.QueryBuilder(tffa__Location__c.SObjectType).selectFields().whereClause('Id', '= :attr1').build().toQuery();

    List<tffa__Location__c> result = (List<tffa__Location__c>) doQuery(q, new List<Object>{ locIds });

    if (!result.isEmpty()) {
      for (tffa__Location__c loc : result) {
        resultMap.put(loc.tffa__Code__c, loc);
      }
    }

    return resultMap;
  }

  public static List<tffa__BrandLocation__c> fetchLocationByCodes(String brandCode) {
    tffa__Brand__c brandObj = CZWTFCBrandRepository.fetchBrandByCode(brandCode);
    List<tffa__BrandLocation__c> result = new List<tffa__BrandLocation__c>();
    String q = new tffa.QueryBuilder(tffa__BrandLocation__c.SObjectType)
      .selectFields()
      .whereClause('tffa__Brand__c', '= :attr1')
      .build()
      .toQuery();

    if (brandObj != null) {
      result = (List<tffa__BrandLocation__c>) doQuery(q, new List<Object>{ brandObj.Id });
    }
    return result.isEmpty() ? new List<tffa__BrandLocation__c>() : result;
  }

  public static List<tffa__ProductMatrix__c> getAllDigitalProductsMatrix() {
    Map<String, Object> mp = new Map<String, Object>();
    mp.put('Channel__c', 'DIGITAL');
    String q = new tffa.QueryBuilder(tffa__ProductMatrix__c.SObjectType)
      .selectFields()
      .whereWithFacts('StateZipValidation', mp)
      .build()
      .toQuery();

    List<tffa__ProductMatrix__c> result = (List<tffa__ProductMatrix__c>) doQuery(q, new List<Object>{});
    return result.isEmpty() ? null : result;
  }

  public static tffa__Product__c getProductByCode(String prodCode) {

    String query = new tffa.QueryBuilder(tffa__Product__c.SObjectType)
      .selectFields()
      .selectChildObject('tffa__Terms__r')
      .selectFields()
      .build()
      .whereClause('tffa__Code__c', '=:attr1')
      .build()
      .toQuery();

    List<tffa__Product__c> prod = (List<tffa__Product__c>) doQuery(query, new List<Object>{ prodCode });

    return prod.isEmpty() ? null : prod[0];
  }

  public static Map<String, tffa__Product__c> getProductByIds(Set<String> ids) {

    String query = new tffa.QueryBuilder(tffa__Product__c.SObjectType)
      .selectFields()
      .selectChildObject('tffa__Terms__r')
      .selectFields()
      .build()
      .whereClause('Id', 'In:attr1')
      .build()
      .toQuery();

    List<tffa__Product__c> prod = (List<tffa__Product__c>) doQuery(query, new List<Object>{ ids });

    Map<String, tffa__Product__c> productMap = new Map<String, tffa__Product__c>();
    if(!prod.isEmpty()){
      for(tffa__Product__c product : prod){
        productMap.put(product.Id, product);
      }
    }

    return productMap;
  }

  /*
  public static List<tffa__Product__c> readAllProducts(List<String> ids){
   
    String query = new tffa.QueryBuilder(tffa__Product__c.SObjectType)
    .selectFields()
    .selectChildObject('tffa__Features__r')
    .selectFields()
    .build()
    .whereClause('id', 'In:attr1')
    .build()
    .toQuery();

    List<tffa__Product__c> prod = (List<tffa__Product__c>) doQuery(query, new List<Object>{ ids });
    return prod.isEmpty() ? null:prod;
  }*/
}