objects/tffa__AccountPreference__c.object
<CustomObject>
    <description>List of account preferences/additional services applied along with the application. Example values are ATM_CARD, INTERNET_BANKING, CHECKBOOK</description>
    <fields>
        <fullName>tffa__AddOnServiceType__c</fullName>
        <description>Captures the type of applied add-on service.</description>
        <label>Add-on service type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__AddOnServiceType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application</description>
        <inlineHelpText>Master Detail Lookup</inlineHelpText>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Account Preferences</relationshipLabel>
        <relationshipName>AccountPreferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__CardNumber__c</fullName>
        <description>Card number (of applied debit card)</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Card number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__EmbossedName__c</fullName>
        <description>Name as it would appear on a card. e.g. Add-on Card.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Embossed name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Stores whether the preference or service was opted for.</description>
        <label>Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to related party.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Account Preferences</relationshipLabel>
        <relationshipName>AccountPreferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Current status (of processing) of the account preference.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__AccountPreferenceStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Account Preference</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>AccountOpeningStatus__c</fullName>
        <description>Account Opening Status</description>
        <inlineHelpText>This includes Customer creation, Account opening, Beneficiary creation, Update customer missing information,Account funding, Funding hold</inlineHelpText>
        <label>Account Opening Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ApplicationProcessStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DebitCardIssuanceStatus__c</fullName>
        <description>Debit Card Issuance Status</description>
        <label>Debit Card Issuance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ApplicationProcessStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>DebitCardIssueRetryCount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Debit Card Issue Retry Count</description>
        <label>Debit Card Issue Retry Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tffa__AccountPurpose__c</fullName>
        <description>Specialised Account Purpose</description>
        <label>Account purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__AccountPurpose</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the application</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/ApplicationProcessStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>SUCCESS</fullName>
    </customValue>
    <customValue>
        <fullName>FAILURE</fullName>
    </customValue>
    <customValue>
        <fullName>PENDING</fullName>
        <default>true</default>
        <label>PENDING</label>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
        <label>Not Applicable</label>
    </customValue>
    <description>Application Process Status.</description>
    <masterLabel>ApplicationProcessStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__AccountPreferenceStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
        <label>Failed</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>List of status(s) (of processing) of account preference.</description>
    <masterLabel>AccountPreferenceStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__AccountPurpose.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>FIDUCIARY</fullName>
        <label>Fiduciary</label>
    </customValue>
    <customValue>
        <fullName>REPRESENTIVE_PAYEE</fullName>
        <label>Representative Payee</label>
    </customValue>
    <customValue>
        <fullName>ESCROW</fullName>
        <label>Escrow</label>
    </customValue>
    <customValue>
        <fullName>COURT_ORDERED</fullName>
        <label>Court Ordered</label>
    </customValue>
    <customValue>
        <fullName>FBO</fullName>
    </customValue>
    <customValue>
        <fullName>UTMA</fullName>
    </customValue>
    <customValue>
        <fullName>MINOR</fullName>
        <label>Minor</label>
    </customValue>
    <customValue>
        <fullName>POA</fullName>
    </customValue>
    <customValue>
        <fullName>TRUST</fullName>
        <label>Trust</label>
    </customValue>
    <customValue>
        <fullName>GUARDIANSHIP</fullName>
        <label>Guardianship</label>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>ESTATE</fullName>
        <label>Estate</label>
    </customValue>
    <description>A list of specialised account purposes</description>
    <masterLabel>AccountPurpose</masterLabel>
</GlobalValueSet>

classes/FISCCCardBaseIntegrationExecutor.cls
public inherited sharing class FISCCCardBaseIntegrationExecutor {
  public static List<String> statuses = new List<String>{ 'FUNDED', 'ACCOUNT_OPENED' };

  public static tffa__Application__c processDebitCardRequest(tffa__Application__c app) {
    tffa__AccountPreference__c accPref = new tffa__AccountPreference__c();
    List<tffa__AccountPreference__c> accPrefList = new List<tffa__AccountPreference__c>();
    String cardNoGenLogKey = null;
    String cardDOLogKey = null;
    String cardCustDemographicsLogKey = null;
    String ExpediteCardLogKey = null;
    Integer i = 0;
    try {
      FISCCIntegrationLogService.applicationCode = 'CB'; // Set Appplication code to CB
      if (String.isBlank(FISCCIntegrationLogService.auth)) {
        FISCCIntegrationLogService.auth = FISCCGetAccessTokenProvider.processGetAccessToken(FISCCIntegrationLogService.charterConfig);
      }
      accPrefList = app.tffa__AccountPreferences__r;
      tffa__Party__c partyObj;
      Boolean isSuccess = false;
      String accPrefStatus;
      if (!containsDebitCard(app)) {
        app.DebitCardIssuanceStatus__c = CZWTFCConstants.PROCESS_STATUS_NOT_APPLICABLE;
        return app;
      }
      for (i = 0; i < accPrefList.size(); i++) {
        accPref = accPrefList.get(i);

        if (!FISCCSubmissionExecutor.withinGovernorLimits()) {
          FISCCIntegrationLogService.submissionObj.CZRetryAccountOpening__c = true;
          return app;
        }

        if (
          !(CZWTFCConstants.ADDON_STATUS_COMPLETED).equals(accPref.tffa__Status__c) &&
          accPref.tffa__AddOnServiceType__c == FISCCIntegrationConstants.DBT_TYPE &&
          accPref.tffa__Enabled__c
        ) {
          accPrefStatus = CZWTFCConstants.ADDON_STATUS_FAILED;

          if (!Test.isRunningTest() && app.tffa__AccountPurpose__c != 'DEBIT_CARD' && getPrimaryAccountStatus(accPref)) {
            app.DebitCardIssuanceStatus__c = CZWTFCConstants.PROCESS_STATUS_FAILURE;
            app.DebitCardIssueRetryCount__c = app.DebitCardIssueRetryCount__c + 1;
            return app;
          }

          if (FISCCIntegrationLogService.partyObjMap.containsKey(accPref.tffa__party__c)) {
            partyObj = FISCCIntegrationLogService.partyObjMap.get(accPref.tffa__party__c);
          }

          FISCCIntegrationLogService.setCurrentLog(
            FISCCIntegrationConstants.DEBIT_CARD_ISSUE +
            accPref.tffa__EmbossedName__c +
            '-' +
            accPref.Id
          );

          if (
            FISCCIntegrationLogService.isLogNewOrFailed(
              FISCCIntegrationConstants.DEBIT_CARD_ISSUE +
              accPref.tffa__EmbossedName__c +
              '-' +
              accPref.Id
            )
          ) {
            // CardNo generation
            cardNoGenLogKey = FISCCIntegrationLogService.setCurrentLogItem(
              FISCCIntegrationConstants.DEBIT_CARDNO_GEN + accPref.tffa__EmbossedName__c,
              accPref.Id,
              false
            );

            if (FISCCIntegrationLogService.isLogItemNewOrFailed(cardNoGenLogKey)) {
              try {
                tffa.Logger.debug('cardNoGen logic started for accPref :' + accPref.Id);
                isSuccess = FISCCCardBaseIntegrationProvider.generateCardNo(accPref, partyObj);
                tffa.Logger.debug('cardNoGen isSuccess : ' + isSuccess);
                if (isSuccess) {
                  FISCCIntegrationLogService.setLogItemOk(
                    FISCCIntegrationConstants.DCARDNOGEN_API_NAME,
                    FISCCIntegrationConstants.DEBIT_CARDNO_GEN_SUCCESS
                  );
                  app.tffa__AccountPreferences__r.get(i).tffa__CardNumber__c = FISCCCardBaseIntegrationHelper.cardNumber;
                } else {
                  FISCCIntegrationLogService.setLogItemFailed(
                    FISCCIntegrationConstants.DCARDNOGEN_API_NAME,
                    FISCCIntegrationConstants.ErrorMessage
                  );
                  FISCCIntegrationLogService.setLogFailed(FISCCIntegrationConstants.DEBIT_CARD_FAILURE);
                }
                tffa.Logger.debug('cardNoGenResult isAPICallSuccess : ' + isSuccess);
              } catch (Exception ex) {
                FISCCIntegrationLogService.setLogItemFailed(
                  FISCCIntegrationConstants.DCARDNOGEN_API_NAME,
                  (FISCCIntegrationConstants.DEBIT_CARDNO_GEN_FAILURE +
                  ' exception : ' +
                  ex.getMessage())
                );
                FISCCIntegrationLogService.setLogFailed(FISCCIntegrationConstants.DEBIT_CARD_FAILURE);
              }
            }

            // Deposit Origination call
            cardDOLogKey = FISCCIntegrationLogService.setCurrentLogItem(
              FISCCIntegrationConstants.DEBIT_CARD_CREATION + accPref.tffa__EmbossedName__c,
              accPref.Id,
              false
            );
            if (
              (FISCCIntegrationLogService.isLogItemNewOrFailed(cardDOLogKey) && FISCCIntegrationLogService.isLogItemOk(cardNoGenLogKey)) ||
              Test.isRunningTest()
            ) {
              try {
                tffa.Logger.debug('card creation logic started for accPref :' + accPref.Id);
                isSuccess = FISCCCardBaseIntegrationProvider.generateDepositOriginationReq(accPref, partyObj, app);
                tffa.Logger.debug('cardCreation isSuccess : ' + isSuccess);
                if (isSuccess) {
                  FISCCIntegrationLogService.setLogItemOk(
                    FISCCIntegrationConstants.DCARDDEPOSITE_ORIGINATION_API_NAME,
                    FISCCIntegrationConstants.DEBIT_CARD_DO_SUCCESS
                  );
                } else {
                  FISCCIntegrationLogService.setLogItemFailed(
                    FISCCIntegrationConstants.DCARDDEPOSITE_ORIGINATION_API_NAME,
                    FISCCIntegrationConstants.ErrorMessage
                  );
                  FISCCIntegrationLogService.setLogFailed(FISCCIntegrationConstants.DEBIT_CARD_FAILURE);
                }
                tffa.Logger.debug('cardCreationResult isAPICallSuccess : ' + isSuccess);
              } catch (Exception ex) {
                FISCCIntegrationLogService.setLogItemFailed(
                  FISCCIntegrationConstants.DCARDDEPOSITE_ORIGINATION_API_NAME,
                  (FISCCIntegrationConstants.DEBIT_CARD_DO_FAILURE +
                  ' exception : ' +
                  ex.getMessage())
                );
                FISCCIntegrationLogService.setLogFailed(FISCCIntegrationConstants.DEBIT_CARD_FAILURE);
              }
            }

            // Customer Demographics
            cardCustDemographicsLogKey = FISCCIntegrationLogService.setCurrentLogItem(
              FISCCIntegrationConstants.DEBIT_CARD_DEMOGRAPHICS,
              accPref.Id,
              false
            );
            if (
              (FISCCIntegrationLogService.isLogItemNewOrFailed(cardCustDemographicsLogKey) &&
              FISCCIntegrationLogService.isLogItemOk(cardDOLogKey)) || Test.isRunningTest()
            ) {
              try {
                tffa.Logger.debug('CardCustDemographics logic started for accPref :' + accPref.Id);
                isSuccess = FISCCCardBaseIntegrationProvider.updateCustomerDemographics(accPref, partyObj, app);
                tffa.Logger.debug('cardCustDemographicsResult isSuccess : ' + isSuccess);
                if (isSuccess) {
                  FISCCIntegrationLogService.setLogItemOk(
                    FISCCIntegrationConstants.DCARDCUSTDEMOGRAPHICS_API_NAME,
                    FISCCIntegrationConstants.DEBIT_CARD_DEMOGRAPHICS_SUCCESS
                  );
                  FISCCIntegrationLogService.setLogOk(FISCCIntegrationConstants.DEBIT_CARD_SUCCESS);
                  accPrefStatus = CZWTFCConstants.ADDON_STATUS_COMPLETED;
                } else {
                  FISCCIntegrationLogService.setLogItemFailed(
                    FISCCIntegrationConstants.DCARDCUSTDEMOGRAPHICS_API_NAME,
                    FISCCIntegrationConstants.ErrorMessage
                  );
                  FISCCIntegrationLogService.setLogFailed(FISCCIntegrationConstants.DEBIT_CARD_FAILURE);
                }
                tffa.Logger.debug('cardCustDemographicsResult isAPICallSuccess : ' + isSuccess);
              } catch (Exception ex) {
                FISCCIntegrationLogService.setLogItemFailed(
                  FISCCIntegrationConstants.DCARDCUSTDEMOGRAPHICS_API_NAME,
                  (FISCCIntegrationConstants.DEBIT_CARD_DEMOGRAPHICS_FAILURE +
                  ' exception : ' +
                  ex.getMessage())
                );
                FISCCIntegrationLogService.setLogFailed(FISCCIntegrationConstants.DEBIT_CARD_FAILURE);
              }
            }

            // Expedite card delivery
            if((FISCCIntegrationLogService.isLogItemOk(cardCustDemographicsLogKey) &&
            accPref.CZDebitCardIssueMethod__c == 'EXPEDITE_SHIPPING') || Test.isRunningTest()){
              ExpediteCardLogKey = FISCCIntegrationLogService.setCurrentLogItem(
                FISCCIntegrationConstants.DEBIT_CARD_EXPEDITE,
                accPref.Id,
                false
              );

              if (
                (FISCCIntegrationLogService.isLogItemNewOrFailed(ExpediteCardLogKey) || Test.isRunningTest())
              ) {
                try {
                  tffa.Logger.debug('Expedite card delivery logic started for accPref :' + accPref.Id);
                  isSuccess = FISCCCardBaseIntegrationProvider.generateExpediteDeliveryReq(accPref, partyObj, app);
                  tffa.Logger.debug('cardCustDemographicsResult isSuccess : ' + isSuccess);
                  if (isSuccess) {
                    FISCCIntegrationLogService.setLogItemOk(
                      FISCCIntegrationConstants.DCARDEXPEDITEDELIVERY_API_NAME,
                      FISCCIntegrationConstants.DEBIT_CARD_EXPEDITE_SUCCESS
                    );
                    FISCCIntegrationLogService.setLogOk(FISCCIntegrationConstants.DEBIT_CARD_SUCCESS);
                    accPrefStatus = CZWTFCConstants.ADDON_STATUS_COMPLETED;
                  } else {
                    FISCCIntegrationLogService.setLogItemFailed(
                      FISCCIntegrationConstants.DCARDEXPEDITEDELIVERY_API_NAME,
                      FISCCIntegrationConstants.ErrorMessage
                    );
                    FISCCIntegrationLogService.setLogFailed(FISCCIntegrationConstants.DEBIT_CARD_FAILURE);
                    accPrefStatus = CZWTFCConstants.ADDON_STATUS_FAILED;
                  }
                  tffa.Logger.debug('cardCustDemographicsResult isAPICallSuccess : ' + isSuccess);
                } catch (Exception ex) {
                  FISCCIntegrationLogService.setLogItemFailed(
                    FISCCIntegrationConstants.DCARDEXPEDITEDELIVERY_API_NAME,
                    (FISCCIntegrationConstants.DEBIT_CARD_EXPEDITE_FAILURE +
                    ' exception : ' +
                    ex.getMessage())
                  );
                  FISCCIntegrationLogService.setLogFailed(FISCCIntegrationConstants.DEBIT_CARD_FAILURE);
                }
              }
            }

            if (app.tffa__AccountPreferences__r.get(i).tffa__Status__c != CZWTFCConstants.ADDON_STATUS_COMPLETED) {
              app.tffa__AccountPreferences__r.get(i).tffa__Status__c = accPrefStatus;

              if (!accPref.CZSecAccountAdditionFlag__c || Test.isRunningTest()) {
                // Set to FAILED so that AccountOpeningStatus__c will be set for FAILURE for Retry
                //app.tffa__AccountPreferences__r.get(i).tffa__Status__c = CZWTFCConstants.ADDON_STATUS_FAILED;

                isSuccess = false;

                FISCCIntegrationLogService.setCurrentLogItem(
                  FISCCIntegrationConstants.DEBIT_CARD_CREATION + accPref.tffa__EmbossedName__c,
                  accPref.Id,
                  false
                );

                FISCCIntegrationLogService.setLogItemFailed(
                  FISCCIntegrationConstants.DCARDDEPOSITE_ORIGINATION_API_NAME,
                  FISCCIntegrationConstants.ErrorMessage
                );

                FISCCIntegrationLogService.setLogFailed(FISCCIntegrationConstants.DEBIT_CARD_FAILURE);
              }
            }
          }
        } else {
          isSuccess = true;
        }
      }

      app.DebitCardIssuanceStatus__c = accPrefList.isEmpty() ? CZWTFCConstants.PROCESS_STATUS_NOT_APPLICABLE : getDebitIssuanceStatus(app);

      if (!accPrefList.isEmpty() && !isSuccess) {
        app.DebitCardIssuanceStatus__c = CZWTFCConstants.PROCESS_STATUS_FAILURE;
      }

      if (app.DebitCardIssuanceStatus__c == CZWTFCConstants.PROCESS_STATUS_FAILURE) {
        app.DebitCardIssueRetryCount__c = app.DebitCardIssueRetryCount__c + 1;
      }
    } catch (Exception ex) {
      tffa.Logger.error('Exception in processDebitCardRequest :' + ex.getMessage() + ' :: ' + ex.getStackTraceString());
    } finally {
      FISCCIntegrationLogService.applicationCode = ''; // Reset Appplication code to blank
    }
    return app;
  }

  private static String getDebitIssuanceStatus(tffa__Application__c appObj) {
    Boolean isAllAccPrefStatusCompleted = true;
    for (tffa__AccountPreference__c accPref : appObj.tffa__AccountPreferences__r) {
      if (
        (!(CZWTFCConstants.ADDON_STATUS_COMPLETED).equals(accPref.tffa__Status__c)) &&
        accPref.tffa__AddOnServiceType__c == FISCCIntegrationConstants.DBT_TYPE
      ) {
        isAllAccPrefStatusCompleted = false;
      }
    }

    if (!containsDebitCard(appObj) && appObj.tffa__AccountPreferences__r != null && !appObj.tffa__AccountPreferences__r.isEmpty()) {
      return CZWTFCConstants.PROCESS_STATUS_NOT_APPLICABLE;
    } else if (isAllAccPrefStatusCompleted) {
      return CZWTFCConstants.PROCESS_STATUS_SUCCESS;
    } else {
      return CZWTFCConstants.PROCESS_STATUS_FAILURE;
    }
  }

  public static boolean containsDebitCard(tffa__Application__c app) {
    for (tffa__AccountPreference__c accPref : app.tffa__AccountPreferences__r) {
      if (accPref.tffa__AddOnServiceType__c == FISCCIntegrationConstants.DBT_TYPE && accPref.tffa__Enabled__c) {
        return true;
      }
    }
    return false;
  }

  public static Boolean getPrimaryAccountStatus(tffa__AccountPreference__c accPref) {
    if (!statuses.contains(FISCCIntegrationLogService.applicationObjMap.get(accPref.tffa__Application__c).tffa__Status__c)) {
      return true;
    } else if (
      accPref.PriSavingApplicationId__c != null &&
      FISCCIntegrationLogService.applicationObjMap.get(accPref.PriSavingApplicationId__c) != null &&
      !statuses.contains(FISCCIntegrationLogService.applicationObjMap.get(accPref.PriSavingApplicationId__c).tffa__Status__c)
    ) {
      return true;
    } else {
      return false;
    }
  }
}