objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FISCCCustAccRelnProvider.cls
public with sharing class FISCCCustAccRelnProvider {
  public static boolean createCustAccountRelnship(List<tffa__Party__c> partyObjs, tffa__Application__c appObj, tffa__Submission__c subObj) {
    tffa.Logger.debug('In createCustAccountRelnship');
    Boolean isSuccess = false;
    Boolean isAPICall = false;
    Boolean isAPICallFailed = false;

    try {
      if (String.isBlank(FISCCIntegrationLogService.auth)) {
        FISCCIntegrationLogService.auth = FISCCGetAccessTokenProvider.processGetAccessToken(FISCCIntegrationLogService.charterConfig);
      }
      tffa.logger.debug('FISCCIntegrationLogService.auth in DO==>' + FISCCIntegrationLogService.auth);
      isAPICall = FISCCCustAccRelnExtension.invokeCustAccRelnAPI(partyObjs, appObj, subObj);
      tffa.logger.debug('isAPICall in createCustAccountRelnship==>' + isAPICall);
      if (isAPICall != null && isAPICall) {
        //FISCCIntegrationLogService.setLogOk(FISCCIntegrationConstants.CUSTOMER_ACCOUNT_RELATIONSHIP_SUCCESS);
      } else {
        //FISCCIntegrationLogService.setLogFailed(FISCCIntegrationConstants.CUSTOMER_ACCOUNT_RELATIONSHIP_FAILURE);
        isAPICallFailed = true;
        tffa.Logger.debug('Create DO  Call Failed for parties ::: ' + partyObjs);
      }

      if (isAPICall) {
        isSuccess = true;
      }

      tffa.logger.debug('isSuccess in createCustomerProvider ==>' + isSuccess);
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in createCustAccountRelnship ' + ex.getLineNumber() + ' ' + ex.getMessage());
    }
    return isSuccess;
  }
}