objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>AcctOpenRetryCount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Account Opening Retry Count</description>
        <label>Account Opening Retry Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DPTDId__c</fullName>
        <description>Deposit Number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Deposit Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDMUploadRetryCount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>MDM Upload Retry Count</description>
        <label>MDM Upload Retry Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MDMUploadStatus__c</fullName>
        <description>Status of MDM Upload</description>
        <label>MDM Upload Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SUCCESS</fullName>
                </value>
                <value>
                    <fullName>FAILURE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The final generated account number. This will be set only after the final account number is available as part of the response of an account open API call.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__AccountPurpose__c</fullName>
        <description>Specialised Account Purpose</description>
        <label>Account purpose</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__AccountPurpose</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__DepositBoxAccountNumber__c</fullName>
        <description>Box Number of the safe deposit box. Include 3 pieces of information, the branch number, region code and box number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Deposit box account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ProductCategory__c</fullName>
        <description>Different product category supported by system. This classifies the flow of account opening , the underlying data model and the servicing components about an account.</description>
        <label>Product Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ProductCategory</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the application</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Beneficiary__c.object
<CustomObject>
    <description>A beneficiary typically refers to someone who is eligible to receive distributions from deposits upon death of primary owner of account. Beneficiary capture typically happens for Certificate Deposits.
Designating a beneficiary not only ensures the CD will not have to go through probate when the applicant dies.</description>
    <fields>
        <fullName>CZMDMPartyID__c</fullName>
        <description>MDM Global Id</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MDM Global ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CZParty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Party</relationshipLabel>
        <relationshipName>Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Beneficiaries</relationshipLabel>
        <relationshipName>Beneficiaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - PRIMARY, CONTINGENT</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__BeneficiaryType</valueSetName>
        </valueSet>
    </fields>
    <label>Beneficiary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Beneficiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>CZMDMPartyID__c</fullName>
        <description>MDM Global Id</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MDM Global ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDMUploadRetryCount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>MDM Upload Retry Count</description>
        <label>MDM Upload Retry Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MDMUploadStatus__c</fullName>
        <description>Status of MDM Upload</description>
        <label>MDM Upload Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SUCCESS</fullName>
                </value>
                <value>
                    <fullName>FAILURE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__IsExistingCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current applicant is existing customer of the bank.</description>
        <label>IsExistingCustomer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>CZRetryAccountOpening__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Retry Account Opening is set to true if Governor limit is reached</description>
        <label>Retry Account Opening</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the submission</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__AccountPurpose.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>FIDUCIARY</fullName>
        <label>Fiduciary</label>
    </customValue>
    <customValue>
        <fullName>REPRESENTIVE_PAYEE</fullName>
        <label>Representative Payee</label>
    </customValue>
    <customValue>
        <fullName>ESCROW</fullName>
        <label>Escrow</label>
    </customValue>
    <customValue>
        <fullName>COURT_ORDERED</fullName>
        <label>Court Ordered</label>
    </customValue>
    <customValue>
        <fullName>FBO</fullName>
    </customValue>
    <customValue>
        <fullName>UTMA</fullName>
    </customValue>
    <customValue>
        <fullName>MINOR</fullName>
        <label>Minor</label>
    </customValue>
    <customValue>
        <fullName>POA</fullName>
    </customValue>
    <customValue>
        <fullName>TRUST</fullName>
        <label>Trust</label>
    </customValue>
    <customValue>
        <fullName>GUARDIANSHIP</fullName>
        <label>Guardianship</label>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
    </customValue>
    <customValue>
        <fullName>ESTATE</fullName>
        <label>Estate</label>
    </customValue>
    <description>A list of specialised account purposes</description>
    <masterLabel>AccountPurpose</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__BeneficiaryType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PRIMARY</fullName>
        <default>true</default>
        <label>Primary</label>
    </customValue>
    <customValue>
        <fullName>CONTINGENT</fullName>
        <label>Contingent</label>
    </customValue>
    <description>Type of the Beneficiary</description>
    <masterLabel>BeneficiaryType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>ABANDONED</fullName>
        <label>Abandoned</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>SAVED</fullName>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>SUBMITTED</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>Indicates current status of the submission.This will be computed and be useful for regulations.</description>
    <masterLabel>SubmissionStatus</masterLabel>
</GlobalValueSet>

classes/CZMDMDataUploadExecutor.cls
public inherited sharing class CZMDMDataUploadExecutor {
  public static List<tffa__Application__c> applicationList = new List<tffa__Application__c>();
  public static List<tffa__Party__c> partyList = new List<tffa__Party__c>();

  public static void processRequest(tffa__Submission__c submission) {
    try {
      // Fetch Auth token
      FISCCIntegrationLogService.auth = CZWTFCMulesoftOAuthProvider.getAuthHeader();

      if (FISCCIntegrationLogService.auth == null) {
        return;
      }

      Boolean isDebitCardProduct = false;
      for (tffa__Application__c app : FISCCIntegrationLogService.applicationObjs) {
        if (app.tffa__AccountPurpose__c == 'DEBIT_CARD') {
          isDebitCardProduct = true;
          break;
        }
      }

      Boolean hasExistingCustomers = false;
      Boolean hasNewCustomers = false;

      for (tffa__Party__c party : FISCCIntegrationLogService.partyObjs) {
        if (party.tffa__IsExistingCustomer__c || party.MDMUploadStatus__c == CZWTFCConstants.PROCESS_STATUS_SUCCESS) {
          hasExistingCustomers = true;
        } else {
          hasNewCustomers = true;
        }
      }

      // Call account creation API
      if (hasExistingCustomers && !isDebitCardProduct) {
        for (tffa__Application__c app : FISCCIntegrationLogService.applicationObjs) {
          if (
            app.MDMUploadStatus__c != CZWTFCConstants.PROCESS_STATUS_SUCCESS &&
            (app.tffa__AccountNumber__c != null ||
            app.tffa__DepositBoxAccountNumber__c != null) &&
            (!CZWTFCCommonHelper.isCertificateProduct(app) || app.DPTDId__c != null) &&
            FISCCIntegrationConstants.ACCT_OPEN_STATUS_LIST.contains(app.tffa__Status__c)
          ) {
            if (!FISCCSubmissionExecutor.withinGovernorLimits()) {
              FISCCIntegrationLogService.submissionObj.CZRetryAccountOpening__c = true;
              return;
            }
            try {
              app.MDMUploadStatus__c = CZMDMDataUploadProvider.processAccountCreation(app);
              if (app.MDMUploadStatus__c == CZWTFCConstants.PROCESS_STATUS_FAILURE) {
                app.MDMUploadRetryCount__c++;
                app.MDMUploadStatus__c = 'FAILURE';
                //app.AcctOpenRetryCount__c = app.AcctOpenRetryCount__c + 1;
              }
            } catch (Exception ex) {
              tffa.Logger.error(
                'CZMDMDataUploadExecutor Exception in account creation msg : ' +
                ex.getMessage() +
                ' ' +
                ex.getStackTraceString()
              );
              app.MDMUploadStatus__c = CZWTFCConstants.PROCESS_STATUS_FAILURE;
              app.MDMUploadRetryCount__c++;
              app.MDMUploadStatus__c = 'FAILURE';
              //app.AcctOpenRetryCount__c = app.AcctOpenRetryCount__c + 1;
            }
            //applicationList.add(app);
          }
        }
      }

      // Call customer creation API
      if (hasNewCustomers || isDebitCardProduct) {
        for (tffa__Party__c party : FISCCIntegrationLogService.partyObjs) {
          //tffa__Party__c party = subPartyXref.tffa__Party__r;
          if (
            party.MDMUploadStatus__c != CZWTFCConstants.PROCESS_STATUS_SUCCESS &&
            (!party.tffa__IsExistingCustomer__c || isDebitCardProduct) &&
            !String.isBlank(party.Customer_Number__c)
          ) {
            if (!FISCCSubmissionExecutor.withinGovernorLimits()) {
              FISCCIntegrationLogService.submissionObj.CZRetryAccountOpening__c = true;
              return;
            }
            String mdmStatus = 'FAILURE';
            try {
              if (!isDebitCardProduct || (isDebitCardProduct && party.tffa__Type__c == FISCCIntegrationConstants.INDIVIDUAL)) {
                mdmStatus = CZMDMDataUploadProvider.processCustomerCreation(submission, party);
              }

              party.MDMUploadStatus__c = mdmStatus;
            } catch (Exception ex) {
              tffa.Logger.error(
                'CZMDMDataUploadExecutor Exception in customer creation msg : ' +
                ex.getMessage() +
                ' ' +
                ex.getStackTraceString()
              );

              party.MDMUploadStatus__c = CZWTFCConstants.PROCESS_STATUS_FAILURE;
            }

            if (party.MDMUploadStatus__c == CZWTFCConstants.PROCESS_STATUS_FAILURE) {
              party.MDMUploadRetryCount__c++;
            }

            //partyList.add(party);

            // need to update application status when submission has only new customers
            if (!hasExistingCustomers || isDebitCardProduct) {
              for (tffa__Application__c app : FISCCIntegrationLogService.applicationObjs) {
                if (
                  (app.tffa__AccountNumber__c != null ||
                  app.tffa__DepositBoxAccountNumber__c != null ||
                  isDebitCardProduct) &&
                  (!FISCCIntegrationConstants.CERTIFICATE_PROD_CATEGORY.contains(app.tffa__ProductCategory__c) || app.DPTDId__c != null) &&
                  app.MDMUploadStatus__c != CZWTFCConstants.PROCESS_STATUS_SUCCESS &&
                  FISCCIntegrationConstants.ACCT_OPEN_STATUS_LIST.contains(app.tffa__Status__c)
                ) {
                  app.MDMUploadStatus__c = mdmStatus;

                  if (mdmStatus == CZWTFCConstants.PROCESS_STATUS_FAILURE) {
                    app.MDMUploadRetryCount__c++;
                    app.MDMUploadStatus__c = 'FAILURE';
                    //app.AcctOpenRetryCount__c = app.AcctOpenRetryCount__c + 1;
                  }
                  //applicationList.add(app);
                }
              }
            }
          }
        }
      }

      //call customer update api
      for (tffa__Party__c party : FISCCIntegrationLogService.partyObjs) {
        String mdmUpdateStatus = 'FAILURE';

        if (
          party.MDMUploadStatus__c != CZWTFCConstants.PROCESS_STATUS_SUCCESS &&
          party.tffa__IsExistingCustomer__c &&
          party.CZContactInfoUpdated__c &&
          !String.isBlank(party.CZMDMPartyID__c) &&
          !String.isBlank(party.Customer_Number__c) &&
          party.CZCustomerUpdated__c
        ) {
          if (!FISCCSubmissionExecutor.withinGovernorLimits()) {
            FISCCIntegrationLogService.submissionObj.CZRetryAccountOpening__c = true;
            return;
          }

          try {
            mdmUpdateStatus = CZMDMDataUploadProvider.processCustomerUpdate(submission, party);
            party.MDMUploadStatus__c = mdmUpdateStatus;
          } catch (Exception ex) {
            tffa.Logger.error(
              'CZMDMDataUploadExecutor Exception in customer update msg : ' +
              ex.getMessage() +
              ' ' +
              ex.getStackTraceString()
            );
            mdmUpdateStatus = 'FAILURE';
            party.MDMUploadStatus__c = mdmUpdateStatus;
          }

          if (party.MDMUploadStatus__c == CZWTFCConstants.PROCESS_STATUS_FAILURE) {
            party.MDMUploadRetryCount__c++;
          }
        }
      }
    } catch (Exception ex) {
      tffa.Logger.error('Exception in CZMDMDataUploadExecutor :' + ex.getMessage() + ' :: ' + ex.getStackTraceString());
    }
  }
}