objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>DisclosureConverted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Disclosure Converted to PDF</description>
        <label>DisclosureConverted</label>
        <type>Checkbox</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CZWTFCFCMDocumentUploadBatch.cls
global inherited sharing class CZWTFCFCMDocumentUploadBatch extends tffa.AbstractBatchJob implements Database.Batchable<sObject>, Database.AllowsCallouts {
  public static List<String> statuses = new List<String>{ 'FUNDED', 'ACCOUNT_OPENED' };
  public static Integer retryCount = (Integer) CZWTFCHelperRepository.fetchWintrustEnvConfig().BatchRetryCount__c;
  public static List<String> fcmStatus = new List<String>{ CZWTFCConstants.PROCESS_STATUS_SUCCESS };
  public static List<tffa__Submission__c> submissionLst = new List<tffa__Submission__c>();

  global List<tffa__Application__c> start(Database.BatchableContext batchableContext) {
    tffa.Logger.debug('CZWTFCFCMDocumentUploadBatch Start');
    List<tffa__Application__c> appLst = CZWTFCApplicationRepository.fetchApplicationsForFCM(statuses, retryCount, fcmStatus);
    List<tffa__Application__c> filteredApps = filterApps(appLst);
    tffa.Logger.flush();
    return filteredApps;
  }

  global void execute(Database.BatchableContext batchableContext, List<tffa__Application__c> applications) {
    tffa.Interaction.begin(CZWTFCFCMDocumentUploadBatch.class, 'execute');
    try {
      tffa__Application__c application = applications[0];

      tffa__Application__c app = FCMIntegrationExecutor.processRequest(application);

      CZWTFCApplicationRepository.save(new List<tffa__Application__c>{ app });
    } catch (Exception ex) {
      tffa.Logger.debug('CZWTFCFCMDocumentUploadBatch Exception msg : ' + ex.getMessage() + ' ' + ex.getStackTraceString());
    } finally {
      tffa.Interaction.close();
    }
  }

  global void finish(Database.BatchableContext batchableContext) {
    tffa.Logger.debug('CZWTFCFCMDocumentUploadBatch finish()');
    tffa.Logger.flush();
  }

  private static List<tffa__Application__c> filterApps(List<tffa__Application__c> appLst) {
    List<tffa__Application__c> filterApplications = new List<tffa__Application__c>();
    for (tffa__Application__c appObj : appLst) {
      if (appObj.tffa__Submission__r != null && appObj.tffa__Submission__r.DisclosureConverted__c) {
        filterApplications.add(appObj);
      }
    }

    return filterApplications;
  }
}