objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the application</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__FundingRequest__c.object
<CustomObject>
    <description>Supports the capture of details pertaining to funding a payment obligation using one of the various available sources of funding</description>
    <fields>
        <fullName>MultiPartialFlag__c</fullName>
        <description>Value sent in Approval API call to Elavon. Y means to use partial funds and keep remaining funds in Auth Only state.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Value sent in Approval API call to Elavon. Y means to use partial funds and keep remaining funds in Auth Only state.</inlineHelpText>
        <label>Partial shipment indicator</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReversalRetryCount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>ReversalRetryCount</description>
        <label>Reversal Retry Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tffa__LinkedApplication__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to application.</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Funding Requests</relationshipLabel>
        <relationshipName>LinkedFundingRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Funding status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__FundingStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to parent submission.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Consolidated Funding Requests</relationshipLabel>
        <relationshipName>FundingRequests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__TransactionReferenceId__c</fullName>
        <description>The reference ID generated against the funding transaction from external system.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Transaction reference id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of funding selected for the current application.</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__FundingType</valueSetName>
        </valueSet>
    </fields>
    <label>Funding Request</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the submission</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__FundingStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>FUNDED</fullName>
        <label>Funded</label>
    </customValue>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
        <label>Failed</label>
    </customValue>
    <customValue>
        <fullName>APPROVAL</fullName>
        <label>Approved</label>
    </customValue>
    <customValue>
        <fullName>REVERSED</fullName>
        <label>Reversed</label>
    </customValue>
    <customValue>
        <fullName>REVERSAL_FAILED</fullName>
        <label>Reversal Failed</label>
    </customValue>
    <customValue>
        <fullName>ACH_FILE_GENERATED</fullName>
        <label>ACH File Generated</label>
    </customValue>
    <customValue>
        <fullName>ACH_FILE_FAILED</fullName>
        <label>ACH File Generation Failed</label>
    </customValue>
    <customValue>
        <fullName>HOLD_APPLIED</fullName>
        <label>Hold Applied on Funds</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>REVERSAL_NOT_REQ</fullName>
        <label>Reversal Not Required</label>
    </customValue>
    <customValue>
        <fullName>AUTHORIZED</fullName>
        <isActive>false</isActive>
        <label>AUTHORIZED</label>
    </customValue>
    <description>Status of funding</description>
    <masterLabel>FundingStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__FundingType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>ACH</fullName>
    </customValue>
    <customValue>
        <fullName>WIRE</fullName>
        <label>Wire Transfer</label>
    </customValue>
    <customValue>
        <fullName>CASH</fullName>
        <label>Branch or ATM Deposit</label>
    </customValue>
    <customValue>
        <fullName>DEBIT_CARD</fullName>
        <label>DEBIT CARD</label>
    </customValue>
    <customValue>
        <fullName>INTERNAL_TRANSFER</fullName>
        <label>INTERNAL TRANSFER</label>
    </customValue>
    <customValue>
        <fullName>APPLE_PAY</fullName>
        <isActive>false</isActive>
        <label>APPLE_PAY</label>
    </customValue>
    <customValue>
        <fullName>GOOGLE_PAY</fullName>
        <isActive>false</isActive>
        <label>GOOGLE_PAY</label>
    </customValue>
    <customValue>
        <fullName>CHECK</fullName>
        <isActive>false</isActive>
        <label>CHECK</label>
    </customValue>
    <customValue>
        <fullName>CREDIT_CARD</fullName>
        <isActive>false</isActive>
        <label>CREDIT_CARD</label>
    </customValue>
    <customValue>
        <fullName>PAYPAL</fullName>
        <isActive>false</isActive>
        <label>PAYPAL</label>
    </customValue>
    <description>Type of funding selected for the current deposit application.</description>
    <masterLabel>FundingType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>ABANDONED</fullName>
        <label>Abandoned</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>SAVED</fullName>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>SUBMITTED</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>Indicates current status of the submission.This will be computed and be useful for regulations.</description>
    <masterLabel>SubmissionStatus</masterLabel>
</GlobalValueSet>

classes/CZWTFCDebitCardFundingVoidBatch.cls
global with sharing class CZWTFCDebitCardFundingVoidBatch extends tffa.AbstractBatchJob implements Database.Batchable<sObject>, Database.AllowsCallouts {
  @TestVisible
  private static boolean calledFromTestCls = false;

  global List<tffa__Submission__c> start(Database.BatchableContext batchableCntx) {
    tffa.Logger.debug('CZWTFCDebitCardFundingVoidBatch Job started');

    List<tffa__Submission__c> filterSubList = new List<tffa__Submission__c>();
    List<tffa__Submission__c> subList = CZWTFCSubmissionRepository.fetchSubForCCDelete();

    filterSubList = filterSubs(subList);

    if (Test.isRunningTest()) {
      filterSubList = CZWTFCSubmissionRepository.findtestSubmission();
    }
    tffa.Logger.flush();
    return filterSubList;
  }

  global void execute(Database.BatchableContext batchableCntx, List<SObject> subObject) {
    tffa.Logger.debug('CZWTFCDebitCardFundingVoidBatch execute Datetime Started on : ' + String.valueOf(Datetime.now()));
    Boolean isSuccess = false;
    List<tffa__Submission__c> subList = (List<tffa__Submission__c>) subObject;
    List<tffa__FundingRequest__c> fundObjList = new List<tffa__FundingRequest__c>();

    try {
      for (tffa__Submission__c sub : subList) {
        List<tffa__Submission__c> submissionList = CZWTFCSubmissionRepository.findSubmissionAndAppByIds(new List<String>{ sub.Id });
        if (checkPendingApp(submissionList[0])) {
          boolean doCCDelete = true;
          for (tffa__FundingRequest__c fundObj : submissionList[0].tffa__FundingRequests__r) {
            if (fundObj.MultiPartialFlag__c != null && (fundObj.MultiPartialFlag__c).equalsIgnoreCase('N')) {
              doCCDelete = false;
              break;
            }
          }
          if (doCCDelete) {
            isSuccess = CZWTFCConvergeService.ccDeleteConvergeTrans(
              sub.Id,
              sub.tffa__FundingRequests__r[0].tffa__TransactionReferenceId__c
            );

            for (tffa__FundingRequest__c fundObj : sub.tffa__FundingRequests__r) {
              if (!fundObj.tffa__Status__c.equalsIgnoreCase(CZWTFCConstants.APPROVAL)) {
                if (isSuccess) {
                  fundObj.tffa__Status__c = CZWTFCConstants.REVERSED;
                } else {
                  fundObj.tffa__Status__c = CZWTFCConstants.REVERSAL_FAILED;
                  fundObj.ReversalRetryCount__c += 1;
                }
              }
              fundObjList.add(fundObj);
            }
          } else {
            for (tffa__FundingRequest__c fundObj : sub.tffa__FundingRequests__r) {
              if (!fundObj.tffa__Status__c.equalsIgnoreCase(CZWTFCConstants.APPROVAL)) {
                fundObj.tffa__Status__c = CZWTFCConstants.REVERSAL_NOT_REQ;
                fundObjList.add(fundObj);
              }
            }
          }
        }
      }
      WTFCObjectManagerRepository.doUpsertObjects(fundObjList);
    } catch (Exception ex) {
      tffa.Logger.error('Exception in CZWTFCDebitCardFundingVoidBatch cls: Execute ' + ex.getMessage() + ' ' + ex.getStackTraceString());
    } finally {
      tffa.Logger.flush();
    }
  }

  global void finish(Database.BatchableContext batchableCntx) {
    tffa.Logger.debug('CZWTFCDebitCardFundingVoidBatch execute Completed at  : ' + String.valueOf(Datetime.now()));
    tffa.Logger.flush();
  }

  public List<tffa__Submission__c> filterSubs(List<tffa__Submission__c> sublist) {
    List<tffa__Submission__c> filtersublist = new List<tffa__Submission__c>();
    if (sublist != null && !sublist.isEmpty()) {
      for (tffa__Submission__c sub : sublist) {
        if (
          sub.tffa__FundingRequests__r != null &&
          !sub.tffa__FundingRequests__r.isEmpty() &&
          sub.tffa__Applications__r != null &&
          !sub.tffa__Applications__r.isEmpty()
        ) {
          filtersublist.add(sub);
        }
      }
    }
    return filtersublist;
  }

  public static boolean checkPendingApp(tffa__Submission__c sub) {
    if (Test.isRunningTest() && calledFromTestCls) {
      return true;
    }
    List<tffa__Application__c> appList = CZWTFCApplicationRepository.findApplicationWithChildObjsBySubId(sub);
    List<String> appStatusLst = new List<String>{ CZWTFCConstants.REVIEW, CZWTFCConstants.APPROVED };
    for (tffa__Application__c app : appList) {
      if (appStatusLst.contains(app.tffa__Status__c)) {
        return false;
      } else if ((app.tffa__Status__c).equalsIgnoreCase(CZWTFCConstants.ACCOUNT_OPENED)) {
        if (app.tffa__LinkedFundingRequests__r != null && !app.tffa__LinkedFundingRequests__r.isEmpty()) {
          if ((app.tffa__LinkedFundingRequests__r[0].tffa__Type__c).equalsIgnoreCase(CZWTFCConstants.DEBIT_CARD)) {
            return false;
          }
        }
      }
    }
    return true;
  }
}