objects/tffa__Address__c.object
<CustomObject>
    <description>An address is a collection of information, presented in a mostly fixed format, used to give the location of a building, apartment, or other structure or a plot of land, generally using political boundaries and street names as references,  along with other identifiers such as house or apartment numbers

 For more reference lookup https://en.wikipedia.org/wiki/Address_(geography)#United_States</description>
    <fields>
        <fullName>tffa__City__c</fullName>
        <description>The city of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Line1__c</fullName>
        <description>line 1 of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Line1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Line2__c</fullName>
        <description>line 2 of the address</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Line 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <description>A state is a geographical region of a country used for administrative or political purposes,</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ZipCode__c</fullName>
        <description>Also known as post code , a series of numbers that forms part of an address, used to help organize post so that it can be delivered more quickly</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Zip Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Address</label>
    <nameField>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>CZBillingMode__c</fullName>
        <description>Billing Mode</description>
        <label>Billing Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BANK_BOX</fullName>
                    <label>BANK BOX</label>
                </value>
                <value>
                    <fullName>WAIVE_FEE</fullName>
                    <label>WAIVE FEE</label>
                </value>
                <value>
                    <fullName>PRINT_INVOICE</fullName>
                    <label>PRINT INVOICE</label>
                </value>
                <value>
                    <fullName>AUTO_DEBIT</fullName>
                    <label>AUTO DEBIT</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CZCautionCode1__c</fullName>
        <description>Program Type</description>
        <label>Program Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CautionCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CZCautionCode2__c</fullName>
        <description>Additional Discount Type</description>
        <label>Additional Discount Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CautionCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CZCautionCode3__c</fullName>
        <description>Caution Code 3</description>
        <label>Caution Code 3</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>CautionCode</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CZIsDiscountForFirstYearOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Discount Applies for First Year Only</description>
        <label>Discount Applies for First Year Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CZPrimaryOfficer__c</fullName>
        <description>Primary Officer</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Officer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CZRenewalBillingMode__c</fullName>
        <description>Renewal Billing Mode</description>
        <label>Renewal Billing Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BANK_BOX</fullName>
                    <label>BANK BOX</label>
                </value>
                <value>
                    <fullName>WAIVE_FEE</fullName>
                    <label>WAIVE FEE</label>
                </value>
                <value>
                    <fullName>PRINT_INVOICE</fullName>
                    <label>PRINT INVOICE</label>
                </value>
                <value>
                    <fullName>AUTO_DEBIT</fullName>
                    <label>AUTO DEBIT</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CZSDBDiscountReasonTxt__c</fullName>
        <description>SDB Discount Reason</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SDB Discount Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CZSDBRateApplied__c</fullName>
        <description>SDB Rate Applied</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SDB Rate Applied</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CostCenter__c</fullName>
        <description>Cost center for location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Cost center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account address for purposes of statement etc. If Address Prefill Source Id is set, the address details are not persisted directly, only address id is persisted.</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Amount__c</fullName>
        <description>Total certificate amount captured for the certificate application</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>tffa__DepositBoxAccountNumber__c</fullName>
        <description>Box Number of the safe deposit box. Include 3 pieces of information, the branch number, region code and box number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Deposit box account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__DepositBoxExpirationDate__c</fullName>
        <description>Date on which the box lease expires</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Deposit box expiration date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>tffa__DepositBoxExpirationTerm__c</fullName>
        <description>Deposit box Expiration Duration in months</description>
        <label>Deposit Box Expiration Term</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tffa__DepositBoxRentalDiscount__c</fullName>
        <description>Discount applied to the rental fee of safe Deposit box</description>
        <label>Deposit Box Rental Discount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>tffa__DepositBoxStartDate__c</fullName>
        <description>Date on which the box lease starts</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Deposit Box Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>tffa__IsDepositBoxDiscountApplied__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True, if the discount is applied on deposit box fees</description>
        <label>Is deposit box discount applied</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__IsDepositBoxFeeWaived__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True, if the deposit box fees is waived</description>
        <label>Is deposit box fee waived</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <defaultValue>&quot;Init&quot;</defaultValue>
        <description>The stage of the application in context of the product applied. This will be different for each product and is more granular than the status field.This field will be updated on the state transition the application in the origination workflow.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>CostCenter__c</fullName>
        <description>Cost center for location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Cost center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__FirstName__c</fullName>
        <description>The first name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>The last name of the individual represented by the parent object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__MiddleName__c</fullName>
        <description>The middle name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__NationalIdentifierType__c</fullName>
        <description>Classifies identification numbers used by the Internal Revenue Service (IRS) in the administration of tax laws.</description>
        <label>National identifier type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__NationalIdentifierType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__NationalIdentifierValue__c</fullName>
        <description>The value of the taxpayer identifier as assigned by the IRS to the individual or legal entity.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>National identifier value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryPhone__c</fullName>
        <description>Primary phone number of the party</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Primary phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Suffix__c</fullName>
        <description>The name suffix of the individual represented by the parent object. (E.g., JR = Junior, SR = Senior, etc.)</description>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Suffix</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyAddressXref__c.object
<CustomObject>
    <description>Association table between Party and Address . This supports capture of multiple types and also periodAtAddress.
This creates an address book of the party</description>
    <fields>
        <fullName>tffa__Address__c</fullName>
        <description>The address lookup @managed</description>
        <label>Address</label>
        <referenceTo>tffa__Address__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyAddresses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>The party which owns the address.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>AddressXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Address Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartyAddresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/CautionCode.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>001</fullName>
        <label>DECEASED</label>
    </customValue>
    <customValue>
        <fullName>002</fullName>
        <label>FOUNDERS</label>
    </customValue>
    <customValue>
        <fullName>003</fullName>
        <label>PREMIER CHECKING</label>
    </customValue>
    <customValue>
        <fullName>004</fullName>
        <label>PLATINUM PREFERRED</label>
    </customValue>
    <customValue>
        <fullName>005</fullName>
        <label>EMPLOYEE</label>
    </customValue>
    <customValue>
        <fullName>006</fullName>
        <label>REVIEWED BY CDO</label>
    </customValue>
    <customValue>
        <fullName>007</fullName>
        <label>2 SIGNATURES REQUIRED</label>
    </customValue>
    <customValue>
        <fullName>008</fullName>
        <label>GET CUSTOMER ADDRESS</label>
    </customValue>
    <customValue>
        <fullName>009</fullName>
        <label>GET CUSTOMER PHONE</label>
    </customValue>
    <customValue>
        <fullName>010</fullName>
        <label>SUSPECTED ID THEFT</label>
    </customValue>
    <customValue>
        <fullName>011</fullName>
        <label>CONVERSION BOX</label>
    </customValue>
    <customValue>
        <fullName>012</fullName>
        <label>STANDARDIZE FEES 09.01.20</label>
    </customValue>
    <customValue>
        <fullName>013</fullName>
        <label>Private Client</label>
    </customValue>
    <description>Caution Codes</description>
    <masterLabel>CautionCode</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__NationalIdentifierType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>SSN</fullName>
    </customValue>
    <customValue>
        <fullName>TIN</fullName>
    </customValue>
    <description>Classifies identification numbers used by the Internal Revenue Service IRS.</description>
    <masterLabel>NationalIdentifierType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__Suffix.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Jr</fullName>
    </customValue>
    <customValue>
        <fullName>Sr</fullName>
        <label>Sr.</label>
    </customValue>
    <customValue>
        <fullName>II</fullName>
    </customValue>
    <customValue>
        <fullName>III</fullName>
    </customValue>
    <customValue>
        <fullName>IV</fullName>
    </customValue>
    <customValue>
        <fullName>246</fullName>
        <isActive>false</isActive>
        <label>246</label>
    </customValue>
    <customValue>
        <fullName>Esq</fullName>
        <isActive>false</isActive>
        <label>Esq</label>
    </customValue>
    <customValue>
        <fullName>VI</fullName>
        <isActive>false</isActive>
        <label>VI</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <isActive>false</isActive>
        <label>V</label>
    </customValue>
    <customValue>
        <fullName>2nd</fullName>
        <isActive>false</isActive>
        <label>2nd</label>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
        <isActive>false</isActive>
        <label>Test</label>
    </customValue>
    <description>The name suffix of the individual represented by the parent object. (E.g., JR = Junior, SR = Senior, etc.)</description>
    <masterLabel>Suffix</masterLabel>
</GlobalValueSet>

classes/FISCCDOAddSDBOwnerExtension.cls
public with sharing class FISCCDOAddSDBOwnerExtension {
  public static FISCCDepositOriginationRequestBaseDTO invokeDepositeBoxOwner(
    tffa__Party__c partyObj,
    tffa__Application__c appObj,
    FISCC_Adapter_Configs__mdt adapterConfig,
    FISCC_Charter_Config__mdt charterConfig
  ) {
    FISCCDepositOriginationRequestBaseDTO fisccDepositOriginationRequestBaseDTO = null;
    try {
      fisccDepositOriginationRequestBaseDTO = depositBoxOwnerRequest(partyObj, appObj);

      return fisccDepositOriginationRequestBaseDTO;
    } catch (Exception ex) {
      tffa.Logger.error('Exception in invokeDepositeBoxOwner : ' + ex.getMessage() + ex.getLineNumber() + ex.getStackTraceString());
      return fisccDepositOriginationRequestBaseDTO;
    }
  }

  public static FISCCDepositOriginationRequestBaseDTO depositBoxOwnerRequest(tffa__Party__c partyObj, tffa__Application__c appObj) {
    FISCCDepositOriginationRequestBaseDTO fisccDepositOriginationRequestBaseDTO = null;
    CZSDBAddOwnerRequest request = new CZSDBAddOwnerRequest();
    request.SvcID = FISCCIntegrationConstants.SVCID_SDBAddOwner;

    String[] boxDetails = appObj.tffa__DepositBoxAccountNumber__c.split('-');

    request.boxOwnerNew.Brnch = boxDetails[0];
    request.boxOwnerNew.BoxPrfx = boxDetails[1];
    request.boxOwnerNew.BoxNbr = boxDetails[2];
    request.boxOwnerNew.CurTerm = String.valueOf(appObj.tffa__DepositBoxExpirationTerm__c);
    request.boxOwnerNew.RnwTerm = String.valueOf(appObj.tffa__DepositBoxExpirationTerm__c);
    request.boxOwnerNew.RepositionPassInd = '';

    // Set Expiration date
    Datetime expDate = DateTime.newInstance(appObj.tffa__DepositBoxExpirationDate__c, Time.newInstance(0, 0, 0, 0));
    request.boxOwnerNew.ExpDte = expDate.format('MM') + '/' + expDate.format('dd') + '/' + expDate.format('yy');

    // Set Rented date
    Datetime dt = DateTime.newInstance(appObj.tffa__DepositBoxStartDate__c, Time.newInstance(0, 0, 0, 0));
    request.boxOwnerNew.DteRentedMM = dt.format('MM');
    request.boxOwnerNew.DteRentedDD = dt.format('dd');
    request.boxOwnerNew.DteRentedCCYY = dt.format('yyyy');

    request.boxOwnerNew.NmeAddr1 = CZWTFCCommonHelper.getFormattedFullName(
      partyObj.tffa__FirstName__c,
      partyObj.tffa__MiddleName__c,
      partyObj.tffa__LastName__c,
      partyObj.tffa__Suffix__c,
      FISCCIntegrationConstants.FULL_NAME_LENGTH
    );

    request.boxOwnerNew.ShrtNme = CZWTFCCommonHelper.getFormattedFullName(
      partyObj.tffa__FirstName__c,
      partyObj.tffa__MiddleName__c,
      partyObj.tffa__LastName__c,
      partyObj.tffa__Suffix__c,
      FISCCIntegrationConstants.CUST_NAME_LENGTH_1
    );

    tffa__Address__c addressObj = partyObj.tffa__AddressXrefs__r[0].tffa__Address__r;

    // Set Address
    if (addressObj != null) {
      request.boxOwnerNew.NmeAddr2 = addressObj.tffa__Line1__c;

      if (addressObj.tffa__Line2__c != null) {
        request.boxOwnerNew.NmeAddr3 = addressObj.tffa__Line2__c;
        request.boxOwnerNew.NmeAddr4 = addressObj.tffa__City__c + ' ' + addressObj.tffa__State__c + ' ' + addressObj.tffa__ZipCode__c;
      } else {
        request.boxOwnerNew.NmeAddr3 = addressObj.tffa__City__c + ' ' + addressObj.tffa__State__c + ' ' + addressObj.tffa__ZipCode__c;
      }
    }

    // Set Phone number
    if (partyObj.tffa__PrimaryPhone__c != null) {
      String phoneNumber = getPhoneNumber(partyObj.tffa__PrimaryPhone__c);
      request.boxOwnerNew.HmPh1 = phoneNumber.substring(0, 3);
      request.boxOwnerNew.HmPh2 = phoneNumber.substring(3, 6);
      request.boxOwnerNew.HmPh3 = phoneNumber.substring(6);
    }

    // Set Tax Id and type
    request.boxOwnerNew.TaxNbr = partyObj.tffa__NationalIdentifierValue__c;
    request.boxOwnerNew.TaxId = CZWTFCCommonHelper.getTaxIdType(partyObj.tffa__NationalIdentifierType__c);

    request.boxOwnerNew.PrmyOffcr = appObj.CZPrimaryOfficer__c;
    request.boxOwnerNew.CstCntr = appObj.CostCenter__c;

    // Set Discount Reason text
    getReasonText(request, appObj);

    // Set Billing Details
    setBillingDetails(request, appObj);

    // Set Current Rate Code
    setRateCode(request, appObj);

    //set Caution codes
    getCautionCodes(request, appObj);

    fisccDepositOriginationRequestBaseDTO = request;

    tffa.Logger.debug('FISCCDOAddSDBOwnerExtension::fisccDepositOriginationRequestBaseDTO: ' + fisccDepositOriginationRequestBaseDTO);

    return fisccDepositOriginationRequestBaseDTO;
  }

  public static CZSDBAddOwnerRequest getCautionCodes(CZSDBAddOwnerRequest request, tffa__Application__c appObj) {
    if (String.isNotBlank(appObj.CZCautionCode1__c)) {
      request.boxOwnerNew.CautionCde1 = String.valueOf(appObj.CZCautionCode1__c);
    }

    if (String.isNotBlank(appObj.CZCautionCode2__c)) {
      request.boxOwnerNew.CautionCde2 = String.valueOf(appObj.CZCautionCode2__c);
    }

    // if (String.isNotBlank(appObj.CZCautionCode3__c)) {
    //   request.boxOwnerNew.CautionCde3 = String.valueOf(appObj.CZCautionCode3__c);
    // }

    return request;
  }

  public static CZSDBAddOwnerRequest getReasonText(CZSDBAddOwnerRequest request, tffa__Application__c appObj) {
    if (String.isNotBlank(appObj.CZSDBDiscountReasonTxt__c)) {
      if (appObj.CZSDBDiscountReasonTxt__c.length() <= 30) {
        request.boxOwnerNew.OwnComment1 = appObj.CZSDBDiscountReasonTxt__c;
      } else if (appObj.CZSDBDiscountReasonTxt__c.length() > 30 && appObj.CZSDBDiscountReasonTxt__c.length() <= 60) {
        request.boxOwnerNew.OwnComment1 = appObj.CZSDBDiscountReasonTxt__c.substring(0, 29);
        request.boxOwnerNew.OwnComment2 = appObj.CZSDBDiscountReasonTxt__c.substring(30, appObj.CZSDBDiscountReasonTxt__c.length() - 1);
      } else if (appObj.CZSDBDiscountReasonTxt__c.length() > 60) {
        request.boxOwnerNew.OwnComment1 = appObj.CZSDBDiscountReasonTxt__c.substring(0, 29);
        request.boxOwnerNew.OwnComment2 = appObj.CZSDBDiscountReasonTxt__c.substring(30, 59);
      }
    }

    return request;
  }

  public static void setRateCode(CZSDBAddOwnerRequest request, tffa__Application__c appObj) {
    request.boxOwnerNew.CurRteCde = appObj.tffa__IsDepositBoxDiscountApplied__c ? 'O' : appObj.CZSDBRateApplied__c == 'S' ? 'S' : '1';
    request.boxOwnerNew.CurDiscPremInd = appObj.tffa__IsDepositBoxDiscountApplied__c ? 'D' : 'N';
    request.boxOwnerNew.StdRte = String.valueOf(appObj.tffa__Amount__c);
    request.boxOwnerNew.AmtDue = String.valueOf(appObj.tffa__Amount__c);

    if (appObj.tffa__IsDepositBoxDiscountApplied__c && appObj.CZIsDiscountForFirstYearOnly__c) {
      request.boxOwnerNew.RnwRteCde = appObj.CZSDBRateApplied__c == 'S' ? 'S' : '1';
      /* TODO : set rate without discount*/
      request.boxOwnerNew.RnwRte = String.valueOf(appObj.tffa__DepositBoxRentalDiscount__c + appObj.tffa__Amount__c);
      request.boxOwnerNew.RnwDiscPremInd = 'N';
    } else {
      request.boxOwnerNew.RnwRteCde = request.boxOwnerNew.CurRteCde;
      request.boxOwnerNew.RnwRte = request.boxOwnerNew.StdRte;
      request.boxOwnerNew.RnwDiscPremInd = request.boxOwnerNew.CurDiscPremInd;
    }
    if (request.boxOwnerNew.CurBillCde == 'W' || request.boxOwnerNew.CurBillCde == 'B') {
      request.boxOwnerNew.CurRteCde = 'S';
      request.boxOwnerNew.CurDiscPremInd = 'N';
    }
    if (request.boxOwnerNew.RnwBillCde == 'W' || request.boxOwnerNew.RnwBillCde == 'B') {
      request.boxOwnerNew.RnwRteCde = 'S';
      request.boxOwnerNew.RnwDiscPremInd = 'N';
    }
  }

  public static CZSDBAddOwnerRequest setBillingDetails(CZSDBAddOwnerRequest request, tffa__Application__c appObj) {
    if (appObj.tffa__IsDepositBoxFeeWaived__c) {
      request.boxOwnerNew.CurBillCde = 'W';
      return request;
    }

    if (appObj.CZBillingMode__c != null && FISCCIntegrationConstants.SDB_BILLING_CODE_MAP.containsKey(appObj.CZBillingMode__c)) {
      request.boxOwnerNew.CurBillCde = FISCCIntegrationConstants.SDB_BILLING_CODE_MAP.get(appObj.CZBillingMode__c);
    }
    if (
      appObj.CZRenewalBillingMode__c != null && FISCCIntegrationConstants.SDB_BILLING_CODE_MAP.containsKey(appObj.CZRenewalBillingMode__c)
    ) {
      request.boxOwnerNew.RnwBillCde = FISCCIntegrationConstants.SDB_BILLING_CODE_MAP.get(appObj.CZRenewalBillingMode__c);
    }
    if (request.boxOwnerNew.CurBillCde == 'A' && FISCCIntegrationLogService.SDB_Funding_Details_MAP.containsKey(appObj.Id + '_DEPOSIT')) {
      request.boxOwnerNew.BillableAcct = FISCCIntegrationLogService.SDB_Funding_Details_MAP.get(appObj.Id + '_DEPOSIT')
        .tffa__AccountNumber__c;
    } else if (
      request.boxOwnerNew.RnwBillCde == 'A' && FISCCIntegrationLogService.SDB_Funding_Details_MAP.containsKey(appObj.Id + '_RENEWAL')
    ) {
      request.boxOwnerNew.BillableAcct = FISCCIntegrationLogService.SDB_Funding_Details_MAP.get(appObj.Id + '_RENEWAL')
        .tffa__AccountNumber__c;
    }
    return request;
  }

  public static String getPhoneNumber(String phonenumber) {
    phonenumber = phonenumber.reverse();
    phonenumber = phonenumber.substring(0, 10);
    phonenumber = phonenumber.reverse();

    return phonenumber;
  }
}