objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>CZAccountOpeningDate__c</fullName>
        <description>Account Opening Date</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Opening Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DPTDId__c</fullName>
        <description>Deposit Number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Deposit Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDMUploadRetryCount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>MDM Upload Retry Count</description>
        <label>MDM Upload Retry Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MDMUploadStatus__c</fullName>
        <description>Status of MDM Upload</description>
        <label>MDM Upload Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SUCCESS</fullName>
                </value>
                <value>
                    <fullName>FAILURE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product code identifier.</description>
        <label>Financial Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR (4 AND 5))</booleanFilter>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>$Source.tffa__ProductCategory__c</field>
                <operation>equals</operation>
                <valueField>tffa__Product__c.tffa__Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value>In Progress</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ApplicationPartyXref__c.object
<CustomObject>
    <description>Each Applicant of the submission can play different roles in the application and the eventual account.</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Beneficiary__c.object
<CustomObject>
    <description>A beneficiary typically refers to someone who is eligible to receive distributions from deposits upon death of primary owner of account. Beneficiary capture typically happens for Certificate Deposits.
Designating a beneficiary not only ensures the CD will not have to go through probate when the applicant dies.</description>
    <fields>
        <fullName>CZMDMPartyID__c</fullName>
        <description>MDM Global Id</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MDM Global ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CZParty__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Party</relationshipLabel>
        <relationshipName>Party</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to parent application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Beneficiaries</relationshipLabel>
        <relationshipName>Beneficiaries</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Beneficiary</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Beneficiary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Beneficiaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>CZMDMPartyID__c</fullName>
        <description>MDM Global Id</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MDM Global ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MDMUploadRetryCount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>MDM Upload Retry Count</description>
        <label>MDM Upload Retry Count</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MDMUploadStatus__c</fullName>
        <description>Status of MDM Upload</description>
        <label>MDM Upload Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>SUCCESS</fullName>
                </value>
                <value>
                    <fullName>FAILURE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyPartyXref__c.object
<CustomObject>
    <description>A relationship between 2 applicants of a submission. 
Personal relationship could be SPOUSE, PARENT, FRIENDS.
Business relationship between a company and an individual could be DIRECTOR, OWNER, EXECUTIVE, PARTNER etc. In additional the ownership percentage can be captured for OWNER type of relationship. 
Relationship between 2 company type applicants can also be captured such as PARENT and SUBSIDIARY.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Party managing the relationship</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Related To</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Party Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Party Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__BrandEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The current brand of the submission</description>
        <label>Brand</label>
        <referenceTo>tffa__Brand__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Bundle__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Bundle code identifier</description>
        <label>Bundle</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Product Bundle not valid.</errorMessage>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Type__c</field>
                <operation>equals</operation>
                <value>Bundle</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__SubmissionPartyXref__c.object
<CustomObject>
    <description>An individual or a legal entity which is applying for certain services/products in the bank. An applicant exists only in the context of a submission.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to Party object @managed</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission object.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submission Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CZMDMDataUploadBatch.cls
global inherited sharing class CZMDMDataUploadBatch extends tffa.AbstractBatchJob implements Database.Batchable<sObject>, Database.AllowsCallouts {
  public static Set<String> subIdSet = new Set<String>();

  global Database.QueryLocator start(Database.BatchableContext batchableContext) {
    return Database.getQueryLocator(getQuery());
  }

  global void execute(Database.BatchableContext batchableContext, List<tffa__Submission__c> submissionList) {
    tffa.Interaction.begin(CZMDMDataUploadBatch.class, 'execute');
    try {
      tffa__Submission__c submission = submissionList[0];

      FISCCIntegrationLogService.setSubmissionObj(String.valueOf(submission.Id));
      FISCCIntegrationLogService.setPartyObjs();
      FISCCIntegrationLogService.setApplicationObjs();
      FISCCIntegrationLogService.setIntegrationLog(
        String.valueOf(submission.Id),
        new List<String>{
          FISCCIntegrationConstants.CREATE_CUSTOMER_MDM,
          FISCCIntegrationConstants.CREATE_ACCOUNT_MDM,
          FISCCIntegrationConstants.UPDATE_CUSTOMER_MDM
        }
      );
      FISCCIntegrationLogService.isBatchSource = true;

      CZMDMDataUploadExecutor.processRequest(submission);
    } catch (Exception ex) {
      tffa.Logger.error('CZMDMDataUploadBatch Exception msg : ' + ex.getMessage() + ' ' + ex.getStackTraceString());
    } finally {
      try {
        List<tffa__Party__c> parties = new List<tffa__Party__c>();
        if (FISCCIntegrationLogService.partyObjs != null && FISCCIntegrationLogService.partyObjs.size() != 0) {
          for (tffa__Party__c partyObj : FISCCIntegrationLogService.partyObjs) {
            tffa__Party__c party = new tffa__Party__c();
            party.Id = partyObj.Id;
            party.MDMUploadRetryCount__c = partyObj.MDMUploadRetryCount__c;
            party.MDMUploadStatus__c = partyObj.MDMUploadStatus__c;
            party.CZMDMPartyID__c = partyObj.CZMDMPartyID__c;
            parties.add(party);
          }
          if (parties != null && !parties.isEmpty()) {
            FISCCObjectManagerRepository.doUpsertParties(parties);
          }
        }
        List<tffa__Application__c> applications = new List<tffa__Application__c>();
        if (FISCCIntegrationLogService.applicationObjs != null && !FISCCIntegrationLogService.applicationObjs.isEmpty()) {
          for (tffa__Application__c appObj : FISCCIntegrationLogService.applicationObjs) {
            tffa__Application__c app = new tffa__Application__c();
            app.Id = appObj.Id;
            app.MDMUploadRetryCount__c = appObj.MDMUploadRetryCount__c;
            app.MDMUploadStatus__c = appObj.MDMUploadStatus__c;
            applications.add(app);
          }
          if (applications != null && !applications.isEmpty()) {
            FISCCObjectManagerRepository.doUpsertApplications(applications);
          }
        }
        FISCCIntegrationLogService.persistIntegationLogs();
      } finally {
        tffa.Interaction.close();
      }
    }
  }

  global void finish(Database.BatchableContext batchableContext) {
    tffa.Logger.debug('CZMDMDataUploadBatch finish()');
    tffa.Logger.flush();
  }

  private static String getQuery() {
    List<tffa__Application__c> applicationList = CZWTFCApplicationRepository.findApplicationByMDMStatus();

    // Avoid the application if its a certificate product and DPTDId is missing.
    // Avoid the application if account is not yet opened.
    for (tffa__Application__c app : applicationList) {
      if ((CZWTFCCommonHelper.isCertificateProduct(app) && String.isBlank(app.DPTDId__c)) || app.CZAccountOpeningDate__c == null) {
        continue;
      }
      subIdSet.add(app.tffa__Submission__c);
    }

    // Fetch failed customer creation party
    List<tffa__Party__c> partyList = CZWTFCPartyRepository.fetchPartyByMDMUploadStatus('FAILURE');

    // Iterate through each party and get the submission Id
    for (tffa__Party__c party : partyList) {
      for (tffa__SubmissionPartyXref__c subParty : party.tffa__Submissions__r) {
        subIdSet.add(subParty.tffa__Submission__c);
      }
    }

    // Get the funding request with pending status
    String query = new tffa.QueryBuilder(tffa__Submission__c.SObjectType)
      .selectFields()
      .selectObject('tffa__BrandEntity__r')
      .selectFields()
      .build()
      .selectChildObject('tffa__Applications__r')
      .selectFields()
      .selectObject('tffa__Product__r')
      .selectFields()
      .build()
      .build()
      .selectChildObject('tffa__PartyXrefs__r')
      .selectFields()
      .selectObject('tffa__Party__r')
      .selectFields()
      .build()
      .build()
      .whereClause('Id', ' IN :subIdSet')
      .build()
      .toQuery();

    tffa.Logger.debug('CZMDMDataUploadBatch query => ' + query);

    return query;
  }
}