objects/tffa__Disclosure__c.object
<CustomObject>
    <description>Supports the capture of a list of disclosures which the applicant has to accept or execute before opening the account. List of disclosures is fetched from disclosure checklist maintained for a product and type of applicant.</description>
    <fields>
        <fullName>CZDisclosureParticipantCount__c</fullName>
        <description>Disclosure Participant Count</description>
        <label>Disclosure Participant Count</label>
        <summaryForeignKey>tffa__DisclosureParticipant__c.tffa__Disclosure__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>tffa__EnvelopeId__c</fullName>
        <description>Unique identifier for the docusign document envelope.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Envelope Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__ExecutionRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether digital signature is required</description>
        <label>Execution required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__ExternalId__c</fullName>
        <description>External id as referred by external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates the current status of disclosure resolved for the applicant.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DisclosureStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference to parent submission.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Disclosures</relationshipLabel>
        <relationshipName>Disclosures</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Disclosure</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Disclosure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disclosures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__DisclosureEnvelope__c.object
<CustomObject>
    <description>An envelope is a container for documents that you send to a recipient to sign. An envelope can have one document or many documents. The envelope holds data on the documents to be signed, the signers and other recipients, and the places where signers will sign the
        documents</description>
    <label>Disclosure Envelope</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Disclosure Envelope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disclosure Envelopes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__ExternalId__c</fullName>
        <description>External id as referred by external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the submission</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__DisclosureStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <customValue>
        <fullName>DECLINED</fullName>
        <label>Declined</label>
    </customValue>
    <customValue>
        <fullName>GENERATION_IN_PROGRESS</fullName>
        <label>Generation In Progress</label>
    </customValue>
    <description>Indicates current status of the disclosure. This will be computed and be useful for regulations.</description>
    <masterLabel>DisclosureStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>ABANDONED</fullName>
        <label>Abandoned</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>SAVED</fullName>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>SUBMITTED</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>Indicates current status of the submission.This will be computed and be useful for regulations.</description>
    <masterLabel>SubmissionStatus</masterLabel>
</GlobalValueSet>

classes/CZDousignReminderBatch.cls
global with sharing class CZDousignReminderBatch extends tffa.AbstractBatchJob implements Database.Batchable<sObject>, Database.AllowsCallouts {
  global List<tffa__DisclosureEnvelope__c> start(Database.BatchableContext bc) {
    List<tffa__DisclosureEnvelope__c> discEnvs = CZWTFCHelperRepository.findGeneratedDisclosureEnvs();
    //
    return discEnvs;
  }

  global void execute(Database.BatchableContext batchableContext, List<SObject> subObject) {
    tffa.Logger.debug('In CZDousignReminderBatch.execute');
    List<tffa__DisclosureEnvelope__c> envList = (List<tffa__DisclosureEnvelope__c>) subObject;
    tffa.Interaction.begin(CZDousignReminderBatch.class, 'execute');
    try {
      List<Id> envIdList = new List<Id>();
      for (tffa__DisclosureEnvelope__c env : envList) {
        envIdList.add(env.Id);
      }
      List<tffa__Disclosure__c> diclosuresLst = CZWTFCHelperRepository.findDiscsByEnvId(envIdList);
      for (tffa__Disclosure__c disc : diclosuresLst) {
        if (disc.CZDisclosureParticipantCount__c < 1 || !disc.tffa__ExecutionRequired__c) {
          disc.tffa__Status__c = 'COMPLETED';
        }
      }
      for (tffa__DisclosureEnvelope__c discEnv : envList) {
        boolean isPendingDisc = false;
        for (tffa__Disclosure__c disc : diclosuresLst) {
          if (disc.tffa__Status__c != 'COMPLETED') {
            isPendingDisc = true;
          }
        }
        if (isPendingDisc) {
          CZWTFCSignersStatusDTO signerStatusDTO;
          if (!Test.isRunningTest()) {
            signerStatusDTO = CZWTFCDocusignService.getSignersStatus(discEnv.tffa__Submission__c, discEnv.tffa__ExternalId__c);
          } else {
            CZWTFCSignersStatusDTO.SignersDTO signerStatus = new CZWTFCSignersStatusDTO.SignersDTO();
            signerStatusDTO = new CZWTFCSignersStatusDTO();
            signerStatusDTO.signers.add(signerStatus);
          }

          if (!isSigningCompleted(signerStatusDTO)) {
            Boolean isPending = CZDocusignReminderHelper.sendReminderMail(signerStatusDTO, discEnv);
            if (!isPending) {
              discEnv.tffa__Status__c = 'COMPLETED';
            }
          } else {
            for (tffa__Disclosure__c disc : diclosuresLst) {
              if (discEnv.tffa__ExternalId__c == disc.tffa__EnvelopeId__c) {
                disc.tffa__Status__c = 'COMPLETED';
              }
            }
            discEnv.tffa__Status__c = 'COMPLETED';
          }
        } else {
          discEnv.tffa__Status__c = 'COMPLETED';
        }
      }
      WTFCObjectManagerRepository.doUpsertObjects(envList);
      WTFCObjectManagerRepository.doUpsertObjects(diclosuresLst);
    } catch (Exception ex) {
      tffa.Logger.error('Exception in CZDousignReminderBatch ' + ex.getStackTraceString() + ' ' + ex.getLineNumber());
    } finally {
      tffa.Interaction.close();
    }
  }

  global void finish(Database.BatchableContext batchableContext) {
    tffa.Logger.debug('CZDousignReminderBatch finish()');
    tffa.Logger.flush();
  }

  public static boolean isSigningCompleted(CZWTFCSignersStatusDTO signerStatusDTO) {
    boolean isCompleted = true;
    for (CZWTFCSignersStatusDTO.SignersDTO signer : signerStatusDTO.signers) {
      if ((signer.status != null && !signer.status.equalsIgnoreCase('Completed'))) {
        isCompleted = false;
      }
    }
    return isCompleted;
  }
}