objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ProductMatrix__c.object
<CustomObject>
    <description>Represents business rules for filtering products available for applying. Criteria for filtering may be based on the originating channel, branch and even user (by skills).</description>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The outcome of the rule, an allowed product.</description>
        <label>Product (outcome)</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Matrices</relationshipLabel>
        <relationshipName>Matrices</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Product Matrix</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Matrices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CZWTFCProductController.cls
global with sharing class CZWTFCProductController extends tffa.AbstractController implements tffa.IController {
  private static tffa.IController controller;

  global CZWTFCProductController(tffa.IController p) {
    controller = p;
  }

  @RemoteAction
  /**
   * @Description Returns Brand Object
   * @return Response
   */
  global static tffa.Response getProductList(tffa.Context ctx, Map<String, Object> params) {
    tffa.Interaction.begin(ctx, CZWTFCProductController.class, 'getProductList');
    try {
      if (!Test.isRunningTest()) {
        validateSession();
        validateRecordAccess(params);
      }

      List<tffa__ProductMatrix__c> prodMatrixList = new List<tffa__ProductMatrix__c>();
      List<tffa__Product__c> productList = new List<tffa__Product__c>();
      if (params.containsKey('brandCode')) {
        prodMatrixList = CZWTFCProductService.readProductMatrix(params);
        if (prodMatrixList == null || prodMatrixList.isEmpty()) {
          throw new IllegalArgumentException('THE ACCOUNT YOU ARE ATTEMPTING TO APPLY FOR IS NOT AVAILABLE IN YOUR AREA.');
        } else {
          productList = CZWTFCProductService.readProducts(prodMatrixList, params);
        }
        return tffa.Response.ok(productList).build();
      } else {
        throw new IllegalArgumentException('Invalid Request Parameters');
      }
    } catch (Exception ex) {
      tffa.Logger.error('Exception in CZWTFCProductController' + ex.getMessage() + ex.getStackTraceString());
      return tffa.Response.fail(ex).build();
    } finally {
      tffa.Interaction.close();
    }
  }
}