objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>tffa__IsExistingCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current applicant is existing customer of the bank.</description>
        <label>IsExistingCustomer</label>
        <type>Checkbox</type>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>CZIsDebitCardProductSelected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is DebitCard Product Selected</description>
        <label>IsDebitCardProductSelected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__SubmittedChannel__c</fullName>
        <description>Type of the channel from which the application has been originated. 

Supported values are - 

BRANCH
DIGITAL
CALLCENTER</description>
        <label>Submitted Channel</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionChannelType</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__SubmissionPartyXref__c.object
<CustomObject>
    <description>An individual or a legal entity which is applying for certain services/products in the bank. An applicant exists only in the context of a submission.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to Party object @managed</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission object.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submission Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/tffa__SubmissionChannelType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>BRANCH</fullName>
        <label>Branch</label>
    </customValue>
    <customValue>
        <fullName>DIGITAL</fullName>
        <label>Digital</label>
    </customValue>
    <customValue>
        <fullName>CALL_CENTER</fullName>
        <label>Call Center</label>
    </customValue>
    <customValue>
        <fullName>AGENT</fullName>
        <label>Agent</label>
    </customValue>
    <description>Type of the channel from which the submission has been originated</description>
    <masterLabel>SubmissionChannelType</masterLabel>
</GlobalValueSet>

classes/CZUpdatePartyInfoBatch.cls
global with sharing class CZUpdatePartyInfoBatch extends tffa.AbstractBatchJob implements Database.Batchable<sObject>, Database.AllowsCallouts {
  global List<tffa__Party__c> start(Database.BatchableContext bc) {
    List<tffa__Party__c> parties = CZWTFCPartyRepository.fetchPartyForUpdate();
    return parties;
  }

  global void execute(Database.BatchableContext batchableContext, List<SObject> subObjectList) {
    tffa.Interaction.begin(CZUpdatePartyInfoBatch.class, 'execute');
    List<tffa__Party__c> parties = (List<tffa__Party__c>) subObjectList;
    try {
      for (tffa__Party__c partyObj : parties) {
        tffa.Logger.debug('partyObj in  update party batch ' + partyObj.Id);
        tffa__SubmissionPartyXref__c subPartyObj = CZWTFCPartyRepository.findSubPartyById(partyObj.Id);
        FISCCIntegrationLogService.setSubmissionObj(String.valueOf(subPartyObj.tffa__Submission__c));
        if (
          FISCCIntegrationLogService.submissionObj.tffa__SubmittedChannel__c == CZWTFCConstants.BRANCH &&
          !FISCCIntegrationLogService.submissionObj.CZIsDebitCardProductSelected__c
        ) {
          FISCCIntegrationLogService.setIntegrationLog(subPartyObj.tffa__Submission__c, FISCCIntegrationConstants.CUSTOMER_INFORMATION);
          FISCCIntegrationLogService.setCurrentLog(FISCCIntegrationConstants.CUSTOMER_INFORMATION);
          boolean aliasUpdateSuccess = FISCCUpdateCustomerInfoExtension.updatePartyInfo(partyObj);
          if (partyObj.tffa__IsExistingCustomer__c && !partyObj.CZCustomerUpdated__c) {
            FISCCUpdateCustInfoProvider.isBatchSource = true;
            FISCCUpdateCustInfoProvider.updateBranchCustomerInformation(new List<tffa__Party__c>{ partyObj });
          }

          if (aliasUpdateSuccess && (partyObj.CZCustomerUpdated__c || partyObj.tffa__IsExistingCustomer__c)) {
            partyObj.CZBatchUpdateStatus__c = FISCCIntegrationConstants.PARTY_UPDATE_COMPLETED;
          }
          partyObj.CZBatchUpdateRetryCount__c++;
        } else {
          partyObj.CZBatchUpdateStatus__c = FISCCIntegrationConstants.PARTY_UPDATE_COMPLETED;
        }
      }
      parties = getupdatedPartyList(parties);
      WTFCObjectManagerRepository.doUpsertObjects(parties);
    } catch (Exception ex) {
      tffa.Logger.error('Exception in CZUpdatePartyInfoBatch.execute ' + ex.getStackTraceString());
    } finally {
      FISCCIntegrationLogService.persistIntegationLogs();
      tffa.Interaction.close();
      tffa.Logger.flush();
    }
  }

  global void finish(Database.BatchableContext batchableContext) {
    tffa.Logger.debug('In CZUpdatePartyInfoBatch.finish');
    tffa.Logger.flush();
  }

  public static List<tffa__Party__c> getupdatedPartyList(List<tffa__Party__c> parties) {
    List<tffa__Party__c> updatedParties = new List<tffa__Party__c>();
    for (tffa__Party__c party : parties) {
      tffa__Party__c p = new tffa__Party__c();
      p.Id = party.Id;
      p.CZCustomerUpdated__c = party.CZCustomerUpdated__c;
      p.CZBatchUpdateStatus__c = party.CZBatchUpdateStatus__c;
      p.CZBatchUpdateRetryCount__c = party.CZBatchUpdateRetryCount__c;
      updatedParties.add(p);
    }
    return updatedParties;
  }
}