objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FISCCCustomerIndDemoExtension.cls
public with sharing class FISCCCustomerIndDemoExtension {
  public static FISCCDepositOriginationRequestBaseDTO generateCustomerIndDemoRequest(tffa__Party__c partyObj) {
    FISCCDepositOriginationRequestBaseDTO fisccDepositOriginationRequestBaseDTO;
    try {
      FISCCDOIndividualDemoRequest individualDemo = new FISCCDOIndividualDemoRequest();
      individualDemo.SvcID = FISCCIntegrationConstants.INDIVIDUAL_DEMOGRAPHICS;
      individualDemo.individualDemographics.CIApplNbr = partyObj.Customer_Number__c;
      individualDemo.individualDemographics.NNAPhnNum = partyObj.CZInternationalPhoneNumber__c;

      fisccDepositOriginationRequestBaseDTO = individualDemo;
      tffa.Logger.debug('FISCCCustomerIndDemoExtension req ==> ' + fisccDepositOriginationRequestBaseDTO);
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in generateCustomerIndDemoRequest ' + ex.getLineNumber() + ' ' + ex.getMessage());
    }
    return fisccDepositOriginationRequestBaseDTO;
  }
}