objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>tffa__BirthDate__c</fullName>
        <description>The date of birth of the individual</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Birth date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>tffa__Citizenship__c</fullName>
        <description>The citizenship of the individual.</description>
        <label>Citizenship</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Citizenship</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__DoNotCall__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that the applicant does not want to receive calls.</description>
        <label>Do not call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__DoNotEmail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that the applicant does not want to receive emails.</description>
        <label>Do not email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__DoNotText__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates that the applicant does not want to receive sms text messages.</description>
        <label>Do not text</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__FicoScore__c</fullName>
        <description>The fico score of the individual</description>
        <label>Fico score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tffa__FirstName__c</fullName>
        <description>The first name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__IsEmployee__c</fullName>
        <defaultValue>false</defaultValue>
        <description>true, if the individual is an employee of the bank</description>
        <label>Is employee</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__IsExistingCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current applicant is existing customer of the bank.</description>
        <label>IsExistingCustomer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>The last name of the individual represented by the parent object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__MaritalStatus__c</fullName>
        <description>Indicates marital status of the applicant.</description>
        <label>Marital status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__MaritalStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__MiddleName__c</fullName>
        <description>The middle name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__NationalIdentifierType__c</fullName>
        <description>Classifies identification numbers used by the Internal Revenue Service (IRS) in the administration of tax laws.</description>
        <label>National identifier type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__NationalIdentifierType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__NationalIdentifierValue__c</fullName>
        <description>The value of the taxpayer identifier as assigned by the IRS to the individual or legal entity.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>National identifier value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__NickName__c</fullName>
        <description>A familiar name given to a individial instead of or as well as the legal name. Can be used in communication mechanisms.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Nick name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PoliticallyExposedPerson__c</fullName>
        <defaultValue>false</defaultValue>
        <description>true, if the individual has been entrusted with a prominent public function. A PEP generally presents a higher risk for potential involvement in bribery and corruption by virtue of their position and the influence that they may hold</description>
        <label>Politically Exposed Person</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__PreferredContactMethod__c</fullName>
        <description>Indicates preferred contact method to contact the applicant.</description>
        <label>Preferred contact method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ContactMethodType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__PreferredLanguage__c</fullName>
        <description>The preferred Language for the applicant</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Preferred language</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PreferredTimeToCall__c</fullName>
        <description>Preferred time to call to the applicant if the application has been scheduled.</description>
        <label>Preferred time to call</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ContactTimeSlot</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Prefilled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>true, if the data was prefilled using either scanning of photo ID or existing customer login.</description>
        <label>Prefilled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Prefix__c</fullName>
        <description>Title preceding the name of an individual (Judge, Mr. Mrs. Colonel).</description>
        <label>Prefix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Prefix</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__PrimaryEmailType__c</fullName>
        <description>The type of the primary  email , valid values can be HOME,WORK,BUSINESS</description>
        <label>Primary email type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__EmailType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__PrimaryEmail__c</fullName>
        <description>Primary email of the party.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryPhoneType__c</fullName>
        <description>The type of the primary phone</description>
        <label>Primary phone type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PhoneType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__PrimaryPhone__c</fullName>
        <description>Primary phone number of the party</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Primary phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__SecondaryEmailType__c</fullName>
        <description>The type of the secondary email</description>
        <label>Secondary email type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__EmailType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__SecondaryEmail__c</fullName>
        <description>Secondary email of the party.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Secondary email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__SecondaryPhoneType__c</fullName>
        <description>The type of the Secondary phone</description>
        <label>Secondary phone type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PhoneType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__SecondaryPhone__c</fullName>
        <description>Secondary phone of the party.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Secondary phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__SpousalVABenefitsEligibilityIndicator__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When true, indicates that the individual is a surviving spouse of a Veteran who served and was Missing In Action (MIA) /Killed In Action (KIA), a Veteran who died of a condition or impairment connected to his/her service in the Armed Forces (as determined by VA or DoD), or a Veteran whose service connected disability/impairment, they believe, entitles them to benefits from the VA.</description>
        <label>Spousal vabenefits eligibility indicator</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__Citizenship.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Citizen</fullName>
        <label>US Citizen</label>
    </customValue>
    <customValue>
        <fullName>Resident</fullName>
        <label>Permanent Resident Alien</label>
    </customValue>
    <customValue>
        <fullName>NonResident</fullName>
        <label>Non-Permanent Resident Alien</label>
    </customValue>
    <customValue>
        <fullName>International_I20</fullName>
        <label>I20 (International Student)</label>
    </customValue>
    <description>The citizenship of the individual. Valid values are Citizen,Resident,NonResident</description>
    <masterLabel>Citizenship</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__ContactMethodType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Phone</fullName>
    </customValue>
    <description>Indicates preferred contact method to contact the applicant.</description>
    <masterLabel>ContactMethodType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__ContactTimeSlot.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Morning</fullName>
    </customValue>
    <description>Preferred time to call to the applicant if the application has been scheduled.</description>
    <masterLabel>ContactTimeSlot</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__EmailType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PRIMARY</fullName>
        <label>Primary</label>
    </customValue>
    <customValue>
        <fullName>BUSINESS</fullName>
        <label>Business</label>
    </customValue>
    <customValue>
        <fullName>SECONDARY</fullName>
        <label>Secondary</label>
    </customValue>
    <description>The type of the primary email , valid values can be HOME,WORK,BUSINESS</description>
    <masterLabel>EmailType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__MaritalStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Married</fullName>
    </customValue>
    <customValue>
        <fullName>Unmarried</fullName>
    </customValue>
    <customValue>
        <fullName>Separated</fullName>
    </customValue>
    <customValue>
        <fullName>Divorced</fullName>
    </customValue>
    <customValue>
        <fullName>Widowed</fullName>
    </customValue>
    <customValue>
        <fullName>Undisclosed</fullName>
        <isActive>false</isActive>
        <label>Undisclosed</label>
    </customValue>
    <description>Describes values for marital status accepted by the system</description>
    <masterLabel>MaritalStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__NationalIdentifierType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>SSN</fullName>
    </customValue>
    <customValue>
        <fullName>TIN</fullName>
    </customValue>
    <description>Classifies identification numbers used by the Internal Revenue Service IRS.</description>
    <masterLabel>NationalIdentifierType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PhoneType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HOME</fullName>
        <label>Home</label>
    </customValue>
    <customValue>
        <fullName>WORK</fullName>
        <label>Work</label>
    </customValue>
    <customValue>
        <fullName>CELL</fullName>
        <label>Cell</label>
    </customValue>
    <customValue>
        <fullName>MOBILE</fullName>
        <label>Mobile</label>
    </customValue>
    <customValue>
        <fullName>BUSINESS</fullName>
        <label>Business</label>
    </customValue>
    <description>The type of the primary phone , valid values can be HOME,WORK,BUSINESS</description>
    <masterLabel>PhoneType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__Prefix.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Mr</fullName>
    </customValue>
    <customValue>
        <fullName>Mrs</fullName>
    </customValue>
    <customValue>
        <fullName>Ms</fullName>
    </customValue>
    <description>Title preceding the name of an individual (Judge, Mr. Mrs. Colonel).</description>
    <masterLabel>Prefix</masterLabel>
</GlobalValueSet>

classes/FISCCTestDataRepository.cls
/**
 * @description Repository/Utility class to create test data
 */
public with sharing class FISCCTestDataRepository {
  /**
   * Creates a submission (persisted)
   */

  public static tffa__Party__c createIndividualPartyWithChildObjects() {
    tffa__Party__c party = createIndividualParty();

    return party;
  }
  public static tffa__Party__c createIndividualParty() {
    tffa__Party__c party = new tffa__Party__c();
    party.tffa__IsExistingCustomer__c = false;
    party.tffa__BirthDate__c = Date.valueOf('1981-02-02');
    party.tffa__Citizenship__c = 'Citizen';
    party.tffa__DoNotCall__c = false;
    party.tffa__DoNotEmail__c = false;
    party.tffa__DoNotText__c = false;
    party.tffa__FirstName__c = 'Florence';
    party.tffa__LastName__c = 'May';
    party.tffa__MaritalStatus__c = 'Married';
    party.tffa__MiddleName__c = 'J';
    party.tffa__NationalIdentifierType__c = 'SSN';
    party.tffa__NationalIdentifierValue__c = '123555555';
    party.tffa__PreferredContactMethod__c = 'Phone';
    party.tffa__PoliticallyExposedPerson__c = false;
    party.tffa__PreferredLanguage__c = 'English';
    party.tffa__PreferredTimeToCall__c = 'Morning';
    party.tffa__Prefilled__c = false;
    party.tffa__Prefix__c = 'Mr';
    party.tffa__PrimaryEmailType__c = 'PRIMARY';
    party.tffa__PrimaryEmail__c = 'a@a.com';
    party.tffa__SecondaryEmailType__c = 'SECONDARY';
    party.tffa__SecondaryEmail__c = 'b@b.com';
    party.tffa__PrimaryPhoneType__c = 'HOME';
    party.tffa__PrimaryPhone__c = ' 131334234';
    party.tffa__SecondaryPhoneType__c = 'WORK';
    party.tffa__SecondaryPhone__c = ' 131334288';
    party.tffa__FicoScore__c = 750;
    party.tffa__IsEmployee__c = false;
    party.tffa__NickName__c = 'Florence';
    party.tffa__SpousalVABenefitsEligibilityIndicator__c = false;
    party.tffa__Type__c = 'INDIVIDUAL';
    return party;
  }
}