objects/tffa__DisclosureEnvelope__c.object
<CustomObject>
    <description>An envelope is a container for documents that you send to a recipient to sign. An envelope can have one document or many documents. The envelope holds data on the documents to be signed, the signers and other recipients, and the places where signers will sign the
        documents</description>
    <label>Disclosure Envelope</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Disclosure Envelope Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Disclosure Envelopes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>tffa__ExternalId__c</fullName>
        <description>External id as referred by external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>tffa__PrimaryEmail__c</fullName>
        <description>Primary email of the party.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyPartyXref__c.object
<CustomObject>
    <description>A relationship between 2 applicants of a submission. 
Personal relationship could be SPOUSE, PARENT, FRIENDS.
Business relationship between a company and an individual could be DIRECTOR, OWNER, EXECUTIVE, PARTNER etc. In additional the ownership percentage can be captured for OWNER type of relationship. 
Relationship between 2 company type applicants can also be captured such as PARENT and SUBSIDIARY.</description>
    <fields>
        <fullName>tffa__ExternalId__c</fullName>
        <description>External id as referred by external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Party managing the relationship</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Related To</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Party Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Party Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__ExternalId__c</fullName>
        <description>External id as referred by external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <defaultValue>&quot;Init&quot;</defaultValue>
        <description>The current state/step of the Submission</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__SubmissionPartyXref__c.object
<CustomObject>
    <description>An individual or a legal entity which is applying for certain services/products in the bank. An applicant exists only in the context of a submission.</description>
    <fields>
        <fullName>tffa__ExternalId__c</fullName>
        <description>External id as referred by external system</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to Party object @managed</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__State__c</fullName>
        <description>store the current stage/state/step of the submission the current party/applicant  is at. This is useful for joint applicants where each one is filling his own data.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission object.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submission Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CZWTFCDocusignService.cls
public with sharing class CZWTFCDocusignService {
  public List<CZWTFCDocusignRequestDTO.CompositeTemplateDTO> lstCompositeTemplate = new List<CZWTFCDocusignRequestDTO.CompositeTemplateDTO>();
  //Docusign Signers list to be used in case of online signing
  //  List<CZWTFCDocusignRequestDTO.SignerDTO> lstDocusignSigners = new List<CZWTFCDocusignRequestDTO.SignerDTO>();
  //Signers
  //  public CZWTFCDocusignRequestDTO.SignerDTO signer = new CZWTFCDocusignRequestDTO.SignerDTO();

  public CZWTFCDocusingResult initateDocusign(List<CZWTFCDocusignRequestDTO.CompositeTemplateDTO> compositeTemplates, String action) {
    CZWTFCDocusignRequestDTO request = new CZWTFCDocusignRequestDTO();
    CZWTFCDocusingResult result = new CZWTFCDocusingResult();
    tffa.Interaction.begin(CZWTFCDocusignService.class, 'initateDocusign');
    try {
      tffa.Logger.debug('In CZWTFCDocusignService');
      try {
        request.envelope.compositeTemplates = compositeTemplates;
        request.envelope.status = action;
      } catch (Exception ex) {
        tffa.Logger.debug('Exception in CZWTFCDocusignService ' + ex.getLineNumber() + ' ' + ex.getMessage());
      }
      result = processRequest(request, action);
    } finally {
      tffa.Interaction.close();
    }
    return result;
  }

  public CZWTFCDocusingResult processRequest(CZWTFCDocusignRequestDTO request, String action) {
    CZWTFCDocusingResult docuResult = new CZWTFCDocusingResult();

    try {
      tffa.Interaction.begin(CZWTFCDocusignService.class, 'processRequest');

      //Call API to send templates and generate envelop ID
      CZWTFCDocusignAdapter adptr = new CZWTFCDocusignAdapter(request);
      CZWTFCDocusignResponseDTO generateEnvelopIDresponse = adptr.processRequestforApplicationDocusign();
      tffa.Logger.debug('response from generate envelop => ' + generateEnvelopIDresponse);

      if ((generateEnvelopIDresponse != null && generateEnvelopIDresponse.envelopeResp != null) || test.isRunningTest()) {
        tffa.Logger.debug('generateEnvelopIDresponse==>' + generateEnvelopIDresponse);
        docuResult.envelopeId = test.isRunningTest() ? '1234' : generateEnvelopIDresponse.envelopeResp.envelopeId;
        // tffa.Logger.debug('docuRequest==>' + docuRequest);

        if (action == CZDocusignConstants.GENERATE_DRAFT_MODE) {
          //Call API to get recipeint view for each recipient
          //adptr = new CZWTFCDocusignAdapter(request);
          Map<String, String> params = new Map<String, String>();
          params.put('envId', docuResult.envelopeId);
          docuResult = adptr.fetchDocusignUrl(params);
          tffa.Logger.debug('Result from recipeint view API ==>' + docuResult);
        }
      }
    } finally {
      tffa.Interaction.close();
    }

    return docuResult;
  }
  /*
  public CZWTFCDocusignRequestDTO.CompositeTemplateDTO createTemplate(CZDocusignDocumentGenDTO document) {
    CZWTFCDocusignRequestDTO.CompositeTemplateDTO compositTemplate = new CZWTFCDocusignRequestDTO.CompositeTemplateDTO();

    CZWTFCDocusignRequestDTO.ServerTemplateDTO serverTemplate = new CZWTFCDocusignRequestDTO.ServerTemplateDTO();
    serverTemplate.templateId = document.documentDTO.documentId;
    serverTemplate.sequence = String.valueOf(document.documentDTO.sequenceNumber);

    compositTemplate.serverTemplates = new List<CZWTFCDocusignRequestDTO.ServerTemplateDTO>{ serverTemplate };
    //----------------------------------------------------------------------------------------------------------

    CZWTFCDocusignRequestDTO.InlineTemplateDTO inlineTemplate = new CZWTFCDocusignRequestDTO.InlineTemplateDTO();
    inlineTemplate.sequence = String.valueOf(document.documentDTO.sequenceNumber);
    inlineTemplate.recipients = new CZWTFCDocusignRequestDTO.RecipientDTO();

    inlineTemplate.recipients.signers = new List<CZWTFCDocusignRequestDTO.SignerDTO>();

    inlineTemplate.recipients.signers = addSigners(document);
    //Add Signers
    tffa.Logger.debug('template fater adding signers ==>' + JSON.serialize(inlineTemplate.recipients.signers));
    compositTemplate.inlineTemplates = new List<CZWTFCDocusignRequestDTO.InlineTemplateDTO>{ inlineTemplate };
    return compositTemplate;
  }

  public CZWTFCDocusignRequestDTO.EnvelopeRecipientTabDTO getSignerTabs(CZDocusignDocumentGenDTO.SignerDTO signerDTO) {
    //Map result to docusing request
    CZWTFCDocusignRequestDTO.EnvelopeRecipientTabDTO lsttabs = new CZWTFCDocusignRequestDTO.EnvelopeRecipientTabDTO();
    lsttabs.textTabs = new List<CZWTFCDocusignRequestDTO.TextTabDTO>(); //document.documentDTO.prefillDataDTO.lstTextDTO;
    for (CZDocusignDocumentGenDTO.TextDTO textDTO : signerDTO.prefillDataDTO.lstTextDTO) {
      CZWTFCDocusignRequestDTO.TextTabDTO txt = new CZWTFCDocusignRequestDTO.TextTabDTO();
      txt.tabLabel = textDTO.name;
      txt.value = textDTO.value;
      lsttabs.textTabs.add(txt);
    }
    signerDTO.prefillDataDTO.lstTextDTO.clear(); //TODO: check without clear();
    lsttabs.radioGroupTabs = new List<CZWTFCDocusignRequestDTO.RadioTabDTO>(); //document.documentDTO.prefillDataDTO.lstTextDTO;
    for (CZDocusignDocumentGenDTO.RadioDTO textDTO : signerDTO.prefillDataDTO.lstRadioTO) {
      CZWTFCDocusignRequestDTO.RadioTabDTO txt = new CZWTFCDocusignRequestDTO.RadioTabDTO();
      txt.radios = new List<CZWTFCDocusignRequestDTO.RadiosDTO>();
      CZWTFCDocusignRequestDTO.RadiosDTO radiovalue = new CZWTFCDocusignRequestDTO.RadiosDTO();
      txt.groupName = textDTO.name;
      radiovalue.value = textDTO.radios[0].value;
      radiovalue.selected = 'true';
      txt.radios.add(radiovalue);
      lsttabs.radioGroupTabs.add(txt);
    }
    signerDTO.prefillDataDTO.lstRadioTO.clear();

    // lsttabs.checkboxTabs = new List<CZWTFCDocusignRequestDTO.CheckboxTabDTO>(); //document.documentDTO.prefillDataDTO.lstCheckBoxTO;

    lsttabs.checkboxTabs = new List<CZWTFCDocusignRequestDTO.CheckboxTabDTO>(); //document.documentDTO.prefillDataDTO.lstTextDTO;
    for (CZDocusignDocumentGenDTO.CheckboxDTO textDTO : signerDTO.prefillDataDTO.lstCheckBoxTO) {
      CZWTFCDocusignRequestDTO.CheckboxTabDTO txt = new CZWTFCDocusignRequestDTO.CheckboxTabDTO();
      txt.tabLabel = textDTO.name;
      txt.value = textDTO.value;
      txt.selected = textDTO.selected;
      lsttabs.checkboxTabs.add(txt);
    }
    signerDTO.prefillDataDTO.lstCheckBoxTO.clear();
    //Initiate

    return lsttabs;
  }

  public List<CZWTFCDocusignRequestDTO.SignerDTO> addSigners(CZDocusignDocumentGenDTO document) {
    List<CZWTFCDocusignRequestDTO.SignerDTO> result = new List<CZWTFCDocusignRequestDTO.SignerDTO>();
    Integer count = 0;
    for (CZDocusignDocumentGenDTO.SignerDTO signerDTO : document.documentDTO.lstSignerDTO) {
      CZWTFCDocusignRequestDTO.SignerDTO signer = new CZWTFCDocusignRequestDTO.SignerDTO();
      signer.name = signerDTO.name;
      signer.email = signerDTO.email;
      signer.recipientId = String.valueOf(signerDTO.recipientId);
      signer.clientUserId = String.valueOf(signerDTO.clientUserId);
      signer.roleName = signerDTO.roleName;

      signer.tabs = getSignerTabs(signerDTO);
      result.add(signer);
    }
    return result;
  }

  public static List<tffa__Party__c> fetchSigningStatus(Map<String, String> params) {
    CZWTFCDocusignResponseDTO response = new CZWTFCDocusignResponseDTO();
    tffa__Submission__c sub = CZWTFCSubmissionRepository.findOne(params.get('Submission__c'));
    String partyid = params.containsKey('Party__c') ? params.get('Party__c') : '';
    Map<String, tffa__Party__c> partymap = new Map<String, tffa__Party__c>();
    CZWTFCDocusignRequestDTO request = new CZWTFCDocusignRequestDTO();
    String envelopeId = sub.DocusignEnvelopID__c;
    List<tffa__Party__c> pendingSigners = new List<tffa__Party__c>();
    response = getSignersStatus(sub.id, envelopeId); //here
    //sub = CustomSubmissionRepository.findSubmissionById(params.get('Submission__c'));
    Set<Id> idSet = new Set<Id>();
    for (tffa__SubmissionPartyXref__c signerfromObject : sub.tffa__PartyXrefs__r) {
      idSet.add(signerfromObject.tffa__Party__c);
    }
    Integer pendingcount = 0;
    pendingSigners = FISCCIntegrationLogRepository.findPartydWithChildObjects(new List<Id>(idSet));
    tffa.Logger.debug('Signing Resp ' + response);
    if (response.signersStatus != null) {
      for (tffa__Party__c signerfromObject : pendingSigners) {
        Boolean issigner = false;
        // for (Docusign_Signing_Sequence__c signerfromObject : lstSigners) {
        for (CZWTFCSignersStatusDTO.SignersDTO signerfromAPI : response.signersStatus.signers) {
          if (signerfromAPI.email == signerfromObject.tffa__PrimaryEmail__c && signerfromAPI.name == signerfromObject.Name) {
            issigner = true;
            if ('Completed'.equalsIgnorecase(signerfromAPI.status)) {
              //Update status to Done
              signerfromObject.SigningStatus__c = 'Done';
            } else if (!'Completed'.equalsIgnorecase(signerfromAPI.status)) {
              signerfromObject.SigningStatus__c = 'Pending';

              pendingcount++;
            }
          }
        }
        tffa.Logger.debug('Pending Count ' + pendingcount);
        if (!issigner) {
          signerfromObject.SigningStatus__c = 'Done';
        }
        partymap.put(signerfromObject.id, signerfromObject);
      }
      FISCCObjectManagerRepository.doUpsertParties(pendingSigners);
    }
    if (pendingcount > 0) {
      sub.Envelope_Status__c = 'In Progress';
      // sub.tffa__State__c = 'Pending Docusign Signature';
    } else {
      sub.Envelope_Status__c = 'Completed';
      sub.Document_Saved_Status__c = 'Completed';
    }

    FISCCObjectManagerRepository.updateRecords(new List<tffa__Submission__c>{ sub });
    if (String.isNotBlank(partyid) && partymap.containsKey(partyid)) {
      return (new List<tffa__Party__c>{ partymap.get(partyid) });
    }
    return pendingSigners;
  }
*/
  public static CZWTFCSignersStatusDTO getSignersStatus(String submissionId, String envelopeId) {
    //CZWTFCDocusignRequestDTO request = new CZWTFCDocusignRequestDTO();
    CZWTFCDocusignAdapter adptr = new CZWTFCDocusignAdapter();
    CZWTFCSignersStatusDTO response;
    try {
      //Call Get Signers Status API
      response = adptr.getSignersStatus(envelopeId);
    } catch (exception ex) {
      tffa.Logger.debug('Exception in getSignersStatus  ==>' + ex.getStackTraceString() + 'at line number ' + ex.getLineNumber());
    }
    return response;
  }
  /*
  public CZWTFCDocusingResult prefillEnv(Map<String, String> params) {
    tffa.Logger.debug('In prefillEnv');
    tffa__Submission__c sub = CZWTFCSubmissionRepository.findOne(params.get('Submission__c'));
    tffa__DisclosureEnvelope__c discEnv = CZDocusignRepository.fetchDiscEnv(sub.Id);
    CZWTFCDocusingResult result = new CZWTFCDocusingResult();
    CZWTFCDocusignAdapter docAdapter = new CZWTFCDocusignAdapter();
    try {
      if (discEnv != null) {
        params.put('envId', discEnv.tffa__ExternalId__c);
        Blob respBlob = docAdapter.prefilledEnvelope(params);
        if (respBlob != null) {
          tffa.DocumentMetadataDTO report = new tffa.DocumentMetadataDTO('Docusign-Prefill.pdf', respBlob, sub.Id, 'OTHER');
          report.participants.add(new tffa.DocumentParticipantDTO(null, (String) discEnv.Id));
          ContentVersion cv = tffa.ContentService.createContentWithParticipant(report);
          result.msg = 'Success';
          result.contentDocId = cv.ContentDocumentId;
          return result;
        }
      }
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in prefill Env' + ex.getMessage());
    }
    result.msg = 'Failure';
    return result;
  }

  public CZWTFCDocusingResult fetchDocUrl(Map<String, String> params) {
    tffa.Logger.debug('In fetchDocUrl');
    CZWTFCDocusingResult result = new CZWTFCDocusingResult();
    CZWTFCDocusignRequestDTO request = new CZWTFCDocusignRequestDTO();
    CZWTFCDocusignAdapter docAdapter = new CZWTFCDocusignAdapter(request);
    try {
      result = docAdapter.fetchDocusignUrl(params);
      return result;
    } catch (Exception ex) {
      tffa.Logger.debug('Exception in fetchDocUrl Env' + ex.getMessage());
    }
    result.msg = 'Failure';
    return result;
  }*/
}