objects/tffa__Identification__c.object
<CustomObject>
    <description>Identification details of the party such as  driver license numbers, passport numbers .  Supports capture of identity document id as well which is stored as an attachment in the system.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to the parent party object</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Identifications</relationshipLabel>
        <relationshipName>Identifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>The kind of document that was examined to verify identity of the applicant. A driver&apos;s license is an example of an identity document.. The name will be defaulted to the name field</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__IdentificationType</valueSetName>
        </valueSet>
    </fields>
    <label>Identification</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Identifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyPartyXref__c.object
<CustomObject>
    <description>A relationship between 2 applicants of a submission. 
Personal relationship could be SPOUSE, PARENT, FRIENDS.
Business relationship between a company and an individual could be DIRECTOR, OWNER, EXECUTIVE, PARTNER etc. In additional the ownership percentage can be captured for OWNER type of relationship. 
Relationship between 2 company type applicants can also be captured such as PARENT and SUBSIDIARY.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Party managing the relationship</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Related To</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Party Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Party Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__SubmissionPartyXref__c.object
<CustomObject>
    <description>An individual or a legal entity which is applying for certain services/products in the bank. An applicant exists only in the context of a submission.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to Party object @managed</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current applicant is primary applicant of the application.</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission object.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Submission Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/tffa__IdentificationType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DL</fullName>
        <label>Drivers License</label>
    </customValue>
    <customValue>
        <fullName>StateID</fullName>
        <label>State ID</label>
    </customValue>
    <customValue>
        <fullName>Passport</fullName>
    </customValue>
    <customValue>
        <fullName>StudentID</fullName>
        <label>Student ID with Photo - under 18 only</label>
    </customValue>
    <customValue>
        <fullName>Minor</fullName>
    </customValue>
    <customValue>
        <fullName>MilitaryID</fullName>
        <label>Military ID</label>
    </customValue>
    <customValue>
        <fullName>ASSUMED_NAME_CERT</fullName>
        <label>Assumed Name Certificate</label>
    </customValue>
    <customValue>
        <fullName>NONE</fullName>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>CERT_OF_FORMATION</fullName>
        <label>Certificate of Formation</label>
    </customValue>
    <customValue>
        <fullName>ARTICLES_OF_INCORPORATION</fullName>
        <label>Articles of Incorporation</label>
    </customValue>
    <customValue>
        <fullName>CERT_OF_LIMITED_PARTNERSHIP</fullName>
        <label>Certificate of Limited Partnership</label>
    </customValue>
    <customValue>
        <fullName>BUSINESS_LICENSE</fullName>
        <label>Business License</label>
    </customValue>
    <customValue>
        <fullName>GreenCard</fullName>
        <label>Green Card</label>
    </customValue>
    <customValue>
        <fullName>ForeignPassport</fullName>
        <label>FOREIGN PASSPORT</label>
    </customValue>
    <customValue>
        <fullName>ResidentAlienCard</fullName>
        <label>RESIDENT ALIEN CARD</label>
    </customValue>
    <customValue>
        <fullName>Matricula</fullName>
        <label>MATRICULA</label>
    </customValue>
    <customValue>
        <fullName>USImmigrationVisa</fullName>
        <label>US IMMIGRATION VISA</label>
    </customValue>
    <description>The list of supported identification type for a party</description>
    <masterLabel>IdentificationType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

classes/CZWTFCCommonHelper.cls
public inherited sharing class CZWTFCCommonHelper {
  public static tffa__Party__c getPrimaryParty(tffa__Submission__c subObj, List<tffa__party__c> partyObjList) {
    for (tffa__SubmissionPartyXref__c subPartyXref : subObj.tffa__PartyXrefs__r) {
      if (subPartyXref.tffa__Primary__c) {
        for (tffa__Party__c partyObj : partyObjList) {
          if ((subPartyXref.tffa__Party__c).equals(partyObj.Id)) {
            return partyObj;
          }
        }
      }
    }
    return partyObjList[0];
  }

  public static String formatPhoneNumber(String phone) {
    return phone.replace('+1', '');
  }

  public static String getFormattedFullName(String firstName, String middleName, String lastName, String suffix, Integer maxLength) {
    String strFullName = firstName + ' ' + (String.isEmpty(middleName) ? '' : middleName + ' ') + lastName;
    if (!String.isBlank(suffix)) {
      maxLength = maxLength - suffix.length() - 1;
    }

    if (strFullName.length() > maxLength) {
      strFullName = firstName + ' ' + (String.isEmpty(middleName) ? '' : middleName.left(1) + ' ') + lastName;
    }
    if (strFullName.length() > maxLength) {
      strFullName = firstName + ' ' + lastName;
    }
    if (strFullName.length() > maxLength) {
      strFullName = firstName.left(1) + ' ' + (String.isEmpty(middleName) ? '' : middleName.left(1) + ' ') + lastName;
    }
    if (strFullName.length() > maxLength) {
      strFullName = firstName + ' ' + (String.isEmpty(middleName) ? '' : middleName.left(1) + ' ') + lastName.left(1);
    }
    if (strFullName.length() > maxLength) {
      strFullName = (firstName + ' ' + (String.isEmpty(middleName) ? '' : middleName + ' ') + lastName).substring(0, maxLength);
    }
    if (!String.isBlank(suffix)) {
      strFullName = strFullName + ' ' + suffix;
    }
    return strFullName;
  }

  public static String trimString(String value, Integer length) {
    if (String.isNotBlank(value) && value.length() > length) {
      return value.substring(0, length);
    } else {
      return value;
    }
  }

  public static String generateUUID() {
    Blob b = Crypto.GenerateAESKey(128);
    String hexCode = EncodingUtil.ConvertTohex(b);
    String uuid =
      hexCode.SubString(0, 8) +
      '-' +
      hexCode.SubString(8, 12) +
      '-' +
      hexCode.SubString(12, 16) +
      '-' +
      hexCode.SubString(16, 20) +
      '-' +
      hexCode.substring(20);
    return uuid;
  }

  public static String getIdentificationLabel(String value) {
    List<Schema.PicklistEntry> picklistEntries = Schema.SObjectType.tffa__Identification__c.fields.tffa__Type__c.getPicklistValues();

    if (picklistEntries != null) {
      for (Schema.PicklistEntry ple : picklistEntries) {
        if ((ple.getValue()).equalsIgnoreCase(value)) {
          return ple.getLabel();
        }
      }
    }
    return '';
  }
}