objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__KYCDecisionOutcome__c</fullName>
        <description>Outcome of a KYC decisioning process.</description>
        <label>KYC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationDecisionOutcome</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the application</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ApplicationPartyXref__c.object
<CustomObject>
    <description>Each Applicant of the submission can play different roles in the application and the eventual account.</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>tffa__FirstName__c</fullName>
        <description>The first name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__KYCDecisionOutcome__c</fullName>
        <description>Outcome of a KYC decisioning process.</description>
        <label>KYC Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyDecisionOutcome</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>The last name of the individual represented by the parent object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__OTP__c</fullName>
        <description>One time confirmation token generated for the applicant to authenticate himself</description>
        <encryptionScheme>None</encryptionScheme>
        <label>One Time Confirmation token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryEmail__c</fullName>
        <description>Primary email of the party.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryPhone__c</fullName>
        <description>Primary phone number of the party</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Primary phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Suffix__c</fullName>
        <description>The name suffix of the individual represented by the parent object. (E.g., JR = Junior, SR = Senior, etc.)</description>
        <label>Suffix</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__Suffix</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WT_AdverseActionNotice__c.object
<CustomObject>
    <description>Temporary object to store Adverse Action catch up</description>
    <fields>
        <fullName>DateProcessed__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DateProcessed</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PartyId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PartyId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>AdverseActionNotice</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>AdverseActionNotice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AdverseActionNotices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__ApplicationDecisionOutcome.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>APPROVED</fullName>
        <label>✅Approved</label>
    </customValue>
    <customValue>
        <fullName>DECLINED</fullName>
        <label>❌Declined</label>
    </customValue>
    <customValue>
        <fullName>REVIEW</fullName>
        <label>⚠️Review</label>
    </customValue>
    <customValue>
        <fullName>COUNTER_OFFER</fullName>
        <label>🔶Counter offer</label>
    </customValue>
    <description>Possible outcomes of an Application decisioning process. Each outcome has a different effect on the Application process. e.g. DECLINED may result in termination of further processing, REVIEW may result in manual intervention for further processing</description>
    <masterLabel>ApplicationDecisionOutcome</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyDecisionOutcome.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>APPROVED</fullName>
        <label>✅Approved</label>
    </customValue>
    <customValue>
        <fullName>DECLINED</fullName>
        <label>❌Declined</label>
    </customValue>
    <customValue>
        <fullName>REVIEW</fullName>
        <label>⚠️Review</label>
    </customValue>
    <customValue>
        <fullName>COUNTER_OFFER</fullName>
        <label>🔶Counter offer</label>
    </customValue>
    <description>Possible outcomes of an Party decisioning process. Each outcome has a different effect on the Party as well as on related Application(s). e.g. if outcome is DECLINED, related Application may be DECLINED, if outcome is REVIEW, related Application may be marked for REVIEW</description>
    <masterLabel>PartyDecisionOutcome</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__Suffix.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Jr</fullName>
    </customValue>
    <customValue>
        <fullName>Sr</fullName>
        <label>Sr.</label>
    </customValue>
    <customValue>
        <fullName>II</fullName>
    </customValue>
    <customValue>
        <fullName>III</fullName>
    </customValue>
    <customValue>
        <fullName>IV</fullName>
    </customValue>
    <customValue>
        <fullName>246</fullName>
        <isActive>false</isActive>
        <label>246</label>
    </customValue>
    <customValue>
        <fullName>Esq</fullName>
        <isActive>false</isActive>
        <label>Esq</label>
    </customValue>
    <customValue>
        <fullName>VI</fullName>
        <isActive>false</isActive>
        <label>VI</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <isActive>false</isActive>
        <label>V</label>
    </customValue>
    <customValue>
        <fullName>2nd</fullName>
        <isActive>false</isActive>
        <label>2nd</label>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
        <isActive>false</isActive>
        <label>Test</label>
    </customValue>
    <description>The name suffix of the individual represented by the parent object. (E.g., JR = Junior, SR = Senior, etc.)</description>
    <masterLabel>Suffix</masterLabel>
</GlobalValueSet>

classes/WT_BatchAdverseActionLetter.cls
global class WT_BatchAdverseActionLetter implements Database.Batchable<sObject>
{
    global Database.QueryLocator start(Database.BatchableContext batchContext) 
    {
        return Database.getQueryLocator([SELECT Id,
                                         PartyId__c,
                                         DateProcessed__c
                                         FROM WT_AdverseActionNotice__c
                                         WHERE DateProcessed__c = null
                                         ORDER BY CreatedDate
                                         LIMIT 2]);
    }
    
    global void execute(Database.BatchableContext batchContext, List<WT_AdverseActionNotice__c> scope)
    {
        Set<Id> setPartyId = new Set<Id>();
        List<WT_AdverseActionNotice__c> listNoticeToUpdate = new List<WT_AdverseActionNotice__c>();
        for(WT_AdverseActionNotice__c notice : scope)
        {
            setPartyId.add(notice.PartyId__c);
            notice.DateProcessed__c = System.now();
            listNoticeToUpdate.add(notice);
        }
        
        Map<Id, tffa__Application__c> mapPartyIdAndApplication = new Map<Id, tffa__Application__c>();
        
        for(tffa__ApplicationPartyXref__c partyXref : [SELECT Id,
                                                       tffa__Application__c,
                                                       tffa__Application__r.Name,
                                                       tffa__Application__r.tffa__Status__c,
                                                       tffa__Party__c
                                                       FROM tffa__ApplicationPartyXref__c
                                                       WHERE tffa__Party__c IN :setPartyId])
        {
            tffa__Application__c relatedApplication = new tffa__Application__c();
            relatedApplication.Id = partyXref.tffa__Application__c;
            relatedApplication.Name = partyXref.tffa__Application__r.Name;
            relatedApplication.tffa__Status__c = partyXref.tffa__Application__r.tffa__Status__c;
            
            mapPartyIdAndApplication.put(partyXref.tffa__Party__c, relatedApplication);
        }
        
        for(tffa__Party__c partyToEmail : [SELECT Id,
                                           Name,
                                           tffa__PrimaryEmail__c,
                                           tffa__PrimaryPhone__c,
                                           tffa__Suffix__c,
                                           tffa__FirstName__c,
                                           tffa__LastName__c,
                                           tffa__OTP__c,
                                           tffa__KYCDecisionOutcome__c
                                           FROM tffa__Party__c
                                           WHERE Id IN :setPartyId])
        {
            if(mapPartyIdAndApplication.containsKey(partyToEmail.Id))
            {
                new CZWTFCPartyEventExtensionOld('Application_Declined_Adverse').sendAdverseActionMail(partyToEmail, mapPartyIdAndApplication.get(partyToEmail.Id));   
            }
            else
            {
                new CZWTFCPartyEventExtensionOld('Application_Declined_Adverse').post(partyToEmail);   
            }
        }
        
        update listNoticeToUpdate;
    }
    
    global void finish(Database.BatchableContext batchContext)
    {
        List<WT_AdverseActionNotice__c> listNotice = [SELECT Id,
                                                      PartyId__c,
                                                      DateProcessed__c
                                                      FROM WT_AdverseActionNotice__c
                                                      WHERE DateProcessed__c = null
                                                      ORDER BY CreatedDate];
        
        if(!listNotice.isEmpty() && listNotice.size() > 0)
        {
            Database.executeBatch(new WT_BatchAdverseActionLetter(), 2);
        }
    }
}