objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>CZLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location</description>
        <label>Location</label>
        <referenceTo>tffa__Location__c</referenceTo>
        <relationshipLabel>Location</relationshipLabel>
        <relationshipName>Location</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>Fis branch code for Location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Branch Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Brand__c</fullName>
        <description>Brand code of the Brand for the submission if applicable</description>
        <formula>tffa__Submission__r.tffa__Brand__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Brand Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The current geographical location/branch of the account. This will be computed or selected</description>
        <label>Location(Branch)</label>
        <referenceTo>tffa__Location__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>Unique code for the brand</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Code</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__BrandLocation__c.object
<CustomObject>
    <description>A list of locations associated with brand</description>
    <fields>
        <fullName>tffa__Brand__c</fullName>
        <description>Reference to the parent brand object.</description>
        <label>Brand</label>
        <referenceTo>tffa__Brand__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Location which is linked to the brand</description>
        <label>Location</label>
        <referenceTo>tffa__Location__c</referenceTo>
        <relationshipLabel>Brand Locations</relationshipLabel>
        <relationshipName>BrandLocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Brand Location</label>
    <nameField>
        <displayFormat>BL-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brand Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Location__c.object
<CustomObject>
    <description>Named geographical place (such as a branch or terminal) that provides permanent facilities for movement of goods (such as customs, storage, and other support services) or is designated for a stated purpose. Read more: http://www.businessdictionary.com/definition/location.html</description>
    <fields>
        <fullName>CZSDBSalesTaxPct__c</fullName>
        <description>SDB Tax Rate for location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SDB Tax Rate</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>Fis branch code for Location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Branch Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Code__c</fullName>
        <description>A logical identifier that is more human friendly.</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Code</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Location (branch)</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations (branch)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CZWTFCFetchSDBTaxRateBatch.cls
global with sharing class CZWTFCFetchSDBTaxRateBatch extends tffa.AbstractBatchJob {
  public static List<tffa__Location__c> locationlst = new List<tffa__Location__c>();
  public List<tffa__BrandLocation__c> start(Database.BatchableContext bc) {
    tffa.Logger.debug('CZWTFCFetchSDBTaxRateBatch start Datetime : ' + String.valueOf(Datetime.now()));
    return CZWTFCHelperRepository.getBrandLocations();
  }

  public void execute(Database.BatchableContext bc, List<tffa__BrandLocation__c> brandLocations) {
    tffa.Interaction.begin(CZWTFCFetchSDBTaxRateBatch.class, 'execute');
    try {
      for (tffa__BrandLocation__c brandLocation : brandLocations) {
        tffa__Location__c locationObj = brandLocation.tffa__Location__r;
        CZWTFCFetchSDBTaxRateResponseDTO result = new CZWTFCFetchSDBTaxRateResponseDTO();
        FISCCIntegrationLogService.setCharterConfig(brandLocation.tffa__Brand__r.tffa__Code__c);
        FISCCIntegrationLogService.auth = FISCCGetAccessTokenProvider.processGetAccessToken(FISCCIntegrationLogService.charterConfig);
        result = CZWTFCFetchSDBTaxRateProvider.generateBranchDetails(
          locationObj.FISBranchCode__c,
          FISCCIntegrationLogService.charterConfig
        );

        if (result != null && result.entity != null && result.entity.branchesDetail != null) {
          locationObj.CZSDBSalesTaxPct__c = result.entity.branchesDetail.SafeDPBoxSalesTaxPct;
        } else {
          locationObj.CZSDBSalesTaxPct__c = '0.000';
        }

        locationlst.add(locationObj);
      }

      CZWTFCHelperRepository.saveLocation(locationlst);
    } catch (Exception ex) {
      tffa.logger.error('Exception in  CZWTFCFetchSDBTaxRateBatch ' + ex.getMessage() + ' ' + ex.getStackTraceString());
    } finally {
      tffa.Logger.debug('CZWTFCFetchSDBTaxRateBatch.execute: Execute Datetime Ended on : ' + String.valueOf(Datetime.now()));
      tffa.Interaction.close();
    }
  }

  public void finish(Database.BatchableContext bc) {
    tffa.Logger.debug('CZWTFCFetchSDBTaxRateBatch Completed at  : ' + String.valueOf(Datetime.now()));
  }
}