objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>AdobeCampaignRetryCount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Adobe Campaign Retry Count</description>
        <label>AdobeCampaignRetryCount</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsAccTransferred__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If Submission data is sent to Adobe Campaign</description>
        <label>IsAccTransferred</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the submission</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/tffa__SubmissionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>ABANDONED</fullName>
        <label>Abandoned</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>SAVED</fullName>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>SUBMITTED</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>Indicates current status of the submission.This will be computed and be useful for regulations.</description>
    <masterLabel>SubmissionStatus</masterLabel>
</GlobalValueSet>

classes/CZWTFCACCBatch.cls
global with sharing class CZWTFCACCBatch extends tffa.AbstractBatchJob implements Database.Batchable<sObject>, Database.AllowsCallouts {
  String status = 'EXPIRED';
  Integer retryCount = 4;

  public Database.QueryLocator start(Database.BatchableContext batchableCntx) {
    tffa.Logger.debug('start Datetime : ' + String.valueOf(Datetime.now()));
    tffa.Logger.flush();
    return Database.getQueryLocator(getQuery());
  }

  public void execute(Database.BatchableContext batchableCntx, List<SObject> subObject) {
    tffa.Logger.debug('ACC execute Datetime Started on : ' + String.valueOf(Datetime.now()));
    try {
      List<tffa__Submission__c> subList = new List<tffa__Submission__c>();
      List<tffa__Submission__c> submissionList = (List<tffa__Submission__c>) subObject;
      tffa.Logger.debug('ACC Submission List : ' + submissionList);

      CZWTFCAdobeCampaignService accService = new CZWTFCAdobeCampaignService();
      subList = accService.processExpiredSubmissions(submissionList);

      if (!Test.isRunningTest()) {
        CZWTFCSubmissionRepository.save(subList);
      }
    } catch (Exception ex) {
      tffa.Logger.error('Exception in ACC :::' + ex.getStackTraceString() + 'LineNumber :::' + ex.getLineNumber());
    } finally {
      tffa.Logger.flush();
    }
    tffa.Logger.debug('ACC execute Datetime Ended on  : ' + String.valueOf(Datetime.now()));
  }

  public void finish(Database.BatchableContext batchableCntx) {
    tffa.Logger.debug('ACC execute Completed at  : ' + String.valueOf(Datetime.now()));
    tffa.Logger.flush();
  }

  private static String getQuery() {
    String query = new tffa.QueryBuilder(tffa__Submission__c.SObjectType)
      .selectFields()
      .whereClause('tffa__Status__c', '= :status')
      .opAnd()
      .whereClause('IsAccTransferred__c', '= false')
      .opAnd()
      .whereClause('AdobeCampaignRetryCount__c', '< :retryCount')
      .build()
      .toQuery();

    tffa.Logger.debug(query);
    return query;
  }
}