objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>CostCenter__c</fullName>
        <description>Cost center for location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Cost center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DPTDId__c</fullName>
        <description>Deposit Number</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Deposit Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>Fis branch code for Location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Branch Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__AccountNumber__c</fullName>
        <description>The final generated account number. This will be set only after the final account number is available as part of the response of an account open API call.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Account number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Product code identifier.</description>
        <label>Financial Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND 2 AND (3 OR (4 AND 5))</booleanFilter>
            <errorMessage>Product not valid.</errorMessage>
            <filterItems>
                <field>$Source.tffa__ProductCategory__c</field>
                <operation>equals</operation>
                <valueField>tffa__Product__c.tffa__Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>tffa__Product__c.tffa__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value>In Progress</value>
            </filterItems>
            <filterItems>
                <field>$Source.tffa__Status__c</field>
                <operation>notEqual</operation>
                <value></value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>tffa__Product__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ApplicationPartyXref__c.object
<CustomObject>
    <description>Each Applicant of the submission can play different roles in the application and the eventual account.</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Brand__c.object
<CustomObject>
    <description>Multi-branding occurs when banks market similar and competing products under the different sub-brands that they own, many of which look like regional banks or non-banks</description>
    <fields>
        <fullName>CIPrmyOffcrNbr__c</fullName>
        <description>CI Prmy Offcr Nbr</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Officer Number</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>CZMDMPartyID__c</fullName>
        <description>MDM Global Id</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MDM Global ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CellPhoneNumber__c</fullName>
        <description>Cell phone of the party.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Cell phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CostCenter__c</fullName>
        <description>Cost center for location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Cost center</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>Fis branch code for Location</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Branch Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsCrossCharterCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is CrossCharter Customer</description>
        <inlineHelpText>If the customer is not having an existing realtionship with this charter but has a relationship in another charter.</inlineHelpText>
        <label>CrossCharter Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__BrandCode__c</fullName>
        <description>Brand code of the submission this party is associated with</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__FirstName__c</fullName>
        <description>The first name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>First name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__LastName__c</fullName>
        <description>The last name of the individual represented by the parent object</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Last name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__MiddleName__c</fullName>
        <description>The middle name of the individual represented by the parent object.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Middle name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__OnboardingDate__c</fullName>
        <description>Date on which party was onboarded into the system</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Onboarding date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>tffa__PrimaryPhone__c</fullName>
        <description>Primary phone number of the party</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Primary phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__SecondaryPhone__c</fullName>
        <description>Secondary phone of the party.</description>
        <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
        <label>Secondary phone</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__PartyAddressXref__c.object
<CustomObject>
    <description>Association table between Party and Address . This supports capture of multiple types and also periodAtAddress.
This creates an address book of the party</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>The party which owns the address.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>AddressXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Address Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PartyAddresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__PartyPartyXref__c.object
<CustomObject>
    <description>A relationship between 2 applicants of a submission. 
Personal relationship could be SPOUSE, PARENT, FRIENDS.
Business relationship between a company and an individual could be DIRECTOR, OWNER, EXECUTIVE, PARTNER etc. In additional the ownership percentage can be captured for OWNER type of relationship. 
Relationship between 2 company type applicants can also be captured such as PARENT and SUBSIDIARY.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Party managing the relationship</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Related To</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Party Party Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Party Party Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <fields>
        <fullName>tffa__Category__c</fullName>
        <description>Broad classification of the product</description>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ProductCategory</valueSetName>
        </valueSet>
    </fields>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>FISBranchCode__c</fullName>
        <description>FIS Branch Code.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This is the branch code received in URL Parameter from marketing site.</inlineHelpText>
        <label>FIS Branch Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__SubmissionPartyXref__c.object
<CustomObject>
    <description>An individual or a legal entity which is applying for certain services/products in the bank. An applicant exists only in the context of a submission.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to Party object @managed</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission object.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Submission Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MDMCustomerCreateExtension.cls
public with sharing class MDMCustomerCreateExtension {
  public static String createCustomer(tffa__Submission__c submission, tffa__Party__c party) {
    try {
      MuleSoft_Adapter_Config__mdt adapterConfig = CZWTFCHelperRepository.fetchMulesoftAdapterConfig('CreateCustomer');

      MDMCustomerCreateRequest request = generateCustomerCreateRequest(submission, party);

      String requestStr = System.JSON.serialize(request, true);

      CZMulesoftAdapter.auth = FISCCIntegrationLogService.auth;

      Object resp = CZMulesoftAdapter.invokeAPI(requestStr, adapterConfig);

      if (resp != null) {
        CZMDMCustomerCreationResponseDTO custResp = (CZMDMCustomerCreationResponseDTO) resp;
        if (custResp.wtfcPartyId != null) {
          party.CZMDMPartyID__c = custResp.wtfcPartyId;
        }
      }

      FISCCIntegrationLogService.setLogItemOk(FISCCIntegrationConstants.CREATE_CUSTOMER_MDM);
      return 'SUCCESS';
    } catch (Exception ex) {
      tffa.logger.error('Exception in MDMCustomerCreateExtension ' + ex.getMessage() + ' ' + ex.getStackTraceString());

      FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.CREATE_CUSTOMER_MDM);
      return 'FAILURE';
    }
  }

  public static MDMCustomerCreateRequest generateCustomerCreateRequest(tffa__Submission__c submission, tffa__Party__c party) {
    //party = CZWTFCPartyRepository.findByIdWithChildObjects(party.Id);

    MDMCustomerCreateRequest request = new MDMCustomerCreateRequest();

    request.rowidObject = '';

    // If party is part of another charter
    if (party.IsCrossCharterCustomer__c) {
      request.rowidObject = party.CZMDMPartyID__c;
    }

    Datetime startDate = party.tffa__OnboardingDate__c;

    if (startDate == null) {
      startDate = Datetime.now();
    }

    if (party.Customer_Number__c != null) {
      Integer custNumber = Integer.valueOf(party.Customer_Number__c);
      request.key.sourceKey = String.valueOf(custNumber) + '|' + MDMCommonHelper.getBrandCode(party.tffa__BrandCode__c);
    }

    request.ptyTypCd = 'INDV';
    request.costCntrNo = party.CostCenter__c != null ? party.CostCenter__c : '';
    request.endDt = '9999-12-31';
    request.strtDt = startDate.formatGMT(FISCCIntegrationConstants.MDM_DATE_FORMAT);
    request.ptyNm = party.tffa__LastName__c + ', ' + party.tffa__FirstName__c;
    request.statChngDt = startDate.formatGMT(FISCCIntegrationConstants.MDM_DATE_FORMAT);

    request.offcrRowid.offcrCd =
      FISCCIntegrationLogService.brandObj.CIPrmyOffcrNbr__c +
      '|' +
      MDMCommonHelper.getBrandCode(party.tffa__BrandCode__c);
    request.statCd.lkpCd = 'STATUS|A';
    request.psptIn.lkpCd = 'FLAG|N';
    request.cntryCd.ctryCd = 'USA'; // Default set to USA
    request.bnkCd.locCd = MDMCommonHelper.getBrandCode(party.tffa__BrandCode__c);
    request.brnchCd.locCd = MDMCommonHelper.getBrandCode(party.tffa__BrandCode__c) + '|' + party.FISBranchCode__c;

    request.Details.item.add(getPartyDetails(party));
    request.Identifiers.item.add(getIdentifiers(party));
    request.Email.item.add(getEmail(party));
    request.Addresses.item.add(getAddress(party));

    if (party.CellPhoneNumber__c != null || party.tffa__PrimaryPhone__c != null || party.tffa__SecondaryPhone__c != null) {
      request.Communication.item.addAll(getCommunication(party));
    }

    for (tffa__Application__c app : FISCCIntegrationLogService.applicationObjs) {
      if (app.tffa__AccountNumber__c != null && (app.tffa__Product__r.tffa__Category__c != 'CERTIFICATE' || app.DPTDId__c != null)) {
        request.AccountRelationship.item.add(getAccountRelationShip(app, party));
      }
    }

    return request;
  }

  public static MDMCustomerCreateRequest.DetailsItem getPartyDetails(tffa__Party__c party) {
    MDMCustomerCreateRequest.DetailsItem item = new MDMCustomerCreateRequest.DetailsItem();
    item.lstNm = party.tffa__LastName__c.touppercase();
    item.frstNm = party.tffa__FirstName__c.touppercase();
    item.midNm = party.tffa__MiddleName__c != null ? party.tffa__MiddleName__c.touppercase() : '';
    item.sfxVl = party.tffa__Suffix__c != null ? party.tffa__Suffix__c : '';

    Datetime dob = Date.Valueof(party.tffa__BirthDate__c);
    item.birthDt = dob.formatGMT(FISCCIntegrationConstants.MDM_DATE_FORMAT);

    item.empIn.lkpCd = 'FLAG|N';

    item.ctznCd.lkpCd = (party.tffa__Citizenship__c == 'Citizen') ? 'CTZNCD|Y' : 'CTZNCD|N';
    item.statCd.lkpCd = 'STATUS|A';
    item.occpnCd.occpnCd = '011';

    return item;
  }

  public static MDMCustomerCreateRequest.IdentifiersItem getIdentifiers(tffa__Party__c party) {
    MDMCustomerCreateRequest.IdentifiersItem item = new MDMCustomerCreateRequest.IdentifiersItem();

    item.idntyCd = party.tffa__NationalIdentifierValue__c;
    item.idntyTypCd.idntyTypCd = 'S';

    return item;
  }

  public static List<MDMCustomerCreateRequest.CommunicationItem> getCommunication(tffa__Party__c party) {
    List<MDMCustomerCreateRequest.CommunicationItem> communicationList = new List<MDMCustomerCreateRequest.CommunicationItem>();
    Boolean isHomeAddressAdded = false;
    MDMCustomerCreateRequest.CommunicationItem item = new MDMCustomerCreateRequest.CommunicationItem();

    if (party.CellPhoneNumber__c != null) {
      String phoneNumber = String.valueOf(party.CellPhoneNumber__c);
      item.commcnVl = phoneNumber.right(10);
      item.commcnTypCd.commcnTypCd = 'MBL';
      item.prefFg.lkpCd = isPreferredContactNumber(party.PreferredContactNumber__c, 'MBL');
      communicationList.add(item);

      if (item.prefFg.lkpCd == 'FLAG|Y') {
        item = new MDMCustomerCreateRequest.CommunicationItem();
        item.commcnVl = phoneNumber.right(10);
        item.commcnTypCd.commcnTypCd = 'HME';
        item.prefFg.lkpCd = isPreferredContactNumber(party.PreferredContactNumber__c, 'HME');
        communicationList.add(item);

        isHomeAddressAdded = true;
      }
    }

    if (party.tffa__PrimaryPhone__c != null && !isHomeAddressAdded) {
      item = new MDMCustomerCreateRequest.CommunicationItem();
      String phoneNumber = String.valueOf(party.tffa__PrimaryPhone__c);
      item.commcnVl = phoneNumber.right(10);
      item.commcnTypCd.commcnTypCd = 'HME';
      item.prefFg.lkpCd = isPreferredContactNumber(party.PreferredContactNumber__c, 'HME');
      communicationList.add(item);
    }

    if (party.tffa__SecondaryPhone__c != null) {
      item = new MDMCustomerCreateRequest.CommunicationItem();
      String phoneNumber = String.valueOf(party.tffa__SecondaryPhone__c);
      item.commcnVl = phoneNumber.right(10);
      item.commcnTypCd.commcnTypCd = 'WRK';
      item.prefFg.lkpCd = isPreferredContactNumber(party.PreferredContactNumber__c, 'WRK');
      communicationList.add(item);
    }

    return communicationList;
  }

  public static String isPreferredContactNumber(String type, String code) {
    if (type == 'HOME' && code == 'HME') {
      return 'FLAG|Y';
    } else if ((type == 'MOBILE' || type == 'CELL') && code == 'MBL') {
      return 'FLAG|Y';
    } else if (type == 'WORK' && code == 'WRK') {
      return 'FLAG|Y';
    }

    return 'FLAG|N';
  }

  public static MDMCustomerCreateRequest.EmailItem getEmail(tffa__Party__c party) {
    MDMCustomerCreateRequest.EmailItem item = new MDMCustomerCreateRequest.EmailItem();

    item.emailTypCd.commcnTypCd = 'EMAIL';
    item.email = party.tffa__PrimaryEmail__c;

    return item;
  }

  public static MDMCustomerCreateRequest.AddressesItem getAddress(tffa__Party__c party) {
    MDMCustomerCreateRequest.AddressesItem item = new MDMCustomerCreateRequest.AddressesItem();

    item.primAddrIn.lkpCd = 'FLAG|Y';
    item.addrTypCd.addrTypCd = 'PRIM';
    item.Address.stateCd = party.tffa__AddressXrefs__r[0].tffa__Address__r.tffa__State__c;
    item.Address.cityNm = party.tffa__AddressXrefs__r[0].tffa__Address__r.tffa__City__c;
    item.Address.addrLine1Tx = party.tffa__AddressXrefs__r[0].tffa__Address__r.tffa__Line1__c;

    List<String> zipCode = party.tffa__AddressXrefs__r[0].tffa__Address__r.tffa__ZipCode__c.split('-', 2);
    if (zipCode != null) {
      if (zipCode.size() > 0) {
        if (zipCode.get(0).length() > 5) {
          item.Address.zip5Cd = zipCode.get(0).substring(0, 5);
          if (zipCode.get(0).length() == 9) {
            item.Address.zip4Cd = zipCode.get(0).substring(5, 9);
          }
        } else {
          item.Address.zip5Cd = zipCode.get(0);
        }
      }
      if (zipCode.size() > 1 && zipCode.get(1).length() == 4) {
        item.Address.zip4Cd = zipCode.get(1);
      }
    }
    item.Address.cntryCd.ctryCd = 'USA'; // Default set to USA

    return item;
  }

  public static MDMCustomerCreateRequest.AccountRelationshipItem getAccountRelationShip(tffa__Application__c app, tffa__Party__c party) {
    MDMCustomerCreateRequest.AccountRelationshipItem item = new MDMCustomerCreateRequest.AccountRelationshipItem();

    tffa__ApplicationPartyXref__c applicationParty = new tffa__ApplicationPartyXref__c();

    for (tffa__ApplicationPartyXref__c applicationPartyObjs : app.tffa__PartyXrefs__r) {
      if (applicationPartyObjs.tffa__Party__c == party.Id) {
        applicationParty = applicationPartyObjs;
      }
    }

    item.relRoleCd = 'CtoA' + '|' + MDMCommonHelper.getBrandCode(app.tffa__Brand__c) + '|' + applicationParty.CZFISRelationshipCode__c;

    item.relTypeCode = 'INDV_DEP';
    item.hierarchyCode = 'PTY_ACCT_HIER';
    item.endDt = '9999-12-31';
    item.strtDt = app.CZAccountOpeningDate__c.format(FISCCIntegrationConstants.MDM_DATE_FORMAT);
    item.primCustAcctFg.lkpCd = 'FLAG|Y';
    item.statCd.lkpCd = 'STATUS|A';

    MDMCustomerCreateRequest.Account accountDetails = new MDMCustomerCreateRequest.Account();

    String accountNumber = app.tffa__AccountNumber__c;

    if (accountNumber != null && accountNumber.length() != 11) {
      accountNumber = accountNumber.leftPad(11, '0');
    }

    if (app.tffa__Product__r.tffa__Category__c == 'CERTIFICATE' && app.DPTDId__c != null) {
      String DPTDId = app.DPTDId__c.leftPad(11, '0');
      accountNumber = accountNumber + '-' + DPTDId;
    }

    accountDetails.key.sourceKey = accountNumber + '|' + MDMCommonHelper.getBrandCode(app.tffa__Brand__c);
    accountDetails.acctNo = accountNumber;
    accountDetails.boClassCode = 'DEPOSIT';
    accountDetails.closeDate = '9999-12-31';
    accountDetails.openDate = app.CZAccountOpeningDate__c.format(FISCCIntegrationConstants.MDM_DATE_FORMAT);
    accountDetails.statChngDt = app.CZAccountOpeningDate__c.format(FISCCIntegrationConstants.MDM_DATE_FORMAT);

    accountDetails.bnkCd.locCd = MDMCommonHelper.getBrandCode(app.tffa__Brand__c);
    accountDetails.brnchCd.locCd = MDMCommonHelper.getBrandCode(app.tffa__Brand__c) + '|' + app.FISBranchCode__c;
    accountDetails.prodCtgry.prodCd = 'DP';
    accountDetails.statCd.lkpCd = 'ACCTSTAT|O';
    accountDetails.prodType.prodCd = 'DP|' + MDMCommonHelper.getProductTypeCode(app.tffa__Product__r);
    accountDetails.prodSubType.prodCd = accountDetails.prodType.prodCd + '|' + app.tffa__Product__r.tffa__Code__c.leftPad(3, '0');

    MDMCustomerCreateRequest.AccountPreferencesItem acctPrefItem = new MDMCustomerCreateRequest.AccountPreferencesItem();
    acctPrefItem.prefTypCd.prefTypCd = 'ACCT|STMT';
    acctPrefItem.prefVl.lkpCd = 'ACCTPREFVL|E';
    acctPrefItem.statCd.lkpCd = 'STATUS|A';

    accountDetails.AccountPreferences.item.add(acctPrefItem);

    item.Account = accountDetails;

    return item;
  }

  public static String getPartySuffixData(String value) {
    Schema.DescribeFieldResult fieldResult = tffa__party__c.tffa__Suffix__c.getDescribe();
    List<Schema.PicklistEntry> values = fieldResult.getPicklistValues();
    for (Schema.PicklistEntry v : values) {
      if (v.getValue() == value) {
        return v.getLabel();
      }
    }

    return '';
  }
}