objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>tffa__IDAStatus__c</fullName>
        <description>Overall IDAStatus (refer DueDiligence for IDA) across related Parties. Typically refers to IDAStatus of primary Party.</description>
        <label>IDA Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__ApplicationPartyXref__c.object
<CustomObject>
    <description>Each Applicant of the submission can play different roles in the application and the eventual account.</description>
    <fields>
        <fullName>tffa__Application__c</fullName>
        <description>Reference to application object</description>
        <label>Application</label>
        <referenceTo>tffa__Application__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Application Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__DueDiligence__c.object
<CustomObject>
    <description>Due diligence is the process of gathering data in order to verify the identity of the applicant and to make sure they are not involved in money laundering , fraud  and high risk activities.
Tracks due diligence status for the given provider.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to related party.</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Due Diligences</relationshipLabel>
        <relationshipName>DueDiligences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>The status captured for the due diligence record.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceType</valueSetName>
        </valueSet>
    </fields>
    <label>Due Diligence</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Due Diligences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Employment__c.object
<CustomObject>
    <description>Captures employment information of the applicant. Employment is a relationship between two parties, usually based on a contract where work is paid for, where one party, which may be a corporation, for profit, not-for-profit organization, co-operative or other entity is the employer and the other is the employee.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to party object</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Employments</relationshipLabel>
        <relationshipName>Employments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the employment</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__EmploymentType</valueSetName>
        </valueSet>
    </fields>
    <label>Employment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Employment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Identification__c.object
<CustomObject>
    <description>Identification details of the party such as  driver license numbers, passport numbers .  Supports capture of identity document id as well which is stored as an attachment in the system.</description>
    <fields>
        <fullName>tffa__BackPhotoId__c</fullName>
        <description>Identifier of the back photo document persisted in the system against the identity document.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>BackPhotoId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__FrontPhotoId__c</fullName>
        <description>Identifier of the front photo attachment document persisted in the system against the identity document.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FrontPhotoId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to the parent party object</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Identifications</relationshipLabel>
        <relationshipName>Identifications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>The kind of document that was examined to verify identity of the applicant. A driver&apos;s license is an example of an identity document.. The name will be defaulted to the name field</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__IdentificationType</valueSetName>
        </valueSet>
    </fields>
    <label>Identification</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Identification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Identifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/tffa__Party__c.object
<CustomObject>
    <description>A party is an individual or a legal entity  who own or apply  for certain services/products in the bank. 
A party can be an existing customer of the bank or a new prospect.</description>
    <fields>
        <fullName>CZMDMPartyID__c</fullName>
        <description>MDM Global Id</description>
        <encryptionScheme>None</encryptionScheme>
        <label>MDM Global ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Number__c</fullName>
        <description>Customer number a unique identifier for customer on core banking</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FISDob__c</fullName>
        <description>Date of Birth stored in Fis</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS Birth date</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FISLastName__c</fullName>
        <description>LastName stored in Fis</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FIS LastName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsAuthenticatedCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is Authenticated Customer</description>
        <label>Authenticated Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsCrossCharterCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Is CrossCharter Customer</description>
        <inlineHelpText>If the customer is not having an existing realtionship with this charter but has a relationship in another charter.</inlineHelpText>
        <label>CrossCharter Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsExceptionPlanRequired__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is Exception Plan Required</description>
        <inlineHelpText>Exception plan is not required to be set for new accounts for existing customers who have transactional accounts older than 30 days.</inlineHelpText>
        <label>ExceptionPlan Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsKYCRequired__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is KYC Required</description>
        <inlineHelpText>For authenticated customers, Is KYC required to be done?</inlineHelpText>
        <label>KYC Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsOLBEnrolled__c</fullName>
        <description>Status of customer&apos;s online banking enrollment Y = Yes , N = No and F = Failure while checking</description>
        <label>IsOLBEnrolled</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
                <value>
                    <fullName>F</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__IDAStatus__c</fullName>
        <description>A rollup of status across DueDiligence(s) of type IDA.</description>
        <label>IDA status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__DueDiligenceStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__IsExistingCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the current applicant is existing customer of the bank.</description>
        <label>IsExistingCustomer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__IsMinor__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the Individual is minor by law. Default is false</description>
        <label>Is Minor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Product__c.object
<CustomObject>
    <description>A financial product serves as a template and framework  for the financial account or service.</description>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <defaultValue>&quot;PRODUCT&quot;</defaultValue>
        <description>Type of product, which determines its behavior in the application. e.g. BUNDLE, PRODUCT</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ProductType</valueSetName>
        </valueSet>
    </fields>
    <label>Financial Product</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__SubmissionPartyXref__c.object
<CustomObject>
    <description>An individual or a legal entity which is applying for certain services/products in the bank. An applicant exists only in the context of a submission.</description>
    <fields>
        <fullName>tffa__Party__c</fullName>
        <description>Reference to Party object @managed</description>
        <label>Party</label>
        <referenceTo>tffa__Party__c</referenceTo>
        <relationshipLabel>Submissions</relationshipLabel>
        <relationshipName>Submissions</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <description>Reference to parent submission object.</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Parties</relationshipLabel>
        <relationshipName>PartyXrefs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>tffa__Type__c</fullName>
        <description>Type of the party. Allowed values are - INDIVIDUAL, ORGANIZATION</description>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__PartyType</valueSetName>
        </valueSet>
    </fields>
    <label>Submission Party</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Submission Parties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/tffa__DueDiligenceStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PASSED</fullName>
        <label>✅Passed</label>
    </customValue>
    <customValue>
        <fullName>DECLINED</fullName>
        <label>❌Declined</label>
    </customValue>
    <customValue>
        <fullName>FAILED</fullName>
        <label>❌Failed</label>
    </customValue>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <label>🔶In progress</label>
    </customValue>
    <customValue>
        <fullName>CHALLENGED</fullName>
        <label>⚠️Challenged</label>
    </customValue>
    <customValue>
        <fullName>REVIEW</fullName>
        <label>⚠️Review</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>❌Expired</label>
    </customValue>
    <description>States of a due diligence activity.</description>
    <masterLabel>DueDiligenceStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__DueDiligenceType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IDV</fullName>
    </customValue>
    <customValue>
        <fullName>CDD</fullName>
    </customValue>
    <customValue>
        <fullName>FRAUD</fullName>
        <label>Fraud</label>
    </customValue>
    <customValue>
        <fullName>OFAC</fullName>
    </customValue>
    <customValue>
        <fullName>QUALIFILE</fullName>
        <label>QualiFile</label>
    </customValue>
    <customValue>
        <fullName>IDA</fullName>
    </customValue>
    <customValue>
        <fullName>CREDIT_BUREAU</fullName>
        <label>Credit Bureau</label>
    </customValue>
    <customValue>
        <fullName>DEBIT_BUREAU</fullName>
        <label>Debit Bureau</label>
    </customValue>
    <description>Types of due diligences</description>
    <masterLabel>DueDiligenceType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__EmploymentType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>SALARIED</fullName>
        <label>Salaried</label>
    </customValue>
    <customValue>
        <fullName>CONTRACTOR</fullName>
        <label>Contractor</label>
    </customValue>
    <customValue>
        <fullName>SELF_EMPLOYED</fullName>
        <label>Self employed</label>
    </customValue>
    <customValue>
        <fullName>FULLTIME</fullName>
        <label>Full Time</label>
    </customValue>
    <customValue>
        <fullName>PARTTIME</fullName>
        <label>Part Time</label>
    </customValue>
    <customValue>
        <fullName>RETIRED</fullName>
        <label>Retired</label>
    </customValue>
    <customValue>
        <fullName>STUDENT</fullName>
        <label>Student</label>
    </customValue>
    <customValue>
        <fullName>HOMEMAKER</fullName>
        <label>Homemaker</label>
    </customValue>
    <customValue>
        <fullName>UNEMPLOYED</fullName>
        <label>Unemployed</label>
    </customValue>
    <customValue>
        <fullName>MILITARY</fullName>
        <label>Military</label>
    </customValue>
    <customValue>
        <fullName>Test</fullName>
        <isActive>false</isActive>
        <label>Test</label>
    </customValue>
    <description>Type of the employment, Valid values are SALARIED,CONTRACTOR,SELF_EMPLOYED,RETIRED,STUDENT,UNEMPLOYED,MILITARY</description>
    <masterLabel>EmploymentType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__IdentificationType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>DL</fullName>
        <label>Drivers License</label>
    </customValue>
    <customValue>
        <fullName>StateID</fullName>
        <label>State ID</label>
    </customValue>
    <customValue>
        <fullName>Passport</fullName>
    </customValue>
    <customValue>
        <fullName>StudentID</fullName>
        <label>Student ID with Photo - under 18 only</label>
    </customValue>
    <customValue>
        <fullName>Minor</fullName>
    </customValue>
    <customValue>
        <fullName>MilitaryID</fullName>
        <label>Military ID</label>
    </customValue>
    <customValue>
        <fullName>ASSUMED_NAME_CERT</fullName>
        <label>Assumed Name Certificate</label>
    </customValue>
    <customValue>
        <fullName>NONE</fullName>
        <label>None</label>
    </customValue>
    <customValue>
        <fullName>CERT_OF_FORMATION</fullName>
        <label>Certificate of Formation</label>
    </customValue>
    <customValue>
        <fullName>ARTICLES_OF_INCORPORATION</fullName>
        <label>Articles of Incorporation</label>
    </customValue>
    <customValue>
        <fullName>CERT_OF_LIMITED_PARTNERSHIP</fullName>
        <label>Certificate of Limited Partnership</label>
    </customValue>
    <customValue>
        <fullName>BUSINESS_LICENSE</fullName>
        <label>Business License</label>
    </customValue>
    <customValue>
        <fullName>GreenCard</fullName>
        <label>Green Card</label>
    </customValue>
    <customValue>
        <fullName>ForeignPassport</fullName>
        <label>FOREIGN PASSPORT</label>
    </customValue>
    <customValue>
        <fullName>ResidentAlienCard</fullName>
        <label>RESIDENT ALIEN CARD</label>
    </customValue>
    <customValue>
        <fullName>Matricula</fullName>
        <label>MATRICULA</label>
    </customValue>
    <customValue>
        <fullName>USImmigrationVisa</fullName>
        <label>US IMMIGRATION VISA</label>
    </customValue>
    <description>The list of supported identification type for a party</description>
    <masterLabel>IdentificationType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__PartyType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>INDIVIDUAL</fullName>
        <label>Individual</label>
    </customValue>
    <customValue>
        <fullName>ORGANIZATION</fullName>
        <label>Organization</label>
    </customValue>
    <description>Type of the party</description>
    <masterLabel>PartyType</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__ProductType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>PRODUCT</fullName>
        <label>Product</label>
    </customValue>
    <customValue>
        <fullName>BUNDLE</fullName>
        <label>Bundle</label>
    </customValue>
    <description>Type of product, which determines its behavior in the application. e.g. Product - standard product, Bundle - Product that groups multiple products together</description>
    <masterLabel>ProductType</masterLabel>
</GlobalValueSet>

classes/CZWTFCIDAServiceProvider.cls
/**
 * Copyright (c) 2020 Terafina Inc
 * @group  Provider
 * @description Override the package default functionalities for due diligence
 **/

global with sharing class CZWTFCIDAServiceProvider extends tffa.DueDiligenceServiceProvider {
  /**
   * @description
   * @param tffa__Party__c partyObj
   * @param Map<String Object> params
   * @return List<tffa__Party__c>
   **/
  private List<tffa__Application__c> apps;
  global override List<tffa__Party__c> verify(List<tffa__Party__c> parties, Map<String, Object> params) {
    /*  tffa.Logger.debug('In CZWTFCIDAServiceProvider Verify');
    Boolean skipDSS = false;
    Boolean saveIDA = false;
    Boolean saveVerifyIDA = false;
    Boolean saveIDV = false;
    Boolean isStudent = false;
    Boolean doIDV = false;
    Boolean isStudProd = false;
    Boolean isAuthKycRequired = false;

    FISIDAResponseDTO idaResp;
    FISIDVResponseDTO idvResp;

    List<tffa__Party__c> partyList;
    List<tffa__Party__c> partyDetailList = new List<tffa__Party__c>();
    List<String> ids = new List<String>();
    tffa__DueDiligence__c dueDiligenceVerify;

    try {
      FISCCIntegrationLogService.setSubmissionObj((String) params.get('Submission__c'));

      if (parties[0].tffa__DueDiligences__r != null && !parties[0].tffa__DueDiligences__r.isEmpty()) {
        for (tffa__DueDiligence__c dd : parties[0].tffa__DueDiligences__r) {
          if (dd.tffa__Type__c.equals('IDA')) {
            dueDiligenceVerify = dd;
          }
        }
      }

      for (tffa__Party__c party : parties) {
        ids.add(party.Id);
      }

      parties = CZWTFCPartyRepository.findAllPartiesByIds(ids);
      FISCCIntegrationLogService.setIntegrationLog(
        (String) params.get('Submission__c'),
        parties[0].Name +
        '-' +
        FISCCIntegrationConstants.CUSTOMER_API_INQUIRES
      );
      FISCCIntegrationLogService.setCurrentLog(parties[0].Name + '-' + FISCCIntegrationConstants.CUSTOMER_API_INQUIRES);

      if (parties[0].tffa__IDAStatus__c == null || !parties[0].tffa__IDAStatus__c.equalsIgnoreCase('CHALLENGED')) {
        if (!parties[0].IsAuthenticatedCustomer__c) {
          parties[0].tffa__IsExistingCustomer__c = false;
          parties[0].IsCrossCharterCustomer__c = false;
          parties[0].IsExceptionPlanRequired__c = true;
          parties[0].Customer_Number__c = '';
          parties[0].CZMDMPartyID__c = '';
          parties[0].IsOLBEnrolled__c = 'F';
          parties[0].FISDob__c = '';
          parties[0].FISLastName__c = '';
          parties[0] = searchCustomerInMDM(parties[0]);
        }

        if (parties[0].tffa__IsExistingCustomer__c) {
          parties[0] = FISCCDepositOriginationExtension.fetchContactEffDate(parties[0]);
          parties[0] = FISCCDepositOriginationExtension.FetchCustomerInfo(parties[0]);
        }

        /*FISCCCustomerSearchTaxnbrProvider.processSearchByTaxbr((String) params.get('Submission__c'), parties[0]);
        //FISCCIntegrationLogService.setLogOk(FISCCIntegrationConstants.SEARCH_CUSTOMER);

        if (parties[0].tffa__IsExistingCustomer__c) {
          FISCCIntegrationLogService.setLogItemOk(FISCCIntegrationConstants.SEARCH_CUSTOMER);
        } else {
          FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.SEARCH_CUSTOMER);
        }*

        for (tffa__Party__c party : parties) {
          if ((party.tffa__IsExistingCustomer__c || party.IsCrossCharterCustomer__c) && !party.IsAuthenticatedCustomer__c) {
            try {
              CZWTFCIntegrationLogService.setCurrentLogItem(FISCCIntegrationConstants.OLB_CHECK, parties[0].name, true);
              if (CZWTFCOLBEnrollmentCheckService.checkIfOLBIsEnrolled(party.CZMDMPartyID__c)) {
                party.IsOLBEnrolled__c = 'Y';
                CZWTFCIntegrationLogService.setLogItemOk(FISCCIntegrationConstants.OLB_CHECK);
              } else {
                party.IsOLBEnrolled__c = 'N';
                CZWTFCIntegrationLogService.setLogItemOk(FISCCIntegrationConstants.OLB_CHECK);
              }
            } catch (Exception ex) {
              tffa.Logger.error('In IDA Service Provider OLB ' + ex.getMessage() + ' ' + ex.getStackTraceString());
              party.IsOLBEnrolled__c = 'F';
              CZWTFCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.OLB_CHECK);
            }
          }
          // party.tffa__IDAStatus__c = 'PASSED';
        }
      }

      //--------------------------------------FIS DSS------------------------------------------------------------//
      tffa.Logger.debug('Processing DSS');

      tffa__Party__c detailedParty = CZWTFCPartyRepository.findByIdWithChildObjects(parties[0].Id);
      tffa__Employment__c emp = CZWTFCPartyRepository.findEmploymentByPartyID(detailedParty.Id);
      tffa__Submission__c sub = CZWTFCSubmissionRepository.findSubWithProdById(detailedParty.Id);
      tffa__SubmissionPartyXref__c subParty = CZWTFCPartyRepository.findSubPartyById(detailedParty.Id);
      Boolean idUploaded = false;

      if (
        detailedParty.tffa__Identifications__r != null &&
        detailedParty.tffa__Identifications__r.size() > 0 &&
        detailedParty.tffa__Identifications__r[0] != null
      ) {
        if (
          !String.isBlank(detailedParty.tffa__Identifications__r[0].tffa__FrontPhotoId__c) ||
          !String.isBlank(detailedParty.tffa__Identifications__r[0].tffa__BackPhotoId__c)
        ) {
          idUploaded = true;
        }
      }

      detailedParty.tffa__IsExistingCustomer__c = parties[0].tffa__IsExistingCustomer__c;
      detailedParty.Customer_Number__c = parties[0].Customer_Number__c;
      detailedParty.IsOLBEnrolled__c = parties[0].IsOLBEnrolled__c;
      detailedParty.FISDob__c = parties[0].FISDob__c;
      detailedParty.FISLastName__c = parties[0].FISLastName__c;
      detailedParty.IsCrossCharterCustomer__c = parties[0].IsCrossCharterCustomer__c;
      detailedParty.IsExceptionPlanRequired__c = parties[0].IsExceptionPlanRequired__c;
      detailedParty.CZMDMPartyID__c = parties[0].CZMDMPartyID__c;
      detailedParty.CZFisHomeNbr__c = parties[0].CZFisHomeNbr__c;
      detailedParty.CZFisWorkNbr__c = parties[0].CZFisWorkNbr__c;
      detailedParty.CZFisCellNbr__c = parties[0].CZFisCellNbr__c;
      detailedParty.CZFisEmail__c = parties[0].CZFisEmail__c;
      detailedParty.CZFisCustCodes__c = parties[0].CZFisCustCodes__c;
      detailedParty.CZFisHomeNbrEffDt__c = parties[0].CZFisHomeNbrEffDt__c;
      detailedParty.CZFisWorkNbrEffDt__c = parties[0].CZFisWorkNbrEffDt__c;
      detailedParty.CZFisCellNbrEffDt__c = parties[0].CZFisCellNbrEffDt__c;
      detailedParty.CZFisEmailEffDt__c = parties[0].CZFisEmailEffDt__c;

      if (detailedParty.tffa__isMinor__c || (detailedParty.IsAuthenticatedCustomer__c && !detailedParty.IsKYCRequired__c)) {
        skipDSS = true;
      }

      //to check if it's a cust/stud product
      if (!skipDSS && sub.tffa__Applications__r != null) {
        for (tffa__Application__c app : sub.tffa__Applications__r) {
          if (app.tffa__Product__r.IsCustodianProduct__c && subParty.tffa__Primary__c) {
            skipDSS = true;
          }
          if (app.tffa__Product__r.IsStudentProduct__c) {
            isStudProd = true;
          }
        }
      }

      if (!skipDSS) {
        if (
          emp != null &&
          emp.tffa__Type__c != null &&
          emp.tffa__Type__c.equalsIgnoreCase('STUDENT') &&
          isStudProd &&
          subParty.tffa__Primary__c
        ) {
          isStudent = true;
          doIDV = true;
        }

        if (detailedParty.IsAuthenticatedCustomer__c && detailedParty.IsKYCRequired__c) {
          doIDV = true;
          isAuthKycRequired = true;
        }
      }

      if (
        !skipDSS &&
        !isStudent &&
        !isAuthKycRequired &&
        (String.isBlank(detailedParty.tffa__IDAStatus__c) || !detailedParty.tffa__IDAStatus__c.equalsIgnoreCase('CHALLENGED'))
      ) {
        FISCCIntegrationLogService.setCurrentLogItem(FISCCIntegrationConstants.FETCH_OOW_QUESTIONS, parties[0].name, true);
        idaResp = FISIDAProvider.fetchOOWQuestions(detailedParty);
        saveIDA = true;
        if (idaResp == null) {
          saveIDA = false;
          detailedParty.IsDobMatch__c = false;
          detailedParty.IsSsnMatch__c = false;
          detailedParty.tffa__IDAStatus__c = 'FAILED';
          if (idUploaded) {
            doIDV = true;
          }
          FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.FETCH_OOW_QUESTIONS);
          FISCCIntegrationLogService.setLogItemMessage(FISCCIntegrationConstants.FETCH_OOW_QUESTIONS_FAILURE);
        } else {
          if (idaResp.errorCd != null && !String.isBlank(idaResp.errorCd)) {
            if (idUploaded) {
              doIDV = true;
            }
            FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.FETCH_OOW_QUESTIONS);
            FISCCIntegrationLogService.setLogItemMessage(FISCCIntegrationConstants.FETCH_OOW_QUESTIONS_FAILURE);
          } else if (idaResp.idaQuestion1 == null) {
            saveIDA = false;
            detailedParty.IsDobMatch__c = false;
            detailedParty.IsSsnMatch__c = false;
            if (idUploaded) {
              doIDV = true;
            }
            detailedParty.tffa__IDAStatus__c = 'FAILED';
            FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.FETCH_OOW_QUESTIONS);
            FISCCIntegrationLogService.setLogItemMessage(FISCCIntegrationConstants.FETCH_OOW_QUESTIONS_FAILURE);
          } else {
            FISCCIntegrationLogService.setLogItemOk(
              FISCCIntegrationConstants.FETCH_OOW_QUESTIONS,
              FISCCIntegrationConstants.FETCH_OOW_QUESTIONS_SUCCESS
            );
          }
        }
        tffa.Logger.debug('In CZWTFCIDAServiceProvider Verify CheckPoint One');
      } else if (!skipDSS && !isStudent && !isAuthKycRequired && detailedParty.tffa__IDAStatus__c.equalsIgnoreCase('CHALLENGED')) {
        FISCCIntegrationLogService.setCurrentLogItem(FISCCIntegrationConstants.VERIFY_OOW_QUESTIONS, parties[0].name, true);
        idaResp = FISIDAProvider.verifyOOWQuestions(detailedParty, dueDiligenceVerify);
        FISCCIntegrationLogService.setLogItemOk(
          FISCCIntegrationConstants.VERIFY_OOW_QUESTIONS,
          FISCCIntegrationConstants.VERIFY_OOW_QUESTIONS_SUCCESS
        );

        saveVerifyIDA = true;
        if (idaResp != null && idaResp.decision != null) {
          if (idaResp.decision.equalsIgnoreCase('Pass') || idUploaded) {
            doIDV = true;
          }
        } else {
          saveVerifyIDA = false;
          detailedParty.IsDobMatch__c = false;
          detailedParty.IsSsnMatch__c = false;
          detailedParty.tffa__OFACStatus__c = 'FAILED';
          detailedParty.tffa__DebitBureauStatus__c = 'FAILED';
          detailedParty.tffa__IDVStatus__c = 'FAILED';
          detailedParty.tffa__IDAStatus__c = 'FAILED';
          FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.VERIFY_OOW_QUESTIONS);
          FISCCIntegrationLogService.setLogItemMessage(FISCCIntegrationConstants.VERIFY_OOW_QUESTIONS_FAILURE);
        }
      }

      if (skipDSS) {
        detailedParty.IsDobMatch__c = true;
        detailedParty.IsSsnMatch__c = true;
        detailedParty.tffa__OFACStatus__c = 'PASSED';
        detailedParty.tffa__DebitBureauStatus__c = 'PASSED';
        detailedParty.tffa__IDVStatus__c = 'PASSED';
        detailedParty.tffa__IDAStatus__c = 'PASSED';
      }

      if (isStudent || isAuthKycRequired) {
        detailedParty.tffa__IDAStatus__c = 'PASSED';
      }

      tffa.Logger.debug('In CZWTFCIDAServiceProvider Verify CheckPoint Two');
      if (!skipDSS && doIDV) {
        FISCCIntegrationLogService.setCurrentLogItem(FISCCIntegrationConstants.DO_IDV_VERIFICATION, parties[0].name, true);
        idvResp = FISIDVProvider.doIdentityVerification(detailedParty);
        FISCCIntegrationLogService.setLogItemOk(
          FISCCIntegrationConstants.DO_IDV_VERIFICATION,
          FISCCIntegrationConstants.DO_IDV_VERIFICATION_SUCCESS
        );

        saveIDV = true;
        if (idvResp == null) {
          saveIDV = false;
          FISCCIntegrationLogService.setLogItemFailed(FISCCIntegrationConstants.DO_IDV_VERIFICATION);
          FISCCIntegrationLogService.setLogItemMessage(FISCCIntegrationConstants.DO_IDV_VERIFICATION_FAILURE);
        }
      }

      if (saveIDA) {
        FISDSSService.removeExistingDueDiligence(detailedParty, new List<String>{ 'IDA', 'IDV', 'DEBIT_BUREAU', 'OFAC' });

        // try{
        //   CZWTFCHelperRepository.deleteContentDocument(FISDSSService.qualifyReportName('idv_report.html',detailedParty));
        // }catch(Exception){
        //   tffa.Logger.debug('Exception in Delete Existing IDV Report Document '+ex.getMessage()+' '+ex.getStackTraceString());
        // }

        detailedParty = FISDSSService.upsertDueDiligence(detailedParty, idaResp);
      }

      if (saveVerifyIDA) {
        tffa__DueDiligence__c dueDiligence;
        List<tffa__DueDiligence__c> ddList = CZWTFCHelperRepository.getDueDiligenceList(detailedParty.Id);
        if (detailedParty.tffa__IDAStatus__c.equals('CHALLENGED') && ddList != null) {
          for (tffa__DueDiligence__c dd : ddList) {
            if (dd.tffa__Type__c.equals('IDA')) {
              dueDiligence = dd;
            }
          }
        }
        detailedParty = FISDSSService.doAnswersCheckAndBuildDD(detailedParty, idaResp, dueDiligence);
      }

      if (saveIDV) {
        FISDSSService.removeExistingDueDiligence(detailedParty, new List<String>{ 'IDV', 'DEBIT_BUREAU', 'OFAC' });
        detailedParty = FISDSSService.processIDVResult(detailedParty, idvResp);
      }
      tffa.Logger.debug('Adding updated party to Party List after DSS API call');
      partyDetailList.add(detailedParty);
    } catch (Exception ex) {
      tffa.Logger.error(' Exception In IDA Service Provider FIS DSS ' + ex.getMessage() + ' ' + ex.getStackTraceString());
      partyDetailList = parties;
    } finally {
      FISCCIntegrationLogService.persistIntegationLogs();
    }

    CZWTFCPartyRepository.save(partyDetailList);
    //fetch without dd
    tffa__party__c updatedPartyObj = CZWTFCPartyRepository.findByIdWithChildObjs(partyDetailList[0].Id);
    List<tffa__DueDiligence__c> updatedDDList = CZWTFCHelperRepository.getDueDiligenceList(updatedPartyObj.Id);
    tffa.SObjectAssembler asm = new tffa.SObjectAssembler(updatedPartyObj);
    asm.addChildObjects('DueDiligences__r', updatedDDList);
    partyDetailList.clear();
    partyDetailList.add((tffa__Party__c) asm.assemble());*/
    return parties;
  }

  public static tffa__Party__c searchCustomerInMDM(tffa__Party__c partyObj) {
    /* tffa.Logger.debug('Search Cust in MDM');
    try {
      Map<String, String> params = new Map<String, String>();
      params.put('lstNme', partyObj.tffa__LastName__c);
      params.put('ssnNmb', partyObj.tffa__NationalIdentifierValue__c);
      params.put('brandCode', partyObj.tffa__BrandCode__c);
      params.put('authType', 'ind-3');
      params.put('method', 'CUSTOMER_SEARCH');
      CZWTFCAuthResponse authResp = CZWTFCAuthenticationService.verifyUser(params);
      tffa.Logger.debug('authResp ' + authResp);
      if (String.isNotBlank(authResp.status) && authResp.status.equalsIgnoreCase('success')) {
        if (String.isNotBlank(authResp.custInfo.CISNumber)) {
          partyObj.tffa__IsExistingCustomer__c = authResp.custInfo.IsExistingCustomer;
          partyObj.Customer_Number__c = authResp.custInfo.CISNumber;
        }
        partyObj.IsCrossCharterCustomer__c = authResp.custInfo.IsCrossCharterCustomer;
        partyObj.IsExceptionPlanRequired__c = authResp.custInfo.IsExceptionPlanRequired;
        partyObj.CZMDMPartyID__c = authResp.globalCustomerId;
        partyObj.FISDob__c = authResp.custInfo.DateOfBirth;
        partyObj.FISLastName__c = authResp.custInfo.LastName;
      }
    } catch (Exception ex) {
      tffa.Logger.error(' Exception In IDA Service Provider searchCustomerInMDM ' + ex.getMessage() + ' ' + ex.getStackTraceString());
    }*/
    return partyObj;
  }
}