objects/tffa__Application__c.object
<CustomObject>
    <description>Submission can have multiple applications  based on number of products selected. An application will have product specific attributes which will eventually result into an account. Used to store account specific information like Acount Number, Routing Number, Loan Amount, Credit Limit, Vehicle Year, Vehicle make, vehicle model, as well as mortgage and home equity related information.</description>
    <fields>
        <fullName>AccountOpeningStatus__c</fullName>
        <description>Account Opening Status</description>
        <inlineHelpText>This includes Customer creation, Account opening, Beneficiary creation, Update customer missing information,Account funding, Funding hold</inlineHelpText>
        <label>Account Opening Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ApplicationProcessStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>AccountPreference__c</fullName>
        <description>This includes both OD Protection and E-Statement</description>
        <inlineHelpText>This includes both OD Protection and E-Statement</inlineHelpText>
        <label>Account Preference Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ApplicationProcessStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>CZKYCOutcomeQueueName__c</fullName>
        <description>KYC Outcome Queue Name</description>
        <encryptionScheme>None</encryptionScheme>
        <label>KYC Outcome Queue Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DebitCardIssuanceStatus__c</fullName>
        <description>Debit Card Issuance Status</description>
        <label>Debit Card Issuance Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>ApplicationProcessStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsAccAlreadyOpened__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to check if account has opened in current process submission call</description>
        <label>IsCurrentIterAccOpen</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsRoutingRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to check if routing and mail event needs to be triggered from batch for an application</description>
        <label>Is Routing Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>tffa__Score__c</fullName>
        <description>A calculated figure that can help the financial institution make effective automated decisions about the application. e.g. for abandoned applications it can influence the order in which the applications get picked up for followup (high score ones are picked first).</description>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the application</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__ApplicationStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>tffa__Submission__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Reference to Submission object @parent</description>
        <label>Submission</label>
        <referenceTo>tffa__Submission__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/tffa__Submission__c.object
<CustomObject>
    <description>Submission  is a collection of products which the party or group of parties wish to apply for. Models a group of applications of related product and services applied for together.</description>
    <fields>
        <fullName>tffa__Status__c</fullName>
        <description>Indicates current status of the submission</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>tffa__SubmissionStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Submission</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/ApplicationProcessStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>SUCCESS</fullName>
    </customValue>
    <customValue>
        <fullName>FAILURE</fullName>
    </customValue>
    <customValue>
        <fullName>PENDING</fullName>
        <default>true</default>
        <label>PENDING</label>
    </customValue>
    <customValue>
        <fullName>NA</fullName>
        <label>Not Applicable</label>
    </customValue>
    <description>Application Process Status.</description>
    <masterLabel>ApplicationProcessStatus</masterLabel>
</GlobalValueSet>

globalValueSets/tffa__SubmissionStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>IN_PROGRESS</fullName>
        <default>true</default>
        <label>In Progress</label>
    </customValue>
    <customValue>
        <fullName>ABANDONED</fullName>
        <label>Abandoned</label>
    </customValue>
    <customValue>
        <fullName>CANCELLED</fullName>
        <label>Cancelled</label>
    </customValue>
    <customValue>
        <fullName>SAVED</fullName>
        <label>Saved</label>
    </customValue>
    <customValue>
        <fullName>SUBMITTED</fullName>
        <label>Submitted</label>
    </customValue>
    <customValue>
        <fullName>EXPIRED</fullName>
        <label>Expired</label>
    </customValue>
    <customValue>
        <fullName>COMPLETED</fullName>
        <label>Completed</label>
    </customValue>
    <description>Indicates current status of the submission.This will be computed and be useful for regulations.</description>
    <masterLabel>SubmissionStatus</masterLabel>
</GlobalValueSet>

classes/CZWTFCAppRoutingService.cls
public with sharing class CZWTFCAppRoutingService implements Queueable {
  private tffa__Application__c applicationObject;
  public CZWTFCAppRoutingService(tffa__Application__c appObject) {
    this.applicationObject = appObject;
    tffa.Logger.debug('CZWTFCAppRoutingService called for : ' + appObject.Id);
  }

  public void execute(QueueableContext context) {
    routeApplicationAndRaiseEvent(applicationObject);
  }

  public static void routeApplicationAndRaiseEvent(tffa__Application__c appObj) {
    try {
      appObj = routeApplication(appObj);
      appObj.IsRoutingRequired__c = false;
      if (
        (appObj.tffa__Status__c.equals(CZWTFCConstants.ACCOUNT_OPENED) || appObj.tffa__Status__c.equals(CZWTFCConstants.FUNDED)) &&
        !appObj.IsAccAlreadyOpened__c
      ) {
        (new CZWTFCApplicationEventExtension()).post(appObj);
      }
      if (appObj != null) {
        FISCCObjectManagerRepository.doUpsertApplications(new List<tffa__Application__c>{ appObj });
      }
    } catch (Exception ex) {
      tffa.Logger.error('Exception  :::' + ex.getMessage() + 'LineNumber  :::' + ex.getStackTraceString());
    }
  }

  public static tffa__Application__c routeApplication(tffa__Application__c appObj) {
    // if (CZWTFCConstants.PROCESS_STATUS_FAILURE.equals(appObj.AccountPreference__c)) {
    //   appObj.tffa__Score__c = FISCCApplicationConstants.ESTMT_REGN_FAILED_CODE;
    // } else if (CZWTFCConstants.PROCESS_STATUS_FAILURE.equals(appObj.DebitCardIssuanceStatus__c)) {
    //   appObj.tffa__Score__c = FISCCApplicationConstants.DEBIT_ISSUANCE_FAILED_CODE;
    // } else if (CZWTFCConstants.PROCESS_STATUS_FAILURE.equals(appObj.AccountOpeningStatus__c)) {
    //   appObj.tffa__Score__c = FISCCApplicationConstants.ACC_OPENING_FAILED_CODE;
    // } else if (
    //   (appObj.tffa__Status__c.equals(CZWTFCConstants.ACCOUNT_OPENED) || appObj.tffa__Status__c.equals(CZWTFCConstants.FUNDED)) &&
    //   (appObj.DebitCardIssuanceStatus__c.equals('PENDING') ||
    //   appObj.AccountPreference__c.equals('PENDING') ||
    //   appObj.DebitCardIssuanceStatus__c.equals('PENDING'))
    // ) {
    //   appObj.tffa__Score__c = FISCCApplicationConstants.IN_PROGRESS_APPLICATION;
    // } else if ((appObj.tffa__Status__c.equals(CZWTFCConstants.ACCOUNT_OPENED) || appObj.tffa__Status__c.equals(CZWTFCConstants.FUNDED))) {
    //   appObj.tffa__Score__c = FISCCApplicationConstants.APPLICATION_PROCESSING_COMPLETED;
    // }
    tffa__Submission__c submission = CZWTFCSubmissionRepository.findSubmissionById(appObj.tffa__Submission__c);
    Map<String, Object> facts = new Map<String, Object>();
    facts.put('AccountOpeningStatus__c', appObj.AccountOpeningStatus__c);
    facts.put('DebitCardIssuanceStatus__c', appObj.DebitCardIssuanceStatus__c);
    facts.put('AccountPreference__c', appObj.AccountPreference__c);
    facts.put('tffa__StatusSet__c', appObj.tffa__Status__c);

    if (String.isNotBlank(appObj.CZKYCOutcomeQueueName__c)) {
      facts.put('CZKYCOutcomeQueueName__c', appObj.CZKYCOutcomeQueueName__c);
    }

    tffa.ApplicationAssigner appAssigner = new tffa.ApplicationAssigner();
    List<tffa__Application__c> appObjList = appAssigner.assign(new List<tffa__Application__c>{ appObj }, facts);
    if (appObjList != null && appObjList.size() > 0)
      return appObjList.get(0);
    else
      return appObj;
  }
}