objects/User.object
<CustomObject>
    <fields>
        <fullName>WT_Referrals_Type__c</fullName>
        <description>Additional Referral Type</description>
        <label>Referral Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chicago Deferred Exchange</fullName>
                </value>
                <value>
                    <fullName>Commercial Banking</fullName>
                </value>
                <value>
                    <fullName>Community Advantage</fullName>
                </value>
                <value>
                    <fullName>Community Impact</fullName>
                </value>
                <value>
                    <fullName>Consumer Lending</fullName>
                </value>
                <value>
                    <fullName>Corporate Credit Card</fullName>
                </value>
                <value>
                    <fullName>CRE</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Leasing</fullName>
                </value>
                <value>
                    <fullName>Merchant Processing</fullName>
                </value>
                <value>
                    <fullName>Other Referral</fullName>
                </value>
                <value>
                    <fullName>Platinum Adventures</fullName>
                </value>
                <value>
                    <fullName>Retail Banking</fullName>
                </value>
                <value>
                    <fullName>SBA</fullName>
                </value>
                <value>
                    <fullName>Small Business Lending</fullName>
                </value>
                <value>
                    <fullName>Swaps/Derivatives</fullName>
                </value>
                <value>
                    <fullName>Testing &amp; Training Referral</fullName>
                </value>
                <value>
                    <fullName>TMIS - Treasury Management Inside Sales</fullName>
                </value>
                <value>
                    <fullName>Wintrust Wealth Management</fullName>
                </value>
                <value>
                    <fullName>Private Client Group</fullName>
                </value>
                <value>
                    <fullName>Wintrust Mortgage</fullName>
                </value>
                <value>
                    <fullName>Wintrust Receivables Finance</fullName>
                </value>
                <value>
                    <fullName>Wealth Services</fullName>
                    <isActive>false</isActive>
                    <label>Wealth Services</label>
                </value>
                <value>
                    <fullName>Wealth – Chicago Trust</fullName>
                    <isActive>false</isActive>
                    <label>Wealth – Chicago Trust</label>
                </value>
                <value>
                    <fullName>Wealth – Corporate Plan Services</fullName>
                    <isActive>false</isActive>
                    <label>Wealth – Corporate Plan Services</label>
                </value>
                <value>
                    <fullName>Wealth – Great Lakes Advisors</fullName>
                    <isActive>false</isActive>
                    <label>Wealth – Great Lakes Advisors</label>
                </value>
                <value>
                    <fullName>Wealth – Wayne Hummer Investments</fullName>
                    <isActive>false</isActive>
                    <label>Wealth – Wayne Hummer Investments</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/WT_User_Branch_Factor_Lookup__c.object
<CustomObject>
    <description>Junction Object looking up the user Object and BF(Branch Factor ) object.</description>
    <fields>
        <fullName>WT_Branch_Factor__c</fullName>
        <description>Branch Factor Lookup on User Branch Factor Object</description>
        <label>Branch Factor</label>
        <referenceTo>WT_Business_Unit_Entity__c</referenceTo>
        <relationshipLabel>Users Branch Factor Lookup</relationshipLabel>
        <relationshipName>Users_Branch_Factor_Lookup</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WT_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User Object Lookup on User Branch Factor Junction Object</description>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Users_Branch_Factor_Lookup</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Branch Factor Lookup</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>User Branch Factor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Users Branch Factor Lookup</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/WT_ReferralNewOverrideController.cls
/**
* --------------------------------------------------------------------------------------------------------------
* @Name				WT_ReferralNewOverrideController
* @Author			Swaminathan E	<SEzhumal@wintrust.com>
* @ModifiedBy		Vasavi K	<vkolusu@wintrust.com>
* @Version			v1.0
* @CreatedDate		30-11-2020
* @UsedBy			Lead Object
* --------------------------------------------------------------------------------------------------------------
* @Description
* This is controller class for Override the New Button on Referral Records.
* This handles based on RecordType, Prepopulate value on Referral Records.
* --------------------------------------------------------------------------------------------------------------
* @Changes
* v2.0
* 05-31-2022
* --------------------------------------------------------------------------------------------------------------
**/
// Code Coverage: WT_ReferralNewOverrideController_T
public without sharing class WT_ReferralNewOverrideController 
{
    /**
*-----------------------------------------------------------------------------------------------------------------------------
* @description
*This method auto populate default value on Referral Records.
*-----------------------------------------------------------------------------------------------------------------------------
**/
    @AuraEnabled(cacheable=true)
    public static Map<String,Id> getPrePopulateValue()
    {     
        List<Schema.RecordTypeInfo> listRecordType = Lead.SObjectType.getDescribe().getRecordTypeInfos();
        Map<String ,Id> mapRecordType = new Map<String ,Id>(); 
        Id currentUserId =  UserInfo.getUserId();
        for(Schema.RecordTypeInfo recordType : listRecordType )
        {
            if(recordType.isAvailable() && recordType.Name != 'Master')
            {
                mapRecordType.put(recordType.Name,recordType.getRecordTypeId());
            }
        }
        mapRecordType.put('CurrentUser',currentUserId);
        Id businessUnitRecordId = populateBusinessReferralUnit(currentUserId);
        if(businessUnitRecordId != null)
        {
            mapRecordType.put('BUId',businessUnitRecordId);
        }
        return mapRecordType;
    }
    /**
*-----------------------------------------------------------------------------------------------------------------------------
* @description
*This method get Branch Factor Id on Referral record based on Referredby selected.
*-----------------------------------------------------------------------------------------------------------------------------
* @param    userId   This contains User Id.
*-----------------------------------------------------------------------------------------------------------------------------
**/    
    @AuraEnabled
    public static Id populateBusinessReferralUnit(Id userId)
    {       
        List<WT_User_Branch_Factor_Lookup__c> businessUnitRecord = [SELECT Id, WT_Branch_Factor__c, WT_User__c FROM WT_User_Branch_Factor_Lookup__c WHERE WT_User__c = : userId Limit 1];
        if(businessUnitRecord.size() > 0)
        {
            return businessUnitRecord[0].WT_Branch_Factor__c;
        }
        else
        {
            return null;
        }
    }
    /**
*-----------------------------------------------------------------------------------------------------------------------------
* @description
*This method get Name on Referral record based on Account Referred selected.
*-----------------------------------------------------------------------------------------------------------------------------
* @param    referredAccountId   This contains Account Referred Id.
*-----------------------------------------------------------------------------------------------------------------------------
**/
    @AuraEnabled
    public static Account populateName(Id referredAccountId)
    {
        Account accountRecord = [SELECT Id, Name, FirstName, MiddleName, LastName ,RecordType.Name FROM Account WHERE Id = :referredAccountId];
        if(!accountRecord.RecordType.Name.contains('Person'))
        {
            accountRecord.LastName = accountRecord.Name;
        }
        return  accountRecord;
    }
    /**
*-----------------------------------------------------------------------------------------------------------------------------
* @description
*This method get User records based on Referral Type selected.
*-----------------------------------------------------------------------------------------------------------------------------
* @param    searchKey   This contains search value.
* @param    objectName   This contains Object-Api-Name.
* @param    filterValue   This contains filter value.
*-----------------------------------------------------------------------------------------------------------------------------
**/
    @AuraEnabled(cacheable=true)  
    public static List<sobject> findRecords(String searchKey, String objectName, String filterValue) 
    {  
        string searchText = '\'' + String.escapeSingleQuotes(searchKey) + '%\'';  
        objectName = String.escapeSingleQuotes(objectName);
        filterValue = String.escapeSingleQuotes(filterValue);
        string query = 'SELECT Id,Phone,Name,WT_Referrals_Type__c  FROM ' +objectName+ ' WHERE Name LIKE '+searchText+' AND WT_Referrals_Type__c includes '+'(\''+filterValue+'\')'+' LIMIT 6';           
        if(String.isNotBlank(objectName) && objectName.toLowerCase() == 'user' && filterValue!=''  && filterValue != null)
        {
            query = 'SELECT Id,Phone,Name,WT_Referrals_Type__c FROM ' +objectName+ ' WHERE IsActive = true AND Name LIKE '+searchText+'AND WT_Referrals_Type__c!=null AND WT_Referrals_Type__c includes '+'(\''+filterValue+'\')'+' LIMIT 6';
        } 
        else
        { 
            query = 'SELECT Id,Phone,Name,WT_Referrals_Type__c FROM ' +objectName+ ' WHERE IsActive = true AND WT_Referrals_Type__c!=null AND Name LIKE '+searchText+' LIMIT 6';
        } 
        return Database.query(query);  
    }  
}