objects/WT_Activity_Extension__c.object
<CustomObject>
    <description>To store TM Call Records</description>
    <fields>
        <fullName>WT_Account_Activity_As_Initially_Said__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Account activity same as initially said?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Any_Changes_Over_Last_60_Days__c</fullName>
        <description>Created as a part of DBSFCRM-852</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Any changes over the last 60 days?</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WT_Are_Fees_Set_Up_Correctly__c</fullName>
        <description>Created as a part of DBSFCRM-852</description>
        <label>Are the fees set up correctly?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Dashboard_Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Dashboard Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Did_You_Customize_DB_Views_Panels__c</fullName>
        <label>Did you customize DB, views &amp; panels?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Digital_Products_Comments__c</fullName>
        <description>Created as a part of DBSFCRM-852</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Digital Products Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WT_Doc_Timeline_Satisfact__c</fullName>
        <description>Created as a part of DBSFCRM-852</description>
        <label>Documentation timeline satisfactory?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Document_Comments__c</fullName>
        <description>Created as apart of DBSFCRM-852</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Document Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WT_Easy_To_Use_Our_Digital_Products__c</fullName>
        <description>Created as a part of DBSFCRM-852</description>
        <label>Is it easy to use our digital products?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_EventId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>EventId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Favorite_Dashboard_Panel__c</fullName>
        <description>Created as a part of DBSFCRM-852</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Favorite Dashboard Panel</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WT_Fees_Comments__c</fullName>
        <description>Created as a part of DBSFCRM-852</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Fees Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>WT_How_Would_You_Rate_Training__c</fullName>
        <description>Created as a part of DBSFCRM-852</description>
        <label>How would you rate the training?</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Other_Products_Services_To_Discuss__c</fullName>
        <description>Created as a part of DBSFCRM-852</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Other products &amp; services to discuss?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Record_Type_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Type Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_TM_Onboarding_Call__c</fullName>
        <description>This field is created to check whether the activity created is for 14 Days or for 60 Days</description>
        <label>TM Onboarding Call</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>14 Days</fullName>
                </value>
                <value>
                    <fullName>60 Days</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_TaskId__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>TaskId</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Training_Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Training Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_What_Can_We_Improve_On__c</fullName>
        <description>Created as a part of DBSFCRM-852</description>
        <encryptionScheme>None</encryptionScheme>
        <label>What can we improve on?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_What_Did_We_Do_Really_Well__c</fullName>
        <description>Created as a part of DBSFCRM-852</description>
        <encryptionScheme>None</encryptionScheme>
        <label>What did we do really well?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_What_Do_We_Need_To_Improve_Upon__c</fullName>
        <description>Created as a part of DBSFCRM-852</description>
        <encryptionScheme>None</encryptionScheme>
        <label>What do we need to improve upon?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_What_Has_Improved_Since_We_Last_Spoke__c</fullName>
        <description>Created as a part of DBSFCRM-852</description>
        <encryptionScheme>None</encryptionScheme>
        <label>What has improved since we last spoke?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Activity Extension</label>
    <nameField>
        <displayFormat>TM Call-{0000}</displayFormat>
        <label>Activity TM Call Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Extensions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_ActivityExtensionController.cls
/**
* --------------------------------------------------------------------------------------------------------------
* @Name             WT_ActivityExtensionController
* @Author           Anoop           <abattini@wintrust.com>
* @ModifiedBy       Swaminathan E   <SEzhumal@wintrust.com>
* @Version          v1.0
* @CreatedDate      15-02-2021
* @UsedBy           Task Object
* --------------------------------------------------------------------------------------------------------------
* @Description
* This is controller class to create Activity Extension records
* --------------------------------------------------------------------------------------------------------------
* @Changes
* v1.0
* 04-23-2021
* --------------------------------------------------------------------------------------------------------------
**/
// Code Coverage: WT_ActivityExtensionController_T
public class WT_ActivityExtensionController
{
/**
*-----------------------------------------------------------------------------------------------------------------------------
* @description
* This method auto populate default value on Task TM Call Records.
*-----------------------------------------------------------------------------------------------------------------------------
**/   
    @AuraEnabled
    public static String fetchRecordTypeID(String recordTypeName)
    {
        RecordType recordType = [SELECT id, DeveloperName FROM recordType Where DeveloperName =: recordTypeName and SobjectType = 'WT_Activity_Extension__c'];
        return recordType.id;
    }        
    @AuraEnabled
    public static Id updateTask(Id activityExtensionId,Id taskId) {
        WT_Activity_Extension__c activityExtension = new WT_Activity_Extension__c();
        activityExtension = [Select Id, WT_Doc_Timeline_Satisfact__c, WT_How_Would_You_Rate_Training__c, WT_Easy_To_Use_Our_Digital_Products__c,
                             WT_Did_You_Customize_DB_Views_Panels__c, WT_Favorite_Dashboard_Panel__c, WT_What_Do_We_Need_To_Improve_Upon__c,
                             WT_Document_Comments__c, WT_Training_Comments__c, WT_Digital_Products_Comments__c, WT_Dashboard_Comments__c,
                             WT_What_Did_We_Do_Really_Well__c, WT_Are_Fees_Set_Up_Correctly__c, WT_Other_Products_Services_To_Discuss__c, 
                             WT_Any_Changes_Over_Last_60_Days__c, WT_What_Can_We_Improve_On__c, WT_Fees_Comments__c, 
                             WT_Account_Activity_As_Initially_Said__c, WT_What_Has_Improved_Since_We_Last_Spoke__c, 
                             WT_TM_Onboarding_Call__c from WT_Activity_Extension__c where id =:activityExtensionId];
        if(activityExtension != null)
        {
            //if WT_TM_Onboarding_Call__c = 14 Days, all the 60 days field values should be null
            if(activityExtension.WT_TM_Onboarding_Call__c == '14 Days')
            {
                activityExtension.WT_Are_Fees_Set_Up_Correctly__c = '';
                activityExtension.WT_Other_Products_Services_To_Discuss__c = '';
                activityExtension.WT_Any_Changes_Over_Last_60_Days__c = '';
                activityExtension.WT_What_Can_We_Improve_On__c = '';
                activityExtension.WT_Fees_Comments__c = '' ;
                activityExtension.WT_Account_Activity_As_Initially_Said__c = '';
                activityExtension.WT_What_Has_Improved_Since_We_Last_Spoke__c = '';
            }
            
            //if WT_TM_Onboarding_Call__c = 60 Days, all the 14 days field values should be null
            if(activityExtension.WT_TM_Onboarding_Call__c == '60 Days')
            {
                activityExtension.WT_Doc_Timeline_Satisfact__c = '';
                activityExtension.WT_How_Would_You_Rate_Training__c = '';
                activityExtension.WT_Easy_To_Use_Our_Digital_Products__c = '';
                activityExtension.WT_Did_You_Customize_DB_Views_Panels__c = '';
                activityExtension.WT_Favorite_Dashboard_Panel__c = '';
                activityExtension.WT_What_Do_We_Need_To_Improve_Upon__c = '' ;
                activityExtension.WT_Document_Comments__c = '';
                activityExtension.WT_Training_Comments__c = '';
                activityExtension.WT_Digital_Products_Comments__c = '';
                activityExtension.WT_Dashboard_Comments__c = '';
                activityExtension.WT_What_Did_We_Do_Really_Well__c = '';
            }
            update activityExtension;
        }        
        return null;
    }    
    @AuraEnabled
    public static WT_Activity_Extension__c returnTaskDetails(Id taskRecordId)
    {
        WT_Activity_Extension__c returnRecord = null;
        if(taskRecordId != null )
        {
            List<WT_Activity_Extension__c> listActivityExtension = [SELECT Id, WT_TaskId__c, WT_Record_Type_Name__c, WT_TM_Onboarding_Call__c 
                                                                    FROM WT_Activity_Extension__c 
                                                                    WHERE WT_TaskId__c =:taskRecordId];
            
            if(!listActivityExtension.isEmpty() && listActivityExtension.size() > 0)
            {
                returnRecord = listActivityExtension[0];
            }
        }
        return returnRecord;      
    }
    @AuraEnabled
    public static WT_Activity_Extension__c returnEventDetails(String eventRecordId)
    {
        WT_Activity_Extension__c returnRecord = null;
        if(eventRecordId != null )
        {
            List<WT_Activity_Extension__c> listActivityExtension = [SELECT Id, WT_EventId__c, WT_Record_Type_Name__c 
                                                                    FROM WT_Activity_Extension__c 
                                                                    WHERE WT_EventId__c =:eventRecordId];
            
            if(!listActivityExtension.isEmpty() && listActivityExtension.size() > 0)
            {
                returnRecord = listActivityExtension[0];
            }
        }
        return returnRecord;   
    }    
}