objects/WT_Contact_Center_Link__c.object
<CustomObject>
    <description>Contact Center External Links</description>
    <fields>
        <fullName>WT_Category__c</fullName>
        <label>Category</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FXD Links</fullName>
                </value>
                <value>
                    <fullName>Vision Content Links</fullName>
                </value>
                <value>
                    <fullName>Universal Links</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Icon__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Icon</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_SortOrder__c</fullName>
        <label>SortOrder</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WT_Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>InActive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WT_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Title</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>URL</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Contact Center Link</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Center Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_ContactCenterLinksHelper_T.cls
/**
* -------------------------------------------------------------------------------------------------------------------------------------------------
* @Name         WT_ContactCenterLinksHelper_T
* @Author       Venkatareddy Somireddy
* @version      v1.0 
* @CreatedDate  02-24-2021
* ---------------------------------------------------------------------------------------------------------------------------------------------------
* @Description 
* This Class is used as test class for WT_ContactCenterLinksHelper
* ---------------------------------------------------------------------------------------------------------------------------------------------------
* @Changes
* v1.1				Venkatareddy Somireddy
* 03-10-2021		Code Review Changes done.
* ----------------------------------------------------------------------------------------------------------------------------------------------------
**/
@isTest
public class WT_ContactCenterLinksHelper_T {
     @isTest static void getUniversalLinks_Test()
    {
        Test.startTest();
        List<WT_Contact_Center_Link__c> listUniversalLinks = WT_ContactCenterLinksHelper.getUniversalLinks();        

        List<WT_Contact_Center_Link__c> listUniversalLinksUpdated = [SELECT WT_Title__c,WT_Category__c,WT_URL__c,WT_Icon__c,WT_SortOrder__c 
                                                                from WT_Contact_Center_Link__c 
                                                                where WT_Category__c='Universal Links' AND WT_Status__c ='Active' order by WT_SortOrder__c];

        System.debug('UniversalLinks List Count-' + listUniversalLinks.size()); 
        System.assertEquals(listUniversalLinks.size(), listUniversalLinksUpdated.size());        
        Test.stopTest();
    }

    @isTest static void getFXDLinks_Test()
    {
        Test.startTest();
        List<WT_Contact_Center_Link__c> listFXDLinks = WT_ContactCenterLinksHelper.getFXDLinks();        

        List<WT_Contact_Center_Link__c> listFXDLinksUpdated = [SELECT WT_Title__c,WT_Category__c,WT_URL__c,WT_Icon__c,WT_SortOrder__c 
                                                            from WT_Contact_Center_Link__c 
                                                            where WT_Category__c='FXD Links' AND WT_Status__c ='Active' order by WT_SortOrder__c];

        System.debug('FXDLinks List Count-' + listFXDLinks.size()); 
        System.assertEquals(listFXDLinks.size(), listFXDLinksUpdated.size());
        Test.stopTest();     
    }

    @isTest static void getVisionContentLinks_Test()
    {
        Test.startTest();
        List<WT_Contact_Center_Link__c> listVisionContentLinks = WT_ContactCenterLinksHelper.getVisionContentLinks();        

        List<WT_Contact_Center_Link__c> listVisionContentLinksUpdated = [SELECT WT_Title__c,WT_Category__c,WT_URL__c,WT_Icon__c,WT_SortOrder__c 
                                                                    from WT_Contact_Center_Link__c 
                                                                    where WT_Category__c='Vision Content Links' AND WT_Status__c ='Active' order by WT_SortOrder__c];

        System.debug('UniversalLinks List Count-' + listVisionContentLinks.size()); 
        System.assertEquals(listVisionContentLinks.size(), listVisionContentLinksUpdated.size());         
        Test.stopTest();
    }
}