objects/WT_CI_Funding_History__c.object
<CustomObject>
    <fields>
        <fullName>WT_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CI Funding Histories (Account)</relationshipLabel>
        <relationshipName>CI_Funding_Histories1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>WT_Date_of_Payment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date of Payment</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WT_Funding_Amount__c</fullName>
        <label>Funding Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>WT_Split_Payment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Split Payment</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CI Funding History</label>
    <nameField>
        <displayFormat>CI-{0000000000}</displayFormat>
        <label>CI Funding History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CI Funding Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/WT_CIFundingController.cls
/* ----------------------------------------------------------
* @Name             WT_CIFundingController
* @Author           Vamshi Papisetty
* @ModifiedBy       Vamshi Papisetty    <vpapiset@wintrust.com>
* @Version          v1.0
* @CreatedDate      08/31/2022          
* Code Coverage: WT_CIFundingController_T
* The is Apex Controller for wT_CIFundingDetailNiche Component
* @Changes v2.0
* ---------------------------------------------------------*/
public class WT_CIFundingController 
{
        @AuraEnabled(cacheable=true)        
        public static List<WT_CI_Funding_History__c> getFundingList(String accountId)
        { 
            return
            [SELECT Id, WT_Funding_Amount__c, WT_Date_of_Payment__c, WT_Split_Payment__c,WT_Account__c, CreatedById FROM WT_CI_Funding_History__c 
             WHERE WT_Account__c =:accountId ORDER by CreatedDate desc LIMIT 5];
         }        
}