objects/WT_Exception_Log__c.object
<CustomObject>
    <fields>
        <fullName>WT_Class_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Exception__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Exception</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>WT_Method_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Record_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Exception Log</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Exception Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_ExceptionLogHelper.cls
public without sharing class WT_ExceptionLogHelper 
{
    public static void LogException(String recordId, String className, String methodName,
                                    String dmlException)
    {
        List<WT_Exception_Log__c> listExceptionLogToInsert = new List<WT_Exception_Log__c>();
        WT_Exception_Log__c newLog = new WT_Exception_Log__c();
        newLog.WT_Record_Id__c = recordId;
        newLog.WT_Class_Name__c = className;
        newLog.WT_Method_Name__c = methodName;
        newLog.WT_Exception__c = dmlException;

        listExceptionLogToInsert.add(newLog);
        Database.insert(listExceptionLogToInsert, false);
    }   
}