objects/WT_FAQ_Customer_Support__c.object
<CustomObject>
    <fields>
        <fullName>WT_Bank_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Customer_Support_Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Customer Support Phone</label>
        <type>Phone</type>
    </fields>
    <label>FAQ Customer Support</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>FAQ Customer Support Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FAQ Customer Support</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_FAQCustomerSupportController_T.cls
@isTest
public class WT_FAQCustomerSupportController_T 
{
	@testSetup
    static void Setup()
    {
        WT_FAQ_Customer_Support__c newCustomerSupport = new WT_FAQ_Customer_Support__c();
        newCustomerSupport.WT_Bank_Name__c = 'Test';
        newCustomerSupport.WT_Customer_Support_Phone__c = '5555555555';
        
        insert newCustomerSupport;
    }
    
    @isTest
    static void TestGetCustomerSupportInformation()
    {
        Test.startTest();
        WT_FAQCustomerSupportController.GetCustomerSupportInformation();
        Test.stopTest();
    }
}