objects/WT_Goal__c.object
<CustomObject>
    <description>Object to hold all the goals assigned to any given user in the system</description>
    <fields>
        <fullName>WT_Actual__c</fullName>
        <label>Actual</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WT_Date_From__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WT_Date_Last_In_Progress_Rolled_Up__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Rolled Up Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WT_Date_To__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>WT_Goal_Metric__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Metric</label>
        <referenceTo>WT_Goal_Metric__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Goal_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Goal Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_In_Progress__c</fullName>
        <label>In-Progress</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WT_Parent_Goal__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Goal</label>
        <referenceTo>WT_Goal__c</referenceTo>
        <relationshipLabel>Goals</relationshipLabel>
        <relationshipName>Goals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WT_Percentage_Achieved__c</fullName>
        <label>Percentage To Goal</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>WT_Run_Rate_To_Goal__c</fullName>
        <label>Run Rate To Goal</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>WT_Target__c</fullName>
        <label>Target</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Goal</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/WT_Goal_Metric__c.object
<CustomObject>
    <description>Re-usable metric that can be assigned to multiple Goals</description>
    <label>Goal Metric</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Goal Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_IndividualGoalBatch.cls
/**
* --------------------------------------------------------------------------------------------------------------
* @Name             WT_IndividualGoalBatch
* @Author           Krupa Chinthakindi
* @Version          v1.0
* @CreatedDate      01-03-2022
* @UsedBy      
* -----------------------------------------------------------------------------------------------------------------------------
* @Description      This batch is used to process all the Goal Records and 
                    send an email to the CRMSupport team if there are any failed records.
------------------------------------------------------------------------------------------------------------------------------------------
**/

global class WT_IndividualGoalBatch implements Database.Batchable<sObject>, Database.stateful {
    
    List<String> errors = new List<String>();
   
    global Database.QueryLocator start(Database.BatchableContext BC) {
        // collect the batches of records or objects to be passed to execute
        String query = 'SELECT Id,WT_Goal_Metric__c,WT_Date_From__c,WT_Goal_Owner__c,WT_Run_Rate_To_Goal__c,WT_Date_To__c,WT_Target__c,WT_Date_Last_In_Progress_Rolled_Up__c,LastModifiedDate,WT_Percentage_Achieved__c,WT_Actual__c,WT_In_Progress__c FROM WT_Goal__c Order By WT_Parent_Goal__c DESC NULLS LAST';
        return Database.getQueryLocator(query);
    }
        // This method collects the failed records from WT_GoalPopulationLogic.
    global void execute(Database.BatchableContext BC, List<WT_Goal__c> scope) {
       
        List<Id> goalIdLst = new List<Id>();
        for(WT_Goal__c gl : scope){
            goalIdLst.add(gl.Id);
        }
        if(goalIdLst.size()>0 || !goalIdLst.isEmpty()){
            system.debug('goalIdLst'+goalIdLst);
            List<String> errLst = WT_GoalPopulationLogic.updateGoal(goalIdLst);
            if(errLst != null && errLst.size() > 0) errors.addAll(errLst);
            system.debug('errors**'+errors);
        }
    }   
        // This method is to send error list to the support team.
    global void finish(Database.BatchableContext BC) {
        
        system.debug('errorsFinish**'+errors);
        String htmlBody = '';
        htmlBody = '<br></br><table border="1" style="border-collapse: collapse"><tr><th>RecordIDs</th></tr>';
        for(String ers: errors){
            String recordIDs = ers;
            htmlBody += '<tr><td>' + recordIDs + '</td></tr>';
        }
        
        if(!errors.isEmpty()){
            String toaddressList = System.Label.WT_Goal_UserEmailIDs;
            String[] toaddressSplit = toaddressList.split(',');
            String[] toAddress = toaddressSplit;
            system.debug('toAddress'+toAddress);
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setToAddresses(toAddress);
            mail.setSubject('GoalRecords ' + 'Failed');
            Integer numberOfErros = errors.size();
            String  messageBody =  'There are '+ numberOfErros +' Failed Records.';
            messageBody += htmlBody;
            mail.setHtmlBody(messageBody);
            Messaging.Email[] emails = new Messaging.Email[]{mail};
            Messaging.sendEmail(emails);
            
        }

    }

}