objects/WT_Household_Relation_To_Process_Log__c.object
<CustomObject>
    <fields>
        <fullName>WT_Contact_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contact Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WT_Date_Added__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Added</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WT_Household_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Household Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Household Relation To Process Log</label>
    <nameField>
        <displayFormat>H-{0000000}</displayFormat>
        <label>Household Relation To Process Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Household Relation To Process Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WT_AccountContactRelationAfterHandler.cls
/**
* @Name             WT_AccountContactRelationAfterHandler 
* @Author           
* @ModifiedBy
* @Version          v1.0
* @CreatedDate      16-FEB-2021
* @UsedBy           WT_AccountContactTrigger
* ---------------------------------------------------------------------------------------------------------------------------------------------------
* @Description 
* this is used by trigger WT_AccountContactTrigger
*  --------------------------------------------------------------------------------------------------------------
* @Changes
* --------------------------------------------------------------------------------------------------------------
**/
// Code Coverage: WT_AccountContactRelationAfterHandler_T
public class WT_AccountContactRelationAfterHandler extends TriggerHandler
{    
    private List<AccountContactRelation> listNewAccountContactRelation = new List<AccountContactRelation>();
    private Map<Id, AccountContactRelation> mapNewAccountContactRelationIdAndAccountContactRelation = new Map<Id, AccountContactRelation>();
    private Map<Id, AccountContactRelation> mapOldAccountContactRelationIdAndAccountContactRelation = new Map<Id, AccountContactRelation>();
    //constructor   
    public WT_AccountContactRelationAfterHandler()
    {
        if(trigger.isUpdate || trigger.isInsert)
        {
            this.listNewAccountContactRelation = (List<AccountContactRelation>) Trigger.new;
            this.mapNewAccountContactRelationIdAndAccountContactRelation = (Map<Id, AccountContactRelation>) Trigger.newMap;
            this.mapOldAccountContactRelationIdAndAccountContactRelation = (Map<Id, AccountContactRelation>) Trigger.oldMap;
        }
        if(trigger.isDelete)
        {
            this.mapOldAccountContactRelationIdAndAccountContactRelation = (Map<Id, AccountContactRelation>) Trigger.oldMap;
        }
    }
    public override void afterUpdate()
    { 
        AddHouseholdRelationToProcessLog(false);
    }
    public override void afterInsert()
    {
        AddHouseholdRelationToProcessLog(true);
    }
    public override void afterDelete()
    { 
        AddHouseholdRelationToProcessLog(false);
    }    
    
    private void AddHouseholdRelationToProcessLog(Boolean isInsert)
    {
        List<WT_Household_Relation_To_Process_Log__c> listLogToInsert = new List<WT_Household_Relation_To_Process_Log__c>();
        List<AccountContactRelation> listAccountContactRelationToProcess = new List<AccountContactRelation>();
        if(isInsert)
        {
            listAccountContactRelationToProcess.addAll(listNewAccountContactRelation);
        }
        else
        {
            listAccountContactRelationToProcess.addAll(mapOldAccountContactRelationIdAndAccountContactRelation.values());
        }
        
        if(!listAccountContactRelationToProcess.isEmpty())
        {
            for(AccountContactRelation accountContactRelationToProcess : listAccountContactRelationToProcess)
            {
                WT_Household_Relation_To_Process_Log__c newLog = new WT_Household_Relation_To_Process_Log__c();
                newLog.WT_Contact_Id__c = accountContactRelationToProcess.ContactId;
                newLog.WT_Household_Id__c = accountContactRelationToProcess.AccountId;
                newLog.WT_Date_Added__c = System.now();
                
                listLogToInsert.add(newLog);
            }
        }
        
        if(!listLogToInsert.isEmpty())
        {
            insert listLogToInsert;
        }
    }
}